### PR TITLE
Add azure public ip label

### PR DESCRIPTION
**Pull request by EarthmanT**
Add a public IP label to Azure config

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add a DCO and update the docs?

**Comment by EarthmanT** [comment]
> Can you add a DCO and update the docs?

Added Docs and rebased with DCO.

**Comment by brian-brazil** [comment]
That's failing to build. Are you sure you've the right field name?

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
