### PR TITLE
promql: Test errors aren't always ParseErr

### PR DESCRIPTION
**Pull request by brian-brazil**

### CODE REVIEW

**Comment by fabxc** [comment]
This refers to the "unexpected error" introduced yesterday, I suppose?

:+1:

**Comment by brian-brazil** [comment]
This predates it I think, it comes up when with the fuzz input is used in testdata.

**Comment by fabxc** [comment]
When going through the `Parser.errorf?` functions it should always be a parse error (except for the "unexpected error"). If not, that's worth checking.

What exactly are you referring to?

**Comment by brian-brazil** [comment]
`parser.recover` returns an `error`, `test.go` was expecting any errors to always be a `ParseErr`.

**Pull request merged**
