### PR TITLE
Fixup sighup for P2 TSDB init #2699

### LINKED ISSUE #2699: Prometheus 2: sighup not handled gracefully during initialization phase
**What did you do?**
Ran P2 from checkout https://github.com/prometheus/prometheus/commit/ff0ee264aea5ac7f8b757433e226c0e4c708cf52.
We have an external job that SIGHUPs prometheus when config reloads. There is a potential race condition between the first SIGHUP and prometheus being ready. That bug was fixed in P1, but seems to be back in P2.

**What did you see instead? Under which circumstances?**

```
2017-05-09T14:00:15.768151000Z 2017/05/09 14:00:15 dinit: pid 37 finished: [/prometheus/prometheus -config.file=/prometheus.yml -log.level=info -query.staleness-delta=60s -query.max-concurrency=100 -query.timeout=2m -storage.local.path=/prometheus-data -storage.tsdb.appendable-blocks=2 -storage.tsdb.max-block-duration=36h -storage.tsdb.min-block-duration=2h -storage.tsdb.retention=360h -storage.tsdb.no-lockfile=true -web.external-url=http://hubmon2.h-te1.internal.improbable.io:9090/] with error: signal: hangup
```

The `error: signal: hangup` shouldn't happen.  Note: this is *after* Prometheus starts with an existing volume and existing data, so the issue may be in the code initializing the TSDB.

@fabxc

### PR DESCRIPTION
**Pull request by mwitkow**
Fixes #2699 potentialy. Waiting to verify.

### CODE REVIEW

**Comment by mwitkow** [comment]
@fabxc this fixes our TSDB initialization problem.

**Comment by fabxc** [comment]
👍 if it solves the problem.

**Comment by juliusv** [comment]
:+1:

**Comment by mwitkow** [comment]
can i haz merge? :)

**Pull request merged**
