### PR TITLE
[DON'T MERGE] add owners file to enable Prow benchmarks

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
This list doesn't match -team, and it'd be good not to have extra places to maintain the list of -team.

**Comment by krasi-georgiev** [comment]
This is only for some initial tests.
The filename is required by Prow to decide who can trigger benchmark tests via comments.

I think it is hard coded, but in general I agree that it is a good idea to maintain a single file so will think best way to handle this.

**Comment by krasi-georgiev** [comment]
maybe we can't change it so that when someone requests /benchmark.... Prow will make a request to check the repo members and if the commenter is also a repo member it will trigger a new job.

**Pull request closed without merging**
