### PR TITLE
add flush cmd in tsdbcli

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

Since readonly db already supported flush https://github.com/prometheus/prometheus/pull/6006, it is nice to have this feature in tsdbcli.

### CODE REVIEW

**Comment by brian-brazil** [comment]
You can already access this by taking a snapshot.

**Comment by yeya24** [comment]
Oh, I miss that. But I guess these two are still a little different? Flush only creates a new block from the WAL but snapshot API also links the existing blocks.

**Comment by krasi-georgiev** [comment]
@yeya24 Could you describe the use case that requires this?

**Comment by yeya24** [comment]
@krasi-georgiev  This would be useful to https://github.com/thanos-io/thanos/issues/1849, just creating a block without losing the data in WAL.

**Comment by krasi-georgiev** [comment]
if thas is the case why implement in the tsdb cli and not in the thanos sidecar?

**Pull request closed without merging**
