### PR TITLE
tsdbv2: experimantal storage.Storage implementation

### PR DESCRIPTION
**Pull request by gernest**
This commit adds a disk based alternantive implementation of of `tsdb`.It is based on roaring bitmap  index found on [Featurebase](https://github.com/FeatureBaseDB/featurebase) formerly `pilosa`, on top of [Pebble](https://github.com/cockroachdb/pebble) key value store.

Key properties

- Multi tenant
- Disk based
- Sharded
- Order less ingestion ( samples and  exemplars can be appended in any order)
- Designed to handle open telemetry workloads. This includes removing all restrictions like label  size for exemplars etc. Fully open telemetry samples are ingested and queried without restriction.
- Efficient and fast high cardinality series handling. Care has been taken to ensure, from storage perspective live or stale series have no difference, each series is lowevered into a low cardinality bit, which is used by the index throughout the lifetime of the series.

This is initial implementation, focus is to be correct and have feature parity with `tsdb`. There is no way to know if this is better or worse than `tsdb` yet, I havent ran benchmarks. The idea is theoretically sound, but eventually we will have to test to see the results.

The end goal is to be a drop in replacement for `tsdb`.

Currently it is just a draft, I will remove the draft status when I am able  to replace tsdb in `util/teststorage` package.

**Maintainers**: Please ignore this, I am publishing it so that I won't lose focus. This is 2 weeks work  from idea to implementation. There is a long road ahead for it to be ready for review.

### CODE REVIEW

**Comment by bwplotka** [comment]
Wow this looks like a huge effort! Feel free to keep this PR(s) open and to experiment. We could run our macrobenchmark once tests are passing too to help with the efficiency comparisons 💪🏽 It's definitely amazing to keep experimenting and innovate in this area, let us know how we can help!

Generally it would be epic to also understand the foundational requirements and design for new TSDB storage changes, if you plan is to replace current TSDB or allow a different TSDB mode. You can do that in the form of [the proposal](https://github.com/prometheus/proposals) if you want. Also note that the current TSDB is called "2.0" historically (see the official [docs](https://prometheus.io/docs/prometheus/latest/storage/) and the [original presentation](https://promcon.io/2017-munich/slides/storing-16-bytes-at-scale.pdf)), (just to avoid confusion).

Finally, we discussed internally to experimenting with an Arrow/Parquet based TSDB one day, which is yet another option.

**Comment by bboreham** [comment]
FYI there was a previous attempt to use Roaring Bitmaps in #7617

**Comment by gernest** [comment]
> FYI there was a previous attempt to use Roaring Bitmaps in #7617

@bboreham 

This is a complete separate implementation of `tsdb`. Roaring Bitmaps used here store
data in dirrerent encodings depending on cardinality.

For instance if you want to store an array `[ 5, 6, 7, 8]` together with its indices
`[0 , 1,  2, 3]`. Remember we have to encode position with values for each column so that 
columns can be processed independent of each other.

In tabular 

index| 0| 1| 2| 3
-----|--|--|--|--
value| 5| 6| 7| 8

Since values are of low cardinality, they will be encoded into following slice of `uint64`

```
[0 1048577 2097154 3145731]
```

Adding these values to a roaring bitmap, creates a `2D` mapping in such away that values ` 5, 6 ...` will be pointing to container keys and  container values will have respective indices.

So, basically we can answer questions like 

In which indices does the value `6` appear ?

By 

- Convert 6 into container position
- Seek to the container position
- Read the container

The container will have all indices in which value  `6` appeared. whish in our case is `[1]`

Note that all this is sharded into `1<<20` records groups, so roughly a million records per container, provided they are of low cardinality.

We benefit from all selling points of roaring bitmaps, we use low bits sequences so normally values generated will result into shrinking containers i.e `array => bitmaps => run`  containers.

Massive sample  ingestion will always lead to a lot of run containers. A full run container is `5 bytes`. So with each compaction and more data ingested the store will get more efficient.

I have so much to learn on this regard, and I have no math background so I might be wrong with my interpretation.

I just studied pilose implementation for almost 3 years, I applied my learings to web analytics events by creating [vince](https://github.com/vinceanalytics/vince) which has survived Hacker News hug of death on a commodity `6$`  vultr instance with only `1% vCPU` used , the bill was `3$` which was for the badwidth.

Thanks for the positive feedback, I will keep hacking and learning  and we will  see how this goes.

**Comment by gernest** [comment]
My bad, I thought experimenting on public will keep me focused, It has negative effect instead. I am completely lost, will have to go back to hacking locally.

I will reopen a new PR when I have something worth reviewing.

**Pull request closed without merging**
