### PR TITLE
Update minimum Go version

### PR DESCRIPTION
**Pull request by SuperQ**
Update minimum required Go version to 1.16 due to use of standard
library package `io/fs`.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Ci will need update as well, we shall test tsdb with go 1.16

**Comment by LeviHarrison** [comment]
So these were the 1.16 errors I mentioned in Slack. As you can see, they don't happen with 1.17.

```shell
➜  prometheus git:(main) go1.16 build ./cmd/prometheus
# sigs.k8s.io/json/internal/golang/encoding/json
/home/levi/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
/home/levi/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
➜  prometheus git:(main) go build ./cmd/prometheus
➜  prometheus git:(main) go1.16 version
go version go1.16 linux/amd64
➜  prometheus git:(main) go version
go version go1.17.5 linux/amd64
```

**Comment by SuperQ** [comment]
@LeviHarrison Maybe we should rollback the k8s version dependencies so we don't require the latest-latest Go version there.

**Comment by SuperQ** [comment]
I updated the test so it attempts a simple `make build` on the oldest supported Go version.

**Comment by LeviHarrison** [comment]
> Maybe we should rollback the k8s version dependencies so we don't require the latest-latest Go version there.

Sure, I guess it helps ease the transition for library consumers.

**Review by LeviHarrison — APPROVED** [review]
LGTM. And thanks to @aramcodz for pointing this out.

We should be wary that Dependabot will probably try to update the k8s dependencies again.

**Comment by SuperQ** [comment]
Yea, we can put the dependabot PR on hold with a note that it needs to wait for 1.18 at least.

**Comment by LeviHarrison** [comment]
Aaaaaand there we go https://github.com/prometheus/prometheus/pull/10104

**Pull request merged**
