### PR TITLE
Merge `release-2.52` back to main

### PR DESCRIPTION
**Pull request by ArthurSens**

### CODE REVIEW

**Comment by ArthurSens** [comment]
Hmmm, I wasn't expecting conflicts in the changelog file...

Not sure if I should be adding extra commits to the release branch to fix this 🤔

**Comment by Nexucis** [comment]
@ArthurSens you should create a branch from the release one, resolve the conflict and then merge your branch into the main

**Comment by ArthurSens** [comment]
> @ArthurSens you should create a branch from the release one, resolve the conflict and then merge your branch into the main

I'm not sure how that would work... If I create another branch from the release branch, and then rebase on top of main to solve the conflicts, the PR will contain a lot of extra commits that are already in the main branch 🤔

**Comment by Nexucis** [comment]
1. you create a branch based on the branch "release-2.52"
2. You merge (not rebase) the main branch into yours.
3. You open a PR with your branch to main
4. You merge (not squash) the PR.

Is it clearer @ArthurSens  ?

**Pull request merged**
