### PR TITLE
Add metrics for append attempts/errors

### LINKED ISSUE #12585: Counters for sample appends
### Proposal

We just had an incident where one of our Prometheus instances was not appending any samples to storage. We manage a fleet of Prometheus with very different sizes. We could create an alert with `prometheus_tsdb_head_active_appenders == 0` but it could become noisy.

With `prometheus_tsdb_head_appends_total` and `prometheus_tsdb_head_append_errors_total`, we could create an SLO for this case and be more proactive to such failures in the future.

### PR DESCRIPTION
**Pull request by ArthurSens**
Another take to fix #12585 

Finally understood this "chained interfaces" approach 😅

### CODE REVIEW

**Comment by ArthurSens** [comment]
There are just a few things that I couldn't find yet:
* Remote-write and rule evaluation also use appenders, right? I believe they should also be wrapped with meteredAppender, but I couldn't find the right place yet
* If I'm wrapping scrape appenders, remote-write appenders and rule-evaluation appenders, the package that I've used to create/register the metrics doesn't seem appropriate... any suggestions as to where they should live?

**Comment by ArthurSens** [comment]
> There are just a few things that I couldn't find yet:
> 
> * Remote-write and rule evaluation also use appenders, right? I believe they should also be wrapped with meteredAppender, but I couldn't find the right place yet
> * If I'm wrapping scrape appenders, remote-write appenders and rule-evaluation appenders, the package that I've used to create/register the metrics doesn't seem appropriate... any suggestions as to where they should live?

maybe I should be wrapping the fanoutstorage appender also/instead? 🤔

**Comment by gouthamve** [comment]
Hi @jesusvazquez @bwplotka, could you take a look at the PR? This looks useful in general, and hopefully we can get some feedback to Arthur soon!

_We looked at this in our bug scrub._

**Comment by bboreham** [comment]
Hello from the bug-scrub!  @ArthurSens do you think you will get back to this?

**Comment by ArthurSens** [comment]
No, I don't think I'll have the time to work on this anytime soon. Closing it and thanks for the ping

**Pull request closed without merging**
