### PR TITLE
Fix `Matcher.String()` with empty label name

### PR DESCRIPTION
**Pull request by colega**
When the label name is empty, which can happen now with quoted label name, it should be quoted when printed as a string again.

### CODE REVIEW

**Comment by jesusvazquez** [comment]
Will wait for Juliens review!

**Comment by bboreham** [comment]
We already had this matcher: https://github.com/prometheus/prometheus/blob/5c6bd3c07a40f1b9095347a0df4e8cf496a5ad22/tsdb/db_test.go#L2440

Does empty name mean anything, aside from that case?

**Comment by colega** [comment]
> Does empty name mean anything, aside from that case?

I don't think it's useful, and actually we should review whether it's harmful on some paths.

**Comment by bboreham** [comment]
To clarify: do you think we should leave this PR in-place for troubleshooting purposes even though it shouldn’t happen?

**Comment by colega** [comment]
I think the PR is correctly merged: if something is a parseable PromQL matcher (and it is already), its `.String()` should yield a parseable PromQL (fixed in this PR). 

However, I think that we should disallow the empty matcher in the query endpoints because I'm afraid that it might have undesirable performance effects (matching the all postings key)

**Pull request merged**
