### PR TITLE
UI: introduce codemirror editor for local query to filter targets, service discovery

### PR DESCRIPTION
**Pull request by Nexucis**
This PR is proposing a way to write more precise and sofisticate query to filter a list of targets.

Hopefully this new query language is not so complicated to understand and the autocompletion is here to help to write query.

I'm wondering if we should put a switch somewhere to enable this thing or move back to a simple query search bar like we have today.
Today both are mixed and basically when the query translate returns nothing, then we run a simple search.

PS: I know it is ugly, I'm just opening the PR so I can share the code and open discussion around this topic.

Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

### CODE REVIEW

**Comment by Nexucis** [comment]
It looks like this for the moment:

https://user-images.githubusercontent.com/4548045/168836425-c05832da-a72a-4f58-930e-79f7620191a4.mov

**Comment by roidelapluie** [comment]
It would be awesome to be able to do lastScrapeDuration > 2

**Comment by Nexucis** [comment]
Ooooh that's a cool idea ! I didn't think about it!
Yeah we should do that @roidelapluie

**Comment by Nexucis** [comment]
@roidelapluie it is now supporting this kind of expression. 

`lastScrapeDuration > 2` will return an empty search in the current context ;).

**Comment by juliusv** [comment]
And an OSS React one: https://github.com/ukrbublik/react-awesome-query-builder

**Comment by roidelapluie** [comment]
cc @Nexucis are you still willing to work on this?

**Comment by Nexucis** [comment]
I think we can close this PR.
The packages used in this PR (with the query language) are stable now. But for the moment I don't have the time to work on a visualisation tool to abstract the query language.
If one day I'm able to provide it I will create another PR.

**Pull request closed without merging**
