### PR TITLE
Vendoring with govendor

### PR DESCRIPTION
**Pull request by fabxc**
`go get github.com/kardianos/govendor`

`GO15VENDOREXPERIMENT=1 govendor list`
`GO15VENDOREXPERIMENT=1 govendor add <mypkg>`
`GO15VENDOREXPERIMENT=1 govendor update <mypkg>`

Our Makefile currently does all sort of other things by itself, so not actually using the support of the go tool to build directly with this vendoring approach.
In turns this means with exported `GO15VENDOREXPERIMENT=1` `make` currently cannot start the tests – separate issue though.

@juliusv @beorn7 maybe check out how you like `govendor`

### CODE REVIEW

**Comment by juliusv** [comment]
Did you forget to check in the new vendor directory?

**Comment by juliusv** [comment]
Hmm, it might be GitHub just not showing everything.

**Comment by fabxc** [comment]
Yep, that's GH.

**Comment by juliusv** [comment]
<3 GitHub

**Comment by juliusv** [comment]
Ok, it has the same issue as Godeps that it only checks out exactly the directories of the packages, so if you're only using a package in a subpath of a repository (like `github.com/syndtr/goleveldb/leveldb`), it doesn't include the LICENSE files. These still need to be copied in manually.

**Comment by juliusv** [comment]
The `make format` filtering step needs to be adjusted to not only remove `Godeps`, but add `vendor`.

**Comment by juliusv** [comment]
:+1: otherwise

**Comment by fabxc** [comment]
No, I removed that on purpose. 
Why do we care if a vendored package is formatted correctly? Why would we modify vendored code like this?

**Comment by juliusv** [comment]
Exactly, we do *not* want to format it. Ergo, it needs to be filtered out.

**Comment by fabxc** [comment]
Ah, I misread that entirely, thanks.

**Pull request merged**
