### PR TITLE
Cut 2.34.0-rc.1

### PR DESCRIPTION
**Pull request by csmarchbanks**
This PR creates the second release candidate of the 2.34 series now that the remote write deadlock fix has been merged. Rather than cherry picking just that fix and risking divergence I updated to the most recent main commit so we get a couple other enhancements and bugfixes as well.

### CODE REVIEW

**Comment by csmarchbanks** [comment]
Looks like DCO is failing due to the merge commits, so not blocking.

**Review by roidelapluie — APPROVED** [review]
LGTM

**Comment by csmarchbanks** [comment]
/prombench cancel

I am going to cut another release candidate with https://github.com/prometheus/prometheus/pull/10425 so may as well not waste the resources.

**Pull request merged**
