### PR TITLE
remote-write receiver: reuse 'ref' to optimize multiple samples for same series

### PR DESCRIPTION
**Pull request by shichanglin5**

### CODE REVIEW

**Comment by bboreham** [comment]
See discussion at https://github.com/prometheus/prometheus/pull/8489#pullrequestreview-1536975348; it doesn't apply to input from Prometheus which only ever sends one sample per series, but can apply for other senders.

As a rule we ask for a benchmark to demonstrate performance improvements, but this one is fairly obvious.

**Review by bboreham — APPROVED** [review]
lgtm

**Review by bwplotka — APPROVED** [review]
Thanks - same suggestion as @bboreham - benchmark would be nice (:

**Comment by shichanglin5** [comment]
I tested it on my macbook，bench results as follows:

switch to my branch
```log
lhhdz@LHHDZ-MACBOOOK-PRO prometheus % git status
On branch reuse_ref
Your branch is up to date with 'origin-scl/reuse_ref'.

nothing to commit, working tree clean
lhhdz@LHHDZ-MACBOOOK-PRO prometheus % go build ./cmd/promtool              
lhhdz@LHHDZ-MACBOOOK-PRO prometheus % ./promtool tsdb bench write --metrics 100000 --scrapes 5000 ./tsdb/testdata/20kseries.json 
level=info ts=2023-07-20T11:43:23.278989Z caller=head.go:595 msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2023-07-20T11:43:23.279066Z caller=head.go:676 msg="On-disk memory mappable chunks replay completed" duration=12.792µs
level=info ts=2023-07-20T11:43:23.279073Z caller=head.go:684 msg="Replaying WAL, this may take a while"
level=info ts=2023-07-20T11:43:23.279599Z caller=head.go:755 msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2023-07-20T11:43:23.279617Z caller=head.go:792 msg="WAL replay completed" checkpoint_replay_duration=47.167µs wal_replay_duration=491.208µs wbl_replay_duration=42ns total_replay_duration=563.958µs
level=info ts=2023-07-20T11:43:23.280258Z caller=db.go:1786 msg="Compactions disabled"
>> start stage=readData
>> completed stage=readData duration=95.089208ms
>> start stage=ingestScrapes
ingestion completed
>> completed stage=ingestScrapes duration=4.02153575s
 > total samples: 100000000
 > samples/sec: 2.4866082933297634e+07
>> start stage=stopStorage
>> completed stage=stopStorage duration=206.86775ms
lhhdz@LHHDZ-MACBOOOK-PRO prometheus % 
```

switch to main
```log
lhhdz@LHHDZ-MACBOOOK-PRO prometheus % git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
lhhdz@LHHDZ-MACBOOOK-PRO prometheus % go build ./cmd/promtool 
lhhdz@LHHDZ-MACBOOOK-PRO prometheus % ./promtool tsdb bench write --metrics 100000 --scrapes 5000 ./tsdb/testdata/20kseries.json 
level=info ts=2023-07-20T11:44:49.452849Z caller=head.go:595 msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2023-07-20T11:44:49.452882Z caller=head.go:676 msg="On-disk memory mappable chunks replay completed" duration=1.916µs
level=info ts=2023-07-20T11:44:49.45289Z caller=head.go:684 msg="Replaying WAL, this may take a while"
level=info ts=2023-07-20T11:44:49.453061Z caller=head.go:755 msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2023-07-20T11:44:49.453073Z caller=head.go:792 msg="WAL replay completed" checkpoint_replay_duration=33µs wal_replay_duration=143.833µs wbl_replay_duration=125ns total_replay_duration=192.25µs
level=info ts=2023-07-20T11:44:49.453581Z caller=db.go:1786 msg="Compactions disabled"
>> start stage=readData
>> completed stage=readData duration=92.603459ms
>> start stage=ingestScrapes
ingestion completed
>> completed stage=ingestScrapes duration=4.012812416s
 > total samples: 100000000
 > samples/sec: 2.492014728180846e+07
>> start stage=stopStorage
>> completed stage=stopStorage duration=208.166083ms
lhhdz@LHHDZ-MACBOOOK-PRO prometheus %
```

**Comment by cstyan** [comment]
@shichanglin5 I think that benchmark is unrelated to the code your changing

@bwplotka @bboreham it's not the easiest thing to setup a benchmark for since the existing mock appender we use in `BenchmarkRemoteWritehandler` doesn't even use refs but just appends all samples to a slice. I modified the mock appender to use a map, and if the param for the append function is 0 it will return a value for the ref from it's monotonically increasing counter. I then also modified the write handlers code to pass 0 if the ref for that iteration of the loop is not set yet, otherwise use the one that's returned from the first call to append. None of these changes seemed to make any difference to the benchmark output allocs or bytes.

**Pull request merged**
