### PR TITLE
Revert head posting optimization

### PR DESCRIPTION
**Pull request by roidelapluie**
See #6968 #7048

### CODE REVIEW

**Comment by bwplotka** [comment]
I guess it was not limiting the stuff we touch index in head on query time?

**Comment by roidelapluie** [comment]
Probably because we scan the full head before filtering on labels. That is a huge loop. Is that correct?

**Comment by bwplotka** [comment]
What's wrong for windows? ):

**Comment by roidelapluie** [comment]
> What's wrong for windows? ):

https://github.com/prometheus/prometheus/issues/6672

**Comment by bwplotka** [comment]
Happy for this to be merged @roidelapluie

**Comment by roidelapluie** [comment]
I think we can wait a few hours to see if @SuperQ can install that on its env?

**Comment by bwplotka** [comment]
And what if not fully solved? There might be more sources of regression not
only this.

But yea, let's see first (:

**Comment by SuperQ** [comment]
I've deployed this patch to two nodes. It seems to be in the order of expected additional CPU time required for isolation. (5-10%) 

I'm going to give it another 30min so I can verify that it stays that way.

**Comment by roidelapluie** [comment]
> I've deployed this patch to two nodes. It seems to be in the order of expected additional CPU time required for isolation. (5-10%)
> 
> I'm going to give it another 30min so I can verify that it stays that way.

What about recording rule time?

**Comment by SuperQ** [comment]
Recording rule time is also "normal"

image

**Comment by SuperQ** [comment]
Just to followup, CPU time:

image

**Comment by bwplotka** [comment]
Thanks for quick check @SuperQ ! :tada:

**Pull request merged**
