### PR TITLE
TLS Server Name relabeling

### LINKED ISSUE #4827: Simplify connecting to targets via TLS with different server_name
Hi, 

## Proposal

Would it be possible to request that server_name in the tls config can be set through relabel config.
I was told in it is not possible to do this when asked in prometheus-users mailing list. 
https://groups.google.com/forum/#!searchin/prometheus-users/efahale%7Csort:date/prometheus-users/Ca4pE5MEC8g/xxJtXg5qAwAJ

This will simplify the prometheus configuration where the certitificate doesn't contain targets IP address.

### PR DESCRIPTION
**Pull request by LeviHarrison**
This PR adds the ability to set the TLS Server Name used for scraping targets through relabeling. It is currently a draft evaluating the functionality proposed in https://github.com/prometheus/common/pull/324.

Fixes #4827

### CODE REVIEW

**Comment by LeviHarrison** [comment]
Now that we know the cause of #9512, the issue here becomes how/if to close individual connections. When changing the CA file (and soon the other files too), all the connections are closed (https://github.com/prometheus/common/blob/ce7006ede1b27960d267508d7ae0af2f51422610/config/http_config.go#L831), but that makes sense because those files affect all the targets. The server name can be configured per target, and therefore it doesn't make sense to the connections for all targets.

**Comment by beorn7** [comment]
@LeviHarrison we ran into this during the bug scrub. Do you think there is a way to finish this up?

**Comment by LeviHarrison** [comment]
It's been a little while so I don't remember all the context, but I think what I came to is that the TLS server name can't be changed on an individual target without reloading the connections for all of them, which is undesirable.

**Comment by bboreham** [comment]
Closing as it's been in draft state for a long time.
If you come back to it please re-open.

**Pull request closed without merging**
