### PR TITLE
*: cut 1.4.0

### PR DESCRIPTION
**Pull request by fabxc**
@brian-brazil @brancz

### CODE REVIEW

**Comment by brancz** [comment]
not attached to it, but do you think we should mention #2180 as a bugfix for the k8s sd?

**Comment by brancz** [comment]
other than that lgtm

**Comment by brancz** [comment]
👍 lgtm

**Comment by fabxc** [comment]
I bumped the compiler version Travis uses and the error is gone. Most certainly because that version is more optimized and doesn't hit timeout and memory limits anymore.

**Pull request merged**
