### PR TITLE
Fix logging after the move to go-kit/log

### PR DESCRIPTION
**Pull request by roidelapluie**
Not perfect, but works until we have a proper fix for the underlying library.
This enables us to get a 2.28.1 release out.

cc @juliusv 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Review by LeviHarrison — APPROVED** [review]
Thanks for getting this sorted

**Review by juliusv — APPROVED** [review]
:+1: Assuming you tested this :)

**Comment by peterbourgon** [comment]
Is there some way I can help to make this better? I'd like it if you could avoid the go-kit/kit dependency, of course.

**Comment by juliusv** [comment]
@peterbourgon My understanding from the sidelines: I think the issue is just that we used another library (https://github.com/simonpasquier/klog-gokit/) in the k8s-related parts of Prometheus that hadn't switched over to the more light-weight logging lib, so the log-level-related types didn't match up between that and the rest of Prometheus, and we couldn't get a hold of @simonpasquier quickly enough to cut a new release of klog-gokit in time for a quickly-needed Prometheus 2.28.1. But it should fix itself once we release that library (with https://github.com/simonpasquier/klog-gokit/pull/18 already merged into it) and use it Prometheus.

**Comment by roidelapluie** [comment]
> Is there some way I can help to make this better? I'd like it if you could avoid the go-kit/kit dependency, of course.

You could release a new go-kit/kit where the log package public functions would simply call the go-kit/log ones. That way the transition could be smooth for everyone.

**Comment by peterbourgon** [comment]
> You could release a new go-kit/kit where the log package public functions would simply call the go-kit/log ones. That way the transition could be smooth for everyone.

Sure. But it's not really meant to be a transition, it's meant to be a distinct package. It's unlikely go-kit/kit/log will ever reference go-kit/log, or vice versa.

**Comment by roidelapluie** [comment]
> > You could release a new go-kit/kit where the log package public functions would simply call the go-kit/log ones. That way the transition could be smooth for everyone.
> 
> Sure. But it's not really meant to be a transition, it's meant to be a distinct package. It's unlikely go-kit/kit/log will ever reference go-kit/log, or vice versa.

You asked how you could help make this better, I answered :) The issue here was that both level packages are not compatible :)

**Pull request merged**
