### PR TITLE
promtool: Allow regexp matching on annotations in unit tests

### PR DESCRIPTION
**Pull request by dgl**
This allows regexp matching on annotations (not labels) in alert tests.

It achieves this by switching to yaml-v3 for just the unit tests, which means we can use a `yaml.Node` and therefore accept data with different "shapes", i.e. a string or a map.

It supports either YAML tags, or a map structure, as YAML tags may be hard to generate from JSON (many people actually write unit tests directly, hence why supporting the slightly nicer syntax, but not requiring it).

YAML tag:

```yaml
exp_annotations:
  foo: !regexp "some.*thing"
```

Mapping:

```yaml
exp_annotations:
  foo:
    match: regexp
    value: some.*thing
```

Note switching to yaml-v3 is not without risk, but I don't think any of the known issues will affect unit tests, and we use v3 for the rule files without issue now.

Partially addresses #7370.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can we avoid `foo: !regexp "some.*thing"`? I don't really think it helps users because in Prometheus regexp get their own string field.

**Comment by roidelapluie** [comment]
my comment still stands

**Comment by dgl** [comment]
@roidelapluie PTAL, I dropped the yaml tag part.

**Comment by michael-doubez** [comment]
Hello,

Thanks for the work.
@roidelapluie When can we expect this feature to be merged ?

It is not that it is much a burden to update the tests when we update annotations but the added value is low.

**Comment by roidelapluie** [comment]
Can we have separate fields to avoid the yaml unmarshalling magic? I don't like that kind of things and it sounds like it could be hard to maintain if we switch yaml library

**Comment by roidelapluie** [comment]
cc @dgl have you seen my last comment?

**Comment by bwplotka** [comment]
(During Prometheus bug scrub meeting)

Seems like no activity since July 2023. We would love this change, but @roidelapluie comment still stands. Closing for now, we can always reopen, thanks @dgl! 💪🏽

**Pull request closed without merging**
