### PR TITLE
Pass groupName as context value in call to Appender

### PR DESCRIPTION
**Pull request by annanay25**
As a follow up action from this comment https://github.com/prometheus/prometheus/pull/7660#issuecomment-664317496, I'd like to propose the following change to pass `groupName` as a context value, in the call to `Appender()` from `group.run()`. 

This will enable us to choose group spec Appenders in the Cortex Ruler.

Signed-off-by: Annanay <annanayagarwal@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Group names are not unique.

**Comment by roidelapluie** [comment]
We already pass the file and the group to the promql engine. Can we reuse that or refactor it?

**Comment by annanay25** [comment]
@roidelapluie - Thanks for pointing that out. 

In Prometheus, code flow will not be affected by this extra config key (we can choose to ignore it), and for our use case, groups with the same name can use the same appender. So it remains useful.

**Comment by roidelapluie** [comment]
I'd still add it at the same place, because it is set once for all (and not each time we get an appender), and include the file so that we do not end up with a PR adding the file in the future, WDYT?

**Comment by annanay25** [comment]
I think you're right @roidelapluie. :)

> We already pass the file and the group to the promql engine via context. Can we reuse that or refactor it?

We can make use of this key from the context. I will close this PR once I confirm that works for us.

**Comment by roidelapluie** [comment]
> I think you're right @roidelapluie. :)
> 
> > We already pass the file and the group to the promql engine via context. Can we reuse that or refactor it?
> 
> We can make use of this key from the context. I will close this PR once I confirm that works for us.

You will not be able to do so as they use private types of the promql package.

**Comment by roidelapluie** [comment]
My initial point about what about we simply make the rule manager instanciable multiple times so we don't need that in contexts at all was not answered; cortex could create one rule manager per Appendable.

**Comment by annanay25** [comment]
Thanks @bwplotka I think that makes sense. I can change this to a typed string, which is a golang context-key recommendation as well.

**Comment by annanay25** [comment]
> You will not be able to do so as they use private types of the promql package.

The other option is to make the promql key public. That would reduce adding duplicate information to the group context.

**Comment by roidelapluie** [comment]
Closed by #7748

**Comment by annanay25** [comment]
Thanks @roidelapluie and @bwplotka :)

**Pull request closed without merging**
