### PR TITLE
upgrade k8s client to v6.0.0

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fixes: #3685

it was a big pain to update the client due to enormous dependency web

### CODE REVIEW

**Comment by brancz** [comment]
Note that while there is a tag for 1.11.0-alpha.0 that's an automatically generated tag, it doesn't say much about the stability of the code other than that's the version used to build the respective Kubernetes version. It's generally recommended to use the official version tags, latest for that would be: https://github.com/kubernetes/client-go/releases/tag/v6.0.0

**Comment by krasi-georgiev** [comment]
@brancz thanks, changed to v6

**Comment by Mrcortez34** [comment]
@krasi-georgiev Is v6.0.0 being used in 2.2.0-rc.1?  I updated my Prom server to use 2.20-rc.1, and it has resolved my memory leak. If you would like further logs, I can get them to you. 

screenshot from 2018-03-01 12-13-12

**Comment by krasi-georgiev** [comment]
@Mrcortez34 nope this hasn't been upgraded in a while.

did I read correctly that you upgraded from  prometheus 1.7.4? 
if that is the case than there were enormous improvements since than.

**Comment by Mrcortez34** [comment]
@krasi-georgiev No, thats the version of my kubernetes. 

I upgraded prom from 1.8 to 2.0(No issues). Then prometheus released 2.1, I upgraded to 2.1 and thats where I started to see the memory leak.  

Now my current version for Prometheus is 2.2.0-rc.1

**Comment by krasi-georgiev** [comment]
there was one major bug fix from 2.1 to 2.2 so there is a big chance you were hitting that one
https://github.com/prometheus/prometheus/issues/3715

**Comment by brancz** [comment]
Seems like there are still some problems with CI in travis, any idea what might be happening?

**Comment by brian-brazil** [comment]
This need a rebase.

**Comment by krasi-georgiev** [comment]
seems 2.2.0-rc.1 fixes the issue so best to close this one as it might brake other things.

**Comment by krasi-georgiev** [comment]
[prometheus.zip](https://github.com/prometheus/prometheus/files/1859485/prometheus.zip)
attached for testing

**Comment by nim-nim** [comment]
> Note that while there is a tag for 1.11.0-alpha.0 that's an automatically generated tag, it doesn't say much about the stability of the code other than that's the version used to build the respective Kubernetes version. It's generally recommended to use the official version tags, latest for that would be: https://github.com/kubernetes/client-go/releases/tag/v6.0.0

Unfortunately is seems kubernetes client noes not exist as a project with separate versioning anymore, the separate versionning in their repo is an historical artifact, other projects that interface with kubernetes now base themselves on the kubernetes_x_y_z tags

Which basically means choosing the major kubernetes version to target and building from the latest full minor release tag of that version.
* kubernetes 1.9.6 if you target kubernetes 1.9 (that's what v 6.0.0 was + fixes)
* kubernetes 1.10.0  if you target kubernetes 1.10 (what would have been v 7.0.0 with the old numbering convention)

**Comment by krasi-georgiev** [comment]
too many conflicts. Needs to be started over so closing for now.

**Comment by FUSAKLA** [comment]
I'm still running this in staging but there will be lot of work regarding the recent PR with k8s SD refactor I suppose? 

If there will be new version to test I'll be happy to do deploy it again.

**Comment by krasi-georgiev** [comment]
I have moved my focus to tsdb so someone else needs to take over this one.

**Pull request closed without merging**
