### PR TITLE
Update common/route vendoring for contextFn errors

### PR DESCRIPTION
**Pull request by juliusv**
@fabxc

### CODE REVIEW

**Comment by redbaron** [comment]
just curious, why not submodules?

**Comment by juliusv** [comment]
@redbaron In my experience, git submodules are even clunkier to use with weird behaviors, but the other reason is that Go vendoring tools don't use submodules either (at least none that I know of). Not sure if anyone uses submodules for Go vendoring purposes.

**Comment by redbaron** [comment]
which go vendoring tools?

Vendor:
```
git submodule add  https://github.com/prometheus/common.git vendor/github.com/prometheus/common
( cd vendor/github.com/prometheus/common; git checkout <tag> )
git commit -a -m "Vendor prometheus/common"
```

Update:
```
( cd vendor/github.com/prometheus/common; git checkout <tag_to_update_to> )
git commit -a -m "Updated vendored prometheus/common"
```

anyway, whatever works best for you :)

**Comment by grobie** [comment]
Please let's not introduce submodules. I like them personally, but in my experience they'll cause a high support volume.

**Comment by juliusv** [comment]
@redbaron Go vendoring tools also help you manage more than that, like automatically vendoring transitive dependencies. And they don't necessarily vendor the entire repo, but just the Go package directories you need, sometimes also without the test and other non-Go files.

**Pull request merged**
