### PR TITLE
travis: add 1.x to go versions

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by fabxc** [comment]
I'm relatively sure we do not support many older versions of Go. Probably why Travis is failing on this branch.

Given how easy upgrading Go is, I don't see much incentive for us to maintain compatibility, especially since there security fixes in the mean time.

So the current and previous minor version of Go seems sane to test. Nothing older.

**Comment by dvrkps** [comment]
1.x means latest stable version(1.9 in this moment) but 1.9.x, 1.10.x will also match in future.

Test fails in github.com/prometheus/prometheus/storage/local for Go 1.9

**Comment by fabxc** [comment]
Oh, okay. Thanks for the explanation. This makes sense then. 
Restarted the build in case it was just a flake. Otherwise, we need to fix things for 1.9.

**Comment by dvrkps** [comment]
I think that 1.9 exclude vendor folder from go test ./..., maybe "make test" produce that fail for some reason.

**Comment by fabxc** [comment]
Seems it was just a flake.

**Pull request merged**
