### PR TITLE
Show special float values as gaps.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by leonerd** [comment]
Hm; this doesn't appear to have helped; I pulled from master, rebuilt prometheus, restarted server. Still the gaps remain.

**Comment by juliusv** [comment]
@leonerd Is this on /graph or in console templates? I have only personally verified the former because I didn't have consoles with NaN data handy.

**Comment by leonerd** [comment]
@juliusv This is on /graph and the console templates that use `new PromConsole.Graph(...)`. The two behave identically.

**Comment by juliusv** [comment]
@leonerd Hm, that's weird. At least on /graph it does gaps correctly for NaN for me:

graph_gaps

Sure you hard-refreshed everything in the browser? What browser is it?

**Comment by leonerd** [comment]
I'm plotting the (recorded) expression of `(rate(synapse_storage_cache:hits[5m]) / rate(synapse_storage_cache:total[5m]))`, so there are times when the hit ratio is NaN due to div0.

This is Firefox (well, Iceweasel from debian testing) 31.5.0.

Definitely hard-refreshed by Ctrl-Shift-R.

broken-graph

**Comment by leonerd** [comment]
Same behaviour with Chrome Version 41.0.2272.76

**Comment by juliusv** [comment]
Weird. It works for me in Chrome 41.0.2272.89 and Firefox 36.0.1 on Ubuntu.
The /graph endpoint, that is (still haven't tried consoles, but let's get
/graph working first). Do you see any JS errors on /graph?

**Comment by leonerd** [comment]
Ahah! I think we might just blame agressive caching. After having left it a couple of hours and refreshed, it appears to be finally working. So this seems fixed now.

**Comment by leonerd** [comment]
Or... half-works. The /graph page works nicely to show individual graphs, but now my overall console HTML page generates lots of errors of

    TypeError: self._parseValue is not a function

and none of the graphs display; they're all just stuck on the "loading" spinner.

**Comment by leonerd** [comment]
(solved by IRC; needed a `var self = this` inserting into the start of the `_parseValue function` source)

**Pull request merged**
