### PR TITLE
Update react deps

### PR DESCRIPTION
**Pull request by SuperQ**
* Bump all yarn deps (rm yarn.lock ; yarn)

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@SuperQ Thanks! Bumping React from 16 to 17 breaks a couple of things, especially with test libraries, so I'd suggest holding off on that for now. I'll separately try to upgrade that sometime soon (but probably need to wait until https://github.com/enzymejs/enzyme/issues/2429 is done), but more decoupled from release timing.

**Comment by bwplotka** [comment]
Thanks Ben, sounds like we can proceed the release without this then?

**Comment by SuperQ** [comment]
Dropped the React 17 update.

**Comment by bwplotka** [comment]
👍🏽

**Pull request merged**
