### PR TITLE
TSDB: Add hints to Append interface

### PR DESCRIPTION
**Pull request by jesusvazquez**
Attempt to do https://github.com/prometheus/prometheus/issues/11765 implementation

This PR is for now just adding the hints argument to the signature of all appends. They are not currently used in this PR but https://github.com/prometheus/prometheus/pull/14710 will start using hints for scraping and rule managers.

### CODE REVIEW

**Review by krajorama — COMMENTED** [review]
Should [AppendCTZeroSample](https://github.com/prometheus/prometheus/blob/ad4857de5210bb1756b46c9ae6e653c72cc7654d/storage/interface.go#L364) also have the hints?

**Comment by jesusvazquez** [comment]
Benchmark results of passing the hints as a pointer:
```
❯ go test -run -benchmem -bench=^BenchmarkHeadAppender_Append_Commit_ExistingSeries ./tsdb
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/tsdb
cpu: Apple M2 Pro
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/1_samples_per_append-12         	    7314	    197277 ns/op	    4027 B/op      51 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/2_samples_per_append-12         	    4593	    361728 ns/op	    4054 B/op      51 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/5_samples_per_append-12         	    1984	    884303 ns/op	    6686 B/op      62 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/100_samples_per_append-12       	     280	   4127620 ns/op	   71203 B/op     609 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/1_samples_per_append-12        	     669	   2632063 ns/op	   37646 B/op     505 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/2_samples_per_append-12        	     517	   4267123 ns/op	   38051 B/op     502 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/5_samples_per_append-12        	     292	   4086363 ns/op	   63684 B/op     601 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/100_samples_per_append-12      	     150	   7969295 ns/op	  714767 B/op    6010 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/1_samples_per_append-12       	     262	   4904098 ns/op	  366451 B/op    4971 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/2_samples_per_append-12       	     247	   4956200 ns/op	  364004 B/op    4867 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/5_samples_per_append-12       	     189	   6393647 ns/op	  666721 B/op    5988 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/100_samples_per_append-12     	      13	  79796644 ns/op	11281595 B/op   60015 allocs/op
``` 

Benchmark results passing hints by value:
```
❯ go test -run -benchmem -bench=^BenchmarkHeadAppender_Append_Commit_ExistingSeries ./tsdb
goos: darwin
goarch: arm64
pkg: github.com/prometheus/prometheus/tsdb
cpu: Apple M2 Pro
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/1_samples_per_append-12               7633            200406 ns/op            4028 B/op         51 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/2_samples_per_append-12               3865            378531 ns/op            4057 B/op         51 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/5_samples_per_append-12               1580            870002 ns/op            6663 B/op         62 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/100_series/100_samples_per_append-12              261           4910778 ns/op           67828 B/op        609 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/1_samples_per_append-12               501           2584373 ns/op           37741 B/op        504 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/2_samples_per_append-12               340           4589202 ns/op           38588 B/op        509 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/5_samples_per_append-12               267           5049211 ns/op           64121 B/op        590 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/1000_series/100_samples_per_append-12             141           8905587 ns/op          719873 B/op       6010 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/1_samples_per_append-12              235           5086385 ns/op          365834 B/op       4903 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/2_samples_per_append-12              235           5119528 ns/op          371554 B/op       4903 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/5_samples_per_append-12              170           6810698 ns/op          629392 B/op       5950 allocs/op
BenchmarkHeadAppender_Append_Commit_ExistingSeries/10000_series/100_samples_per_append-12             13          83769292 ns/op        26394274 B/op      60029 allocs/op
PASS
ok      github.com/prometheus/prometheus/tsdb   23.211s

```

**Comment by bboreham** [comment]
I don't like a 500-line PR, not to mention downstream impact, for something we might need in future.

**Comment by jesusvazquez** [comment]
Closing this one since we cant reach agreement and because the change on the interface expands everywhere.

**Pull request closed without merging**
