### PR TITLE
Install go 1.14 in windows

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
@brian-brazil Required so we can update kubernetes go dependency + future TLS work.

**Comment by brian-brazil** [comment]
The Windows CI is still unhappy.

**Comment by roidelapluie** [comment]
success

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
