### PR TITLE
vendor: update gopkg.in/fsnotify.v1

### LINKED ISSUE #1507: Please consider disabling fsnotify in certain architectures
Hi,

As noted in bug fsnotify/fsnotify#130, fsnotify fails to work correctly (or at all) in arm64, ppc64 and ppc64el.

This was preventing prometheus to be accepted in Debian testing, so while this is solved upstream, I hacked together a [patch](http://anonscm.debian.org/cgit/pkg-go/packages/prometheus.git/tree/debian/patches/07-Disable_fsnotify.patch) to disable fsnotify and rely only on refresh intervals in those architectures. You might want to consider applying something similar, so prom keeps working.

### PR DESCRIPTION
**Pull request by fabxc**
This updates the fsnotify package, which now uses golang.org/x/sys/unix
package. This fixes #1507.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Did you forget to add vendor.json?

**Comment by fabxc** [comment]
No, probably just GH failing to show it due to too many files.

```
$ git show --name-only 733ed099f55e02a883b2989ccc9e8f2cfac754b6 | grep vendor.json
vendor/vendor.json
```

**Comment by brian-brazil** [comment]
:+1:

**Comment by fabxc** [comment]
CircleCI is having issues, Travis succeeded though so merging anyway.

**Pull request merged**
