### PR TITLE
Fix race condition in Rule manager.Update() function

### PR DESCRIPTION
**Pull request by liguozhong**
Fix race condition in Rule manager.Update() function
image

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks!

**Comment by roidelapluie** [comment]
That would mean that we could pass newg to the inner goroutine as well

**Comment by liguozhong** [comment]
> Thanks!

thanks

**Comment by roidelapluie** [comment]
Now that I look deeper I don't see a race here as the olg id scoped to the inner loop.

**Comment by roidelapluie** [comment]
> That would mean that we could pass newg to the inner goroutine as well

That comment is invalid. We don't need to.

**Pull request merged**
