### PR TITLE
minor fix for making map

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@huawei.com>

### CODE REVIEW

**Comment by cstyan** [comment]
why is the `2*` needed?

**Comment by YaoZengzeng** [comment]
@cstyan because each label and annotation will create two key-value pair in the map.

**Comment by bwplotka** [comment]
Maybe some commentary would be nice then, but otherwise LGM

**Comment by cstyan** [comment]
:point_up: agreed, a comment would help

**Comment by YaoZengzeng** [comment]
@codesome @bwplotka @cstyan Updated.

But why we need another key like `XXX_labelpresent_XXX=true` ?

**Pull request merged**
