### PR TITLE
#1722 - ignore apps with zero apps

### LINKED ISSUE #1722: Marathon discovery - panic: runtime error: index out of range
Stacktrace:

```
panic: runtime error: index out of range

goroutine 219 [running]:
panic(0xd864c0, 0xc820010030)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/prometheus/prometheus/retrieval/discovery/marathon.targetForTask(0xc83e5e38e0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:229 +0x1cf
github.com/prometheus/prometheus/retrieval/discovery/marathon.targetsForApp(0xc83e5e3b48, 0x0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:219 +0x18b
github.com/prometheus/prometheus/retrieval/discovery/marathon.createTargetGroup(0xc83e5e3b48, 0xc83b2d9aa0)
	/go/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:195 +0x33
github.com/prometheus/prometheus/retrieval/discovery/marathon.AppsToTargetGroups(0xc826630640, 0x56)
	/go/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:187 +0xe0
github.com/prometheus/prometheus/retrieval/discovery/marathon.(*Discovery).fetchTargetGroups(0xc8393e00c0, 0xc8393ce3b8, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:113 +0xb1
github.com/prometheus/prometheus/retrieval/discovery/marathon.(*Discovery).updateServices(0xc8393e00c0, 0x7f0857028650, 0xc8393a7480, 0xc8393ce3c0, 0x0, 0x0)
	/go/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:73 +0x50
github.com/prometheus/prometheus/retrieval/discovery/marathon.(*Discovery).Run(0xc8393e00c0, 0x7f0857028650, 0xc8393a7480, 0xc8393ce3c0)
	/go/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:64 +0x177
created by github.com/prometheus/prometheus/retrieval.(*targetSet).runProviders
	/go/src/github.com/prometheus/prometheus/retrieval/targetmanager.go:328 +0x308
```

**What did you do?**
Using service discovery with marathon.

**What did you expect to see?**
Services running under marathon in targets.

**What did you see instead? Under which circumstances?**
Exception in logs. Index out of range.

**Environment**
OS: ubuntu 14.04 64bit server.

* System information:
Linux 4.2.0-36-generic x86_64

* Prometheus version: 
Tested with prometheus 16.2, 19.2 and master branch.

### PR DESCRIPTION
**Pull request by rohit01**
Fixes #1722

### CODE REVIEW

**Comment by rohit01** [comment]
If all is good, please cherry pick this commit for release 19.2 as well.

**Comment by beorn7** [comment]
This looks good to me. I'd feel much better if somebody who actually knows something about Marathon would have a look. @xperimental perhaps?

@rohit01 As a bug fix for 0.19.2, it's actually easier if you create a PR to merge your change into the release-0.19 branch. After we have merged your change, we then merge release-0.19 into master. (Cherrypicking creates now commits and makes those merges more painful.)

**Comment by rohit01** [comment]
@beorn7 Thanks. New PR for 19.2 https://github.com/prometheus/prometheus/pull/1727

**Comment by xperimental** [comment]
@beorn7 Looks fine from a first glance for me as well, although the description should probably read "ignore tasks with no open ports".

I'd like to validate my assumption that this is indeed something that depends on the app configuration and is not a runtime condition, if you can wait until tomorrow.

Also adding a test for this condition would probably be a good idea as this configuration has not crossed my mind before.

**Comment by rohit01** [comment]
Added Test cases. Test result with fix:
```
$ go test
PASS
ok  	github.com/prometheus/prometheus/retrieval/discovery/marathon	0.020s
```

Test result without fix:
```
$ go test
--- FAIL: TestMarathonZeroTaskPorts (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 24 [running]:
panic(0x3b7a00, 0xc82000a080)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc8200a4240)
	/usr/local/go/src/testing/testing.go:467 +0x192
panic(0x3b7a00, 0xc82000a080)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/prometheus/prometheus/retrieval/discovery/marathon.targetForTask(0xc8200498d8, 0x0, 0x0)
	/Users/rohit/golang/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:232 +0x1cf
github.com/prometheus/prometheus/retrieval/discovery/marathon.targetsForApp(0xc820049b40, 0x0, 0x0, 0x0)
	/Users/rohit/golang/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:222 +0x18b
github.com/prometheus/prometheus/retrieval/discovery/marathon.createTargetGroup(0xc820049b40, 0x0)
	/Users/rohit/golang/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:195 +0x33
github.com/prometheus/prometheus/retrieval/discovery/marathon.AppsToTargetGroups(0xc8200df060, 0x2f)
	/Users/rohit/golang/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:187 +0xe0
github.com/prometheus/prometheus/retrieval/discovery/marathon.(*Discovery).fetchTargetGroups(0xc820049f20, 0x0, 0x0, 0x0)
	/Users/rohit/golang/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:113 +0xb1
github.com/prometheus/prometheus/retrieval/discovery/marathon.(*Discovery).updateServices(0xc820049f20, 0x1298bd0, 0xc820072fc8, 0xc8200708a0, 0x0, 0x0)
	/Users/rohit/golang/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon.go:73 +0x50
github.com/prometheus/prometheus/retrieval/discovery/marathon.TestMarathonZeroTaskPorts(0xc8200a4240)
	/Users/rohit/golang/src/github.com/prometheus/prometheus/retrieval/discovery/marathon/marathon_test.go:134 +0x1b6
testing.tRunner(0xc8200a4240, 0x6306d0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
exit status 2
FAIL	github.com/prometheus/prometheus/retrieval/discovery/marathon	0.013s
$
```

**Comment by rohit01** [comment]
It's a simple validation fix. I have tested the build myself in our environment as well. Working fine.

**Comment by rohit01** [comment]
>  although the description should probably read "ignore tasks with no open ports".
@xperimental Agree. But the problem is not zero ports, it is **app with zero tasks**. The JSON returned by the marathon API contains:
```
"tasks": [ ],
```

JSON parsing of go succeeds. App struct is initialized with zero task array.

**Comment by beorn7** [comment]
@xperimental @rohit01 Great stuff. Once you have settled on the correct wording in the description and @xperimental has verified in his setup, we can merge (but please via #1727, makes porting of the bugfix to both branches easier).

**Comment by rohit01** [comment]
Closing this PR in favour of #1729 . Assuming, once 1729 is merged, it will be merged back into master.

**Pull request closed without merging**
