### PR TITLE
Mark `Histogram.positive_spans` and `negative_spans` as non-nullable.

### PR DESCRIPTION
**Pull request by charleskorn**
As far as I understand it, we'd never expect to receive a `nil` span, and [`remote.spansProtoToSpans()`](https://github.com/prometheus/prometheus/blob/c70d85baed260f6013afd18d6cd0ffcac4339861/storage/remote/codec.go#L562) would panic if we received a `nil` span. 

Marking the fields as non-nullable also means the generated Golang code doesn't use pointers for these fields, reducing allocations.

cc @krajorama

### CODE REVIEW

**Comment by charleskorn** [comment]
The "mixins tests" CI job seems to be failing for unrelated reasons:

```
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
```

**Comment by beorn7** [comment]
I'm re-running the presumably flaky tests.

In different news: I like this, but I think the remote write experts should chime in. @csmarchbanks @cstyan

**Comment by beorn7** [comment]
OK, it's not flaky, it's something more fundamental, but seems indeed unrelated.

**Comment by beorn7** [comment]
Tests are fixed now (in prometheus/golang_builder). I'm re-running once more.

**Review by codesome — APPROVED** [review]

**Pull request merged**
