### PR TITLE
WIP - Azure VMSS support for azure_sd

### LINKED ISSUE #2369: Add Azure VM scale sets to azure_sd_config
**What did you do?**

Configured azure_sd_config to point to my Azure subscription.

**What did you expect to see?**

All my resource manager vms.

**What did you see instead? Under which circumstances?**

I only saw standalone vms. VMs managed under Azure Scale Set where not visible.

**Environment**

Windows, Azure

* System information:

```
'uname' is not recognized as an internal or external command,
operable program or batch file.
```

* Prometheus version: 

```
prometheus, version 1.5.0 (branch: master, revision: d840f2c400629a846b210cf58d65b9fbae0f1d5c)
  build user:       root@a04ed5b536e3
  build date:       20170123-14:03:28
  go version:       go1.7.4
```

### PR DESCRIPTION
**Pull request by gambrose**
fixes #2369 

I am new to go so wanted to get a early review to see if I am on the right track with this fix.
I have got basic scenario of loading and exporting the VMSS vms working but have not yet added any new VMSS specific labels to the scraped targets.

The `compute.VirtualMachine` and `compute.VirtualMachineScaleSetVM` are different structs returned from the azure api but they share the same properties that we need so I have mapped them to a common struct to avoid duplicating the target creation code.

The biggest issue I had was with the parsing of azure ids to get the constituent parts. The azure api does not appear to have methods to retrieve a network interface using an id directly. The existing code did some basic parsing of the id to get the resource group name and resource name. This code did not work with the more complicated 'nested' ids for network interfaces managed by VMSS.
I think that we should try and avoid this id parsing so I have changed to using the lower level interface that the azure client exposes of `CreatePreparer`, `GetSender`, `GetResponder` but wonder if I should raise an issue with the azure sdk to ask them to support the use case?
I have done the minimum required to get `newAzureResourceFromID` parsing the new ids as I was looking for guidance on how to improve this. Ideally, we would not need this method but if we want to make it more robust can we import terraform's implementation https://github.com/hashicorp/terraform/blob/master/builtin/providers/azurerm/resourceid.go?

If someone could spare the time to review my PR and give me some guidance to make my code more go like and better then I would appreciate the feedback.

### CODE REVIEW

**Comment by beorn7** [comment]
@rjtsdl @brian-brazil @fabxc could any of you provide some early feedback for @gambrose ?

I feel like I'm less qualified than any single one of you.

**Comment by rjtsdl** [comment]
Their implementation has some assumptions, which is clearly stated in the comment.

Another option is, try to get azure-sdk-for-go to implement parsing logic for resourceid. I don't know how hard that would be like though. But if you made such a PR, i can reach out internally to get it reviewed fast.

**Comment by gambrose** [comment]
Unfortunately I don't have time to get this PR up-to quality, tested and merged.

**Comment by sylr** [comment]
I'd like to revive this. VMSS is going to be used more and more.

Even kubernetes autoscaling for azure which is alpha as of [v1.10.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#azure) and planned to be stable for v1.12.0 rely on virtual machine scale sets.

**Comment by agolomoodysaada** [comment]
We really need this feature as well. Anyone interested in collaborating on this?

**Pull request closed without merging**
