### PR TITLE
Release 2.48.0-rc.2

### PR DESCRIPTION
**Pull request by LeviHarrison**
Waiting on #13062?

### CODE REVIEW

**Comment by beorn7** [comment]
I'll merge #13062 once the tests are done. Including it here would be much appreciated .

**Comment by beorn7** [comment]
It's merged now.

**Comment by LeviHarrison** [comment]
Great, thanks. It's already in the changelog here.

**Review by beorn7 — APPROVED** [review]
Thanks.

**Review by roidelapluie — APPROVED** [review]
Thanks!

**Comment by LeviHarrison** [comment]
Thanks for the merge 👍

**Comment by LeviHarrison** [comment]
Alright, so Prombench is not working right now so I'm not sure how we're going to proceed with this release. I guess I could just run a local version of it myself, or do we want to do something else?

**Comment by bboreham** [comment]
Ideally we would fix Prombench, but I'm at KubeCon this week so I probably won't get to it.

I fired up `prom/prometheus:v2.48.0-rc.2` in a dev environment just now; will report back.

**Comment by ArthurSens** [comment]
> Alright, so Prombench is not working right now so I'm not sure how we're going to proceed with this release. I guess I could just run a local version of it myself, or do we want to do something else?

Is that something that people outside of Prometheus team could help with?

**Comment by LeviHarrison** [comment]
See https://cloud-native.slack.com/archives/C01AUBA4PFE/p1698501889156349, but I think at least some part it would require access to our Google cloud account, which only team members have.

**Comment by bboreham** [comment]
It is still noticeably slower:
image
image

**Comment by LeviHarrison** [comment]
This release is already considerably late, so maybe we should just scrap the annotations all together and leave them for 2.49 (presuming that is what's causing the problem).

**Comment by bboreham** [comment]
I've just been looking at profiles and cannot see annotations as a problem. 

[Comparing memory allocations.
](http://prombench.prometheus.io/profiles?compare_a=true&expression_a=memory:alloc_space:bytes:space:bytes{pr_number=%2213083%22}&from_a=1699539273066&to_a=1699540173066&time_selection_a=relative:minute|15&profile_name_a=memory:alloc_space:bytes:space:bytes&compare_b=true&expression_b=memory:alloc_space:bytes:space:bytes{pr_number=%2213083%22}&from_b=1699539273066&to_b=1699540173066&time_selection_b=relative:minute|15&profile_name_b=memory:alloc_space:bytes:space:bytes&dashboard_items=table&merge_from_a=1699539895674&merge_to_a=1699539895674&query_a=memory:alloc_space:bytes:space:bytes{pr_number=%2213083%22,%20instance=%2210.52.17.3:9090%22,%20job=%22prometheus%22,%20prometheus=%22test-pr-13083%22}&labels_a=pr_number=13083,instance=10.52.17.3:9090,job=prometheus,prometheus=test-pr-13083&merge_from_b=1699539882884&merge_to_b=1699539882884&query_b=memory:alloc_space:bytes:space:bytes{pr_number=%2213083%22,%20instance=%2210.52.18.2:9090%22,%20job=%22prometheus%22,%20prometheus=%22test-v2-47-1%22}&labels_b=pr_number=13083,instance=10.52.18.2:9090,job=prometheus,prometheus=test-v2-47-1)

**Comment by bboreham** [comment]
I can't figure out what is going on.  Rate of garbage production is lower in 2.48rc2 than 2.47; everything else looks much the same, yet the stats say it is running slower.

**Comment by bboreham** [comment]
I change the load-generator config to query less often, to see if that would make things clearer.
In this spec: https://github.com/prometheus/test-infra/blob/2198f38fcba604d3f9e7ce16e33d7972a00f2161/prombench/manifests/prombench/benchmark/6_loadgen.yaml#L10-L50
I changed group 0 from 2s to 10s; group 1 from 5s to 15s; group 2 from 10s to 60s; and group 3 from 10s to 60s.
Slightly later changed `node_cpu` to `node_cpu_seconds_total` in queries, because that latter name exists.

Filed https://github.com/prometheus/test-infra/issues/617 to note the details.

Anyway post that change things look closer between 2.47.1 and 2.48.0-rc.2.

**Comment by roidelapluie** [comment]
LGTM Bryan.

**Comment by LeviHarrison** [comment]
Alright, sounds good 👍 I'll cut the final release soon

**Pull request merged**
