### PR TITLE
Move global /graph settings to navbar

### PR DESCRIPTION
**Pull request by juliusv**
This saves precious space at the top and makes the page look less
awkward.

Signed-off-by: Julius Volz <julius.volz@gmail.com>

Screenshots:

**Closed:**

topsettings

**Open:**

topsettings_open

### CODE REVIEW

**Comment by juliusv** [comment]
@boyskila

**Comment by roidelapluie** [comment]
js tests fail

**Comment by boyskila** [comment]
Interesting! I have another idea if you like to try it. How about to move the checkboxes in the navbar and to dispatch StorageEvent on change like so:
```
window.dispatch(StorageEvent('storage', {
    key: 'enable-query-history',
    newValue: `${e.target.checked}`
}))
```
Then we can  ```window.addEventListener('storage', updateStateFunction)``` whenever we like and thus we will not be restricted to use it only in one place.
Also attaching the ```eventListener``` can be utilized in component, let say ```LocalStorageListener``` which will be responsible to update the storage and to propagate it to its children. Something like this:
```
<LocalStorageListener>
   {storage => {
        
   }}
</LocalStorageListener>
```

**Comment by roidelapluie** [comment]
I don't like what this change makes on mobile, as this is not navbar items, it should not be hidden on twice on mobile.

But besides me during outages, who runs promql queries on mobile? :smile:

**Comment by boyskila** [comment]
> as this is not navbar items

Yeah, should be hidden for other pages as those options are graph page related only.

**Comment by boyskila** [comment]
Ops, the became hidden on unmount...ignore comment above :)

**Comment by juliusv** [comment]
Whoops yeah, I always forget about the JS tests, sorry. Will update them once we agree on what we want.

@boyskila Regarding the event listener: for now I would only want to display the settings on the /graph page, as that's the only thing they affect (even if TZ settings become relevant for other settings, the query history setting is graph-page-specific). I think once we do want to support custom TZs on other pages, we'll have to rethink this all a bit. E.g. if /alerts had custom TZ support, I'd probably want to show this menu at the top too, but only with the relevant TZ option, not the query history one. So then it'd still have to be page-specific, and maybe the way it's currently done here (albeit a bit odd) is easiest for that case? But maybe there's a better way.

**Comment by juliusv** [comment]
Regarding mobile: Yeah, will play around a bit more later to see if I can make it a bit nicer. You can currently still access it under mobile (at least when testing in mobile mode in Chrome), though it's hidden behind the hamburger menu).

**Comment by boyskila** [comment]
I think It'd be good to have such pattern which will allow subscribing for storage change. It'd be much cleaner and relatively easy to use.

**Comment by gouthamve** [comment]
@juliusv is this still relevant / active?

**Comment by juliusv** [comment]
Closing for now.

**Pull request closed without merging**
