### PR TITLE
Web: Format files.go when it is built.

### PR DESCRIPTION
**Pull request by brian-brazil**
This will avoid unrelated changes appearing
when you do a make fmt.

@juliusv

### CODE REVIEW

**Comment by fabxc** [comment]
:+1:

**Comment by juliusv** [comment]
How about just ignoring it in https://github.com/prometheus/prometheus/blob/master/Makefile#L76. The `generated` bit there isn't needed anymore.

**Comment by fabxc** [comment]
meh - gofmt all the way!

**Comment by juliusv** [comment]
Hm, ok.

**Comment by fabxc** [comment]
I mean, unless you feel strongly about it. Last time we were discussing whether generated Go code should have proper comments everywhere so having it formatted seems reasonable.

**Comment by juliusv** [comment]
Nah, it's fine. We just need to clean some stuff up from the `make format` in the Makefile. I'll do that.

**Pull request merged**
