### PR TITLE
WIP Optimize the labels memory usage

### PR DESCRIPTION
**Pull request by abitduck**
@roidelapluie @LeviHarrison

With millions metrics，memory will be the first limitation for most cases, so we did some work for this problem.

## Optmize for labels caching

The flowing grafana is the tsdb top 10 label value pairs

image

There have a lot duplicated labels in the memory store with `labels.Labels`

With go pprof heap, almost half of the memory is used by labels

So we decide use dict cache to solve the problem, but the result is better than expect.

## Results

* 4.6M metrics for mesh service
  * Memory from 43G to 14G, reduce **68%**
  * CPU from 400% to 130%, reduce **67.5%**
* Another 29M metrics instance memory compared: 200G vs 50G
* Less go gc time

---
## The metric compre grafana screenshot

image

---
Best Reguards

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR. There are some CI errors. 

FYI I have a WIP to do roughly the same thing but varint-encoding the string indexes, and using multiple string tables with different lifetimes.

**Comment by bboreham** [comment]
On first reading I couldn’t spot your cache eviction policy; can you explain it please?

**Comment by abitduck** [comment]
> On first reading I couldn’t spot your cache eviction policy; can you explain it please?

OK，I'll expain it more~

**Comment by bboreham** [comment]
I would like to suggest: this would be a much smaller PR if you left `Label` unchanged and made the int pairs an internal detail of `Labels`. This was the idea of adding abstractions like `Labels.Range`, which (in theory) don’t need to change as the internals evolve.

**Comment by abitduck** [comment]
> I would like to suggest: this would be a much smaller PR if you left `Label` unchanged and made the int pairs an internal detail of `Labels`. This was the idea of adding abstractions like `Labels.Range`, which (in theory) don’t need to change as the internals evolve.

Yes, this maybe a better idea. Most label string is genterated by func `Metric(l *labels.Labels) string` like :
```golang
func (p *PromParser) Metric(l *labels.Labels) string {
	// Copy the buffer to a string: this is only necessary for the return value.
	s := string(p.series)

	p.builder.Reset()
	p.builder.Add(labels.MetricName, s[:p.offsets[0]-p.start])

	for i := 1; i < len(p.offsets); i += 4 {
		a := p.offsets[i] - p.start
		b := p.offsets[i+1] - p.start
		c := p.offsets[i+2] - p.start
		d := p.offsets[i+3] - p.start

		value := s[c:d]
		// Replacer causes allocations. Replace only when necessary.
		if strings.IndexByte(s[c:d], byte('\\')) >= 0 {
			value = lvalReplacer.Replace(value)
		}
		p.builder.Add(s[a:b], value)
	}

	p.builder.Sort()
	*l = p.builder.Labels()

	return s
}
```
We can do label cache logic here, this need more function and performance test.

**Comment by abitduck** [comment]
This the easy label cache mode: https://github.com/abitduck/prometheus/commit/815e976761331ae3533bb8ab462c700aed9be010

Result:
* Memory from 43G to 20G
* CPU from 429% to 113%

**Comment by abitduck** [comment]
> I'm sorry, I don't seem to have got my point across. I'm suggesting something like:
> 
> ```
>  type Label struct { 
>  	Name, Value string 
>  } 
> 
> // A pair of indexes into the dictionary.
> type internalLabel struct {
> 	name  int64
> 	value int64
> }
>   
> // Labels is a sorted set of labels. Order has to be guaranteed upon
> // instantiation.
> type Labels []internalLabel
> ```
> 
> Compare here:
> 
> https://github.com/prometheus/prometheus/blob/7cd9f8a34030a0bdd56a49e80cc0d4f915f80deb/model/labels/labels_string.go#L41-L50
> 
> This is a completely different implementation of `labels.Labels`, but it has the same API - `Range()`, `Get()`, etc.

This the reason why ci-build failed, local `make test` don't have test with `-tags=stringlabels`

**Comment by abitduck** [comment]
> I'm sorry, I don't seem to have got my point across. I'm suggesting something like:
> 

Thanks for your patient explain, I got your point!

**Comment by abitduck** [comment]
need more work for rules optmize, close it first!

**Pull request closed without merging**
