### PR TITLE
Chore: Log segment number when segment read failed

### PR DESCRIPTION
**Pull request by gastonqiu**
To manually fix the WAL files, it is good to know where the corrupt
happened so we should log the segment number when the read failed.

Related Issue #7506

### CODE REVIEW

**Comment by roidelapluie** [comment]
Should'nt we return that with the function and a fmt.Errorf("segment %d: %w", err) ?

**Comment by gastonqiu** [comment]
You are right. It's better. 
> Should'nt we return that with the function and a fmt.Errorf("segment %d: %w", err) ?

**Comment by cstyan** [comment]
Julien is right, we should be adding this in via `errors.Wrap(...)`. The function calling `watcher.Run()` does nothing more than log the error and then call `Run` again, it doesn't care if the error is some assertable type.

**Comment by gastonqiu** [comment]
Will change it need some time.

**Comment by gastonqiu** [comment]
@cstyan @roidelapluie I change the code according to the review. Can you help me to review again? Hope I don't misunderstand you guys.

**Comment by gastonqiu** [comment]
@cstyan Are there any other reviewers can help on review this PR or it is fine to merge now?

**Pull request merged**
