### PR TITLE
Allow users of scrape manager to configure context and custom roundtripper

### PR DESCRIPTION
**Pull request by bogdandrutu**
Please let me know if you are ok with this, and what kind of tests you would like to see for this.

### CODE REVIEW

**Comment by brian-brazil** [comment]
What are you trying to do here? This is the user-facing config file, and users can't specify either of those object types.

**Comment by bogdandrutu** [comment]
I am using just the scraper component of the prometheus server, and would like to be able to configure extra things (like tracing, or special headers) for every request. Also I did use "-" to clarify that these configs are only possible when you start your own scraper.Manager

**Comment by brian-brazil** [comment]
We don't generally add code that we don't use, nor have non-config things in our config structs, in order to keep things maintainable. If there's something that makes sense in Prometheus terms, it could be added directly.

**Comment by bogdandrutu** [comment]
To make sure I understand your comment. Are you fine with adding these as options to the NewManager instead?

**Comment by beorn7** [comment]
We revisited this during the bug scrub. In general, hooking in contexts and such is something that we could accept even if it currently not used by core Prometheus. However, things like changing the config struct are a bit too invasive.

Sorry for letting this PR rot. At this point, if this is still a need of yours, please follow up here so that we can see what next steps could be. For now, we are closing this.

**Pull request closed without merging**
