### PR TITLE
Cut Prometheus 0.16.0.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
Pending docs issues that would be nice before release:

https://github.com/prometheus/docs/issues/232
https://github.com/prometheus/docs/issues/221

**Comment by juliusv** [comment]
@brian-brazil @fabxc @beorn7 @jimmidyson

**Comment by juliusv** [comment]
Ah, https://github.com/prometheus/docs/issues/221 is already done, great. So I think we're ready for cutting the release.

**Comment by fabxc** [comment]
:+1: :ship:

**Comment by jimmidyson** [comment]
Yay! Nice work.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
