### PR TITLE
Fix Dockerfile with the removal of tools/rulechecker

### PR DESCRIPTION
**Pull request by sdurrheimer**
@fabxc @juliusv

### CODE REVIEW

**Comment by fabxc** [comment]
:+1: Thanks

Sorry once more for forgetting the Dockerfile!

**Comment by grobie** [comment]
Time to add a test to run the docker container?

**Comment by fabxc** [comment]
That would be great – but to be realistic, I won't get to this any time soon. So hopefully people who are using the container images can step in. They would probably get this done much faster, too.

**Comment by sdurrheimer** [comment]
Actually I just proposed the same thing on IRC
> [21:17:44]  <sdurrheimer>	maybe it would be interesting to setup a automated build like the one with travis but for the dockerfile.

This can be done easily with CircleCI I guess.

**Comment by juliusv** [comment]
We already have Travis, so: https://twitter.com/juliusvolz/status/614187692390223873

**Pull request merged**
