### PR TITLE
Fix / -> /graph redirect when using a path prefix.

### PR DESCRIPTION
**Pull request by juliusv**
@fabxc

### CODE REVIEW

**Comment by fabxc** [comment]
:-1: 

No, the whole point of the router changes was to no longer hacking in the path prefix relentlessly. There must be a cleaner solution.

**Comment by juliusv** [comment]
Uh, well, you could add a `Redirect` method to the web router which would encapsulate the prefix? Or what would you have in mind to fix this more cleanly?

**Comment by fabxc** [comment]
That seems like a clean solution.

**Comment by juliusv** [comment]
@fabxc Added something like that. Let's see how you like it...

**Comment by fabxc** [comment]
Looks good, I would just call it `Redirect` though as the prefixing is generally transparent to the user of a router.

**Comment by juliusv** [comment]
Ja, was thinking that too, but then called it `PrefixedRedirect`, fearing that someone could use it wrongly for non-internal redirects. Not sure if that's so much clearer though. Just named it `Redirect` now.

**Comment by fabxc** [comment]
:+1:

**Pull request merged**
