### PR TITLE
Updated TSDB dependency to 0.9.0.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
Adjusting for interface changes now.

**Comment by krasi-georgiev** [comment]
and add the experimental WAL compression flag. 

see: https://github.com/prometheus/tsdb/pull/609#issuecomment-497030695

**Comment by codesome** [comment]
I am not sure if it is relevant here, but pointing out this issue https://github.com/prometheus/tsdb/issues/646

**Comment by csmarchbanks** [comment]
> I am not sure if it is relevant here, but pointing out this issue prometheus/tsdb#646

We are discussing/fixing that issue in IRC now.

> and add the experimental WAL compression flag.
I can update https://github.com/prometheus/prometheus/pull/5592 right after this is merged if we want to keep them separate. Either way is fine by me.

**Comment by bwplotka** [comment]
Happy for you @csmarchbanks to do update of TSDB in https://github.com/prometheus/prometheus/pull/5592 as you did majority of work :+1: 

Just point to 0.9.1 once we land the fix and relase TSDB. Does it make sense?

**Comment by csmarchbanks** [comment]
Sounds good, I will update once I see the 0.9.1 PR land :)

**Comment by bwplotka** [comment]
Also I guess we want to separate changes and actual enabling compression by default for benchmarks (?)

**Comment by csmarchbanks** [comment]
Yes, for 2.11 the default will be false (I will just remove the second commit on that branch)

**Pull request closed without merging**
