### PR TITLE
Refactor discovery

### PR DESCRIPTION
**Pull request by grandbora**
This pr does some small refactoring on discovery package:
* The only logical change is https://github.com/prometheus/prometheus/pull/3477/commits/13c23c6740acad393785838fd0acc866ca00a566. Code used to try to send a signal to the sync channel for each target group in an update. Sync channel is a buffered channel with size 1. So multiple signals doesn't have any effect. I changed the logic to send a signal per update.

* Mechanical change https://github.com/prometheus/prometheus/pull/3477/commits/5e0de7894a8c1429fbf558ac37ff840d72d404a7. Logic of binding to the updates of a TargetProvider is extracted to its own function.

* https://github.com/prometheus/prometheus/pull/3477/commits/871c5bcc207e251af74883bd4f69e7f72ab393f6 Tests fail immediately on timeouts.

Lastly, now that there is decent test coverage on this package, I am confident about the logical change.

### CODE REVIEW

**Comment by grandbora** [comment]
cc @brian-brazil @grobie @fabxc please have a look. Danke.

**Comment by grandbora** [comment]
ping @brian-brazil

**Comment by grandbora** [comment]
Hi, this is a small refactoring of a single unit test. This PR is sitting here for 3 days. I would appreciate if anyone can show some ❤️  cc @brian-brazil @fabxc @grobie

**Comment by grobie** [comment]
On my review list for the weekend.

**Comment by brian-brazil** [comment]
I believe this change is already (roughly) part of https://github.com/prometheus/prometheus/pull/3362

**Comment by brian-brazil** [comment]
I believe this is obsolete.

**Pull request closed without merging**
