### PR TITLE
Fix reporting wrong default value for retention flags

### PR DESCRIPTION
**Pull request by vitkovskii**
Hey :) As you added the feature of size-based retention you changed some logic in the command line parameters parsing. And it leads to reporting wrong flags values on `/flags` page and in api `/api/v1/status/flags`.

**Steps to reproduce**
1) Build prometheus `2.8.1`
2) Run prometheus locally with empty config `./prometheus --config.file=empty.yaml`
3) It logs `no time or size retention was set so using the default time retention`
4) Go to `localhost:9090/flags`
5) You should see `storage.tsdb.retention.time`/`storage.tsdb.retention` = `15d`, but it shows `0s`

**Why it happens?**
Because default value for retention duration is set simply to cfg: `cfg.tsdb.RetentionDuration = defaultRetentionDuration`

But source values for `/flags` and `/api/v1/status/flags` are taken from kingping flag values:
```
`a.Flag("storage.tsdb.retention.time", "...").SetValue(&oldFlagRetentionDuration)`
`a.Flag("storage.tsdb.retention.time", "...").SetValue(&newFlagRetentionDuration)`
 ```
Setting value to `cfg.tsdb.RetentionDuration` aren't affect `oldFlagRetentionDuration` and `newFlagRetentionDuration` so you see `0s` instead of `15d`.

@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
This is something we've actually already discussed, the /flags is what the user has passed in - not what we subsequently do with it.

**Comment by vitkovskii** [comment]
That would be the logic. But I don't pass `0s` to for `storage.tsdb.retention`. And don't pass `2h` for `storage.tsdb.min-block-duration` too. Why setting the default value in one case is shown as value and don't shown in other case? If kingpin sets the default value it will be on the page, but if you set it by hand it won't.

**Comment by vitkovskii** [comment]
Anyway thanks for the fast reply and for the explanation :)

**Comment by roidelapluie** [comment]
Note: we added retention info in the status page.

**Comment by roidelapluie** [comment]
You do not pass it but it is still the actual value.

**Comment by roidelapluie** [comment]
As the information is available in the status page, we have decided to close this PR.

**Pull request closed without merging**
