### PR TITLE
add a pull requests examples section

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by roidelapluie** [comment]
I would add a note saying that the exemples given might become out of date but should give a good impression about the areas touched by a new service discovery.

**Comment by remyleone** [comment]
@roidelapluie do you see other examples that might be useful?

**Comment by roidelapluie** [comment]
I think it is the only one which was merged after the split of the discoveries.

**Comment by roidelapluie** [comment]
Could you add the comment so we can merge? :tada:

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
