### PR TITLE
update mock code.

### PR DESCRIPTION
**Pull request by johncming**
make mock code simple.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1: 

CI is still being dodgy.

**Comment by johncming** [comment]
> 👍
> 
> CI is still being dodgy.

part of tests failed which are not `discovery` tests. How can I re-trigger the circle test.  Is there a command for it? 

Thank you.

**Comment by brian-brazil** [comment]
You can't trigger it, but I've done it for you. You can always force push a minor tweak to the PR.

**Comment by johncming** [comment]
> You can't trigger it, but I've done it for you. You can always force push a minor tweak to the PR.

ok.

**Comment by roidelapluie** [comment]
Can you please rebase this ? It should also fix the failing test. Thanks.

**Comment by roidelapluie** [comment]
implemented in #7725

**Pull request closed without merging**
