### PR TITLE
Fix updating rule manager never finishing

### PR DESCRIPTION
**Pull request by csmarchbanks**
Rather than sending a value to the done channel on a group to indicate
whether or not to add stale markers to a closing rule group use an
explicit boolean. This allows more functions than just run() to read
from the done channel and fixes an issue where Eval() could consume the
channel during an update, causing run() to never return.

cc: @roidelapluie @brian-brazil

### CODE REVIEW

**Comment by roidelapluie** [comment]
g.done doesn't have to be a chan bool anymore

**Comment by csmarchbanks** [comment]
> g.done doesn't have to be a chan bool anymore

Good catch, fixed!

**Comment by brian-brazil** [comment]
:+1:

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
