### PR TITLE
Update various UI components

### PR DESCRIPTION
**Pull request by SuperQ**
* Correct jquery version in prom.lib.
* Update to bootstrap 4.5.2.
* Bump yarn versions.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
Have you double checked locally that this does not introduce https://github.com/prometheus/prometheus/issues/7803 in the old web UI or prom.lib?

**Comment by SuperQ** [comment]
@juliusv No, I'll double check.

**Comment by SuperQ** [comment]
Looked at the issue, the change from 3.3.1 is for the console libraries, which from what I can tell are currently broken since we don't vendor the old version of jquery. This is just correcting the console libraries reference..

**Comment by juliusv** [comment]
Ah yeah, in `web/ui/templates/_base.html` it's just the bootstrap update.

:+1:

**Comment by roidelapluie** [comment]
Thanks for this!

**Pull request merged**
