### PR TITLE
web/api: Expose rule health and last error

### PR DESCRIPTION
**Pull request by mxinden**
Expose rule health and last evaluation error on `/api/v1/rules`.

//CC @noqcks

Follow up to https://github.com/prometheus/prometheus/pull/4457#pullrequestreview-143589537.

### CODE REVIEW

**Comment by mxinden** [comment]
Ping @juliusv @fabxc @brian-brazil

**Comment by gouthamve** [comment]
Actually, just noticed a minor race condition: https://github.com/prometheus/prometheus/blob/master/rules/alerting.go#L368-L369

These should use `r.SetHealth` and `r.SetLastError` else there is a race while accessing the same via the API.

**Comment by simonpasquier** [comment]
@gouthamve in fact not, see https://github.com/prometheus/prometheus/commit/b7e2f407ded76644edc97957c6e8e611a64ea29d

**Comment by mxinden** [comment]
@gouthamve @simonpasquier thanks for the feedback. Any further concerns?

**Comment by gouthamve** [comment]
Nope, this is good to go :)

**Comment by gouthamve** [comment]
I think two reviews from `-team` would be enough. Usually people won't approve the change unless they are pretty confident about it.

Having a maintainer approve every single PR in a repo like `prometheus/prometheus` would be too much to ask, if you ask me.

**Comment by brian-brazil** [comment]
> Usually people won't approve the change unless they are pretty confident about it.

That's not the case for all of -team. In this case I believe you have gotten sufficient review.

**Comment by mxinden** [comment]
Thanks for clarifying!

**Pull request merged**
