### PR TITLE
synchronize makefile.common for community

### PR DESCRIPTION
**Pull request by roidelapluie**
cc @simonpasquier 

some repos in community use this: https://github.com/prometheus-community/stackdriver_exporter/blob/master/Makefile.common

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
We also need to provide appropriate rights to @prombot

**Comment by roidelapluie** [comment]
Apparently this is already the case.

**Comment by SuperQ** [comment]
prombot already has write to everything in prometheus-community.

**Comment by simonpasquier** [comment]
:+1:

**Pull request merged**
