### PR TITLE
agent: make the global hash lookup table smaller

### PR DESCRIPTION
**Pull request by bboreham**
This is the same change made in #13040, plus subsequent improvements, applied to agent-mode code.

Brought in some tests too, adapted for the different API.

### CODE REVIEW

**Review by jesusvazquez — APPROVED** [review]
This is looking good to me @bboreham I understand that running prombench wont yield any results here because this is agent code but I let you chose if you want to run it anyway.

**Review by bwplotka — APPROVED** [review]
LGTM, have you benchmarked it somewhere? I bet you did, do you mind sharing screenshots for future reference? (:

**Comment by bboreham** [comment]
I added a benchmark:

```
name            old time/op    new time/op    delta
CreateSeries-8     593ns ± 5%     526ns ± 5%  -11.20%  (p=0.002 n=6+6)

name            old alloc/op   new alloc/op   delta
CreateSeries-8      254B ± 1%      177B ± 6%  -30.19%  (p=0.004 n=5+6)

name            old allocs/op  new allocs/op  delta
CreateSeries-8      2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.002 n=6+6)
```

**Comment by bboreham** [comment]
Got a lint error from a file I didn't change, so rebased and force-pushed.

**Comment by bboreham** [comment]
Lint error should be fixed by #13343

**Pull request merged**
