### PR TITLE
Add vetting to default make target

### PR DESCRIPTION
**Pull request by fabxc**

### CODE REVIEW

**Comment by fabxc** [comment]
Seriously confused about the failing CI. The vetting fails on cases of slice types using "unkeyed fields", which doesn't make sense.

Also it passes locally for the apparently same Go version.

**Comment by juliusv** [comment]
I get the same vetting errors locally too with Go 1.5.1. See this bug why that's expected even in cases where you're not even using unkeyed fields: https://github.com/golang/go/issues/6820#issuecomment-66088420. If you really want to require `go vet` in the `all` target and thus in the CI, we'll at least need to turn off the `composite literal uses unkeyed fields` warnings by using `go tool vet -composites=false`. `go tool vet` takes a list of file names and not packages though (unlike `go vet`), so that would need to be adjusted in the Makefile as well.

**Comment by juliusv** [comment]
Btw., from https://golang.org/cmd/vet/:

"Note that the tool does not check every possible problem and depends on unreliable heuristics so it should be used as guidance only, not as a firm indicator of program correctness."

So we can expect some other erroneous errors to pop up in the future. As long as that doesn't happen too often, it's probably worth it to keep in the `all` target.

**Comment by juliusv** [comment]
Woops, that was the wrong quote from that page (basically, the reverse). I meant this:

"Vet uses heuristics that do not guarantee all reports are genuine problems, but it can find errors not caught by the compilers."

**Comment by fabxc** [comment]
Mh, maybe not the best idea after all. Building a habit of running it more
frequently manually seems to be better.

**Comment by fabxc** [comment]
Removed `vet` from `all`. Rest should still be changed.

**Comment by matthiasr** [comment]
:+1:

**Pull request merged**
