### PR TITLE
tsdb: add default logger for writeMetaFile.

### PR DESCRIPTION
**Pull request by johncming**
Add a default logger for writeMetaFile.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Not sure it is worth it as this is a unexported function.

**Comment by roidelapluie** [comment]
Yeah I would limit that to public functions.

**Comment by johncming** [comment]
`logger` as a parameter should handle nil situation, function or method is a black box even if it's private.

It's easy and appropriate for a method to avoid `nil logger` as `logger` can be a field of the class. But way to function looks like tricky.

Another way in other projects use the package level logger may be a better way to handle nil logger rather than simply relying on conventions.

**Comment by johncming** [comment]
> Checking for `nil` logger in _all_ methods looks does not smell that good to me. As @roidelapluie said, this is better to be limited only to public methods.

Yes, I agree with it now after review some code likes this. I will close the pr.

**Pull request closed without merging**
