### PR TITLE
Consoles: Fix broken Node Overview page

### LINKED ISSUE #8876: Broken consoles CSS layout
**What did you do?**

- Downloaded and unpacked prometheus-2.27.1.linux-amd64
- Downloaded and unpacked node_exporter-1.1.2.linux-amd64
- Started the node exporter `./node_exporter`
- Appended the following lines to the `prometheus.yml` (for the node exporter):
```yaml
  - job_name: 'node'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9100']
```
- Started Prometheus: `./prometheus`
- Navigated to http://localhost:9090/consoles/index.html.example in the browser

**What did you expect to see?**

Some nice dashboards for my jobs.

**What did you see instead? Under which circumstances?**

The layout works kinda (the short menu looks strange) in the Prometheus instance overview:
Acceptable layout for an dashboard

But at the node exporter example, the layout falls completely apart, as the first graph got pushed to the right and **the overview table is now at the bottom of the page after all graphs**:
The right column not shown

**Environment**

* System information:

Linux 5.12.6-arch1-1 x86_64
Firefox 88.0.1 (also tested with Chromium 91.0.4472.77)

* Prometheus version:

prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64

* Alertmanager version:

not used 

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9100']
```

* ~~Alertmanager configuration file:~~

* Logs: No useful logs

### PR DESCRIPTION
**Pull request by LeviHarrison**
This was just a matter of rearranging the components on the Node Overview page to match the layout of the Prometheus Overview page. I also removed an unneeded closing tag.

Fixes #8876

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks, do you want to fix node-disk.html as well while you are at it?

**Comment by roidelapluie** [comment]
node-cpu also seems to have an issue with the graph going behind the menu :/

**Comment by LeviHarrison** [comment]
Sure, I'll take a look.

**Comment by LeviHarrison** [comment]
I found what might have been the issue you saw, but only for a second across _all_ node pages. It only covered the very top, so I'm not sure if that's what you were referring to.

**Comment by LeviHarrison** [comment]
I believe the issue with the menu behind the graph is fixed now, or at least I can't reproduce it.

**Comment by roidelapluie** [comment]
node1
node2


I still see the glitch, and on the CPU page I see it also but not every time O_o

**Comment by LeviHarrison** [comment]
It was intermittent but then I stopped seeing it and thought I had solved it

**Comment by LeviHarrison** [comment]
I can't reproduce, although I know it's there

**Comment by roidelapluie** [comment]
Okay, I will try to have another look. I think some pages still have unclosed html tags.

**Comment by LeviHarrison** [comment]
Yeah, I can go over and try to fix some of that stuff.

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
