### PR TITLE
Merge 2.55 into main

### PR DESCRIPTION
**Pull request by bboreham**
Merge release-2.55 branch into main.

Many changes are no longer new in 3.0 (though some, such as UTF-8, have another [CHANGE] line noting they are on by default in 3.0).

Some CHANGELOG edits were previously discussed at #14922.

### CODE REVIEW

**Comment by bboreham** [comment]
Commit 0d22a91267e5520cdf130517cbcfbcb5b6088318 lacks DCO; I don't know why that wasn't picked up before.
We'll have to ignore it to merge; not going to go back and edit branch 2.55 now.

**Comment by aknuds1** [comment]
JavaScript build fails:

> 6:54:42 PM: npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
6:54:42 PM: npm ERR!
6:54:42 PM: npm ERR! Invalid: lock file's @prometheus-io/codemirror-promql@0.54.1 does not satisfy @prometheus-io/codemirror-promql@0.55.0-rc.0
npm ERR! Invalid: lock file's @prometheus-io/lezer-promql@0.54.1 does not satisfy @prometheus-io/lezer-promql@0.55.0-rc.0

**Comment by aknuds1** [comment]
I can try to fix the JS build failure tomorrow.

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Comment by bboreham** [comment]
Thanks; I overwrote my attempt with yours to avoid two 9,000-line commits.

**Comment by aknuds1** [comment]
> Thanks; I overwrote my attempt with yours to avoid two 9,000-line commits.

All the better :)

**Pull request merged**
