### PR TITLE
Initial local pods before using the pod list to initialize pod targets

### PR DESCRIPTION
**Pull request by pdbogen**
Small but important change; the local cache of pods should be updated/initialized before initializing the list of targets; prior to this change it was only updated/initialized when beginning a node watch.

### CODE REVIEW

**Comment by grobie** [comment]
We should get some tests in place for the integration.

**Comment by fabxc** [comment]
Which probably requires a significant refactor to be doable. We should break out the distinct discoveries (node, endpoint, pod) and expose them in the configuration.

**Comment by pdbogen** [comment]
Agreed on all counts. I'll take a look at doing some refactoring with an eye towards testability, but in the mean time this change is a break-fix; without this change, pods that exist at the time Prometheus initializes discovery will not be discovered until some kind of change to the pod occurs. 

On June 2, 2016 11:24:11 PM PDT, Fabian Reinartz <notifications@github.com> wrote:
>Which probably requires a significant refactor to be doable. We should
>break out the distinct discoveries (node, endpoint, pod) and expose
>them in the configuration.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/prometheus/prometheus/pull/1702#issuecomment-223500543

-- 
Patrick Bogen

**Comment by matthiasr** [comment]
👍 

let's fix the issue we know exists for now.

**Comment by fabxc** [comment]
Alright, thanks! 👍

**Pull request merged**
