### PR TITLE
promql: Exposed parsing and using test commands, so Thanos/Cortex can reuse the same language.

### PR DESCRIPTION
**Pull request by bwplotka**
This is the extremely nice framework I would love to leverage for future query pushdown tests on Thanos 🤗 

Related to https://github.com/thanos-io/thanos/pull/3631

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
I love this ; is out test format documented? Should it?

**Comment by bwplotka** [comment]
It is not 🙈 

I can add more comments, but let's attack format docs in separate PR maybe. Also, feedback welcome on how. Just comment in `Test struct`, maybe?

**Comment by brian-brazil** [comment]
How exactly are you thinking of using this?

This is our internal testing for testing PromQL itself, it's not exposed to users, and it's not suitable for more general use as among other things it's doing extensive self-consistency tests that would only be a waste of CPU for a user. If anything we should be getting rid of this in favour of what promtool is using - though still with our extra consistency tests.

If you need PromQL unittests, look at promtool.

**Comment by bwplotka** [comment]
Happy to elaborate how. The idea is that we want to make sure PromQL is accurate for Thanos, Cortex etc Especially when we start doing query pushdown for certain things.

Now we want to simulate in Thanos various cases we talked in the [design doc](https://docs.google.com/document/d/1ajMPwVJYnedvQ1uJNW2GDBY6Q91rKAw3kgA5fykIRrg/edit#):

* Series Within Single Node
* Series Distributed across Nodes Horizontally
* Distinct Series Distributed across Nodes Vertically
* Series one-to-one replicated  
* Series Realistically replicated 

Current format of this test framework only allows simulating ` Series Within Single Node`. This is fine for Prometheus. However with very simple (one new command addition). I can actually create tests simulating ALL of those cases. I propose this on Thanos only (for now), but probably we could also adapt it here in Prometheus to test remote read merging (: 

Happy to discuss this.

The way I currently propose this in Thanos is new command `store <matchers> <mint> <maxt>` which allows to say "Now next `load` commands are for this particular store". So then it's as easy as:

```
store {} 0 50

load 5m
  http_requests{job="api-server", instance="0", group="production"} 0+10x10
  http_requests{job="api-server", instance="1", group="production"} 0+20x10
  http_requests{job="api-server", instance="0", group="canary"}   0+30x10
  http_requests{job="api-server", instance="1", group="canary"}   0+40x10

store {} 50 9999

load 5m
  http_requests{job="api-server", instance="0", group="production"} 0+10x10
  http_requests{job="api-server", instance="1", group="production"} 0+20x10
  http_requests{job="api-server", instance="0", group="canary"}   0+30x10
  http_requests{job="api-server", instance="1", group="canary"}   0+40x10

store {} 0 50

load 5m
  http_requests{job="app-server", instance="0", group="production"} 0+50x10
  http_requests{job="app-server", instance="1", group="production"} 0+60x10
  http_requests{job="app-server", instance="0", group="canary"}   0+70x10
  http_requests{job="app-server", instance="1", group="canary"}   0+80x10

store {} 50 9999

load 5m
  http_requests{job="app-server", instance="0", group="production"} 0+50x10
  http_requests{job="app-server", instance="1", group="production"} 0+60x10
  http_requests{job="app-server", instance="0", group="canary"}   0+70x10
  http_requests{job="app-server", instance="1", group="canary"}   0+80x10

load 5m
  foo{job="api-server", instance="0", region="europe"} 0+90x10
  foo{job="api-server"} 0+100x10

# Simple sum.
eval instant at 50m SUM BY (group) (http_requests{job="api-server"})
  {group="canary"} 700
  {group="production"} 300
  ...
```

Plus it's compatible with Prometheus format. It would ideal to have Prometheus supporting this `store` but let's start small (: 

> This is our internal testing for testing PromQL itself, it's not exposed to users, and it's not suitable for more general use as among other things it's doing extensive self-consistency tests that would only be a waste of CPU for a user. If anything we should be getting rid of this in favor of what promtool is using - though still with our extra consistency tests.

Hm... It sounds like a duplicated effort indeed. I think then it would be amazing to add GH issue to move those tests to promtool unit tests format. And have promql self define those really (and promtool only imports those). Would that be correct direction?

Also it's bit harder to make unittest format multi-node, but doable. Do you think we can make it multi node (e.g for fanout remote read testing and ofc for Thanos, Cortex)?

**Comment by brian-brazil** [comment]
> And have promql self define those really (and promtool only imports those). Would that be correct direction?

Something like that. Having config structs in PromQL would be a bit weird, but I'm sure we can work it out.

> Also it's bit harder to make unittest format multi-node, but doable. Do you think we can make it multi node (e.g for fanout remote read testing and ofc for Thanos, Cortex)?

It's the exact same format, just written differently. If you want to do some more complicated stateful integration testing on top of it, there's nothing stopping you defining a config struct on top of all this over in Thanos.


We should wait until #8121 is in before touching any of this stuff, as it's both touch this code and adding lots of tests.

**Comment by bwplotka** [comment]
Cool, happy with this direction. Let's close this for now then.

**Pull request closed without merging**
