### PR TITLE
Followup on OpenTelemetry migration

### PR DESCRIPTION
**Pull request by roidelapluie**
- tracing_config: Change with_secure to insecure, default to true.
- tracing_config: Call SetDirectory to make TLS certificates relative to the Prometheus
  configuration
- documentation: Change bool to boolean in the configuration
- documentation: document type float
- tracing: Always restart the tracing manager when TLS config is set to
  reload certificates
- tracing: Always set TLS config, which could be used e.g. in case of
  potential redirects.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @matej-g

**Comment by LeviHarrison** [comment]
> tracing_config: Change with_secure to insecure, default to true.

The OLTP exporter specification seems to say that insecure should default to `false` (only for GRPC though?, https://opentelemetry.io/docs/reference/specification/protocol/exporter/#configuration-options). I don't really have an opinion, but I thought I'd point it out.

**Review by LeviHarrison — APPROVED** [review]
Thanks!

**Review by matej-g — COMMENTED** [review]
Late to the party, but looking good, thanks for picking up the remainder :+1:

**Comment by roidelapluie** [comment]
There is still #10225 :)

**Pull request merged**
