### PR TITLE
retrieval: Clean up target group map on config reload

### PR DESCRIPTION
**Pull request by beorn7**
Also, remove unused `providers` field in targetSet.

If the config file changes, we recreate all providers (by calling
`providersFromConfig`) and retrieve all targets anew from the newly
created providers. From that perspective, it cannot harm to clean up
the target group map in the targetSet. Not doing so (as it was the
case so far) keeps stale targets around. This mattered if an existing
key in the target group map was not overwritten in the initial fetch
of all targets from the providers. Examples where that mattered:

```
scrape_configs:
- job_name: "foo"
  static_configs:
  - targets: ["foo:9090"]
  - targets: ["bar:9090"]
```
updated to:
```
scrape_configs:
- job_name: "foo"
  static_configs:
  - targets: ["foo:9090"]
```

`bar:9090` would still be monitored. (The static provider just
enumerates the target groups. If the number of target groups
decreases, the old ones stay around.

```
scrape_configs:
- job_name: "foo"
  dns_sd_configs:
  - names:
    - "srv.name.one.example.org"
```
updated to:
```
scrape_configs:
- job_name: "foo"
  dns_sd_configs:
  - names:
    - "srv.name.two.example.org"
```

Now both SRV records are still monitored. The SRV name is part of the
key in the target group map, thus the new one is just added and the
old ane stays around.

Obviously, this should have tests, and should have tests before, not
only for this case. This is the quick fix. I have created
https://github.com/prometheus/prometheus/issues/1906 to track test
creation.

Fixes https://github.com/prometheus/prometheus/issues/1610 .

@matthiasr @fabxc

### CODE REVIEW

**Comment by grobie** [comment]
👍

**Comment by fabxc** [comment]
Yes, not adding tests for this was a oversight/mistake.
This shouldn't imply that we push fixes without any tests reproducing a rather severe problem and proving it fixed.

**Comment by matthiasr** [comment]
I posted an end-to-end repro case on #1610.

**Comment by beorn7** [comment]
I did the lame "test it in production" approach, which is of course not good.
Since my docker skills are too weak to run a custom binary in a given image, I couldn't directly run @matthiasr `s test, but I recreated the same thing manually.

@matthiasr Just mounting the binary and running it results in "file not found". Perhaps you can help me with that.

@fabxc Are you up for writing tests? You are more familiar with the code, and I don't really have bandwidth, but this problem is hurting right now.

**Comment by fabxc** [comment]
I don't have infinite bandwidth either. FWIW, the amount of things being
forwarded to me due to familiarity with code-base is absolutely not
sustainable/manageable for me right now.

**Comment by beorn7** [comment]
Meanwhile, I got Docker lessons from MR. The dockerized version from MR's gist is able to reproduce the bug and the fix.

To hit three birds with one stone, I created a 1.1 pre-release for SC use with Go1.7. This is canarying right now on a couple of SC production servers, testing (1) this fix, (2) the code in master (to be released as 1.1 soon), (3) Go1.7 compiled code.

@fabxc As nobody seems to have time to fill the testing gap, I'm for merging this just based on "testing in production". That's obviously bad, but it's even worse to leave a pretty relevant bug out there.

**Comment by matthiasr** [comment]
:+1: I think confirming the fix is the good enough given the resources available.

**Comment by grobie** [comment]
If this is blocking a v1.1.0 release, I'd rather release it without tests and add them afterwards. Releasing v1.1.0 during PromCon would be cool :)

**Comment by beorn7** [comment]
1.1 would be cool indeed, but I'm right now worried about 1.0 where many users are affected by the bug right now.

In different news, the canary servers behave normally.

@fabxc Do you want to uphold your objection? Otherwise, I'd like to release a 1.0.2 bugfix release today. For 1.1, it would be nice to wait for @brian-brazil `s time functions.

**Comment by fabxc** [comment]
go ahead

**Pull request merged**
