### PR TITLE
Vendoring update prior to 1.6 release

### PR DESCRIPTION
**Pull request by beorn7**
Mostly needed for summaries without quantiles. (There are a few that have useless quantiles right now.)

@stuartnelson3

### CODE REVIEW

**Comment by brian-brazil** [comment]
Hmm, do you see what has broken Travis? I can't spot it in the logs.

**Comment by stuartnelson3** [comment]
Yeah I couldn't spot anything either

**Comment by grobie** [comment]
```
curl -s https://s3.amazonaws.com/archive.travis-ci.org/jobs/220912966/log.txt | grep -v level=info

...
time="2017-04-11T11:01:48Z" level=warning msg="Series quarantined." fingerprint=2ee1bef294b33c11 metric=test{n1="v3"} reason="size of series file for fingerprint 2ee1bef294b33c11 is 49, which is not a multiple of the chunk length 1041" source="storage.go:1880"
time="2017-04-11T11:01:59Z" level=warning msg="Storage has entered rushed mode." chunksToPersist=6 memoryChunks=852 source="storage.go:1842" urgencyScore=1
FAIL    github.com/prometheus/prometheus/storage/local  52.934s
...
```

I couldn't find a real test error message either.

**Comment by beorn7** [comment]
Rerunning…

**Comment by beorn7** [comment]
Tadaa!

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
