### PR TITLE
web/api/v1: fix optional skip_head for snapshot

### LINKED ISSUE #4671: Snapshot API no longer works without a `skip_head` parameter
## Bug Report
**What did you do?**
Run `curl -XPOST http://localhost:9090/api/v1/admin/tsdb/snapshot`
**What did you expect to see?**
No errors, this worked ok in 2.3.2. Adding `?skip_head=false` to the query fixed the problem
**What did you see instead? Under which circumstances?**
`{"status":"error","errorType":"unavailable","error":"unable to parse boolean 'skip_head' argument: strconv.ParseBool: parsing \"\": invalid syntax"}`
**Environment**

* System information:
Windows 7 SP 1

* Prometheus version:
2.4.2 revision c305ffaa092e94e9d2dbbddf8226c4813b1190a0

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #4671

I started to add a unit test but this would involve quite a bit of refactoring in the unit tests. It would be beneficial to add more tests for the other admin actions too so I propose to tackle it in `master` once this gets merged back.

### CODE REVIEW

**Comment by simonpasquier** [comment]
cc @gouthamve another fix for `release-2.4`

**Comment by gouthamve** [comment]
Can we add a test for this somehow? If it is not trivial, it's okay.

**Comment by simonpasquier** [comment]
I had a look but it requires a bit of rework so I suggest (and commit :sweat_smile:) to do it in `master` once this is merged.

**Comment by simonpasquier** [comment]
@gouthamve friendly ping :smirk:

**Pull request merged**
