### PR TITLE
Adding the option to scrape per network

### PR DESCRIPTION
**Pull request by shirpx**
Currently it's not possible to filter GCE by network, 
GCE API does not support filtering on the fields of repeated message fields.
Public Issue Tracker: https://issuetracker.google.com/issues/73455339

in the mean time this PR will allow to filter by network

### CODE REVIEW

**Comment by brian-brazil** [comment]
This appears to be custom client-side filter logic, if you're looking to do something like this it should be done via relabelling rather than each SD reinventing ways to do arbitrary target manipulation. To me it looks like the required metadata is already available to relabelling for this, but if not it can be  added.

**Comment by shirpx** [comment]
you are right that its can be done through relabelling, 
but when trying to filter out with !=  it does not find instances that doesn't have the network label configured.
`filter: 'labels.network!=example-vpc'`
that means that we need to add network label to every instance which is ok for some envs but for us its a problem in our current setup (huge env and all baked) which brought me to do this PR.
thought others might find this useful, but maybe its only good for our use case. thanks anyway.

**Comment by brian-brazil** [comment]
I'm not familiar with this part of GCE, but relabelling can match the empty string as it's using regexes. So you shouldn't need to change anything about your setup, only choose appropriate relabelling actions.

**Comment by shirpx** [comment]
unfortunately, i checked and if the label doesn't exist it doesn't catch the instance.
(feel free to check as well through the API - https://cloud.google.com/compute/docs/reference/rest/v1/instances/list)
but, back to the pr, don't you think that network is a basic thing that should be configured the same as zone and not as a label?

**Comment by brian-brazil** [comment]
> unfortunately, i checked and if the label doesn't exist it doesn't catch the instance.

I don't understand what you mean here, I've not worked with this bit of GCE.

> don't you think that network is a basic thing that should be configured the same as zone and not as a label?

I also don't know this, however I know that any filtering like this should be done with relabelling. If we lack 
the metadata to make that possible today I'm open to adding it.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and per the above this appears to be doing something that is already possible via relabelling on the `__meta_gce_network` label so we're going to close there. If however there is metadata we're missing we'd appreciate a PR to add it.

**Pull request closed without merging**
