### PR TITLE
rules, alerts api

### PR DESCRIPTION
**Pull request by mg03**
This PR provides api/v1rules and api/v1/alerts endpoints. It takes into consideration the rules groups and alerts per rule/group. ( This is a follow up attempt to closed PR #2600 )

`curl -s localhost:9090/api/v1/alerts | jq '.'`
```json
{
  "status": "success",
  "data": {
    "alertgrp": [
      {
        "name": "R1file2",
        "query": "up != 2",
        "duration": "10s",
        "annotations": {
          "dashboard": "http://grafana.com/somelink",
          "description": "rule1 in file 2",
          "summary": "rule1 in file 2"
        },
        "alerts": [
          {
            "labels": {
              "alertname": "R1file2",
              "env": "test",
              "instance": "localhost:9091",
              "job": "prom",
              "severity": "high"
            },
            "status": "firing",
            "activesince": "2017-11-01T08:03:50.13947789-07:00"
          },
          {
            "labels": {
              "alertname": "R1file2",
              "env": "test",
              "instance": "localhost:9090",
              "job": "prometheus",
              "severity": "high"
            },
            "status": "firing",
            "activesince": "2017-11-01T08:03:50.13947789-07:00"
          }
        ]
      },
      {
        "name": "HighErrors",
        "query": "(100 - (avg(irate(node_cpu{mode=\"idle\",name=\"node-exporter\"}[5m])) BY (instance) * 100)) > 75",
        "duration": "5m0s",
        "annotations": {
          "description": "{{$labels.instance}}:CPU usage is above 75% (current value is:{{ $value }})"
        },
        "alerts": null
      },
      {
        "name": "R1file1",
        "query": "up{job=\"prometheus\"} == 1",
        "duration": "2m0s",
        "annotations": {
          "dashboard": "http://grafana.com/somelink",
          "description": "rule1 in file 1",
          "summary": "rule1 in file 1"
        },
        "alerts": [
          {
            "labels": {
              "alertname": "R1file1",
              "env": "prod",
              "instance": "localhost:9090",
              "job": "prometheus",
              "severity": "high"
            },
            "status": "pending",
            "activesince": "2017-11-01T08:03:48.231826644-07:00"
          }
        ]
      },
      {
        "name": "R2file1",
        "query": "up{job=\"prom\"} == 0",
        "duration": "2m0s",
        "annotations": {
          "dashboard": "http://grafana.com/somelink",
          "description": "rule2 in file 1",
          "summary": "rule2 in file 1"
        },
        "alerts": [
          {
            "labels": {
              "alertname": "R2file1",
              "env": "prod",
              "instance": "localhost:9091",
              "job": "prom",
              "severity": "critical"
            },
            "status": "pending",
            "activesince": "2017-11-01T08:03:48.231826644-07:00"
          }
        ]
      }
    ]
  }
}
```

------

`curl -s localhost:9090/api/v1/rules | jq '.'`
```json
{
  "status": "success",
  "data": {
    "groups": [
      {
        "name": "rule_grp2",
        "file": "/home/user/allrules/grp2_rules.yml",
        "rules": [
          {
            "rule": "alert: R1file2\nexpr: up != 2\nfor: 10s\nlabels:\n  env: test\n  severity: high\nannotations:\n  dashboard: http://grafana.com/somelink\n  description: rule1 in file 2\n  summary: rule1 in file 2\n"
          }
        ]
      },
      {
        "name": "grp3",
        "file": "/home/user/allrules/grp3_rules.yml",
        "rules": [
          {
            "rule": "record: instance:errors:rate5m\nexpr: rate(errors_total[5m])\n"
          },
          {
            "rule": "record: instance:requests:rate5m\nexpr: rate(requests_total[5m])\n"
          },
          {
            "rule": "alert: HighErrors\nexpr: (100 - (avg(irate(node_cpu{mode=\"idle\",name=\"node-exporter\"}[5m])) BY (instance)\n  * 100)) > 75\nfor: 5m\nlabels:\n  severity: critical\nannotations:\n  description: '{{$labels.instance}}:CPU usage is above 75% (current value is:{{ $value\n    }})'\n"
          }
        ]
      },
      {
        "name": "rule_grp1",
        "file": "/home/user/allrules/grp1_rules.yml",
        "rules": [
          {
            "rule": "alert: R1file1\nexpr: up{job=\"prometheus\"} == 1\nfor: 2m\nlabels:\n  env: prod\n  severity: high\nannotations:\n  dashboard: http://grafana.com/somelink\n  description: rule1 in file 1\n  summary: rule1 in file 1\n"
          },
          {
            "rule": "alert: R2file1\nexpr: up{job=\"prom\"} == 0\nfor: 2m\nlabels:\n  env: prod\n  severity: critical\nannotations:\n  dashboard: http://grafana.com/somelink\n  description: rule2 in file 1\n  summary: rule2 in file 1\n"
          }
        ]
      }
    ]
  }
}
```

@fabxc @brian-brazil - please provide your feedback , thanx

### CODE REVIEW

**Comment by mg03** [comment]
@fabxc @brancz : any thoughts / feedback

**Comment by Jaware** [comment]
seem like only rule  list,no creating rule api?

**Comment by mg03** [comment]
@Jaware : 2 endpoints api/v1/rules and api/v1/alerts have been implemented in this PR

**Comment by davkal** [comment]
I'm curious what the state of this PR is. It could enable a UX like the one below that I wish I have had available last week when writing rules for dashboards:
Expand recording rules

**Comment by mg03** [comment]
@davkal - I was awaiting feedback from either the owners/contributors/or someone with merge privileges .. If this is a feature which is still interesting to the project I can work on fixing the conflicts (there were none when I submitted the PR) ...

**Comment by davkal** [comment]
I think fixing conflicts is always good idea. As for further feedback, perhaps @Gouthamve has some?

**Comment by mg03** [comment]
@davkal : looks like #3656 does a similar thing.

**Comment by simonpasquier** [comment]
@mg03 are you still working on this?

**Comment by mg03** [comment]
@simonpasquier : i can but i saw that #3656 does a similar thing . so i dont know how to proceed. I asked for feedback and I am open to working on this and incorporating this into the v2 api. But I need to get guidance as to if this is needed and/or if something is missing in my PR , etc .

**Comment by simonpasquier** [comment]
@mg03 I've asked about the status of https://github.com/prometheus/prometheus/pull/3656 but no response yet.
I think your PR is going in the right direction so it would be good if you could rebase it to fix the conflicts. AFAIU there's no need adding it to the v2 API.

**Comment by mg03** [comment]
@simonpasquier : ok i can work on it later half of the week and get the PR ready . thanx

**Comment by mg03** [comment]
@simonpasquier : this one is closed. Replacement PR is #4012 . Let me know what you think.

**Pull request closed without merging**
