### PR TITLE
Fixes #6127 : Add Collapse all button

### LINKED ISSUE #6127: feature: add collapse/expand all button to ui target page
The ui target page can contain a lot of different scrape jobs which can be collapsed to give a good overview.
What is missing is a collapse and expand all targets button to help navigate to targets on is interested in quickly.

In our case we have prometheus configurations with many jobs, some of them have thousands of scrape targets. Be default on first visit all targets are expanded and one has to scroll many pages to get to a target one wants to check. After the first visit the collapsed jobs are stored in the browser which makes it ok, but if you have many different prometheus instances you have to do a of clicks each time you visit a new one.

### PR DESCRIPTION
**Pull request by djmgit**
The collapse all option as suggested in the corresponding issue
has been implemented in this PR.

### CODE REVIEW

**Comment by djmgit** [comment]
@bwplotka DCO issue is fixed.

**Comment by djmgit** [comment]
@roidelapluie my bad, I have removed those debug statements.

**Comment by djmgit** [comment]
The windows test is failing due to the following testcase failure:

```
=== RUN   TestMetricsUpdate
*** Test killed: ran too long (10m0s).
FAIL	github.com/prometheus/prometheus/rules	600.051s
=== RUN   TestPopulateLabels
--- PASS: TestPopulateLabels (0.00s)
```

**Comment by djmgit** [comment]
@roidelapluie do I need to make any more changes?

**Comment by bwplotka** [comment]
I restarted job. Can you provide some screenshots / GIF here how it looks at the end? (: 

Fixes #6127

**Comment by djmgit** [comment]
prom_sample

@bwplotka

**Comment by roidelapluie** [comment]
I desagree that it fixes #6127. I think we should close 6127 when we have it in the new ui too.

**Comment by roidelapluie** [comment]
Can we align the button with the other buttons? it seems a bit off now.

**Comment by djmgit** [comment]
@roidelapluie sure, I will try to do that.

**Comment by djmgit** [comment]
prom2

@roidelapluie The collapse button has been aligned.

Once this is done, I would give a try at the react app.

**Comment by djmgit** [comment]
@roidelapluie do I need to make any other change?

**Comment by mattmendick** [comment]
Just saw an issue I created (was a dupe) is fixed by this. Is there any reason why this can't be approved?

**Comment by roidelapluie** [comment]
@juliusv Can you look if this pull request can be merged?

**Comment by juliusv** [comment]
@djmgit Happy to merge this, but please be aware that this only changes the old UI, not the new React UI under https://github.com/prometheus/prometheus/tree/master/web/ui/react-app. So this functionality will disappear when we delete the old UI, unless it is added to the React UI as well.

**Pull request merged**
