### PR TITLE
zookeeper: change upstream to github.com/go-zookeeper/zk

### PR DESCRIPTION
**Pull request by roidelapluie**
A first step for #2914

At least that upstream is still being worked on. The last release was 10 days ago.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by roidelapluie** [comment]
Let's wait for #7551 first

**Comment by roidelapluie** [comment]
Hello @jjneely , are you interested in trying this one out? Thanks!

**Comment by roidelapluie** [comment]
I have rebased, planning to merge on green.

**Review by SuperQ — APPROVED** [review]
LGTM

**Pull request merged**
