### PR TITLE
Prometheus CLI: remove no-default-scrape-port featureFlag

### LINKED ISSUE #13959: --enable-feature: Consider removing no-default-scrape-port
### Proposal

Please consider if the behavior enabled with `--enable-feature=no-default-scrape-port` should become the default behavior in Prometheus 3.x /cc @roidelapluie @LeviHarrison

### PR DESCRIPTION
**Pull request by jackma-00**
Fixes #13959

### CODE REVIEW

**Comment by bboreham** [comment]
I’m unclear whether this PR does what was originally proposed. 

Reading back through the issues, it seems the problem was adding a port to the Host header. But it looks like this flag changes whether it is added to the target address. 

Does it work?  Does it double up all series due to a new value for `instance`?

**Comment by bboreham** [comment]
My gut is that post-beta is too late to make such a sweeping change. 

Maybe inverting the feature flag to be on by default is OK, if someone tested it and assures us it’s safe. 

@beorn7 you asked for it - what do you think?

**Comment by beorn7** [comment]
I have very little skin in this game. I only "asked" for it because I tried to gather information provided by others.
@roidelapluie might have more context.

Very generally (without claiming any intimate knowledge of the implications of this change) I think we should try to get rid of all feature flags where it makes sense in the v3 release. (That's why we released only a beta version of v3 for now, precisely so that we can still introduce breaking changes.)

However, if this change manoeuvres us into a corner where users that need the default port have no way of adding it back, we could consider bringing back the old behavior, either as a feature flag with inverted behavior or as some 1st class config setting. (But I would assume you could just work around the change of behavior with one more relabel setting?)

In any case, as said above, my intention was merely to relay information. We should do what the experts say, not what I say.

**Comment by jan--f** [comment]
I also don't see an issue with getting this in. The beta release is an incomplete preview imo with the implication of possibly more breaking changes.
Looking at the issue that prompted the feature flag (#9507) this solution seem right to me.
We could probably add a release note entry or similar pointing out a relabel config that adds this back? Though a feature flag for the old behavior would also work in my book.

**Comment by beorn7** [comment]
An easy work-around is also to specify the desired port (80 or 443) explicitly.

Or in other word: This will only affect users that have not added the port explicitly to their scrape config so far and relied on the default port not only being used but also being added to the `__addr__` label and thus the default `instance` label. This addition was (in the spirit of the discussion on #9507) probably wrong from the beginning. Why should Prometheus code replicate the information what the default port of http or https is?

My gut feeling is we should simply remove this behavior from Prometheus v3, as done in this PR. (But I still don't claim to have expert domain knowledge here. Happy to be proven otherwise.)

**Comment by beorn7** [comment]
Just relaying from an in-person discussion I just had with some colleagues:

Assuming that this change is indeed fairly innocuous, we could move forward with just removing the feature flag (and make the "enabled" behavior the new and only behavior), we should describe more clearly in the description of (one of) the commits and in the PR description above what this is precisely doing (because the linked issue #13959 isn't really telling a lot, and even the very original issue #9507 isn't crystal clear).

I think the feature flag documentation this PR removes is actually pretty good, and the PR description could be build on top of it, i.e.:

"""
When enabled, the default ports for HTTP (`:80`) or HTTPS (`:443`) will _not_ be added to
the address used to scrape a target (the value of the `__address__` label), contrary to the default behavior.
In addition, if a default HTTP or HTTPS port has already been added either in a static configuration or
by a service discovery mechanism and the respective scheme is specified (`http` or `https`), that port will be removed.
""" 

Which reminds me that the last sentence in the above is actually not true. I tried it out. If I enable the feature flag and set `localhost:80` as one of the `targets` in one of the `static_configs`, I still get an `instance` label `localhost:80`. Only if I set merely `localhost` as the target, I get `localhost` as the `instance` label with the feature flag enabled, and `localhost:80` without the feature flag enabled. I think the currently implemented behavior (with the feature flag enabled) is the desired and least surprising one.

In different news, we should have an "upgrade guide" with all the relevant changes from v2 to v3 and how to deal with them. This would also alleviate concerns about how invasive of a change is acceptable.

**Comment by beorn7** [comment]
Taking a step back:

This PR is almost identical to #14160. And the latter still seems active. @jackma-00 why did you open this PR in the first place?

**Comment by arejula27** [comment]
> Not sure why this PR was opened in the first place. It seems to really copy it and not by accident implemented the same feature in a slightly different way.

  @beorn7, we started working on this issue based on your suggestion on Slack when we asked how to begin contributing. So no, it wasn't by accident—we were just following your guidance.

**Comment by jan--f** [comment]
Apologies, I am to blame. #14160 didn't see any activity for over 2 months, so I assumed it was orphaned. ABout a week after @arejula27  and @jackma-00 reached out it got attention again. Sorry for the confusion this caused.

**Comment by arejula27** [comment]
No problem, these things happen. I just want to make it clear that we did not take advantage of an ongoing PR.

However, I would like to make another contribution. Where would be the best place to discuss which issue to take? All the good-first-issue ones seem to be taken. 😄

**Comment by beorn7** [comment]
Apologies also from my side.

Generally, if someone starts to take over the work on an abandoned PR, it would be good to leave a note on the (seemingly) abandoned PR. Now we had multiple persons working in parallel doing the same thing.

**Pull request closed without merging**
