### PR TITLE
support rule format with json

### PR DESCRIPTION
**Pull request by 00arthur00**
support json format

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you explain what you're trying to do? This file is part of the internals of Prometheus, which only uses YAML.

**Comment by 00arthur00** [comment]
We use consul to manage our promethues rule configuration, internally we use json. So add it.
Although yaml is an option, yaml's indentation is challengable for consul-template writer. JSON doesn't have this promblem. It's good for us.
I think others may have this requirement.

**Comment by 00arthur00** [comment]
@brian-brazil

**Comment by brian-brazil** [comment]
These are internal structs, we don't generally change them to support things that aren't features of Prometheus itself as any such change would either constrain us or get removed in passing by some other change. The most we'll usually do is make something public, which these already are.

For these configs JSON will parse as YAML, so you shouldn't need to change anything.

**Comment by roidelapluie** [comment]
I agree with Brian. Lots of people actually generate Json for alerts and it just works out of the box because json is a subset of yaml.

**Comment by 00arthur00** [comment]
Thanks. @brian-brazil  @roidelapluie 
Will close it.

**Pull request closed without merging**
