### PR TITLE
time() return milliseconds

### LINKED ISSUE #3808: time() loses fractional part of the time
The `time()` function only returns integers, it should be returning decimals with up to millisecond resolution.

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fixes #3808
@brian-brazil is this what you meant?

TODO: 
~- [ ] update website docs.~

### CODE REVIEW

**Comment by brian-brazil** [comment]
No the time must still be in seconds, but we're losing the milliseconds from the time. This is due to doing the float conversion too late.

**Comment by krasi-georgiev** [comment]
Thanks PR updates

**Comment by brian-brazil** [comment]
Can you add a test?

**Comment by brian-brazil** [comment]
You should be able to test this with standard promql tests rather than needing to do something bespoke.

**Comment by krasi-georgiev** [comment]
That is nice , didn't notice it. 
test amended.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
