### PR TITLE
fix(model/relabel): string comparison of relabel's regexes

### LINKED ISSUE #12534: KeepEqual/DropEqual should compare Regex.String instead of instance values
### What did you do?

Using a relabel config with keepequal/dropequal compares instance var instead of string value.

https://github.com/prometheus/prometheus/blob/main/model/relabel/relabel.go#L134 should be `c.Regex.String() != DefaultRelabelConfig.Regex.String()` and not `c.Regex != DefaultRelabelConfig.Regex`

### What did you expect to see?

_No response_

### What did you see instead? Under which circumstances?

KeepEqual doesn't work if we the regex is the same string but different instance.

### System information

_No response_

### Prometheus version

_No response_

### Prometheus configuration file

```yaml
relabel_configs:
            - source_labels: [label_1]
              action: keepequal
              target_label: label_2
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by hainenber**
Fixes #12534 

Comparing `Regex` struct object might not always be correct, string comparison would ensure correctness.

### CODE REVIEW

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Do we use this elsewhere?

**Comment by bboreham** [comment]
I commented on the issue; this seems to me to be worse.

**Comment by hainenber** [comment]
@roidelapluie this was used in `grafana/agent`.

**Comment by beorn7** [comment]
@mattdurham what do you think about this?

**Comment by henry-kuehl** [comment]
Any update on this PR?

**Comment by bboreham** [comment]
To clarify from comments across various other issues and PRs:
The change in this PR should be unnecessary. The issue that motivated it appears to arise from marshalling config into Yaml, which incorrectly generates a regex for actions that don't take one.

Therefore a better approach is to fix the marshalling code to generate correct config.

No point in keeping this PR open, months after the better approach was [agreed](https://github.com/prometheus/prometheus/pull/12527#issuecomment-1829677659).

**Pull request closed without merging**
