### PR TITLE
PromQL: Use a sync.Pool for the generated parser structure

### PR DESCRIPTION
**Pull request by slrtbtfs**
The generated PromQL parser allocates a struct about 4kb in size on every run.

This puts a high load on the garbage collector.

To reduce that load, a `sync.Pool` is used to recycle these structures.

For small queries this makes parsing 2-3 times faster.

Signed-off-by: Tobias Guggenmos <tguggenm@redhat.com>

### CODE REVIEW

**Comment by slrtbtfs** [comment]
I've updated the PR to store the `parser` and `Lexer` in that `sync.Pool`, too.

This speeds up the parser by another 10-20%.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
