### PR TITLE
Update dependencies for v2.39

### PR DESCRIPTION
**Pull request by codesome**
I haven't verified individual dependencies yet (however, the upgrade seems small, so as long as the tests pass, I am gonna pass it as well). ~Also, I got errors while updating npm dependencies because it could not find package.json at multiple places, but it did find one and updated it.~

### CODE REVIEW

**Comment by codesome** [comment]
I do not understand the UI errors, so I am skipping npm deps update from this PR.

**Comment by codesome** [comment]
We have these 2 lint errors. We seem to be using some old package. I am not sure about the implications of moving to new ones.

```
SA1019: "github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute" is deprecated: Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details. (staticcheck)
```

```
SA1019: "github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-10-01/network" is deprecated: Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details. (staticcheck)
```

@roidelapluie what do you suggest? Use the new one or add a nolint comment?

**Comment by Nexucis** [comment]
I will do it on a different PR @codesome if you want

**Comment by codesome** [comment]
Thanks @Nexucis. I would not stress much on it at the moment for v2.39, but if it has not been upgraded since long time, feel free to do it :) (in the worst case, the npm upgrade goes into v2.40)

**Comment by Nexucis** [comment]
the script was broken, so I took the opportunity to fix it. I have updated the npm deps as well here @codesome : https://github.com/prometheus/prometheus/pull/11332

**Review by Nexucis — APPROVED** [review]

**Comment by juliusv** [comment]
:+1: I ran into the same Azure package deprecation errors as well last time, and also reverted the upgrade of that package, since the required changes seemed non-trivial and I don't have any Azure stuff. It would be good to get someone more into Azure to look into upgrading at some point.

**Pull request merged**
