### PR TITLE
Remove .pkgignore file

### PR DESCRIPTION
**Pull request by fabxc**
@beorn7

### CODE REVIEW

**Comment by beorn7** [comment]
:+1: 

Apparently, @discordianfish tried to run Prometheus on Bazooka back in 2013... :)

**Comment by discordianfish** [comment]
@beorn7 I did indeed. Wow 2013.. if we just had released it back then...

**Comment by juliusv** [comment]
@discordianfish Who knows, maybe it would have totally flopped. I mean, it was barely working back then... in any case, we seem to be doing fine :)

**Comment by discordianfish** [comment]
@juliusv I was referring to bazooka, the prometheus release/announcement happened at exactly the right time IMO :)

**Comment by juliusv** [comment]
@discordianfish Ah ok :)

**Pull request merged**
