### PR TITLE
discovery: Instead of looping over conf.Search, use NameList()

### PR DESCRIPTION
**Pull request by fastest963**
Instead of looping over the `Search` suffixes manually, use `NameList` (added in https://github.com/miekg/dns/pull/452). This resolves the following ordering problem with the way prometheus was querying using the suffix list. If you have a resolv.conf with a search list but ndots was 1, prometheus would do a query first with the first search suffix, instead of using the sent `name` if it had >= dots than ndots. This caused unnecessary warnings and invalid queries.

### CODE REVIEW

**Comment by beorn7** [comment]
:+1:

**Comment by beorn7** [comment]
Hmmm, Promu has trouble building the darwin-amd64 binary:

```
/go/src/github.com/prometheus/prometheus/vendor/github.com/miekg/dns/server.go:365: undefined: setUDPSocketOptions
 /go/src/github.com/prometheus/prometheus/vendor/github.com/miekg/dns/server.go:395: undefined: setUDPSocketOptions
```

@fastest963 Do you have any context on this?

**Comment by beorn7** [comment]
Interestingly, those lines didn't even change in this PR.

**Comment by beorn7** [comment]
I see, your vendoring tool only vendored for your platform.
Known problem... I'll fix that.

**Comment by fastest963** [comment]
@beorn7 ah, I was new to vendoring so I might've screwed that up. Sorry about that!

**Comment by beorn7** [comment]
No worries, common pitfall.

**Pull request merged**
