### PR TITLE
mixin: Reorder template variables on Remote Write dashboard

### PR DESCRIPTION
**Pull request by f9n**

### CODE REVIEW

**Comment by LeviHarrison** [comment]
Could you please detail the reasoning behind the change? Thanks!

**Comment by f9n** [comment]
I want to filter `instance` variable with variable `cluster`.  I see too many `instance` values.

**Comment by LeviHarrison** [comment]
I'll defer to someone who knows more about the mixin.

cc @beorn7 @cstyan

**Comment by beorn7** [comment]
This makes sense to me. But I'm not using this dashboard myself very often. @cstyan what do you think about this?

**Review by cstyan — APPROVED** [review]

**Review by beorn7 — APPROVED** [review]
Thank you, all. The MS Windows test failure is certainly not related. Merging…

**Pull request merged**
