### PR TITLE
Update Go dependencies in preparation for v2.33

### PR DESCRIPTION
**Pull request by beorn7**
@juliusv & @Nexucis , please note that I haven't touched the React dependencies. I assume that's done by those various individual PRs I have seen, and that it is currently not a responsibility of the release shepherd. If that's wrong, or if there is any React dependency update you would like to get in before the release, please let me know.

### CODE REVIEW

**Comment by Nexucis** [comment]
It looks like there is an issue with the k8s dependencies. @SuperQ rollback them with https://github.com/prometheus/prometheus/commit/a78a3cea0209e11fe9845a11571def1e0065b07f 6 days ago.

**Comment by beorn7** [comment]
The issue seems to only happen with Go 1.16.

Is it OK to require Go 1.17?
Or should I keep the older K8s version?
@SuperQ ?

**Comment by beorn7** [comment]
I see the discussion in #10097. Which would point towards keeping 1.16 happening. However, locking a dependency to an older version causes trouble (as proven here). Perhaps it could be cleanly done with a `replace` directive?

But since Go 1.18 will be released soon, perhaps it's OK to bump the minimum requirement  to 1.17 now?

**Comment by beorn7** [comment]
I added a commit to bump the minimum Go requirement to 1.17. Please let me know if you prefer keeping 1.16 and the weird state with the k8s library (in which case I'll play with `replace` to lock it down properly).

**Comment by beorn7** [comment]
I need to fix the `go mod tidy` inconsistency. My local Go is too old, I guess.

**Comment by beorn7** [comment]
Apparently, there is no clean way of locking a dependency with Go modules.

So it's either weird state and allow Go 1.16 or clean state and require Go 1.17.

**Comment by SuperQ** [comment]
I think we wanted to keep compatibility with at least 1.16 until we are satisfied with 1.18. Supporting at least one older compiler minor version (as Go itself does).

We shouldn't need to do these manual bump PRs anymore, as we have dependabot to do these for us.

My recommendation is to rollback and keep the k8s.io at v0.22.4.

**Comment by beorn7** [comment]
> We shouldn't need to do these manual bump PRs anymore, as we have dependabot to do these for us.

That's news to me. Could you update https://github.com/prometheus/prometheus/blob/main/RELEASE.md#0-updating-dependencies ?

**Comment by beorn7** [comment]
I guess we still need the manual bump for non-semver updates (those with `+incompatible` and `v0.0.0` in the version specifier).

**Comment by beorn7** [comment]
Now updated the PR to update normally but then manually set the following versions:
- k8s.io/api v0.22.4
- k8s.io/apimachinery v0.22.4
- k8s.io/client-go v0.22.4

Let's see if it passes the tests.

**Review by SuperQ — APPROVED** [review]

**Comment by beorn7** [comment]
:tada: It passed!

**Comment by beorn7** [comment]
`npm outdated` shows me the following outdated react dependencies: (@juliusv @Nexucis I always feel a bit lost when it comes to React. Are those below OK or do we need to update before I cot the release?)

```
Package                              Current    Wanted   Latest  Location                                                                Depended by
@codemirror/autocomplete              0.19.9   0.19.10  0.19.10  node_modules/@codemirror/autocomplete                                   react-app@npm:graph@0.1.0
@codemirror/autocomplete              0.19.9   0.19.10  0.19.10  node_modules/@codemirror/autocomplete                                   codemirror-promql@0.19.0
@codemirror/basic-setup               0.19.0    0.19.1   0.19.1  node_modules/@codemirror/basic-setup                                    codemirror-promql@0.19.0
@codemirror/commands                  0.19.5    0.19.6   0.19.6  node_modules/@codemirror/commands                                       react-app@npm:graph@0.1.0
@codemirror/highlight                 0.19.6    0.19.7   0.19.7  node_modules/@codemirror/highlight                                      react-app@npm:graph@0.1.0
@codemirror/highlight                 0.19.6    0.19.7   0.19.7  node_modules/@codemirror/highlight                                      codemirror-promql@0.19.0
@codemirror/history                   0.19.0    0.19.2   0.19.2  node_modules/@codemirror/history                                        react-app@npm:graph@0.1.0
@codemirror/search                    0.19.3    0.19.5   0.19.5  node_modules/@codemirror/search                                         react-app@npm:graph@0.1.0
@codemirror/view                     0.19.27   0.19.39  0.19.39  node_modules/@codemirror/view                                           react-app@npm:graph@0.1.0
@codemirror/view                     0.19.27   0.19.39  0.19.39  node_modules/@codemirror/view                                           codemirror-promql@0.19.0
@forevolve/bootstrap-dark              1.1.0     1.1.0    2.1.0  react-app/node_modules/@forevolve/bootstrap-dark                        react-app@npm:graph@0.1.0
@types/chai                           4.2.22     4.3.0    4.3.0  node_modules/@types/chai                                                codemirror-promql@0.19.0
@types/enzyme                        3.10.10   3.10.11  3.10.11  node_modules/@types/enzyme                                              react-app@npm:graph@0.1.0
@types/jest                           27.0.3    27.4.0   27.4.0  node_modules/@types/jest                                                react-app@npm:graph@0.1.0
@types/jquery                          3.5.9    3.5.11   3.5.11  node_modules/@types/jquery                                              react-app@npm:graph@0.1.0
@types/node                         16.11.12  16.11.19   17.0.8  node_modules/@types/node                                                react-app@npm:graph@0.1.0
@types/node                         16.11.12  16.11.19   17.0.8  node_modules/@types/node                                                codemirror-promql@0.19.0
@types/react                         17.0.36   17.0.38  17.0.38  node_modules/@types/react                                               react-app@npm:graph@0.1.0
@typescript-eslint/eslint-plugin       5.8.0     5.9.0    5.9.0  module/codemirror-promql/node_modules/@typescript-eslint/eslint-plugin  codemirror-promql@0.19.0
@typescript-eslint/parser              5.8.0     5.9.0    5.9.0  module/codemirror-promql/node_modules/@typescript-eslint/parser         codemirror-promql@0.19.0
@wojtekmaj/enzyme-adapter-react-17     0.6.5     0.6.6    0.6.6  node_modules/@wojtekmaj/enzyme-adapter-react-17                         react-app@npm:graph@0.1.0
bootstrap                              4.6.1     4.6.1    5.1.3  node_modules/bootstrap                                                  react-app@npm:graph@0.1.0
eslint                                 8.4.1     8.6.0    8.6.0  module/codemirror-promql/node_modules/eslint                            codemirror-promql@0.19.0
eslint-config-react-app                6.0.0     6.0.0    7.0.0  react-app/node_modules/eslint-config-react-app                          react-app@npm:graph@0.1.0
eslint-plugin-import                  2.25.3    2.25.4   2.25.4  node_modules/eslint-plugin-import                                       codemirror-promql@0.19.0
fsevents                             MISSING     2.3.2    2.3.2  -                                                                       react-app@npm:graph@0.1.0
mocha                                  9.1.3     8.4.0    9.1.3  module/codemirror-promql/node_modules/mocha                             codemirror-promql@0.19.0
react-resize-detector                  6.7.6     6.7.8    7.0.0  node_modules/react-resize-detector                                      react-app@npm:graph@0.1.0
react-router-dom                       5.3.0     5.3.0    6.2.1  react-app/node_modules/react-router-dom                                 react-app@npm:graph@0.1.0
react-scripts                          4.0.3     4.0.3    5.0.0  react-app/node_modules/react-scripts                                    react-app@npm:graph@0.1.0
reactstrap                            8.10.0    8.10.1    9.0.1  react-app/node_modules/reactstrap                                       react-app@npm:graph@0.1.0
sanitize-html                          2.6.0     2.6.1    2.6.1  node_modules/sanitize-html                                              react-app@npm:graph@0.1.0
sass                                  1.44.0    1.44.0   1.46.0  node_modules/sass                                                       react-app@npm:graph@0.1.0
ts-loader                              7.0.5     7.0.5    9.2.6  node_modules/ts-loader                                                  codemirror-promql@0.19.0
typescript                             4.5.2     4.5.4    4.5.4  node_modules/typescript                                                 react-app@npm:graph@0.1.0
typescript                             4.5.2     4.5.4    4.5.4  node_modules/typescript                                                 codemirror-promql@0.19.0
```

**Comment by beorn7** [comment]
I tried to update the packages above, but with my not-existing React knowledge, I predictably ended up with error messages I do not understand.

**Comment by beorn7** [comment]
I'll merge this, as it is titled "update Go dependencies", but please any of the React experts, let me know if there are updates needed for React packages before I cut the release.

**Comment by Nexucis** [comment]
we should be good for the react update @beorn7 :).

**Pull request merged**
