### PR TITLE
Support displaying X-axis of graph in local timezone

### PR DESCRIPTION
**Pull request by kawamuray**
As a prometheus user who live in Japan(UTC+0900), displaying X-axis timestamp of a graph in local timezone is very desired feature.
As I read the FAQ entry(https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone?-why-is-everything-in-utc?) about timezone on prometheus, I understand that the prometheus want to respect UTC as much as possible, so I added an option to switch the display mode of X-axis as a server option.
I also think about introducing "localtime" button on the graph UI but realized something like following which makes me feel it don't mean much.
- Depends on organizations standard but for most cases people who see the same prometheus server wants to rely on the same timezone on the view. At least all people around me says they want to see the graph with local timezone.
- It's really cumbersome to click timezone button every time opening a graph UI or adding a graph.

Any feedbacks are welcome :)

Just for reference, here's the picture of how each display option works:

As-is(built from 82a961):
As-is

Option disabled(resulting same view as before):
Option disabled

Option enabled:
Option enabled

---

This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/1616)

### CODE REVIEW

**Comment by beorn7** [comment]
Thanks for your attempt to tackle this nasty issue.

In general, I'd like it more to have a switch in the WebUI itself rather than a command line flag.

Do you know how the display will look like during a "daylight saving time" switch-over?

**Comment by barkerd427** [comment]
I also think it would be preferential on the web ui side. I work with
people in other timezones within the US, but also people around the world.
We also have datacenters around the world. Setting this on the server would
not be ideal for what I believe is the common pattern. However, a change in
the web ui would be great!

**Comment by brian-brazil** [comment]
See #500 

This should be a checkbox in the UI IMHO

**Comment by grobie** [comment]
I share the same concerns. The problem of persistence of that UI choice can be tackled with cookies and/or local storage.

**Comment by andelf** [comment]
my fork,  https://github.com/andelf/prometheus , make local time works by modifying ui.

**Comment by brian-brazil** [comment]
This review seems stale, if you make the requested changes please let us know.

**Pull request closed without merging**
