### PR TITLE
Update prombench workflows to incorporate new naming convention for eks

### PR DESCRIPTION
**Pull request by weastel**
Signed-off-by: Drumil Patel <drumilpatel720@gmail.com>

This pr incorporates following changes in `.github/workflows/prombench.yml` in favor of prometheus/test-infra#384 :-
1. `all_nodepools_deleted` => `all_nodes_deleted`
2. `all_nodepools_running` => `all_nodes_running`

### CODE REVIEW

**Comment by weastel** [comment]
@geekodour Please give it a look

**Comment by roidelapluie** [comment]
is it required to run prombench tomorrow?

**Comment by geekodour** [comment]
@roidelapluie no, this will be merged once prometheus/test-infra#384 gets merged. So nothing should be breaking :)

**Comment by roidelapluie** [comment]
is this required in the release-2.21 branch? I will launch a prombench this week in the branch.

**Comment by geekodour** [comment]
@roidelapluie this will not affect how current tests are run. (the flag enabling this change will be changed at some later PR). So anything should be fine.

**Pull request merged**
