### PR TITLE
engine_test: replace os.MkdirTemp with t.TempDir

### PR DESCRIPTION
**Pull request by palash25**
Fixes: #9594

Signed-off-by: Palash Nigam <npalash25@gmail.com>

### CODE REVIEW

**Comment by palash25** [comment]
not sure why windows tests are failing with OOM, let me know if that is because of my change. seems unrelated though.

**Comment by roidelapluie** [comment]
I have rebased, let's see how Windows behaves.

**Comment by roidelapluie** [comment]
testing.go:1206: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestQueryConcurrency3839867193\001\queries.active: The process cannot access the file because it is being used by another process.

**Comment by beorn7** [comment]
Looking at this during the bug scrub.

Since there was no follow-up in a long time, we'll close this PR. However, we should still migrate to t.TempDir generally (and everywhere). Any help appreciated.

**Pull request closed without merging**
