### PR TITLE
Race in sd triton test

### PR DESCRIPTION
**Pull request by krasi-georgiev**
I can't reproduce locally , but should fix the fail  when test -race is enabled
https://travis-ci.org/prometheus/prometheus/jobs/345641319

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
@brian-brazil

**Comment by brian-brazil** [comment]
I don't see how this fixes a race. Where's the concurrent access that this is fixing?

**Comment by krasi-georgiev** [comment]
Read
https://github.com/prometheus/prometheus/blob/ffa673f7d813d7c8f4f1677aca9859340d4d4629/discovery/triton/triton_test.go#L89-L90

Write
https://github.com/prometheus/prometheus/blob/ffa673f7d813d7c8f4f1677aca9859340d4d4629/discovery/triton/triton_test.go#L168

Although I don't see why this happens since the tests don't run in parallel , I think it happens because these share the same config via the pointer.

@brian-brazil can you think of any other explanation why is this happening?

**Comment by brian-brazil** [comment]
The context is cancelled, but the code isn't waiting for `Run` to actually terminate.

**Comment by krasi-georgiev** [comment]
Thanks, added an extra blocking channel for this.

**Pull request merged**
