### PR TITLE
scrape: Enable ingestion of multiple exemplars per sample

### LINKED ISSUE #12553: Histograms: not all examplars are ingested
### What did you do?

Exposed exemplars alongside classic buckets, but also exposed a native histogram.

### What did you expect to see?

The native histogram should be ingested together with all the exemplars assigned to the classic buckets.

### What did you see instead? Under which circumstances?

Only the first exemplar is ingested.

### Notes

See https://cloud-native.slack.com/archives/C02KR205UMU/p1688414381799849 for the findings.

It's unclear if that happened with `scrape_classic_histograms` set or not, but that has to be checked in any case.

### PR DESCRIPTION
**Pull request by beorn7**
Fixes #12553 .

@fstab this will be of interest for you.
@krajorama maybe Mimir users have run into this already.
@jesusvazquez is codeowner.

### CODE REVIEW

**Comment by beorn7** [comment]
@jesusvazquez is probably only codeowner because I added a missing "an" in a comment in a TSDB file. :-)

**Comment by roidelapluie** [comment]
How are they represented in text/OM format?

**Comment by fstab** [comment]
> How are they represented in text/OM format, and do we need an additional parsing test?

Native histogram is the only metric type that supports multiple Exemplars per time series. There's no way to have a time series with multiple Exemplars in text / OM format.

**Comment by beorn7** [comment]
The parser test already includes multiple exemplars, as [commented here](https://github.com/prometheus/prometheus/issues/12553#issuecomment-1632744028).

Currently, the only occurrence of multiple exemplars for a single sample happens with native histograms in protobuf if classic buckets are also specified, and they have exemplars. That need is implemented in this PR, with full test coverage.

In the future, we'll support multiple exemplars in a list (so that you don't have to specify classic buckets for the only purpose of adding exemplars), see https://github.com/prometheus/client_model/issues/61 .

Also in the (hopefully close) future, there will be native histogram support in OM, which then will also need multiple exemplars per sample.

**Comment by beorn7** [comment]
Since this is an actual bug, it would be good to get this into 2.46.0. @roidelapluie any other concerns or questions here? Happy to address them ASAP.

**Comment by bwplotka** [comment]
Not merging if we want this in https://github.com/prometheus/prometheus/pull/12581 (we should rebase on that release branch then). Happy with getting this into 2.46.0

**Comment by beorn7** [comment]
@roidelapluie please advise. I'll happily rebase this on top of https://github.com/prometheus/prometheus/tree/release-2.46 , but https://github.com/prometheus/prometheus/pull/12581/ is also on top of main, so maybe you will reset https://github.com/prometheus/prometheus/tree/release-2.46 to main anyway later?

**Review by jesusvazquez — APPROVED** [review]
Got here a bit late but now have reviewed. Looking good to me too. Nice addition :+1:

**Pull request merged**
