### PR TITLE
Fix some warnings: 'redundant type from array, slice, or map composite literal'

### PR DESCRIPTION
**Pull request by Hellcatlk**

### CODE REVIEW

**Comment by brian-brazil** [comment]
These are pretty trivial PRs, would you mind batching them up in to one large PR?

**Comment by Hellcatlk** [comment]
@brian-brazil i have batched them up in to one large PR.

**Comment by brian-brazil** [comment]
Did you forget to push?

**Comment by Hellcatlk** [comment]
@brian-brazil : Sorry, i misunderstand, Could your elaborate on what you mean?

**Comment by Hellcatlk** [comment]
@brian-brazil Do you mean add pr(#7106) into this pr?

**Comment by brian-brazil** [comment]
Given that you said you've batched them up, I was expecting you to add more changes of this nature in to this PR.

**Comment by Hellcatlk** [comment]
@brian-brazil : Thanks for your reply, I have push more  changes into this PR.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
