### PR TITLE
Support escape sequences in strings and add raw strings

### LINKED ISSUE #1121: Support line breaks in alert descriptions
From IRC:
> jrv: shimin: yeah, I believe we still need to add a way to specify multi-line strings. Either with \n-style interpolation or allowing raw newlines in strings...

### LINKED ISSUE #1122: String escaping in alert description seems to be broken
`DESCRIPTION '{{"abc"}}'` renders “abc” correctly

`DESCRIPTION "{{\"abc\"}}"` gives error `unexpected \"\\\\\" in command`

### PR DESCRIPTION
**Pull request by juliusv**
This adapts some functionality from the Go standard library for string
literal lexing and unquoting/unescaping.

The following string types are now supported:

Double- or single-quoted strings:

  These support all escape sequences that Go supports in double-quoted
  string literals. The difference is that Prometheus also has
  single-quoted strings (instead of single-quoted runes in Go). Raw
  newlines are not allowed.

Backtick-quoted raw strings:

  Strings quoted in backticks are treated as raw strings just like in Go
  and may contain raw newlines and other special characters directly.

Fixes #1122
Fixes #1121

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc What's still missing here is some kind of more proper legal attribution for the copied&adapted functions from the Go standard library. Probably it should be something in the NOTICE file, but not sure if I should just phrase it similarly as I have it in the comments above the copied functions. @TheTincho, any advice on that?

**Comment by juliusv** [comment]
Comments, anyone? /cc @brian-brazil @beorn7

**Comment by beorn7** [comment]
That looks like @fabxc should have an opinion, too. I feel way less qualified here than him.

**Comment by juliusv** [comment]
Yep, he was already CCed :)

**Comment by fabxc** [comment]
Sorry, that totally got lost. Will look into it soon.

**Comment by fabxc** [comment]
Okay, didn't walk down every condition for the adapted parts. As per our discussion this seems like the best solution and the test cases cover what I can think of.

Maybe state in the `NOTE:` sections which behaviors exactly were tweaked – just so we don't have to diff the semantics again in our head later.

:+1: 

Sorry again for the delay.

**Comment by juliusv** [comment]
No probs, thanks! I updated the "NOTES" sections to mention the relevant changes.

**Pull request merged**
