### PR TITLE
Improve Go source file formatting and enforce it using linters

### LINKED ISSUE #9557: Consider using more strict formatters like gci and gofumpt
To bring more uniformity to the codebase and to make it easier for developers already using more strict formatters, I'd like to propose enabling `gofumpt` and `gci` linters in golangci-lint configuration and to format all Go source files in this repository using those programs.

Those formatters are compatible with more popular `gofmt`, meaning after applying `gofumpt` formatting, `gofmt` won't try to revert it.

If one has automatic formatting configured in their IDE, working with not formatted files becomes annoying if one wants to produce clear commits (without formatting fixes on the side).

Here you can see applied formatting: https://github.com/prometheus/prometheus/commit/282990880615ab698fe9583b21ae52e19c333f46

I'm happy to open PR configuring linter and fixing current formatting.

### PR DESCRIPTION
**Pull request by invidian**
Closes #9557

Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks, will merge on green

**Comment by roidelapluie** [comment]
can gofumpt -s be enabled on golangci-lint?

**Review by roidelapluie — APPROVED** [review]
thanks!

**Comment by invidian** [comment]
Wait, if we agree on using `-extra`, we should enable it in the linter configuration. `-s` is enabled by default as far as I understand.

**Comment by roidelapluie** [comment]
Can you rebase? Tests are failing.

**Comment by roidelapluie** [comment]
thanks!

**Pull request merged**
