### PR TITLE
Fix JS XHR requests in prom_console.js on IE11

### PR DESCRIPTION
**Pull request by iokill**
IE11 does not support automatic JSON parsing for responses with
xhr.responseType = 'json', so we have to to do it manually.

@beorn7 @brian-brazil

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks 👍

**Comment by beorn7** [comment]
I guess you have to run `make assets` followed by `make format`.

**Comment by iokill** [comment]
Ah right - I didn't realize that. I guess a should have read the readme file. :)
It's fixed now.

**Comment by juliusv** [comment]
:+1: Thanks!

**Pull request merged**
