### PR TITLE
Add CodeQL Security Scanning

### PR DESCRIPTION
**Pull request by caniszczyk**
Try out CodeQL to improve security scanning practices in Prometheus.

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Review by roidelapluie — APPROVED** [review]

**Comment by SuperQ** [comment]
Seems like a good idea to me. @caniszczyk Do you have any examples of projects using this? Do you have any idea what the rate of false-positives are for this tool? We'd like to understand what the signal-to-noise ratio would be with this tool.

**Comment by roidelapluie** [comment]
FYI @caniszczyk I have run this and communicated the results to -team.

We are assessing the initial vulnerabilities discovered by this tool.

**Comment by roidelapluie** [comment]
@SuperQ do you want to move on with this?

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by roidelapluie** [comment]
Thanks @caniszczyk

**Comment by bboreham** [comment]
We gave it a try, and as far as I know it did not tell us anything of interest.
I'm proposing to remove the Go scan in #13721, to save 20 minutes of CI time.

**Pull request merged**
