### PR TITLE
Add InfluxDB read-back support to remote storage bridge

### PR DESCRIPTION
**Pull request by juliusv**
This is becoming serious, so in a next step I would like to move this from the examples directory to separate repos for each backend system and maintain them properly there.

Similar to how we now have client libraries for different languages and exporters for different third-party systems, remote storage integrations could become its own category (and be listed in the docs as well).

### CODE REVIEW

**Comment by grobie** [comment]
Hah, I was wondering about vendoring ...

**Comment by brian-brazil** [comment]
I'd prefer to leave these as examples on our end for now. This is all very early yet.

**Comment by juliusv** [comment]
@grobie Removed the old InfluxDB client vendoring and added the v2 one now, hopefully CI will pass.

@brian-brazil Good point, but on the other hand, look at the interest on this tweet: https://twitter.com/juliusvolz/status/848325516709036032 - and this was without me even publishing anything, so I think a lot of people will want to have this as a non-toy standalone thing. Hey, if it changes, it changes...

**Comment by grobie** [comment]
LGTM.

**Pull request merged**
