### PR TITLE
Add new "globalUrl" field to /api/v1/targets docs

### PR DESCRIPTION
**Pull request by juliusv**
See https://github.com/prometheus/prometheus/pull/6794

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@roidelapluie I didn't elaborate on the meaning of the field, since we don't do that for most other existing fields either (yet)...

**Comment by brian-brazil** [comment]
I'm not sure that this UI implementation detail should leak into our public APIs.

**Comment by juliusv** [comment]
@brian-brazil See https://github.com/prometheus/prometheus/pull/6794#issuecomment-583842388, I allowed it since I thought it could be useful outside of UI purposes as well.

**Comment by brian-brazil** [comment]
Ah, I'd missed that question to me. I've personally wondered if we should do this munging at all.

**Comment by juliusv** [comment]
I think it's useful enough to do.

**Comment by brian-brazil** [comment]
It's a bit messy, as we're trying to guess how name resolution looks like to unknown 3rd parties. I've always kinda wondered if it was worth it. Personally I'd only every scrape "localhost", as against the machine name, when throwing together a quick test Prometheus as otherwise you don't know which localhost is which as the setup gets more complicated.

**Comment by roidelapluie** [comment]
What is the way forward?

**Comment by juliusv** [comment]
Not sure. I buy the argument that localhost links aren't a good idea for production setups. In playground setups though this setting has been quite handy :)

**Comment by brian-brazil** [comment]
In a playground wouldn't localhost be the machine your browser is on :)

**Comment by juliusv** [comment]
Concretely I was thinking about workshops where I had participants use a VM and point the Prometheus on there at all kinds of local stuff (Prometheus, PGW, Node Exporter, Alertmanager, etc.). You can also use absolute IPs for that, it's just more work in terms of participants needing to customize their example config.

**Comment by juliusv** [comment]
I also imagine some (many?) people will try out https://prometheus.io/docs/introduction/first_steps/ not on their own machine, but some VM, in which case the localhost URL we provide in the example config in there will also not be clickable.

**Comment by juliusv** [comment]
Though TBF in that case we also don't provide an external URL, so we don't solve that problem in that case either.

**Comment by roidelapluie** [comment]
The fact that it is documented or not does not change much in term of API compatibility. We can't remove it without changing the API. Since we still expose this today, I will merge this.

**Pull request merged**
