### PR TITLE
Add SubQueryStep to distinguish whether the vectorSelector was wrapped in a SubQuery

### PR DESCRIPTION
**Pull request by wanghaao**
The Select() of Querier interface supports the unexpandedSeriesSet for VectorSelector. The step in SelectHints is a global parameter, and it can't adapt to the VectorSelector which is embedded in a subquery, for example, query: max_over_time(metric[6m:10s])、step: 20s.

For the inner VectorSelector, it should choose 10s not 20s as the step parameter. So, I suggest adding the ``SubQueryStep`` parameter in SelectHints.

Currently, the latest version has already reset the interval, i.e., 
```go
func (ng *Engine) populateSeries(querier storage.Querier, s *parser.EvalStmt) {
	var evalRange time.Duration
	parser.Inspect(s.Expr, func(node parser.Node, path []parser.Node) error {
		switch n := node.(type) {
		case *parser.VectorSelector:
			start, end := ng.getTimeRangesForSelector(s, n, path, evalRange)
			interval := ng.getLastSubqueryInterval(path)
			if interval == 0 {
				interval = s.Interval // the interval has been reset
			}
.............
.............
```

Now, I need to distinguish whether the vectorSelector was wrapped in a subQuery by ``SubQueryStep``, then I can optimize the ``Select()`` process of vectorSelector.

### CODE REVIEW

**Comment by wanghaao** [comment]
In the process of ``Select()``, my service will pull the timeSeries from the remote storage.

There is an optimization point, that is, ``Select()`` method just returns the timeSeries which will be visited. In other words, we can push down the ``range`` and ``lookbackDelta`` to the remote storage.

However, the optimization can'd adjust to the SubQuery. So, I suggest adding ``SubQueryStep`` to check current vectorSelector in ``Select()``.

**Comment by codesome** [comment]
> For the inner VectorSelector, it should choose 10s not 20s as the step parameter. So, I suggest adding the SubQueryStep parameter in SelectHints.

It already does that, doesn't it?

**Comment by wanghaao** [comment]
> > For the inner VectorSelector, it should choose 10s not 20s as the step parameter. So, I suggest adding the SubQueryStep parameter in SelectHints.
> 
> It already does that, doesn't it?

It just reset the interval, but we can't distinguish whether the vectorSelector was wrapped in a subquery in ``Select()`` according to the ``step`` field.

```go
func (ng *Engine) populateSeries(querier storage.Querier, s *parser.EvalStmt) {
	var evalRange time.Duration
	parser.Inspect(s.Expr, func(node parser.Node, path []parser.Node) error {
		switch n := node.(type) {
		case *parser.VectorSelector:
			start, end := ng.getTimeRangesForSelector(s, n, path, evalRange)
			interval := ng.getLastSubqueryInterval(path)
			if interval == 0 {
				interval = s.Interval  // the interval has been reset .......
			}
.............
.............
```

There is an optimizable point that we can improve. In the ``Select()`` of ``Querier``, we can push down the logic about ``lookbackDelta`` and ``range`` into remote storage. However, the optimization logic of ``subquery``  is different, and the  ``SubQueryStep`` field can help us to differ from other scenes.

**Comment by wanghaao** [comment]
Any doubts else? @codesome

**Comment by codesome** [comment]
How does distinguishing subquery and not a subquery help? Do you have a use case where you will actually use it or is it just a "nice to have"?

**Comment by wanghaao** [comment]
> How does distinguishing subquery and not a subquery help? Do you have a use case where you will actually use it or is it just a "nice to have"?

The ``Select()`` of ``Querier``  will pull all timeSeries from remote storage.
```go
// Querier provides querying access over time series data of a fixed time range.
type Querier interface {
	LabelQuerier

	// Select returns a set of series that matches the given label matchers.
	// Caller can specify if it requires returned series to be sorted. Prefer not requiring sorting for better performance.
	// It allows passing hints that can help in optimising select, but it's up to implementation how this is used if used at all.
	Select(sortSeries bool, hints *SelectHints, matchers ...*labels.Matcher) SeriesSet
}
```
We can push down the logic of "lookBackDelta" and "range" to the remote storage, and it just needs to pull the required data. The following case will help you understand the optimization.
```SQL
PromQL: max(irate(metric[2m]))
query range: 7 days
step: 15min
```
For the calculation of each ``step``, it just needs the data of ``[current - 2min, current]``, and the data of the other 13 minutes is useless. It can reduce the data from the remote storage and improve the performance sharply.

However, if the ``VectorSelector`` is wrapped in a Subquery, we can't apply such optimization. ``Subquery`` will align the "step" to the ``start / end / original step`` in the ``eval``, and the  ``align step`` is different from the ``original step``. Therefore, we need to distinguish ``subquery`` and ``normal query``.

**Comment by bboreham** [comment]
It seems to me we could have the request say which data it wants - "2 minutes every 15 minutes aligned to X start time" - and not have it need to understand PromQL, subqueries, etc.  

(Nitpick: you used `irate` in your example, which only looks at the last two samples regardless of the size of the window. But I think that makes my point - we shouldn't need to have the storage provider understand all this.)

The point of putting the aggregation in the hints was if you already downsampled `max`, say, you can return that.

**Comment by wanghaao** [comment]
The calculation ``startTime`` of subquery is completely different from the ``startTime`` of a normal query. You can check the [original code](https://github.com/prometheus/prometheus/blob/c70d85baed260f6013afd18d6cd0ffcac4339861/promql/engine.go#L1651).

case 1:
```SQL
PromQL: rate(metric[2m])
query range: 7 days
step: 15min

For each step calculation, the data of 13 minutes are useless.
```

case2:
```SQL
PromQL: metric
query range: 7 days
step: 15min
lookbackDelta: 5min

For each step calculation, the data of 10 minutes are useless.
```

You shouldn't focus on the specific functions or aggregators, and the ``lookbackdelta``、``range`` and ``step`` are the key points.

**Comment by bboreham** [comment]
Are you saying it is impossible for the caller to say what data are required, but always possible for the callee to figure it out?

**Comment by wanghaao** [comment]
> callee

Sorry, I want to confirm whether you have understood this optimization point.

In my case, the callee is the remote storage. For the ``normal query``, the caller and callee both can figure out what data are required. For the ``subquery``, callee can't figure out that, because the caller will do ``step alignment`` in the calculation process. And the alignment is not visitable for the remote storage(i.e., callee), so I need the ``interval parameter`` of subquery and process the "step alignment" in the remote storage.

**Comment by bboreham** [comment]
Yes, I think I understand your point.
I am proposing something I feel is better, because it is less complicated and less coupled to specific implementation details of PromQL. 

I’ll try to say it differently: the protocol should allow the caller to ask for specific data, in terms of samples or time periods. All requirements of alignment would be specified directly, e.g. “every 15 minutes starting at 10:03:21”.

**Comment by wanghaao** [comment]
> Yes, I think I understand your point. I am proposing something I feel is better, because it is less complicated and less coupled to specific implementation details of PromQL.
> 
> I’ll try to say it differently: the protocol should allow the caller to ask for specific data, in terms of samples or time periods. All requirements of alignment would be specified directly, e.g. “every 15 minutes starting at 10:03:21”.

So, your suggestion is to identify the ``step`` from ``client request parameters ``, not from the ``vectorSelector``.  But I also need the specific ``interval`` of subquery and do ``step alignment`` in remote storage. 

Moreover, the suggesting solution can't adapts the following case,
```SQL
promql:  metric_1 + rate(metric_2[2m:10s])
query range: 7 days
step: 15min
lookbackDelta: 5min
```
In this case, the ``step`` of ``metric_1`` is 15min, while the ``step`` of ``metric_2`` is 10s. Therefore, I must get the ``step/interval`` from the specific ``vectorSelector``.

**Comment by bboreham** [comment]
Yes the two requests have different steps and different alignment. Why is that impossible to state as such?  Why is it essential to reference the word “subquery” in the protocol?

**Comment by wanghaao** [comment]
> Yes the two requests have different steps and different alignment. Why is that impossible to state as such? Why is it essential to reference the word “subquery” in the protocol?

There are two ``VectorSelector`` in such case, not two requests. As you say, for the vectorSelector of ``metric_1``, the ``step`` value in the protocol is  15min. The value of ``metric_2`` is 10s.

However, the alignment process of ``normal query`` and ``subquery``  is completely different, so I need a field to differs subquery from other scenes and execute different alignments.

**Pull request closed without merging**
