### PR TITLE
Handle more screen sizes with console templates.

### PR DESCRIPTION
**Pull request by brian-brazil**
This is based on #1198, and avoids all the weird
behaviour where the graphs aren't aligned.

---

This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/1450)

### CODE REVIEW

**Comment by juliusv** [comment]
Is it intentional that the LHS menu doesn't go all the way to the bottom anymore? It looks a bit broken to me:

newconsoles

Also, the margin at the top of the RHS Overview table is now gone, which also looks stuffed.

**Comment by brian-brazil** [comment]
> Is it intentional that the LHS menu doesn't go all the way to the bottom anymore?

That's the tradeoff for fixing the other problems. Ultimately I plan to make all of the background black (as that's what the cool kids are doing these days), which will resolve this.

> Also, the margin at the top of the RHS Overview table is now gone, which also looks stuffed.

Tweaked.

**Comment by StephanErb** [comment]
FWIW, the LHS menu has been that way in Firefox for a while now. It looked OK in chrome.

**Comment by fabxc** [comment]
@brian-brazil what about this one?

**Comment by brian-brazil** [comment]
I've been waiting on code review for it. Not urgent, and not blocking anything.

**Comment by krasi-georgiev** [comment]
@brian-brazil do we still need this? I just tested the UI and seems to render fine when resizing to smaller window sizes. tested on chrome and firefox

**Comment by brian-brazil** [comment]
There was a recent PR that must have finally fixed this.

**Pull request closed without merging**
