### PR TITLE
discovery/marathon: #1722 - ignore apps with zero ports

### PR DESCRIPTION
**Pull request by rohit01**
Fixed commit diff and squashed commits

### CODE REVIEW

**Comment by beorn7** [comment]
@xperimental Once we have green light from you, I'll merge.

@sdurrheimer The circleci error message here is really weird (and unrelated to this change):
```
An error occurred trying to connect: Post http:///var/run/docker.sock/v1.21/images/create?fromImage=quay.io%2Fprometheus%2Fgolang-builder&tag=1.6.2-mips: EOF
```

Seems like wrongly assembling a URL. Any idea?

**Comment by sdurrheimer** [comment]
@beorn7 Will take a look as soon as possible.

**Comment by sdurrheimer** [comment]
@beorn7 I have successfully rebuilt the PR. Looks like it was due to a flanky docker's daemon from CircleCI.

**Comment by beorn7** [comment]
Cool. Thanks @sdurrheimer , and boo for flaky CI systems.

**Comment by xperimental** [comment]
@beorn7 Tested it with our local Marathon installation. Could reproduce the bug with an application configuration which has no port-forwards defined. The patch nicely fixed the panic.

@rohit01 All our services have a network interface so this did not occur here, good job finding this bug.

The issue with the name remains valid though. It is still about tasks having an empty ports array and not having an empty tasks array (the latter happens quite often), but I'll leave the decision over this to the others. The code and test is fine.

**Comment by beorn7** [comment]
@rohit01 Perhaps you could indeed change the commit description to "zero ports"? Just in case somebody reads through the history at a later point…

After that, I'll merge here and in master.

**Comment by rohit01** [comment]
@beorn7 I suspected, you might say this while writing the test case :-p

I think, the message is correct as it fixes "Zero Task" issue. The explanation is simple. If you parse an empty JSON (Unmarshal) string "{ }" using golang to the "Task" struct, it will still be successful. The result object would be equivalent of "Task{}", i.e, initializing without any values. All elements in the struct would assume zero values. Same happens here.

If you could get me a use case where it fixes only zero port issue, I would be happy to edit my commit message!

**Comment by rohit01** [comment]
Test case clarification: The test case was not working for zero tasks array, so I wrote wrote it with a blank task object. But, it served the purpose.

**Comment by beorn7** [comment]
I'm not a Marathon expert, I'm just paraphrasing what @xperimental said.

From a quick look, I get the impression that the marshaling happens on the app level, and if that contains an empty task array, it will not even enter the loop https://github.com/prometheus/prometheus/pull/1729/files#diff-aef8c47eac97d74bbe871188369cedfdR218 . Only if it contains at least one task, the loop will be entered, and if then the task contains no ports, your fix kicks in.

I might be wrong, but it is in line with what @xperimental said.

**Comment by rohit01** [comment]
Done.

**Comment by beorn7** [comment]
Thanks so much, everybody.

**Comment by fabxc** [comment]
Neither of my concerns of the actual PR were addressed: https://github.com/prometheus/prometheus/pull/1727

**Comment by beorn7** [comment]
@fabxc Sorry, drowned in the number of commits and PRs for this.
Will have a look.

**Comment by fabxc** [comment]
Filed #1733

**Comment by rohit01** [comment]
@beorn7 / @fabxc: Thanks. Could you please release 0.19.2 with this fix.
Tag: https://github.com/prometheus/prometheus/releases/tag/0.19.2

**Pull request merged**
