### PR TITLE
Add scrape_bytes_scraped metric.

### PR DESCRIPTION
**Pull request by tomwilkie**
I was surprised to find we don't export the number of bytes scraped.  Or I missed it :-)

Not sure about (a) metric naming and (b) just using sl.lastScrapeSize - feedback welcome.

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com

### CODE REVIEW

**Comment by roidelapluie** [comment]
sl.lastScrapeSize would not work as we do not reset it when the scrape is dropped because of target_limit. Also, when the scrape is empty, we do not set sl.lastScrapeSize to 0, but we keep the old value.

**Comment by tomwilkie** [comment]
Yes, that was why I didn't use it.

**Comment by roidelapluie** [comment]
Also if I remember correctly that request was denied in the past as the number of samples scrapes should give a good hint about the size of the scrape. I try to find the discussion.

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/issues/6803

**Comment by brian-brazil** [comment]
What is this for, and what exact operational problem is it trying to solve?

This metric increases the cost of every single scrape that every single Prometheus does, so there has to be a very strong use case for adding additional metrics of this nature.

**Comment by roidelapluie** [comment]
Ping @tomwilkie  :) do you have further input?

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and decided to close this, as adding that metric for every scrape it is pretty expensive. We also have metrics around metadata cache if that's the issue you try to address.

Thanks!

**Comment by roidelapluie** [comment]
This would actually be useful to debug #8762 where we do not know if there are big label values or lots of metrics, but we just want to find the biggest scrape target.

**Pull request closed without merging**
