### PR TITLE
Fix solaris build.

### PR DESCRIPTION
**Pull request by ptribble**
Signed-off-by: Peter Tribble <peter.tribble@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Does statfs_linux_386.go also need updating?

**Comment by brian-brazil** [comment]
Can we remove the line with netbsd etc in that file then?

**Comment by ptribble** [comment]
I think you can (and the other excludes). I would say that it's not part of this change, and I have no access to those platforms to test it either.

**Comment by brian-brazil** [comment]
The CI will cover it.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
