### PR TITLE
MemPostings: Use CockroachDB Swiss Map for label values/postings map

### PR DESCRIPTION
**Pull request by aknuds1**
Test of [CockroachDB Swiss Map](https://github.com/cockroachdb/swiss) instead of standard `map` in `tsdb/index.MemPostings`, for performance. Requested by @bboreham for prombench-ing, so we can see if there's any real difference.

Confer corresponding [PR](https://github.com/prometheus/prometheus/pull/13644) for dolthub implementation.

### CODE REVIEW

**Comment by bboreham** [comment]
On these metrics, this one is substantially worse.  However I can't see the `swiss.Map` in a CPU profile so unclear what this is telling us.

image

**Comment by aknuds1** [comment]
Closing since outlived its usefulness.

**Pull request closed without merging**
