### PR TITLE
Fix serving of Prometheus logo, move it into 'src/images'

### PR DESCRIPTION
**Pull request by Nexucis**
Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
Hmm, why?

**Comment by Nexucis** [comment]
oups I forgot to explain.
So it's required because when you are compiling prometheus (golang + react-app), then without this PR, the logo is served at /static/react-app and not at the root like it is required.
So when you are compiling prometheus and started it, you will see that the logo is missing. This PR is fixing that.

**Comment by juliusv** [comment]
Ah, why don't we just point the `src` in the `img` to the correct (non-root) path then? The only reason we serve the favicon and manifest at the root is because browsers automatically look there for them.

**Comment by Nexucis** [comment]
probably we will have to move the logo outside of the `public` folder if we want to do that. Because we need to have the same relative path when you are using `npm start` or when you are compiling Prometheus. From my understanding when you put something in the `public` folder, then you need to serve it at the root.

So probably if we move the image in the `src` folder, it should work. I can try that if we are ok to move this img.

**Comment by juliusv** [comment]
Yeah, I'd just move it to `src`, as that's the common way to handle images in React apps anyway unless you have a special reason to put things into `public` (see https://create-react-app.dev/docs/using-the-public-folder#when-to-use-the-public-folder).

**Comment by juliusv** [comment]
(and with `src` I mean something like `src/images` of course)

**Comment by Nexucis** [comment]
alright it works like a charm @juliusv :D.
Probably we should fine a better name for this PR, the title is not accurate anymore haha.

**Comment by juliusv** [comment]
:+1: Yeah, I'll rename the PR title

**Pull request merged**
