### PR TITLE
Fixed pathPrefix for web pages

### PR DESCRIPTION
**Pull request by codesome**
Fixes [#4004](https://github.com/prometheus/prometheus/issues/4004)

### CODE REVIEW

**Comment by brian-brazil** [comment]
@beorn7

**Comment by beorn7** [comment]
Test timed out. I have restarted it.

**Comment by beorn7** [comment]
This is a bug fix and should go into the release-2.2 branch first rather than directly to master.

**Comment by beorn7** [comment]
I guess that should do the trick. :+1:

**Comment by codesome** [comment]
@beorn7, changing the base to `release-2.2` here adds many commits from `master` as `codesome:route-prefix` was based from `master`. Do you want me to open another PR for `release-2.2`?

**Comment by beorn7** [comment]
@codesome Does it work if you rebase your own codesome:route-prefix branch on top of the release-2.2 branch and force-push your branch?

**Comment by codesome** [comment]
@beorn7 Done

**Comment by beorn7** [comment]
Cool. I'll merge on green.

**Pull request merged**
