### PR TITLE
Use an RW lock to checkpoint fingerprint mappings.

### PR DESCRIPTION
**Pull request by beorn7**
This has to be backported to 0.13.x.

@fabxc @juliusv

### CODE REVIEW

**Comment by fabxc** [comment]
:+1:

**Comment by beorn7** [comment]
I have no created a new branch `release-0.13`, backported this fix to that branch, and cut 0.13.4 there. Do you think that is a sane approach? @fabxc @juliusv

**Comment by fabxc** [comment]
Yes, that's the right way to go :+1:

**Comment by juliusv** [comment]
:+1:

@fabxc @beorn7 - please remember to delete branches after merging (via the "Delete branch" button that appears immediately after pressing the merge button). Otherwise we'll continue accumulating old PR branches...

**Comment by beorn7** [comment]
OK, but the release-0.13 branch is special as we will never merge it into master. (Or will we?) OTOH, the commit and the tag is there, so we would not need that branch anymore, and we could recreate it if we ever need to cut 0.13.5...

Anyway, building the binary now.

**Comment by juliusv** [comment]
@beorn7 Yeah, that one should be fine. I was talking about the `beorn7/fingerprint` branch. Just have seen a lot of not-deleted branches after PR merges these days :)

**Comment by beorn7** [comment]
I see... I deleted all my merged branches now. @juliusv There are a number of very old stale branches listed at https://github.com/prometheus/prometheus/branches/stale . Perhaps you can check them out and delete as you see fit.

**Pull request merged**
