### PR TITLE
Adding URL support for file_sd_configs

### PR DESCRIPTION
**Pull request by matthiaslee**
The attached changes allow `file_sd_configs` to retrieve json/yaml target files from http(s) locations.
This is especially useful for service discovery of non-supported or custom service discovery providers.

Simply add a URL to the `files` list and it will be picked up every time the `refresh_interval` triggers, alternatively add a separate `urls` list. 

```yaml
scrape_configs:
- job_name: dynamic-prom-targets
  file_sd_configs:
   - files:
     - https://internal-backend.acme.org/dynamic-targets/prom-targets.json
```

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. We intend to have exactly one generic interface at each hook point, and we already have file_sd_configs. If you want to work from a URL you can always setup wget in a cronjob to feed into file_sd_configs..

**Comment by brian-brazil** [comment]
You're basically bundling two distinct SDs into one, and we already have a generic SD and a moratorium on new SDs. If you feel our existing SDs are not sufficient you are free to integrate via file_sd_configs.

**Comment by a2ndrade** [comment]
@brian-brazil would you consider accepting a new `url_sd_configs` service discovery configuration instead? Basically, reworking this PR so that that file and URL-based configurations are not conflated.

**Comment by cstyan** [comment]
@matthiaslee have you tried this https://prometheus.io/blog/2018/07/05/implementing-custom-sd/ ?

**Comment by brian-brazil** [comment]
No, as I said we already have a generic SD and we've also a moratorium. See https://github.com/prometheus/prometheus/tree/master/discovery#service-discovery

**Comment by matthiaslee** [comment]
@cstyan I have not, but I'll take a peek, thanks.

**Comment by krasi-georgiev** [comment]
I will post the canned reply as it highlight all the important points why we can't accept any new providers and the link to the example that will enable you to implement the same without any code changes in Prometheus itself.
I had quick chat with Brian on IRC and indeed at the moment even something as small as a http url_sd_configs would mean more bugs and more maintenance so we would rather focus on stability rather than adding more new stuff especially when there is already a good way to achieve the same as per the example in the link below. 


We can only provide the stability and performance we want to provide if we can properly maintain the codebase. This includes, test integrations in an automated and scalable fashion. For this reason, we are suggesting people to integrate via [file SD](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cfile_sd_config%3E) and [here](https://github.com/prometheus/prometheus/tree/master/documentation/examples/custom-sd) is a very good example to show this in practise. We would be more than happy to list this on our [integrations page](https://prometheus.io/docs/operating/integrations/).

Even if existing integrations can not be tested in an automated fashion, we will not remove them for reasons of compatibility. This also means that any additions we take on, or any changes to existing integrations we make or accept, will mean maintaining and testing these until at least the next major version, realistically even beyond that.

Feel free to question this answer on our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers), but be aware it's unlikely that you will get a different answer.

**Comment by roidelapluie** [comment]
Another approach is being implemented in #8839

**Pull request closed without merging**
