### PR TITLE
scrape: error on duplicate conflicting labels

### PR DESCRIPTION
**Pull request by roidelapluie**
cc @beorn7 

This is my proposal for #5861: error upon conflicting exported_ labels 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
I don't think we should ever be erroring here.

**Comment by roidelapluie** [comment]
Then we are back on  #5861 which does not have a clear solution proposal

**Comment by beorn7** [comment]
I think the solution in #5861 is “clearly” sketched out (for certain definition of “clear”). Just the implementation will be a bit more involved. I'm happy to take that issue once I have some idle cycles in my schedule (which won't be happening very soon). Luckily, the practical relevance is very very low (but it's one of those issues where it irritates me immensely that we don't have defined and workable behavior here).

**Comment by roidelapluie** [comment]
I did not find it clear. I am happy to implement if you can write down some tests/examples.

**Comment by beorn7** [comment]
See https://github.com/prometheus/prometheus/issues/5861#issuecomment-584239460

**Pull request closed without merging**
