### PR TITLE
Cut release 1.0.1

### PR DESCRIPTION
**Pull request by beorn7**
This includes cherry-picking of bug fixes that got merged into master instead of into the release-1.0 branch.

### CODE REVIEW

**Comment by SuperQ** [comment]
:+1:

**Comment by jimmidyson** [comment]
Would like to get #1835 in if possible?

**Comment by SuperQ** [comment]
@jimmidyson We'll add that to 1.1.0, this release will be bugfix only.  But don't worry, 1.1.0 won't be a long wait.

**Comment by jimmidyson** [comment]
@SuperQ Cool thx!

**Comment by beorn7** [comment]
Yes, strictly bug-fix. 1,1.0 should be there, two...

**Comment by juliusv** [comment]
:+1:

**Pull request merged**
