### PR TITLE
Add unit test case for matcher.go

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Do we not already have tests that'd cover this that do general PromQL rendering?

**Comment by fenggw-fnst** [comment]
Thanks for the review!

Yes, but I am afraid that they don't cover L34 ~ L36.
https://github.com/prometheus/prometheus/blob/22aa21e5089d0bbba31756a830386da52158c548/pkg/labels/matcher.go#L34
If I intentionally mess up the string value in L34 ~ L36, no test case will report failure. (Messing up L33 will cause test failure.)

**Comment by brian-brazil** [comment]
Let's add a test for that at a higher level then, as that'll catch more issues.

**Comment by fenggw-fnst** [comment]
OK, understood.
I'll close this one and add a test as you said. Thanks!

**Pull request closed without merging**
