### PR TITLE
Remove inline Go vendor dir

### PR DESCRIPTION
**Pull request by SuperQ**
Remove the inline Go vendoring per Prometheus 2020 Dev Summit[0].

[0]: https://docs.google.com/document/d/1yuaPKLDvhJNXMF1ubsOOm5kE2_6dvCxHowBQIDs0KdU/edit

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by simonpasquier** [comment]
I'm for this. You need to remove this line:

https://github.com/prometheus/prometheus/blob/3240cf83f08e448e0b96a4a1f96c0e8b2d51cf61/.golangci.yml#L2

**Comment by brancz** [comment]
I think someone mentioned this on IRC as well. The plan was to do this in node-exporter first and based on that experience potentially do it here. Are there any learnings from node-exporter? Or is it as simple as "works as expected, and without problems"?

**Comment by SuperQ** [comment]
Yup, we did this in the node exporter and there have been no issues so far.

**Review by bwplotka — APPROVED** [review]
VERY LGTM from my side. Now is the question: who merges this sweet PR and get those amazing deleted lines to their contributor statistics :heart: :upside_down_face:

**Comment by roidelapluie** [comment]
@SuperQ Do you want to do this before I do the dependecy update for the next release?

**Comment by SuperQ** [comment]
Closing in favor of https://github.com/prometheus/prometheus/pull/8460

**Comment by roidelapluie** [comment]
Really closing :)

**Pull request closed without merging**
