### PR TITLE
Upgrade yaml version to v3

### PR DESCRIPTION
**Pull request by geekodour**
See #5435 
See #21 

This PR just upgrades the yaml.v2 package to yaml.v3, preserving of comments is not added yet, I think it'll be good to do that in a separate pr. 

As discussed in riot /w @simonpasquier about the following snippet,  a "null" value for regex is equivalent to the zero-value string (eg. the empty string) which is true for yaml.v2
```
  relabel_configs:
  - regex:
    replacement:   static
    target_label:  abc
``` 
but with `yaml.v3` it is interpreted as null value,  so had to set `""` to `regex` explicitly in `/config/testdata/conf.good.yml`

### CODE REVIEW

**Comment by simonpasquier** [comment]
There's no official release of `gopkg.in/yaml.v3` (https://github.com/go-yaml/yaml/issues/487) so I would refrain on using it for now. The behavior change regarding null vs. empty strings deserves more investigation too IMO.

**Comment by brian-brazil** [comment]
We've had fun in the past with nulls and yaml, plus that technically a breaking change.

**Comment by slrtbtfs** [comment]
Another issue with yaml.v3 is, that is does behave in unpredictable ways when there are multiple YAML docs in one file.

**Comment by brian-brazil** [comment]
We only ever have one YAML doc, so that's not a concern.

**Comment by bwplotka** [comment]
It's been a while since we saw movement here, so I would close this - we can always reopen. Thanks @geekodour!

We use v3 already a bit, but we would love to use yaml.v3 just for consistency at some point--low priority though - we have https://github.com/prometheus/prometheus/issues/21 to track the motivation for it.

(Triaged during our bug scrub session)

**Pull request closed without merging**
