### PR TITLE
Lint clean-up

### PR DESCRIPTION
**Pull request by beorn7**
OK, so this has escalated quickly…

It all started with me updating golangci-lint so that it doesn't run out of memory anymore. However, the new version flagged a bunch of issues, which I thought I can quickly fix.

Then I realized that golangci-lint limits the number of issues displayed by default. So where were actual a _lot_ more of them…

But we have to address them anyway, because we certainly want to update golangci-lint now and then.

Since I had already started, I went through all of them. See detailed description in the first commit.

For addressing one issue, I changed an `else if` cascade into a `switch`, which reminded me that I have been planning to get rid of `else if` cascades for a while. So I did that, too… See second commit for detailed explanations.

I separated the whole things into two commits so that we can decide about them separately. I think the golangci-lint thing is uncontroversial. Maybe we might want to disable the empty-block rule altogether. But it's actually a good rule in general, just not for `for` loops. This might be fixed in upstream revive (again, see commit description), but for now, I think we can go with the ` // nolint:revive` comments.

If there is a controversy about the `switch` vs. `else if`, we can just not do it. I can hardly imagine that anyone really _prefers_ `else if`, but I can imagine that some of you are lukewarm about the change and wouldn't like to suggest any preference. (I would still argue that consistency is better, even if only via a role model and not as a hard requirement.)

### CODE REVIEW

**Comment by mmorel-35** [comment]
Hi @beorn7 ,
I recently opened #12241 with similar changes to some of your changes . Are you aware of this ?

**Comment by beorn7** [comment]
Ah cool. No, I haven't seen that.

The overlap between both PRs seems mostly the `else if` → `switch` transition, which is good. Reinforces my believe that it is a good idea.

But then there are a whole lot of changes that are different in both PRs. Should be no problem to merge them both. But let's see what the code owners say…

**Comment by roidelapluie** [comment]
LGTM but unfornately needs a rebase

**Comment by beorn7** [comment]
Rebased. I'll merge on green.

**Pull request merged**
