### PR TITLE
React UI: Some /rules page follow-ups

### PR DESCRIPTION
**Pull request by juliusv**
Just a few follow-ups for now, as I'm a bit short on time today:

- Single table for all rule groups, so that all columns are aligned on
  the page (like in the old UI).
- Remove redundant direct cell styling / switch to using "rule-cell"
  also for recording rules.
- Remove extra left spacing of graph expression links.
- Remove unused CSS.

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@boyskila @Harkishen-Singh

**Comment by Harkishen-Singh** [comment]
@juliusv @boyskila I think we can merge this.

**Comment by boyskila** [comment]
@juliusv do you think we can merge this PR?

**Comment by gouthamve** [comment]
Hi @juliusv, there are a lot of conflicts here, could you rebase if you're still interested? If not, could we close this?

**Comment by roidelapluie** [comment]
We have looked at this pull request during our bug scrub.

Considering that this has drifted a lot, @juliusv would you consider reopening a new pull request if that's needed?

Thank you for your contribution.

**Pull request closed without merging**
