### PR TITLE
chore: switch to go 1.15 in go mod

### PR DESCRIPTION
**Pull request by andyzhangx**
chore: switch to go 1.15 in go mod

### CODE REVIEW

**Comment by roidelapluie** [comment]
This has not been done because some downstream did not rebuild with go1.15. cc @SuperQ

**Comment by SuperQ** [comment]
This is a minimum requirement set. We don't want to change this unless we actively are using a Go 1.15 feature. Is there an intended use case for switching the minimum version?

**Comment by andyzhangx** [comment]
> This is a minimum requirement set. We don't want to change this unless we actively are using a Go 1.15 feature. Is there an intended use case for switching the minimum version?

@SuperQ We hit a read/write error in SMB file system, https://golang.google.cn/doc/go1.15 fixed the EINTR handling issue, details:
```
Packages os and net now automatically retry system calls that fail with EINTR. Previously this led to spurious failures, which became more common in Go 1.14 with the addition of asynchronous preemption. Now this is handled transparently.
```
So if prometheus could build with go 1.15, it should work.

BTW, if hit following error when running `make docker` with go 1.15, is that expected?
```console
# go version
go version go1.15.4 linux/amd64
# make docker
>> bundling npm licenses
rm -f "npm_licenses.tar.bz2"
find web/ui/react-app/node_modules -iname "license*" | tar cfj "npm_licenses.tar.bz2" --transform 's/^/npm_licenses\//' --files-from=-
docker build -t "prom/prometheus-linux-amd64:1.15" \
        -f ./Dockerfile \
        --build-arg ARCH="amd64" \
        --build-arg OS="linux" \
        ./
Sending build context to Docker daemon  790.3MB
Step 1/22 : ARG ARCH="amd64"
Step 2/22 : ARG OS="linux"
Step 3/22 : FROM quay.io/prometheus/busybox-${OS}-${ARCH}:latest
 ---> 59cded67539a
Step 4/22 : LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"
 ---> Using cache
 ---> 49829ff644e7
Step 5/22 : ARG ARCH="amd64"
 ---> Using cache
 ---> 7c1de234986b
Step 6/22 : ARG OS="linux"
 ---> Using cache
 ---> 2b9671ba0e3a
Step 7/22 : COPY .build/${OS}-${ARCH}/prometheus        /bin/prometheus
COPY failed: stat /var/lib/docker/tmp/docker-builder630182004/.build/linux-amd64/prometheus: no such file or directory
Makefile.common:237: recipe for target 'common-docker-amd64' failed
make: *** [common-docker-amd64] Error 1
```

**Comment by roidelapluie** [comment]
Prometheus is built with go 1.15.

**Comment by SuperQ** [comment]
Yes, the go.mod value is a _minimum_ version, not the only version to build with. We only change this when we use language features that are not backwards compatible. You can build Prometheus with 1.14 and later, including 1.15, 1.16, etc. Our official builds are with 1.15 currently.

**Pull request closed without merging**
