### PR TITLE
Rename __meta_dns_srv_name to __meta_dns_name

### PR DESCRIPTION
**Pull request by fabxc**
@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you call out in the description that this is a breaking change?

:+1:

**Comment by fabxc** [comment]
Done.

**Comment by chr4** [comment]
This leaves the documentation [here](https://prometheus.io/blog/2015/06/01/advanced-service-discovery/#discovery-with-dns-srv-records) out of date. 

Not sure where to put this, as as far as I can tell, the blog is not maintained with git.

My relabling didn't work and it took me a while to find this PR, updating my SRV DS config to use `__meta_dns_name` instead of `__meta_dns_srv_name` fixed it.

**Comment by brian-brazil** [comment]
https://github.com/prometheus/docs/blob/master/content/blog/2015-06-01-advanced-service-discovery.md is what you're looking for

**Comment by chr4** [comment]
Thanks! Created a pull-request fixing the docs.

**Pull request merged**
