### PR TITLE
relabel: improve logic for target labels

### PR DESCRIPTION
**Pull request by bboreham**
For `Lowercase`, `KeepEqual`, etc., we do not expand a regexp, so the target label name must not contain anything like `${1}`.

Also for the common case that the `Replace` target does not perform any template expansion, check that the entire string passes label name validity rules.

In the `Replace` implementation:
* If `cfg.TargetLabel` is a template like `$1`, it won't match any labels, so no point calling `lb.Del` with it.
* Similarly if `target` is not a valid label name, it won't match any labels, so don't call with that either.
* The intention seems to have been that a blank _value_ would delete the target, so change that code to use `target` instead of `cfg.TargetLabel`.

### CODE REVIEW

**Comment by roidelapluie** [comment]
I think we should not do this as we plan to support in the short future any UTF8 chars in label names, including $.

**Comment by bboreham** [comment]
That seems to imply the need to escape `$` in these templates?

**Comment by roidelapluie** [comment]
Target Label is not a regex.

**Comment by bboreham** [comment]
Indeed, it is a template.

**Comment by bboreham** [comment]
The code already called out `HashMod` which checks differently:
https://github.com/prometheus/prometheus/blob/b987afa7ef948461100b914fb6aea5e7195fd078/model/relabel/relabel.go#L129

My first point is trying to say that `Lowercase` should do the same, not this:
https://github.com/prometheus/prometheus/blob/b987afa7ef948461100b914fb6aea5e7195fd078/model/relabel/relabel.go#L120

When labels allow UTF-8 characters this logic should change, but they should still be the same.

**Review by roidelapluie — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
