### PR TITLE
Type check rule expr during parsing to fix incorrect error line number

### LINKED ISSUE #2014: Prometheus reports malformed alert at wrong line number
Greetings Prometheans!

**See update below...**

I am trying to setup alerting for my cluster and have run into a troublesome bug.  What I want is pretty standard; to alert for filesystems with less than 20% space free.

Based upon examples I've seen elsewhere it seems the correct thing to do is:

```
ALERT NodeFilesystemUsageHigh
    IF node_filesystem_free{} / node_filesystem_size{} < 0.2
    LABELS { severity = "page" }
    ANNOTATIONS {
    summary = "Node filesystem usage is high",
    description = "Node {{ $labels.instance }}'s filesystem {{ $labels.filesystem }} has less than 20% disk space remaining."
    }
```

My understanding is that the expression `node_filesystem_free{} / node_filesystem_size{} < 0.2` should produce an instance vector of all metrics representing a filesystem with under 20% free.  I've tried it out in the console:
-  `node_filesystem_free{} / node_filesystem_size{}` gives a list of all my filesystems with a value between `0` and `1` representing free space.  So far so good.
-  `node_filesystem_free{} / node_filesystem_size{} < 0.2` gives an empty list because this is a good day and none of my filesystems are full

However, when I try to deploy this rule by reloading my Prometheus config, it logs the error:

```
time="2016-09-21T08:21:58Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:221"
time="2016-09-21T08:21:59Z" level=error msg="Failed to apply configuration: error loading rules, previous rule set restored: error parsing /etc/prometheus/alerts.rules: parse error at line 25, char 2: expected type vector in alert statement, got scalar" source="main.go:239"
time="2016-09-21T08:21:59Z" level=error msg="Error reloading config: one or more errors occured while applying the new configuration (-config.file=/etc/prometheus/prometheus.yml)" source="main.go:146"
```

I've been banging my head against this one for a few hours now.  Doubtless I'm doing something wrong but no amount of googling reveals what it is.  Can somebody please point me in the right direction?

In case it's relevant here's my Prometheus build information:

```
Build Information
Version     1.1.2
Revision    36fbdcc30fd13ad796381dc934742c559feeb1b5
Branch  master
BuildUser   root@a74d279a0d22
BuildDate   20160908-13:12:43
GoVersion   go1.6.3
```

### PR DESCRIPTION
**Pull request by Conorbro**
Fixes #2014

### CODE REVIEW

**Comment by Conorbro** [comment]
@fabxc 

Can you take a quick look at this fix for issue #2014. 

Essentially the bug was caused by type checking after all the parsing had completed which would result in the lexer pointing to the end of the file rather than the line where the parse error was actually detected.

I fixed the issue by type checking during parsing rather than afterwards, however it now always reports the correct line number +1 when a parse error is encountered. (For example, if the line with the parse error is on line 4, it'll now report line 5 etc.)

I’ve written a bit of a workaround to circumvent this by moving the lexer back one line when these errors are detected but I was wondering if you had any ideas as how to handle it in a better way? 

I can elaborate further on the nature of this issue and what I did if need be.

**Comment by brian-brazil** [comment]
Is this still relevant with the new rule format?

**Comment by Conorbro** [comment]
I quickly tested with 2.0 and this still appears to be an issue.

E.g.

```
groups:
- name: alert.rule
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: page
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} down
  - alert: InstanceUp
    expr: increase(prolematic-expr[5m]) > 0
    for: 1m
    labels:
      severity: page
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down
        for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} down
```
Produces the error: 
>level=error ts=2017-12-01T14:39:02.305129605Z caller=manager.go:487 component="rule manager" msg="loading groups failed" err="group \"alert.rule\", rule 1: could not parse expression: parse error at char 41: binary expression must contain only scalar and instant vector types"

Which reports the incorrect rule and incorrect character position.

**Comment by brian-brazil** [comment]
That looks like zero-based numbering, so it is correct. We may be able to make it a bit clearer though.

**Comment by Conorbro** [comment]
Tested with the same error in what would be rule 0 which resulted in same error.

**Comment by Conorbro** [comment]
I'll open a PR improving this error message next week to include the name of the alerting/recording rule.

**Comment by brian-brazil** [comment]
This is obsolete.

**Pull request closed without merging**
