### PR TITLE
Enable reading secrets from files

### PR DESCRIPTION
**Pull request by mem**
This only addresses the prometheus/prometheus portion of this issue.
Similar issues exist in other repositories under the prometheus
organization.

Closes: #8551

Signed-off-by: Marcelo E. Magallon <marcelo.magallon@grafana.com>

### CODE REVIEW

**Comment by mem** [comment]
* This depends on an open review in promethes/common (https://github.com/prometheus/common/pull/320)
* This part of the code doesn't seem to have many tests, I wasn't sure whether they should be added
* Which documentation should be updated? I suppose it's only docs/configuration/configuration.md?

**Review by roidelapluie — COMMENTED** [review]
Thank you for this!

The change to sigv4 should be done in common: https://github.com/prometheus/common/tree/main/sigv4 and then prometheus should point at common.

The change to consul is not needed anymore. We should update the documentation instead, because reading the secrets from file is already possible: https://inuits.eu/blog/prometheus-consul-vault-228/

The change for EC2/OpenStack does not seem to read the file when it changes. Also, we will need the same for lightsail. 

Can we use our HTTP client with openstack to benefit from its capabilities directly?

**Comment by beorn7** [comment]
@mem @roidelapluie we have run into this during our bug scrub. It would still be nice to get this unstuck. @mem at first glance, @roidelapluie 's comment about sigv4 getting fixed upstream in prometheus/common is not addressed yet. Would you be willing to still work on this?
Maybe other comments still need to be addressed?

**Comment by beorn7** [comment]
Hello again from the bug scrub. We still think this is valuable, but there was no response to the last nag almost half a year ago. We are closing this now, but whoever wants to pick up the work, please re-open or create a new PR.

**Pull request closed without merging**
