### PR TITLE
fix wrong spells in live_reader.go

### PR DESCRIPTION
**Pull request by AllenZMC**
make the comment more readable

### CODE REVIEW

**Comment by AllenZMC** [comment]
I have merge two PRs @codesome

**Comment by codesome** [comment]
I would like to wait for about 1-2 weeks before merging this. If you find any more corrections in the meantime, please add it to the same PR. Thanks!

**Comment by cstyan** [comment]
@codesome this is good to merge

**Comment by krasi-georgiev** [comment]
@AllenZMC thanks, if you have the time/ambition to help we would appreciate to aggregate these spelling mistakes to cover many, not just few spelling mistakes.

Although these are useful, are also distracting to the rest of the maintainers for such small changes.

**Pull request merged**
