### PR TITLE
K8s SD: add endpoints labels metadata

### PR DESCRIPTION
**Pull request by fcddk**
K8s SD: add endponits labels metadata.

### CODE REVIEW

**Review by roidelapluie — COMMENTED** [review]
Thanks!

This would require docs update as well.

@brancz Can you please have a look at this?

**Comment by brancz** [comment]
It seems we forgot the same thing in `endpointslice`. Could you add it there as well? Otherwise this looks great, thank you!

**Comment by brancz** [comment]
Actually on second thought, let me just merge this, and if you want to feel free to do the follow up for `endpointslice` in a new PR! :)

**Comment by roidelapluie** [comment]
It would still be nice to have the documentation update :) Thanks!

**Comment by fcddk** [comment]
ok, i will add endpoint labels metadata  in endpointslice.

**Pull request merged**
