### PR TITLE
Update .codeclimate.yml

### PR DESCRIPTION
**Pull request by larkinscott**
Changed the vendor/ path in the exclude paths node.

### CODE REVIEW

**Comment by brancz** [comment]
Yes that looks like what we want 👍 lgtm

**Comment by beorn7** [comment]
I don't understand what the problem is with the previous config. It seems to do what it should do. Where do you see issues in vendored code? All the 45 issues Code Climate flags are in non-vendored code, and are legitimate issues with our own code.

**Comment by brancz** [comment]
That's true, but if I understand the CodeClimate UI correctly it now says that the vendored code went from grade A -> to not existent anymore, so it is entirely ignored - which is what I was going for, I don't want to see the vendored and generated code at all in the UI even if it is not counted into the grade I still don't want it to bloat the UI.

**Comment by beorn7** [comment]
So what you are saying is that `/vendor` excludes the vendored code from the issue reporting, but `vendor/` additionally removes it from the UI? I can hardly imagine that's the case.

In any case, according to https://docs.codeclimate.com/docs/excluding-files-and-folders , the format used after this PR seems to be the documented one, so I'm merging this even if I don't think it will change anything.

**Pull request merged**
