### PR TITLE
Convert pathPrefix to not have trailing slash.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
Fixing test...

**Comment by juliusv** [comment]
Fixed.

**Comment by juliusv** [comment]
@benley @fabxc

**Comment by fabxc** [comment]
:+1:

**Comment by juliusv** [comment]
Still changing some tests which call functions with "/"... (they're not breaking anything, but it's cleaner to convert them to "").

**Comment by juliusv** [comment]
Done.

**Pull request merged**
