### PR TITLE
Make scheme relabelable via discovery

### PR DESCRIPTION
**Pull request by jimmidyson**
As discussed in https://github.com/prometheus/prometheus/issues/910#issuecomment-128305407.

Godep update is from merged prometheus/client_golang#156.

We are actually using this now (since 10 minutes ago ;)) in tandem with the Kubernetes discovery PR (#905).

### CODE REVIEW

**Comment by fabxc** [comment]
:+1:

**Comment by juliusv** [comment]
:+1: Thanks!

Note to both: I think in the future for any feature that'll require new documentation, it would be great to require either a docs PR or an issue for it filed in https://github.com/prometheus/docs/issues along with the change that adds features. That way at least we don't forget to document anything. Added https://github.com/prometheus/docs/issues/153 for this one.

**Comment by jimmidyson** [comment]
@juliusv Fair point - I'll put in a docs PR too now & will try to remember to do so in future (docs not my forte).

**Comment by fabxc** [comment]
:+1:

**Pull request merged**
