### PR TITLE
Reduce Prometheus pull requests builds

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Review by LeviHarrison — APPROVED** [review]
Thanks!

**Comment by SuperQ** [comment]
Still took 20min to build, but seems slightly better.

**Review by SuperQ — APPROVED** [review]
LGTM, We should refactor this into the orb as new build jobs.

**Comment by roidelapluie** [comment]
Okay, let's first experiment this and see how it's going.

**Comment by roidelapluie** [comment]
> Still took 20min to build, but seems slightly better.

Yes, I did not change the number of builds per thread. I am more interested in reducing CPU usage than speed, and reducing the TB's we use each month (+/- 80 to 100 TB).

**Pull request merged**
