### PR TITLE
Fix target update error handling.

### PR DESCRIPTION
**Pull request by juliusv**
Fixes https://github.com/prometheus/prometheus/issues/1378

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc Hope I did this right...

**Comment by juliusv** [comment]
The behavior is now: on startup, bad targets will simply not appear (previously: crash).

On update, existing targets will stay as they are if creating the updated targets gives an error.

**Comment by matthiasr** [comment]
:+1: thank you!

**Comment by fabxc** [comment]
Didn't get to this yesterday. I think not showing up on startup can be confusing behavior that's hard to debug.
Would be hacky to implement differently right now though. One day I'll get to it...

**Pull request merged**
