### PR TITLE
Histograms/promtool tests

### PR DESCRIPTION
**Pull request by hdost**
Fixes https://github.com/prometheus/prometheus/issues/11170

Replacement for #11381

### CODE REVIEW

**Comment by codesome** [comment]
@hdost do you know if you will be able to work on this anytime soon?

**Comment by hdost** [comment]
Yes I have actually done some work , are the meetings still happening because I've tried joining a couple times, maybe i have the time wrong. 

Currently, the existing grammar tooling is hard to debug (possibly due to the form I'm trying to create the input format) 
I've started experimenting with using some different tooling altogether using a PEG grammar the initial creation has been better and the project/tooling around it is a bit better. 
However this is a bit of a bigger change than I think we might want to go down, but it removes quite a bit of the ambiguity. 
After reading the recent document around exposing metrics perhaps I might take a different angle on the format. 
I'll put together a small post in thoughts around the format and ingestion design.

**Comment by codesome** [comment]
I could not find anywhere what the syntax is supposed to be. I just found a suggestion comment in the linked issue. I have created [this doc](https://docs.google.com/document/d/1e8_DABwhVX4pWpDOyQLi556EH7-9aqi0puI1K8buAYo/edit#) to collaborate on the syntax and few examples for reference before we dive into the parser.

**Comment by beorn7** [comment]
:wave: from the bug scrub.

We believe this has been superseded by more recent work on the testing framework. @hdost if you disagree, please follow up. 
We'll close this for now.

**Pull request closed without merging**
