### PR TITLE
Add tests for tsdb CLI commands

### LINKED ISSUE #5864: Add tests for the tsdb cli tool
can start with simple test for the ls, analyze and dump commands.
1. create a block with `createBlock()`
2. run each command
3. compare expected vs actual output.

### PR DESCRIPTION
**Pull request by obitech**
Signed-off-by: obitech <ajknipping@mailbox.org>

Copies over work from https://github.com/prometheus/tsdb/pull/673

Resolves #5864

---

This PR introduces tests for the TSDB CLI tool, verifying the output is correct.

A requirement for this is to refactor out certain utility functions such as createBlock (-> `CreateBlock`) and genSeries (-> `GenSeries`) into a new file, mocks.go, so they can be imported by package main. Certain other types and functions that are required by those test functions are moved out of the respective test files, where they were defined previously, into `mocks.go`.

In order to work around annoying `\t` expansion in `os.Stdout`, all white space is stripped from expected and actual in `main_test.go`

## Test ls
`printBlocks()` now takes an `io.Writer` which can be tested with a `bytes.Buffer`.

##Test analyze
`analyzeBlock()` now takes an `io.Writer` which can be tested with a `bytes.Buffer`.
The functionality of retrieving a block by ID, out of a `[]BlockReader` has been factored out into the function `extractBlock()`, in order to increase testability.

### CODE REVIEW

**Comment by obitech** [comment]
/cc @krasi-georgiev 
/cc @gouthamve 
/cc @bwplotka 

The last discussion point before archiving was: https://github.com/prometheus/tsdb/pull/673#discussion_r312738020

**Comment by krasi-georgiev** [comment]
@obitech I don't think I would have time to look into this properly anytime soon, but having CreateBlock and GenSeries in a package `mocks` doesn't sound right. 
We need to think more how to do this properly.

btw there is another PR for an import tool and this one also uses the create block func so maybe need to put it an import package and expose it like tsdb.CreateBlock
https://github.com/prometheus/tsdb/pull/671

**Comment by obitech** [comment]
@krasi-georgiev ok no worries. Maybe we wait what #671 brings and then pick this PR back up?

**Comment by krasi-georgiev** [comment]
Yeah def, thanks for the understanding.

I will try to revisit soon.

**Comment by beorn7** [comment]
Sorry for letting this become stale.

@krasi-georgiev does your removal of your assignment imply that you aren't able to work on this anymore?

It would be good to get this in, but it probably needs a lot of updates after all those months…

**Comment by krasi-georgiev** [comment]
yeah I don't think I will have time to look into this anytime soon if at all.

**Comment by beorn7** [comment]
@bwplotka @codesome can any of you shepherd this towards merging?

@obitech are you still up to work on this?

**Comment by obitech** [comment]
Hey @beorn7, happy to pick it back up if someone can answer some questions/steward it. If it's not too time critical 🙂

**Comment by beorn7** [comment]
@obitech great to hear. 

@bwplotka @codesome  could you comment if you are able to help?

**Comment by bwplotka** [comment]
Thanks for this! Sounds like the issue was closed https://github.com/prometheus/prometheus/issues/5864 given the code moved a lot, but the tests would be still nice to have!

Really sorry @obitech for lag on our side, we will be better next time if you are around!

Closing this for now, as it's simpler to start from scratch now.

(Triaged during our bug scrub session)

**Pull request closed without merging**
