### PR TITLE
promql: Remove interpolation of vector values.

### PR DESCRIPTION
**Pull request by brian-brazil**
The current behaviour produces values that are not
from rules or scrapes. So if for example I have
a boolean 0/1 it can be returned as 0.2344589. This
prevents a number of advanced use cases, introduces
race conditions and can produce misleading graphs.

@juliusv

### CODE REVIEW

**Comment by juliusv** [comment]
Hmm, this just removes interpolation completely (btw., then the `interpolateSamples` function is now unused and could be removed). This will return less accurate results at least for graphed aggregations of unaligned values, since being able to interpolate the value at a common timestamp based on the sample before and after that common timestamp leads to a more accurate representation of the value that would have been scraped if all series got scraped exactly at that common timestamp. I'm not sure if we should just ignore that or offer some kind of conditionality based on which the interpolation is enabled or not. Let me play with this a bit tonight/tomorrow...

**Comment by fabxc** [comment]
This. There were numerous requests for this in the past – but they all mentioned optionally turning it off, not that it was considered completely useless.

**Comment by brian-brazil** [comment]
> (btw., then the interpolateSamples function is now unused and could be removed)

Done

> less accurate results 

It may be less precise, but I'm not sure about less accurate. For my case it's definitely more accurate, as it's no longer producing impossible results.

Currently we're showing the user data that's at best a guess, which may lead them into a false sense of what the data actually shows. We also have different behaviour between a query run right now, and running it later at that timestamp.

The current behaviour is not a safe default, and it's not clear to me that it should even be an offered feature.

**Comment by robey** [comment]
I like this. I find the interpolated values very misleading, since our services only report integer counts for things like "messages delivered". The float values look like a bug.

**Comment by grobie** [comment]
So I def. see the need for executing expressions without interpolations and have run into issues with interpolations more than once on my own.
On the other hand, we have hundreds of dashboards and checks with the current behavior. So before simply dropping the interpolation altogether, @fabxc @juliusv I'd like us to run a test server(s) with this proposed change and see if we actually depend on the interpolation anywhere. For example, I'm curious on how aggregation functions like `avg()` will behave on jobs which get rarely scraped.

**Comment by brian-brazil** [comment]
Something else that occurs to me is that interpolation can lead to spurious counter resets, if a timestamp landed between a reset and the previous sample.

**Comment by brian-brazil** [comment]
@grobie Has your testing revealed any problems we should be aware of, or can this be merged?

**Comment by fabxc** [comment]
@brian-brazil are we completely going to ignore the issue that some people might want interpolation? Any comments on the aggregation problem?

**Comment by juliusv** [comment]
I want to give this some more testing and thought today. Not sure if we should just completely get rid of interpolation. Don't get me wrong, I really like having the option of no interpolation, but I want it to be thought through better.

**Comment by brian-brazil** [comment]
> are we completely going to ignore the issue that some people might want interpolation?

The main visible effect will be in graphs, and the same effect can be obtained by smoothing in the graphing library.

> Any comments on the aggregation problem?

If you're using pre-computed rules, then this doesn't change the behaviour. If you're using graphs then you're going to get different results depending on when you view the graph. That doesn't sound like the sort of behaviour we want to have, as retroactively changing the results of some expressions in some contexts is going to cause surprises (and bugs).

There is no general solution to how to deal with aggregation of samples with different timestamps, as each type of metric needs custom handling (e.g. gauge vs. counter vs. linear vs. exponential vs. cyclic vs. bool vs. quantile). We know that what we currently have is broken in some of these cases, so we'd need to design something sufficiently generic to be able to handle all these and only use past data so that it maintains the invariant that results don't retroactively change. I'm not sure it's practical to create such a thing.

The answers the current code produces are inaccurate, the answers after this PR are still inaccurate but more predictable and less surprising.

**Comment by juliusv** [comment]
Yeah, I can see good arguments both ways.

As one experiment, I ran parallel Prometheus servers with and without interpolation at a 2m scrape interval and then compared their results to a reference Prometheus that scraped every 5s (so doesn't really matter if that third one has interpolation or not because the samples are so close, but it gives an accurate representation of what the correct sample values would have been in reality at interpolated times). Results for memory usage graphs look like this (the reference one is in the middle for easier comparisons):

120s scraping, with interpolation:
120s_interpolated

5s scraping, no interpolation (but shouldn't matter much)
5s_noninterpolated

120s scraping, no interpolation:
120s_noninterpolated

Obviously the interpolated one is closer to the truth than the non-interpolated one here. That won't be true for all use cases, but at least it makes me think that there could be value in keeping interpolation as an option. In graphs like the above, the beginning of an event like a memory spike will be showed closer to the true beginning with interpolation than if output samples are based only on samples collected *before* the respective evaluation timestamp, not the ones after (especially if the last sample is maybe 1m55s old, while the future one is 5s into the future from the evaluation timestamp).

**Comment by fabxc** [comment]
Isn't that something where interpolation can be applied at the UI level?
This makes enabling/disabling a lot easier.

Aggregation is what interests me mostly. There, the lack of interpolation at evaluation time actually affects the restorable output.

**Comment by juliusv** [comment]
@fabxc The UI can only work with data it gets. In this case, we're throwing away information on the server side already. Consider the case where we only look at the sample 1m55s in the past, and not the one 5s in the future - which one is going to be a more accurate representation of the truth? If we're only basing it on a potentially far away sample, the UI can't really help us improve it anymore.

**Comment by fabxc** [comment]
Ah right, I forgot that we were picking the closest one.

**Comment by juliusv** [comment]
That could be improved somewhat by choosing the closest one even without interpolation, but that'd go against @brian-brazil's desire to not use available information after the evaluation timestamp, and still doesn't lead to as accurate results as interpolating a sample somewhere in the middle (yeah I know that for some use cases that doesn't work, but in the RAM case it seems to make sense).

**Comment by brian-brazil** [comment]
> Consider the case where we only look at the sample 1m55s in the past, and not the one 5s in the future - which one is going to be a more accurate representation of the truth? If we're only basing it on a potentially far away sample, the UI can't really help us improve it anymore.

In that case the user has the option of taking an `avg_over_time()`

The graph output is pretty much what I expected. We'll want to add a few more plotting modes in the future to make the data (and gaps) more obvious.

**Comment by juliusv** [comment]
`avg_over_time()` wouldn't include future values though, so it wouldn't address that case at all? And that'd be quite an "insider" thing for the user to know if we can do a better job by default. If we don't want to interpolate, we should at least think about choosing the closest sample, even if it's in the future, since that *will* be the more accurate graph in case that sample is much closer than the past sample.

**Comment by brian-brazil** [comment]
> avg_over_time() wouldn't include future values though, so it wouldn't address that case at all?

`avg_over_time()` is relative to the "middle" of the range, so you get the same result if you shift the end of the graph forward a bit.

> If we don't want to interpolate, we should at least think about choosing the closest sample, even if it's in the future, since that will be the more accurate graph in case that sample is much closer than the past sample.

That's non-deterministic, so something we should avoid. It's also not more accurate in all use cases.

**Comment by juliusv** [comment]
In typical range/graph queries, the nondeterminism would only affect the very right edge of the graph, but there you can also get non-determinism if you only use samples in the past. If your evaluation timestamp is after the last sample, you could still get a new sample that is between the two when running the query again, and your results will change then too. For graphs that aren't anchored to *now*, but sometime in the past, there's no effect on determinism.

**Comment by brian-brazil** [comment]
> In typical range/graph queries, the nondeterminism would only affect the very right edge of the graph, but there you can also get non-determinism if you only use samples in the past.

It affects all points in the graph, as you're potentially getting a different result than if you'd run that query earlier.

> If your evaluation timestamp is after the last sample, you could still get a new sample that is between the two when running the query again, and your results will change then too.

This is possible, though much less likely in practice.

**Comment by juliusv** [comment]
How would it affect all points in the graph in terms of non-determinism? There's never going to be any new data inserted in the middle of the graph, only at the right edge...

**Comment by brian-brazil** [comment]
> How would it affect all points in the graph in terms of non-determinism?

All points in the graph were the right edge at some point. This PR also goes beyond graphs, it affects all places where evaluation occurs such as console templates, alerts and rules.

**Comment by juliusv** [comment]
I don't see the problem with that beyond some special cases in rules. In a graph, I want to get the most accurate representation of the truth based on the time series samples I have at the time I display the graph. If I need to align data points for graph stacking or aggregations, linear interpolation between the two neighboring data points is my best bet if I don't want to get way more sophisticated. You could argue that if a linear interpolation doesn't work well due to erratic time series, you should configure a higher sampling (scraping) frequency because otherwise you're going to miss all the erraticness anyways.

Now, I do see that people can get confused by interpolation returning values that the raw samples can never have, like `up` being `0.324`. But that wouldn't happen if we dropped linear interpolation, but simply chose the closest sample to our target time, which still gives us a better approximation of the truth.

Would a special-casing of rule evaluation make sense for this?

**Comment by brian-brazil** [comment]
> I don't see the problem with that beyond some special cases in rules.

The problem goes beyond rules as any time we report anything we interpolated we risk the user making an incorrect judgement based on things that may not actually be in the data.

> I want to get the most accurate representation of the truth based on the time series samples I have at the time I display the graph. 

I too want the truth, which is the raw data. Interpolation is a guess at the truth.

> linear interpolation between the two neighboring data points is my best bet if I don't want to get way more sophisticated.

That doesn't cover the general case, only a very specific case (and memory isn't a case it handles - it only works for time series that are a perfectly straight line in perpetuity, and even then there's still corner cases with problems). Any interpolation that's not opted-in to by the user with understanding of what's going on is unsafe - which incidentally is also part of why we need to change how rate/delta/increase work.

> You could argue that if a linear interpolation doesn't work well due to erratic time series, you should configure a higher sampling (scraping) frequency because otherwise you're going to miss all the erraticness anyways.

There's the same race conditions and potential problems with any scrape or eval interval.

> But that wouldn't happen if we dropped linear interpolation, but simply chose the closest sample to our target time, which still gives us a better approximation of the truth.

That would be a pain for debugging, and would also make certain advanced use cases impossible as you can't request the sample before a given time.

> Would a special-casing of rule evaluation make sense for this?

This needs to be removed everywhere. Rule evaluation and query_range are just the more obvious places where there's breakage, but the graphs are also broken due to reporting of impossible and incorrect data. Predictability and a computational model you can reason about and build upon are more important than slightly nicer looking graphs.

I had thought that this only affected graphs based on conversations several months back, had I realised it affected everything this PR would have come back then as I consider this a very severe limitation on the potential of Prometheus.

**Comment by brian-brazil** [comment]
It also occurs to me that this is why I've seen impossible values for `sum(up{job="job"})` in console templates, which I'd never managed to figure out as I thought there was no interpolation on that code path.

**Comment by juliusv** [comment]
I talked some more with Brian. While for general graphs I still think you often want the closest rather than last sample, I agree there are also use cases where you never want to see a value change before it has actually changed in reality. Since the real-world differences in graphs will be pretty small, I'm fine with changing the sample selection to work as in this PR for now. If we want, we can still add optional other behavior later.

If we want to go this route of only choosing the last sample, we could theoretically change things all the way into the storage layer, where we currently get both the sample before and after some target time (in `it.ValueAtTime(...)`. We could now only return a single sample. But maybe let's keep that functionality in the storage layer for a while to see if we really won't use it anymore, and only simplify the query layer for now. There, we can also just assume that the samples returned from `it.ValueAtTime` will be at most two, and sorted by timestamp, and only the first timestamp would be before the target time. So we can just check if the returned slice has at least one sample, and then only look at the first one, and check if that is within staleness bounds. Could maybe look a tiny bit simpler than the current `chooseClosestBefore()` code here.

**Comment by brian-brazil** [comment]
> and check if that is within staleness bounds

I noticed that logic, we'll likely need to make that configurable somehow as #398 only handles evaluation cycles.

**Comment by juliusv** [comment]
@brian-brazil Ok, but for this PR, the `chooseClosestBefore()` code can be simplified a bit still, given that we know the first sample in the returned slice is the one we want, unless if it's outside staleness.

**Comment by brian-brazil** [comment]
> given that we know the first sample in the returned slice is the one we want

That's not guaranteed by the ValueAtTime interface, and it's not completely clear what each of the implementations do.

**Comment by juliusv** [comment]
@brian-brazil Ah yeah, if there's only a value after the target timestamp and none before, there's only going to be one sample and we want to ignore that.

Though at least one could terminate the `range` on the first found candidate, because there can't be two eligible samples anymore.

**Comment by brian-brazil** [comment]
Updated.

**Comment by brian-brazil** [comment]
Are there any other changes required before merging this?

**Comment by juliusv** [comment]
Nope, all good. :+1:

**Pull request merged**
