### PR TITLE
Fix missing 'msg' in remote storage adapter main.go .Log info message

### PR DESCRIPTION
**Pull request by silentpete**
Signed-off-by: silentpete <peter.gallerani@gmail.com>
@juliusv

### CODE REVIEW

**Comment by juliusv** [comment]
@silentpete Sorry, only saw this now. Why did you close this by the way? Seems like a valid fix.

**Comment by silentpete** [comment]
@juliusv, sorry, my request wasn't passing the DCO and I couldn't figure out why it is coming up "unknown". I was going to build my own repository, implement DCO to figure it out, then resubmit. I'm new to this FOSS contributor... 
BTW, have fun at PromCon, that's awesome!

**Comment by juliusv** [comment]
@silentpete No worries - do you want to try again / reopen? Then we can figure out if there is still a DCO problem.

**Comment by silentpete** [comment]
@juliusv sure. I'll have to re-fork and create a new pull request, correct?

**Comment by juliusv** [comment]
@silentpete Sorry for the late reply. You won't have to create a new fork, but you can open a new pull request with a commit that has the right DCO signoff (if it still doesn't work then, we can take a look why not).

**Comment by silentpete** [comment]
Cool, the new pull request is there, and it looks like it passed DCO. I
think it is something with the profiles in GitKraken...

**Pull request closed without merging**
