### PR TITLE
Add support for interpolating target_label

### PR DESCRIPTION
**Pull request by Nomon**
Adds support for interpolating regexp match group names in target_label variable in relabel replace action.

ref: #1099 

Why:

We currently schedule service and batch jobs using nomad scheduler (nomadproject.io), the scheduler registers jobs to consul as services. We would like to expose some details of the nomad scheduling as labels via consul tags and would like freedom to map data from the service tags to arbitrary labels resolved from the tags, so that prometheus reconfiguration is not necessary when introducing new target_labels.

A perhaps better solution to our problem would be to implement nomad discovery instead and expose the jobs metadata as labels instead but I feel that this feature adds to the power of relabeling even on its own.

Below are example prometheus config and nomad job that illustrate what can be done with this PR. It propagates nomad jobs allocation name  (ie. "example-service.api[0]") and version of the running service via consul tags to 'job' and 'version' labels.

```yaml
scrape_configs:
  - job_name: "overwritten-default"
    consul_sd_configs:
    - server:   '127.0.0.1:8500'
    relabel_configs:
    # only scrape services with prometheus tag 
    - source_labels: ['__meta_consul_tags']
      regex:         '(?:^|.+,)prometheus,?.*'
      action:        keep

    # .. set instance and job from consul __meta

    # map any label:k=v tags to labels
    - source_labels: ['__meta_consul_tags']
      regex:         '(?:.+,|^)label:([^=]+)=([^,]+).*'
      target_label: '${1}'
      replacement:  '${2}'
```

```hcl
job "example-service" {
  group "api" {
    count = 5
    task "http" {
      driver = "docker"
      service {
        name = "example"
        port = "http"
        tags = [
          "prometheus",
           # add some prometheus labels.
          "label:version=bdaf0ec6a2210ac93e0addc7b67d524ce5e1c182",
          "label:job=${NOMAD_ALLOC_NAME}"
        ]
      }
      config {
        image = "registry/image:bdaf0ec6a2210ac93e0addc7b67d524ce5e1c182"
      }
      resources {
        network {
          port "http" { }
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by matthiasr** [comment]
Is this not possible by using `action: labelmap`?

**Comment by Nomon** [comment]
nope, labelmap can only change the name of existing label keys. There are currently no way to create new labels from existing label values.

**Comment by beorn7** [comment]
And, as far as I understand, the latter is needed for Consul SD, which has no labels, just "tags".

**Comment by beorn7** [comment]
@brian-brazil Does this look like the right approach to me? I can review the code, but I want to make sure we have consensus it is implementing what we want.

**Comment by brian-brazil** [comment]
We'd discussed in this in #1099 and I'm for this change.

**Comment by beorn7** [comment]
:+1:

**Comment by Nomon** [comment]
oh crap, I just tested this feature with an actual config and prometheus refuses to start due to invalid label (does not match the LabelNameRE). Sorry for the trouble, I will make a fix for it as a new PR.

**Pull request merged**
