### PR TITLE
pkg/textparse: allow null bytes in label values

### LINKED ISSUE #2751: Prom2: "no token found" on scrape
**What did you do?**
Set up monitoring side-by side between Prom2 and Prom1.

**What did you expect to see?**
The same data.

**What did you see instead? Under which circumstances?**
Some scrape targets report `no token found`
```
2017-05-22T08:14:07.683853000Z time="2017-05-22T08:14:07Z" level=error msg="append failed" err="no token found" source="scrape.go:483" 
```

image

### PR DESCRIPTION
**Pull request by fabxc**
@mwitkow @beorn7 @brian-brazil 

Fixes #2751

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why does the character class not cover this already?

**Comment by fabxc** [comment]
There is no character class being used for label values.
Character classes are for restricted alphanum fields like metric name and label names. For label values we have to basically allow everything but consider `"` escaping.

**Comment by brian-brazil** [comment]
`[^\\']` is a regular expression character class, meaning anything except backslash or double quote.

Why isn't that already matching nulls?

**Comment by fabxc** [comment]
Ah, that's what you mean – to be honest. No idea. But it seems that the lexer treats null bytes specially?

**Comment by brian-brazil** [comment]
:+1: 

Well if it works...

**Pull request merged**
