### PR TITLE
Update fsnotify to v1.4.7

### PR DESCRIPTION
**Pull request by jefferyto**
fsnotify v1.3.1 uses `unix.InotifyInit()` which is not available on mips64/mips64le. Updating to a newer version allows builds to succeed on these platforms.

Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by jefferyto** [comment]
Related issues:
* #5689
* openwrt/packages#9494 (openwrt/packages#9543)

The actual change in fsnotify: fsnotify/fsnotify#178 (released in [v1.4.2](https://github.com/fsnotify/fsnotify/blob/master/CHANGELOG.md#v142--2016-10-10))

**Comment by simonpasquier** [comment]
Could you uncomment the mips targets in [`.promu.yml`](https://github.com/prometheus/prometheus/blob/fb2b3c2b0b9a69f70b867a6efeb20058701ca88c/.promu.yml#L46-L49) too?

**Comment by jefferyto** [comment]
@simonpasquier Sure :smile: it's updated

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
