### PR TITLE
Make ISSUE_TEMPLATE.md usage question notice bold

### PR DESCRIPTION
**Pull request by juliusv**
We still get way too many usage questions in issues, maybe bold and command tone works better.

### CODE REVIEW

**Comment by grobie** [comment]
That new issue template was only put in place yesterday. Give it some time?

**Comment by juliusv** [comment]
Oh, didn't notice! Ok, I'll let this sit here for a while, but I'm betting that the bolder version will be at least slightly more successful.

**Comment by grobie** [comment]
There will always be people ignoring such guidelines. I vote to be polite
to the majority.

**Comment by juliusv** [comment]
Meh, sigh. I guess we'll need to create an AI which auto-closes the onslaught of questions recently :(

But let's see how things develop with the current text. Closing for now then.

**Comment by grobie** [comment]
I'm fine reworking the issue template if it still doesn't work with that
new sentence at the top.

**Pull request closed without merging**
