### PR TITLE
Mark remote write address flag as experimental.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by RichiH** [comment]
This patch is well within my Go skillset.

+1

**Comment by fabxc** [comment]
I feel like this needs to be "EXPERIMENTAL - DO NOT USE IN PRODUCTION". Better safe than sorry  :)

**Comment by juliusv** [comment]
@fabxc To see if the big "EXPERIMENTAL" marking is compatible with his taste :)

**Comment by juliusv** [comment]
Ah, my GH page didn't update, didn't see your comment. Will add the big one.

**Comment by juliusv** [comment]
Leaving it as it is, as discussed on IRC :)

**Pull request merged**
