### PR TITLE
Support basic_auth in marathon_sd_config.  Closes #3090

### LINKED ISSUE #3090: basic_auth support in marathon_sd_config
**What did you do?**
Well, trying to configure Marathon monitoring in Prometheus. Marathon does not support built in authentication, so obviously someone has to use basic_auth to protect Marathon/Mesos. We did the same. 

**What did you expect to see?**
There is already a way to support basic auth for other modules, then why shouldn't we implement that for marathon_sd_config? Copy/Past stuff!! :)

* Prometheus version: 

	prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
  build user:       root@0aa1b7fc430d
  build date:       20170612-11:44:05
  go version:       go1.8.3

### PR DESCRIPTION
**Pull request by mciura**

### CODE REVIEW

**Comment by mciura** [comment]
Pinging @brian-brazil as service discovery is his focus area.

**Comment by mciura** [comment]
Pinging also @fabxc as service discovery is his focus area.

**Comment by krasi-georgiev** [comment]
@brian-brazil looks like a dupe of https://github.com/prometheus/prometheus/pull/1745

**Comment by brian-brazil** [comment]
As per the other PR, this should use HTTPClientConfig rather than doing it's own thing auth wise.

**Pull request closed without merging**
