### PR TITLE
release: Volunteering for 2.18 release.

### PR DESCRIPTION
**Pull request by bwplotka**
:wave: 

I am happy to do next release. This is because we spent a lot time recent weeks in query optimizations on Prometheus, Thanos, and Cortex, so 2.18 release might have significant changes like:

* Chunk Iterators finally :heart: 
* @pstibrany and @pracucci major optimizations to postings
* Potentially https://github.com/prometheus/prometheus/issues/6878 with @mkabischev help. 

I know I was a release Shephard just in December, but given that I have full context for those I feel like I can help in releasing 2.18 a lot.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by bwplotka** [comment]
Looks like master is broken again, fixing now

**Comment by bwplotka** [comment]
Something is really broken: Test failed for some old code: https://circleci.com/gh/prometheus/prometheus/28861 This test no longer exists on this branch 0.o some cache somewhere?

**Comment by bwplotka** [comment]
This is scary not because of flakinesses like this, rather the opposite. If CI is running against random code, it can pass for broken code :/

**Comment by bwplotka** [comment]
Tests pass locally.

Somehow does not for CI for non existing code:
```
=== RUN   TestFanoutErrors
--- FAIL: TestFanoutErrors (0.02s)
    fanout_test.go:135: 
        
        exp: &errors.errorString{s:"select error"}
        
        got: <nil>
FAIL
FAIL	github.com/prometheus/prometheus/storage/fanout	0.138s
```

:thinking: cc @simonpasquier any ideas?

**Comment by simonpasquier** [comment]
@bwplotka hmm I've got the failure locally.

**Comment by bwplotka** [comment]
How @simonpasquier ? 

Do you have this test? Also looks like master CI is broken as well.

**Comment by bwplotka** [comment]
Ok, looks like just some test was added in between of merges. Fixed on master now.

**Comment by bwplotka** [comment]
Merging as docs are fine.

**Pull request merged**
