### PR TITLE
Scraping: Optionally use xxhash for series cache keys

### PR DESCRIPTION
**Pull request by bboreham**
This is #12993 re-done with xxhash.

The scrape cache is per target (as @rfratto pointed out to me), so the number of items is generally hundreds or thousands, and the chance of a hash collision with 64-bit hash is low.

By "birthday problem" math, with 190,000 metrics the risk of collision is about one in a billion.

I haven't benchmarked it yet to find the CPU overhead difference.

### CODE REVIEW

**Comment by beorn7** [comment]
But how "stochastic" is xxhash? Small correlated changes might lead to a hash collision with a much higher probability than expected from stochastic distribution of hash values. (Maybe xxhash is really much better than fnv64a, but the fnv64a collisions we ran into were really those where two characters changed in very different parts of a string but managed to even each other out in the hash calculation, and those kind of changes were pretty likely to occur.)

**Comment by bboreham** [comment]
Peter investigated empirically: https://github.com/pstibrany/labels_hash_collisions

**Comment by bboreham** [comment]
I guess we're not going to go ahead with this, so closing.

**Comment by ethercrow** [comment]
Hello together,

After seeing one of the deployments of OpenTelemetry Collector (that includes a prometheus receiver) to retain a lot of memory allocated in `addDropped` function I found this PR and ported this patch to our internal collector build.

Here is the memory chart before and after the patch:

Screenshot 2025-01-23 at 09 45 38

I encourage you to reopen this PR and include it upstream to share this memory improvement with all users.

**Pull request closed without merging**
