### PR TITLE
Cut v1.2.2

### PR DESCRIPTION
**Pull request by beorn7**
This includes cherry-picking a few commits from master that should have gone to the release-1.2 branch and also a major update of vendoring.

Since v1.3 will be breaking for K8s SD users, I want to have all the bug fixes in this release so that nobody has to go to v1.3 just to get rid of bugs.

Rationale for the vendoring update:

- Some packages were plainly missing.
- Some packages have bug fixes upstream that are suspected to have caused reported Prometheus bugs.
- Some packages have data races fixed upstream, which can explain almost any weird behavior within Prometheus.
- Some packages are just so far behind that any reported issue in their area would be a suspect for "already fixed upstream".

### CODE REVIEW

**Comment by beorn7** [comment]
@fabxc as promised.

**Comment by beorn7** [comment]
@fabxc Ping?
Or @brian-brazil @juliusv ?

Let me know if you find the vendoring update too daunting. (We could have a rc or something if you think that's necessary. I just think we should really update the vendoring, where we are way behind and there are a number of bug fixes and enhancements upstream.)

**Comment by fabxc** [comment]
👍

**Comment by beorn7** [comment]
Before tagging and building, I'd like to update promu to Go 1.7.3 (more potential bug sources eliminated there).

**Comment by beorn7** [comment]
There is a problem with the new miekg/dns package. Will follow up...

**Pull request merged**
