### PR TITLE
Fix binary detection in Makefile

### PR DESCRIPTION
**Pull request by linuxgcc**

### CODE REVIEW

**Comment by linuxgcc** [comment]
https://github.com/prometheus/alertmanager/issues/3624

**Comment by linuxgcc** [comment]
@dgl  Please check if it is ok

**Comment by beorn7** [comment]
Thanks for fixing the yaml lint issues. However, this is now conflating an actual change in the Makefile and lint fixes in one and the same commit.

@simonpasquier any reason why https://github.com/prometheus/prometheus/pull/13377 is still a draft?

In any case, @simonpasquier and @SuperQ should review the actual Makefile changes.
Lint cleanups are great, but they should happen in a separate commit (or even PR, if you don't want to wait for the actual changes to get reviewed).

And generally, our apologies for taking so long to review PRs.

**Review by SuperQ — APPROVED** [review]
Great, thanks!

**Pull request merged**
