### PR TITLE
Add Unknown state for alerts on alerts page

### LINKED ISSUE #4510: Distinguish not+yet-evaluated alert from empty alert
Like we do for targets (UNKNOWN) I'd like to see alerts that have mnot yet been evaluated (after a restart or  new alerts) marked as unknown.

ne

### PR DESCRIPTION
**Pull request by pradeepgangwar**
I followed this from existing PR which looked fine to me. Please let me know if this requires any additional changes.

Closes #4510

### CODE REVIEW

**Comment by pradeepgangwar** [comment]
I tried generating an alert for unknown state to test this out but could not do so. Can anybody help me how to generate an alert with `unknown` state. I have this project fully setup on my local machine and I can see one `Inactive` alert after I adding one alert rule in alert config file.

**Comment by roidelapluie** [comment]
Just add `interval: 9999s`

**Comment by roidelapluie** [comment]
mmh, I would disagree that it closes #4510, could you try to set that up for the new UI instead?

**Comment by pradeepgangwar** [comment]
@roidelapluie I am new to this project and haven't explored much. I am not sure what do you mean by new UI 😅 . Can you help me here please?

**Comment by roidelapluie** [comment]
> @roidelapluie I am new to this project and haven't explored much. I am not sure what do you mean by new UI sweat_smile . Can you help me here please?

Prometheus as two UI: a classic one:

https://prometheus.demo.do.prometheus.io/graph

and a new one:

https://prometheus.demo.do.prometheus.io/new/graph?g0.expr=&g0.tab=1&g0.stacked=0&g0.range_input=1h

The new one is in `web/ui/react-app/`. see `web/ui/react-app/README.md` for intro.

**Comment by roidelapluie** [comment]
cc @juliusv

**Comment by juliusv** [comment]
For reference, @roidelapluie already took a shot at this (and more) for the new React UI in https://github.com/prometheus/prometheus/pull/6487, but closed it again for now. But I think that first attempt wasn't so bad, just the comments I made would be good to address / think about.

**Comment by pradeepgangwar** [comment]
I have worked with react.js but don't have prior experience with typescript. I will go through the code & update my PR soon. Allow me to take some time. 😅

**Comment by pradeepgangwar** [comment]
@juliusv @roidelapluie I tried adding unknown state for new UI. Pls take a look and let me know if it needs further changes.

Screenshot 2020-03-07 at 12 41 28 AM

**Comment by gouthamve** [comment]
@juliusv Could you take a look at this?

**Comment by roidelapluie** [comment]
last call @juliusv from the bug scrub, can you please have a look at this? thanks!

**Comment by bwplotka** [comment]
Hello from Bug Scrub!

Looks like we still need to review this (cc @juliusv), perhaps @Nexucis you would like to check this out too? Thanks!

**Comment by beorn7** [comment]
@juliusv @Nexucis once more ping from the bug scrub.

**Comment by bboreham** [comment]
Came back around at the bug-scrub; given no updates after multiple pings we will close this.
Thanks for your interest, and feel free to re-open if you do come back to it.
(Given major changes in the UI, it would probably need a fresh implementation)

**Pull request closed without merging**
