### PR TITLE
switch to go 1.14

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
@simonpasquier any idea why we don't have yarn here?

**Comment by simonpasquier** [comment]
It was an oversight when reviewing https://github.com/prometheus/golang-builder/pull/78. Because `yarn` wasn't added to the 1.12 image, it was missing when we switched to 1.14 from 1.12...

https://github.com/prometheus/golang-builder/pull/87 should fix it.

**Comment by roidelapluie** [comment]
it is green. should we run prombench?

**Comment by roidelapluie** [comment]
Prombench looked really good.

**Comment by geekodour** [comment]
@roidelapluie prombench usually breaks when there is a go version bump, o.O I think prombench built prometheus with 1.13 when you ran it.

**Pull request merged**
