### PR TITLE
Update vendoring for 2.25 release

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Review by beorn7 — APPROVED** [review]
Once the build succeeds…

**Comment by beorn7** [comment]
Which it has by now.

**Comment by SuperQ** [comment]
Did we want to try and figure out how to get https://github.com/prometheus/prometheus/pull/8029 to pass CI tests?

**Comment by beorn7** [comment]
That would be cool. (But I wouldn't delay the release for it.)

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by beorn7** [comment]
It still looks quite red. :crying_cat_face:

**Comment by roidelapluie** [comment]
It is green

**Review by beorn7 — APPROVED** [review]

**Comment by beorn7** [comment]
Largest delta ever!

**Review by SuperQ — APPROVED** [review]
LGTM! :tada:

**Pull request merged**
