### PR TITLE
Add fuzzy search to /graph textarea

### PR DESCRIPTION
**Pull request by lightpriest**
We have a few thousands different metrics and looking up some of them
can be quite annoying with the simple string matching.

This patch adds a fuzzy search to the textarea lookup box on the /graph
page. It uses a small neat library from github.com/mattyork/fuzzy.

I tried to make this PR as unobtrusive as possible to the current graph.js code.
Also included the license of the bundled fuzzy search lib.

### CODE REVIEW

**Comment by juliusv** [comment]
Thanks! To me, the fuzzy search seems to behave nicely. I haven't tried with thousands of metrics, but since that seems to be your use case, I take that that's behaving fine for you?

Could you also:

- run `make assets` to rebuild the compiled-in web assets file
- add a snippet to the `NOTICE` file about the new JS library

**Comment by lightpriest** [comment]
I'm biased, but the other users of Prometheus here seem to be satisfied, so I guess it's working as expected :)

I actually built the assets previously, but now noticed that the FileMode is different. Re-ran it with correct FileMode.

**Comment by fabxc** [comment]
That seems to work nicely and fixes one major annoying issue.

👍  

Hopefully we can extend this at some point to auto-complete beyond the initial metric.

**Comment by beorn7** [comment]
FTR: The issue that reports the history of our auto-complete efforts is https://github.com/prometheus/prometheus/issues/1924 . Help is welcome.

**Pull request merged**
