### PR TITLE
Update vendoring for Azure

### LINKED ISSUE #2152: Missing vendored info
Hi,

A small bug, you have forgotten to include vendoring information (in vendor.json) about the azure-related libraries. They have been releasing very often lately, and I noticed this bug when I wanted to check which version you are tracking.

### PR DESCRIPTION
**Pull request by beorn7**
Also, actually record the vendored version in vendor.json.

@TheTincho Fixes #2152 
@iamseth Does that look sane to you?

### CODE REVIEW

**Comment by TheTincho** [comment]
JWT had an API change, I am surprised the tests are not failing...

**Comment by beorn7** [comment]
I also had to update go-jwt to make it compile... but the test coverage for Azure might not be so good. That's why I want to hear from @iamseth.

**Comment by beorn7** [comment]
@iamseth any chance you can have a look at this?

**Comment by beorn7** [comment]
Does anybody know who would be qualified for Azure SD if @iamseth is not available?

If there is nobody maintaining it, we either need to find one or kick it out.

**Comment by rjtsdl** [comment]
@beorn7 
I am looking into this per Rob's request.

I built from source of your branch.
From user's point of view, i feed a valid config.yml for azureSDConfig, and removed all the other scrape jobs. From the expression browser, i can clearly see all my VMs with correct metadata. 

I thought, it already proved Azure SD is correctly working. Do you have more concern ?

**Comment by beorn7** [comment]
@rjtsdl Sorry for the delay, had a long vacation weekend.

If everything builds as expected building from this branch, that's good news.

@TheTincho could you explain in more detail where you expected problems? Build and tests work fine for me, and @rjtsdl cannot see any problems trying it out for real.

**Comment by beorn7** [comment]
I have rebased on top of the current master.
Still all tests work fine for me.
@TheTincho waiting for your concerns. Otherwise, I guess this is good for merge.

**Comment by TheTincho** [comment]
Sadly, I can't find what was the issue I've found at that time. I think it was either build or test failure in prometheus after upgading jwt and autorest, but I don't have the logs. If prometheus tests are passing without any code changes, then I guess my failures were unrelated. Sorry about the noise.

**Comment by beorn7** [comment]
OK, let's merge. @rjtsdl if you notice any issues, please let me know.

**Pull request merged**
