### PR TITLE
Switch to Go modules

### PR DESCRIPTION
**Pull request by simonpasquier**
Replacing `govendor` by `go mod ...` commands wasn't much involved. Most of the work was making sure that the updated `Makefile.common` works well for other Prometheus projects and libraries (I tested with AlertManager, prometheus/tsdb and prometheus/client_golang) before and after they switch to Go modules as well as with Go < 1.11.

~~The PR is based on https://github.com/prometheus/prometheus/pull/4781 (that would need to be merged first) and definitely needs more polishing (like updating `CONTRIBUTING.md`) but at least it should be working.~~ It doesn't remove the `vendor/` directory as vendoring is still supported by Go modules and from previous discussion in https://github.com/prometheus/alertmanager/pull/1583, we want to keep dependencies in tree.

cc @stuartnelson3 @brancz @krasi-georgiev @brian-brazil

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
I am unable to compile it

`build github.com/prometheus/prometheus/cmd/prometheus: cannot find module for path github.com/Azure/azure-sdk-for-go/arm/compute`

tried few suggestions but at end I gave up. I think something to do with the mod cache. but even after `go clean -modcache` still the same

It works when trying of master which  converts the existing vendor.json
but than stopping Prometheus when built with modules takes a while longer than usual.

gets stuck at:
`level=info ts=2018-10-29T17:54:37.936464124Z caller=main.go:616 msg="Notifier manager stopped"`

**Comment by stuartnelson3** [comment]
Just ran it once and didn't try to debug anything, build failed:

```
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/goc
/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in
go: error loading module requirements

make: *** [Makefile.common:117: common-staticcheck] Error 1
```

**Comment by simonpasquier** [comment]
@stuartnelson3 right, I've encountered this situation too. You'd need `bzr` to be installed on your machine because `github.com/hashicorp/consul/api` depends (indirectly) on `launchpad.net/gocheck` which itself is hosted on Bazaar.

**Comment by stuartnelson3** [comment]
Hm, can this somehow easily be handled within the makefile? at least informing the user 'hey this binary is missing / not in your path'

**Comment by stuartnelson3** [comment]
After adding `bzr` it built without issue

**Comment by simonpasquier** [comment]
> Hm, can this somehow easily be handled within the makefile? at least informing the user 'hey this binary is missing / not in your path'

Definitely.

**Comment by sipian** [comment]
@simonpasquier 
What's the update on this PR? If needed, I would like to be of assistance to get this in. 
The updated `Makefile.common` will be quite useful in adding CI to prombench repo https://github.com/prometheus/prombench/pull/161

**Comment by simonpasquier** [comment]
@sipian the PR needs review and approval but I hope it will be closed soon.

**Comment by stuartnelson3** [comment]
Not up to me to approve, but it's working from my machine.

**Comment by krasi-georgiev** [comment]
before merging can you please make sure that this works even without the make file  

```
GO111MODULE=on go run cmd/prometheus/main.go 
// from $GOPATH/src/github.com/prometheus/prometheus
```

@stuartnelson3 	did you run it using the makefile?

**Comment by stuartnelson3** [comment]
I did use the makefile. Can't get the patch to apply correctly right now to check a bare `go run`, though.

**Comment by simonpasquier** [comment]
@krasi-georgiev I have success with `go run -mod=vendor cmd/prometheus/main.go` (code outside of GOPATH) and `GO111MODULE=on go run -mod=vendor cmd/prometheus/main.go` (code inside GOPATH). The key point is `-mod=vendor` to force using the vendored dependencies.

**Comment by stuartnelson3** [comment]
I've had to do this with other projects -.-

**Comment by simonpasquier** [comment]
Can we move forward with this PR? AFAICT it works fine for those that have tested it locally and the CI is green.

**Comment by brancz** [comment]
Works fine for me. Let's move forward with this :+1:

**Comment by Alger7w** [comment]
I met a problem after I started to use go modules, anyone has seen this ? 

GO111MODULE=on go run cmd/prometheus/main.go
go: finding labix.org/v2/mgo v0.0.0-20140701140051-000000000287
go: labix.org/v2/mgo@v0.0.0-20140701140051-000000000287: bzr pull --overwrite-tags in /xxxx/pkg/mod/cache/vcs/ca61c737a32b1e09a0919e15375f9c2b6aa09860cc097f1333b3c3d29e040ea8: exit status 3:
        bzr: ERROR: Not a branch: "/xxxx/pkg/mod/cache/vcs/ca61c737a32b1e09a0919e15375f9c2b6aa09860cc097f1333b3c3d29e040ea8/.bzr/branch/": location is a repository.
go: error loading module requirements

**Comment by simonpasquier** [comment]
@Alger7 not sure what is happening but if you add `-mod=vendor`, it should at least not try to download stuff:

> GO111MODULE=on go run -mod=vendor cmd/prometheus/main.go

**Pull request merged**
