### PR TITLE
*: enable default all linters

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by SuperQ** [comment]
I take it `cmd/promtool/http.go` is un-used code?

**Comment by SuperQ** [comment]
Can we add some more comments about the errorcheck excludes? Is it just noise? Or a TODO list?

**Comment by simonpasquier** [comment]
> I take it cmd/promtool/http.go is un-used code?

Yes though it wasn't automatically detected by the tool as it was referenced in `cmd/promtool/http_test.go`.

**Comment by simonpasquier** [comment]
The job fails randomly on Circle CI. I suspect that it consumes too many RAM, I'll dig further...

```
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /go/bin/golangci-lint run ./...
Killed
Makefile.common:164: recipe for target 'common-lint' failed
```

**Comment by simonpasquier** [comment]
Sigh, decreasing the job concurrency didn't reduce memory...

**Comment by tariq1890** [comment]
Can this be merged?

**Comment by simonpasquier** [comment]
Merging now. FTR I've decreased the `GOGC` value for the Circle CI job and it _seems_ to be ok (eg not hitting the 4GB RAM limit anymore). If it isn't sufficient in the long run, we'd have to disable the `lint` target for Circle CI.

**Pull request merged**
