### PR TITLE
Release 2.45.5

### PR DESCRIPTION
**Pull request by roidelapluie**
I need to backport a fix to the LTS branch. Also update a probuf with a vulnerability.

### CODE REVIEW

**Comment by bboreham** [comment]
Did you see there was a request to backport #13135 ?

**Review by bboreham — APPROVED** [review]
LGTM

**Comment by bboreham** [comment]
Protobuf change seems to have another problem:
````
/go/pkg/mod/github.com/golang/protobuf@v1.5.3/protoc-gen-go/descriptor/descriptor.pb.go:106:61: undefined: descriptorpb.Default_FileOptions_PhpGenericServices
````

**Comment by roidelapluie** [comment]
> Protobuf change seems to have another problem:
> 
> ```
> /go/pkg/mod/github.com/golang/protobuf@v1.5.3/protoc-gen-go/descriptor/descriptor.pb.go:106:61: undefined: descriptorpb.Default_FileOptions_PhpGenericServices
> ```

Fixed

**Comment by roidelapluie** [comment]
> Did you see there was a request to backport #13135 ?

I did not see it, will do

**Review by bboreham — APPROVED** [review]
lgtm

**Review by cstyan — APPROVED** [review]

**Review by machine424 — APPROVED** [review]
lgtm

**Pull request merged**
