### PR TITLE
Update vendoring of golang.org/x/net/context/...

### PR DESCRIPTION
**Pull request by beorn7**
This should fix problems with hung scrapes.

@fabxc

### CODE REVIEW

**Comment by grobie** [comment]
Can you check if you have the latest version of govendor? They introduced a `checksumSHA1` field.

**Comment by fabxc** [comment]
👍

**Comment by beorn7** [comment]
@grobie Good catch. Updated.

**Comment by beorn7** [comment]
FTR: I executed the new code path in practice:
screenshot_20160519_103629

That's the expected error message, and I have never seen it before.

**Pull request merged**
