### PR TITLE
Use 1.6 tag of the test image in circleci

### PR DESCRIPTION
**Pull request by sdurrheimer**

### CODE REVIEW

**Comment by grobie** [comment]
What is the motivation? In golang 1.6==1.6.0, so this is actually downgrading two patch versions. Do you follow a different naming scheme in the docker images?

**Comment by sdurrheimer** [comment]
I don't follow this confusing naming scheme, for me `1.6` means the latest `1.6.x`. It is way more convenient to use, since it doesn't requires you to update all your config files, if Golang release a new patch version.

**Comment by grobie** [comment]
I understand the motivation to use a label saying "the latest patch version of major.minor" and how that makes things easier. In the context of go, the current image name is ambiguous though. Using `1.6.x` is unambiguous and the reason I opened https://github.com/prometheus/golang-builder/issues/12

**Comment by grobie** [comment]
:+1: to the change in general

**Pull request merged**
