### PR TITLE
don't store empty values in the URL

### PR DESCRIPTION
**Pull request by alicebob**
This changes URLs such as:

`http://localhost:9090/graph#[{%22range_input%22%3A%222h%22%2C%22end_input%22%3A%22%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3A%22%22%2C%22expr%22%3A%22prometheus_build_info%22%2C%22tab%22%3A1}]`

into:

`http://localhost:9090/graph#[{%22range_input%22%3A%222h%22%2C%22expr%22%3A%22prometheus_build_info%22%2C%22tab%22%3A1}] `

Empty values (such as 'range_input' in the example above) are skipped now.

You'll need to run `make assets` (and commit) after merging.

For @grobie maybe?

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks. The `make assets` and `make format` step should be part of the PR.

**Comment by alicebob** [comment]
updated (`push -f`)

**Comment by fabxc** [comment]
Thanks 👍

**Comment by grobie** [comment]
Thanks! Looks great.

**Pull request merged**
