### PR TITLE
Allow negative offset in PromQL

### PR DESCRIPTION
**Pull request by dgl**

### CODE REVIEW

**Comment by brian-brazil** [comment]
As indicated in the issue, this is not desirable and can be done in other ways.

**Comment by roidelapluie** [comment]
This has been declined here already: https://github.com/prometheus/prometheus/pull/2673

**Comment by roidelapluie** [comment]
Hello David!

Things have changed and we now have a different consensus:

CONSENSUS: As an experimental feature behind a feature flag, we will allow query evaluation to access samples with a timestamp larger than the evaluation timestamp

Would you mind re-working this pull request, and add the required feature flag?

Thank you!

**Comment by roidelapluie** [comment]
Source: https://docs.google.com/document/d/18Jbl5LC_FPLqCqU12qY8XpjVMJLCtGt-ykbyAhYXcIc/edit

**Comment by beorn7** [comment]
This is kind of related to allowing the `@` modifier, see #8121 . Not sure if there will be direct overlap in the code, but they should be implemented in a consistent way. And maybe the could share the same feature flag.

**Comment by brian-brazil** [comment]
#8121 should go through first after which this should be trivial, the other way around would cause annoying merge conflicts.

**Comment by dgl** [comment]
Ack, willing to help here but still waiting on the other PR.

**Comment by codesome** [comment]
And that PR is in! See https://github.com/prometheus/prometheus/issues/6282#issuecomment-763526507 for the flag to put this behind.

**Comment by vsile** [comment]
Hello David!
Can you help for this feature?
@dgl

**Pull request closed without merging**
