### PR TITLE
Fix for #3312 sigpanic in TargetManager

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fix for #3312
Run stop only when the TargetManager is confirmed to be started.

cc: @brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Shouldn't this be against master?

**Comment by brian-brazil** [comment]
That's for when we'll be doing a bugfix release, which I don't think is planned here. We should get this fix into master, and if it's a big enough problem for users to justify another 1.8 release we'll worry about that then.

**Comment by krasi-georgiev** [comment]
ok I will open another PR against master.

Just curious , what about these other small issue that were merged against the 1.8 release ?
these ones for example
https://github.com/prometheus/prometheus/commit/bf8e002fcecce326edce70ccbe7b2141ea04183c
https://github.com/prometheus/prometheus/commit/a731a43302a0525affd3bd1253d901ad99786453

**Comment by brian-brazil** [comment]
Those were released as 1.8.2.

**Comment by grobie** [comment]
We release 1.8.2 already with these changes https://github.com/prometheus/prometheus/releases/tag/v1.8.2.

**Comment by krasi-georgiev** [comment]
opened against master
https://github.com/prometheus/prometheus/pull/3420

**Comment by beorn7** [comment]
I think this should have gone into release-1.8 first.

**Pull request closed without merging**
