### PR TITLE
Retrieval refactoring

### PR DESCRIPTION
**Pull request by fabxc**
We group providers by their scrape configuration. Each provider produces
target groups with an unique identifier.

On stopping a set of target providers we cancel the target providers,
stop scraping the targets and wait for the scrapers to finish.

On configuration reload all provider sets are stopped and new ones
are created. This will make targets disappear briefly on configuration
reload. Potentially scrapes are missed but due to the consistent
scrape intervals implemented recently, the impact is minor. (This behavior will be fixed by further changes.)

@brian-brazil 

Code up for review. I'll add improvements based on these changes.
The tests have to be completely redone anyway. To avoid duplicate work I'll write them after I've done a few more changes on top.

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: on the general approach. Longer review after WIP goes away.

**Comment by brian-brazil** [comment]
General approach looks good, this will be great to get in

**Comment by fabxc** [comment]
Even though the brief disruption is a minor feature downgrade, I would prefer getting this merged rather soon. Before this makes it into a release I'll have added the necessary bist on top. 

But we really don't want this PR to blow up to 10+ rather complex commits.

**Comment by fabxc** [comment]
@brian-brazil @juliusv ^

**Comment by brian-brazil** [comment]
:+1:

**Comment by fabxc** [comment]
A/B testing is looking good.
Slight increase of goroutines, which is to be expected due to the design changes (constant ~35 more, total ~1450 with ~1300 targets).

I will run another one with even higher load. If nothing comes up we should merge soon.

**Comment by fabxc** [comment]
Seems to be working well. There are a few more things to work on but any objections to getting this into master?

@brian-brazil @beorn7 @juliusv

**Comment by juliusv** [comment]
I haven't given this a second, closer look yet. But currently traveling and wouldn't be able to until sometime next week. But if you feel like it's been reviewed enough by @brian-brazil and real-world tests are looking good so far, I'd say go ahead.

**Comment by fabxc** [comment]
Let's get some milage on this.

**Pull request merged**
