### PR TITLE
Add regression test for scrape_samples_scraped_post_relabelling metric

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
TestScrapeLoopAppendGracefullyIfAmendOrOutOfOrderOrOutOfBounds seems to already cover this.

**Comment by roidelapluie** [comment]
It does not test that the removed/relabeled items are not counted

**Comment by brian-brazil** [comment]
TestScrapeLoopAppendSampleLimit does though.

**Comment by roidelapluie** [comment]
I will try to think why that test did not catch the regression then

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/pull/7342/files did not touch TestScrapeLoopAppendSampleLimit

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/pull/7342/files did not touch TestScrapeLoopAppendSampleLimit because there was an exception on ErrAppendSampleLimit and that test always produces that.

**Comment by brian-brazil** [comment]
That exception was removed though, so the existing tests should now cover things sufficiently.

**Pull request closed without merging**
