### PR TITLE
Expand alert templates at eval time.

### LINKED ISSUE #1678: ALERT labels do not overwrite.
https://prometheus.io/docs/alerting/rules/ reads (about `LABELS` in `ALERT` rules): "Any existing conflicting labels will be overwritten."

That doesn't seem to be true. Existing labels are left intact, and the newly added label is ignored in case of a conflict.

Either we need to fix the docs, or the code.

What's the intended behavior? @brian-brazil @fabxc

### PR DESCRIPTION
**Pull request by brian-brazil**
Fixes #1678 #1677

### CODE REVIEW

**Comment by fabxc** [comment]
Mh, is this breaking in any way so it cannot be done after 1.0?

**Comment by brian-brazil** [comment]
It could be argued that this is changing the semantic of alert template expansions.

I'm expecting many orgs to run 1.0 and never upgrade, so avoiding potential semantic bugs like this one would be good.

**Comment by fabxc** [comment]
Alright, I guess the code works just fine. Tests would be nice for sure.

The `externalURL` argument hurts my eyes a bit. Maybe a low-priority issue to look into sanitizing the code here a bit so we don't go into cascading quality-degradation.

**Comment by brian-brazil** [comment]
The test changes I made should cover it for labels.

**Comment by mirthy** [comment]
I think this may have caused a regression, I'm seeing the internal __name__ label in the alerts now (and they end up in the alertmanager too).

**Comment by fabxc** [comment]
@brian-brazil

**Pull request merged**
