### PR TITLE
Pinned actions by SHA

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for some of the actions. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

### CODE REVIEW

**Comment by roidelapluie** [comment]
How does this work with dependabot?

**Comment by naveensrinivasan** [comment]
> How does this work with dependabot?

@roidelapluie dependabot is aware of these pinned version and they upgraded pinned versions and here is an example https://github.com/ossf/scorecard/pull/1698

**Comment by prymitive** [comment]
Comment with version doesn’t seem updated on that pr. It still shows 3.1 while the pr is for 4.x

**Comment by naveensrinivasan** [comment]
> Comment with version doesn’t seem updated on that pr. It still shows 3.1 while the pr is for 4.x

Can you specific as to for which one you are referring to?

**Comment by prymitive** [comment]
if you look at the diff from the pr you linked you’ll see that there’s a comment after sha.
Comment is outdated and probably was never updated by dependabot 

https://github.com/ossf/scorecard/pull/1698/files

**Comment by roidelapluie** [comment]
Indeed.

**Comment by naveensrinivasan** [comment]
> if you look at the diff from the pr you linked you’ll see that there’s a comment after sha. Comment is outdated and probably was never updated by dependabot
> 
> https://github.com/ossf/scorecard/pull/1698/files

Yes there is a bug in dependabot upstream for updating comments on PR's. Is that a blocker?

**Comment by roidelapluie** [comment]
Not a blocker but we should not put a commend that will derive.

cc @superq WDYT about this change?

**Comment by naveensrinivasan** [comment]
>Pin actions to a full length commit SHA

>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by naveensrinivasan** [comment]
> Not a blocker but we should not put a commend that will derive.
> 
> cc @SuperQ WDYT about this change?

@roidelapluie A friendly reminder

**Comment by naveensrinivasan** [comment]
a  friendly ping

**Pull request closed without merging**
