### PR TITLE
Revert "Fix `MemPostings.Add` and `MemPostings.Get` data race (#15141)"

### PR DESCRIPTION
**Pull request by bboreham**
This reverts commit 50ef0dc954592666a13ff92ef20811f0127c3b49.

Memory allocation goes so high in Prombench that the system is unusable.

I believe the race that #15141 was fixing had existed for years, so maybe we can live with it till we find a better fix?

### CODE REVIEW

**Review by aknuds1 — APPROVED** [review]
Too bad it has to be reverted :( Thanks for figuring out the performance regression though.

**Comment by bboreham** [comment]
Going to rebase to fix the Node build errors.

**Comment by bboreham** [comment]
For the record, this the difference:
image

**Pull request merged**
