### PR TITLE
Scraping: add scrape_count extra metric

### PR DESCRIPTION
**Pull request by bboreham**
This arises from a situation, where I am debugging Prometheus remote-writing to another store.
When there are gaps in metrics in the store, I cannot* tell whether Prometheus failed to scrape the data or whether the store failed to capture the data.

This metric `scrape_count`, added on every target, will let me detect whether the scrape happened or not.

Only enabled if feature-flag `extra-scrape-metrics` is turned on.

Extend `TestScrapeLoopStop` to check it was incremented.

\* happy to hear other ideas how to detect this.

### CODE REVIEW

**Comment by machine424** [comment]
How about running `count_over_time/sum_over_time` on the `up` metrics?

**Comment by bboreham** [comment]
> How about running count_over_time/sum_over_time on the up metrics?

I don't see how that tells me whether Prometheus failed to scrape the data or whether the store failed to capture the data.
In my case `up` has gaps in it.

**Comment by machine424** [comment]
`count_over_time(up[d])` should return the number of scrapes and `sum_over_time(up[d])` the number of successful scrapes, but maybe I'm not getting what you're trying to achieve.

**Comment by bboreham** [comment]
Indeed they should do, but there are gaps in the data that reached the remote-write store.

Here is an example:
image

**Comment by machine424** [comment]
I see and I assume that there are no metrics/logs indicating data that failed on send.
There is https://github.com/prometheus/prometheus/issues/14087 about prometheus silently skipping records when "falling behind", maybe it's the same issue.

**Comment by bboreham** [comment]
> I see and I assume that there are no metrics/logs indicating data that failed on send.

`prometheus_remote_storage_samples_failed_total` and `prometheus_remote_storage_samples_dropped_total` do not increase at the times of interest.  We don't have debug logging on.

Thanks for the pointer to #14087.

**Comment by bboreham** [comment]
Having found the underlying bug, this metric would not have helped much.

Perhaps something more along the lines of `scrape_samples_scraped_total`, where I could check the rate of samples coming in against the number arriving at remote-write ?

**Pull request closed without merging**
