### PR TITLE
add key to StatusWithStatusIndicator component in loop

### PR DESCRIPTION
**Pull request by kandros**
missing key was causing reconciliation errors in console

### CODE REVIEW

**Comment by boyskila** [comment]
LGTM besides failed ```DCO``` and ```CI``` tests

**Comment by roidelapluie** [comment]
I triggered a rerun.

Regarding DCO:

 For legal reasons, we require that all commits are signed with a [DCO](https://developercertificate.org/) before we can merge them. See [this blog post](https://www.cncf.io/blog/2016/11/08/cloud-native-software-can-trust/) for considerations around this.

This means that the last line of your commit message should read like:

`Signed-Off-By: Your Name <your@email.address>`

If you are using GitHub through the web interface, it's quickest to close this PR and open a new one with the appropriate line.

If you are using Git on the command line, it is probably quickest to amend and force push. You can do that with
````
git commit --amend --signoff
git push -f $remote $remote_branch_for_pr
````

As always, be careful when force-pushing.

**Comment by kandros** [comment]
rebased and signed

**Comment by juliusv** [comment]
:+1: Nice, thanks!

**Pull request merged**
