### PR TITLE
discovery openstack: support discovery hosts

### PR DESCRIPTION
**Pull request by sak0**
support discovery openstack hosts with gophercloud
@fabxc @brian-brazil  PTAL 

Signed-off-by: CuiHaozhi <cuihz@wise2c.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you explain more about what this is?

This smells like it either may be vendor specific, or that it's a different form of discovery.

**Comment by sak0** [comment]
@brian-brazil 
Thanks for review

**before this patch**
prometheus openstack only discoved instances(guests/virtual machines) as targets
**after this patch** 
both discoverd instances and hosts as targets

In our production enviroment with a large scale,  we need monitoring hosts and vms both, and auto discovery all hosts by this mechanism is very useful  :)

**Comment by brian-brazil** [comment]
That's a different type of service discovery. We'll likely want to go down the same role route as we did with kubernetes.

**Comment by sak0** [comment]
apology for conflic, i'will take another pr for this.

**Pull request closed without merging**
