### PR TITLE
Add default values to the help for bool flags

### PR DESCRIPTION
**Pull request by rajatjindal**
for issue : https://github.com/prometheus/prometheus/issues/3476

### CODE REVIEW

**Comment by brian-brazil** [comment]
This is something that should be handled at the flag library level, so that it always happens automatically and stays up to date.

**Comment by rajatjindal** [comment]
I considered that, but they explicitly don't add default value for bool type vars

i can check with them if they are willing to take this as PR

**Comment by krasi-georgiev** [comment]
@rajatjindal yes merging this upstream would be a much better option

**Comment by brian-brazil** [comment]
I'm going to close this off for now.

**Pull request closed without merging**
