### PR TITLE
Add names and email addresses to MAINTAINERS.md

### PR DESCRIPTION
**Pull request by juliusv**
This is so people can more easily reach the right people (e.g. for security
reports), and because we do it like this in other repos.

I did add parentheses to the formatting (different than in other
MAINTAINERS.md) to make it more readable, this this repo is more complex.

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
Just added everyone mentioned as a reviewer so you can check that I'm using the right email address for you :)

**Review by beorn7 — CHANGES_REQUESTED** [review]
I would like beorn@grafana.com .

And BTW: The format that most other MAINTAINERS.md files use is
```
* Björn Rabenstein <beorn@grafana.com> @beorn7
```

**Comment by juliusv** [comment]
@beorn7

> I would like beorn@grafana.com .

Updated.

> And BTW: The format that most other MAINTAINERS.md files use is

I mentioned that in the PR description - IMO due to the complexity of this particular file, it got really unreadable just having three non-separated components after each other everywhere, including in a sentence and in comma-separated lists, so I think it's better to use more formatting here.

**Review by roidelapluie — APPROVED** [review]

**Review by csmarchbanks — APPROVED** [review]

**Review by beorn7 — APPROVED** [review]
My apologies for not reading the PR description properly before commenting. (I feel a bit millennial now. :o)

**Comment by roidelapluie** [comment]
> (I feel a bit millennial now. :o)

🕶️

**Review by cstyan — APPROVED** [review]

**Comment by juliusv** [comment]
> My apologies for not reading the PR description properly before commenting. (I feel a bit millennial now. :o)

how-do-you-do-fellow-kids-meme-gif

**Review by SuperQ — APPROVED** [review]

**Comment by juliusv** [comment]
Got enough approvals for my taste :)

**Pull request merged**
