### PR TITLE
Use faillint to ensure that no restricted imports are being used

### PR DESCRIPTION
**Pull request by jvrplmlmn**
This PR introduces the usage of `faillint` to ensure that no restricted imports are being used, this should be the last bit for https://github.com/prometheus/prometheus/issues/7647

I had to add `faillint` as a dependency for the project even though is only used for the dev toolchain and for Prometheus itself.

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
PTAL @roidelapluie 🙏

**Comment by roidelapluie** [comment]
mmh that go get is annoying

could we try golint standard?

https://github.com/golangci/golangci-lint/blob/master/.golangci.yml

the depguard thing

**Comment by roidelapluie** [comment]
mmmh my initial test:

```
linters:
  enable:
  - depguard

linters-settings:
  depguard:
    list-type: blacklist
    packages:
      - sync/atomic
    include-go-root: true
    packages-with-error-message:
      - sync/atomic: use go.uber.org/atomic
```

**Comment by roidelapluie** [comment]
@jvrplmlmn we are very interested by this. Can you implement it with depguard?

**Comment by jvrplmlmn** [comment]
@roidelapluie thanks for the suggestion, I have tackled it on a separate PR since we are taking a different approach: https://github.com/prometheus/prometheus/pull/7825

**Pull request closed without merging**
