### PR TITLE
Fix merge conflict

### PR DESCRIPTION
**Pull request by codesome**
Fix the merge conflict in https://github.com/prometheus/prometheus/pull/11447. The conflict was trivial.

### CODE REVIEW

**Comment by codesome** [comment]
Conflict mainly comes from some renaming here https://github.com/prometheus/prometheus/pull/11352

**Comment by Nexucis** [comment]
looks like you have some build issue @codesome

```
# github.com/prometheus/prometheus/tsdb
tsdb/head_wal.go:207:19: undefined: wal
```
Maybe a missed in the renaming ?

**Comment by beorn7** [comment]
Yeah, waiting for fixing tests…

**Comment by codesome** [comment]
@Nexucis @beorn7 Fixed.

**Pull request merged**
