### PR TITLE
:zap: Adds debounce in graph timerange and end time setting changes

### LINKED ISSUE #406: Debounce timerange setting changes
After pressing any of the buttons that cause timerange changes, we should wait a short amount of time before updating the graph. That way, if the user presses the button multiple times, we don't load every intermediate result immediately.

### PR DESCRIPTION
**Pull request by adrijshikhar**
Signed-off-by: Adrij Shikhar <adrijshikhar85@gmail.com>

fixes #406

### CODE REVIEW

**Comment by juliusv** [comment]
Cool, thanks! Right now it's only on the end time input, could you add the same to the range input to make the behavior consistent? I guess on the resolution step we don't need it because there's no UI buttons to change it.

**Comment by adrijshikhar** [comment]
Sure i will add `debounce` to range input in the graph

**Comment by juliusv** [comment]
Ahhh... I'm noticing one important UX issue with this: we should debounce the actual request execution, but not the display of the value in the field. Currently if I hit the "+" / "-" / etc. buttons, I don't see the value in the input change during the debounce timeout, which means I'm lacking important visual feedback for where I currently am in the range/time and how often I still have to click to get to my desired target value. So we will have to decouple the displayed value from the affected value, similar to how it is explained in https://www.freecodecamp.org/news/debounce-and-throttle-in-react-with-hooks/ (just that this component isn't a functional one yet, so it wouldn't be with hooks).

**Comment by beorn7** [comment]
During the bug scrub, we decided to close this as stale. @juliusv @adrijshikhar if you believe it still makes sense to finalize this PR, please follow up or re-open.

**Pull request closed without merging**
