### PR TITLE
Remove fuzzit, add oss-fuzz on PR

### PR DESCRIPTION
**Pull request by roidelapluie**
https://groups.google.com/u/3/g/prometheus-developers/c/YZcoHL_tH-g

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
LGTM, thanks!

**Comment by bwplotka** [comment]
(if CI passes)

**Comment by roidelapluie** [comment]
4a4ea30
 worked successfully.

In 7bc4812, I restict fuzzing to *.go, go.mod and go.sum changes, to spare CPU cycles. Therefore it does not run in this PR.

**Review by SuperQ — APPROVED** [review]
LGTM

**Pull request merged**
