### PR TITLE
Correctly identify no-op appends if the value is NaN

### PR DESCRIPTION
**Pull request by beorn7**
This requires an updating of the vendored commen.model package, which
I will do once https://github.com/prometheus/common/pull/40 is merged.

@fabxc

### CODE REVIEW

**Comment by grobie** [comment]
No tests?

**Comment by beorn7** [comment]
The Equal method tests are added in https://github.com/prometheus/common/pull/40
I didn't want to reproduce the same test here.

**Comment by beorn7** [comment]
Having said that, the existing TestAppendOutOfOrder is pretty outdated and doesn't even check for the returned error.

I'll update it and include NaN's, too.

**Comment by grobie** [comment]
Cool. Having unit tests for the Equal method is great, but it doesn't ensure that the Append method uses it and handles NaN correctly. It's not necessary to duplicate all the test case here, but I think it'd be good to verify the integration.

**Comment by beorn7** [comment]
Added much improved test and updated the vendoring. This should be ready for merging now (and it fixes a real bug, so it should go into 0.19).

@grobie @brian-brazil @fabxc whoever finds time…

**Comment by grobie** [comment]
Awesome, thanks for adding the great test coverage. Looking forward to 0.19!

:+1:

**Pull request merged**
