### PR TITLE
Display dates as well as timestamps in status page

### PR DESCRIPTION
**Pull request by sylr**
image

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks! cc @codesome @juliusv

**Comment by juliusv** [comment]
@sylr Thanks! Would you be able to do the same change to the new UI instead of the old one (or both)? Since the old one is going to disappear soon...

**Comment by juliusv** [comment]
Hmm, actually it seems the head stats are even missing in the new UI on https://demo.promlabs.com/new/tsdb-status :thinking: 

So maybe ignore that for now, we need to look at that separately.

**Comment by juliusv** [comment]
:+1:

**Pull request merged**
