### PR TITLE
Added #steps _to_openSource

### PR DESCRIPTION
**Pull request by Transwert**
Just added some minor updates, which involves pointers to resources for Go environment setup and other additional  things, which might come handy for people looking for their first contribution in open source specially in Go. can we add it in @beorn7.

Signed-off-by: Transwert <apoo123rve@gmail.com>

### CODE REVIEW

**Comment by Transwert** [comment]
@beorn7 i totally understand it, but let me include all the points which you mention, propose a new change, if it doesn't work out, fine by me. I thought that adding these changes will beneficial for new comers especially peeps who are both new to Go and Opensource.

**Comment by beorn7** [comment]
I actually don't think that the CONTRIBUTING.md file of an individual open-source project is a good place for a general introduction to open source or programming in Go.

Does anybody else have an opinion on this?

**Comment by roidelapluie** [comment]
I agree with @beorn7

**Comment by roidelapluie** [comment]
Especially since we should then also point to how to start with react, javascript, markdown and many other things used in Prometheus.

**Comment by Transwert** [comment]
@beorn7 @roidelapluie fine by me, it's just based on experience of mine that these docs can be improved a bit (or any other alternatives which can be thought about) as these might not be effective for people who are new with Go OpenSource Development, but if everybody agrees then, no problem i close this PR.

**Pull request closed without merging**
