### PR TITLE
build: try out Profile Guided Optimization

### PR DESCRIPTION
**Pull request by petethepig**
This is an attempt at testing PGO (Profile Guided Optimization) in Prometheus. See a similar previous attempt [here](https://github.com/prometheus/prometheus/pull/12777). See https://go.dev/doc/pgo for more details about PGO.

This is not intended to be merged. The profile is a large binary file that I have stored in git for temporary convenience.

cc @bboreham

### CODE REVIEW

**Comment by bboreham** [comment]
CPU appears 2% lower.
image

However range-query latency appears higher:
image

Inconclusive.

**Review by jesusvazquez — COMMENTED** [review]
This PR was reviewed during the Prometheus Bug Scrub event. 

Since this seems to be an experiment of profile guided optimization we've updated the state of the PR to Draft.

**Comment by bboreham** [comment]
Been in draft a long time; closing.

**Pull request closed without merging**
