### PR TITLE
Add cancel button on graph ui

### PR DESCRIPTION
**Pull request by alileza**
While exploring metrics with sometimes it took a while, and I decided to modify or just abort the query. It happened to me a few times that I look for a cancel button, so I thought it would be nice to have one.

**Screenshot**

Signed-off-by: Ali Reza <alirezayahya@gmail.com>

### CODE REVIEW

**Comment by codesome** [comment]
This would not cancel the query on the prometheus server. This UI change might give a wrong impression that query has stopped in the prometheus server too.

**Comment by alileza** [comment]
Yep, I'm aware of that, if you want the server to cancel the query, you also need to handle on the server side. While reading the code I also just realize, by re-execute the query, it'll abort the request as well. Feel free to close the PR if it doesn't seem to be acceptable~

**Comment by brian-brazil** [comment]
Shouldn't contexts cause it to be cancelled?

**Comment by alileza** [comment]
Ah right, didn't notice that! then I don't see any downside of having this button.

**Comment by roidelapluie** [comment]
cc @juliusv did you see this PR?

**Comment by juliusv** [comment]
Sorry for the long inactivity from my side. I think if we implement something like this, then:

- It should go into the new React UI now
- It should be visually designed to be as unobtrusive as possible, e.g. turning an existing button (maybe the "Execute" one?) into a cancellation button while the query is running

**Comment by alileza** [comment]
I think that make sense in a user experience perspective to turn the execute button to cancel. But anyway since we're moving to react ui, I think this won't be useful, I'll be closing it.

**Pull request closed without merging**
