### PR TITLE
Update remote-write grafana mixin

### PR DESCRIPTION
**Pull request by Allex1**
@beorn7 pls review
This is related to https://github.com/prometheus/prometheus/issues/8229

### CODE REVIEW

**Review by roidelapluie — COMMENTED** [review]
Should we keep that backwards-compatible?

**Comment by roidelapluie** [comment]
> Should we keep that backwards-compatible?

To clarify, that woul be using `or` : `rate(new[5m]) or rate(old[5m])`

**Comment by Allex1** [comment]
> > Should we keep that backwards-compatible?
> 
> To clarify, that woul be using `or` : `rate(new[5m]) or rate(old[5m])`

done.

**Comment by Allex1** [comment]
@roidelapluie any thoughts?

**Comment by roidelapluie** [comment]
LGTM, but I could not test it in practice yet. Can you screenshot it maybe from a server that was updated to 2.23 (with times around the migration?)

**Comment by Allex1** [comment]
@roidelapluie would these suffice ?

Screenshot 2020-12-03 at 18 46 42
Screenshot 2020-12-03 at 18 46 24

**Comment by roidelapluie** [comment]
mmh why aren't the line aligned? is there differences in labels?

**Comment by Allex1** [comment]
not sure I understand. I just changed the version on the `prometheus` cr so it generated new pods.

**Comment by roidelapluie** [comment]
Oh, I see :)

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
I will let it open a few more hours in case @beorn7 wants to review it as well

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub.

@beorn7 Do you want to make it so that these configs work with the associated version of Promethues, or be compatible with all versions of Prometheus as our metrics change over time?

**Comment by beorn7** [comment]
Good question.

In general, I think the change in this PR is a nice thing to have as updating a Prometheus server doesn't change the old metrics in your TSDB to the new name. I wouldn't commit to always do this extra effort but now that @Allex1 already did it, let's keep it but remove the old names in a few months time.

**Comment by beorn7** [comment]
Since the mixin is essentially documentation, I don't think this warrants a bugfix release of v2.23 on its own. However, if we ever need a bugfix release, this might be considered for cherrypicking. @codesome

**Comment by beorn7** [comment]
And sorry for late review. A lot off work these days, creating a huge backlog.

**Comment by roidelapluie** [comment]
> Since the mixin is essentially documentation, I don't think this warrants a bugfix release of v2.23 on its own. However, if we ever need a bugfix release, this might be considered for cherrypicking. @codesome

We do not actually release artefacts of the mixins, that would not really make sense.

**Comment by beorn7** [comment]
These are not the only things implied by a release. For example, the prometheus/client_golang releases are pretty important, and the don't create any website, container images, or binaries. People will pull in the mixin as tagged with a certain release.

**Pull request merged**
