### PR TITLE
Adding Global limits

### PR DESCRIPTION
**Pull request by sabari-karthik**
Signed-off-by: sabari karthik <sabari.karthik@gmail.com>

This is related to [11494](https://github.com/prometheus/prometheus/issues/11494)

### CODE REVIEW

**Comment by sabari-karthik** [comment]
@gouthamve Please review

**Comment by mblaschke** [comment]
any progress here?

**Comment by sabari-karthik** [comment]
Waiting for @gouthamve to approve

**Comment by mblaschke-daimlertruck** [comment]
any progress?

**Comment by roidelapluie** [comment]
Thank you for your contribution. This has been implemented in #12126.

**Pull request closed without merging**
