### PR TITLE
Update Go module directive to v2

### PR DESCRIPTION
**Pull request by SuperQ**
Make the Go modules directive to make Prometheus "v2". This allows git tags like `v2.48.0` to work as expected by thrid party imports.

### CODE REVIEW

**Comment by tomwilkie** [comment]
We discussed this a few years back and intentionally changed the go mod version to be 0.x as (see https://github.com/prometheus/prometheus#prometheus-code-base) - this change will force thousands of other projects to have to update their imports (see https://pkg.go.dev/github.com/prometheus/prometheus@v0.47.0/promql?tab=importedby).

**Comment by juliusv** [comment]
Yeah, @beorn7 (who is sitting next to me) essentially said the same and recommended talking to @roidelapluie about this.

**Comment by tomwilkie** [comment]
:-( that I'm not there

**Comment by SuperQ** [comment]
I did the whole path replacement with a `sed` script.

**Comment by roidelapluie** [comment]
I am open to the change, but indeed it will cause breakages downstream that will need to update their imports.

**Comment by beorn7** [comment]
Wasn't the whole idea of making the module version appear as 0.y.z that we don't suggest any API stability on the Go level?

In other words, if we went to a Go module version 2.x, each time we have a breaking change on the Go API level, we violate the contract of Go modules by not incrementing the major release number.

I'm actually _very_ happy with the current state. I think having a different version for the Prometheus server product vs. the prometheus/prometheus Go module is inevitable anyway. Given that we cannot avoid that confusion, I don't see any better solution than the current one.

**Comment by roidelapluie** [comment]
Technically, the solution we have now follows the Go documentation to the letter - [https://go.dev/doc/modules/version-numbers](https://go.dev/doc/modules/version-numbers) and [https://go.dev/doc/modules/release-workflow](https://go.dev/doc/modules/release-workflow). I think it's great, but this is the first time our solution is challenged from within the team.

I personally would keep the current solution as well - and map `Prometheus v3.0` to go module `v0.300`. I don't think double tagging is a big deal, but I can see how it can confuse users.

The downsides will be all the breakage the move to v2 will create, including:

- Users who see v2 as a major release and don't expect API breakage.
- The cost of every project depending on Prometheus needing to move to a v2 scheme.
- How many users will stay on the last v0 release, not knowing we have published a v2.
- Possible very annoying dependencies between projects that depend on multiple dependencies, some of which will migrate to v2 quickly, others who will not depend on v2.

**Comment by jesusvazquez** [comment]
This was reviewed during the Prometheus Bug Scrub event.

@SuperQ we suggest you add a point to the next dev summit so we can all discuss this as a team 👍 

We need to make a decision for Prometheus 3.0.0 anyway so it will actually be a timely and appropriate discussion.

**Comment by SuperQ** [comment]
FYI, we explicitly list our Go APIs as unstable in our [stability policy](https://prometheus.io/docs/prometheus/latest/stability/).

**Review by bwplotka — COMMENTED** [review]
Thanks. I think we can do this, but honestly it might be more productive and clean if we do this with v3 🤔 

It's about when we ask importers to do extra (sed) work, how we release. There is also another question:

v2 or v3 indicates we make our Go APIs "stable". This means any compatibility break will be much more surprising to callers as Go modules assumes minor/patch means automatic upgradability. I don't think we want to stabilize this as we can't really separate versioning of Prometheus vs Go code (we can actually, just it will have similar problems as what we have now, so for Prometheus 2.xx code you will need to e.g. release/import 4.21.1 Go code).

It would nice to discuss if this is what we want.

**Comment by SuperQ** [comment]
> v2 or v3 indicates we make our Go APIs "stable".

I have seen very few projects follow this in practice. Especially when we have documented that we explicitly declare that we don't follow this convention.

**Comment by beorn7** [comment]
As said, I'm happy with the current state.

As also said above already, this should be discussed at the dev-summit. Please add a topic to the agenda if you want to move forward with this.

**Comment by jesusvazquez** [comment]
cc @carrieedwards @fionaliao please consider this for discussion for the Prometheus 3.0 release

**Comment by cstyan** [comment]
> > v2 or v3 indicates we make our Go APIs "stable".
> 
> I have seen very few projects follow this in practice. Especially when we have documented that we explicitly declare that we don't follow this convention.

Yep, for quite a few years now we've had a blanket policy (or maybe just for certain packages) that the packages aren't strictly `internal` but we don't guarantee any stability. I think if we want to change that it needs to have a dev summit consensus.

**Comment by bboreham** [comment]
Hello from the bug-scrub!  I'm pretty sure we decided not to do this; can you either update where you think we are, or close the PR?  Thanks!

**Comment by SuperQ** [comment]
:disappointed:

**Pull request closed without merging**
