### PR TITLE
parser: Allow parsing arbitrary functions

### PR DESCRIPTION
**Pull request by fpetkovski**
In Thanos we would like to start experimenting with custom functions that are currently not part of the PromQL spec. We would do this by adding an implementation for those functions to the [Thanos engine](https://github.com/thanos-community/promql-engine) and allow users to decide which engine they want to use on a per-query basis.

Since we use the PromQL parser from Prometheus, injecting functions in the global `Functions` variable would mean they also become available for the Prometheus engine. To avoid this side-effect, this commit exposes a Parser interface in which the supported functions can be injected as an option. If no functions are injected, the parser implementation will default to the functions defined in the global Functions variable.

### CODE REVIEW

**Comment by roidelapluie** [comment]
While I appreciate your efforts, I cannot accept this pull request as we aim to maintain a consistent PromQL experience across the ecosystem. I would like to inquire about the types of functions that are not suitable for Prometheus upstream and whether they can be implemented (maybe even behind a feature flag).

(Additionally, some users have already been overriding the exposed `Function`.)

**Comment by fpetkovski** [comment]
Thank you for the feedback. We wanted to experiment with the `xrate`/`xincrease` functions which have been discussed extensively in this issue: https://github.com/prometheus/prometheus/issues/3806.

There are several forks out there that already add support for these functions, but I don't think Prometheus has made a decision yet on whether they make sense in prometheus/prometheus.

**Comment by roidelapluie** [comment]
In my opinion, we should move forward with implementing them in Prometheus behind a feature flag.  Since the design document has stalled, with Alin commenting last, this is definitely something worth implementing and discussing upstream.

**Comment by fpetkovski** [comment]
Thanks for the feedback, and I am glad that Prometheus is willing to consider adding these functions under a feature flag.

I will close this PR now and we will try to get ourselves unblocked in the short term. Maybe it's worth starting a discussion on this topic during a dev summit?

**Comment by roidelapluie** [comment]
It is possible to add fonctions at compile time. Some users do it already.
Functions is public for that reason. But you can't change per engine if you
have multiple engines running.

Le lun. 27 mars 2023, 15:44, Björn Rabenstein ***@***.***> a
écrit :

**Comment by roidelapluie** [comment]
Thanks for your contribution, we have decided during our bug scrub to enable this change.

**Comment by fpetkovski** [comment]
Thank you, much appreciated !

**Pull request merged**
