### PR TITLE
when zooming in/out, we keep the pre-selected lines

### LINKED ISSUE #7818: Unchecked lines should remain unchecked when zooming out
**What did you do?**
1. Visit /graph
1. Enter a query of the form `100 * (count by(job, namespace, service) (up == 0) / count by(job, namespace, service) (up)) > 10`
1. See a couple of lines that correspond to that query (?)
1. In the "legend rickshaw_legend", click the action (✔) for all but one of them
1. See that only one line remains
1. Click the "glyphicon glyphicon-plus" to change the zoom

**What did you expect to see?**

* Any line that I'd unchecked should remain unchecked.
* The line I didn't uncheck should remain checked.
* Lines that were not in the limited scope could appear checked since they had no reason not to.
* If I had zoomed in and lost a line and then later zoomed out and regained a line, I'd expect it to remain hidden.

**What did you see instead? Under which circumstances?**

All of the lines were visible

**Environment**

* System information:

```
Linux 4.19.112+ x86_64
```

* Prometheus version:

```
prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2
```

* Alertmanager version:

* Prometheus configuration file:

* Alertmanager configuration file:

* Logs:

### PR DESCRIPTION
**Pull request by showuon**
Fix #7818 , add one more parameter `needSaveLegendStatus` to check if we need to keep the legend status. Now it'll only set to true when clicking on time range button (increase/decrease).

Signed-off-by: Luke Chen <showuon@gmail.com>

### CODE REVIEW

**Comment by showuon** [comment]
@juliusv , could you review this PR? Thanks.

**Comment by juliusv** [comment]
Hi, thanks for submitting this! But I'm wondering, was there any more discussion after the last comment on https://github.com/prometheus/prometheus/issues/7818#issuecomment-682736613? Because I also was thinking the same thing as @roidelapluie, wondering whether it's worth the extra complexity to add this, since it's possible to turn off all series except some, by just clicking on the series name. And at least in the new UI, you can do that with multiple series by pressing Ctrl.

On a general note, this old UI is going away soon (yeah, for real now), so changes like this would be better made against the new React UI (under https://github.com/prometheus/prometheus/tree/master/web/ui/react-app). But it would be good to clear up the question above first, whether this is really needed.

**Comment by showuon** [comment]
@juliusv OK, I see. But in my opinion, although this old UI is going away soon, the old UI is still the entry point of Prometheus users for now. And if the enhancement makes sense and could make the user experience better, we should do it. Especially, this fix is not that complicated and ready for review now. Anyway, that's my opinion. I'll wait for the discussion. Thanks.

**Comment by codesome** [comment]
@juliusv do we want this?

**Comment by showuon** [comment]
I think we can add it since the patch is ready to go now. That's my opinion. What do you think @juliusv ?

**Comment by juliusv** [comment]
Hi, sorry for dropping the ball on this. The React UI is the default by now, so things like this should go there in the future. However, when testing this for the old UI, I also found that it still has some unexpected behavior: when you zoom into a range that has a subset of the series a different range, and then go back to the bigger range, the bigger range will only have the subset selected, even though there was never any manual selection being done. I would expect that a superset in a larger range would always be shown, unless a user has explicitly manually selected only a subset of series. Things like that still make me wonder whether the feature is worth the mental complexity though.

**Comment by showuon** [comment]
@juliusv , ok, I'll close this PR. Thanks.

**Pull request closed without merging**
