### PR TITLE
HTML-escape string return values in web UI.

### PR DESCRIPTION
**Pull request by juliusv**
Querying for the string literal `"<script>alert(1)</script>"` would alert
otherwise.

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc @brian-brazil

**Comment by brian-brazil** [comment]
I think we should go one further display metric names that can be copy/pasted into queries, rather than expecting users to realise that manual escaping is needed.

**Comment by juliusv** [comment]
@brian-brazil Not sure what you mean exactly? This only is about showing results for string result types, which you normally never do...

**Comment by brian-brazil** [comment]
I'm thinking of graph legends and the names of metrics in the table view.

**Comment by juliusv** [comment]
@brian-brazil Ok yes, that would be a totally different feature though - let's get this bug fix in first? It's a reflected XSS.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
