### PR TITLE
Change dropdown hover color to white

### PR DESCRIPTION
**Pull request by nowke**
Change Dropdown item color in navigation bar (Status) on hover from black to white. Much more readable in `steelblue` background.

Change from,

before

Change to,

after

@simonpasquier

### CODE REVIEW

**Comment by juliusv** [comment]
Sorry, didn't notice this earlier. This is for the old UI and will at least need a rebase (the conflicting file doesn't exist anymore, since asset embedding now happens differently), but happy to merge after that.

The new React UI already has different colors here, so should be fine.

**Comment by roidelapluie** [comment]
Hi @nowke, we are still interested in this. Can you rebase this change? Thanks!

**Comment by nowke** [comment]
@roidelapluie I have rebased the change.

**Comment by roidelapluie** [comment]
Thanks! I have merged it as per Julius' comment:

> This is for the old UI and will at least need a rebase, but happy to merge after that.

**Pull request merged**
