### PR TITLE
Regex match name of consul service, and split consul tags to labels.

### PR DESCRIPTION
**Pull request by zhanglp92**
I want to use regular expressions to match name of consul service, and Split tags of consul into a single label.

eg:
image

image

I'm so sorry, can‘t so good describe, because of my english.

### CODE REVIEW

**Comment by brian-brazil** [comment]
This can be done with relabelling, and we don't accept deployment-specific features into SD.

**Comment by zhanglp92** [comment]
Thanks for your answer.

When I have used the consul_sd_configs, I must use some complete name of service.
I think it don't flexibility.
So, I want  to use regular expressions to match name of consul service.

**Comment by brian-brazil** [comment]
That can be done with relabelling.

**Comment by grobie** [comment]
As mentioned, the Prometheus way to achieve this are relabel rules.

**Comment by zhanglp92** [comment]
sorry I come back.

I look source code.

eg: I want to get n1="v1" and n2="v2" or more than n3="v3"...
image

but that get only one.

prometheus.ymal
image

result
image

so I want to change consul.go or relabel.go.

**Comment by brian-brazil** [comment]
As, I said, that can be done with relabelling. https://www.robustperception.io/extracting-full-labels-from-consul-tags/

**Pull request closed without merging**
