### PR TITLE
[bugfix] Parse negative value in PromQL

### PR DESCRIPTION
**Pull request by codesome**
Fixes https://github.com/prometheus/prometheus/issues/4356

The issue was that, after seeing `+` or `-` parser was expecting `num [+-] num x num` notation and not looking for individual values. 

Signed-off-by: Ganesh Vernekar <cs15btech11018@iith.ac.in>

### CODE REVIEW

**Comment by codesome** [comment]
@brian-brazil PTAL

**Comment by codesome** [comment]
Unfortunately yes. That would be hard to tackle as we ignore white spaces.

**Comment by brian-brazil** [comment]
Hmm, given this is going to be a publicly exposed api we may want to change that.

**Comment by codesome** [comment]
So don't ignore white spaces in lexer and handle them in parsing?

**Comment by brian-brazil** [comment]
We should probably consider it for this bit of parsing.

**Comment by codesome** [comment]
@brian-brazil I have made the changes to consider spaces between values.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
