### PR TITLE
Merge back release 2.39

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by roidelapluie** [comment]
Note: no rebase/squash

**Comment by juliusv** [comment]
:+1:

**Comment by juliusv** [comment]
Tests are failing with:

```
+ tsc --module esnext --target es2018 --outDir dist/esm
src/complete/hybrid.ts(22,3): error TS2305: Module '"@prometheus-io/lezer-promql"' has no exported member 'BoolModifier'.
src/parser/parser.ts(20,3): error TS2305: Module '"@prometheus-io/lezer-promql"' has no exported member 'BoolModifier'.
src/parser/vector.ts(19,3): error TS2305: Module '"@prometheus-io/lezer-promql"' has no exported member 'MatchingModifierClause'.
npm ERR! Lifecycle script `build:lib` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @prometheus-io/codemirror-promql@0.39.0-rc.0 
npm ERR!   at location: /__w/prometheus/prometheus/web/ui/module/codemirror-promql 
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @prometheus-io/codemirror-promql@0.39.0-rc.0 
npm ERR!   at location: /__w/prometheus/prometheus/web/ui/module/codemirror-promql 
make: *** [Makefile:54: ui-build] Error 1
Error: Process completed with exit code 2.
```

These are probably related to the changes that were made in `main` to the Lezer+Codemirror code https://github.com/prometheus/prometheus/pull/11333, now mixing with the version bumps in the release branch? 
@Nexucis Could you advise on how to make the build happy in this case? :grimacing:

**Comment by Nexucis** [comment]
yeah that's because `codemirror-promql` doesn't depend on the last version of `lezer-promql`. The script `make bump-version` didn't update well the package.json (why ? no idea).

So we should probably merge the PR, and then fixing the different `package.json` right after

**Pull request merged**
