### PR TITLE
Mixin: Ignore unset remote write timestamp

### PR DESCRIPTION
**Pull request by roidelapluie**
This pull request ignores the zero value of highest_sent_timestamp_seconds
in Highest Timestamp In vs. Highest Timestamp Sent which just show that
remote write has not been successful yet.

Before:

ts1

After:

ts2

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
I have also fixed the second panel:

before

ts3

after

ts4

**Comment by beorn7** [comment]
@cstyan might have a better understanding of the remote write metrics. This looks reasonable to me, but I'm not quite sure.

**Review by csmarchbanks — APPROVED** [review]
These changes look good to me.

I am curious though, should we change the code for the underlying metrics as well? I wonder if it would be more worthwhile to not publish any value at all, or perhaps the server start time, rather than 0.

**Comment by roidelapluie** [comment]
> These changes look good to me.
> 
> I am curious though, should we change the code for the underlying metrics as well? I wonder if it would be more worthwhile to not publish any value at all, or perhaps the server start time, rather than 0.

I don't know the details but don't we replay the last segment of the walm which could be prior to the server start?

**Comment by csmarchbanks** [comment]
> I don't know the details but don't we replay the last segment of the wal, which could be prior to the server start?

Right now the replay will not write samples until the `startTimestamp`, [code reference](https://github.com/prometheus/prometheus/blob/260cd84d8f8bc8d8545a79cf538470627f3c1642/tsdb/wal/watcher.go#L494).

Whenever the remote-write checkpoint work is done it might start replaying from before then, but you could persist the highest timestamp or something in that checkpoint then to get an accurate value on startup.

**Comment by roidelapluie** [comment]
Something like https://github.com/prometheus/prometheus/pull/8057 ?

**Review by bwplotka — APPROVED** [review]
I like this much more than alternative. Commented https://github.com/prometheus/prometheus/pull/8057#issuecomment-708699670

Suggested option C: Register on first write. :hugs:

**Comment by roidelapluie** [comment]
I have merged this based on the 2 approvals + https://github.com/prometheus/prometheus/pull/8057#issuecomment-708712507

**Comment by roidelapluie** [comment]
Thanks for the reviews!

**Pull request merged**
