### PR TITLE
Use http.ProxyFromEnvironment as fallback for http connections

### PR DESCRIPTION
**Pull request by Fra-nk**
- Explicit definition of proxy variable(s) (still) has precedence over environment variables
- Environment proxies correctly handle HTTP(S)_ and NO_PROXY variables depending on the target URL.

Explicit proxy definitions (`proxy_url: http://adress:port` **should** be preferred by users, but:
1. Environment variables are considered a common way to set these values system-wide. Administrators may be surprised that setting `HTTP_PROXY` has no influence on *Prometheus'* http connections.
2. Go correctly handles the more complex cases (`HTTP_PROXY` and `NO_PROXY` defined simultaneously) for us, so it adds useful functionality with little to no maintenance overhead.
3. People already can use `HTTP_PROXY` in Alert manager.  
While support for explicit proxies should be added in the long term, consistent behavior between all components is desired.
Blackbox exporter had environment proxy variable support added in version 0.4.0 (https://github.com/prometheus/blackbox_exporter/pull/92).

According to https://github.com/prometheus/common/pull/94 this should/has to be accepted in Prometheus, so other tools which rely on `github.com/prometheus/common` can benefit from it.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Our general policy is to have all configuration come from the config file, and I think that we ever supported the environment variables was only a stopgap. What do others think?

**Comment by Fra-nk** [comment]
Since apparently only few people seem to be interested in the topic (is there a "feedback/discussion" tag you can set on the issue to make it more visible?), I want to further explain my point of view:

In general I fully agree, that the configuration should 'show' you what the program does. It is definitely the best point to define configuration variables. That's why I implemented the change so the configuration has priority over the environment proxy.
The problem is that especially proxies are a sore subject in system administration for multiple reasons:
1. Since HTTP is part of the application layer, proxies can not be easily handled by 'just' redirecting all traffic like you would do on the transport layer, e.g. by creating an `iptables` rule.

2. There is no 'single truth' how/where to define system proxy settings. At least in Linux lots of tools have agreed on the `xxx_PROXY` environment variables. Tools like https://github.com/himanshub16/ProxyMan try to offer a unified interface for the rest, but it just complicates the situation even further.
Don't get me started on Windows and the internet proxy configuration settings, which are supported by _most_ tools...

3. Some use proxies to control network/internet access, other use it as a tool for caching. While not disconnected concepts, there is a big difference between these two modes of operation.

While you should consider the configuration file 'the single point of truth', there are always lots of system configuration values which are implicitly used or assumptions made, that require you to understand **the system** that Prometheus is running on and not just the single application and its configuration (the aforementioned `iptables` comes to mind: a single bad rule can completely screw up Prometheus)
In return there are system variables which should imho be honored, when not explicitly overwritten and proxy configuration is one of these.

**Comment by brian-brazil** [comment]
> That's why I implemented the change so the configuration has priority over the environment proxy.

Not quite. If the proxy environment variables are set, there's no way to not use a proxy.

**Comment by Fra-nk** [comment]
I'm still learning go, so I"m happy to correct it, but my understanding is that defining an empty string as Proxy URL will work just fine.

**Comment by brian-brazil** [comment]
That would be quite confusing configuration wise, I could see that sort of subtlety catching out users.

**Comment by Fra-nk** [comment]
Not explicitly setting `proxy_url:` results in proxyURL `nil`.
Setting `proxy_url:` (without setting a value) also results in `nil`, which means one would have to agree on a specific configuration value which signals 'don't use a proxy at all'.
It's definitely no perfect solution, but `''` was the best I could come up with.

**Comment by brian-brazil** [comment]
Noone has come to argue for straying from our policy of all config coming from the config file, so this won't be accepted.

Sorry for this dragging out for so long.

**Comment by uberjay** [comment]
I understand it's probably 3 years too late, but this would have greatly simplified things for me. Arranging for a collection of services and tools to use a proxy worked well until I got to alertmanager. Every other systemd unit could be made to easily load its proxy environment via e.g., `EnvironmentFile=-/etc/proxy.env`. Now, the collection of "standard" proxy environment variables is a somewhat unfortunate situation, but I think it's even more unfortunate that you've chosen to not support them.

The argument "If the proxy environment variables are set, there's no way to not use a proxy" seems a bit baffling to me. If the proxy environment variables are set and you don't want to use a proxy, then just _unset the environment variables_ before starting prometheus.

**Pull request closed without merging**
