### PR TITLE
Backfill from OpenMetrics format

### PR DESCRIPTION
**Pull request by aSquare14**

### CODE REVIEW

**Comment by roidelapluie** [comment]
Hello :wave:  !

I am lost here, is this another iteration of   https://github.com/prometheus/prometheus/pull/7586 ?

Thanks!

**Comment by aSquare14** [comment]
@roidelapluie Yes it is.

**Comment by zach-source** [comment]
@aSquare14 Is there a reason why this was closed? If not can we revisit #7586 and get it finished? Right now everything but #7675 is closed. Or is #7675 the only future path?

**Comment by codesome** [comment]
You missed #8084

**Comment by zach-source** [comment]
Ah I did, thanks @codesome

**Pull request closed without merging**
