### PR TITLE
web/api: Fix typo which broke the 2.0 admin APIs.

### PR DESCRIPTION
**Pull request by Gouthamve**
Don't ask me how long it took to debug this :)

/cc @krasi-georgiev since you touched this codebase last.

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/3240)

### CODE REVIEW

**Comment by fabxc** [comment]
He 👍

**Comment by grobie** [comment]
Given the huge number of bug fixes in the web/api handlers, can we have a test to ensure the behavior won't be broken again in the future?

**Comment by krasi-georgiev** [comment]
@Gouthamve  sorry I missed that, If I read the code correct this is the v2 grpc and  I didn't test that.
should I try to add a grpc test to compensate my error :)

**Comment by Gouthamve** [comment]
@grobie Added tests for it.

@krasi-georgiev No issues, just linked you so that you could take a look :) I added the tests here but thanks for asking!

**Comment by fabxc** [comment]
Can we let `testReady` call `testReadyHandler`?

**Comment by Gouthamve** [comment]
@fabxc Went the other way round :)

**Pull request merged**
