### PR TITLE
promtool: add json schema output commands

### PR DESCRIPTION
**Pull request by muff1nman**
Json Schema is quite useful for tooling interacting with config generation. This PR adds the `schemas config` and `schemas rules` commands to promtool to output the relevant jsonschema. The schemas generated are a bit barebones but they are functional and can be improved in subsequent PRs.

Here is a render of the `promtool schemas config`: https://gist.github.com/muff1nman/355bbd775ec165a943455e6d5420c735

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you for your pull request.

What is your usecase here? Is this something we could simply have generated/downloadable in our documentation instead?

**Comment by muff1nman** [comment]
The usecase is that our prometheus config has gotten complex enough that hand editing yaml is no longer sustainable. There are a few yaml generation tools we have been using for Kubernetes resources that offer strongly typed interfaces. I.e. https://github.com/awslabs/cdk8s and https://github.com/dhall-lang/dhall-haskell (among many others). The idea here is that if one has a json schema, the correct types can be imported into these languages from json schema as interfaces to be written against. This allows all yaml management to be done in centralized way (K8S, prometheus, etc)

Having a generated/downloadable json schema in prometheus documentation would be ideal. This PRs goal was to at least provide the underlying functionality to generate the json schema which sets up the ground work to provide a downloadable artifact in the future. With that said, if you have an alternative idea on how you'd like to see the json schema generated/created, I'm all ears. This PR just seemed like the best way to get closest to the actual golang types.

**Comment by roidelapluie** [comment]
The docs published on the wesite ( https://prometheus.io/docs/prometheus/latest/getting_started/ ) are in this repo, under docs/. Therefore we could get the CI needed to publish them on the documentation website, as it all happens here.

**Comment by muff1nman** [comment]
Created an issue to describe the need: https://github.com/prometheus/prometheus/issues/8511

**Comment by roidelapluie** [comment]
Thank you! I will close this issue, but we can keep your code when implemeting the auto generation.

**Pull request closed without merging**
