### PR TITLE
Check relabel action at yaml unmarshal stage

### PR DESCRIPTION
**Pull request by DrAuYueng**
When action set null value, something  like this:
- job_name: actuator
  metrics_path: /actuator/prometheus
  scrape_interval: null
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: null
    replacement: null
    target_label: __param_target
    action: null

Case panic as blow:
panic: relabel: unknown relabel action type ""

goroutine 348 [running]:
github.com/prometheus/prometheus/pkg/relabel.relabel(0xc000868280, 0x4, 0x4, 0xc0004ee600, 0xc0002fc0a0, 0xc000805300, 0x3233011)
	/root/go/src/github.com/DrAuYueng/prometheus/pkg/relabel/relabel.go:272 +0xde6
github.com/prometheus/prometheus/pkg/relabel.Process(0xc000868280, 0x4, 0x4, 0xc000286378, 0x1, 0x1, 0x0, 0x0, 0x0)
	/root/go/src/github.com/DrAuYueng/prometheus/pkg/relabel/relabel.go:206 +0x72
github.com/prometheus/prometheus/scrape.populateLabels(0xc000c874c0, 0x1, 0x1, 0xc00080e840, 0x1, 0x1, 0xc, 0x60, 0xc0004d95c0, 0x60, ...)
	/root/go/src/github.com/DrAuYueng/prometheus/scrape/target.go:350 +0x41b
github.com/prometheus/prometheus/scrape.targetsFromGroup(0xc000ffd1d0, 0xc00080e840, 0x5025a60, 0x2a497a0, 0xc000c8c370, 0xc0002fe9a8, 0xc0002fea28, 0x2c53ec0)
	/root/go/src/github.com/DrAuYueng/prometheus/scrape/target.go:435 +0x487
github.com/prometheus/prometheus/scrape.(*scrapePool).Sync(0xc000868180, 0xc00013e320, 0x1, 0x1)
	/root/go/src/github.com/DrAuYueng/prometheus/scrape/scrape.go:465 +0x5e5
github.com/prometheus/prometheus/scrape.(*Manager).reload.func1(0xc00067d890, 0xc000868180, 0xc00013e320, 0x1, 0x1)
	/root/go/src/github.com/DrAuYueng/prometheus/scrape/manager.go:195 +0x49
created by github.com/prometheus/prometheus/scrape.(*Manager).reload
	/root/go/src/github.com/DrAuYueng/prometheus/scrape/manager.go:194 +0x210

In this case, the code in func UnmarshalYAML of receiver Action can not be reached which work well when action set to "foo" or something else.
This meaning check will be ignore(same as promtool check config) and the panic occurs in relabel func.
It's useful to reset default relabel config when action (etc.) overwrite with null, for example, set scrape_interval: null, still set correctly with default value 15s.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Empty replacement and empty separator are valids. I would instead just deal with empty action, which can be done inline in unmarshalling.

**Comment by DrAuYueng** [comment]
@roidelapluie Got it.  But i think action is still need to be set default or check for empty.
Think about this case, set action to null in yaml and use promtool check first, it will be pass through which meaning the config is valid,  but will cause promtheus crash actually. 
The key issue is pre-check, if promtool check success, promtheus should not panic with the same relabel config definition.

**Comment by DrAuYueng** [comment]
I will exclude replacement and separator.

**Comment by roidelapluie** [comment]
I think that we should error if it is empty. This shows that the user has tried to compute some configuration which is invalid. This can be done directly in UnmarshalYaml.

**Comment by DrAuYueng** [comment]
Ok. I will change the title of this PR.

**Comment by roidelapluie** [comment]
This is awesome!

Would you also add a test in config/ ? Look at `config/testdata/modulus_missing.bad.yml` which is tested in `config/config_test.go`.

**Review by roidelapluie — APPROVED** [review]
thank you! I will merge this once the tests are green.

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
