### PR TITLE
otlp: Remove OTel feature gate registration from copied translation package

### PR DESCRIPTION
**Pull request by Aneurysm9**
This change removes OTel Collector feature gates registered in copied translation packages.  These feature gates are not used in Prometheus and create duplicate registration conflicts if both the OTel and copied translation packages are imported.  Due to the state of the individual feature gates and their uses this change has no effect on the behavior of the translation packages.

### CODE REVIEW

**Review by ArthurSens — APPROVED** [review]
It's a fair change in my point of view, but I'll wait for others involved with OTLP in prometheus to give their opinions as well (it might take a few days because grafana is doing their offsite at the moment)

cc @jesusvazquez , @aknuds1 @gouthamve

**Comment by aknuds1** [comment]
Yes, we're coming back to this after off-site 🙂

**Review by dashpole — APPROVED** [review]

**Review by jesusvazquez — CHANGES_REQUESTED** [review]
Thanks Anthony for bringing this up and solving the feature gates issue!!

We just opened up https://github.com/prometheus/prometheus/pull/13991 stating that prometheus will now own this bits of code and as part of the PR we are removing the README steps and the otel contrib references and updating the licensing.

I hope you don't mind but since this PR is already drifting away @aknuds1 and I think it would make sense to rebase this PR once the other PR is merged.

**Comment by jesusvazquez** [comment]
@Aneurysm9 This PR is now unblocked, please rebase your PR

**Comment by jesusvazquez** [comment]
@Aneurysm9 thanks for your PR, I took the liberty of rebasing it to get the latest changes from main.

**Pull request merged**
