### PR TITLE
Cut release 0.15.0

### PR DESCRIPTION
**Pull request by beorn7**
Time to promote the release candidate!

@juliusv @brian-brazil @fabxc 

No changes to 0.15.0rc3.

Only consolidated the CHANGELOG.md.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
Hold off! Just noticed that the `/debug/pprof` endpoint is gone since https://github.com/prometheus/prometheus/commit/78047326b487fcfccb25fbaaa2fb5c13397ad97b. Will look into fixing this before the release so that we don't release an undebuggable Prometheus!

**Comment by juliusv** [comment]
See https://github.com/prometheus/prometheus/pull/915

**Comment by juliusv** [comment]
We should also revert https://github.com/prometheus/prometheus/pull/812 before doing 0.15.0. That was a new change since 0.14.0, but it seemed to break more than it fixed. The problem is we'll also need to make `ServiceAddress` available during relabeling then to allow @Marmelatze's use case again. Maybe just revert it now, add the new relabeling features in a subsequent patch release?

**Comment by juliusv** [comment]
See https://github.com/prometheus/prometheus/pull/919 for reverting the `ServiceAddress` change.

**Comment by beorn7** [comment]
OK. Updated CHANGELOG.md.

Good to go?

**Comment by juliusv** [comment]
:+1:

**Comment by beorn7** [comment]
OK, there we go...

**Pull request merged**
