### PR TITLE
WIP: Time golint-ci

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by LeviHarrison** [comment]
For comparison, after caching the official action takes about 30s:

https://github.com/LeviHarrison/prometheus/runs/2712125682

**Comment by roidelapluie** [comment]
We could add that action to sync_repo.sh if there is a go.mod file?

**Comment by LeviHarrison** [comment]
??? It's a Github Action so just a YAML file.

**Comment by roidelapluie** [comment]
> ??? It's a Github Action so just a YAML file.

So, it is possible then.

**Comment by LeviHarrison** [comment]
Yes it is, I was just confused by your mention of a `go.mod` file.

**Comment by Nexucis** [comment]
@roidelapluie : perhaps this PR is not required anymore and should be closed in favor of a the fresher one: https://github.com/prometheus/prometheus/pull/9232.

**Comment by LeviHarrison** [comment]
@Nexucis I think this was just for testing.

**Pull request closed without merging**
