### PR TITLE
retrieval: Don't allocate map on every scrape

### PR DESCRIPTION
**Pull request by fabxc**
@brian-brazil 

Will run it in prombench and check whether it gets resolved.

### CODE REVIEW

**Comment by fabxc** [comment]
Looks like we are back to normal. Bumps from scaling and compaction but saw-tooth pattern is gone.
screen shot 2017-05-24 at 16 35 51

But for some odd reason ingestion is not as stable anymore. Still nothing to worry about too much I suppose.

screen shot 2017-05-24 at 16 38 24

**Comment by brian-brazil** [comment]
:+1: 

A brief comment as to why we're doing this would be good.

**Comment by fabxc** [comment]
The instability is odd and bugging me a fair bit though =/

**Comment by fabxc** [comment]
Ingestion noise probably due to mis-scheduling onto a worker node.

**Pull request merged**
