### PR TITLE
New dockerfile using alpine-glibc base image and make

### PR DESCRIPTION
**Pull request by sdurrheimer**
Here the new Dockerfile with glibc which makes `domain` and `search` directives functional in `/etc/resolv.conf` file for golang.

The Dockerfile also use `make build`, which avoids breaking the image when modifying the build procedure.

Currently, it is based on a [alpine-glibc](https://github.com/sdurrheimer/alpine-glibc) image under my name. We can move this under Prometheus organization if you want. The image is pretty straightforward

PS: Moreover, I will make PRs for the other prometheus repos (exporters and tools) whose Dockerfile will use the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild) based image. This image can be also move under Prometheus organization.

@juliusv @fabxc @discordianfish

### CODE REVIEW

**Comment by matthiasr** [comment]
Unless I'm missing something, the WORKDIR is pointing at a nonexistent directory in the end?

**Comment by sdurrheimer** [comment]
The `/prometheus` folder is created by the `VOLUME` instruction.

```
/dev/sda3 on /prometheus type ext4 (rw,noatime,nodiratime,discard,data=ordered)
```

**Comment by matthiasr** [comment]
yes, but `WORKDIR` is still `/app`?

**Comment by sdurrheimer** [comment]
No it's `/prometheus`

```
EXPOSE     9090
VOLUME     [ "/prometheus" ]
WORKDIR    /prometheus
ENTRYPOINT [ "/bin/prometheus" ]
```

**Comment by matthiasr** [comment]
Ah duh, I fail at Github. That was below the fold and I didn't realize the file goes on. Sorry for the confusion!

:+1: LGTM

**Comment by juliusv** [comment]
:+1: /cc @discordianfish to take a final look.

**Comment by discordianfish** [comment]
LGTM

**Pull request merged**
