### PR TITLE
cmd/prometheus: add tests for sendAlerts

### PR DESCRIPTION
**Pull request by simonpasquier**
~~This is #3879~~ with tests.

cc @roidelapluie

### CODE REVIEW

**Comment by simonpasquier** [comment]
@brian-brazil please take a look.

**Comment by brian-brazil** [comment]
Thinking about this now, I'm not as sure this makes sense. What we send to the AM is about the active alert, not Prometheus-internal state.

**Comment by roidelapluie** [comment]
Yes and it would be a really big breaking change..

**Comment by simonpasquier** [comment]
No problem, I've just kept the tests which are still useful IMO.

**Pull request merged**
