### PR TITLE
Testing: Add more test targets

### PR DESCRIPTION
**Pull request by beorn7**
@fabxc How about that?

### CODE REVIEW

**Comment by beorn7** [comment]
@fabxc So based on your feedback on the other PR, let's just have one test target here that does not include the race detector?

**Comment by beorn7** [comment]
For the record: I _do_ use make targets manually a lot, and personally I would like the targets added here.
Running `go test ./...` from the root dir is annoying as it runs test in vendored packages, too.

**Comment by fabxc** [comment]
If others feel the same, we can add it again. It's just what we moved away from some time ago.

**Comment by beorn7** [comment]
I can live without it. So for now I have removed them again (but still removed the `-race` for the reasons discussed elsewhere).

We might want to think about making it easy to run tests with the race detector and create binaries with the race detector in the future. I'm doing that manually now and then but the number of races that crept in indicate that not many are doing that.

**Comment by fabxc** [comment]
Okay, let's go with this for now and discuss further options later.
If we had a dedicated Jenkins with a bit more power, running these things additionally is probably not too expensive.

**Comment by beorn7** [comment]
In which case we can also run the long tests (out of band perhaps, i.e. only short without race for GH PRs, but run the expensive stuff regularly to catch creep).

**Comment by beorn7** [comment]
I'll take the "Okay" above as equivalent to :+1: .

**Pull request merged**
