### PR TITLE
Fix changelog typo

### PR DESCRIPTION
**Pull request by SuperQ**
Fix entry to reference PromQL, not Promtool.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: Thanks!

**Comment by juliusv** [comment]
I just wonder if it would be better to merge this into release-2.32 and then back into main. Then we'd have it in the release branch as well and don't have to cherry-pick it from main?

**Comment by Nexucis** [comment]
Looking at the age of this PR and since we are at the version v2.34, I think it doesn't matter anymore. I would propose to simply merge it in the `main` branch and that's it.

Are you ok with that @juliusv ?

**Comment by juliusv** [comment]
Ah yeah, ok :+1:

**Pull request merged**
