### PR TITLE
Clarify units of --storage.tsdb.retention.size

### PR DESCRIPTION
**Pull request by drigz**
The flag uses Base2Bytes: https://github.com/prometheus/prometheus/blob/129ed4ec8baf32f9bccd6a73508db45dbec9cbf5/cmd/prometheus/main.go#L1476

Signed-off-by: Rodrigo Queiro <rodrigoq@google.com>

### CODE REVIEW

**Comment by drigz** [comment]
@bwplotka as TSDB maintainer.

**Review by codesome — COMMENTED** [review]
Thanks. Could you also please add that line here for the CLI help text https://github.com/prometheus/prometheus/blob/2f4289a3bfaca725a14f41e30f1c91de92936242/cmd/prometheus/main.go#L305

**Comment by drigz** [comment]
Done, thanks for the suggestion!

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
