### PR TITLE
Cut v1.2.1

### PR DESCRIPTION
**Pull request by beorn7**
@juliusv as you are apparently online.

### CODE REVIEW

**Comment by RichiH** [comment]
:+1:

**Comment by juliusv** [comment]
:+1:

**Comment by beorn7** [comment]
Now we only need somebody to tell me how to convince Promu to use Go1.7.1.

Will https://github.com/prometheus/promu/pull/48 be sufficient?

**Comment by beorn7** [comment]
Added it here to the .promu.yml.

**Pull request merged**
