### PR TITLE
Upgrade to golang 1.16

### PR DESCRIPTION
**Pull request by roidelapluie**
As discussed in the storage working group, also adds test runs on go1.15 for tsdb, to make sure we keep working for people relying on that.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Ready for review.

**Comment by SuperQ** [comment]
Maybe we should setup a test matrix and run `make test` for all Go versions back to the version listed in go.mod.

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by roidelapluie** [comment]
I have forgotten to run

/prombench master

on this one...

**Pull request merged**
