### PR TITLE
Exposing Prometheus configuration file location.

### PR DESCRIPTION
**Pull request by cmpsoares91**
Please expose the location of the configuration file so it will be a lot easier to use and test with tools like Kitematic.

### CODE REVIEW

**Comment by cmpsoares91** [comment]
Thank you for approving it. When will it be merged?

**Comment by cmpsoares91** [comment]
Hello @aixeshunter

Can you please perform the merge?

Best regards,
Carlos.

**Comment by cmpsoares91** [comment]
@brian-brazil @fabxc Can one of you merge this? It's a trivial change that will improve my work a lot.

Thanks ahead! 

Best regards, 
Carlos Soares.

**Comment by cmpsoares91** [comment]
Any updates?

**Comment by juliusv** [comment]
@discordianfish you know more about Docker files, any opinion on this?

**Comment by discordianfish** [comment]
I don't really understand how this makes things easier.

What are you trying to achieve with this?

**Comment by cmpsoares91** [comment]
Tools like Kinematic give users the possibility to very quickly test tools using docker right (as you can search, download and spin up an image from the docker repo very quickly? Even the lesser technical ones. When the volumes are defined in the Dockerfile even if not explicitly mapped out, it does allow quick manipulation of the volume and outs files using the UI itself.

So that's what I'm trying to achieve, make it easier to work/test locally with the Prometheus image, using UI tools like Kinematic.

Impact should be minimal, in the image itself it will only create a tiny new Volume with the config in it.

**Comment by cmpsoares91** [comment]
@juliusv @discordianfish Any news?

**Comment by roidelapluie** [comment]
This is a breaking change that would prevent default config files updates.

You can have that at the kitematic level.

**Comment by roidelapluie** [comment]
It feels like kitematic does not have the feature: https://github.com/docker/kitematic/pull/4401

Still it would be breaking for Prometheus. I suggest you build a 2 lines dockerfike

FROM prom/Prometheus
VOLUME /etc/prometheus

**Pull request closed without merging**
