### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by nghialv**

### CODE REVIEW

**Comment by beorn7** [comment]
The original version is correct. Why do you think it is a typo?

**Comment by beorn7** [comment]
Closing as I don't see the typo. Please re-open with explanations if needed.

**Comment by nghialv** [comment]
Hi @beorn7 . Thanks for your comment.

I think the value of ddt is calculated as the following way.
```
dt_{n} = t_{n} - t_{n-1}
dt_{n-1} = t_{n-1} - t_{n-2}

=> ddt_{n} = dt_{n} - dt_{n-1} = (t_{n} - t_{n-1})  -  (t_{n-1} - t_{n-2})
```
So I think your version is a typo.
And if your formula is correct. Then
```
ddt_{n} = (t_{n} - t_{n-1}) - (t_{n-2} - t_{n-1}) = t_{n} - t{n-2}  ==> most of the times, ddt will not be zero.
```

**Comment by beorn7** [comment]
Now I see where my brain went wrong. Sorry for the noise. You are right, and I was wrong. Merging now.

Thanks.

**Pull request merged**
