### PR TITLE
Release 2.26 to main

### PR DESCRIPTION
**Pull request by roidelapluie**
Release branches should not be squashed, rather they should have a proper merge commit.

### CODE REVIEW

**Comment by juliusv** [comment]
Can you explain to me what happened regarding https://github.com/prometheus/prometheus/pull/8678 and this PR? Both seem to merge the same unsquashed commits into `main`, but one does it from a `merge-2.26.0` branch (which has `release-2.26.0` merged into it prior to the PR), the other one directly from `release-2.26.0`.

**Comment by roidelapluie** [comment]
The other PR was squashed in the github UI in one commit

**Comment by juliusv** [comment]
Ahhh, damn. It doesn't even look like that from just the PR because GitHub just says "merged", and it doesn't tell you that it was squashed. Hmm, but if the same *content* is now already in main, just under a single squashed commit, why does this new PR still show the same diffs? Shouldn't it essentially have no diffs vs. main now?

**Comment by bwplotka** [comment]
Yea, forgot to ask to merge without squash (:

**Review by bwplotka — APPROVED** [review]

**Comment by juliusv** [comment]
I'm still curious about my previous comment though - can someone explain to me how there's a diff vs. `main` in this PR, although `main` already contained all those changes?

**Pull request merged**
