### PR TITLE
Added fuzzer for promql package

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds a fuzzer for the Exec function in the promql package which according to my analysis wasn't covered by the existing fuzzers.

The ultimate target is `_ = vectorQuery.Exec(ctx)` on line 154.
`vectorQuery` holds the random data by means of a `NewInstantQuery` with the random data.

Everything else added is just necessary to make that happen. The comments should explain that.

### CODE REVIEW

**Comment by brian-brazil** [comment]
I don't think this is actually fuzzing anything new. This code will first parse the expression, which we already fuzz. The few cases that don't fail due to parse failure will fail with a storage error, before any real PromQL execution occurs.

**Comment by AdamKorcz** [comment]
I found that this fuzzer added coverage to engine.go by going into `execEvalStmt()` on line 493 and from there into `Eval()` on line 542.
This is based on analysis on the grounds of a corpus built up from 4-8 hours of running the existing fuzzers.

**Comment by brian-brazil** [comment]
That code doesn't do anything with the query string though, that's mainly the time stuff.

**Comment by AdamKorcz** [comment]
Fair enough. I am closing then.

**Pull request closed without merging**
