### PR TITLE
Cut v2.32.0

### PR DESCRIPTION
**Pull request by juliusv**
Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by codesome** [comment]
@juliusv I was about to open a PR cherry picking https://github.com/prometheus/prometheus/pull/9980, can we include that as well?

**Comment by codesome** [comment]
https://github.com/prometheus/prometheus/pull/9985

**Review by roidelapluie — CHANGES_REQUESTED** [review]
Please hold on until we release bugfixes for previous releases.

**Comment by roidelapluie** [comment]
It is necessary to hold on because the :latest docker image points to the last release, in time. if we release 2.31.1 after 2.32.0, :latest would point to 2.31.1.

**Comment by juliusv** [comment]
Alright, will wait for the other releases before doing this one.

**Comment by codesome** [comment]
While the releases are ready with the binaries, creation of docker images are failing for the 2.30.4 and 2.31.2 patch releases, it is getting stuck at s390x build. https://app.circleci.com/pipelines/github/prometheus/prometheus/15194/workflows/5547fd32-06b4-4c56-9f2b-ab1dc3745520/jobs/71491 
I am not sure about the root cause and I mostly wont be able to take a look at it today.

**Comment by juliusv** [comment]
@codesome @roidelapluie @SuperQ Any news here on the CI stuckness?

**Comment by roidelapluie** [comment]
I am closing the problem down. I think it is because of a new busybox image published 5 days ago. cc @SuperQ

**Review by roidelapluie — APPROVED** [review]

**Pull request merged**
