### PR TITLE
PromQL parser: fastpath for non-empty matchers and metric name

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
That test failure is odd,

**Comment by roidelapluie** [comment]
> That test failure is odd,

Yes and not related to this pull request. I have relaunched

**Comment by roidelapluie** [comment]
Note:I could not reproduce the failure

Meanwhile, is this good to go ?

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
