### PR TITLE
Add /api/v1/alerts GET interface

### PR DESCRIPTION
**Pull request by wrouesnel**
Adds a JSON API for retrieving all firing alerts in the normal alertmanager POST request format via a GET request against the Prometheus server.

This is accomplished by modifying the rule manager to expose a public interface for acquiring NotificationReq structures, though there is some slight code duplication in generating the actual JSON (this possibly should be moved to a utility library?)

This provides the basis for a richer interface to manage and handle alerts.

### CODE REVIEW

**Comment by wrouesnel** [comment]
One thing that may be missing here is intelligent use of cache-control headers. Since the server knows the interval between alert rule evaluations, we could send headers to allow a downstream proxy to reduce load.

**Comment by fabxc** [comment]
Thanks. Could you describe your use case?

Generally it makes more sense to file such PRs against the dev branch of
the AM rewrite. It is unlikely that there will be a new release of what you
currently find in master.

**Comment by wrouesnel** [comment]
This is a prometheus change, not an AM change (though it's meant to support one).

The idea here is that this gives a few easy wins:
1. fills in a notable hole in the prometheus API (you can see alerts in HTML template from a server, but can't extract raw data in machine readable format
2. allows the alertmanager to operate in 'pull' mode for scenarios where that's either desirable or the only option (e.g. my office network can see prometheus, but prometheus can't send POST requests into the office network)
3. at the moment, it also means you can code up an alert client which can more easily track when alerts get resolved.

**Comment by fabxc** [comment]
Oh sorry, was writing from the UBahn and apparently mixed things up.
I will take a closer look tomorrow morning.

**Comment by brian-brazil** [comment]
If you're looking for alertstate it can be found in the `ALERTS` metrics.

This is not going to be a reliable way to do alerting, as alerting is events rather than metric based.

**Comment by wrouesnel** [comment]
Typical oncall alerts (which is what I had in mind with this) are usually based on state. If I poll at some given rate and the alert is not active for even a fraction of that rate, then I am already not interested in it as something I want to do something with.

The current dispatching scheme for Prometheus has an implicit resolution built into it anyway, since alerting rules are based on an evaluation interval (which includes a metrics scrape interval etc. etc.).

Handling alerts via the notificationmanager as event data could be an extension of this endpoint - `/api/v1/alerts/subscribe` and setup a server-sent events connection.

**Comment by brian-brazil** [comment]
I would recommend running your alertmanager in production rather than in your office, as you would any other critical production binary. Everything else you want can be done via the existing `ALERTS` metric or the notification webhook.

Exposing the full data structures we use to communicate with the alertmanager to end-users and having to support the inverse of the intended architecture will make it more difficult to implement HA for alertmanagers.

Accordingly I don't think we should currently be considering exposing this information to users, beyond possibly an console somewhere to allow looking at individual alerts for debugging. When this area has stabilised we can reconsider this.

**Comment by fabxc** [comment]
I agree that this can appear as a hole in our API. Possible use would not agree with or not, everything shown in an HTML UI should be retrievable in a machine-friendly manner.

Since this is API v1, I do not want to expose the alerts as they currently are though. With the new Alertmanager we will get a new AM API Prometheus talks to and changed alert structure (see https://github.com/prometheus/common/blob/master/model/alert.go#L28-L41).

So if we add another endpoint to the API, it should be aligned with that right way.

**Comment by wrouesnel** [comment]
Closing this due to aforementioned issues.

**Pull request closed without merging**
