### PR TITLE
Fix gitpod

### PR DESCRIPTION
**Pull request by Nexucis**

### CODE REVIEW

**Comment by Nexucis** [comment]
mmm I don't get the error of `test_mixins`. If someone can light me , would be cool :).

**Comment by juliusv** [comment]
Hm, I don't understand it either.

The error happens in https://github.com/prometheus/prometheus/blob/6c9ded2854ac0bbac862a6c0b46a29c9fa62d800/.circleci/config.yml#L114-L116, complaining about this git diff:

```
#!/bin/bash -eo pipefail
git diff --exit-code
diff --git a/.gitpod.yml b/.gitpod.yml
index bb38f6d2c..6dbc6c206 100644
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -1,5 +1,4 @@
-image:
-  file: .gitpod.Dockerfile
+---
 tasks:
   - init:
       make build
@@ -7,7 +6,7 @@ tasks:
       gp sync-done build
       ./prometheus --config.file=documentation/examples/prometheus.yml
   - command: |
-      cd web/ui/
+      cd web/ui/react-app
       gp sync-await build
       unset BROWSER
       export DANGEROUSLY_DISABLE_HOST_CHECK=true

Exited with code exit status 1
CircleCI received exit code 1
```

...but I don't understand where it would change the on-disk file back to the old version again so that this diff occurs.

@roidelapluie would you happen to understand this?

**Comment by Nexucis** [comment]
yup that's definitely super weird, because the error is in `test_mixins` and in `test_go`, but I don't see what is in common between these two jobs that would explain this diff

**Comment by roidelapluie** [comment]
git diff --exit-code probably runs against the main branch and not the pull request?

**Comment by Nexucis** [comment]
could explain the weird diff indeed, but then on every other regular PR, it should fail as well no ? I mean if it runs on the main then the diff should also fail because you will have diff on golang files.

Or it's only for the file starting with a dot like `.gitignore` maybye ?

**Comment by roidelapluie** [comment]
you run the pull request from the prometheus repository instead of a fork.

**Comment by Nexucis** [comment]
so I tried with my fork https://github.com/prometheus/prometheus/pull/9364 and it's the same issue :(.

**Comment by juliusv** [comment]
I tried reproducing all the steps locally as in `test_go`, but everything works fine. The CI definitely states the right commit in the "Checkout Code" step, so it remains a mystery as to why there is a diff at the end. Some step in the CI must be checking out the local `main` (or at least not PR) state again, and I have no idea what it could be.

**Comment by Nexucis** [comment]
I'm wondering what would happen if we just merge the PR just like that. Probably it will be ok don't you think ?

**Comment by roidelapluie** [comment]
Can you please squash your commits?

**Comment by Nexucis** [comment]
It's done @roidelapluie

**Comment by juliusv** [comment]
> I'm wondering what would happen if we just merge the PR just like that. Probably it will be ok don't you think ?

We could try and see and roll back if necessary. Or what do you think @roidelapluie 

It would of course be much preferable to understand why this is happening, but I'm not sure where to look next.

**Comment by roidelapluie** [comment]
Next is run  in circleci with ssh

**Comment by juliusv** [comment]
> Next is run in circleci with ssh

So I just did that and already while the `make GO_ONLY=1` step was still running, doing a `git diff` via ssh showed the problematic diff. `git branch` shows the `fix-gitpod` branch being checked out, but for some reason the working tree files are the `main` ones.

**Comment by roidelapluie** [comment]
This is concerning.

**Comment by roidelapluie** [comment]
https://github.com/prometheus/golang-builder/pull/160

**Comment by Nexucis** [comment]
ah looks like adding openssh in golang builder fixed the pb @roidelapluie. I just need to patch the package-lock.json and we should be good

**Comment by Nexucis** [comment]
>  I just need to patch the package-lock.json and we should be good

which is weird the CI should have failed before but oh well ...

**Comment by Nexucis** [comment]
https://github.com/prometheus/prometheus/pull/9400 should finally fix the build

**Comment by Nexucis** [comment]
Amazing all green @roidelapluie @juliusv 🥳

**Comment by juliusv** [comment]
:partying_face:

**Comment by roidelapluie** [comment]
🥳

**Pull request merged**
