### PR TITLE
React UI: Add /tsdb-status to React-handled routes

### PR DESCRIPTION
**Pull request by juliusv**
Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@boyskila @sharadgaur

**Comment by sharadgaur** [comment]
Oh, I missed that.
 LGTM I think we need to update all the `ts` files where we are using useFeatch function. Thank you @juliusv

**Comment by sharadgaur** [comment]
question: can we make type conversion via `const stats: TSDBMap = response.data;` this instead of  using `as` keywork like `const stats = response.data as TSDBMap;`

**Comment by juliusv** [comment]
@sharadgaur Ah yep, @boyskila already did that as part of https://github.com/prometheus/prometheus/pull/6314/files, but thanks!

**Comment by juliusv** [comment]
@csmarchbanks cool to merge?

**Pull request merged**
