### PR TITLE
Add API for querying raw sample values.

### PR DESCRIPTION
**Pull request by juliusv**
This is based on https://github.com/prometheus/prometheus/pull/1805, so I'm opening the PR against that for better diffing until it is merged.

This adds an API endpoint for getting out completely raw sample values via label matchers. Useful for anyone who wants to get Prometheus's raw data into some external system to do more work on the data there. It could also be useful for distributed queries.

What do people think?

### CODE REVIEW

**Comment by brian-brazil** [comment]
The `/query` interface already supports this.

For a distributed query interface we should also be doing the parsing of the matchers for the server, as what's on the other end may not be a Prometheus.

**Comment by juliusv** [comment]
Yeah, `/query` kind of does this, but it feels a bit like a hack to use it for the special case of just getting raw samples out (having to query for `foo[...]` and deriving the range from `start` and `end` yourself). I would prefer a more specialized interface that only takes matchers and not a whole query, but don't feel super strongly.

**Comment by brian-brazil** [comment]
We need an interface for that alright, I'm not sure I'd lump it in with these.

Discussions on #1487 indicate that we're looking to use the same protocol as for generic write.

We probably also want this in a different part of the URL namespace, and to mark it experimental with an intention to replace it later.

**Comment by juliusv** [comment]
Ok yeah, maybe we need to resolve the whole generic storage read/write debate first to see what that will look like. I don't know when/if I'll have time to fully jump into that, but will keep it in mind. Closing this for now then.

**Pull request closed without merging**
