### PR TITLE
Changes to Marathon service discovery to use the label PROMETHEUS_PORT_INDEX to configure the target

### PR DESCRIPTION
**Pull request by robsonpeixoto**
Use the app's label `PROMETHEUS_PORT_INDEX` to get the metrics port index

It's another approach to #2448 

Thanks @ShimiTaNaka for the suggestion

### CODE REVIEW

**Comment by grobie** [comment]
No, we shouldn't require a specific app label to be present. There are surely tons of different naming patterns in use by all the different marathon users.

If you already set a specific label to your marathon instances, you can also just add a `PROMETHEUS_PORT` label and use relabeling to use that information.

The change in #2450 will targets for each port. Relabeling can then be used to filter the target list.

**Comment by robsonpeixoto** [comment]
@grobie Thanks the the feedback

> No, we shouldn't require a specific app label to be present. There are surely tons of different naming patterns in use by all the different marathon users.

Labels are used only to integrate with external services. Use a label for that makes sense to me.
But I got your concern.

> If you already set a specific label to your marathon instances, you can also just add a PROMETHEUS_PORT label and use relabeling to use that information.

But the `PROMETHEUS_PORT` will only know the internal docker port.
The current `__target__` show the exported port by the task and this port always change. I have no idea how to use this label on the relabeling process to choose the right port.

For example. I have a process running inside the docker on the port 8000 and 8001 and the mesos created 2 tasks exporting these ports in {35000, 35001} and {36000, 36001}.

The port 8000 is my app and 8001 is my admin port (metrics, health-check, ...)
If I set the `PROMETHEUS_PORT` to 8001 how can I filter the `__target__=<host>:36000` and `__target__=<host>:35000` from my target list?

> The change in #2450 will targets for each port. Relabeling can then be used to filter the target list.
How can I use relabel to filter a target ?

**Comment by grobie** [comment]
> How can I use relabel to filter a target ?

Have a look at the `drop` action documented in https://prometheus.io/docs/operating/configuration/#relabel_config. For all available meta labels on the Marathon SD check https://prometheus.io/docs/operating/configuration/#marathon_sd_config.

**Comment by grobie** [comment]
Ugh, after studying the marathon API docs a bit, there might not be any way around such approach. It doesn't seem to be possible to attach labels to tasks and without that, there wouldn't be a way to drop specific tasks from the implementation in #2450. Furthermore, I can't see that the API exposes any mapping between the internal and the assigned external port. AFAIK we also don't provide a way to drop/keep the Xth target matching a given filter.

Any other ideas or comments @brian-brazil @fabxc?

**Comment by robsonpeixoto** [comment]
O figured out a way to use the #2450
But I'm in meeting now. I'll open another PR with the idea later

**Comment by brian-brazil** [comment]
If an SD mechanism isn't workable, then we may need to drop support.

> as golang's RE2 engine doesn't support back-references, I'm not sure how that could be used in a generic way to match against a user specified label defining desired the task index.

Indexes are bounded, multiple actions can cover this.

**Comment by robsonpeixoto** [comment]
In a marathon app definition we can add labels in `container.docker.portMappings` or in `portDefinitions` for each defined port.

My suggestion is add theses labels for each target. So, using this example we will have these targets:

*targets*
```
{__address__="host:31030", __meta_marathon_app="/robinho", __meta_marathon_app_label_PROMETHEUS="1", __meta_marathon_image="python:3", __meta_marathon_task="robinho.UUID1", __meta_marathon_port_definitions_PROMETHEUS_SKIP="1" __metrics_path__="/metrics", __scheme__="http", job="marathon"},
{__address__="host:31032", __meta_marathon_app="/robinho", __meta_marathon_app_label_PROMETHEUS="1", __meta_marathon_image="python:3", __meta_marathon_task="robinho.UUID2", __meta_marathon_port_mappings_PROMETHEUS_SKIP="2" __metrics_path__="/metrics", __scheme__="http", job="marathon"},
```

*marathon app:*
```json
{
  "id": "/robinho",
  "portDefinitions": [
    { "labels": { "PROMETHEUS_SKIP": "1" } },
    { "labels": {} }
  ],
  "container": {
    "docker": {
      "image": "python:3",
      "portMappings": [
        { "labels": {} },
        { "labels": { "PROMETHEUS_SKIP": "2" } }
      ]
    }
  },
  "labels": {
    "PROMETHEUS": "1"
  },
  "tasks": [
     {
         "id": "robinho.UUID1",
         "host": "host",
         "ports": [31030, 31032]
     }
  ]
}
```

With that approach we can use the relabeling  action `drop` or `keep`
@grobie @brian-brazil @fabxc @rohitChaware?

**Comment by grobie** [comment]
This looks good to me. I guess we'll have to export meta labels for both
labels defined in portDefinitions as well as portMappings.

**Comment by robsonpeixoto** [comment]
Yep @grobie. Because the marathon user has the flexibility to configure the label in both(portDefinitions,  portMappings).

**Comment by robsonpeixoto** [comment]
@grobie @rohitChaware #2506

**Pull request closed without merging**
