### PR TITLE
chore(remote_write): clean up as watcher.go is part of wlog now

### PR DESCRIPTION
**Pull request by machine424**

### CODE REVIEW

**Comment by machine424** [comment]
cc @cstyan, an easy one when you have time.

**Review by cstyan — COMMENTED** [review]
LGTM, compiled locally and remote write still sends samples as expected :+1: 

Just need to fix the conflict.

**Review by cstyan — APPROVED** [review]
@machine424 thanks!

**Comment by bboreham** [comment]
I looked at the history: this clean-up was possible as from 775d90d5f87a64f3594c8b911ab2bc65a04f80c1.

**Pull request merged**
