### PR TITLE
[WIP] Test if assets are up to date

### PR DESCRIPTION
**Pull request by matthiasr**
To catch the usual problem (cf. #2062) of bindata.go being outdated, add a check for this into the Travis build. The check works by regenerating the asset file and checking whether that caused a difference to Git. To make this reliable, force a modification time of "1". (Is this used in any way?)

I am a bit worried about the large changes, is there a forgotten `make assets` that this uncovered? Or did `go-bindata` change too much since last time? Are there platform dependent results?

### CODE REVIEW

**Comment by matthiasr** [comment]
This will conflict with #2062 whenever either of them is merged, but will just require a rebase / re-make-assets then.

**Comment by matthiasr** [comment]
Looks like go-bindata for me (OS X) produces different results than the one on Travis … any input on how to make this not happen is appreciated. Marked as WIP in the meantime, since this would break any contribution from Mac users.

**Comment by grobie** [comment]
I don't think the approach will work as intended. Go-bindata output is not
stable, at least timestamps will change. Also note that the output of
go-bindata is not formatted, that's why we always run gofmt afterwards.

I think such test should only check timestamps but not run go-bindata.

**Comment by matthiasr** [comment]
The timestamp issue is fixed by forcing it to be 1, same for permissions.

What should timestamps be checked against? The mtime of a file in git is
the time the last change to it was checked out. On Travis, this will always
be newer than when make assets was last run.

`go-bindata` should be able to produce stable output, and it does at least
within one machine.

Finally, without actually generating assets outside of the control of the
submitter, how can you be sure that what you reviewed is what is actually
in the shipped bindata?

**Comment by grobie** [comment]
Ah, I didn't see the changed last modified settings. I wonder if that can cause any issues, we should verify that our webserver won't return that date in Last-Modified header or uses it anywhere else.

Can you paste the different outputs? Have you tried updating your local go-bindata?

**Comment by matthiasr** [comment]
Closing this since I don't see an easy way to make it work and won't have time for the complex ways in the near future.

**Pull request closed without merging**
