### PR TITLE
Merge v2.7 bugfixes into master

### PR DESCRIPTION
**Pull request by beorn7**

### CODE REVIEW

**Comment by gouthamve** [comment]
I need to review this before this PR: https://github.com/prometheus/tsdb/pull/514 I'll get around to it today

**Comment by beorn7** [comment]
DCO tests complains about the merge commit not being DCO'd. But we usually don't do that for merge commits.

**Comment by beorn7** [comment]
This is just to make the things in release-2.7 available in master, too. It's kind of a formality. I only created a PR to let the CI run on it.
In the past, I often just merged back from the release branch directly without a PR.

**Comment by beorn7** [comment]
Note that the actual code difference is just one line. All the commits above show up because cherrypicking has happened before (which we like to avoid).

**Comment by gouthamve** [comment]
> All the commits above show up because cherrypicking has happened before (which we like to avoid)

That was because of a conflict. Both master and the PR changed the UI bundle.

**Comment by beorn7** [comment]
Fine. But can we merge this now?

**Comment by beorn7** [comment]
:bowing_man: Thank you.

**Pull request merged**
