### PR TITLE
update kubernetes to v1.18.x and update the ingress apiVersion

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @brancz as this is kube
cc @simonpasquier as this involved dependencies

thanks :)

**Comment by tariq1890** [comment]
Not sure why the windows test job should fail here. Can that job alone be restarted?

**Comment by tariq1890** [comment]
Looks like the master branch build is failing for test_windows: https://circleci.com/gh/prometheus/prometheus/29422?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The files changed in this PR don't correspond with the test failures.

**Comment by brancz** [comment]
Also having a hard time understanding the CI failure. Restarted it for now, let's see what happens.

**Comment by brancz** [comment]
This needs a rebase

**Comment by tariq1890** [comment]
Failed again. Hmmm, I see another master merge build failing: https://circleci.com/gh/prometheus/prometheus/29487?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

FYI: @brian-brazil

**Comment by tariq1890** [comment]
@roidelapluie Will you be able to help with this PR?

**Comment by tariq1890** [comment]
@simonpasquier @brancz @brian-brazil @juliusv  Figured out why it's failing

The go windows executor is using `go 1.12.7` and not `go .13`. `k8s.io/apimachinery` has breaking changes which will only build in `>= go 1.13` versions. 

How can we fix this? I believe I am using the latest windows orb in the hopes that they would have updated the go version, but that doesn't seem to be the case. Would we need to contact CircleCI?

**Comment by juliusv** [comment]
@simonpasquier could you help out with the CircleCI orb stuff? I once semi-figured out how it worked, but have forgotten everything about it again.

**Comment by roidelapluie** [comment]
> @simonpasquier could you help out with the CircleCI orb stuff? I once semi-figured out how it worked, but have forgotten everything about it again.

AFAIK circle ci does not offer go 1.14 for windows yet.

**Comment by simonpasquier** [comment]
It might be possible to install a newer version before running the tests but from a quick look, neither the `circleci/go` orb nor the `circleci/windows` orb offer this possibility...

**Comment by bwplotka** [comment]
Same problem as https://github.com/prometheus/prometheus/pull/7158

**Comment by tariq1890** [comment]
Any suggestions on what can be done at this point?

I am assuming we still want to move past `go 1.12` limitations?

**Comment by roidelapluie** [comment]
@tariq1890 I have updated go to 1.14 on windows on master. Please rebase.

**Comment by roidelapluie** [comment]
Also please revert your changes to circleci.yml

**Comment by roidelapluie** [comment]
@tariq1890 Thanks!

@brancz Please review :)

**Comment by brancz** [comment]
lgtm

**Pull request merged**
