### PR TITLE
Update fsnotify to v1.4.9

### PR DESCRIPTION
**Pull request by johejo**
Migrate from gopkg.in to github.com

Signed-off-by: Mitsuo Heijo <mitsuo.heijo@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why are you changing where we're taking the package from? The gopkg.in version appears to be official.
Also is there some particular bug or other reason you're looking to bump this?

**Comment by johejo** [comment]
fsnotify migrated from gopkg.in to github.com for go modules.
https://github.com/fsnotify/fsnotify/pull/309

Modules newer than v1.4.8 do not exist in gopkg.in.

Some fixes
- https://github.com/fsnotify/fsnotify/pull/219
- https://github.com/fsnotify/fsnotify/pull/273

**Comment by brian-brazil** [comment]
> Modules newer than v1.4.8 do not exist in gopkg.in.

https://gopkg.in/fsnotify/fsnotify.v1 has 1.4.9.


> fsnotify/fsnotify#219 fsnotify/fsnotify#273

We don't fork, so these aren't relevant to Prometheus.

**Comment by johejo** [comment]
ok, I understand. close

**Comment by johejo** [comment]
v1.4.9 doesn't exist in pkg.go.dev, so it seems that I made a mistake.
https://pkg.go.dev/gopkg.in/fsnotify/fsnotify.v1?tab=versions

**Pull request closed without merging**
