### PR TITLE
Set read-timeout for http.Server

### LINKED ISSUE #2238: Grafana 4.0.0 causes Prometheus denial of service
**What did you do?**

Upgraded to Grafana 4.0.0

**What did you expect to see?**

Snazzy charts as always.

**What did you see instead? Under which circumstances?**

Prometheus ran out of filehandles, didn't crash, but stopped ingesting new data.

Grafana 4.0.0 introduces a bug in which each chart data gather is issued in a new HTTP connection, and these connections appear to be kept alive in Grafana even though they are never used again. The issue is described here: https://github.com/grafana/grafana/issues/6759

Clearly Grafana needs to fix this on their end, but it exposes a problem in that Prometheus can be DoSed simply by opening too many connections. Prometheus should be able to fend off a misbehaving frontend without stopping backend data ingestion.

**Environment**

* System information:

```
Linux 3.13.0-76-generic x86_64
```

* Prometheus version: 

```
prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root@e685d23d8809
  build date:       20161128-09:59:22
  go version:       go1.7.3
```

* Alertmanager version: N/A

* Prometheus configuration file: N/A

* Alertmanager configuration file: N/A

* Logs:

Thousands of lines like this:
```
ERRO[2900] http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
ERRO[2898] http: Accept error: accept tcp [::]:9090: accept4: too many open files; retrying in 1s
ERRO[2898] Error refreshing service xxx_exporter: Get http://localhost:8500/v1/catalog/service/xxx_exporter?index=47790194&wait=30000ms: dial tcp 127.0.0.1:8500: socket: too many open files  source=consul.go:252
ERRO[2900] Error dropping persisted chunks: open /prometheus/data/1b/949dcb022d6cfb.db: too many open files  source=storage.go:1495
WARN[2900] Series quarantined.                           fingerprint=7795383ca895e3d7 metric=node_netstat_TcpExt_TCPHPAcks{environment="production", host="xxx", instance="xxx", job="node_exporter", role="xxx", zone="xxx"} reason=open /prometheus/data/77/95383ca895e3d7.db: too many open files source=storage.go:1646
ERRO[2900] Error while checkpointing: open /prometheus/data/heads.db.tmp: too many open files  source=storage.go:1252
ERRO[2900] Error dropping persisted chunks: open /prometheus/data/1b/94b35810940463.db: too many open files  source=storage.go:1495
ERRO[2900] Error while checkpointing: open /prometheus/data/heads.db.tmp: too many open files  source=storage.go:1252
WARN[2900] Series quarantined.                           fingerprint=baf8faede9e50c85 metric=node_vmstat_nr_tlb_local_flush_all{environment="production", host="xxx", instance="xxx", job="node_exporter", role="xxx", zone="xxx"} reason=open /prometheus/data/ba/f8faede9e50c85.db: too many open files source=storage.go:1646
```

### PR DESCRIPTION
**Pull request by agaoglu**
Fixes #2238

Is this any good @fabxc ?

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks. I wrote up my total thoughts on #2238 – please have a look and see whether they make sense.

**Comment by fabxc** [comment]
LGTM 👍  Thanks

The defaults seem sane to me. @brian-brazil?

**Comment by brian-brazil** [comment]
The connections feels like it may be low. It's not hard to imagine 100 people having a dashboard open.

**Comment by agaoglu** [comment]
I guess they'll probably use a connection-pooling proxy, but i can't decide so what should it be? I'll update right away.

**Comment by brian-brazil** [comment]
512 say? Should be plenty for any reasonable usage.

**Comment by agaoglu** [comment]
Done!

**Comment by sodabrew** [comment]
👍

**Pull request merged**
