### PR TITLE
Populate __meta_gce_instance_id discovery label

### PR DESCRIPTION
**Pull request by jkohen**
Populated from instance.ID. I will follow up with a change to the documentation.

### CODE REVIEW

**Comment by simonpasquier** [comment]
You can do the documentation change in this PR. 
https://github.com/prometheus/prometheus/blob/master/docs/configuration/configuration.md

You also miss the DCO.

**Comment by jkohen** [comment]
Thanks @simonpasquier . I've addressed your feedback.

**Comment by fabxc** [comment]
👍

**Pull request merged**
