### PR TITLE
scripts: sort file list in embed directive

### PR DESCRIPTION
**Pull request by jan--f**
Otherwise the resulting string depends on find, which afaict depends on the underlying filesystem. A stable file list make it easier to detect UI changes in downstreams that need to track UI assets.

This is a new iteration of #13047 that I think is POSIX compatible, i.e. should work the same on Apple.

### CODE REVIEW

**Comment by jan--f** [comment]
@roidelapluie kindly requesting another look at this.

**Comment by roidelapluie** [comment]
why not just piping | sort after xargs?

**Comment by jan--f** [comment]
Because we keep the file names on a single line and (posix) sort doesn't sort words in a line afaik.

**Comment by roidelapluie** [comment]
We use xargs -I so seach echo has a newline

**Comment by jan--f** [comment]
Ah yes, thanks! Good point.

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks

**Pull request merged**
