### PR TITLE
Update vendor github.com/miekg/dns@v1.0.4

### PR DESCRIPTION
**Pull request by SuperQ**
Update vendor `github.com/miekg/dns` to `v1.0.4` release.
* Add dependent vendor `golang.org/x/crypto/ed25519`.
* Add dependent vendor `golang.org/x/crypto/ed25519/internal/edwards25519`.
* Add dependent vendor `golang.org/x/net/bpf`.
* Add dependent vendor `golang.org/x/net/internal/iana`.
* Add dependent vendor `golang.org/x/net/internal/socket`.
* Add dependent vendor `golang.org/x/net/ipv4`.
* Add dependent vendor `golang.org/x/net/ipv6`.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by SuperQ** [comment]
Looks like netbsd-armv6 fails with the updated golang/x/net updates. :(

```
/go/src/github.com/prometheus/prometheus/vendor/golang.org/x/net/internal/socket/mmsghdr_unix.go:11:17: undefined: mmsghdr

!! command failed: build -o .build/netbsd-armv6/prometheus -ldflags -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.Version=2.0.0 -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.Revision=a4dac8ae0b1382842696fba64cfd33faa209fcf5 -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.Branch=superq/update_dns_vendor -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.BuildUser=root@a7c4b12d0bee -X github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version.BuildDate=20171213-08:56:00  -extldflags '-static' -a -tags netgo github.com/prometheus/prometheus/cmd/prometheus: exit status 2
```

**Comment by brian-brazil** [comment]
Is this still relevant?

**Comment by SuperQ** [comment]
The tests seem to be failing on K8s discovery test timeout.  Not sure why.

**Comment by SuperQ** [comment]
Fixed the staticcheck issue.

**Pull request merged**
