### PR TITLE
Allow PromQL to register custom funcs

### PR DESCRIPTION
**Pull request by vjsamuel**
This PR attempts to achieve what is stated in https://github.com/prometheus/prometheus/issues/4522

As seen in the test case, this would allow us to register a custom function on PromQL and achieve use-cases that are not generic enough to be committed back into Prometheus. 

Kindly take a look and provide feedback.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR, Per #4522, this is not something we intend to support on maintenance/support grounds.

**Comment by vjsamuel** [comment]
@brian-brazil, I understand the concern but as I understand and please correct me if I am wrong, the community would support only folks relying on the stock code right?

**Comment by m2s** [comment]
@brian-brazil, @fabxc As I understand, the recommendation is to keep this out as this feature doesn’t benefit core prometheus.  While that makes sense for keeping low maintenance, it would hurts adoption due to inflexibility.  

If you look at other successful communities, we find ability to expand via plugin like model (e.g., Kubernetes) and registration mechanism.  When using promql as library, there would be use cases to extend it to support additional functions and extend it for supporting events and other functions?

**Comment by RalphSu** [comment]
+1 for @m2s 
This PR appeals for me. That would be helpful for extension from developer point of view who use prometheus as library.

Having new function like BB runs as preprocessing before prometheus is leaky, it's similar to holt_winters.

@brian-brazil merged discussion in #4522 to here, let me know if it's already supported.

> That's already possible within PromQL.

Do you mean extension is already possible? That would be cool, can you point me a bit of reference? Not find in site docs if i don't miss anything

**Comment by shaoxt** [comment]
I like this proposal.  Why don't we make prometheus extensible for this useful feature?

**Comment by brian-brazil** [comment]
Obseleted by #6434

**Pull request closed without merging**
