### PR TITLE
Replace AUTHORS.md by an updated MAINTAINERS.md

### PR DESCRIPTION
**Pull request by beorn7**
@juliusv @brian-brazil @fabxc

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
@juliusv @fabxc Could you thumb/comment please?

**Comment by fabxc** [comment]
I guess I kinda own the alert notification layer as well. Looks good in general.

**Comment by beorn7** [comment]
Added alert notification, too.

Ass @juliusv voiced his agreement earlier, I'll merge for now.

**Pull request merged**
