### PR TITLE
Cleanup: Remove parser switching logic

### PR DESCRIPTION
**Pull request by slrtbtfs**
During the PromQL parser rewrite there was some logic put in place that allowed switching between the non generated and the generated parser. Since the parser is now fully generated this is not needed anymore.

Signed-off-by: Tobias Guggenmos <tguggenm@redhat.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Perhaps you should group your cleanups in a single PR?

thanks

**Comment by slrtbtfs** [comment]
I assumed it's better to have multiple smaller PRs. But sure, I can do that.

**Comment by roidelapluie** [comment]
I would do multiple commits in one PR

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
