### PR TITLE
add --max-block-duration in promtool create-blocks-from rules

### PR DESCRIPTION
**Pull request by william-tran**
- support maxBlockDuration for promtool tsdb create-blocks-from rules
- Write all rules from the same group into the same block 

Fixes prometheus/prometheus#9465

### CODE REVIEW

**Comment by JessicaGreben** [comment]
At first pass this PR looks great. I want to dig into this PR a little more this week and test some edge cases to make sure there aren't any side effects I didn't think of.  Also good catch @roidelapluie about errors in the rules. We might want to log and aggregate the errors while processing them. Then after all rules have been processed return the errors.

**Comment by william-tran** [comment]
Thanks for catching that, the change to fail fast behaviour from best effort was not intended. I can tune this up.

**Comment by william-tran** [comment]
How about just taking the first commit and leaving https://github.com/prometheus/prometheus/pull/9511/commits/d69eb0865a22c3950f2316f8629ec99d8b689ba0 for another time? I see a new release is about to be cut.

**Comment by william-tran** [comment]
Thanks @JessicaGreben and @roidelapluie for your guidance!

**Pull request merged**
