### PR TITLE
chore: setting golangci-lint targeted go version

### PR DESCRIPTION
**Pull request by dongjiang1989**
Setting `golangci-lint` targeted go version to be consistent with dependency version.

ref: https://github.com/golangci/golangci-lint/discussions/2314

### CODE REVIEW

**Comment by bboreham** [comment]
No objection to the idea, but I'd like to know what the benefit to Prometheus is.
The linked issue seems to be about forcing an older version.

**Comment by dongjiang1989** [comment]
> The linked issue seems to be about forcing an older version.

Thanks for your review.  Through the `--go` setting, ensure that golang-lint uses the latest feature rules of this version of the go language for detection.
Add this parameter in `.github/workflows/ci.yml`, not in `.golangci.yml`. For local development, developers can use the old version.

**Comment by aknuds1** [comment]
> Thanks for your review. Through the --go setting, ensure that golang-lint uses the latest feature rules of this version of the go language for detection.

golangci-lint [defaults to using the Go version from go.mod](https://golangci-lint.run/usage/configuration/#run-configuration), what's the practical benefit of overriding the Go version in CI?

**Comment by krajorama** [comment]
Hello from the bug scrub:  closing the issue due to concerns raised and lack of answer, please reopen if more information is present.

**Pull request closed without merging**
