### PR TITLE
uber.go/automaxprocs package upgrade for cgroups2 support

### PR DESCRIPTION
**Pull request by TomasKohout**
Signed-off-by: Tomas Kohout <tomas.kohout1995@gmail.com>

Hi,

I'm here only to bump version of automaxprocs to 1.5.1 since it now supports v2 cgroups. :slightly_smiling_face:

### CODE REVIEW

**Comment by TomasKohout** [comment]
I'll rebase as soon as fix for ui test is in main. :slightly_smiling_face:

**Comment by roidelapluie** [comment]
@Nexucis this ui tests seem to be flappy. do you know why?

**Comment by roidelapluie** [comment]
Could you change base branch to release-2.35? we are cutting a new rc anyway

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Can you cherry pick only your commit?

**Comment by TomasKohout** [comment]
Done. :+1:

**Comment by Nexucis** [comment]
> @Nexucis this ui tests seem to be flappy. do you know why? 

Not yet :/. Another weird things with the UI environment. You fixed one thing, another one doesn't work as expected lol.

**Pull request merged**
