### PR TITLE
Use exclude in go-dep

### PR DESCRIPTION
**Pull request by roidelapluie**
The trick is to use:

```
exclude (
        // Exclude grpc v1.30.0 because of breaking changes. See #7621.
        google.golang.org/grpc v1.30.0

        // Exclude pre-go-mod kubernetes tags, as they are older
        // than v0.x releases but are picked when we update the dependencies.
        k8s.io/client-go v1.4.0+incompatible
        k8s.io/client-go v1.5.0+incompatible
        k8s.io/client-go v1.5.1+incompatible
        k8s.io/client-go v10.0.0+incompatible
        k8s.io/client-go v11.0.0+incompatible
        k8s.io/client-go v2.0.0+incompatible
        k8s.io/client-go v3.0.0+incompatible
        k8s.io/client-go v4.0.0+incompatible
        k8s.io/client-go v5.0.0+incompatible
        k8s.io/client-go v5.0.1+incompatible
        k8s.io/client-go v6.0.0+incompatible
        k8s.io/client-go v7.0.0+incompatible
        k8s.io/client-go v8.0.0+incompatible
        k8s.io/client-go v9.0.0+incompatible
)
```

cc @beorn7 as he faced the issue
cc @simonpasquier @SuperQ as our build maintainers

### CODE REVIEW

**Comment by roidelapluie** [comment]
```
exclude (
￼	google.golang.org/grpc v1.30.0
￼	k8s.io/client-go v1.4.0+incompatible
￼	k8s.io/client-go v1.5.0+incompatible
￼	k8s.io/client-go v1.5.1+incompatible
￼	k8s.io/client-go v10.0.0+incompatible
￼	k8s.io/client-go v11.0.0+incompatible
￼	k8s.io/client-go v2.0.0+incompatible
￼	k8s.io/client-go v3.0.0+incompatible
￼	k8s.io/client-go v4.0.0+incompatible
￼	k8s.io/client-go v5.0.0+incompatible
￼	k8s.io/client-go v5.0.1+incompatible
￼	k8s.io/client-go v6.0.0+incompatible
￼	k8s.io/client-go v7.0.0+incompatible
￼	k8s.io/client-go v8.0.0+incompatible
￼	k8s.io/client-go v9.0.0+incompatible
￼)
```

:cry:

cc @SuperQ @simonpasquier

**Comment by roidelapluie** [comment]
Note that this contains one of my contributions to the digitalocean api client to make it goroutine safe. However in Prometheus we only use it in one go routine so we don't need to backport it.

**Comment by beorn7** [comment]
Do you understand the test failure?

**Comment by roidelapluie** [comment]
> Do you understand the test failure?

Buggy google.golang.org/genproto release

**Comment by roidelapluie** [comment]
Yes and it is fixed. Without -mod=readonly go list with 1.14 in the do.mod file does not show the local .Dir of the package.

**Comment by roidelapluie** [comment]
Ready for review - cc @SuperQ @simonpasquier

**Pull request merged**
