### PR TITLE
added ssl scrape statistics

### PR DESCRIPTION
**Pull request by tux21b**
I would like to have some additional scrape metrics, similar to "scrape_duration_seconds" but for SSL. In particular:

`scrape_ssl`: this value is 1 if the target was scraped via SSL and 0 otherwise (similar to probe_ssl from the blackbox exporter)

`scrape_ssl_earliest_cert_expiry`: this metric is only available if scrape_ssl=1 and has the same meaning as probe_ssl_earliest_cert_expiry from the blackbox exporter.

Use case: we are running all exporters behind a nginx secured using server and client certs. It would be great to get notified when one of the server certificates is going to expire soon (similar to the blackbox exporter), but it would be overhead to configure one blackbox exporter for each scrape target. Integrating those metrics into Prometheus itself seems reasonable in my opinion.

This change is a try to add the functionality to Prometheus.

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'm not sure this functionality belongs in Prometheus. Each synthetic series we add is an additional cost that every single user of Prometheus must bear, so there's a high bar for adding new ones.

Http/https is a SD/relabelling question, there's APIs you can use to check that.

Knowing if a ssl cert is going to expire is blackbox monitoring, and as you note the blackbox exporter already handles this.

> it would be overhead to configure one blackbox exporter for each scrape target

That should require at most a doubling of the number of scrape_configs.

**Comment by tux21b** [comment]
It is not just configuration overhead, but also scraping overhead (each metrics endpoint has to be scraped multiple times). But I understand that this increases the base overhead of scraping metrics in general and that you want to avoid that. What about some kind of setting that makes this additional metrics inside the Prometheus scraper configurable?

**Comment by brian-brazil** [comment]
I think from a scrape standpoint that that sort of information is more for debugging/tracing, rather than something we'd ingest.

**Comment by juliusv** [comment]
I agree, I don't think that particular information should be automatically recorded by Prometheus into a synthetic metric per target.

**Pull request closed without merging**
