### PR TITLE
Linode: bugfix, resolves partial fetch problem in 2.52 when service discovery would return more than exceeds 500 elements

### PR DESCRIPTION
**Pull request by dandrucz**
Fixes partial fetch problem only seen on large environments where more than 500 elements are returned in the Service Discovery calls to the Linode API.  Caused by sharing of the ListOptions struct between calls, This PR resolves this.

### CODE REVIEW

**Comment by dennisme** [comment]
Looks good! Thanks @dandrucz

**Comment by dennisme** [comment]
> Thanks for the PR, but I'll need more details, if you could reproduce the issue in a test, it'd be great. I'd assume the "options" to be readonly and safe to share, `IF` there is really a problem there, I think it'll need to be fixed in `linodego` itself.

@machine424 Thats a valid point, thanks for taking a look. We will touch base with the linodego folks and get back to you. Have an awesome weekend!

**Comment by dennisme** [comment]
@ArthurSens yes it was a bug added in https://github.com/prometheus/prometheus/pull/13774 

The ListOptions is being shared between the calls. The `page` field isn't zeroed out after use (something we are also looking into). This means that when you make the ListInstances call and it returns `page: 3` for example and your subsequent ListIPAddresses only has 2 pages, it will return no data. 

```
BODY         :
{
   "data": [],
   "page": 3,
   "pages": 2,
   "results": N
}
```

I do think it would be worth reverting https://github.com/prometheus/prometheus/pull/13774 or creating a patch release with the changes once you folks have reviewed. As it stands now linode_sd in 2.52 isn't functioning as desired.

**Comment by dennisme** [comment]
With further testing for impact I can confirm that this only effects users of linode_sd with less than 500 linodes, ips or ipv6 ranges.

**Review by bboreham — APPROVED** [review]
I think this is ok to merge, even though we may prefer that the upstream library do things differently.

Personally I would put a comment somewhere, maybe line 235, noting that multiple structs are being created because `List` calls modify the parameter.

**Comment by ArthurSens** [comment]
If we want a patch release with this fix, could we point the base branch to `release-2.52`?

**Comment by dandrucz** [comment]
I have re-pointed the base branch to release-2.52 as per request.

________________________________

**Comment by machine424** [comment]
I wasn't blocking the fix ;)
I thought it should be a small bug in `linodego` that should `ALSO` be fixed there, but apparently, that's intentional, that is how they do it. 
I opened https://github.com/linode/linodego/issues/511 to discuss that.
A test would still be great for this to avoid regression. I could take a look at that when I have some time.

**Review by machine424 — APPROVED** [review]
Thanks @dennisme!

**Comment by dennisme** [comment]
Anytime @machine424! Thanks for filing the linodego issue we appreciate it!

**Comment by ArthurSens** [comment]
`Build Prometheus for all architectures` is waiting for status to be reported because `Build Prometheus for common architectures` was skipped. Looking at our [CI config](https://github.com/prometheus/prometheus/blob/a6316a5dcb9bafcae4a478c574659437f56ea0f5/.github/workflows/ci.yml#L110), I'm assuming this is expected behavior 🤔, so I'm force-merging the PR and starting the release process for the new patch

**Pull request merged**
