### PR TITLE
Avoid creating new slices for labels values on postings for matchers

### PR DESCRIPTION
**Pull request by alanprot**
Avoid creating new string slices when running queries with regex that match lots of postings.

We can see in some cases that this method is allocating quite a bit of memory and causing GC to use quite a bit CPU.

Benchmark result for the regex cases that match lots of postings (the main difference is in the total bytes allocated per operation):

```
~/go/bin/benchstat /tmp/old /tmp/new                                                                                                              

goos: linux
goarch: amd64
pkg: github.com/prometheus/prometheus/tsdb
cpu: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
                                              │  /tmp/old   │             /tmp/new              │
                                              │   sec/op    │   sec/op     vs base              │
Querier/Head/PostingsForMatchers/i=~"1.*"-32   7.939m ± 1%   7.146m ± 1%  -9.99% (p=0.002 n=6)
Querier/Block/PostingsForMatchers/i=~"1.*"-32   6.375m ± 1%   5.973m ± 3%  -6.30% (p=0.002 n=6)

                                              │   /tmp/old   │              /tmp/new               │
                                              │     B/op     │     B/op      vs base               │
Querier/Head/PostingsForMatchers/i=~"1.*"-32   3.357Mi ± 0%   2.722Mi ± 0%  -18.92% (p=0.002 n=6)
Querier/Block/PostingsForMatchers/i=~"1.*"-32   3.357Mi ± 0%   2.722Mi ± 0%  -18.92% (p=0.002 n=6)

                                              │  /tmp/old   │             /tmp/new              │
                                              │  allocs/op  │  allocs/op   vs base              │
Querier/Head/PostingsForMatchers/i=~"1.*"-32   11.13k ± 0%   11.12k ± 0%  -0.16% (p=0.002 n=6)
Querier/Block/PostingsForMatchers/i=~"1.*"-32   11.13k ± 0%   11.12k ± 0%  -0.16% (p=0.002 n=6)
```

### CODE REVIEW

**Comment by machine424** [comment]
Thanks.
I suggest keeping `res` for enhanced readability and to avoid confusion:

```
	res := vals[:0]
	for _, val := range vals {
		if m.Matches(val) {
			res = append(res, val)
		}
	}

	if len(res) == 0 {
		return index.EmptyPostings(), nil
	}

	return ix.Postings(ctx, m.Name, res...)
```
This should maintain the same performance. WDYT?

Should we also adjust `inversePostingsForMatcher` as well?

**Comment by alanprot** [comment]
Great suggestion... I updated the PR!
The benchmark results remains the same!

**Review by yeya24 — APPROVED** [review]
Looks great!

**Review by machine424 — APPROVED** [review]
> The benchmark results remains the same for memory allocation and is even better for "sec/op" (now is 10% better and before was just 6%)

Interesting, I'll dig into that when I have some time.

Good catch, lgtm.

**Comment by alanprot** [comment]
>Interesting, I'll dig into that when I have some time.

I think this is probably due the slice indexing.. im not sure... but is better anyway so all good i guess. :D

**Comment by alanprot** [comment]
We can get even better results if we pool the slices from `LabelValues` func [here](https://github.com/prometheus/prometheus/blob/f36915b6b14e3b54132a9cd701835d0255741f96/tsdb/index/postings.go#L149) and [here](https://github.com/prometheus/prometheus/blob/f36915b6b14e3b54132a9cd701835d0255741f96/tsdb/index/index.go#L1539)

WIP change: https://github.com/alanprot/prometheus/commit/e279a8352d3a2c9e557079d454a3b56c5c9a0f2f

```
goos: linux
goarch: amd64
pkg: github.com/prometheus/prometheus/tsdb
cpu: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
                                             │  /tmp/old   │              /tmp/new              │
                                             │   sec/op    │   sec/op     vs base               │
Querier/Head/PostingsForMatchers/i=~"1.*"-32   8.131m ± 2%   6.747m ± 1%  -17.02% (p=0.002 n=6)

                                             │   /tmp/old   │              /tmp/new               │
                                             │     B/op     │     B/op      vs base               │
Querier/Head/PostingsForMatchers/i=~"1.*"-32   3.357Mi ± 0%   1.212Mi ± 2%  -63.90% (p=0.002 n=6)

                                             │  /tmp/old   │             /tmp/new              │
                                             │  allocs/op  │  allocs/op   vs base              │
Querier/Head/PostingsForMatchers/i=~"1.*"-32   11.14k ± 0%   11.12k ± 0%  -0.13% (p=0.002 n=6)
```

@yeya24  @machine424 Do you think is worth it? (i think it is as it shows a big improvement on memory allocation and probably it will have a impact on GC if we run multiples regex queries)

If so i can create a follow up PR.

**Comment by alanprot** [comment]
@jesusvazquez Can you take a look when u have some time? :D

**Comment by machine424** [comment]
> @yeya24 @machine424 Do you think is worth it? (i think it is as it shows a big improvement on memory allocation and probably it will have a impact on GC if we run multiples regex queries)

> If so i can create a follow up PR.

As long the code stays correct and readable, all optimizations are welcome ;).
So yes, let's discuss that over another PR.

**Review by machine424 — APPROVED** [review]
Thanks!

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
