### PR TITLE
Remove trailing zeros in scrape timeout header

### PR DESCRIPTION
**Pull request by juliusv**
See https://twitter.com/AviKivity/status/1405147699557638145 and
https://twitter.com/juliusvolz/status/1405790211670515712

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
I do not see why we need to add that complexity. Plus we use the same in other headers.

**Comment by roidelapluie** [comment]
Also, I think some people might rely on the current format. HTTP headers are typed string, not float. As it was covered by tests, I'd expect this to be stable. This can break users.

**Comment by RichiH** [comment]
Just as the tests _finally_ pass, @roidelapluie comes with a reasonable argument. Complexity is not too much of a concern here, but external breakage is a valid point.

**Comment by roidelapluie** [comment]
We can do this for HTTP SD's "X-Prometheus-Refresh-Interval-Seconds" header, but then we would need to test it.

**Comment by roidelapluie** [comment]
(After second view, I agree that complexity is not an issue.)

**Comment by juliusv** [comment]
Yeah, the proposed solution is simpler than the current one, as generally it's preferred to do a direct formatting conversion rather than a whole `Sprintf()` call with associated string parsing and extra memory allocations for this.

I can't say I buy the breakage aspect. Someone depending on some exact number formatting seems very unlikely (and broken) to me, I don't think we have to cater to that.

**Comment by juliusv** [comment]
(regarding other headers, we should then convert them as well)

**Comment by roidelapluie** [comment]
I am not going to invent usecases about why people would use the exact string, but it can happen.

We can merge this, then let's do it still in 2.28, so we can fix HTTP SD header. It is maybe cautious to mark this as a change in the changelog (or maybe I am overthinking here).

**Comment by RichiH** [comment]
Mentioning it in the changelog can't hurt, even though it seems overkill. Doing it in 2.28 makes sense.

**Review by RichiH — APPROVED** [review]

**Comment by RichiH** [comment]
https://xkcd.com/1172/

**Comment by beorn7** [comment]
"Someone depending on some exact number formatting seems very unlikely (and broken) to me" – thanks for saying that. Note that Prometheus 2.x depends on exact number formatting when ingesting Summaries and Histograms.

**Comment by juliusv** [comment]
> Note that Prometheus 2.x depends on exact number formatting when ingesting Summaries and Histograms.

Yup :( Though important to point out that at least for the use case of `histogram_quantile()` we managed to work around that by introducing [bucket coalescing](https://github.com/prometheus/prometheus/blob/664b39157381239c7c5e568ca9dcebc8732beae4/promql/quantile.go#L117-L134) in https://github.com/prometheus/prometheus/pull/5158.

**Pull request merged**
