### PR TITLE
Revert "Improving Performance on the API Gzip Handler (#12363)"

### PR DESCRIPTION
**Pull request by roidelapluie**
This reverts commit dfae954dc1137568f33564e8cffda321f2867925.

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
I don't understand the mechanism (and I spent several hours trying to), but I agree with the results.

**Comment by jesusvazquez** [comment]
Latest benchmark shows that now the branch has better performance than 2.44 
image


So we're going to cut 2.45.0-rc.1 out of the current state of the release branch

cc @alanprot We remove this change from the release due to the performance implications. Letting you know in case you want to invest more time finding out if we can use that new lib without the performance impact. :pray:

**Comment by alanprot** [comment]
Yeah... indeed seems to be using more CPU. But (if im reading this correctly) also seems also that at some point we have a better latency and more req/second using the new handler? Do we know what happens around 6 that the req/sec start to decrease and de latency to increase (and is where we see a better latency with the new handler)? Maybe at this time the response become bigger and is where the new gzip is better?

Screenshot 2023-06-20 at 8 35 59 AM

**Comment by alanprot** [comment]
> However rc-0 is slower before that point and using more CPU so I think it is worth looking into how we can improve that.

Yeah, I agree... `rc-0` is always using more CPU and we need to understand why. I was just pointing out that seems the `rc-0` is faster after some point. (I wonder if the new lib is less efficient with smaller payload but more efficient with big ones or something like that - just speculation for now). I will see if i have some time this week to look into it!

**Comment by roidelapluie** [comment]
Thanks @alanprot :-)

**Pull request merged**
