### PR TITLE
Expose service clusterIP

### PR DESCRIPTION
**Pull request by BasPH**
Expose Kubernetes service clusterIP as meta label as suggested in https://github.com/prometheus/prometheus/issues/3110. The full label has the name `__meta_kubernetes_service_clusterIP`.

### CODE REVIEW

**Comment by fabxc** [comment]
Based on how we converted the K8S var names so far it sohuld probably be `..._cluster_ip`

**Comment by brancz** [comment]
Not that it does any harm to add this, I am curious though what you're intending to use this label for?

**Comment by grobie** [comment]
@BasPH Can you elaborate on the use case?

**Comment by michaelfavia** [comment]
I cant speak for BasPH but we have need for the ClusterIP and more importantly PORT to perform filtering of monitored metrics endpoints for prometheus. 

Right now Prometheus is pinging every available port in our pods and it would be nice to scope it down but we need the service info to do that in the prometheus.yaml

**Comment by brian-brazil** [comment]
Can you add this to the config docs please?

**Comment by krasi-georgiev** [comment]
ping @BasPH

**Comment by BasPH** [comment]
Whoops, sorry for the super late reply. I will update the docs tomorrow night. As described in https://github.com/prometheus/prometheus/issues/3110 and by @michaelfavia, it would be nice to have the cluster_ip exposed, e.g. to group pod metrics by the cluster_ip.

**Comment by brian-brazil** [comment]
Docs still need updating.

**Comment by simonpasquier** [comment]
@BasPH would you have time to rebase your change and update the [documentation](https://github.com/prometheus/prometheus/blob/master/docs/configuration/configuration.md#service)?

**Comment by simonpasquier** [comment]
Superseded by #4940

**Pull request closed without merging**
