### PR TITLE
Fix scrape races

### PR DESCRIPTION
**Pull request by simonpasquier**
The change avoids passing the full scrape configuration down to the scrape loop which resolves the data races when the scrape configuration is being reloaded.

The PR adds a unit test that fails as described in the initial report from #4067. I've seen the [other data race](https://github.com/prometheus/prometheus/issues/4067#issuecomment-380108030) too but it happened far less often.

cc @krasi-georgiev  @beorn7 @brian-brazil

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
nice! 
can confirm that it fixes the race I found.

@simonpasquier any idea how to replicate the second one?

maybe the problem is that we are passing `[]*config.RelabelConfig` with a pointer , what if we pass a copy `[]config.RelabelConfig` ?

**Comment by krasi-georgiev** [comment]
I see what you mean. I have run this for a while and no races were detected and I don't see any problems in the code changes.
+1 from me.

**Comment by brian-brazil** [comment]
:+1:

**Comment by krasi-georgiev** [comment]
@beorn7 do you want to test it?

**Comment by beorn7** [comment]
I'm on vacations this week. I'll happily try it out next week.

Can this be rebased on top of the release-2.2 branch and then merged into that one first?

**Comment by simonpasquier** [comment]
@beorn7 yep, i'll try this.

**Comment by beorn7** [comment]
I'll close this in lieu of #4096 . (We just merge from the release-2.2 into master once #4096 is merged into release-2.2.)

**Pull request closed without merging**
