### PR TITLE
vendor: update TSDB

### PR DESCRIPTION
**Pull request by fabxc**
@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
The build failure is real.

**Comment by fabxc** [comment]
Fixed it right in this PR since it's small enough.

**Comment by brian-brazil** [comment]
:+1: once CI is good.

**Comment by krasi-georgiev** [comment]
@fabxc reduced memory usage, didn't expect that.

http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&var-RuleGroup=All&var-pr-number=4471

**Pull request merged**
