### PR TITLE
Update rule_evaluation_duration_seconds to hold rule_group/rule labels

### PR DESCRIPTION
**Pull request by commixon**
Transform `rule_evaluation_duration_seconds` to SummaryVec and update it to hold "rule_group", "rule".

The reasoning behind this is to be able to find and drill down on specific rules, besides the more "general" rule_group.

This will result in a change like the following:
`prometheus_rule_evaluation_duration_seconds{instance="localhost:9090", job="prometheus", quantile="0.5"}`

--> 

`prometheus_rule_evaluation_duration_seconds{instance="localhost:9090", job="prometheus", quantile="0.5", rule="job:prometheus_info:sum", rule_group="rules.yml;example"}`

Signed-off-by: Chris Loukas <commixon@gmail.com>

### CODE REVIEW

**Comment by tchatzig** [comment]
TFKT

**Comment by commixon** [comment]
@roidelapluie Do you have any insight in why the `test_windows` step keeps failing?

**Comment by dgl** [comment]
This would add `sum(prometheus_rule_group_rules) - 1` additional timeseries; there's no current metrics that include a rule label and it would likely have too high cardinality (https://www.robustperception.io/cardinality-is-key).

There is already `prometheus_rule_group_last_duration_seconds` which does provide per rule group durations, for more detailed rule evaluation times tracing would likely be the way to go (the opentracing support does include "name" as a tag).

**Comment by commixon** [comment]
@dgl I agree about the cardinality indeed.

`prometheus_rule_group_last_duration_seconds` is useful indeed but in some cases I think the proposed diff will be kind of more useful (we recently had a case like this). I see that tracing is probably the way to go. However, do you think there would be a way to have this enabled through a flag/config setting (not even sure if this is feasible).

Disclaimer, I am really new as you can imagine in the prometheus repo here so I really have no strong opinion of course.

**Comment by roidelapluie** [comment]
Hello,

Thanks for the pull request!

Because prometheus_rule_group_last_duration_seconds is guaranteed to exist for every evaluation, I'd propose that you use alternave PromQL queries to achieve your needs. e.g `quantile_over_time(0.95, prometheus_rule_group_last_duration_seconds[1h])`, or `max_over_time(prometheus_rule_group_last_duration_seconds[1h])`.  Turning a summary into a vec seems not-needed because of the cardinality, and you should have enough other metrics to guide you to this point.

Does that make sense to you?

**Comment by commixon** [comment]
Hey @roidelapluie !

Thanks for your detailed answer. We already use the mentioned PromQL queries to discern on different rule_groups. Maybe our use case is kind of nit-picky, since we had some unknown "bad actors" (i.e. rules) and wanted to further drill down on them since we have many teams adding their own rule groups with rules. My initial thought was that maybe the extra labels could be dropped if not needed for compensation (regarding cardinality), but I guess ours is kind of an edge case.

Most probably will revert to tracing for some detailed view and find a way to alert from there. In any case, thank you very much!

**Comment by roidelapluie** [comment]
Did you also look at our query log ? :)

**Comment by roidelapluie** [comment]
Documentation about the query log: https://prometheus.io/docs/guides/query-log/

**Comment by commixon** [comment]
Aha! This is an excellent advice for live debugging! Again, thanks a lot @roidelapluie 

Will close this PR now, but again I really appreciate your insights!

**Pull request closed without merging**
