### PR TITLE
Reduce chunk write queue memory usage 1

### PR DESCRIPTION
**Pull request by pstibrany**
This avoids wasting memory on the `c.chunkRefMap` by re-initializing it regularly. When re-initializing it, it gets initialized with a size which is half of the peak usage of the time period since the last re-init event, for this we also track the peak usage and reset it on every re-init event.

Very frequent re-initialization of the map would cause unnecessary allocations, to avoid that there are two factors which limit the frequency of the re-initializations:
* There is a minimum interval of 10min between re-init events
* In order to re-init the map the recorded peak usage since the last re-init event must be at least `1000` (objects in `c.chunkRefMap`).

When re-initializing it we initialize it to half of the peak usage since the last re-init event to try to hit the sweet spot in the trade-off between initializing it to a very low size potentially resulting in many allocations to grow it, and initializing it to a large size potentially resulting in unused allocated memory.

With this solution we have the following advantages:
* If a tenant's number of active series decreases over time then we want that their queue size also shrinks over time. By always resetting it to half of the previous peak it will shrink together with the usage over time
* We don't want to initialize it to a size of 0 because this would cause a lot of allocations to grow it back to the size which it actually needs. By initializing it to half of the previous peak it will rarely have to be grown to more than double of the initialized size.
* We don't want to initialize it too frequently because that would also cause avoidable allocations, so there is a minimum interval of 10min between re-init events

This PR comes from https://github.com/grafana/mimir-prometheus/pull/131. We use it in Grafana Mimir to reduce memory usage in Mimir clusters with thousands of open TSDBs in a single process.

Related to https://github.com/prometheus/prometheus/pull/10874.

### CODE REVIEW

**Comment by pstibrany** [comment]
Before this change, we have seen this cumulative memory usage across pods in single Mimir deployment.



Legend:
- zone-a using new chunk mapper without fix from this PR
- zone-b and zone-c are using old chunk mapper before https://github.com/prometheus/prometheus/pull/10051

After applying change from this PR into zone-b and enabling new chunk mapper there, we can see that memory usage has improved compared to zone-a:




Legend:
- zone-a using new chunk mapper without fix from this PR
- zone-b using new chunk mapper with the fix from this PR
- zone-c using old chunk mapper before https://github.com/prometheus/prometheus/pull/10051

Note that memory usage in zone-b still isn't the same as with old chunk mapper (zone-c), but second part is addressed by https://github.com/prometheus/prometheus/pull/10874

**Review by codesome — APPROVED** [review]
Makes sense. Thanks!

**Comment by bboreham** [comment]
Could you say which metric is being graphed, please?  (working set?)

**Comment by pstibrany** [comment]
Query is:

```
sum by (zone) (label_replace(go_memstats_heap_inuse_bytes{job=~"cortex-dev-01/ingester.*"}, "zone", "$1", "pod", "(ingester-zone-.)-\\d+")) / 1e9
```

With pod names like `ingester-zone-<a|b|c>-<number>`.

**Pull request merged**
