### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VineethReddy02**
This is my commit message
Signed-off-by: Vineeth Reddy <vineethpothulapati@outlook.com>

Added a build badge, Good to have a badge to the latest release for Prometheus

### CODE REVIEW

**Comment by beorn7** [comment]
Not sure if that's a useful badge. A badge should display some state, which could, at least in principle, turn red. This badge will always be green. It's essentially a link to the latest release, which is almost as readily (and more uniformly) accessible via the Releases tab.

The most straightforward way to download the latest released binaries is via the project page: https://prometheus.io/download/

**Comment by VineethReddy02** [comment]
Hi Rabenstein, I was looking to work for prometheus, as a first PR tried. If you want any enhance would love to do it.

**Comment by beorn7** [comment]
Thanks for your interest in contributing. I suggest to have a look at the issues of the various repositories in the [Prometheus org](https://github.com/prometheus). Many have tags like "help wanted" or "good first issue" or "low hanging fruit". Before investing larger chunks of work, it's probably good to first join the [developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) and discuss planned contributions there. See also https://github.com/prometheus/prometheus/blob/master/CONTRIBUTING.md and the _Contributing_ section of https://prometheus.io/community/ .

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and decided to close it as per above comments. We have "help wanted" and "low hanging fruit" issues for starters :)

**Pull request closed without merging**
