### PR TITLE
Fixed broken link in tsdb README.md

### LINKED ISSUE #11069: [Broken Link in Documentation] tsdb README external link.
### What did you do?

In the tsdb [README](https://github.com/prometheus/prometheus/tree/v0.37.0/tsdb), I tried to check the external resources.

### What did you expect to see?

_No response_

### What did you see instead? Under which circumstances?

`A writeup of the original design can be found [here](https://fabxc.org/blog/2017-04-10-writing-a-tsdb/).`

The link in this line is broken.

### System information

_No response_

### Prometheus version

_No response_

### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by sonali-rajput**
Signed-off-by: Sonali Rajput <sonalirajput1088@gmail.com>

Fixes  #11069

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
LGTM, thanks

**Comment by LeviHarrison** [comment]
@RichiH have you heard anything from @fabxc or should we move forward with this?

**Comment by RichiH** [comment]
I reached out Aug 11th and didn't hear back. Let's fix it via archive.org for now and if/when @fabxc brings the link back we can point to the original source again.

**Comment by RichiH** [comment]
Thanks @sonali-rajput !

**Pull request merged**
