### PR TITLE
Explicitly add logging flags to our custom flag set

### PR DESCRIPTION
**Pull request by beorn7**
In https://github.com/prometheus/prometheus/pull/1782 , we moved to a
custom flag set to avoid getting test flags into the main prometheus
binary. However, that removed the logging flags, too. This commit
updates the vendoring to a version of the log package that allows
adding the log flags to our flag set explicitly.

@juliusv @fabxc 

Fixes https://github.com/prometheus/prometheus/issues/1826

### CODE REVIEW

**Comment by beorn7** [comment]
My bad, I got confused with branches. Pushed to release-1.0 and created a PR for master instead of pushing to my own branch creating a PR for the release-1.0 branch.

Still, this can be used for reviewing.
We have to merge into master later anyway.

**Comment by SuperQ** [comment]
:+1:

**Comment by juliusv** [comment]
:+1:

**Comment by beorn7** [comment]
So now it is in master and release-1.0.

I guess we should release 1.0.1 pretty soon. There were too many zeros anyway...

**Pull request merged**
