### PR TITLE
Migrate "golang.org/x/net/context" -> "context"

### PR DESCRIPTION
**Pull request by juliusv**
In some places, where ctxhttp or gRPC are concerned, we still need to use the
old contexts.

### CODE REVIEW

**Comment by fabxc** [comment]
👍

**Comment by juliusv** [comment]
Hrm, since we're using native contexts now, CodeClimate can find more context-related issues and is failing here:

https://codeclimate.com/github/prometheus/prometheus/pull/3333

All issues around context cancellation, but I don't think they're all real (e.g. the notifier one doesn't seem to be). I haven't had a look at CodeClimate yet, do you happen to know what to do in this case? CodeClimate shows @beorn7 as the user for the integration in GitHub here...

**Comment by beorn7** [comment]
I introducted CodeClimate as an experiment a while ago, and the only easy way I saw back then was to use my own user as the one granting permissions and such. Thus, my face shows up there.

We have Codacy now, too, and I'm sure others played with several other tools as well. We should decide at some point which tools we want to have, and then create some consistency across repos. I'm not in a position to drive that right now, though.

If you find CodeClimate un-helpful, feel free to remove it. No emotional or other attachment to it from my side. However, should the problem it exposed here be real, it would be pretty awesome.

**Comment by juliusv** [comment]
> If you find CodeClimate un-helpful, feel free to remove it. No emotional or other attachment to it from my side. However, should the problem it exposed here be real, it would be pretty awesome.

The reported problems are just `go vet` results, and we know that those also provide false positives at times. That seems to be the case here. So I'll remove CodeClimate.

**Pull request merged**
