### PR TITLE
remote: don't set highestSentTimestamp to 0

### PR DESCRIPTION
**Pull request by roidelapluie**
Alternative to #8046 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by bwplotka** [comment]
Hm tricky one. I think I like the dashboard fix more than this. The problem here is that we are lying here - no remote write happened.


What about registering this on first write only? This way it will solve the problem by also not confusing. Normally we initialize metrics to 0 for labels, but it's mainly needed for counters / gauges. Timestamp based metrics are much different. WDYT?

**Comment by roidelapluie** [comment]
> Hm tricky one. I think I like the dashboard fix more than this. The problem here is that we are lying here - no remote write happened.
> 
> What about registering this on first write only? This way it will solve the problem by also not confusing. Normally we initialize metrics to 0 for labels, but it's mainly needed for counters / gauges. Timestamp based metrics are much different. WDYT?

I 100% agree with you.

Registering only when we send is also hard because we also unregister those metrics. While technically this would be valid, what would happen if we register the gauge before the register() is called on the queue manager?

I think the dashboard fix seems better.

**Comment by csmarchbanks** [comment]
I think we should do the dashboard fix for sure for older versions. IMO this would be in addition to that if we choose to do it.

I agree that lying is not good. We could have that gauge set to nil, and only create & register it on first sample sent? Then do a nil check when unregistering that gauge?

**Comment by roidelapluie** [comment]
#8060 was better

**Pull request closed without merging**
