### PR TITLE
Add AlertManagers' url to "Service Discovery" page.

### PR DESCRIPTION
**Pull request by mrasu**
For https://github.com/prometheus/prometheus/issues/3843, add AlertManagers' url to "Service Discovery" page.

I add only url found by service discovery because `alertmanager` expose only `url()`
If there is other information useful, I will add.

This iscurrent page.
image

Signed-off-by: mrasu <m.rasu.hitsuji@gmail.com>

### CODE REVIEW

**Comment by simonpasquier** [comment]
This is only duplicating what already exists in the /status page. If I understand the original issue correctly, the goal is to display all discovered AlertManager instances including those which are dropped by relabeling.

**Comment by mrasu** [comment]
Thanks, I didn't realize it. I will change

**Comment by mrasu** [comment]
@simonpasquier changed!

**Comment by mrasu** [comment]
@simonpasquier Can I ask you to look again?

**Comment by mrasu** [comment]
Sorry, I'm busy and I don't have time to do more right now. So I close it.
Sorry about it.

**Comment by simonpasquier** [comment]
@mrasu no need to be sorry. Thanks for the effort!

**Pull request closed without merging**
