### PR TITLE
Avoid browser's spell-checking the Expression field

### PR DESCRIPTION
**Pull request by ariya**
@juliusv

Signed-off-by: Ariya Hidayat <ariya.hidayat@gmail.com>

### CODE REVIEW

**Comment by ariya** [comment]
This gets rid of the red squiggly line. The difference is as follow.

**Before** the change:
image

**After**:

image

**Comment by juliusv** [comment]
:+1: Awesome, thanks!

**Comment by juliusv** [comment]
Could you run `make assets` to rebuild the assets?

**Comment by ariya** [comment]
> Could you run `make assets` to rebuild the assets?

Done (and amended to keep the commit atomic). Thank you!

**Comment by simonpasquier** [comment]
@ariya you've got a conflict with `web/ui/assets_vfsdata.go` so you need to rebase on master and run `make assets`. Sorry for the inconvenience!

**Comment by ariya** [comment]
Rebased on the latest master.

**Comment by ariya** [comment]
Rebased again on the latest master.

**Pull request merged**
