### PR TITLE
WIP For prombench run - Share string interner between scrape cache and remote_write

### PR DESCRIPTION
**Pull request by tpaschalis**
This PR contains the same code as #10231, with just the instances of the `UseSharedInterner` feature flag set to true. We'd like to have prombench run and be able to quantify performance differences of using the internet to the rest of Prometheus' components.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Note: prombench does not use remote write

**Comment by csmarchbanks** [comment]
As I stated [here](https://github.com/prometheus/prometheus/pull/10231#issuecomment-1068221591) I want to know the effect on performance of the scrape path without remote write. I am not looking for, or expecting a performance improvement in the benchmark, rather making sure there isn't a significant regression.

Looking at the graphs the performance looks interesting. Allocations are 10-15% higher. CPU is roughly the same, but 15 minute load looks to be consistently a bit higher, not sure what would be causing that. Overall memory usage looks to be down ~7% which is quite nice.

**Comment by tpaschalis** [comment]
One "side-effect" in this PR is changing the key type for the seriesCur/seriesPrev maps, from `labels.Labels` to `*cacheEntry`, which might also play a role in the more allocations/lower memory usage.

Should I roll back this specific change (it's only a few lines) to focus solely on the effect of the interner?

**Comment by tpaschalis** [comment]
@csmarchbanks I've opened a second WIP PR in #10460, where I've reverted the change of using `*cacheEntry` for seriesCur/seriesPrev as map keys.

Do you think it's a good idea to start a prombench run there as well? It should be a clearer opportunity to see the performance tradeoff of the shared interner in isolation.

**Pull request closed without merging**
