### PR TITLE
SampleRingIterator: add currType field

### PR DESCRIPTION
**Pull request by duricanikolic**
This PR introduces an additional field `currType` in `storage.SampleRingIterator`. This field is used for checking whether the current type of the iterator is consistent with calls to `At()`, `AtHistogram()` and `AtFloatHistogram()`.

This field, additionally, fixes a bug discovered in `storage.SampleRingIterator.AtFloatHistogram()`. Namely, if the current value of the iterator is of type `chunkenc.ValHistogram` (and therefore supposed to be stored in the field `h`), but previously the iterator held a value of type `chunkenc.ValFloatHistogram` (and therefore cached in the field `fh`), the latter will be preferred over the former, so `storage.SampleRingIterator.AtFloatHistogram()` used to return a wrong value.

### CODE REVIEW

**Comment by beorn7** [comment]
I pushed another commit. WDYT?

**Comment by duricanikolic** [comment]
> I pushed another commit. WDYT?

That was also something I was evaluating, but I wasn't sure whether we maybe want to keep the histograms and float histograms to avoid new allocations (e.x., [here](https://github.com/prometheus/prometheus/blob/583f3e587cf7b8f94b325ae72906815d5be480f4/storage/buffer.go#L384-L387)) @fpetkovski

**Comment by beorn7** [comment]
I would assume that the resets happen way less frequently than accesses, so that nil'ing out the histogram pointers doesn't really make a dent. Practice have to tell, of course, but I would go down the simpler route until it's proven that there is a relevant performance loss.

**Comment by beorn7** [comment]
And actually, I don't even think the optimization applies here. We are recycling the histogram we are passing in, not the histogram that was in the iterator before.

**Comment by fpetkovski** [comment]
Looks like `Reset` happens once per series, so I assume this should not be too expensive. We have a benchmark that we can run https://github.com/prometheus/prometheus/blob/main/promql/bench_test.go#L293 and compare to the main branch.

**Comment by duricanikolic** [comment]
> And actually, I don't even think the optimization applies here. We are recycling the histogram we are passing in, not the histogram that was in the iterator before.

I am OK if we go this way.

**Comment by beorn7** [comment]
The lint warning is for old code, not sure why it shows up suddenly.

@duricanikolic if you mark this as "ready for review", I can approve and merge it.

**Review by beorn7 — APPROVED** [review]

**Comment by bboreham** [comment]
Please, if you change the meaning of a PR, also change the title.

**Comment by beorn7** [comment]
Indeed. Sorry for missing that.

**Pull request merged**
