### PR TITLE
otlptranslator: fix up import paths

### PR DESCRIPTION
**Pull request by jcajka**
Fix up inline import paths. These get ignored most of the time by the Go module based tooling, but GOPATH based tooling expects it to match the real import path.

### CODE REVIEW

**Comment by machine424** [comment]
This is intentional actually, as the files are `COPIED AS-IS` as mentioned in the header and we want the imports to use that path. See https://go.dev/doc/go1.4#canonicalimports and https://github.com/prometheus/prometheus/tree/main/storage/remote/otlptranslator#copying-from-opentelemetryopentelemetry-collector-contrib
What's exactly does your tooling complain about?

**Comment by jcajka** [comment]
I don't think that it is intentional, there is shell script that adjusts the import paths for this bit of code https://github.com/prometheus/prometheus/blob/main/storage/remote/otlptranslator/update-copy.sh among other things.

For the record just go test/build running in GOPATH mode not liking it.
```otlptranslator/prometheusremotewrite/helper.go:27:2: code in directory /builddir/build/BUILD/prometheus-2.50.1/_build/src/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheus expects import "github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus"```
 It seems as possible regression since the last bump to this, I haven't bisected it.

**Comment by machine424** [comment]
Maybe I understood it backwards, but the `sed` in that file is only for the `./prometheusremotewrite/*.go` which doesn't cover the 3 files you changed https://github.com/prometheus/prometheus/blob/f1e9ec29f8f7d8c273e8980494be6aca18e1ef6f/storage/remote/otlptranslator/update-copy.sh#L26. Plus the [README](https://github.com/prometheus/prometheus/tree/main/storage/remote/otlptranslator) doesn't seem to be up to date anymore (after https://github.com/prometheus/prometheus/tree/main/storage/remote/otlptranslator, we copy `/.prometheus` as well now)

I'll cc @gouthamve to get a confirmation and the script and the README need to be adapter.
(That would fix the imports)

**Comment by aknuds1** [comment]
> Maybe I understood it backwards, but the sed in that file is only for the ./prometheusremotewrite/*.go which doesn't cover the 3 files you changed

I suspect that update-copy.sh should also fix the import paths in the prometheus/ directory.

**Comment by jesusvazquez** [comment]
Yup! I agreee with @machine424 and @aknuds1 , we probably need to update the script to update all the import paths and dont leave any files behind, maybe those files were introduced later and hence the issue. 

The reason why we do this with the import paths is that the code from the otel contrib repo still is the source of truth. We cant just import it because there is a cycilical dependency so what we do is try to keep prometheus updated with it. This is not the best scenario but until prometheus becomes the source of truth for that code its what we've got.

@jcajka maybe you'd like to update the script to sed all the imports properly instead?

**Comment by jcajka** [comment]
I believe that this is the case that the package should be used just under one import path(the canonical one) per the https://go.dev/doc/go1.4#canonicalimports.
Ack, I will fix up the script and I guess the README too, along with the import paths.

**Comment by jcajka** [comment]
Done. Tested by running the script, creates no changes to the tree for me locally.

**Review by aknuds1 — APPROVED** [review]
LGTM!

**Review by gouthamve — APPROVED** [review]
LGTM

**Comment by gouthamve** [comment]
Thanks for your contributions @jcajka!

**Comment by jcajka** [comment]
Thank you all for quick review and feedback

**Pull request merged**
