### PR TITLE
storage: Correctly increase prometheus_local_storage_open_head_chunks

### PR DESCRIPTION
**Pull request by beorn7**
@brancz @fabxc Your 1.6 server was so strongly affected by this because it wasn't ingesting anything for a while, so a lot of head chunks got closed. Then it crashed, and after that, started to append samples to many series that had a closed head chunk. In general, it's a rare event that a series with a closed head chunk gets new samples.

### CODE REVIEW

**Comment by beorn7** [comment]
Fixes #2687 .

**Comment by fabxc** [comment]
Maybe dumb question, but this fixes an increment of a Prometheus gauge. Gauges from client_go can generally not be read, so how does this play into the feedback loop for the 1.6 target heap size? Are we scraping ourselves?

Or was it really just a metric issue?

**Comment by beorn7** [comment]
> Or was it really just a metric issue?

Yes. 

The 1.6 feedback loop works with the current heap size and with the target heap size for the next GC cycle.

**Comment by fabxc** [comment]
Ah okay, I somehow had the impression from the comments that this caused us to scale some things wrong internally.

👍

**Pull request merged**
