### PR TITLE
Check for unused vendored packages

### PR DESCRIPTION
**Pull request by krasi-georgiev**
usnig govendor to check for unused packages

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
@brian-brazil , @SuperQ all green

**Comment by brian-brazil** [comment]
Is this our canonical Makefile or is it the one in promu we should be changing first?

**Comment by krasi-georgiev** [comment]
I will let you decide. this is simply checking the code base doesn't have any unused vendored packages. Similar to the checkstatic and checkstyle

**Comment by krasi-georgiev** [comment]
@brian-brazil  promu seems to do only builds so I think this is not related and should stay here.

**Comment by brian-brazil** [comment]
My point is more that we shouldn't be hand-editing all the Makefiles and letting them drift across repos. We should have one canonical Makefile, and copy it everywhere else. My question is whether the prometheus or the promu Makefile is meant to be the canonical one.

**Comment by krasi-georgiev** [comment]
I makes sense to make this one the source , but how do you think we can auto sync it with the other ones?

**Comment by krasi-georgiev** [comment]
^ @brian-brazil

**Comment by brian-brazil** [comment]
It'd be copied by hand every now and then. I'm more worried by different features/behaviours in different repos than some repos having an old Makefile.

**Comment by krasi-georgiev** [comment]
so maybe put a comment somewhere in the Makefile as a reminder that any reusable parts should be copied from https://github.com/prometheus/prometheus/blob/master/Makefile ?

**Comment by brian-brazil** [comment]
My point is that the entire file should be reusable and always copied from one place.

**Pull request merged**
