### PR TITLE
Add a feature flag to enable the new discovery manager

### PR DESCRIPTION
**Pull request by roidelapluie**
This PR creates a copy of the legacy manager and uses it by default.

It is a companion PR to #9349. With this PR, users can enable the new
discovery manager and provide us with any feedback / side effects that
the new behaviour might have.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
This is a safeguard against things we might have forgotten in #9349. It is optional, I made this PR to gather your opinions @beorn7 @LeviHarrison

**Comment by LeviHarrison** [comment]
Definitely, a change this big to something as core as the discovery manager should be put behind a feature flag.

**Comment by LeviHarrison** [comment]
> I however want to get feedback from some users about this and see if we forgot some cornercases.

Yup, that's what I mean.

**Comment by roidelapluie** [comment]
> I'm not familiar enough with the discovery code to comment on it in depth.
> 
> I'm not opposed to using feature flags for this kind of "trial run" (if that was the question you wanted me to answer).

Yes that was it. Thank you :)

**Comment by roidelapluie** [comment]
I have addressed the comments

**Pull request merged**
