### PR TITLE
Change bounds for WALSegmentSize flag value

### PR DESCRIPTION
**Pull request by afnanenayet**
This allows the flag sets `WALSegmentSize` to be negative, which allows the user to disable the WAL. I saw that in tsdb/db.go:60 there is a comment stating that setting the segment size to anything less than zero will actually disable the WAL, but in the main file, the flag is restricted to a value between 10 and 256 MB. I wanted to expose this setting through the flag because the WAL can use a significant amount of RAM and for some users I think it may be worth disabling the WAL to avoid the OOM crash cycle as described in this comment: https://github.com/prometheus/prometheus/issues/5560#issuecomment-537210222

### CODE REVIEW

**Comment by brian-brazil** [comment]
I don't think this is something we should expose, in fact with the current
code I don't think we need this flag at all.

**Comment by afnanenayet** [comment]
I apologize because I think I may have been unclear and framed this as an addition rather than a bugfix (not trying to add a new flag or anything).

We can see here that the `WALSegmentSize` value already accepts negative numbers to disable the WAL, and I just wanted to update main so it accurately reflects the WAL settings since it is already documented in the WAL options and it seems like the command line flag doesn't accurately reflect that.

https://github.com/prometheus/prometheus/blob/5f1be2cf455409d3577ac9ddb43144ec2d39c90b/tsdb/db.go#L59-L62

**Comment by brian-brazil** [comment]
It's not sane to run the Prometheus binary without a WAL, and if you're OOMing at startup you were going to OOM anyway.

**Comment by afnanenayet** [comment]
Gotcha, makes sense. Closing

**Pull request closed without merging**
