### PR TITLE
Add '--run' flag to promtool test rules

### PR DESCRIPTION
**Pull request by machadovilaca**
When developing unit tests for rules it would be helpful to be able to run only a single group and avoid testing all test groups in a single file.
This PR adds a new `--run` flag to `promtool test rules` that allows users to pass multiple regular expressions to filter the test groups that will be run based on their names.

### CODE REVIEW

**Comment by machadovilaca** [comment]
@dgl are you able to take a look at this?

**Comment by roidelapluie** [comment]
Can we find a more intuitive name for the flag?

**Comment by roidelapluie** [comment]
maybe --run, like go test?

**Comment by roidelapluie** [comment]
Hi @machadovilaca , we looked at this during our bug scrub, would you like to continue working on this pull request and update the flag name to `--run`? Thanks!

**Comment by machadovilaca** [comment]
@roidelapluie Hi, I've been a little short on time, thanks for the reminder and I'll make sure I take 10min to update the PR this week.

**Comment by machadovilaca** [comment]
@roidelapluie ping

**Review by roidelapluie — APPROVED** [review]

**Review by bwplotka — APPROVED** [review]
Thanks! LGTM 💪🏽

**Pull request merged**
