### PR TITLE
Remove unnecessary sort

### PR DESCRIPTION
**Pull request by damnever**

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @bboreham

**Comment by bboreham** [comment]
On what do you base the statement that this is "unnecessary"?

**Comment by bboreham** [comment]
Oh it's also sorted in `New` ?

**Comment by roidelapluie** [comment]
func New(ls ...Label) Labels {
	slices.SortFunc(ls, func(a, b Label) bool { return a.Name < b.Name })

**Comment by bboreham** [comment]
The parallel function in `labels_string.go` can have the same change.

**Comment by bboreham** [comment]
BTW both versions are also doing an unnecessary allocation.  I think it doesn't matter because they are only used in tests.

**Comment by damnever** [comment]
> The parallel function in labels_string.go can have the same change.

Are you talking about this?https://github.com/prometheus/prometheus/blob/435b500de73dec7caa8241b17e42783cc6706739/model/labels/labels.go#L378-L389

I think this may be intentional.

> BTW both versions are also doing an unnecessary allocation. I think it doesn't matter because they are only used in tests.

Some detailed "Doc comments" would be nice to have.

**Comment by roidelapluie** [comment]
the second one does not call New indeed.

**Comment by bboreham** [comment]
Sorry I misread where your change was proposed.
I think I'll stop commenting on this PR.

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
