### PR TITLE
Update dependencies for 2.42

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

### CODE REVIEW

**Comment by kakkoyun** [comment]
CI failures related to https://github.com/prometheus/prometheus/pull/11860

**Comment by kakkoyun** [comment]
Reverted Azure SDK upgrade. It's more involved and needs to be tested. See #11860

**Review by roidelapluie — APPROVED** [review]
LGTM

**Review by bwplotka — APPROVED** [review]
Thanks!

**Pull request merged**
