### PR TITLE
Add PromQL syntax text with tabs, spaces, trailing commas, singlequotes

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'd suggest a comment that some of these are tabs/spaces. Otherwise it might get auto-formatted away at some point - might even be worth testing these ones in Go rather than here.

**Comment by slrtbtfs** [comment]
You might want to include some test with backquotes, too.

**Comment by brian-brazil** [comment]
I guess some weird unicode quotes while we're at it too.

**Comment by roidelapluie** [comment]
OK I will work on that in the coming days

**Comment by roidelapluie** [comment]
Most of this is actually already covered now.

**Pull request closed without merging**
