### PR TITLE
Bump version for 2.48.0-rc.1

### PR DESCRIPTION
**Pull request by LeviHarrison**
Signed-off-by: Levi Harrison <git@leviharrison.dev>

Forgot to bump the version in the `VERSION` file in #13028.

Also if someone else with admin doesn't mind merging this once it's ready, I can't because of the broken check.

### CODE REVIEW

**Comment by bboreham** [comment]
Do you need to do all the GUI files too?

**Comment by roidelapluie** [comment]
Yes

**Comment by LeviHarrison** [comment]
Whoops, sorry, forgot about that too

**Comment by juliusv** [comment]
:+1:

**Review by Nexucis — APPROVED** [review]

**Comment by LeviHarrison** [comment]
Just waiting on a merge here because I can't

**Comment by juliusv** [comment]
Hmm, the "Build Prometheus for all architectures" CI check is still in the state "Expected — Waiting for status to be reported" but I'm not sure why. If I go to https://github.com/prometheus/prometheus/actions/runs/6654964167 it looks like it has completed and the time that GitHub displays for it when I hover over the "Triggered via pull request yesterday" text matches the timestamp of your last force push. Maybe some GitHub glitch? Should I just ignore and merge? :)

**Comment by LeviHarrison** [comment]
Yeah, it's been broken for a while, which we should take a deeper look at. But for now, we've just been force merging these.

**Comment by juliusv** [comment]
Ah ok, merging then!

**Comment by LeviHarrison** [comment]
Thanks so much!

**Pull request merged**
