### PR TITLE
Parse custom step parameter correctly.

### LINKED ISSUE #2827: Bug: Unable to modify resolution in graph view
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**

Was showing a colleague how to use Prometheus. We have small blips in the data which are normal, but which you can't see unless you bump the resolution to something like 60s. However in doing this Chrome crashes outright, and firefox complains about a script dying.

**What did you expect to see?**

Finer data in the graph

**What did you see instead? Under which circumstances?**

He's dead, jim

**Environment**

https://hub.docker.com/r/prom/prometheus/

1.7 tag

* System information:

```
Linux 4.4.35+ x86_64
```

* Prometheus version: 
```
prometheus -version
prometheus, version 1.7.0 (branch: master, revision: bfa37c8ee39d11078662dce16c162a61dccf616c)
  build user:       root@7a6329cc02bb
  build date:       20170607-09:43:48
  go version:       go1.8.3
```

Some information not included as I don't think it's relevant. Can post anything else you neeed here also.

### PR DESCRIPTION
**Pull request by AlekSi**
We could use parseDuration, but this will require
more changes.

Fixes #2827.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you run `make assets` please?

The hint on this field says it's seconds, so this is fine.

**Comment by AlekSi** [comment]
I'm on macOS, so diff contains a lot of changes from `os.FileMode(436)` to `os.FileMode(420)`. Is it ok?

**Comment by AlekSi** [comment]
Added the only relevant change.

**Comment by brian-brazil** [comment]
You removed the change to the file contents. I don't think the mode makes a difference.

**Comment by AlekSi** [comment]
Done.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
