### PR TITLE
Unnecessary go routine spawn.

### PR DESCRIPTION
**Pull request by LasTshaMAN**
I've been studying `prometheus` code base, and have noticed that there is no need to create a new `go routine` in this piece of code. This PR removes it. 

Though this doesn't really have much of an impact, I hope to make this my first contribution to `prometheus` repository :)

### CODE REVIEW

**Comment by brian-brazil** [comment]
Nice spot. Can you add the DCO?

**Comment by roidelapluie** [comment]
I guess L190 too then

**Comment by LasTshaMAN** [comment]
> Can you add the DCO?

Yep, done.

> I guess L190 too then

Sorry @roidelapluie, I didn't quite get what `L190` is, can you elaborate ?

**Comment by roidelapluie** [comment]
Sorry, line 490 :)

**Comment by LasTshaMAN** [comment]
> Sorry, line 490 :)

I think we shouldn't do this for `line 490` cause we'll block in that case resulting in sequential execution of this loop:
```go
for _, l := range uniqueLoops {
		if l != nil {
			go l.run(interval, timeout, nil)
		}
}
```

while in `line 376` we've already spawned a `go routine` and just letting it go & creating a separate one looks like a waste ...

**Comment by LasTshaMAN** [comment]
I've removed `line ` as well, it also looks unnecessary.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
