### PR TITLE
Release 2.17.2

### PR DESCRIPTION
**Pull request by roidelapluie**
The goal is to get the different pull request merged over the week end or Monday; and do the release on Monday.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by bwplotka** [comment]
Prombench error:

```
19:47:36 provider.go:47: Request for 'applying deployment:promtail-pr-7139' is in progress. Checking in 10s
19:47:46 provider.go:47: Request for 'applying deployment:promtail-pr-7139' is in progress. Checking in 10s
19:47:46 gke.go:568: error while applying a resource err:error applying 'manifests/prombench/benchmark/3c_promtail-bench_deployment.yaml' err:Request for 'applying deployment:promtail-pr-7139' hasn't completed after retrying 50 times
make: *** [Makefile:19: resource_apply] Error 1
```

What's the procedure in such cases @krasi-georgiev maybe? Should we retry?

**Comment by roidelapluie** [comment]
Prombench is broken. On the other hand I think the bugs fixed here are important enough not to delay the release, I still plan to release tomorrow unless someone objects.

**Comment by brian-brazil** [comment]
Sounds fine to me.

**Comment by krasi-georgiev** [comment]
> Prombench error:
> 
> ```
> 19:47:36 provider.go:47: Request for 'applying deployment:promtail-pr-7139' is in progress. Checking in 10s
> 19:47:46 provider.go:47: Request for 'applying deployment:promtail-pr-7139' is in progress. Checking in 10s
> 19:47:46 gke.go:568: error while applying a resource err:error applying 'manifests/prombench/benchmark/3c_promtail-bench_deployment.yaml' err:Request for 'applying deployment:promtail-pr-7139' hasn't completed after retrying 50 times
> make: *** [Makefile:19: resource_apply] Error 1
> ```
> 
> What's the procedure in such cases @krasi-georgiev maybe? Should we retry?

Please ping @geekodour as he is the Prombench maintainer now :)

**Pull request merged**
