### PR TITLE
release 2.4.2

### PR DESCRIPTION
**Pull request by gouthamve**
Update vendor properly this time.

### CODE REVIEW

**Comment by gouthamve** [comment]
@SuperQ @krasi-georgiev @brian-brazil

**Comment by gouthamve** [comment]
Looks like this is a serious issue: https://github.com/prometheus/prometheus/issues/4635

I ran `2.3.2` then `2.4.0/1` and both hit this:
err="opening storage failed: open e:\prometheus-data\wal\00000002: The system cannot find the file specified."`

I'm deferring the release until this is fixed.

**Comment by krasi-georgiev** [comment]
@gouthamve btw I have done a wiki page for a reminder to myself how to update a vendored package.
https://github.com/prometheus/prometheus/wiki/Updating-a-vendored-package

**Comment by gouthamve** [comment]
@krasi-georgiev @brian-brazil @juliusv @fabxc @simonpasquier @grobie 

This pulls in the WAL migration and corruption bugfixes from prometheus/tsdb.

**Comment by gouthamve** [comment]
Fixes #4635

**Comment by grobie** [comment]
LGTM

**Pull request merged**
