### PR TITLE
Console graph color scheme support

### PR DESCRIPTION
**Pull request by alin-amana**
Add a colorScheme parameter to PromConsole.Graph, to allow using custom colors in console graphs. Can be either a list of hex color codes (e.g. ['#ff0000', '#00ff00', '#0000ff']) or one of the color scheme names supported by Rickshaw (e.g. 'spectrum2000').

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you do a `make assets`?

**Comment by alin-amana** [comment]
Done, wasn't sure I needed to include that too.

**Comment by alin-amana** [comment]
Forgot to mention this was tested locally, with (1) no explicit value, (2) list of hex codes and (3) Rickshaw color scheme name. No errors in Chrome's console, everything looked as expected.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by alin-amana** [comment]
Thank you.

Question: should I also update the docs with the new parameter?

**Comment by brian-brazil** [comment]
Yes please, in the next-release branch.

**Pull request merged**
