### PR TITLE
tracing: add tcp events to remote store span

### PR DESCRIPTION
**Pull request by jmichalek132**
When debugging latency issues between prometheus and backend it's remote writing to (especially latency issues due to dns / network, etc) having bit more details in the tracing data for remote write would be really helpful.

Example from locally running what details this adds to the tracing.

image

image

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks. I think it is useful. 

It looks similar to what is provided by https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace; is there a reason to avoid that one?

**Comment by jmichalek132** [comment]
> Thanks. I think it is useful.
> 
> It looks similar to what is provided by https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace; is there a reason to avoid that one?

I will look into updating the PR using that option. Thank you for the suggestion.

**Comment by jmichalek132** [comment]
image
Trace with https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace

**Comment by bboreham** [comment]
I much prefer it with events rather than sub-spans, both for data volume and for screen real-estate reasons. 

I believe there is an option to do that in the library.

**Comment by jmichalek132** [comment]
> I much prefer it with events rather than sub-spans, both for data volume and for screen real-estate reasons.
> 
> I believe there is an option to do that in the library.

Hi, thank you for the feedback I think that makes sense, I updated the PR and this is how it looks with only span events.

image

**Review by bboreham — APPROVED** [review]
LGTM

**Comment by bboreham** [comment]
Please squash commits when they backtrack and take an alternative approach.

**Comment by jmichalek132** [comment]
> Please squash commits when they backtrack and take an alternative approach.

Will do next time, thank you for the feedback.

**Comment by bboreham** [comment]
Sorry, the comment was for Bartek; it’s an option available when merging.

**Pull request merged**
