### PR TITLE
Merge the 2.13 release branch

### PR DESCRIPTION
**Pull request by krasi-georgiev**

### CODE REVIEW

**Comment by beorn7** [comment]
Hmm, I would just merge the prometheus:release-2.13 branch into prometheus:master. But here you are merging one of your own branches.

**Comment by beorn7** [comment]
I see, there are merge conflicts...

**Comment by krasi-georgiev** [comment]
I tried in https://github.com/prometheus/prometheus/pull/6167 , but there is was a merge conflict so need to create another branch to resolve the conflict

**Comment by beorn7** [comment]
But why are there so many more commits in here?

Let me try something...

**Comment by krasi-georgiev** [comment]
fixed it

**Comment by beorn7** [comment]
I see. Now your attempt and mine (#6171) look the same. :+1: here and I'll remove my own PR.

**Pull request merged**
