### PR TITLE
Kubernetes SD: disable resync timer

### PR DESCRIPTION
**Pull request by JensErat**
## The Issue and Change

While originally the resync period also forced refreshing from Kubernetes API server, this [has been removed for some years now because watching the API server got more stable][1]. Today, this just results in all entities being sent to the service discovery again, which is valid from a general Prometheus perspective, but results in unnecessary CPU load and also breaks service discovery metrics. In especially, this makes monitoring "do we actually observe changes from Kubernetes API server" impossible (receiving constant updates from Kubernetes service discovery is a pretty valid assumption, for example nodes get frequent status updates, ...). I guess this actually is nothing more than a left-over from the very early times of Kubernetes and Prometheus (pre Kubernetes 1.3), where the resync period actually periodically relisted items from the API server and using it was considered good practice.

Today, it should only be required (and used) for applications that sporadically might miss events and "eventually repair" their state by retrying this way.

**I assume this change is safe**, because

- the resync timer doesn't pull updates from Kubernetes anyway, ie. will not fetch up "missed" changes because of a broken watch, ...
- while the Prometheus code well supports resending service discovery updates, it does not require them and should never miss changes from my understanding of the code.

[1]: https://github.com/kubernetes/kubernetes/pull/24142

This would also replace #11726, which was another approach I considered for providing the monitoring we require.

## Considerable Alternatives

- client-go's approach in discriminating between refreshed and really new changes is by comparing the `.metadata.resourceVersion` field. We could store this as a service discovery label, but this does not really feel appropriate and will change quite often, especially for nodes.
- Accepting that the `prometheus_sd_kubernetes_events_total` metrics is kind of broken and using something else for monitoring. We actually did so (until now), and checked the HTTP client error rate. Sadly, this isn't really going well: there is a single metrics for all discovery targets, and HTTP requests tend to be quickly retried during outages, such that the error rate well spikes even for just some network flakiness (while successful requests are long-lasting and infrequent). Paging on such information results in mostly false positives.
- We might make the constant configurable, which was proposed already. As discussed above, I don't really see a reason in having the resync anyway and it just confuses users (eg. #4984, also has a PR for such a configuration value attached).
- In my opinion, the best solution (which requires changes to the Kubernetes code base though) would actually be a feature in client-go similar to the `HasSynced() bool` function, which provides constant information on the informer's sync state. This is not available in Kubernetes though, and a [change request was automatically closed and never really draw lots of atttention](https://github.com/kubernetes/kubernetes/issues/57074). We might then pass this as new Kubernetes service discovery metrics.

## Test Series With Explanation

I ran a test series with variants of Kubernetes API server running/shut down and with and without my patch. We're now running a bunch of development clusters with this configuration over the christmas holidays to analyze any potential impact on stability.

### Original behavior

This test shows the original behavior. One can well observe the large number of events received from the informer cache every 10 minutes. In-between, there are some minor changes (like cron jobs, node updates, ...). This small number is gone once the API server is shutdown (simulating an outage), but the 10-minutes-refresh-events still occur.

prom-apiserver-shutoff-without-patch

### Patched Prometheus, running API Server

During this test, I rolled out the patched Prometheus image disabling the resync period (when the large spike happened, as the restarted Prometheus had to load all entities again. Afterwards, only the expected small number of changes is left.

prom-apiserver-running-with-patch

### Patched Prometheus, shut-off API server

Here, I actually performed two changes: first, I rolled out the patched release (stopping the refresh bursts), then I shut off the API server. The Kubernetes SD event counter metrics dropped to exactly 0 as expected. After I restarted the API server, service discovery pretty much immediately started working again, receiving new updates.

prom-apiserver-shutoff-with-patch

<sup>Jens Erat <jens.erat@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>

### CODE REVIEW

**Review by bboreham — COMMENTED** [review]
Thanks for this; I agree we should disable it.

I might rename the constant to something like `resyncDisabled`; this would make it clear at every point of use.

And I feel the comment is too long; something like "Disable the informer's resync period. The resync period just periodically sends all cached events again which has no value." would suffice.  Background info, like the effect on metrics, can go in the git commit description.

**Comment by JensErat** [comment]
Thank you for the quick review.

> And I feel the comment is too long; something like "Disable the informer's resync period. The resync period just periodically sends all cached events again which has no value." would suffice. Background info, like the effect on metrics, can go in the git commit description.

I agree (the discussion is included in the comment anyway already). I really like the idea of renaming the constant, I guess this will already replace half of the comment's length. I'm out of office right now, but will soon provide the proposed update.

**Comment by JensErat** [comment]
@bboreham I just pushed an updated commit, renaming the constant helped stripping down the comment to a single line.

**Review by bboreham — APPROVED** [review]
LGTM, thanks!

**Comment by brancz** [comment]
lgtm thank you!

**Pull request merged**
