### PR TITLE
Update prometheus/client_golang and prometheus/tsdb modules

### PR DESCRIPTION
**Pull request by beorn7**
Promtool test is failing. I still have to look into it.

Wanted to put this out already. Perhaps it's a known issue for somebody.

### CODE REVIEW

**Comment by simonpasquier** [comment]
LGTM

**Comment by beorn7** [comment]
@krasi-georgiev I'm fairly sure this is because the API cilent is now using POST. Is that intended/ok? If so, I'll adjust the test.

**Comment by beorn7** [comment]
Test fixed. It should pass now.

**Comment by beorn7** [comment]
I'll merge to get more time with the dependency updated (before cutting the RC).
@krasi-georgiev if my assumptions here are wrong, please let me know and we can rectify things.

**Pull request merged**
