### PR TITLE
go.mod: update github.com/prometheus dependencies

### PR DESCRIPTION
**Pull request by roidelapluie**
Except common, which is handled in #6661 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
go get -u github.com/prometheus/client_golang
go get -u github.com/prometheus/alertmanager
go get -u github.com/prometheus/client_model
go mod tidy
go mod vendor

**Comment by brian-brazil** [comment]
We generally do this just before a release. Is there a particular one you're looking for?

**Comment by roidelapluie** [comment]
I was doing common for #6661, we are just one week off release, and it was not done for 2.15.  While I was as it, I did it.

**Comment by brian-brazil** [comment]
@cstyan this is yours then.

**Comment by cstyan** [comment]
I missed this, do you want me to put this into a 2.16.0-rc.1?

**Comment by beorn7** [comment]
I'd say let's only do the update and a second RC if we have reasons to believe an update is necessary.

For the routine dependency update alone, I wouldn't do a separace RC. Should the rc.0 have a bug and we have to do an rc.1 anyway, then I would also include the dependency update.

**Pull request closed without merging**
