### PR TITLE
Promql: Add clarifying note to Point.MarshalJSON

### PR DESCRIPTION
**Pull request by beorn7**

### CODE REVIEW

**Comment by juliusv** [comment]
:+1:

**Comment by roidelapluie** [comment]
Should we add tests for this method to prevent further removals?

**Comment by beorn7** [comment]
I think this note is more effective than a unit test. If a unit tests tests something that is used nowhere, it will be as confusing, and it can be removed as easily as this method.

**Comment by beorn7** [comment]
I'll merge this now to avoid further confusion. This doesn't prevent us from adding a unit test in addition, should we decide that it is desired.

**Pull request merged**
