### PR TITLE
add supoort k8sdiscovery via kubeconfig

### PR DESCRIPTION
**Pull request by 3Xpl0it3r**
Signed-off-by: 3Xpl0it3r <shouc.wang@hotmail.com>

add support discovery k8s via kubeConfig file

when I run prometheus out of kubernetes cluster, if I want to discovery I must config credentials and credentials_file, and in this way is very convenient. But use kubeConfig is very convenient.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you for this.

A few op level comments:

- I am not fully qualified to say if we want to support this in Prometheus. @brancz can you please express your opinion?
- I think kube config can contain multiple configurations, so we should probably have some parameters to determine which config we want to use (maybe use kubeconfig as a struct ?)
- This pull request contains unrelated changes in .gitignore and some metrics changes.
- This pull requests lacks documentation and tests.

**Comment by roidelapluie** [comment]
It also seems that some commits have bad authorship: @gouthamve does not seem to have worked on this but their name is in the commits.

**Comment by 3Xpl0it3r** [comment]
@roidelapluie 
about the second point, yean ,kube config contain multiple configure, and the way that add parameter to determine which context it used  may be more flexible  . But the way that switch context in Kube config I have no good idea,and  I will think it carefully 。
so far ,the context switch can be done with kubectl easily.

**Comment by 3Xpl0it3r** [comment]
@roidelapluie some unexpected metrics I am also confused, I do nothing about metrics, may Goland Ide  add it or some magic  things happened. It's not rigorous, and I am very sorry about this.

**Comment by roidelapluie** [comment]
If you are not familiar with git, you could try the PR again from scratch? We also offer contributor hours on Mondays to provide some help and unblock contributors: https://prometheus.io/community

Thanks!

**Pull request closed without merging**
