### PR TITLE
api: drop legacy API

### LINKED ISSUE #1593: Drop legacy API

### PR DESCRIPTION
**Pull request by fabxc**
Fixes #1593 
Waiting for confirmation from @stuartnelson3 there.

### CODE REVIEW

**Comment by beorn7** [comment]
Isn't the Prometheus CLI using the legacy format?
And wasn't the reason to not just deprecate the Prometheus CLI that the Nagios plugin depends on it?
And wasn't the plan to build query functionality into promtool? That's in progress in https://github.com/prometheus/prometheus/pull/1753 .
But only once that's done, we can port the Nagios plugin and then drop the legacy API.

See also https://github.com/prometheus/prometheus/pull/1601 , the previous attempt to do this.

**Comment by fabxc** [comment]
Okay, can we merge this into master regardless?

**Comment by beorn7** [comment]
My impression was we do not want to break the Prometheus CLI before we have a replacement in promtool and ported the Nagios plugin to promtool.

**Comment by fabxc** [comment]
It's in master and will be completed before the next release. Master is our development branch, breaking there is totally okay.

**Comment by beorn7** [comment]
Sure, but is not merging this PR blocking anything? If avoiding breakage has no cost, I'm for avoiding it.

I'd feel better if could shepherd #1753 into merging ASAP. @fabxc you already looked at it. How far away is it? I'm happy to port the Nagios plugin to promtool once the functionality is there.

**Comment by fabxc** [comment]
It's having many things in the air.

Who knows how far, I made comments and am waiting for a response.
I also mentioned some concerns on how we handle time. So I ultimately expect promtool to not be stable (something we should make clear in our 1.0.0 guarantees).

Might be better to migrate prometheus_cli to APIv1 and keep it around for a bit.
Or... make the Nagios plugin talk the the API directly. Should be not too much overhead with `curl` and `jq`. How about that?

**Comment by beorn7** [comment]
> Might be better to migrate prometheus_cli to APIv1 and keep it around for a bit.
> Or... make the Nagios plugin talk the the API directly. Should be not too much overhead with curl and jq. How about that?

I'll look into that today.

**Comment by beorn7** [comment]
> I'll look into that today.

Fniday is already over (in my timezone), but I'll try my best on Saturday...

**Comment by beorn7** [comment]
https://github.com/prometheus/nagios_plugins/pull/8 is my attempt. I'll run it by @matthiasr to see if the escaping is right. (Worked for a number of cases I tried, but with shell, you never know for sure...)

**Comment by beorn7** [comment]
In any case, we know now the nagios plugin is totally doable with curl and jq, so I believe this can be merged now (assuming you got confirmation from @stuartnelson3 by now).

**Comment by stuartnelson3** [comment]
PromDash no longer uses the legacy API. 👍 to this PR.

**Pull request merged**
