### PR TITLE
support HTTP basic auth

### PR DESCRIPTION
**Pull request by rickypai**
will follow up with tests

### CODE REVIEW

**Comment by rickypai** [comment]
needs https://github.com/prometheus/common/pull/260 first

**Comment by roidelapluie** [comment]
Thank you but we would use the node_exporter tls library for this, which still need some minor tweaks. That should hopefully happen in the coming weeks.

**Comment by mdlayher** [comment]
Closing per https://github.com/prometheus/common/pull/260.

**Comment by shishirkh** [comment]
Hi any update on this. Basically we want to be able to specify username and password inside k8s annotations.
              prometheus.io/password:  pass123
              prometheus.io/username: pass123

**Pull request closed without merging**
