### PR TITLE
Allow injection of arbitrary headers in promtool, for auth etc.

### PR DESCRIPTION
**Pull request by tomwilkie**
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Should we really be putting passwords on the command line?

**Comment by juliusv** [comment]
Btw., there's a bunch of open promtool PRs that add more querying which are waiting for the feature moratorium to end, this will have to be integrated with all of them as well:

https://github.com/prometheus/prometheus/pull/4346
https://github.com/prometheus/prometheus/pull/4308
https://github.com/prometheus/prometheus/pull/4247

**Comment by tomwilkie** [comment]
@juliusv will wait; really want to refactor this a little so server, headers etc can be specified once.  Is the promtool CLI included in out compatibility guarantee?

**Comment by brian-brazil** [comment]
Promtool is not mentioned either way, so breaking changes should be avoided without a good reason I'd say.

**Comment by roidelapluie** [comment]
"As long as you are not using any features marked as experimental/unstable, an upgrade within a major version can usually be performed without any operational adjustments and very little risk that anything will break"

**Pull request merged**
