### PR TITLE
Promote rc.0 to final v2.10.0

### PR DESCRIPTION
**Pull request by beorn7**
No changes required from the RC.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
I made the call to include #5596 (low risk bug fix, added to CHANGELOG in this PR) and #5594 (only example code, not worth mentioning in CHANGELOG) and still promote this to the final release.

Please object if you feel strongly.

**Comment by gouthamve** [comment]
No objections to those additions.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
