### PR TITLE
Update remote storage maintainers to Callum and Chris

### PR DESCRIPTION
**Pull request by juliusv**
Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@csmarchbanks @cstyan

**Comment by brian-brazil** [comment]
Per the dev summit, I'll be redoing this whole file. Hopefully this week.

**Comment by juliusv** [comment]
Ok, should we merge this or leave it then?

In any case, I added @bwplotka for remote read now based on IRC feedback.

**Comment by brian-brazil** [comment]
I don't mind really, it'll go away soon one way or the other.

**Comment by juliusv** [comment]
Ok, will just merge for now.

**Pull request merged**
