### PR TITLE
Don't sync golangci-lint GitHub Action if `Makefile.common` isn't used

### PR DESCRIPTION
**Pull request by LeviHarrison**
If repositories don't use `Makefile.common` we shouldn't enforce additional testing systems.

For example, windows_exporter (see https://github.com/prometheus-community/windows_exporter/pull/833), which doesn't use the Makefile and as a result doesn't run golangci-lint.

### CODE REVIEW

**Comment by roidelapluie** [comment]
is there a way to make windows_exporter pass this?

**Comment by LeviHarrison** [comment]
I guess the errors could be ignored or fixed, but there are also cases like https://github.com/prometheus-community/promql-langserver/pull/226.

**Comment by roidelapluie** [comment]
The promql errors sounds legit and some of them are actually bugs

**Comment by LeviHarrison** [comment]
True, but my point was more that they had already set up the Action, and now repo_sync wants to make them use ours.

**Comment by LeviHarrison** [comment]
Whatever the case, I think we've come to a consensus that we do want to force sync the Action, not dependent on `Makefile.common`, so this can be closed.

**Comment by carlpett** [comment]
I guess we (windows_exporter) could try to make our linting setup mesh better with how this repo does it, but currently the problem is that the runner uses Linux, and for obvious reasons doesn't like the Windows-specific stuff.
This is going to be a blocker to us ever syncing with upstream again, since we'd be getting failing checks on every commit.

**Comment by roidelapluie** [comment]
I will exclude you from the script

**Pull request closed without merging**
