### PR TITLE
Azure: Fix panic when IP Address isn't set

### LINKED ISSUE #10271: Azure SD with Public IP Address: panic: runtime error: invalid memory address or nil pointer dereference
## Version
Docker image `prom/prometheus`, tags `latest` and `main`, both have the same problem.

## Problem
We're receiving a panic from Azure SD plugin whenever it tries to enumerate our VMs. The problem is caused by an incorrect nil check as seen below:

https://github.com/prometheus/prometheus/blob/579331446a04503b2b1515767e7ceaceab2c6342/discovery/azure/azure.go#L374-L376

## Fix
The current code is checking `ip.PublicIPAddress.PublicIPAddressPropertiesFormat` but is dereferencing `ip.PublicIPAddress.IPAddress`. We should nil check `ip.PublicIPAddress.IPAddress` instead.

## Stacktrace
```
Feb 08 17:14:17 prometheus docker[8302]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 08 17:14:17 prometheus docker[8302]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeb0ac1]
Feb 08 17:14:17 prometheus docker[8302]: goroutine 776 [running]:
Feb 08 17:14:17 prometheus docker[8302]: github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh.func1(0xd9bebd0f7c815613, {{0xc00194db80, 0x92}, {0xc001950228, 0x11}, {0xc001950240, 0x11}, {0xc0019726f0, 0x21}, {0xc001a62590, ...}, ...})
Feb 08 17:14:17 prometheus docker[8302]:         /app/discovery/azure/azure.go:375 +0x7a1
Feb 08 17:14:17 prometheus docker[8302]: created by github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh
Feb 08 17:14:17 prometheus docker[8302]:         /app/discovery/azure/azure.go:321 +0xd52
```

### PR DESCRIPTION
**Pull request by LeviHarrison**
See https://github.com/prometheus/prometheus/issues/10271#issuecomment-1033170264

Fixes #10271

### CODE REVIEW

**Comment by LeviHarrison** [comment]
@beorn7 this might be a candidate for a minor release.

**Comment by beorn7** [comment]
Yes, please change the PR to be on top of the release-2.33 branch. We need a bugfix release with #10279 anyway.

**Comment by LeviHarrison** [comment]
Branch changed; apologies for the mass ping;

**Comment by roidelapluie** [comment]
Thanks!!

**Pull request merged**
