### PR TITLE
discovery: kubernetes: Avoid creating unnecessary Kubernetes indexers…

### PR DESCRIPTION
**Pull request by machine424**
… in RoleEndpointSlice

This was due to a missing "return", see https://github.com/prometheus/prometheus/pull/13554#discussion_r1490965817

### CODE REVIEW

**Comment by machine424** [comment]
We can see the test failing on main https://github.com/prometheus/prometheus/actions/runs/7931265848/job/21655128095?pr=13593#step:6:347

**Comment by machine424** [comment]
cc @bboreham

**Review by bboreham — APPROVED** [review]
lgtm

**Comment by beorn7** [comment]
Merging this with @bboreham 's approval. @brancz please shout if you see any issues here.

**Pull request merged**
