### PR TITLE
filter-all-healthy-targets

### PR DESCRIPTION
**Pull request by ghost**
Patch for Issue #5219

### CODE REVIEW

**Comment by smarch2** [comment]
Hi @codesome, PR for review.

**Comment by songjiayang** [comment]
@smarch2 thanks for this PR, It's the thing I really want.

**Comment by jritchieBAE** [comment]
Hi, this PR has been quiet for a long time, could someone from the project a look at accepting it please?

**Comment by roidelapluie** [comment]
Hi @juliusv , can you look at this?

**Comment by roidelapluie** [comment]
Thanks for your work. Somehow we did not review it in time, sorry about that!! It seems that this is for the classic UI, which does not get new changes nowadays. This would need to be implemented for the new react UI.

**Comment by Nexucis** [comment]
looks like the user that open this PR doesn't exist anymore.
We can close this PR, I fixed the issue in https://github.com/prometheus/prometheus/pull/10103

**Pull request closed without merging**
