### PR TITLE
[ENHANCEMENT] remote storage: http json implementation of labelvalues

### PR DESCRIPTION
**Pull request by liguozhong**
[ENHANCEMENT] remote storage: http son implementation of labelvalues

https://github.com/prometheus/prometheus/issues/6124
debug Screenshot
image
config
image
example implement

### CODE REVIEW

**Comment by DeeeFOX** [comment]
This will help my case a lot

**Comment by rinkako** [comment]
+1. label_values interface is essential in some case using remote storage.

**Comment by liguozhong** [comment]
@simonpasquier  
Please help review this PR and help me to confirm if this PR is meaningful to the Prometheus master branch, and if I need to do some code optimization to achieve the standard that can be merged.  thank you very much.

**Comment by liguozhong** [comment]
@simonpasquier 
Is this PR useful? Do I need to close this PR.

**Comment by simonpasquier** [comment]
deferring to @csmarchbanks and @cstyan who are responsible for the remote storage code.

**Comment by csmarchbanks** [comment]
I am also going to ping @bwplotka as he does more with remote read.

**Comment by brian-brazil** [comment]
We looked at this during the bug scrub, and it has been superseded by #7076.

**Pull request closed without merging**
