### PR TITLE
Revert "Merge pull request #1051 from prometheus/globallabels"

### PR DESCRIPTION
**Pull request by juliusv**
This reverts commit d839980fcb3c44db7f90b6238e9b238aba34baae, reversing
changes made to 9ec11b1847b712c33bad90fdbf8db1c7f200f4f2.

See https://groups.google.com/forum/#!topic/prometheus-developers/ziiQ7H-sa9A
for the reasons behind this revert.

Conflicts:
	storage/remote/remote.go
	web/federate.go
	web/web.go

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc @brian-brazil @grobie 

I'm a bit sad to revert this and make global labels useless again, but unless we can quickly make a decision how to address the issues raised in https://groups.google.com/forum/#!topic/prometheus-developers/ziiQ7H-sa9A, we should revert this for now and make a proper decision in 0.17.0 to not break things twice.

**Comment by brian-brazil** [comment]
It's not so much that this makes global labels useless, as it makes federation near to useless.

**Comment by juliusv** [comment]
@brian-brazil I'm all for not reverting this and going forward with a proper fix if we can all agree on one in time for 0.16.0 (ha!). My first idea would be to just rename the global labels config option to `external_labels` and leave it at that. Thoughts?

**Comment by brian-brazil** [comment]
That'd make sense to me.

The other general option is that we will have to offer full metric relabelling support on the external paths, so we could leave it to that (though the federation case is a bit tricker). Given though that I'd expect the `external_labels` setting to cover the vast majority of use cases (many of which are pretty basic), I think not requiring users to use relabelling here would be a tradeoff.

**Comment by fabxc** [comment]
If we can boil it down to that simple change (breaking, unless we want to preserve the current behavior).

@grobie Do you feel that this would make things clearer?

**Comment by juliusv** [comment]
:+1: to me obviously, let's see what @grobie thinks.

**Comment by juliusv** [comment]
Relevant piece to figure out for this discussion: https://github.com/prometheus/prometheus/issues/1128

**Comment by brian-brazil** [comment]
I'm not sure that #1128 applies here, as it requires that users don't aggregate the global labels away. Given that alert writers don't (nominally) even know what the global labels are, using them in alert templates is unwise.

**Comment by juliusv** [comment]
For #1128 I would expect the global labels to be applied to the alerts after the expression evaluation, but before the template expansion. That way you wouldn't be able to aggregate them away. But I'm also fine with not supporting global labels here, as they are static per server anyways and thus not of much use once we got notification templates on the AM side.

**Comment by brian-brazil** [comment]
I think it's one of those ones where we're best off playing it safe and holding off until we see what the advanced use cases are like. I can see alert relabelling logic getting quite funky in some setups, and having that exposed to alert writers could cause confusion at best.

**Comment by grobie** [comment]
I'm totally fine with using `external_labels` as this makes it clear to the user that they behave differently than `labels` in job sections.

**Comment by juliusv** [comment]
Closing this PR here in favor of the rename PR: https://github.com/prometheus/prometheus/pull/1129

**Pull request closed without merging**
