### PR TITLE
Merge fanout module into fanout directory

### PR DESCRIPTION
**Pull request by liguozhong**
Merge fanout module into fanout directory. 
When I was writing the test class, I found that fanout.go was easy to cause the problem of "import cycle", so I created a "fanout" folder. 
This PR is to move fanout from "storage" to "fanout" folder. Otherwise, there will be two files with the same name of "fanout_test.go"

image

### CODE REVIEW

**Comment by brian-brazil** [comment]
This doesn't seem right. How were the tests passing if there was a cycle preventing a build?

**Comment by liguozhong** [comment]
> This doesn't seem right. How were the tests passing if there was a cycle preventing a build?

storage/fanout_test.go->util/teststorage.go.New->storage/storage.Storage
image
image

**Comment by liguozhong** [comment]
> This doesn't seem right. How were the tests passing if there was a cycle preventing a build?

The four methods of fanout.go (add addfast commit rollback) currently have no test classes, which should also be caused by the failure to import "teststorage. Go.New"

**Comment by gouthamve** [comment]
Hi @liguozhong, thanks for the PR, but unfortunately a lot of the code around this has been refactored. Could you see if the change you want is still relevant with the new code? If yes, could you open another PR for it?

**Pull request closed without merging**
