### PR TITLE
Update React vendoring

### PR DESCRIPTION
**Pull request by SuperQ**
`yarn upgrade` all deps.
* Fixe security warning for `serialize-javascript`.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
This causes a bunch of failures in the React tests, so it seems it would require a bit of a deeper look into things.

Alternatively you could try just updating the one package (I think `yarn upgrade serialize-javascript`?).

**Comment by SuperQ** [comment]
Yea, I tried just the minimal upgrade first, but it is's a burred deep dependency, with a major version change. I'll see if I can walk up the tree to see if I can make yarn upgrade just the bare minimum.

**Comment by roidelapluie** [comment]
Does https://github.com/prometheus/prometheus/pull/6831 help?

**Comment by SuperQ** [comment]
Ok, I think I figured out the minimum update chain to fix the security warning.

**Comment by SuperQ** [comment]
Looks like eslint got stricter, will see if I can fix things.

**Comment by SuperQ** [comment]
Looks like there's a couple of additional test failures.

**Comment by SuperQ** [comment]
I fixed up one test fixture.

**Comment by juliusv** [comment]
:+1: Thanks!

**Pull request merged**
