### PR TITLE
promql: Propagate Inspect() errors to the user

### PR DESCRIPTION
**Pull request by juliusv**
...instead of logging them.

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
Note that the tests here are failing because they and the API v1 still expect something around an `ErrStorage` error type, but we never actually ever create errors of that sort anywhere (also not sure how they are currently propagated in the test). That seems broken, will have a look...

**Comment by juliusv** [comment]
(DON'T MERGE)

**Comment by juliusv** [comment]
Aha! The `ErrStorage` error type was only ever used by Cortex (see https://github.com/weaveworks/cortex/search?q=errstorage&unscoped_q=errstorage). The existing test ensures that it is still propagated correctly. So I will have to preserve that... fix incoming.

**Comment by juliusv** [comment]
Ok, so it turns out that the storage errors were already propagated correctly through an `err` variable in the outer function which the `Inspect()` calls close over... this works, but I wonder if it wouldn't be better to not do that kind of convoluted thing and do it by returning the error from `Walk()` instead.

**Comment by brian-brazil** [comment]
Yeah, doing it explicitly is a lot clearer.

**Comment by codesome** [comment]
This seems still relevant. @juliusv could you rebase the PR?

**Comment by juliusv** [comment]
Closing, as it doesn't seem that errors can happen in this path anymore.

**Pull request closed without merging**
