### PR TITLE
Introduce elasticsearch as a remote storage adapter.

### PR DESCRIPTION
**Pull request by Colstuwjx**
Hi team,

As the [user mailist](https://groups.google.com/forum/#!topic/prometheus-users/fAfkBn4HpEY) said, I'd like to introduce the elasticsearch adapter for Prometheus.

Thanks.

### CODE REVIEW

**Comment by Vivian007** [comment]
what the fuck!!

**Comment by Vivian007** [comment]
楼上 +1

**Comment by Colstuwjx** [comment]
Aha, all things clear right now. Ping @juliusv

**Comment by Colstuwjx** [comment]
Any update about this PR? @juliusv @tomwilkie

**Comment by juliusv** [comment]
@Colstuwjx Hey! Exciting that you built an ES remote adapter!

This demo adapter here was meant as example code only, so I'm unsure whether we should make it any more complex by adding more backends to it than it already has (because we have to somehow understand and maintain them all). I think it would make sense to release the ES adapter as a separate open source project that doesn't just live an example directory somewhere, and that gets proper tests and maintenance. Would you be up for that? It would probably live outside of the "prometheus" org to begin with, but maybe we would have an interest in bringing some adapters into the org officially at some point. The same goes for the existing mechanisms btw. (OpenTSDB, InfluxDB, Graphite). We should probably split those out into independent projects at some point too.

**Comment by Colstuwjx** [comment]
Yes, you're right. I learned the [cortex architecture](https://docs.google.com/document/d/1C7yhMnb1x2sfeoe45f4mnnKConvroWhJ8KQZwIHJOuw), and I am still curious about the final clustering solution for prometheus.

The elastic adapter is also a test case, and it seems not work well in my production environment.

As you mentioned, I'd like to create a new repo to serve the elastic adapter, and still watch the `remote-storage` experimental feature.

Look forward to have a great clustering solution for prometheus!

**Comment by juliusv** [comment]
@Colstuwjx Great. I'll close the PR here for now then and looking forward to seeing this as a separate repo!

> Look forward to have a great clustering solution for prometheus!

Please note that we don't plan to add clustering to Prometheus ourselves. So far, the only plan is to let people solve this externally via remote read/write adapters like these.

**Comment by Colstuwjx** [comment]
Aha.. I have already moved this adapter into [this separate repo](https://github.com/Colstuwjx/elastic-adapter)!

**Pull request closed without merging**
