### PR TITLE
tsdb: remove deleted series from WAL checkpoint without delay

### LINKED ISSUE #12286: WAL Checkpoint holds series from too far back
### What did you do?

I observed a Prometheus where `prometheus_tsdb_head_series` varied from 4 million to 7 million over each compaction cycle.

The number of series in the WAL checkpoint is not observable via a metric, so I downloaded it and used the following code, adapted from `TestReadCheckpointMultipleSegments` to see the number of series:

```
	wt := newWriteToMock()
	watcher := NewWatcher(wMetrics, nil, nil, "", wt, dir, false, false)
	watcher.MaxSegment = -1
	watcher.setMetrics()

	lastCheckpoint, _, err := LastCheckpoint(watcher.walDir)
	err = watcher.readCheckpoint(lastCheckpoint, (*Watcher).readSegment)
	fmt.Println(len(wt.seriesSegmentIndexes))
```

### What did you expect to see?

About 7 million series in the WAL checkpoint (same as the max observed number of series).

Reasoning: a WAL checkpoint is generated every head compaction* (= 2 hours with default settings) and the checkpoint covers about the same time, so the checkpoint should have about the same number of series as I observe in the head.

\* unless the amount of data being collected is small, in which case it's every 2 head compactions.

### What did you see instead? Under which circumstances?

The WAL checkpoint had 18 million series in it, any time I looked at it.

### System information

_No response_

### Prometheus version

```text
I was looking at 2.41 but further tests show the same thing happens in 2.43.
```

### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by bboreham**
Remove the `deleted` map that retained deleted series for 3 head compaction cycles; it is not needed.

This should significantly improve the time to read the WAL, and reduce memory usage for remote-write.

Fixes #12286 

To illustrate, pictured below is a Prometheus TSDB that has been collecting data since 10:00 UTC. WAL segments are named A, B, C, ...

```
           10:00        12:00
Head       ┌───────────────────┐
           └───────────────────┘
WAL        A- B- C- D- E-- F- G-
```

At approx 13:00, head compaction runs.  A block is created from 10:00-12:00, and that data is dropped from the head. Any series which stopped before 12:00 is garbage-collected from the head.

A WAL checkpoint is created from the first two thirds of the segments, A-D. All samples before 12:00 are excluded. WAL segments A-D are removed from disk.

```
           10:00        12:00
Head                    ┌──────┐
                        └──────┘
Block      ┌────────────┐
           └────────────┘
WAL                    E-- F- G-
Checkpoint            X
```

There is no need to remember any series deleted from the head in the WAL checkpoint, since the condition to garbage-collect a series is that it has no samples after 12:00.

### CODE REVIEW

**Review by jesusvazquez — COMMENTED** [review]
I found this useful to understand why this deleted map existed https://github.com/prometheus/prometheus/commit/dfed85e4a4be232dc15527645f1b4bb3aa549023

> There is no need to remember any series deleted from the head in the WAL checkpoint, since the condition to garbage-collect a series is that it has no samples after 12:00.

After reading @bboreham 's explanation and going through the code I think it makes sense to no longer track these. 

I'm also thinking that if a sudden restart / out of memory  where to happen, we could only rely on whatever series refs are on the WAL since these `deleted` memory map would also dissapear so to me there is no point in making the live WAL checkpointing more complex than the worst case scenario.

**Comment by bboreham** [comment]
@codesome pointed out there can be samples in the 1/3 of WAL not being cleaned up, but still the series has been removed from the head. 

In terms of the example, this means the samples came after 12:00 but also in the last 1/3 of the WAL.
This can happen if the rate of data slows down.  Zooming in to make that easier to draw:
```
           10:00        11:00        12:00        13:00
Head       ┌───────────────────────────────────────┐
           └───────────────────────────────────────┘
WAL        A B C D E F G H I J--- K--- L--- M--- N---
```

There are 12 WAL segments from A to M, so 8 of them A-H would be deleted by truncation.
If the samples are in segment J, say, then we should not remove the series from the checkpoint.

**Comment by cstyan** [comment]
I'm not understanding why the initial commit https://github.com/prometheus/prometheus/commit/dfed85e4a4be232dc15527645f1b4bb3aa549023 was needed:
> If all the samples are deleted for a series,
we should still keep the series in the WAL as
anything else reading the WAL will still care
about it in order to understand the samples.

what samples? we deleted them all for that series

On top of that, to counter act the scenario Ganesh pointed out in Bryan's latest comment, maybe we should consider checkpointing/truncating the WAL based on the overall time range rather than just WAL segment? it's just the segment index we use to decide whether we delete the segment or not: https://github.com/prometheus/prometheus/blob/main/tsdb/head.go#L1201-L1208

**Comment by bboreham** [comment]
> maybe we should consider checkpointing/truncating the WAL based on the overall time range

I think you can only do that by scanning the entire WAL and rewriting to remove deleted series.
This seems too expensive.

Note timestamps may be supplied by targets, so it's possible that each WAL segment has an overlapping time range with the one before.

**Comment by cstyan** [comment]
> Note timestamps may be supplied by targets, so it's possible that each WAL segment has an overlapping time range with the one before.

Okay yes, this definitely complicates things. I was thinking we could just introduce another record type that has metadata `first sample` and `last sample` timestamps as the last record in a segment, and check that record during the process to decide what segments to delete.

> I think you can only do that by scanning the entire WAL and rewriting to remove deleted series.
This seems too expensive.

yes

**Comment by bboreham** [comment]
Closing this; I think #12297 is workable now and a better solution will take time.

**Pull request closed without merging**
