### PR TITLE
Added externalURL and pathPrefix functions to Template reference docs

### PR DESCRIPTION
**Pull request by peergynt**
https://github.com/prometheus/prometheus/pull/2716 added the functions: externalURL and pathPrefix.
It looks like this never made it into the documentation.
This PR adds the two aforementioned functions to the Template reference documentation.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks for your PR. For legal reasons, we require that all commits are signed with a [DCO](https://developercertificate.org/) before we can merge them. See [this blog post](https://www.cncf.io/blog/2016/11/08/cloud-native-software-can-trust/) for considerations around this.

This means that the last line of your commit message should read like:

`Signed-Off-By: Your Name <your@email.address>`

If you are using GitHub through the web interface, it's quickest to close this PR and open a new one with the appropriate line.

If you are using Git on the command line, it is probably quickest to amend and force push. You can do that with
````
git commit --amend --signoff
git push -f $remote $remote_branch_for_pr
````

As always, be careful when force-pushing.

**Comment by roidelapluie** [comment]
Commit sha: 6674c5e, Author: Jerome Meyer, Committer: Jerome Meyer; Expected "Jerome Meyer peergynt@users.noreply.github.com", but got "Jerome Meyer jxmeyer@gmail.com".

**Comment by peergynt** [comment]
Did an interactive rebase and forced push to fix DCO author. DCO bot seems happy now.

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
