### PR TITLE
Change expression input field to multi-line textarea.

### PR DESCRIPTION
**Pull request by juliusv**
Also, rearrange and clean up some things to make this work.

The textarea starts as a single line, but auto-expands when entering
multiple lines (e.g. via Shift+Enter). Pressing just "Enter" still
executes the expression.

### CODE REVIEW

**Comment by fabxc** [comment]
\o/ :+1:

**Comment by juliusv** [comment]
Some screenshots:

textarea1

textarea2

textarea3

**Comment by juliusv** [comment]
@matthiasr

**Comment by matthiasr** [comment]
Can't competently comment on CSS/JS but :+1: for the concept

**Pull request merged**
