### PR TITLE
scrape_test.go: Increase scrape interval in TestScrapeLoopCache to re…

### PR DESCRIPTION
**Pull request by machine424**
…duce potential flakiness

fixes: https://github.com/prometheus/prometheus/issues/12727

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks; needs DCO.

Will this increase the test run time?

**Comment by machine424** [comment]
> Will this increase the test run time?

Yep, it'll move from `0.04s` to `0.4s` in average.
Another solution would be to add a `time.Sleep(2*time.Millisecond)` to the `scraper.scrapeFunc` to make sure it isn't triggered at the same ms timestamp.

**Comment by bboreham** [comment]
How about we make this change only on the OSs where it is required?  (Which I think is Windows)

**Comment by machine424** [comment]
> How about we make this change only on the OSs where it is required? (Which I think is Windows)
I have the same issue on Mac actually.

**Comment by machine424** [comment]
There is also this hack:

> Another solution would be to add a time.Sleep(2*time.Millisecond) to the scraper.scrapeFunc to make sure it isn't triggered at the same ms timestamp.

Which will not increase the runtime A LOT (given https://github.com/golang/go/issues/44343)

(fun fact: we don't recommend using such small scrape intervals, but they're the ones we "test" the most so tests run faster, I don't know if parallelism may help to be able ti use larger intervals...)

**Review by bboreham — APPROVED** [review]
OK let's move ahead with this and revisit if the extra fraction of a second is important.

**Pull request merged**
