### PR TITLE
Adds support for expanding templates before rules check

### PR DESCRIPTION
**Pull request by Harkishen-Singh**
Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>
Fixes: #6467 

Explanatory gif:

expd

Output before the patch:
```
Checking test.yml
  FAILED:
../../test.yml: yaml: line 11: could not find expected ':'
```

**test.yml**
```
groups:
    - name: test
      rules:
      - alert: Test Alert
        expr:  up == 0
        annotations:
          description: This is a test alert that should always fire
        labels:
          severity: warning
        {{define "test-macro"}}
            expr:  time() > {{.arg0}}
        {{end}}
```

### CODE REVIEW

**Comment by juliusv** [comment]
@Harkishen-Singh I think there was some misunderstanding unfortunately - this looks like it's adding templating functionality to the top-level file, before YAML is even parsed. The creator of the linked issue https://github.com/prometheus/prometheus/issues/6467 apparently assumed that this was functionality that was supposed to work and that we want to have, but so far we've decided pretty explicitly against having general templating functionality in the top-level of the YAML. And for the specific fields where templating is supported, we already check the template parsing when the file is loaded. So I believe there is nothing to actually do there, as indicated by https://github.com/prometheus/prometheus/issues/6467#issuecomment-589329945.

**Comment by brian-brazil** [comment]
Ah indeed, this is not something that should work.

**Comment by Harkishen-Singh** [comment]
@juliusv @brian-brazil I get your point. Thank you for explaining the issue. Can we close the issue if it points to something we do not need?

**Comment by roidelapluie** [comment]
I have closed it. Thanks however to look into it. Sorry you did not see my comment in time.

**Pull request closed without merging**
