### PR TITLE
add os.RemoveAll err verification

### PR DESCRIPTION
**Pull request by zhouhao3**

### CODE REVIEW

**Comment by q384566678** [comment]
> Do you think you can fix them?

@codesome  I don't know why this problem occurs under the windows system. At present, I have no solution. Can you give me some suggestions? Or merge this PR first, and then someone creates a new PR to solve this problem.

**Comment by beorn7** [comment]
The problem occurs in the ci/circleci test for MS Windows. That should give a hint (and at the same time is the reason why we cannot merge this as is: It would break the CI tests).

**Comment by codesome** [comment]
@q384566678 basically we are not closing files somewhere and in Windows you cannot delete a file/directory if it is open somewhere. So you have to check where all are we not closing files in the test and close them before the deletion phase.

**Comment by zhouhao3** [comment]
@codesome Done, PTAL.

**Pull request merged**
