### PR TITLE
Remove unused flock package

### PR DESCRIPTION
**Pull request by simonpasquier**
This package was used in the pre-2.x code base.

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
how did you even catch that?
LGTM on green - always happy when reducing code count :smile:

**Comment by brian-brazil** [comment]
Thanks!

**Comment by krasi-georgiev** [comment]
shouldn't we also have some check for unused vendored packages?

a quick check with `vendorcheck -u` shows few unused (some false positive)
```
go get github.com/FiloSottile/vendorcheck
vendorcheck -u
```

**Comment by simonpasquier** [comment]
> how did you even catch that?

I was just browsing `util/` and wondered why there was  a `flock` directory there. It didn't took me long to realize that it was unused.

**Comment by krasi-georgiev** [comment]
govendor support this as well `govendor list +unused` and has less false positive , only need to check for each supported OS which might be a blocker.

**Comment by peterbourgon** [comment]
Oh no, I used this dependency. Does it exist somewhere else or shall I mirror it?

**Comment by brian-brazil** [comment]
I think this is the only one, so I'd say mirror it.

**Pull request merged**
