### PR TITLE
Display active alerts on top

### PR DESCRIPTION
**Pull request by mszczygiel**
Closes https://github.com/prometheus/prometheus/issues/5655

### CODE REVIEW

**Comment by brian-brazil** [comment]
This would make the order of rule groups basically random if you're trying to look at a specific group.

**Comment by mszczygiel** [comment]
I agree that following a particular group can be annoying now. Maybe it could be done with simple filtering (like on `Targets` tab where there are `All/Unhealthy` buttons). I could put buttons like `All`, `Active`, `Firing` on the Alerts tab where `Active` would contain both pending and active alerts. What do you think?

**Comment by kustodian** [comment]
Filtering would be great. Also IMO the default should be to only display active alerts.

**Comment by mszczygiel** [comment]
I will close this PR in favour of https://github.com/prometheus/prometheus/pull/5758 where instead of sorting I added filters.

**Pull request closed without merging**
