### PR TITLE
Add armv6 docker image

### PR DESCRIPTION
**Pull request by mhansen**
This follows the approach used to generate armv7 images.

It was all so nicely factored already that I just had to update two
parts of the code.

Addresses #6604

### CODE REVIEW

**Comment by simonpasquier** [comment]
you would need to rebase on master

**Comment by mhansen** [comment]
Rebased to master, thanks!

**Comment by mhansen** [comment]
Hi, friendly ping :-), I've rebased to master - could I get a review?

**Comment by simonpasquier** [comment]
:+1:

**Comment by simonpasquier** [comment]
@cstyan since we're in release time and I'm not sure which workflow you've picked up, feel free to merge this if you're ok or if it doesn't interfere with your release work.

**Comment by cstyan** [comment]
@simonpasquier feel free to merge into master, unless you wanted this to be part of the 2.16.0 release.

I have a separate branch for the release and any bugfixes that need to go into the release, as per the `RELEASE.md` doc.

**Comment by simonpasquier** [comment]
@mhansen unfortunately the change didn't build correctly in the CI so I had to revert the PR. The issue was that we didn't have a `quay.io/prometheus/busybox-linux-arm32v6` image. And I'm afraid that it can't happen because there's no arm32v6/busybox:glibc or arm32v6/busybox:ulibc in the first place (see https://github.com/docker-library/busybox/issues/58 for the rationale).

**Comment by mhansen** [comment]
Oh dang. Thanks for giving this a go, sorry about the hassle

**Pull request merged**
