### PR TITLE
Deprecate DeduplicateSeriesSet() in favor of NewMergeSeriesSet().

### PR DESCRIPTION
**Pull request by EdSchouten**
Federation makes use of dedupedSeriesSet to merge SeriesSets for every
query into one output stream. If many match[] arguments are provided,
many dedupedSeriesSet objects will get chained. This has the downside of
causing a potential O(n*k) running time, where n is the number of series
and k the number of match[] arguments.

In the mean time, the storage package provides a mergeSeriesSet that
accomplishes the same with an O(n*log(k)) running time by making use of
a binary heap. Let's just get rid of dedupedSeriesSet and change all
existing callers to use mergeSeriesSet.

### CODE REVIEW

**Comment by EdSchouten** [comment]
Wow! I just gave this patch a try. We want to do cherry picking of about ~100 metrics from one Prometheus server and store it in another one. This `/federate` request would take at least one minute of CPU time. With this patch attached, the requests now finish in ~3.5 seconds.

**Comment by tomwilkie** [comment]
Sweet! I’ll take a look first thing tomorrow, but nice improvement.

**Comment by tomwilkie** [comment]
This does introduce a semantic change; if two supplied matches to the federate endpoint returned the same timeseries, the previous code would drop one, whereas this code will merge them.  Given the series come from the same datasource, the merge on them should be harmless (as the merge will also dedupe), but I think a second opinion would be worth it here.  So +1 from me, but maybe someone from @brian-brazil, @fabxc or @juliusv should also take a look?

**Comment by brian-brazil** [comment]
That sounds fine to me semantically. Only technically correct with isolation, but that's the case with isolation generally :)

**Comment by juliusv** [comment]
I think this is fine too, great improvement!

**Comment by EdSchouten** [comment]
Awesome! Thanks for merging this so quickly!

**Pull request merged**
