### PR TITLE
Fix watching multiple Zookeeper paths in serverset SD.

### PR DESCRIPTION
**Pull request by juliusv**
@brian-brazil I'm not very familiar with serversets or the SD code around it, but this looked kind of like the obvious solution to https://github.com/prometheus/prometheus/issues/1137 - still waiting for confirmation though.

Since all the updates go into a channel, it should be fine to just spin up one ZK tree cache for each configured path?

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
Thanks! Will wait for confirmation from @StephanErb before merging.

**Comment by juliusv** [comment]
Merging for now since it seems like the solution - let me know if anyone encounters problems with this.

**Comment by StephanErb** [comment]
Looks good. Sorry for the delay and thanks for the patch!

**Comment by juliusv** [comment]
@StephanErb No problem! Thanks for the confirmation!

**Pull request merged**
