### PR TITLE
Update Go dependencies ahead of v2.38

### PR DESCRIPTION
**Pull request by juliusv**
I skipped an update for the Azure client libraries because that was too
involved and needs some migration work from Azure SD maintainers.

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
Is the CI check test_golang_oldest failing with this error new?

```
[...]
go: downloading github.com/Azure/go-autorest/autorest/validation v0.3.1
go: downloading github.com/Azure/go-autorest/autorest/to v0.4.0
# github.com/linode/linodego
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:23:21: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:36:64: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:41:28: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:59:30: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:61:26: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:74:11: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:81:35: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:86:20: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/waitfor.go:14:13: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/waitfor.go:577:26: undefined: any
/go/pkg/mod/github.com/linode/linodego@v1.9.1/filter.go:86:20: too many errors
note: module requires Go 1.18
!! command failed: build -o /root/project/prometheus -ldflags -X github.com/prometheus/common/version.Version=2.37.0 -X github.com/prometheus/common/version.Revision=fe7dac8e4b1dfaa9f6c7496d498b4cf0bfcb0a21 -X github.com/prometheus/common/version.Branch=update-go-deps -X github.com/prometheus/common/version.BuildUser=root@3b3f6ccbbb5f -X github.com/prometheus/common/version.BuildDate=20220810-14:08:15  -extldflags '-static' -a -tags netgo,builtinassets github.com/prometheus/prometheus/cmd/prometheus: exit status 2
make: *** [Makefile.common:195: common-build] Error 1
```

I'm not sure which part exactly wants Go 1.18... `github.com/prometheus/common` still has `go 1.17` in its `go.mod` and the package preceding the failure lines has `go 1.15`.

**Comment by juliusv** [comment]
Ah, somehow I thought those tests were running on Linode for some special reason and `linodego` was some special old Go compiler there... not the actual package that we are using in Prometheus and that I just updated 🤣

**Comment by juliusv** [comment]
So the question is whether we still need to support Go 1.17 (what's our policy there)? It's at least holding back this Linode package update.

**Comment by LeviHarrison** [comment]
IRC from last week:

> Levi Harrison
Now that go 1.19 is out are we good to update to 1.18 (at least in prometheus/prometheus)?

> SuperQ@SuperQ:libera.chat
Levi Harrison: Let's give it a couple weeks.

> Julien Pivotto
...
We generally update to the latest when it is available.
However since we release in 1 week, we can still do 2.38 with go1.18

So I think the consensus was not yet.

**Comment by juliusv** [comment]
@LeviHarrison Sounds good, so I just dropped the `linodego` update part from this PR for now. Let's see if things pass now...

**Comment by LeviHarrison** [comment]
```
diff --git a/go.sum b/go.sum
index 0f6939a4f..26c4643b5 100644
--- a/go.sum
+++ b/go.sum
@@ -1485,6 +1485,7 @@ gopkg.in/fsnotify.v1 v1.4.7/go.mod h1:Tz8NjZHkW78fSQdbUxIjBTcgA1z1m8ZHf0WmKUhAMy
 gopkg.in/gcfg.v1 v1.2.3/go.mod h1:yesOnuUOFQAhST5vPY4nbZsb/huCgGGXlipJsBn0b3o=
 gopkg.in/inf.v0 v0.9.1 h1:73M5CoZyi3ZLMOyDlQh031Cx6N9NDJ2Vvfl76EDAgDc=
 gopkg.in/inf.v0 v0.9.1/go.mod h1:cWUDdTG/fYaXco+Dcufb5Vnc6Gp2YChqWtbxRZE0mXw=
+gopkg.in/ini.v1 v1.66.4/go.mod h1:pNLf8WUiyNEtQjuu5G5vTm06TEv9tsIgeAvK8hOrP4k=
 gopkg.in/ini.v1 v1.66.6 h1:LATuAqN/shcYAOkv3wl2L4rkaKqkcgTBQjOyYDvcPKI=
 gopkg.in/ini.v1 v1.66.6/go.mod h1:pNLf8WUiyNEtQjuu5G5vTm06TEv9tsIgeAvK8hOrP4k=
 gopkg.in/resty.v1 v1.12.0/go.mod h1:mDo4pnntr5jdWRML875a/NmxYqAlA73dVijT2AXvQQo=
```

Looks like you need to run `go mod tidy`

**Comment by juliusv** [comment]
@LeviHarrison Ah thanks, ran it again!

**Review by LeviHarrison — APPROVED** [review]
Thanks!

**Pull request merged**
