### PR TITLE
Switch client_golang/model (a.k.a clientmodel) to common/model

### PR DESCRIPTION
**Pull request by fabxc**
This is what I'd suggest to do with packages in the future.

`client_golang/text` > `common/textproto` (or just proto considering that it handles protobuf).
`client_golang/extraction` > `common/extraction`
`client_golang/model` > `common/model` and no more renaming to `clientmodel`

`client_golang` should get an API package which also provides a simple interface to read metric endpoints. No more dependencies of `prometheus` to `client_golang`.

@juliusv @beorn7

### CODE REVIEW

**Comment by beorn7** [comment]
WRT to textproto: The fact that it handles protobuf is actually not significant as protobuf happens to be the internal DTO format. Any package able to parse and create a non-internal format will implicitly handle protobuf. So the title of that package should not contain "proto" at all.

**Comment by fabxc** [comment]
I was thinking about `proto` in the sense of "protocol" as this package handles our application-level protocol (in whatever lower-level format). So this was not meant to be a reference to "procbuf".

**Comment by juliusv** [comment]
Can we defer the move of the `text` and `extraction` packages until we have a replacement for them in the client library / API package?

**Comment by beorn7** [comment]
But `text` (or now `textproto`) handles only the text-based format.

Perhaps we should have `protocols` and then subpackages... OTOH, we don't want to support more exchange protocols...

Just 'proto' is really ambiguous in a context where you use protobufs.

**Comment by fabxc** [comment]
Closing as this was to check whether there is some level of acceptance for the idea.
Will happen in a new PR if the time is right.

**Pull request closed without merging**
