### PR TITLE
multiple queries test for StreamRead

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@bwplotka PTAL

**Comment by bwplotka** [comment]
Just curious @YaoZengzeng, are you doing multi-query requests against remote read? (:

**Comment by YaoZengzeng** [comment]
@bwplotka Actually I want to fix issue #5926 :)

**Comment by bwplotka** [comment]
Awesome! can you mention on the issue that you want to work on this? It would help others to understand that someone is working on it.

Can you also mention the directions and potential design? It's not a super easy issue (: Probably needs multiple PRs.

**Pull request merged**
