### PR TITLE
Testing alerting rules with UI

### PR DESCRIPTION
**Pull request by codesome**
This PR adds a new webpage for testing alerting rules.

Opens up at `/alert-rule-testing`.
~~This code is already running on a server for a demo: http://159.65.80.85:9090/alert-rule-testing, this link will be updated with any further updates to this PR.~~

Addresses these long standing issues:
https://github.com/prometheus/prometheus/issues/1154
https://github.com/prometheus/prometheus/issues/1220

Suggestions are welcome. Some screenshots can be found [here](https://ganeshvernekar.com/gsoc-2018/alert-rule-testing-ui/).

PS: I have run this on very small set of expressions, but as `Eval` logic is reused, should not be a problem?.

### CODE REVIEW

**Comment by codesome** [comment]
@brian-brazil PTAL

**Comment by base698** [comment]
This is nice, anyone have any input here?

@codesome good work.

**Comment by roidelapluie** [comment]
We have decided to close this PR as @codesome has told us that this PR was not being worked on anymore.

**Comment by kadaan** [comment]
@codesome I resurrected your work, made some improvements, and it seems to work well for my use cases.  I have included it in my https://github.com/kadaan/promutil.  

2022-09-01 at 13 41 58@2x

**Pull request closed without merging**
