### PR TITLE
[remote-storage] use warn log level when send samples to remote failed

### PR DESCRIPTION
**Pull request by qingwave**
**What type of PR is this?**
Add a detail error for [sendSamplesWithBackoff](https://github.com/prometheus/prometheus/blob/05038b48bdf08dd72731bfaf74c9f5e5eaff5f39/storage/remote/queue_manager.go#L875)

**What this PR does / why we need it:**
This useful for user to find remote write error directly, rather than a `context deadline exceeded`. 
e.g. `no route to host` occured, we can easily find it.

### CODE REVIEW

**Comment by qingwave** [comment]
> Thank you for the PR!
> 
> A couple things here, I don't like that we could potentially be printing out nil errors here, and would prefer the error to be reported more quickly as it would currently be necessary to shutdown or change a queue to get this error.
> 
> What would you and @cstyan think of increasing the level of the "Failed to send batch, retrying" log message? We use a dedupe logger so it shouldn't be too noisy.
> 
> This could fix #5735 depending on the implementation

If dedupe logger is ok, increasing the `send batch error` log level maybe reasonable.

**Comment by cstyan** [comment]
I think bumping the log level while we're still using the deduper is fine. Especially given that we also have the metric for retried samples.

**Comment by unfor19** [comment]
Was this merged to `prom/prometheus:v2.24.1` ? I can see the proper error when using `debug` level but not `info` level (which is "higher" than `warn`)

Am I missing something?

**Comment by roidelapluie** [comment]
Can you paste the log line ?

**Comment by roidelapluie** [comment]
Also note that the error will not be repeated if it is the same (IIRC)

**Comment by unfor19** [comment]
@roidelapluie
1. Changed `log.level` to `debug`, `info` and `warn`
1. Disallowed outbound connection (AWS Security Group > removed `outbound to 0.0.0.0/0` rule)
1. Restarted Prometheus - `kill -HUP 1`

`--log.level=debug` (works as expected)
```
ts=2021-01-27T11:21:21.540Z caller=dedupe.go:112 component=remote
level=debug remote_name=lalala url="https://metric-api.newrelic.com/prometheus/v1/write?X-License-Key=TOKEN&prometheus_server=prom" msg="failed to send batch, retrying" err="Post \"https://metric-api.newrelic.com/prometheus/v1/write?X-License-Key=TOKEN&prometheus_server=prom\": context deadline exceeded"
```

`--log.level=info` - no error appears, even though there's outbound connection is not allowed
```
ts=2021-01-27T11:51:24.781Z caller=dedupe.go:112 component=remote
level=info remote_name=lalala url="https://metric-api.newrelic.com/prometheus/v1/write?X-License-Key=TOKEN&prometheus_server=prom" msg="Done replaying WAL" duration=14.391332476s
```

`--log.level=warn` - nothing to show, no logs at all

**Comment by csmarchbanks** [comment]
This was a part of v2.19, but it looks like in v2.23 a change was merged that accidentally changed it back to debug. Here is a PR to change this line back to warn: https://github.com/prometheus/prometheus/pull/8412.

So v2.19.x -> v2.22.x should have the debug log if you need it. Sorry about that!

**Comment by unfor19** [comment]
@csmarchbanks - Thank you very much for the clarification, I'll use v2.22.x, no biggy. Originally I used 2.18.1 so 2.22.x is still an upgrade ... 😄 

Thanks!

**Pull request merged**
