### PR TITLE
translation to spanish some md files

### PR DESCRIPTION
**Pull request by johnfelipe**
Signed-off-by: Mgtr Felipe Urrego <ingenierofelipeurrego@gmail.com>

translation to spanish some md files

### CODE REVIEW

**Comment by johnfelipe** [comment]
i signed, but no work

**Comment by a-gavin** [comment]
image
The name you provided in the sign of and the name in your git config do not match. The above screenshot is taken from the bottom of the DCO check.

See the [GitHub Desktop](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/configuring-git-for-github-desktop) for info on how to change this.

**Comment by johnfelipe** [comment]
Signed-off-by: Felipe <ingenierofelipeurrego@gmail.com>
recheck

**Comment by roidelapluie** [comment]
Thank you. However, translating is a really complex process and I think we should only do it if a Prometheus team member agrees to take the time it needs to maintain the translation up to date, to avoid drift. As this is unprecedented in Prometheus, it should be discussed in a developer summit.

**Comment by LeviHarrison** [comment]
#10902 is closely related to this

**Comment by jesusvazquez** [comment]
Closing this one. The translation to spanish is too literal and some files are only half translated. This requires spending a bit more time to get it right. Also before that Julien is right that whether or not we want to do this should be discussed in a developer summit.

**Pull request closed without merging**
