### PR TITLE
cmd/prometheus: replace glog by glog-gokit

### LINKED ISSUE #4795: Prometheus crashes if it can't write logs to /tmp
## Bug Report
**What did you do?**

We copy the Prometheus binary into a from-scratch Docker container and run it as a non-root user to reduce our footprint and threat surface. This is a practice we follow with all applications we run in our Kubernetes environment. Recently we upgraded to prometheus v2.4.2 from v2.3.0, where in both cases we were running in containers using this method.

**What did you expect to see?**

Prometheus should run fine, as v2.3.0 seemed to.

**What did you see instead? Under which circumstances?**

Prometheus is repeatedly crashing with this error:

```
W1026 14:54:21.157256       1 reflector.go:341] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:306: watch of *v1.Pod ended with: too old resource version: 19430593 (19430983)
log: exiting because of error: log: cannot create log: open /tmp/prometheus.prometheus-75f465d4d4-hjztt.unknownuser.log.WARNING.20181026-145421.1: no such file or directory
```

This seems to be a glog error message which occurs when glog can't write a logfile. However, I don't want glog writing to any files at all; it should write all logs to stderr, since we are running in a Docker container and want to delegate log management to Docker. However, I see no way to configure Prometheus or glog to not log to files.

glog apparently has a `--logtostderr` flag, but it's not being exposed by Prometheus.

Note that the crash is ALWAYS preceded by a warning log from Kubernetes service discovery, so this may be the source of the bug.

This error was also reported on coreos/prometheus-operator here: https://github.com/coreos/prometheus-operator/issues/1932 Notice that the crash in that report is ALSO preceded by a warning from Kubernetes service discovery.

**Environment**

* System information: no `uname` in a scratch container.

* Prometheus version:

```
prometheus, version 2.4.2 (branch: HEAD, revision: c305ffaa092e94e9d2dbbddf8226c4813b1190a0)
  build user:       root@dcde2b74c858
  build date:       20180921-07:22:29
  go version:       go1.10.3
```

* Logs:
```
W1026 14:54:21.157256       1 reflector.go:341] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:306: watch of *v1.Pod ended with: too old resource version: 19430593 (19430983)
log: exiting because of error: log: cannot create log: open /tmp/prometheus.prometheus-75f465d4d4-hjztt.unknownuser.log.WARNING.20181026-145421.1: no such file or directory
```

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #4795 #3236

cc @metalmatze

### CODE REVIEW

**Comment by brancz** [comment]
Out of curiosity, can we test this somewhere just to make sure the "6" verbosity is not over-doing it?

**Comment by simonpasquier** [comment]
@brancz yep I meant to provide some snippets of logs anyhow.

**Comment by simonpasquier** [comment]
Prometheus logs with level 6:

https://paste.fedoraproject.org/paste/ZbTSh5FuyAaoKSQ7M7EaFg

Prometheus logs with level 7 (I didn't redacted the tokens since this cluster is already gone):

https://paste.fedoraproject.org/paste/iKb7LBrFJm1IeA9kjVutZQ

**Comment by simonpasquier** [comment]
@brancz friendly ping

**Comment by brancz** [comment]
Did we have this verbosity level previously? I don't recall seeing messages like that.

Generally looks good to me though.

**Comment by brancz** [comment]
Oooohhhh... I see now, yes that makes perfect sense. In that case lgtm :+1:

**Pull request merged**
