### PR TITLE
add take relabel action

### PR DESCRIPTION
**Pull request by gitwillsky**
Add `take` relabel action for scrape whitelist metrics

Usage:
```yaml
    metric_relabel_configs:
      - source_labels: ['__name__', 'cpu', 'mode']
        regex: 'node_cpu_seconds_total;0;user'
        action: 'take'
      - source_labels: ['__name__', 'cpu', 'mode']
        regex: 'node_cpu_seconds_total;1;idle'
        action: 'take'
```

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you explain more about your use case? This seems to be handled by the existing keep/drop actions.

**Comment by gitwillsky** [comment]
Forgive my poor english, :)
If user only want to scrape some metrics, like this:
```bash
a {cpu="cpu0", mode="idle"}
b {type="1",mode="user"}
```
`keep` action config will like this:
```yaml
 - source_labels: ['__name__', 'mode']
        regex: '(?:a|b);(?:idle|user)'
        action: 'keep'
```
But when a metric like this:

```bash
b {type="1",mode="idle"}
```
It will also be keep

**Comment by brian-brazil** [comment]
What you want is `a;idle|b;user`

**Comment by gitwillsky** [comment]
Suddenly realized，thank you.

**Pull request closed without merging**
