### PR TITLE
Fix potential panic when prometheus is watching multiple zookeeper paths

### PR DESCRIPTION
**Pull request by meridional**
#5675 introduced a serious bug: if prometheus is configured to watch multiple zk paths, multiple tree caches will share the same updates channel. When reloaded, each treecache will call `close` on the `updates` channel, causing a panic.

This patch fixes the issue by using fan-in pattern, where each treecache gets its own update channel, and in zookeeper library, we merge the events from each channel into `zookeeper.Discovery.updates`.

Sorry for the interruptions caused by #5675!

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1: 

@brancz Bugfix for 2.11.0

**Comment by beorn7** [comment]
@brian-brazil As you correctly identified this as a bugfix for v2.11, you could as well have changed the target branch to be release-2.11. New @brancz needed to cherry-pick, which we want to avoid.

**Comment by brancz** [comment]
@beorn7 you're right. My mistake.

**Comment by brian-brazil** [comment]
I was leaving this up to the release owner, which is why I didn't merge it.

**Comment by beorn7** [comment]
As cherry-picking is explicitly marked as something we'd like to avoid in the instructions, it would have been a friendly move to point out that the base branch should not be master. A :+1: by an experienced core developer conveys the meaning that all is good with the PR.

**Pull request merged**
