### PR TITLE
Refactor discover recreate target groups test

### PR DESCRIPTION
**Pull request by grandbora**
This pr refactors the test that covers the case with multiple `UpdateProviders` calls. Expectation here is that none of the earlier target groups will be sent in the `sync` calls that follows the latest `UpdateProviders` call.
improvements:
1) Assertions are now done on the contract(`sync` call arguments) rather than the internal state of the target set that consumers don't care about (`ts.tgroups`).
1) Now there is a timeout for the test. In case sync call is never called it won't wait forever but will fail gracefully after the timeout
1) This approach is consistent with the other tests that I added earlier.

cc @grobie @brian-brazil

### CODE REVIEW

**Comment by grandbora** [comment]
The ci failure is the flaky test. This is ready for 👀 . cc @grobie @brian-brazil Thank you :)

**Comment by grandbora** [comment]
If anyone shows ❤️  to this pr I'd be happy. cc @fabxc @brian-brazil

**Comment by grandbora** [comment]
Hi, this is a small refactoring of a single unit test. This PR is sitting here for 3 days. I would appreciate if anyone can show some ❤️  cc @brian-brazil @fabxc @grobie

**Comment by grobie** [comment]
On my review list for this weekend.

**Comment by brian-brazil** [comment]
It looks like this PR is also touching code that's changing in #3362. I'd suggest adding any comments you have on that review.

**Comment by grandbora** [comment]
Ok, I'll have a look.

**Comment by brian-brazil** [comment]
There are conflicts.

**Comment by simonpasquier** [comment]
This part of the code has been rewritten since then and is now (reasonably) tested.

**Pull request closed without merging**
