### PR TITLE
Avoid unnecessary index matching if the OOO head is empty

### PR DESCRIPTION
**Pull request by damnever**
This could happen in test cases.

### CODE REVIEW

**Comment by damnever** [comment]
Maybe we can reuse the matched postings from the head since the index is the same.

**Comment by roidelapluie** [comment]
I would strongly advice against taking a different code path just because of tests.

**Comment by bboreham** [comment]
I suspect it will go slower in the common case, due to two reads of an atomic value.
(which can be coded around, but the complexity will increase)

Note this in the PR instructions:

> Performance improvements would need a benchmark test to prove it.

**Comment by damnever** [comment]
I don't think we should ignore any edge cases, even if this only happens in the test cases.

And this idea is worth a try:
> Maybe we can reuse the matched postings from the head since the index is the same.

**Comment by damnever** [comment]
> Maybe we can reuse the matched postings from the head since the index is the same.

FYI, https://github.com/prometheus/prometheus/issues/11628

**Pull request closed without merging**
