### PR TITLE
Disable fsnofity in arm64, ppc64, and ppc64el.

### PR DESCRIPTION
**Pull request by TheTincho**
Fsnotify is is broken in these architectures (fsnotify/fsnotify#130). While
this gets fixed, this patch disables fsnotify and uses only timer expires to
refresh discovery files.
Fixes: #1507

### CODE REVIEW

**Comment by juliusv** [comment]
Thanks! But rather than duplicating so much of the generic code, could we maybe only wrap the needed fsnotify interface for the different platforms? That is, make our own watcher that forwards calls to the real fsnotify on good archs, but falls back to doing its own polling on bad ones?

**Comment by TheTincho** [comment]
Julius, you are completely right. That's why I said this patch was just a hack :)

I will try to get some time to work on this in the next few days, let's see if I can improve my golang-foo.

**Comment by TheTincho** [comment]
So, the fsnotify people managed to fix this issue already. Fixes were submitted to the syscall and the x/sys packages. So actually, thanks to this, bugs in core libraries were fixed!

**Comment by juliusv** [comment]
@TheTincho Nice! Thanks for this :)

**Pull request closed without merging**
