### PR TITLE
Add a command to promtool that dumps metadata of heads.db

### PR DESCRIPTION
**Pull request by beorn7**
I needed this today for debugging. It can certainly be improved, but
it's already quite helpful.

I refactored the reading of heads.db files out of persistence, which
is an improvement, too.

I made minor changes to the cli package to allow outputting via the
io.Writer interface.

@fabxc

### CODE REVIEW

**Comment by fabxc** [comment]
Happy to have more commands in helper tools.
The name `dump-heads` tells me nothing as a user and once we add it it's there to stay.

I don't think a normal user needs this and it's very specific to implementation details.
Maybe we can factor this out in a tool called `promdev` or something where we won't worry about a stable user interface.

**Comment by beorn7** [comment]
The docstring tells the user what the command is doing.

It's certainly only useful for advanced forensics, but not restricted to dev-related issues. I see users using it, so the question would be if we want a tool for basic use-cases and a different one for advanced use-cases.

**Comment by fabxc** [comment]
Yes, but they (mostly) won't understand what it even means (and that's not solved by turning it into 2 paragraphs building everything up).

I honestly think no normal user will care or ever need it and every additional feature, used or not, is cognitive burden. It's 100% internal and for that certainly super handy – an extra tool for that makes sense. Our user-tools should only concern with user interfaces.

I know it's far down the road, but I imagine `promtool` to carry a bunch of more things like alert unit testing, rule formatting, relabel testing.
I can also see various dev-concerned helper tools, e.g. I briefly discussed build/release tooling with @sdurrheimer and he already build something in that direction.

Also worth keeping in mind, commands working on storage etc. are way more volatile. We don't want to feel an obligation to keep a command such as `promtool dump-heads` working with 3 different formats that might have over time.
With a `promdev` tool it's easier to say "check out an older version if you want to run it against an old storage".

**Comment by matthiasr** [comment]
what about a dev command namespace within promtool? The help text coughs
day that these are for debugging internals, that sets the expectations
correctly without introducing yet another binary.

**Comment by fabxc** [comment]
Similar option. Than we get into a similar hierarchy like Bazooka CLI – I don't feel strongly about that yet, as long as we don't nest things that deep.

Probably it would be time then to evaluate a more complex CLI package to use.

**Comment by beorn7** [comment]
I'm all up for a separate tool (e.g. just for storage-related forensics) or an "advanced" namespace. I strongly oppose the notion that this is 100% dev-related.

Otherwise, I don't feel strongly. Please vote "namespace within promtool" vs. "separate tool for storage forensics".

**Comment by fabxc** [comment]
There are other things the regular user isn't concerned with like release processs functionality. I would co-locate it with these things to fragment sanely but not overly.

Certainly highly advanced users could look into this feature here as well – but I think `dev` is a reasonably understandable namespace for such things.

I need the full picture here for final judgement.
`promtool` allows validation of the Prometheus config. We don't have something similar for AM do we want a separate `alertmanagertool`. Does it make sense to consolidate this with `promtool` into its own repository? Then we will run into issues with validating different configuration versions.

Just throwing thoughts out there.

**Comment by beorn7** [comment]
The argument about storage being just implementation detail behind storage/local/interface.go would convince me to create a separate storage analysis tool somewhere in that part of the tree.

However, a separate tool would raise the question how to package it, if at all. Advanced users should be able to compile themselves, but having it in promtool would allow helping out with copy&paste command line tools. "Send me the output of `promtool dump-heads data/heads.db | grep FP=aef73742fe8c17ac`."

**Comment by fabxc** [comment]
Agreed, having it within reach on instruction is very helpful.

**Comment by grobie** [comment]
No strong opinion, but slight feeling it should be a separate tool. Could still be part of the release packages in the bin/ folder.

**Comment by juliusv** [comment]
:+1: to having it available to normal users, but no opinion on separate tool or only separate namespace.

For Alertmanager, I have the feeling that it would probably be a separate tool, since both Prometheus and Alertmanager are sufficiently big standalone components, and you'd then run into trouble with tool versions vs. Prometheus/Alertmanager versions.

**Comment by beorn7** [comment]
To not block on the outcome of the discussion, I have moved the `dump-heads` command into its own `storagetool` buried within `storage/local`. Let's consider it "freak stuff" for now and not provide Makefile integration. Once we have clarity how useful it is (and for whom), we can reconsider moving it somewhere and/or integrating it into the build process.

**Comment by fabxc** [comment]
That sounds good.

**Comment by fabxc** [comment]
:+1: nice

**Comment by beorn7** [comment]
thanks.

**Pull request merged**
