### PR TITLE
Simplify Makefile promu fetch

### PR DESCRIPTION
**Pull request by SuperQ**
Closes: https://github.com/prometheus/prometheus/issues/3460

### CODE REVIEW

**Comment by grobie** [comment]
For the test issues, see https://github.com/prometheus/prometheus/issues/3462.

**Comment by brian-brazil** [comment]
@sdurrheimer

**Comment by krasi-georgiev** [comment]
@sdurrheimer PTAL

**Comment by krasi-georgiev** [comment]
@brian-brazil actually I think this is good  to go , it is quite straight forward.

**Comment by SuperQ** [comment]
It would be nice to get one official maintainer thumb on this one.

**Pull request merged**
