### PR TITLE
Remove `AllowOverlappingCompaction` unused flag.

### PR DESCRIPTION
**Pull request by alanprot**
Opening this as a head up/ discussion point.

IDK if this flag ever worked but right now it seems that it is not being used anywhere.

### CODE REVIEW

**Comment by bwplotka** [comment]
Are you sure no one using compactor code uses this? (e.g Thanos) 

cc @saswatamcode @fpetkovski

**Comment by saswatamcode** [comment]
I don't think we use it now: https://github.com/search?q=repo%3Athanos-io%2Fthanos+AllowOverlappingCompaction&type=code. 
Although I did notice flag that doesn't do anything that we need to remove on Thanos side: https://github.com/thanos-io/thanos/blob/main/cmd/thanos/receive.go#L917

**Comment by yeya24** [comment]
We checked both Thanos and Cortex code. Even if the flag is set, it is not doing anything (nop)

**Comment by bboreham** [comment]
It's used in the Mimir compactor. https://github.com/grafana/mimir-prometheus/blame/cdc4e7fd4bb868e221fb1eb16a39362c6e1a1e77/tsdb/compact.go#L323

Ping @jesusvazquez do you know how to unpick this?

**Comment by bboreham** [comment]
Closed by #13282

**Pull request closed without merging**
