### PR TITLE
#1618 support the credentials file

### PR DESCRIPTION
**Pull request by yamatoya**
#1618 

This PR is supported for AWS Credential File.

* I have to update aws-sdk-go/credential, because of [aws-sdk-go/credentials](https://github.com/aws/aws-sdk-go/commits/master/aws/credentials/shared_credentials_provider.go) update for credential file at 2 Jun 2017.
* when CredentialPath is empty, sdk automatically search
  * sdk [ref](https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go#L26)
* when profile is empty, sdk automatically search
  * sdk [ref](https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go#L34)

@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why exactly do you need this, and in what way does the existing ability to specify an access key and secret key not cover you?

**Comment by yamatoya** [comment]
I want to use github for versioning prometheus.yaml.
But prometheus.yaml has aws access key/secret key, if I missed , it is published.
When I use sharedCredential, I can't miss published.

**Comment by brian-brazil** [comment]
It's expected that you'll use your usual configuration management system to handle that.

**Comment by yamatoya** [comment]
i understood and close

**Pull request closed without merging**
