### PR TITLE
Adding configuration documentation changes for username_file support for basic auth http client config

### PR DESCRIPTION
**Pull request by wasim-nihal**
Including documentation changes to have `username_file` option for basic auth configuration.

Changes for the ticket: https://github.com/prometheus/prometheus/issues/12576

@roidelapluie , request you to review the changes.

### CODE REVIEW

**Comment by wasim-nihal** [comment]
Please find the code changes PR at https://github.com/prometheus/common/pull/511

**Comment by gouthamve** [comment]
@roidelapluie Could you take a look? At first glance this looks correct. 

@wasim-nihal could you rebase your PR to fix the conflict?

_We looked at this in our bug scrub._

**Comment by wasim-nihal** [comment]
@gouthamve , I have rebased the PR. Can you please review?

**Comment by wasim-nihal** [comment]
@roidelapluie could you have a look at this once?  Currently, the documentation (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) is not update with the change.

**Review by krajorama — APPROVED** [review]
lgtm

**Review by bboreham — APPROVED** [review]
LGTM, thanks! 

Sorry for delay; I checked that [upstream](https://github.com/prometheus/common/blame/40d6251261f77cdc4a84219ba6243c0f18974fa6/config/http_config.go) still has these changes.

**Pull request merged**
