### PR TITLE
Prebuilt dev environments for easier onboarding and code reviews

### PR DESCRIPTION
**Pull request by svenefftinge**
Hey @juliusv,

This PR adds configuration for Gitpod to this repo. 
It allows anyone to quickly spin up fresh prebuilt dev environment in a browser for any branches, issues and pull requests.
I have configured it to prebuild your branches using (i.e. the init task in .gitpod.yml)
```
make build
```
On start it launches prometheus with the example config 
```
./prometheus --config.file=documentation/examples/prometheus.yml
```
in one terminal and the web UI in a separate one:

```
cd web/ui/react-app
yarn start
```

I hope the config is a good start. Please propose any changes to align better with your daily routines and use cases.

To get the prebuilds, you also need to install the [GitHub app](https://github.com/apps/gitpod-io) on this project. Without the app the config works, but users will have to wait for the init task (`make build`). 

You can try the experience on my fork https://gitpod.io/#https://github.com/svenefftinge/prometheus
Or even review this PR using gitpod by prefixing the URL of this page with `gitpod.io#`.

Screenshot 2020-07-26 at 11 42 40

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you for bringing this idea.

I feel like this should be discussed on our developers mailing list: https://groups.google.com/forum/#!forum/prometheus-developers rather than in a pull request.

**Comment by roidelapluie** [comment]
I will close this PR for now ; let's see what the discussions of the mailing list will give.

**Comment by juliusv** [comment]
To be fair, in a conversation with the nice people from Gitpod they mentioned their CI capabilities and I thought it sounded so awesome that I proposed them to send a PR :) But yeah, so you think we should discuss this first? It's going to add a CI check badge, and the benefit will be that you can immediately jump into an online container+IDE for any PR branch (with the binary pre-built), to further poke around at both the code and the actual behavior, without having to check out a PR branch locally. I think that's super cool :)

**Comment by juliusv** [comment]
I'll open a discussion on prometheus-developers.

**Pull request closed without merging**
