### PR TITLE
Followup on k8s' "own namespace" feature

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Review by brancz — APPROVED** [review]
lgtm

**Comment by beorn7** [comment]
I assume this is in essence cherry-picked from main? I don't feel qualified to review the content of this change, but I agree it should go into release-2.33

**Comment by roidelapluie** [comment]
Part of it is cherry picked from main, with an additional fix from my side.

**Comment by beorn7** [comment]
Anyway, let's merge it.

@roidelapluie how urgent is the bugfix release? Can we wait a bit longer for more fixes, or do you feel we need the release very soon?

**Pull request merged**
