### PR TITLE
Add methods to fetch page's buf data in tsdb WAL

### PR DESCRIPTION
**Pull request by erbesharat**
This PR adds methods like `bufalloc` or `bufremaining` to fetch page's buf data and a `reset` method to reset page's `alloc` and `buf` fields in tsdb WAL.

Related Issue: #5956

### CODE REVIEW

**Comment by erbesharat** [comment]
The force push is because I didn't know about the DCO check.

**Comment by codesome** [comment]
I personally don't see a need for this given all of them are used in a single place and all are simple enough to be inlined.

**Comment by krasi-georgiev** [comment]
maybe the reset one makes it a bit nicer to read, but the rest yeah , don't see how it helps.

**Comment by erbesharat** [comment]
Yeah, I agree that only the `reset` makes the code cleaner but thought since others are mentioned in the issue, they have to be implemented too.

**Comment by codesome** [comment]
>  since others are mentioned in the issue, they have to be implemented too

Not necessary. Could you just keep the `reset` method?

**Comment by krasi-georgiev** [comment]
the failing test is about a data race that is not related to this PR so merging.

Thanks

**Comment by brancz** [comment]
> the failing test is about a data race that is not related to this PR so merging.

Even if that is the case, I think we agreed that we at least want to see a green CI by re-running if that's the case. Otherwise we don't truly know if it's just a flake.

**Comment by krasi-georgiev** [comment]
I don't believe I have seen an invalid race condition so I have opened an issues.
https://github.com/prometheus/prometheus/issues/5977

I thought to leave it as is just to have the race details, but I copied the logs in the issues and now have triggered the CI run again.

**Comment by krasi-georgiev** [comment]
all green in CI now.

**Comment by brancz** [comment]
Opening an issue is even better. Thanks! :)

**Pull request merged**
