### PR TITLE
storage/remote: use t.TempDir instead of ioutil.TempDir on tests

### PR DESCRIPTION
**Pull request by msAlcantara**
Updates  #9594

### CODE REVIEW

**Comment by roidelapluie** [comment]
close/reopen to have ci running

**Comment by LeviHarrison** [comment]
There are some issues with `err`s now not being defined, as can be seen here: [`91ce37c` (#9811)](https://github.com/prometheus/prometheus/pull/9811/commits/91ce37cc0efeb688cfbeafa62d7992ff0fb7f08e#diff-34b9105f3a2061db734fcfb5304df321e648a86a319b5da251e110bfdaa0401f).

**Comment by msAlcantara** [comment]
> Thanks! There are some issues with `err`s now not being defined, as can be seen here: [`91ce37c` (#9811)](https://github.com/prometheus/prometheus/pull/9811/commits/91ce37cc0efeb688cfbeafa62d7992ff0fb7f08e#diff-34b9105f3a2061db734fcfb5304df321e648a86a319b5da251e110bfdaa0401f).

Fixed

**Review by LeviHarrison — APPROVED** [review]
Thanks!

**Comment by LeviHarrison** [comment]
Re-triggering CI

**Comment by cstyan** [comment]
Thanks @msAlcantara (and @LeviHarrison for the review). I like the simplification we get with `t.TempDir`.

**Pull request merged**
