### PR TITLE
Add more labels for endpointslice and endpoints role in k8s discovery

### PR DESCRIPTION
**Pull request by wangrzneu**
1. add endpoints annotation labels
2. add endpointslice annotation labels
3. add __meta_kubernetes_endpoints_label_* and __meta_kubernetes_endpoints_labelpresent_* labels
4. refine the code of getting labels from object meta, including name, label and annotation.

### CODE REVIEW

**Review by brancz — APPROVED** [review]
lgtm!

**Comment by wangrzneu** [comment]
@brancz PTAL

**Comment by wangrzneu** [comment]
@brancz Could you help to merge this PR? Thanks.

**Comment by roidelapluie** [comment]
this now needs a rebase

**Comment by wangrzneu** [comment]
@roidelapluie PTAL

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
