### PR TITLE
tsdb: Fix histogram validation

### PR DESCRIPTION
**Pull request by beorn7**
So far, `ValidateHistogram` would not detect if the count did not include the count in the zero bucket. This commit fixes the problem and updates all the tests that have been undetected offenders so far.

Note that this problem would only ever create false negatives, so we never falsely rejected to store a histogram because of it.

On the other hand, `ValidateFloatHistogram` has been to strict with the count being at least as large as the sum of the counts in all the buckets. Float precision issues could create false positives here, see products of PromQL evaluations, it's actually quite hard to put an upper limit no the floating point imprecision. Users could produce the weirdest expressions, maxing out float precision problems. Therefore, this commit simply removes that particular check from `ValidateFloatHistogram`.

### CODE REVIEW

**Comment by beorn7** [comment]
@leizor please review.

Fixes #12713 (which is the reason why I would like to see this in the upcoming release /cc @bboreham - note that the non-test change here is actually very small).

**Comment by beorn7** [comment]
@leizor I have to admit that I just dumped the changed bytel for the test in storage/remote/read_handler_test.go . It seems plausible that the byte pattern has changed now, but I didn't properly decode it. Did you do anything smarter when you touched the test the last time?

**Comment by roidelapluie** [comment]
Note: to be cherry-picked into 2.46

**Comment by bboreham** [comment]
This applies to native histograms only, right?

**Comment by beorn7** [comment]
> Note: to be cherry-picked into 2.46

I think this doesn't really create urgent issues in practice. We would accept an inconsistent histogram into TSDB if somebody exposed one.

**Comment by beorn7** [comment]
Sorry, missed the more significant issue described in #12713. So maybe that's worth cherrypicking into 2.46. On the other hand, we are still talking about an experimental feature only.

I think this should be cherry-picked into 2.45, the LTS release. (Maybe that's what you wanted to say anyway.)

**Comment by beorn7** [comment]
> This applies to native histograms only, right?

Yes.

**Comment by leizor** [comment]
> @leizor I have to admit that I just dumped the changed bytes for the test in storage/remote/read_handler_test.go . It seems plausible that the byte pattern has changed now, but I didn't properly decode it. Did you do anything smarter when you touched the test the last time?

@beorn7 That's pretty much what I did--I think I decoded the first few and checked them, but after that I was just verifying sample counts while stepping through in a debugger.

**Comment by linasm** [comment]
```go
c := nCount + pCount + h.ZeroCount; c > h.Count
```
@beorn7 I was trying to understand why a strict equality is not being enforced in this validation. Are there any valid cases when `c < h.Count`? I might be missing something obvious, but FWIW, there are no such test cases included in `TestHistogramValidation`.

**Comment by beorn7** [comment]
Observations of `NaN` are counted in `h.Count` but not in any bucket. This will be specified explicitly in the spec I'm currently writing (which, obviously, should have been completed long ago).

It's important to handle correctly, but it's in practice an edge case that will rarely happen.

**Comment by linasm** [comment]
Thanks, now it totally makes sense to me. I've submitted a minor (test only) PR to have this detail captured in test code: https://github.com/prometheus/prometheus/pull/12894

**Pull request merged**
