### PR TITLE
Cast value to float, as that's what the console templates expect.

### LINKED ISSUE #556: Alert templates type conflict: SampleValue v. float64
Attempts to interpolate `{{humanizeDuration $value}}` fail with a type error:

> wrong type for value; expected float64; got model.SampleValue

There's no way to work around this.

### PR DESCRIPTION
**Pull request by brian-brazil**
Fixes #556 

This whole function needs unittests, though it wouldn't help much with this particular case.

### CODE REVIEW

**Comment by juliusv** [comment]
The reason why we didn't change that yet is this: https://github.com/prometheus/prometheus/issues/556. But not sure, maybe we should just change it and offer all kinds of template formatting functions to make things look sane again.

**Comment by brian-brazil** [comment]
The reason it wasn't changed yet was I didn't have time to write the unittests - and now that I do I realise they wouldn't have helped catch this case. There's already `humanize` and `printf`.

**Comment by juliusv** [comment]
Hrm yeah, but people will get bad-looking values by default. On the other hand, fixing the functions to work in this case is more important. I guess I can't convince you to make them accept both `float64` and `model.SampleValue` :)

:+1: then, but needs a rebase.

**Comment by brian-brazil** [comment]
> I guess I can't convince you to make them accept both float64 and model.SampleValue :)

That'd only fix it for that, the reason there's the conversion to float64 is so that various math operations (including comparisons) will work.

**Pull request merged**
