### PR TITLE
Deduplicate containers attached to multiple networks

### PR DESCRIPTION
**Pull request by darshanime**
closes https://github.com/prometheus/prometheus/issues/8831

Signed-off-by: darshanime <deathbullet@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you.

I think what we want is a bool in the config that adds all the networks' labels to ONE targets per discovered task/service/etc, not more labels on existing duplicate targets.

**Comment by darshanime** [comment]
@roidelapluie, from the open issue, 
>find some other way to avoid duplicate targets.  

this PR tries to do that by:
- adding a single target for the container even if it's attached to multiple networks
- collating `name:ipAddr` of the other networks on a new label `__meta_docker_network_other_networks`

Let me know if I misunderstood your review comment.

**Comment by beorn7** [comment]
@roidelapluie could you clarify what's missing here, or if this is a dead alley we shouldn't go down further?

**Comment by bboreham** [comment]
I suspect #10490 implements the same feature.

**Comment by darshanime** [comment]
closing the PR in favor of #10490 👍

**Pull request closed without merging**
