### PR TITLE
PromQL: Promote negative offset and @ modifer to stable

### PR DESCRIPTION
**Pull request by beorn7**
I hereby propose to promote the negative offset and the @ modifer to stable with v2.33. This PR can be used to discuss it. If we decide to postpone the promotion, we can keep it around and merge it once we are ready to do so.

Following the argument that breaking the invariant that PromQL does
not look ahead of the evaluation time implies a breaking change, we
still need to keep the feature flag around, but at least we can
communicate that the feature is considered stable, and that the
feature flags will be ignored from v3 on.

That's what this PR implements.

However, personally I still don't consider these features breaking changes. The invariant is only broken for queries that were invalid queries before the feature existed. I see how the new features are problematic for implementers of caching proxies, but there was never an explicit stability guarantee that PromQL would never have features that allow accessing samples newer than the query time. When we start to consider emerging behavioral patterns as stability guarantees, we could declare many new features or even improvements and bug fixes as breaking changes, breaking the invariant that they surely change _some_ behavior. It's a question where to draw the line. That's ultimately a pragmatic decision without a precise answer. We probably all agree that the [obligatory XKCD comic](https://xkcd.com/1172/) draws the line at the wrong level, but this case is more problematic. I would like to find out where you all would draw the line in this case. Perhaps we can after all just drop the feature flag and enable the features by default already now.

### CODE REVIEW

**Review by codesome — APPROVED** [review]
LGTM

**Comment by juliusv** [comment]
I'm for just promoting it and removing the feature flag.

**Comment by roidelapluie** [comment]
I now also think if we have not a list of invariants documented, this is not a breaking change. Especially because it does not change existing queries results. This is an extra fonctionality at most .

**Comment by beorn7** [comment]
Thanks for the feedback. Since so far, you all agreed that the negative offset and the @ modifier should be a regular "always on" feature even in 2.x, I'll amend this PR to do so later today. But I'll wait until Wednesday to see if there are objections.

**Comment by beorn7** [comment]
I pushed an additional commit that permanently enables negative `offset` and the `@` modifier. If we decide that's the way to go, we leave the commit in. If we decide to keep those features behind a feature flag until v3.x, we simply remove the commit from the PR again.

Please let me know what you think. It would be cool to make the call by Wednesday, when I plan to cut the release candidate. (And since it is a release candidate only, we can still change our mind before the final release.)

**Comment by pstibrany** [comment]
> I pushed an additional commit that permanently enables negative `offset` and the `@` modifier. If we decide that's the way to go, we leave the commit in. If we decide to keep those features behind a feature flag until v3.x, we simply remove the commit from the PR again.

In Cortex we would prefer to be able to disable negative offsets (via field in `EngineOpts` struct) until we explore how to handle them properly with regards to caching. We also currently expose flag to disable @-modifier, but we could remove that.

**Comment by beorn7** [comment]
So what does everyone think about leaving the various Opts structs in place, but not exposing them in `prometheus` and `promtool`?

**Comment by beorn7** [comment]
To extend on the latter: Those Opts structs and their handling would be "dead code" from the Prometheus perspective, but once we introduce the next feature flag for PromQL, it would come in handy to have all the plumbing in place already.

Since it _also_ helps Cortex, I tend to do it that way (with some doc comments so that devs understand why it's there and aren't tempted to rip it out as "dead code").

If there is no other feedback within the next hours, I will amend this PR again to implement that idea.

**Comment by roidelapluie** [comment]
Side note: if we enable them by default, they would become de facto part of the PromQL compatibility suite, so cloud providers and downstream projects will need to support that to be "Prometheus Compatible".

**Comment by roidelapluie** [comment]
> So what does everyone think about leaving the various Opts structs in place, but not exposing them in `prometheus` and `promtool`?

LGTM

**Comment by beorn7** [comment]
OK, done. This now has the plumbing for the options in place, but in the `prometheus` and `promtool` binaries, both features are always enabled.

**Review by roidelapluie — COMMENTED** [review]
Extra nits:

- Now those features are undocumented.
- They should be always on in promql tests, too. Is it the case?

**Comment by beorn7** [comment]
The features are documented:
- https://github.com/prometheus/prometheus/blob/beorn7/promql/docs/querying/basics.md#-modifier
- https://github.com/prometheus/prometheus/blob/beorn7/promql/docs/querying/basics.md#offset-modifier

About the tests: You can pick for tests if they should be enabled or not, and both is still tested, which is important because we should still test the behavior when they are disabled as we are offering that behavior to users of the engine as a library.

**Comment by beorn7** [comment]
Oops, perhaps you wore thinking about the PromQL tests (in `testdata/...`), which I ignored so far.

In fact, they already had `EnableAtModifier` enabled always, but not `EnableNegativeOffset` (simply because none of those tests used that). I will enable the latter, too, and add a test case with a negative offset.

**Comment by juliusv** [comment]
Looks good, thanks! :+1: 

For keeping the old options around, we just shouldn't do that for too long, as we shouldn't incentivize anyone using the PromQL engine code in a way that is not PromQL comaptible anymore. Maybe we can keep it for the same time frame as compliant and compatible marks are meant to be valid for: "Both compliant and compatible marks are valid for 2 minor releases or 12 weeks, whichever is longer." (from https://prometheus.io/blog/2021/05/03/introducing-prometheus-conformance-program/)

**Pull request merged**
