### PR TITLE
Add Support for OAuth 2.0 Authorization for Remote Write Requests

### PR DESCRIPTION
**Pull request by LeviHarrison**
This PR adds support for OAuth 2.0 authorization on remote write requests by way of a provided `access_token`.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you.

This is already supported by Prometheus: you can use

```
authorization:
  credentials: <token>
```

What would be needed for oauth2:

- Provide the token endpoint
- Provide access key and secret key
- fetch the access token from the token endpoint

Additionally, I'd like to have this with the golang stdlib and in the prometheus/common repository.

Feel free to reach out if you want to help with that.

**Comment by LeviHarrison** [comment]
Sure, I'd be glad to take a look into implementing that.

**Comment by LeviHarrison** [comment]
By stdlib do you mean not using the [oauth2](https://pkg.go.dev/golang.org/x/oauth2) package?

**Comment by roidelapluie** [comment]
Yes :)

**Comment by LeviHarrison** [comment]
Ok. I think this will be a challenge, but a fun one!

**Comment by roidelapluie** [comment]
I think everything is there: Config, and even a Transport.

We can look at that together if you want, feel free to drop me a mail: roidelapluie at prometheus.io or use the contributor office hours: https://prometheus.io/community

**Comment by LeviHarrison** [comment]
Just opened a pull request [common#287](https://github.com/prometheus/common/pull/287)

**Pull request closed without merging**
