### PR TITLE
Bump prometheus common to v0.45.0

### PR DESCRIPTION
**Pull request by YannickTeKulve**
This bumps prometheus common to v0.45.0

### CODE REVIEW

**Comment by YannickTeKulve** [comment]
I just realized this also could be merged to 2.48 release. But i'm not sure if the version is already frozen.

**Comment by LeviHarrison** [comment]
Yeah, 2.48 is frozen. So unless this update of common has a serious bug fix, which it looks like it doesn't, this will end up in 2.49.

**Review by LeviHarrison — APPROVED** [review]
LGTM. Thanks!

**Comment by YannickTeKulve** [comment]
@LeviHarrison Thx!

**Pull request merged**
