### PR TITLE
console_libraries: Update to Bootstrap 4.3.1

### PR DESCRIPTION
**Pull request by roramirez**
PR #5506  update the version for Bootstrap. This change update the
assets for console_libraries on this version of Bootstrap.

cc @brian-brazil

### CODE REVIEW

**Comment by simonpasquier** [comment]
You would need to sign your commit to pass the DCO check:

```
git commit --amend -s
```

Then push again your change.

**Comment by roramirez** [comment]
Hi @simonpasquier This already done. Thanks!

**Comment by simonpasquier** [comment]
IIUC it affects v2.10.0? If so it might be good to have this PR against the `release-2.10` branch. Cc @beorn7 who's the release shepherd.

**Comment by beorn7** [comment]
Yes, I'd say this qualifies as a bug fix and should be a PR against the release-2.10 branch (from where it will later be merged into master).

Thanks @simonpasquier for your attention. and thanks @roramirez for catching the issue in the first place.

**Comment by roramirez** [comment]
I've change the PR against the `release-2.10 ` branch

**Pull request merged**
