### PR TITLE
add query labels command to promtool

### PR DESCRIPTION
**Pull request by infoverload**
Signed-off-by: Daisy T <daisyts@gmx.com>

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: Thanks

@brian-brazil We have a couple of pending (but approved) promtool PRs that'll probably need a bit of merge resolving once we start to merge them. Do we want to adhere to the feature moratorium for `promtool` as well?

**Comment by brian-brazil** [comment]
Probably easiest from a cherrypicking standpoint, hopefully we'll be clear in a week.

**Comment by infoverload** [comment]
@juliusv Done!

**Comment by infoverload** [comment]
@juliusv Done!

**Pull request merged**
