### PR TITLE
Implement full matching on external labels for remote read

### PR DESCRIPTION
**Pull request by csmarchbanks**
This will allow users trying to do a remote read to a prometheus with
external labels to properly do matches besides external_label="value".

According to the docs
> In communication with external systems, they [external_labels] are always applied only when a time series does not have a given label yet and are ignored otherwise.

Which led to the development of the following logic:

For each matcher in a query, check if it pertains to an external label.
If so then following table shows how the matcher needs to be transformed
before querying local storage.

| Matcher | Matched external label | Did not match external label | 
| --- | --- | --- |
| =   | label=value OR label=""    | label=value AND label!="" |
| !=  | label!=value OR label=""   | label!=value AND label!="" |
| =~ | label=~value OR label="" | label=~value AND label!="" |
| !~  | label!~value OR label=""   | label!~value AND label!="" |

This can be simplified to:
* external label is matched, then the internal label must match the matcher OR be empty
* external label is not matched, then the internal label must match the matcher AND not be empty

Each time an OR is done, twice as many queries are done (one for each of the cases), then the results are merged together. If there is a better way of accomplishing an OR, I am happy to hear it!

Signed-off-by: Chris Marchbanks <csmarchbanks@gmail.com>

Closes https://github.com/prometheus/prometheus/issues/4790

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR, I don't think this makes sense semantically. #4790 is the intended behaviour.

**Comment by csmarchbanks** [comment]
What exactly does not make sense semantically? I am happy to change this around. I tried to make sure that external_labels do not override any internal labels as the docs suggest.

I have tested with queries similar to those found in #4790 and they have started working with this PR. In fact I was doing something similar to that when I found this bug.

**Comment by brian-brazil** [comment]
We shouldn't be 2nd guessing the query the user has provided. In addition i don't think we should be adding features to support abuses of remote read.

**Comment by csmarchbanks** [comment]
I don't agree that this is 2nd guessing the query the user has provided. It is making the query actually work. If I provide a query like `{region!="europe"}`, and a series comes back with region="europe" that is not what I expect as a user. But it is exactly what happens right now.

What would be a solution that doesn't support abuse cases to you? Allowing regular promql matchers to work doesn't seem abusive to me.

**Comment by brian-brazil** [comment]
That sounds like you're doing cross-region remote read, which is not the intended use case. Do you have a use case that applies in the horizontal-sharding case?

**Comment by csmarchbanks** [comment]
I don't personally do this, but I remember a presentation/talking to people at PromCon that do 1 prometheus per team. It could be nice to have a central prometheus that could do ad hoc queries across multiple teams. 

Do I personally absolutely need this fix? Probably not. But it is not much fun when promql does not behave how I expect when testing out remote read.

**Comment by brian-brazil** [comment]
> It could be nice to have a central prometheus that could do ad hoc queries across multiple teams.

That's a good way to simultaneously take out all of your monitoring, and is thus explicitly not what remote read is for.

**Comment by csmarchbanks** [comment]
I am going to try to refocus this conversation.

I was experimenting with remote read and discovered that promql was broken when trying to query using external_labels. I looked online, and found #4790, which means other people are trying similar queries to me. I had some time, so I decided to fix the issue. From your first comment, you agree that #4970 is the expected behavior, which is what I am trying to implement. To move forward:

1. Reject this PR/behavior change on the grounds of it supporting abusive remote read cases. That is your/the Prometheus Team's prerogative. I would ask that the associated issue is also closed with a comment about not fixing this behavior for future reference.
2. Please provide specific feedback on the implementation of this fix. I chose a method that emphasized correctness of results according to the tests and documentation I could find. I am happy to consider alternative implementation ideas.

**Comment by brian-brazil** [comment]
> From your first comment, you agree that #4970 is the expected behavior, which is what I am trying to implement.

To clarify, I meant that the output the user was seeing was as expected.

**Comment by cboggs** [comment]
I'm also curious - if remote_read is not intended for standard Prometheus queries, what _is_ it intended for?

**Comment by brian-brazil** [comment]
> I'm also curious - if remote_read is not intended for standard Prometheus queries, what is it intended for?

Transition from Prometheus 1.x, and horizontal sharding.

**Comment by cboggs** [comment]
There's a good chance I'm missing some nuance here, but it seems that "horizontal sharding" is something that would require the ability to query shards in the same way one would query the local store, yea? If I have 3 "shards" in my DC, and a query that *should* return 12 series only returns 4, that seems broken to me.

**Comment by brian-brazil** [comment]
> is something that would require the ability to query shards in the same way one would query the local store, yea?

The external label setup is such that this is not an issue.

> I'm also not sure why your concern about "taking down all your monitoring at once" doesn't apply equally to the sharding use case as it presumably would to the multi-region sharding use case.

It does, but it's more restricted. It's a tradeoff against using federation for the same.

**Pull request closed without merging**
