### PR TITLE
initilise `ss` var only once - reduce mem usage a bit.

### PR DESCRIPTION
**Pull request by krasi-georgiev**

### CODE REVIEW

**Comment by brian-brazil** [comment]
I'd expect `ss` to be on the stack, have you benchmarks to indicate this makes a difference?

**Comment by krasi-georgiev** [comment]
yes , I did some mem pprof a while back when I was trying to improve promql , but can run again if you have suspicions.

**Comment by brian-brazil** [comment]
If you don't mind, as I'd expect this to be something that Go would handle automatically. Would be worth a feature request to Go if it doesn't put this on the stack.

**Comment by krasi-georgiev** [comment]
I am not able to replicate and your suggestion seems right so will close for now and will reopen if I see it again next time I pprof promql.

**Pull request closed without merging**
