### PR TITLE
Fix graph page for IE11

### PR DESCRIPTION
**Pull request by bege13mot**
Issue #4098 

Fix to load the main /graph page for Internet Explorer 11

### CODE REVIEW

**Comment by brian-brazil** [comment]
You need to `make assets`

**Comment by bege13mot** [comment]
Hi @brian-brazil ,

Thank you for your help. Could you please advise me about execution make assets? Why should we update bindata?

**Comment by brian-brazil** [comment]
The bindata is what Prometheus actually loads, so it's required for any js/css changes.

**Comment by bege13mot** [comment]
Got it. Thank you for your help

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
