### PR TITLE
consul: support reading token from a file

### LINKED ISSUE #6140: feature: Support loading file for Consul Token
## Proposal

I use vault as a secret storage solution and I think it could be useful to support loading the consul token from a file like the `bearer_token_file`. For exemple, the Marathon SD already support it.

What do you think ?
If you like it, I could start working on a PR.

Thanks

### PR DESCRIPTION
**Pull request by roidelapluie**
Closes #6140 

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
What's the use case for this? I wouldn't think these would be rotated automatically.

**Comment by roidelapluie** [comment]
If you use hashicorp vault, as described in the issue, they would be rotated.

**Comment by roidelapluie** [comment]
In particular, https://www.vaultproject.io/docs/agent/index.html with a file sink.

Note that in particular, vault and consul are from the same company so the chances are high that you use both.

**Comment by brian-brazil** [comment]
Hmm, can those actually be tied together? If this were possible and common I'd expect to be able to find a guide on how to do it, which I can't.

It also looks like Consul supports standard bearer tokens now, so we should check when that happened and see if we can switch.

**Comment by roidelapluie** [comment]
they support both but I decided to use X-Consul-Token as this is what the native go client uses.

here is the documentation to have vault creating short term rotating consul tokens:

https://www.vaultproject.io/docs/secrets/consul/

**Comment by brian-brazil** [comment]
We already have code to deal with normal bearer tokens though.

**Comment by roidelapluie** [comment]
Ok I will normalize on normal bearer

**Comment by wpjunior** [comment]
@roidelapluie Could I help you to finalize this issue ?

**Pull request closed without merging**
