### PR TITLE
Merge main into sparsehistogram

### PR DESCRIPTION
**Pull request by beorn7**
_This is only for the sparsehistogram branch._

It's about time again: merge main into sparsehistogram.

(Thanks to @bboreham 's work on the signature functions, this resolves a few TODOs for the histogram_quantile function.)

### CODE REVIEW

**Comment by beorn7** [comment]
There is nothing we can do right now about the buf.build lint errors. The things are just copied from prometheus/client_model (where we don't do that linting yet).

I guess this test can be disabled somehow for those files, but I don't know how right now.

**Comment by Nexucis** [comment]
maybe using this option in the config can help: https://docs.buf.build/lint/configuration#allow_comment_ignores

**Comment by beorn7** [comment]
Thanks @Nexucis . There is actually a buf.yaml already in place for the remote write/read protobufs. I'll just piggyback on that.

**Comment by beorn7** [comment]
Great, it worked.

Merging now, as @codesome is still on vacation (and this is only for the sparsehistogram branch).

**Pull request merged**
