### PR TITLE
Prepare release 3.1.0

### PR DESCRIPTION
**Pull request by bboreham**
I found a couple of PRs that were in 3.0.0 but not specifically cited in the CHANGELOG.

### CODE REVIEW

**Review by jan--f — APPROVED** [review]
Prombench looks good to my untrained eyes, changes too.

**Comment by jan--f** [comment]
Hmm I think this updates fsnotify to 1.8.0 again causing the leak test on windows to trigger.
#15466 has more details, #15694 reverted the revert.

**Review by jan--f — CHANGES_REQUESTED** [review]
We should probably downgrade fsnotify to 1.7.0 again.

**Comment by bboreham** [comment]
I downgraded fsnotify in #15700 and rebased this PR.

**Review by jan--f — APPROVED** [review]
:+1:

**Comment by bboreham** [comment]
The excess CPU usage and higher latency are concerning.

image

**Comment by bboreham** [comment]
But the right PR is also concerning
image

**Comment by bboreham** [comment]
I took profiles and cannot see any particular difference.
Wondering if it is some environmental thing on the nodes - across 24h it comes and goes, but the benchmark is designed to be stable.

image

**Pull request merged**
