### PR TITLE
Release 2.33.2

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
I have already included #10279

**Review by LeviHarrison — APPROVED** [review]
Thanks for helping expedite this. Hopefully #10279 is released today but if not we should remember to change the date of the release.

**Review by csmarchbanks — APPROVED** [review]
:+1: I have merged #10279 so this is ready to go now.

**Comment by beorn7** [comment]
Thanks for doing this. @roidelapluie are you also performing the remaining steps of the release procedure?

**Comment by roidelapluie** [comment]
Yes

**Pull request merged**
