### PR TITLE
otlptranslator/update-copy.sh: Fix sed command lines

### PR DESCRIPTION
**Pull request by aknuds1**
I realized that the `sed` command lines in `storage/remote/otlptranslator/update-copy.sh` are non-standard, at least they won't work with GNU sed. The reason being the initial empty argument (`''`), which might be for the OSX version of sed?

I propose we remove the initial empty argument, to make this script work with GNU sed. I tested my changes locally, and they work (i.e. the copied files don't change versus main).

### CODE REVIEW

**Comment by gouthamve** [comment]
Thanks for this Arve! I got this through blind stackoverflow copying.

Unfortunately the new change doesn't work for MacOS sed:

```
+ sed -i s#github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus#github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheus#g ./prometheusremotewrite/helper.go ./prometheusremotewrite/histograms.go ./prometheusremotewrite/metrics_to_prw.go ./prometheusremotewrite/number_data_points.go
sed: 1: "./prometheusremotewrite ...": invalid command code .
```

Do you know if we can use some other command or tool to do this platform agnostically?

**Comment by aknuds1** [comment]
@gouthamve if we are going to support OSX sed (I always install GNU sed in OSX), we need some heuristics for choosing the right command line based on OS.

**Comment by gouthamve** [comment]
So I did run `brew install gnu-sed` thanks to @jesusvazquez 

But the command still failed because we need to now run `gsed`? Can we document what MacOS users need to do in the readme? I don't expect a lot of people to run this script so if we can provide clear instructions, that'd be best. We don't need to add complexity to the script.

**Comment by aknuds1** [comment]
@gouthamve I might have a working solution, testing it now.

**Comment by aknuds1** [comment]
@gouthamve I pushed a cross-platform revision, PTAL.

**Review by gouthamve — APPROVED** [review]
This works!!

Thanks a lot for figuring this out <3

**Pull request merged**
