### PR TITLE
Run gofumpt on all files

### PR DESCRIPTION
**Pull request by prymitive**
Getting golangci-lint errors when building on my laptop, possibly because I have newer version of gofumpt then what it was formatted with.
Run gofumpt -w -extra on all files as it will be needed in the future anyway.

Signed-off-by: Łukasz Mierzwa <l.mierzwa@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can we have an update of gofumpt in our CI?

**Comment by prymitive** [comment]
Is that only https://github.com/prometheus/prometheus/blob/main/Makefile.common#L86 which needs updating?

**Comment by prymitive** [comment]
actions workflow file also needs an update

**Comment by prymitive** [comment]
>   Warning: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)

This needs addressing before we can upgrade golangci-lint

**Comment by prymitive** [comment]
Ready now

**Comment by roidelapluie** [comment]
thanks!

**Pull request merged**
