### PR TITLE
Improve resource isolation in test code

### PR DESCRIPTION
**Pull request by invidian**
As a prerequisite to #9514, which enables parallel execution for all tests, this PR fixes various code, which shares objects between the tests, which when executed in parallel will result in races or flaky tests.

### CODE REVIEW

**Review by cstyan — COMMENTED** [review]
:+1: the remote write file changes look fine to me

**Comment by invidian** [comment]
Rebased to resolve conflicts.

**Comment by invidian** [comment]
@roidelapluie what do you think about this PR? Is it small enough to be reviewed and merged?

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
This is good to me, but could we change the function names? e.g. `conf()` -> `testConfig()` etc?

**Comment by invidian** [comment]
>This is good to me, but could we change the function names? e.g. conf() -> testConfig() etc?

Make sense, done :)

**Review by roidelapluie — APPROVED** [review]
Thanks!

**Comment by invidian** [comment]
Thanks!

**Pull request merged**
