### PR TITLE
test chunk pool

### PR DESCRIPTION
**Pull request by krasi-georgiev**
testing a tsdb PR

Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by csmarchbanks** [comment]
Looking at the graphs it doesn't look like prombench is doing any queries?

**Comment by krasi-georgiev** [comment]
hm yeah the the dashboards don't show any query timings but I double checked and the querier does indeed show some logs that it runs different queries.

@csmarchbanks maybe run some heavy ones manually on both as well.
PR - prombench.prometheus.io/4962/prometheus-pr
master - prombench.prometheus.io/4962/prometheus-release

@sipian can you see why the the query dashboards are empty? maybe changed metrics names?
http://prombench.prometheus.io/grafana/d/7gmLoNDmz/prombench?orgId=1&var-RuleGroup=All&var-pr-number=4962&from=now-3h&to=now

**Comment by sipian** [comment]
@krasi-georgiev I seem to have found the issue. Testing a fix now.

**Comment by krasi-georgiev** [comment]
will restart after the queerer is fixed

/benchmark cancel

**Pull request closed without merging**
