### PR TITLE
use consistent margin-bottom for all alert kinds

### PR DESCRIPTION
**Pull request by victorhaggqvist**
`.alert-danger` looks like the odd one out having `margin-bottom: 10px` for some reason (something from pre-react?). The rest has bootstrap default (16px). 

Updated all `.alert` to have the same and a bit less than `.alert-danger` at `.2rem`, to fit some more rows above the fold, as there are quite alot of whitespace as-is. If thats undesirable, I can keep all at `10px` as well.

Visual change

old | 
-----|
am-old| 

new |
-----|
am-new|

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you for your pull request and welcome in the community :)

space

The space below the filenames is bigger than above, which seems strange to me. How can we better split it? Maybe add space above file names?

**Comment by victorhaggqvist** [comment]
@roidelapluie Something like that should do, which does add an unnecessary margin at the first file, but the damage of that is probably overall negligible.

**Comment by roidelapluie** [comment]
Thanks!

**Review by roidelapluie — APPROVED** [review]

**Comment by juliusv** [comment]
:+1: Thanks!

**Pull request merged**
