### PR TITLE
[test] Add tests for promql/parser.Tree()

### PR DESCRIPTION
**Pull request by liguozhong**
[test] Add tests for promql/parser.Tree()

### CODE REVIEW

**Comment by roidelapluie** [comment]
Maybe we can update existing tests instead of writing a new ones? Also it is not clear if this year is needed, is this function used by Prometheus?

**Comment by liguozhong** [comment]
> Maybe we can update existing tests instead of writing a new ones? Also it is not clear if this year is needed, is this function used by Prometheus?

This function has not been used inside Prometheus, presumably for other systems.
 When I saw this function, I found that this function was very complex, but there was no test function, so I added one test.

**Comment by slrtbtfs** [comment]
The only use case for that tree function I'm aware of is debugging the parser.

Having a test for it doesn't hurt, though.

**Comment by gouthamve** [comment]
Hrm, do we really need unit-tests for this though? There are regression tests and we are not sure if tests are warranted for this code. We've decided to close this as part of our bug scrub, sorry! Thanks for submitting the PR though, would always appreciate more tests for a lot of the components, but sadly not this one :(

**Pull request closed without merging**
