### PR TITLE
Implement changes() function.

### PR DESCRIPTION
**Pull request by juliusv**
changes() takes a range vector and returns the number of times a value
has changed in the given time window for each time series as an instant
vector.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by aecolley** [comment]
It's like you read my mind, except 5 hours ahead of time, and with working code and tests. Nice work!

**Comment by juliusv** [comment]
@aecolley I looooooove the new testing language that @fabxc created for us :) It makes query language testing such a breeze.

**Pull request merged**
