### PR TITLE
Graph Color for New UI

### PR DESCRIPTION
**Pull request by suyashtava**
Issue: https://github.com/prometheus/prometheus/issues/8256

Reference PR: https://github.com/prometheus/prometheus/pull/10172

### CODE REVIEW

**Comment by suyashtava** [comment]
@juliusv Is there any way I can sign off.

I included all the "Signed-off-by: suyashtava <suyashtava@example.com>" in each commit-msg, ut still it is not passing DCO

**Comment by suyashtava** [comment]
@juliusv Signed off with a merge.

Added the issue and previous PR link as a reference.

It is passing all the test cases as well.

Can I get it approved and merged please?

**Comment by juliusv** [comment]
:+1: Wonderful, thanks again!

**Comment by suyashtava** [comment]
Thank you will be happy to contribute more, incase u find something on which I can work, pls tag me there aswell. :)

**Pull request merged**
