### PR TITLE
Upgrade several dependencies

### PR DESCRIPTION
**Pull request by mmorel-35**
Hi !

This upgrade several dependencies and includes the adaption of the concerned tests.
This also increases the number of pull-request allowed on npm dependencies.

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: Thanks! :)

@nexucis As my trusted dependabot person, does the PR limit bump for it look good?

**Comment by Nexucis** [comment]
From my side I don't see the point of increasing the number of PR opened for the frontend. By default it's 10.
Moreover dependabot usually try to upgrade to dependencies to the latest version. And for a certain amount of dependencies for the frontend, each upgrade required to take time to migrate things because well many things are broken between major versions.

I'm just saying that increasing the number of PRs for dependabot for the for frontend won't help to upgrade the dependencies.

**Comment by mmorel-35** [comment]
Hi @Nexucis ,
I can remove the change for the open-pull-requests-limit. 
To my knowledge, the default amount is 5 .
What do you prefer ?

**Comment by Nexucis** [comment]
> To my knowledge, the default amount is 5 , see this documentation.

Ah thanks for refreshing my mind :). I thought t'enebut you are right !
I would prefer to keep the default value for the reasons I explained above.

Once the limit changed is removed we can merge this PR @juliusv

**Comment by juliusv** [comment]
:+1: Thanks :)

**Pull request merged**
