### PR TITLE
Fix tests that were broken by #7009

### PR DESCRIPTION
**Pull request by beorn7**
Hi :cloud_with_rain::crown: and :st_barthelemy::fish:, 

here the promised fix for #7009 .

### CODE REVIEW

**Comment by bwplotka** [comment]
Anyway, thanks. LGTM (:

**Comment by bwplotka** [comment]
And now you need elaborate @beorn7 what those emojis mean... (:

**Comment by beorn7** [comment]
> How we broke it?

My theory is in this comment: https://github.com/prometheus/prometheus/pull/7009#issuecomment-601239616

In short, I think our CircleCI setup just runs the tests in the branch the PR wants to pull from. IIRC, with Travis, we performed the merge on the CI pipeline and _then_ ran the test. @simonpasquier might know more.

**Comment by roidelapluie** [comment]
:cloud_with_rain::crown: is king of the rain, whose french translation is roidelapluie

**Comment by beorn7** [comment]
> And now you need elaborate @beorn7 what those emojis mean... (:

@roidelapluie already figured out himself. @bwplotka you should be able to figure out yours. (o:

**Comment by beorn7** [comment]
To expand on my theory: I guess the fundamental problem with the "old" setup (we presumably had with Travis) is that at the time the test run, it will do the merge, but that's just one point in time. If, in the meantime, something changes in master, we might still now have a broken test after the merge. So perhaps the current setup is actually saner. _After_ the merge, we get a test run anyway, and this is how I noticed that #7009 broke the tests.

**Comment by simonpasquier** [comment]
@beorn7 I think you've nailed it perfectly. It happens from time to time but not frequently from what I remember.

**Comment by bwplotka** [comment]
I got the fish one, but I did not know there is `:saint barthelemy` :st_barthelemy: emoji!!! XD

**Pull request merged**
