### PR TITLE
Enforce the usage of github.com/stretchr/testify/require

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Amazing, LGTM

**Review by codesome — APPROVED** [review]

**Comment by bboreham** [comment]
I would like to know why.

**Comment by codesome** [comment]
All I can think right now is: Keep it consistent. I haven't dug the differences between require and assert, but I would like to know if you had some use for assert.

**Comment by roidelapluie** [comment]
Inconsistent use of require and assert caused panics during tests. It is a way to make sure tests fail early, which is the best way to avoid those panics.

We can not expect all the contributors to learn the difference between both, especially because we want to lower the barrier to contribute. Choosing a single one (even if it is not the perfect technical solution for every situation) helps reaching that goal.

**Comment by bboreham** [comment]
> if you had some use for assert

Yes, the use for `assert` is to allow all incorrect results to be reported on a single run of a test. Also it is significantly faster, but that wasn’t a factor on the day I asked the question. 

(Clearly you are free to make the rules on a project you maintain, but it’s nice to know why they are set up that way)

**Pull request merged**
