### PR TITLE
remove deprecated and replaced remote-write-receiver flag from enable-feature

### LINKED ISSUE #13206: remove the `remote-write-receiver` flag from `enable-feature`
### Proposal

This flag has been deprecated and user should use `--web.enable-remote-write-receiver` to enable this feature.

_edit_
This issue needs no work at this point. https://github.com/prometheus/prometheus/pull/13435 is the proposed fix. We can only merge this when we have a prometheus 3 branch, so this issue is done but will stay open for a bit.

### PR DESCRIPTION
**Pull request by pawarpranav83**
Fixes #13206

### CODE REVIEW

**Comment by pawarpranav83** [comment]
We would also need to update this blog ig.
https://prometheus.io/blog/2021/11/16/agent/

**Comment by bboreham** [comment]
Thanks for the PR.  Blog can be updated via PR here: https://github.com/prometheus/docs/tree/main/content/blog

**Comment by jan--f** [comment]
@pawarpranav83 Could uou resolve the conflicts here, then we should be good to go.

**Comment by krajorama** [comment]
Hello from the bug scrub: @pawarpranav83  gentle reminder to resolve conflicts so we can merge.

**Comment by pawarpranav83** [comment]
Created new PR: #14526

**Pull request closed without merging**
