### PR TITLE
some_metric{{a="1",b="2"}} & some_metric{a=-"1,2,3"}

### PR DESCRIPTION
**Pull request by hantuo**
1. 
`cpu_time{{job="prom",instance="host1",cpu="cpu0",mode="free"}}`

`{{...}}` means "I give all labels"(may be the most likely case),we can optimize this kind of query by **avoid fingerprints for label pair finding**,it`s 10X - 100X faster in our production env(40000 hosts,100M metrics).

2.
`{instance=-"host1,host2,host3"}`

`=-` means "Match items in list",best used with `{{...}}`,it\`s better than `{instance=~"host1|host2|host3"}` by **avoid label values for label name finding**

I think it`s a very small change, but very effective, we use it in out production env already, maybe we can add it to 2.0 release?
(This pull request is just for propose, and not be expected to be merged)

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thank you for the PR. I don't think it should be the user's responsibility to microoptimise their queries, that's something we should be doing in the background, such as #2651

**Comment by hantuo** [comment]
@brian-brazil 
I can get your point about `=-`, I agree with you (but have reservations 😄  )
But I don\`t think `{{...}}` is a microoptimise, we can`t do it in the background with our current storage(also 2.0)

**Comment by brian-brazil** [comment]
The presumption is that you always know what your labels are, if there are extra labels coming from elsewhere sometimes then that's something to be fixed in your label taxonomy.

**Comment by Gouthamve** [comment]
Also, I don't think in the 2.0 storage we are not having a mapping from "all labels" --> series that allows simple lookups. We will have to do the intersecting anyways.

**Comment by hantuo** [comment]
@brian-brazil Thanks for reply.
Once the presumption is true, like {__name__="prometheus_.*|node_.*"} and so many other env, `{{}}` really much faster than `{}`, one more FAST-STUPID option is not bad, isn't it?

**Comment by hantuo** [comment]
> if there are extra labels coming from elsewhere sometimes then that's something to be fixed in your label taxonomy.

when new labels coming,
1. I don't care about the new labels : {}query not change,{{}}query not change too.
2. I care about them : {{}}query must change, also {}query

**Comment by brian-brazil** [comment]
> I don't care about the new labels 

You need to care about them. If a new job-level label is added, everything breaks. This is why without is recommended over by, it works in a variety of user setups.

**Pull request closed without merging**
