### PR TITLE
Scraper config reload bugfix

### PR DESCRIPTION
**Pull request by krasi-georgiev**
When the discovery manager send the target list to the scrape manager , the scrape manager needs to read the configuration for the given target set(job name). 
If the discovery manager send targets for a job which configuration is still not loaded in the scrape manager it will fail to create scrape pools for this target set(job name).

This happens at boot time or when reloading all configs.

Another fix would be to send the job configs when sending the  targets list from the Discovery manager.

the config handling is due for some refactoring anyway so I think best to have this fix for the 2.1 release and think about the refactoring after that.

### CODE REVIEW

**Comment by Gouthamve** [comment]
This also needs to handle the config reload when the HTTPClientConfig changes.

**Comment by Gouthamve** [comment]
LGTM. Tests remain to be ported from https://github.com/prometheus/prometheus/pull/3673/

**Comment by Gouthamve** [comment]
merge on green.

**Comment by krasi-georgiev** [comment]
@Gouthamve didn't know this new command :)

**Comment by krasi-georgiev** [comment]
@Gouthamve closes  #2756, #2830

**Pull request merged**
