### PR TITLE
[FEATURE] add anomaly detect functions in promql/function.go

### PR DESCRIPTION
**Pull request by durdendong**
[FEATURE] add anomaly detect functions in promql/function.go
Functions list:
"iad_n_sigma"
"iad_n_sigma_upper_bound"
"iad_n_sigma_lower_bound"
"iad_box_line"

How to use?
type promql like: 
iad_n_sigma(metric_name[60m],3), make sure that the input should be a range vector.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you.

There is some discussions on the mailing list right now: https://groups.google.com/g/prometheus-developers/c/ejm-NmoubX0

Could you join the discussion here?

thanks.

**Comment by beorn7** [comment]
We discussed this during the bug scrub.

There is an overarching problem here: We still haven't come to terms when we want to add "special purpose" functions to PromQL. There is a topic on the dev-summit agenda to find out about it. Once we have clarity, we can decide how to proceed with this proposal.

**Comment by beorn7** [comment]
Update from the dev-summit: As long as there aren't relatively easy ways of implementing a given function based on existing PromQL primitives, we are generally open to adding new functions and operators behind a feature flag (where people can play with them and we can later either promote them to stable or remove them again). There should be _some_ credible claim of usefulness, of course, but as I understand the recent consensus from the dev summit, we want to keep the bar quite low here.

**Comment by beorn7** [comment]
Hello again from the bug scrub. As said, we are willing to accept functions like this behind a feature flag. But no activity happened on this PR afterwards. We'll close this now, but whoever wants to pick this up, please re-open or re-create.

**Pull request closed without merging**
