### PR TITLE
Responding to #5585: Check for syscall errors

### PR DESCRIPTION
**Pull request by pswica**
Responding to https://github.com/prometheus/prometheus/issues/5585

I try to log an Error, instead of a warning, if there's a syscall error in `scrape.go`. Please let me know wherever I can improve.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you explain what you're trying to do?

**Comment by pswica** [comment]
Thanks so much for reviewing this. I'm trying to log an Error (rather than Warning) if the application catches a syscall error--that is, something like a ENOMEM (enough memory) error.

**Comment by brian-brazil** [comment]
It's already a warning, and this seems to be tackling things at the wrong level. What exact syscall is returning this?

**Comment by pswica** [comment]
I changed it to Error as this seemed to be a wanted/requested feature (instead of silently failing when the application is out of memory). I chose syscall errors to generate Error as I think most seem to warrant that.

I'm not sure which syscall (any call which asks for more memory when there is none could generate it), but would definitely be ENOMEM which has error code 12.
```
errno 12
>>ENOMEM 12 Cannot allocate memory
```

This matches the error message that @woodsaj reported: `write /prometheus/data/wal/00002922: cannot allocate memory`. 

Do you have any suggestions on how to go about this (I'm still new to open source, so I would love to learn more)? Also, let me know what further information you need.

**Comment by brian-brazil** [comment]
Changing the severity of a log message doesn't solve any problems. The question here is why this isn't either panicing or OOMing.

**Comment by pswica** [comment]
Oh I see what you are saying, yes that's definitely a better approach. Maybe this weirdness is due to using:

```
func yoloString(b []byte) string {
	return *((*string)(unsafe.Pointer(&b)))
}
```

Do you think a good approach would be replacing this with the safer golang construct `string([]byte)`? Let me know if this is something you'd welcome and I can implement this. Otherwise, please feel free to close this PR as I completely agree with your logic and thoughts.

**Comment by brian-brazil** [comment]
That's nothing to do with it, that'd cause different problems.

**Pull request closed without merging**
