### PR TITLE
Add unit test case for func Type in record.go

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @gouthamve @codesome  WDTY?

**Comment by fenggw-fnst** [comment]
Thanks for your review!
But I think TestRecord_EncodeDecode does not cover the test of function "Type".
The "Type(dec.Byte())" in dec.Series, dec.Samples and dec.Tombstones is not a function call, it's a type conversion.
Package test show that the new TestRecord_Type will improve test coverage of statements 82.9% -> 89.5%.

**Comment by fenggw-fnst** [comment]
@codesome Could you please take a look again? Thanks!

**Comment by fenggw-fnst** [comment]
PTAL, thanks!

**Pull request merged**
