### PR TITLE
Support to query elements by a specific time

### PR DESCRIPTION
**Pull request by kdada**
Implement #1246.

UI:
image

There are two options in URL query string:
- g[index].moment_input: date string. ex. 2018-10-20 10:11:12
- g[index].timestamp: unix timestamp. ex. 1540012198.141

If time and timestamp are provided, timestamp is choosen. After page loading, timestamp will be applied to moment_input and removed from URL.

Examples of URL:
```
/graph?g0.expr=go_memstats_alloc_bytes_total&g0.tab=1&g0.moment_input=2018-10-20 05:10:08
/graph?g0.expr=go_memstats_alloc_bytes_total&g0.tab=1&g0.timestamp=1540013881.663
```

### CODE REVIEW

**Comment by kdada** [comment]
@grobie @SuperQ please take a look.

**Comment by kdada** [comment]
@grobie @SuperQ please take a look.

**Comment by kdada** [comment]
@grobie @SuperQ please take a look.

**Comment by kdada** [comment]
You can't comment at this time.

**Comment by kdada** [comment]
t

**Comment by kdada** [comment]
@SuperQ @stuartnelson3 What's the next?

**Comment by stuartnelson3** [comment]
I'm happy with the PR, so unless someone disagrees, I'll merge this later today.

**Comment by kdada** [comment]
@stuartnelson3

**Comment by brancz** [comment]
we're in code freeze for 2.5.0, so I'm reverting this until that's lifted

**Pull request merged**
