### PR TITLE
Capitalizing first letter of all log lines

### PR DESCRIPTION
**Pull request by thaniri**
# What this change is

This is a solution for some inconsistency in capitalization in log messages. https://github.com/prometheus/prometheus/issues/6972

I grepped my repository with this regex: `level\.(Warn|Debug|Info)\(.*\)\.Log\(\"msg\", \"[a-z]` and looked for all log lines that matched. Changing capital letters where necessary.

I did _not_ change these two log lines which matched:

https://github.com/prometheus/prometheus/blob/master/storage/remote/queue_manager.go#L826 - because runShard is actually matching the capitalization of a function.

https://github.com/prometheus/prometheus/blob/master/discovery/file/file.go#L340 - because file_sd is actually matching the capitalization of the [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config).

As for the comment on errors in the Github issue from brian-brazil, I elected to capitalize logs that include error objects because we have precedent for this pattern https://github.com/prometheus/prometheus/blob/master/documentation/examples/remote_storage/remote_storage_adapter/main.go#L283 (and also on line 299 and 330 in this file). I did *not* capitalize log lines of the Error level, though.

# Testing Done

Ran `make test` in the base directory of my repository and everything passed.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1: 

Just need to get the tests passing.

> I elected to capitalize logs that include error objects because we have precedent for this pattern

I was talking about the error object themselves.

**Comment by thaniri** [comment]
It looks like the failing tests in circleci are all from the React frontend. In around 8 hours I will attempt to look into them.

**Comment by thaniri** [comment]
I rebased from master hoping that it would fix the front-end code. Unfortunately no help.

I also checked that other recent builds were having the same failures:

- https://circleci.com/gh/prometheus/prometheus/28758?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/prometheus/prometheus/28754?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/prometheus/prometheus/28792?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It appears that there was a change pushed to master which broke the unit testing for the front-end.

If I look at the latest [commits](https://github.com/prometheus/prometheus/commits/master) to master I can see some merges were allowed without having passing builds.

This is the one that changed front-end code (yarn package management! grrr) most recently with a failed build: https://github.com/prometheus/prometheus/commit/24ecae995691dabf782a6b4a7464f7aab561b554. Fascinatingly, the build did seem to succeed in [circleci](https://circleci.com/gh/prometheus/prometheus/28648?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) It had a failed build when actually [merging to master](https://circleci.com/gh/prometheus/prometheus/28685?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). In the [history](https://github.com/prometheus/prometheus/commits/master/web/ui/react-app) we can see the front-end code hasn't been changed that often so we can probably pinpoint it to this one change.

In order to try to reproduce the problem:

1. Install yarn `apt install yarn=1.22.0-1`
2. `cd ~/go/src/prometheus/web/ui/react-app`
3. `yarn install`
4. `yarn build`
5. `yarn test --no-watch --coverage`
6. Press 'a' at the prompt to run all tests

However all tests pass on my desktop.

I have one question, one recommendation:

**Question**: if I want to run a CI test on my own branch without creating a pull request how should I do that? Basically I want to try reverting the recent change to the yarn dependencies and see if that makes the problem go away. Unfortunately I've spent the last couple of years trying to avoid Javascript as much as possible and I am reluctant to dig into the front-end errors until I have at least done something like the react tutorial.

**Recommendation**:
My recommendation is to add -x to [scripts which are used in the build process](https://github.com/prometheus/prometheus/blob/master/scripts/build_react_app.sh). This makes reading the logs from a circleci build easier.

**Comment by thaniri** [comment]
There are still people getting this:

https://circleci.com/gh/prometheus/prometheus/29086?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

https://circleci.com/gh/prometheus/prometheus/29069?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

How are some pull requests passing their builds?

https://github.com/prometheus/prometheus/pull/7066

There is some magic that I, and clearly some other people, am not getting. We are only touching go code and having react code fail tests.

**Comment by thaniri** [comment]
Tests pass now.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
