### PR TITLE
cmd/prometheus: remove govalidator for url validation

### PR DESCRIPTION
**Pull request by pgier**
The usage of govalidator is redundant with the call to url.Parse for
url validation. Removing it has the following benefits:

 - The explicit error message is displayed instead of just a generic
   valid/invalid message
 - Slightly smaller code with one fewer external dependency
 - Speed improvement by removing duplicate call to url.Parse (inside
   govalidator.IsURL()
 - Resolves issue #2717

The only potential drawback of removing govalidator is that certain
URLs will be considered valid which were previously invalid. For example:

 - URLs with hostnames that start and/or end with an underscore (http://\_example.com_)
 - URLs with hostnames that contain some special characters (http://foo&*bar.org)

These are valid URIs according to RFC 3986 and valid domain names per RFC 2181,
however they are not valid hostnames per RFC 952.

### CODE REVIEW

**Comment by pgier** [comment]
If it's preferable to have stricter hostname requirements, I can add a regex validation in a separate commit.

**Comment by pgier** [comment]
I think url.Parse("'https://url/prometheus'") causes a validation error only because it contains a colon.  Something like "'https//url/prometheus'" will pass validation treating the entire string as the path with a null scheme and hostname.

**Comment by grobie** [comment]
I think we should make sure to continue handling such problematic inputs. Do you have examples for paths including quotes? Are there valid cases with quote at the beginning/end of an input? Can we manually check for that?

**Comment by pgier** [comment]
The quote in the url doesn't seem to cause any problems as long as it's still a valid URI path.  I did couple quick tests, for example:

    prometheus -web.external-url="'mypath'"

This allows the web UI to be accessed at:

    http://localhost:9090/%27mypath%27

So I think it would be ok to allow this even though it's probably a very uncommon use case.

**Comment by grobie** [comment]
@pgier I think we expect a real URL and not only a path section in the value of `web.external-url`. Therefore, we should continue to validate the input accordingly. It must not only be a path.

**Comment by pgier** [comment]
The existing code (before the proposed change) supports some relative paths, so I wasn't sure about the requirements.  For example "test" is rejected, but "example.com/test" is accepted but interpreted as a relative path instead of a hostname/path.
If an absolute URI is required, it's better to use url.ParseRequestURI instead of url.Parse.  And we can also check that a valid scheme (http/https) was given.

**Comment by pgier** [comment]
Removed the requirement for absolute URL and added a check for single or double quotes at the beginning or end of the web and alertmanager URLs.  Also rebased against latest master.

**Pull request merged**
