### PR TITLE
Make window reload on history back action.

### PR DESCRIPTION
**Pull request by varunpatro**
Simple fix for history back events.

Because of `onpopstate`, `window.location.reload();` is only triggered when the user clicks back button or `history.back();`

Works good for me.

---

This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/1143)

### CODE REVIEW

**Comment by juliusv** [comment]
@varunpatro Thanks, testing!

**Comment by juliusv** [comment]
Hmm, this now does a full page reload every time you change the expression input and defocus it because the defocus fires a change event for the expression input, which re-encodes the expression in the hash part of the URL, which triggers as popstate event:

1) enter `foo` in the expression input field
2) click outside the expression input field
3) page reloads (expected behavior: nothing happens)

Looking a bit more.

**Comment by juliusv** [comment]
Ok, one further problem is that the URL hash part is only updated when defocusing the expression input, but not if I enter `foo` and just press "Enter". It should also be updated in that case, but somehow that doesn't trigger the `change` event on the expression input field, which then should trigger the URL update.

**Comment by juliusv** [comment]
One more comment: the code for the history handling is `/graph`-specificl, so it should ideally go into https://github.com/prometheus/prometheus/blob/master/web/blob/static/js/graph.js, not the `_base.html`.

**Comment by varunpatro** [comment]
Thanks for the feedback. Shall fix these issues and update this PR.

**Comment by krasi-georgiev** [comment]
@varunpatro is it too late to revisit this? It would be nice to make the back button work as expected.

**Comment by krasi-georgiev** [comment]
@brian-brazil this one seems useful , but shall we close it for no activity and reopen if needed?

**Pull request closed without merging**
