### PR TITLE
The workqueue of service should be `service` other than `ingress`

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: yaozengzeng@zju.edu.cn

### CODE REVIEW

**Comment by brancz** [comment]
lgtm :+1: thanks!

**Comment by YaoZengzeng** [comment]
@brancz the `ci/circleci:build` is still pending, but it seems not related with my code change :)

**Comment by brancz** [comment]
will merge when it goes green :)

**Comment by brancz** [comment]
Did the build fail or why did you force push? (it does take a while as it builds prometheus for all architectures, it just needs time if you thought it was stuck)

**Comment by YaoZengzeng** [comment]
@brancz I thought it was stuck and force push to re-trigger it which I don't have the permission 😂

**Comment by brancz** [comment]
It does finish, just give it some time, if it truly takes too long then the timeout will kick in :)

**Comment by YaoZengzeng** [comment]
@brancz It actually passed, but took so long time 😂

**Comment by brancz** [comment]
Thanks for the patience :)

**Pull request merged**
