### PR TITLE
ui: heatmap visualization for histogram buckets

### PR DESCRIPTION
**Pull request by Loori-R**
#### Description:

This Pull Request implements a heatmap visualization feature for histogram buckets on the Prometheus `/graph` page. It utilizes a `flotjs` plugin for rendering, aligning its functionality with that observed in the VictoriaMetrics UI (vmui), as discussed in issue: [VictoriaMetrics#3384](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3384).

#### Key Changes:

- **`flotjs` Plugin Integration**: Facilitates the rendering of heatmaps.
- **"Show Histogram Graph" Button Added**: A new button placed adjacent to the "Show Stacked Graph" button.
- **Histogram Rendering**: Clicking the "Show Histogram Graph" button renders the graph as a histogram.
- **Auto-switch to Line Graph**: The graph automatically transitions to a linear representation if the query data lacks bucket data.
- **Button Activation Logic**: The "Show Histogram Graph" button is enabled only when the data comprises a single histogram series.
- **Deactivation Logic**: The button is disabled if the data includes more or fewer than one histogram series.

#### Future Enhancements:

- **Renderer Selection Option**: Consider substituting the button with a selector to choose the histogram rendering type when multiple series are available.

Screenshot 2023-10-30 at 11 36 22

### CODE REVIEW

**Comment by Loori-R** [comment]
@beorn7, Thank you for your insights and suggestions.

- At present, the histogram displays only for one series. If there are multiple series, a line graph will be shown.
- Regarding the issues with sorting and "de-cumulating": I will investigate this and make the necessary corrections.

**Comment by beorn7** [comment]
> At present, the histogram displays only for one series. If there are multiple series, a line graph will be shown.

OK, that's certainly good enough for a first iteration. Maybe, to avoid confusions, you could show the line graph by default in any case, and then offer a button "render as heatmap" in case there is only one histogram (or, to get one step closer to treating multiple histograms properly, offer a button for each histogram shown).

**Comment by Loori-R** [comment]
@beorn7, I've updated the PR to address your comments, making the following changes:

- **Bucket Sorting**: Now correctly numerical, including proper placement of the `+Inf` bucket.
- **Histogram De-cumulation**: Ensured accurate rendering of the histogram's distribution of values.
- **Rendering Options**: Line graph is set as default, with a "Show histogram graph" button for single histograms.

The PR description and screenshots have also been updated to reflect these changes.

**Comment by beorn7** [comment]
Thank you very much. I'll have a detailed look ASAP (and I'll need @juliusv anyway for the React parts). In the meantime, could you do the DCO signing to make the CI pass?

**Comment by juliusv** [comment]
The UI part is not supposed to work yet, right? Since the histogram button doesn't do anything (`// Do nothing`). Let me know when that part is ready for review!

**Comment by Loori-R** [comment]
@beorn7, sorry, when I tried to do the DCO signing, I got a bit confused and something went wrong) I created a pull request #13096, there is a DCO signature there.

@juliusv, the entire UI should work, when you press the button, the graph is drawn as a histogram. You probably saw the function in the tests (other old functions were done similarly there).

**Comment by Loori-R** [comment]
This pull request has been closed as a new pull request #13096 has been created.

**Comment by juliusv** [comment]
@Loori-R Oh yeah, I misread that from the test file, but I also tried out the PR locally first and the button didn't do anything. It shows up, but it's disabled and not clickable.

**Comment by Loori-R** [comment]
@juliusv, The button is active when the results have bucket data for a single series, example query:
`sum(increase(go_gc_pauses_seconds_total_bucket[30m])) by (le)`

For testing, I used the playground: https://prometheus.demo.do.prometheus.io
It's possible that you're not receiving the data that isn't intended for the histogram. 
Can you show the query or its result?

**Pull request closed without merging**
