### PR TITLE
consul: Initial implemenation of catalog filter support

### PR DESCRIPTION
**Pull request by dekimsey**
This adds support for Consul's Catalog [List Services][^1] API's `filter`
parameter added in 1.14.x. This parameter grants the operator more
flexibility to do server-side filtering of the Catalog, before
Prometheus subscribes for updates. Operators can use this to improve
both the performance of Prometheus's Consul SD and reduce the impact of
enumerating large catalogs.

[^1]: https://developer.hashicorp.com/consul/api-docs/v1.14.x/catalog

### Background

In Consul 1.14, the List Catalog API gained support for the powerful `filter` parameter. This grants operators new flexibility in tuning their catalog queries. The change is backwards compatible with existing Consul versions as they will ignore the new field.

An operator might be interested in this feature as it address a gap in Prometheus when handling large catalogs. Where Prometheus must query and then set Consul watches for large swaths of catalog services just to later make drop decisions during the relabel phase based on metadata/tag/node information. By allowing the operator to select services of interest during the ListCatalog step, we can reduce the number of RPC calls being made to Consul. This also helps mitigate Consul load for large catalogs for tracking the watches.

### TODO

  - [x] Update test to include new filter argument
  - [x] Perform integration tests with `consul -dev`

<details>
<summary>Integration Tests with Consul 1.18</summary>

To perform the integration tests I performed the following steps:

1. In a separate terminal I launched a consul agent (obtained from [releases.hashicorp.com](https://releases.hashicorp.com/consul/1.18.0/)):
```
consul agent -dev
```
2. Then I register a couple of test services like such:
```
consul services register -id app1 -name app -tag foo -tag bar
consul services register -id app2 -name app -tag bar -tag baz
consul catalog services -tags
```
3. I defined a simple set of prometheus scrape jobs to exercise the new code.
```
cat <<EOF >integration.yml
global:
  scrape_interval:     1s
scrape_configs:
  - job_name: foo
    consul_sd_configs:
      - tags: [foo]
  - job_name: baz
    consul_sd_configs:
      - filter: '"baz" in ServiceTags'
  - job_name: foobar
    consul_sd_configs:
      - tags: [foo]
        filter: '"bar" in ServiceTags'
EOF
```
4. Test `foo`, the original implementation still works:
```
go run ./cmd/promtool check service-discovery --timeout=2s prometheus.yml foo
level=debug datacenter=dc1 msg="Watching services" tags=foo
level=debug datacenter=dc1 msg="Watching service" service=app tags=foo
[
  {
    "discoveredLabels": {
      "__meta_consul_service": "app",
      "__meta_consul_service_id": "app1",
      "__meta_consul_tags": ",foo,bar,"
  }
]
...
```
5. Test `baz`, the new `filter` query works:
```
go run ./cmd/promtool check service-discovery --timeout=5s prometheus.yml baz
level=debug datacenter=dc1 msg="Watching services" tags=
level=debug datacenter=dc1 msg="Watching service" service=app tags=
[
  {
    "discoveredLabels": {
      "__meta_consul_service": "app",
      "__meta_consul_service_id": "app1",
      "__meta_consul_tags": ",foo,bar,"
  },
    "discoveredLabels": {
      "__meta_consul_service": "app",
      "__meta_consul_service_id": "app2",
      "__meta_consul_tags": ",bar,baz,"
    }
  },
]
...
```
6. Test `foobar` using both an old tag and new filter works:
```
go run ./cmd/promtool check service-discovery --timeout=5s prometheus.yml foobar
level=debug datacenter=dc1 msg="Watching services" tags=foo
level=debug datacenter=dc1 msg="Watching service" service=app tags=foo
[
  {
    "discoveredLabels": {
      "__meta_consul_service": "app",
      "__meta_consul_service_id": "app1",
      "__meta_consul_tags": ",foo,bar,"
  },
]
```

Expected services are returned successfully. 🎉 

</details>

Related: https://github.com/hashicorp/consul/issues/9422

### CODE REVIEW

**Comment by beorn7** [comment]
Looking at this during the bug scrub again.

Since there was no follow-up, we'll close this now, but we would love further work on this, may it be by @dekimsey or anyone else.

**Comment by dekimsey** [comment]
My apologies, I missed the initial reminder ping a few months ago after a recent job switch. IIRC the only blocker was to add testing. I'll set aside some time to work on this. I would like to see it get merged.

@roidelapluie I marked it as deprecated because the upstream Consul project indicated that field as deprecated. I'll simply comment the field is deprecated by the upstream instead as recommended.

@beorn7 Sorry for dropping the ball on this. It was important to me at $lastjob because we couldn't scan our large consul catalog. But I was able to work around it with some very kludgy terraform generating Prometheus config which reduced the immediate pressure.

Thank you for the reminders!

**Review by bboreham — APPROVED** [review]
Reviewed at the bug-scrub - LGTM.

I had to resolve one merge conflict.

**Comment by dekimsey** [comment]
Thank you for doing that!

**Pull request merged**
