### PR TITLE
Removed extra tsdb/testutil after merge.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by codesome** [comment]
While this does remove some duplicate code, it also makes tsdb depend on prometheus now and is no longer independent. I guess that was going to happen after the merger anyway.

**Comment by bwplotka** [comment]
Mhm only on testing helpers, so it is ok I think.

**Comment by brancz** [comment]
Package encapsulation still holds. I would deem this ok.

**Comment by krasi-georgiev** [comment]
LGTM

**Pull request merged**
