### PR TITLE
Added OpenAPI Specification file for v2 API

### PR DESCRIPTION
**Pull request by HelloKunal**
Signed-Off-By: Kunal <hellokunalpawar@gmail.com>

Related to #2392.
This PR is used to review and eventually add the Open API specification file. Which can later be used to generate client and server code for the v2 API by Swagger Codegen.

This is the generated client and server code from OpenAPI3 specification for preview and further test: 
- [Github](https://github.com/HelloKunal/OpenAPI-Specification-of-Go-API)

Here is the live UI of the RESTful API to preview: 
- [Swagger](https://stoic-kare-8f0c7d.netlify.app/)
- [Redoc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HelloKunal/OpenAPI-Specification-of-Go-API/main/swagger.yaml?token=AMOBCW7RTV66T62OMRGAFRTBDX434#section/Format-overview)

### CODE REVIEW

**Comment by bwplotka** [comment]
I think we are mostly using v1, so would be nice to have those under OpenAPI. cc @Hangzhi - she is adding those to Thanos code too and she has some tooling figured out already. 

Does this looks side from your side @Hangzhi?

**Comment by Hangzhi** [comment]
@HelloKunal Thanks for your work! The documentation looks good to me. We want the definition to be applied more than just documentation and generate client and server code from it. Looking forward to working on this together.

**Comment by subzero112233** [comment]
Hello,
Is there any plan for adding OpenAPI specification for API v1?

**Comment by roidelapluie** [comment]
There is no v2 yet in Prometheus. The goal would be to implement a v2 based on the OpenAPI spec, and in the far future to remove the v1.

I would not want an open api spec for v1 that is not backed by code generated from openapi spec.

**Comment by tejaswiniVadlamudi** [comment]
@roidelapluie : Generating code from OpenAPI spec in the coming releases is a good idea. Is there any proposal or a commit available to understand various reasons for version updates and ideologies behind v2?

**Comment by beorn7** [comment]
Digging this up during our bug scrub.

Currently, there are (still) no plans to add a v2 of the API. Should we ever add a v2, OpenAPI spec will be on the table definitely. But for the reasons stated here, we won't add one to v1.

**Comment by bwplotka** [comment]
> There is no v2 yet in Prometheus. The goal would be to implement a v2 based on the OpenAPI spec, and in the far future to remove the v1.

BTW: I think there might have been some misunderstanding, this does not introduce another version of an API, but rather retro-fitted OpenAPI spec? Anyhow, I wonder if it's possible to retro-fit: Create a OpenAPI spec and use client/server for exisiting v1 Prometheus APIs, without any modification (:

**Pull request closed without merging**
