### PR TITLE
add new functions 'consecutive_gt' and 'consecutive_lt'

### PR DESCRIPTION
**Pull request by uglycow**
PR for https://github.com/prometheus/prometheus/issues/12062
@roidelapluie plz help me on this.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Hey @uglycow, thanks for submitting the pull request.

It would be great to have some documentation on how to use this functionality.

Additionally, we can consider adding support for comparisons other than greater than and less than that can be specified using string parameters. For example, if we have a time series `some_metric{label="value"}` and we want to check if it is not equal to 10, we can write a query like this: `consecutive(some_metric{label="value"}[1m], "ne", 10, 2)`. Similarly, if we want to check if it is equal to 10 or more, we can use `ge` as the second parameter like so: `consecutive(some_metric{label="value"}[1m], "ge", 10, 2)`.

It would also be good to have some test cases with NaN values.

We could also think about other names.

streak?
sequence?

Ping @juliusv what is pinion on this pull request / issue?

**Comment by uglycow** [comment]
Hi man, @roidelapluie.
I have committed the code related to 
- change the func name to streak
- multiplex the func by using the comparison operator param

document for streak: `streak(v range-vector, operator string, targetValue scalar, countThreshold scalar)` check whether the series has no less than countThreshold consecutive points whose value satisfies the condition indicated by the operator when compared to targetValue. The operator could be "gt", "ge", "lt", "le", "eq", "ne". return an instant vector whose value would be 1 or 0, value 1 means the series satisfies the condition, and value 0 means not.


when I test the code, I found that the current func call code in `engine.go` can't work if we got matrix param and string param at the same time. we would get a type assertion error.
```shell
    promql_test.go:37: 
        	Error Trace:	/Users/yuneng.xie/github/uglycow/prometheus/promql/promql_test.go:37
        	Error:      	Received unexpected error:
        	            	error evaluating query "streak(metric_gt_1[1m],\"gt\",0,2)" (line 1051): unexpected error: interface conversion: parser.Value is promql.String, not promql.Matrix
        	Test:       	TestEvaluations/testdata/functions.test
```
related code: https://github.com/prometheus/prometheus/blob/24a9678dcc68057c64106ae1125fdb43413279f4/promql/engine.go#L1372

It seems like we are assuming that, if a matrix param is present, all other params should be Scalar.
I fixed it in this pr. not sure if it's the best solution. plz, help to review.

**Comment by beorn7** [comment]
Very generally, I'm deeply concerned about implementing (the beginnings of) another expression language inside of PromQL. Can't we do better and utilize existing PromQL syntax for it?

Brainstorming:

Maybe `streak` could simply return the longest streak of samples that are not zero (and maybe not `NaN` and `±Inf`)? Then `streak(some_metric{label="value"}[5m], "gt", 10, 3)` could be written as
```PromQL
streak(
  (some_metric{label="value"} > bool 10)[5m:15s]
) > 2
```

In the future, we might allow certain operators to act on range vectors (discussed elsewhere already, IIRC), allowing something like `streak(some_metric{label="value"}[5m] > bool 10)) > 2`

**Comment by uglycow** [comment]
Hi, @beorn7 sorry that I didn't explain the background clearly. For the alert of each occurrence, yes, I think we can use the `for` clause. I encountered the issue when I tried to set up a panel to show the total time that we are in a high-latency state for the last week as a service quality indicator which means our service is bad if the value is too high, and maybe need to notify the pm. So I need to count the high-latency time. As explained in #12062,  we care only when the high-latency issue persists for 5min. I did it with something like: `(sum_over_time(((sum_over_time(((job:latency_quantile95) > bool 100 ) [3m:1m])) >= bool 5)[7d:5m])`.
With this fixed time-window solution, we can`t capture the issue if it persists for 5min but spans across two time-window.

Sorry that I can't recall all the details cause it was quite a while ago and I just made a brief note about my idea that we should be able to do this more efficiently. You kind of remind me that `streak` might output the number of points that satisfy the condition, not just 1 to indicate existence. 

I agree with you that it's good to keep each operator and function simple and general and achieve our goal by combining them. What comes into my mind first, before I checked the code, is a function, we say streak, to zeroize those points which do not satisfy the 'consecutive condition' and output a range vector.
Then we can do it like: sum_over_time(streak(some_metric{label="value"}[7d] > bool 100)).

But after I checked the code, I found almost all functions return vector, no one is returning range vector, I didn't figure out a way to support it with a minor code change (CMIIW, I'm new to Prometheus code). On the other side, if we follow the routine to return just a vector, the code would be very simple.  

@beorn7  hope this would help you to understand my idea.

**Comment by uglycow** [comment]
changed the mean of the return value to the total count of all points that satisfy the condition. 
if the user wanna 0 or 1 to indicate the existence, can `streak(some_metric{label="value"}[7d], 9, 5) > bool 0`

**Comment by beorn7** [comment]
Thanks for the explanation.

I still think implementing "yet another expression language" (YAEL) should be avoided if at all possible.

What do you think about my suggestion [above](https://github.com/prometheus/prometheus/pull/12063#issuecomment-1462037343)? Doesn't that satisfy your use case?

**Comment by uglycow** [comment]
@beorn7  For now,  the signature of streak is 
`streak(matrix parser.ValueTypeMatrix, comparisonOperator parser.ValueTypeString, targetValue, countThreshold parser.ValueTypeScalar) Vector`
If we can apply operators on range vector, we can save the `comparisonOperator` and `targetValue` param, but we still need the `countThreshold` param. I can achieve my goal with `streak(some_metric{label="value"}[7d] > bool 100, 5)`.

Your suggestion does make the `streak` more simple cause we move the compare logic out. 
If you guys already make the decision to support operators on range vector, I can change the streak code accordingly ; )

**Comment by beorn7** [comment]
Allowing comparison operators on range vectors will be a fairly invasive change of PromQL. Unfortunately, even if we decided now to do it, it will take some time to make it work.

In the meantime, you could use subqueries for a similar result. See the example above:

```PromQL
streak(
  (some_metric{label="value"} > bool 10)[5m:15s]
) > 2
```

That's a tiny derivation, and a bit more effort to write, but it should in practical terms still do the trick (as long as the sample interval of the subquery is the same as the scrape interval).

About the count threshold: If `streak` returns the longest streak found, wouldn't we avoid the need for the count threshold? The example above returns any metric that had 3 or more consecutive data points above 10.

**Comment by uglycow** [comment]
image
I need to know the total count of points that satisfy the condition so I know how long we are in the error state.
`streak((some_metric{label="value"} > bool 10)[5m:15s], 2)` should produce 7 as the result, not just 1 indicating that we once were in the error state.

"Allowing comparison operators on range vectors will be a fairly invasive change of PromQL. It will take some time to make it work", understand, that's why I choose to implement the logic in the function, way simple...

**Comment by beorn7** [comment]
Thanks for the illustrated example. That helps a lot.

From the discussion above, I assumed you would like `streak((some_metric{label="value"} > bool 10)[5m:15s])` to return 4 (for the length of the longest streak.

Now I understand that you want the total length of all streaks longer than 2.

> "Allowing comparison operators on range vectors will be a fairly invasive change of PromQL. It will take some time to make it work", understand, that's why I choose to implement the logic in the function, way simple...

The problem is that implementing a new expression language within PromQL is even worse. It might appear simple to implement in an ad hoc fashion, but it's not simple conceptually and WRT the long-term impact. PromQL would be a huge mess if we added bespoke functions for every specific use case that somebody comes up with.

Allowing comparison operators on range vectors appears generally useful (we had a number of cases already where it would have come in handy), and I believe it plays well with the language concepts. It's still requiring some thought and care, but we should give it a try IMHO.

My gut feeling is that there should be a work around for your problem (which I have understood only now) using the existing language features. Let me think about it…

**Comment by beorn7** [comment]
Maybe I'm still misunderstanding your use case, but here is my train of thought:

Let's come back to your original alerting condition from #12062, namely "to alert if the spike persists for a period of time, say 5 min". Or for the sake of this example: `some_metric{label="value"}` is above 10 for 5m straight. The following expression yields 1 if you are in the alerting condition at the time of the evaluation:

```PromQL
min_over_time(some_metric{label="value"}[5m]) > bool 10
```

The following expression (with a subquery) should than give you the percentage of time during the last day that the alerting condition has been true:

```PromQL
avg_over_time((min_over_time(some_metric{label="value"}[5m]) > bool 10)[1d:15s]) * 100
```

Would that work?

**Comment by uglycow** [comment]
@beorn7 `avg_over_time((min_over_time(some_metric{label="value"}[5m]) > bool 10)[1d:15s]) * 100` I didn't fully understand this expression, especially for the `avg_over_time` and `*100`. 
As far as I understand it, yes, it works to a certain extent and it suffers from accuracy and efficiency issues, just as our running workaround.

the accuracy issue:
image
point a and b won't be counted.

the subquery would evaluate to false or 0, for the leading points of the streak, which should be taken into account, cause the subquery time window would include points that don't satisfy the condition.

> Allowing comparison operators on range vectors appears generally useful (we had a number of cases already where it would have come in handy), and I believe it plays well with the language concepts. 

I agreed with you on this. Just let me know when it's finished so I can change the streak code accordingly.

**Comment by beorn7** [comment]
I think you can increase the accuracy by reducing the sampling interval of the subquery.

I'm very reluctant to add a dedicated function for a fairly specific use case if subqueries give you a work around with the only cost of minor accuracy problems and a somewhat reduced performance.

I am very confident that we should not introduce an embedded expression language into PromQL if we can avoid it.

I would be very happy to hear other opinions (@roidelapluie, @juliusv maybe?).

**Comment by juliusv** [comment]
> I am very confident that we should not introduce an embedded expression language into PromQL if we can avoid it.
>
> I would be very happy to hear other opinions (@roidelapluie, @juliusv maybe?).

Agreed, unless absolutely necessary and well thought out, it would be much better to find a solution that fits more natively into the existing language and solves more use cases.

**Comment by uglycow** [comment]
Our running workaround is based on sub-query, I remember it takes too long for the query (our running workaround) to return.

**Comment by beorn7** [comment]
The work-around query you described in #12062 contained a subquery within a subquery. Plus it didn't catch certain conditions, as you described. The work-around query I suggested above only contains one subquery. I can imagine it performs much better already. Plus, I believe it better models what you would like to alert on.

If there is still a performance problem, you could still use recording rules to avoid them.

**Comment by uglycow** [comment]
> The work-around query you described in https://github.com/prometheus/prometheus/issues/12062 contained a subquery within a subquery. Plus it didn't catch certain conditions, as you described. The work-around query I suggested above only contains one subquery. I can imagine it performs much better already. Plus, I believe it better models what you would like to alert on.
 
I'm confused here, cause these two expressions seem to have the same structure.
the first one has better accuracy, but their performance shouldn't differ too much, CMIIW.
`avg_over_time((min_over_time(some_metric{label="value"}[5m]) > bool 10)[1d:15s]) * 100`
`(sum_over_time(((sum_over_time(((job:latency_quantile95) > bool 100 ) [3m:1m])) >= bool 5)[1d:5m])`

> If there is still a performance problem, you could still use recording rules to avoid them.

Yes, recording rule should solve the performance issue.

Actually, our last resort would be “get all the raw data and calculate it in our app”, after all, we only need to present the data to pm once a week for now. Just share my thoughts so you guys can evaluate whether it's worth providing the streak function.

**Comment by beorn7** [comment]
> I'm confused here, cause these two expressions seem to have the same structure.
the first one has better accuracy, but their performance shouldn't differ too much, CMIIW.
`avg_over_time((min_over_time(some_metric{label="value"}[5m]) > bool 10)[1d:15s]) * 100`
`(sum_over_time(((sum_over_time(((job:latency_quantile95) > bool 100 ) [3m:1m])) >= bool 5)[1d:5m])`

Have you tried both queries next to each other? Reality is always right. :o)

You could also reduce the resolution of the sub-query in the first query to get better performance. To make them comparable, maybe `1m` or even `5m` would be more appropriate. It depends what accuracy you need.

What I see as a performance drain in the 2nd query is that is contains a sub-query of a sub-query. The outer subquery with `[1d:5m]` evaluates the inner query 289 times (12*24+1). The inner query contains a subquery again, evaluating its own inner query 4 times. The engine tries to be smart to not evaluate again points in time it has already evaluated (when the sub-queries overlap), but there is actually no overlap here.

**Comment by roidelapluie** [comment]
Thanks for your pull request. We have discussed this during our bug scrub and as per @juliusv and @beorn7 comments above, we have decided not to go further with it at the moment. If you want to discuss this further please submit a [topic for the Prometheus dev summit](https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE).

**Pull request closed without merging**
