### PR TITLE
PromTool: Support Scrape Interval Lint Checking

### LINKED ISSUE #10263: promtool to report at least warning when scrape interval is greater than 4 minutes
## Proposal
**Use case:** 
There are some product related metrics that are collected by running some scripts. As the scripts puts heavy load on system, they are run only once per day during night time. These metrics are exported via a custom exporter which is scrapped from Prometheus once in 23 hours.
**Issue:**
Because of 5minute staleness, any metric that is reported with more than 4 minute scrape interval will essentially be marked as stale. 
**Proposal:**
While there are other mechanisms like using push gateway or implementing our own metric cache and scrapping the cache for every say 4 minutes, it is good if promtool reports larger scrape intervals as warning so that new bees like us are made aware of things then and there. 
**References:**
https://stackoverflow.com/questions/57663315/how-to-correctly-scrape-and-query-metrics-in-prometheus-every-hour
https://github.com/prometheus/prometheus/issues/9250

### PR DESCRIPTION
**Pull request by wangzhao765**
Fixes #10263 

Support scrape interval lint checking in PromTool.
Now lookback delta is not a command line flag, so I set the 5 minutes as a const value.

### CODE REVIEW

**Comment by wangzhao765** [comment]
> Hello! I think we should add the flag.

Thank you for you reply!
I do agree with you that we should add the lookback flag.
However, it seems that the configurable lookback may affact almost all PromTool rule tests ( https://github.com/prometheus/prometheus/issues/10263#issuecomment-1055936627 ). So I think a separate PR to add the lookback flag may be a good idea.
I am also willing to try to do some work to add the lookback flag.

**Comment by bboreham** [comment]
You can have a flag to set the value used for this check, without having it affect other things.

**Comment by wangzhao765** [comment]
Hi~ @roidelapluie @bboreham 
I have added a flag to set the look back duration for linting check.

**Comment by wangzhao765** [comment]
I'm so sorry! It seems that I have made a mistake on rebase.
I create a new PR  https://github.com/prometheus/prometheus/pull/14979  instead. Sorry for the inconvenience.

**Pull request closed without merging**
