### PR TITLE
upgrade aws-sdk-go

### PR DESCRIPTION
**Pull request by mtanda**
Upgrade aws-sdk-go to use IMDSv2.
https://aws.amazon.com/jp/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

The Prometheus itself should be safe for SSRF, but could be blocker for migrating IMDSv2.
This change will help Prometheus user to migrate IMDSv2.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you add the DCO?

**Comment by mtanda** [comment]
I added the DCO.

**Comment by brian-brazil** [comment]
Thanks!

**Comment by mtanda** [comment]
Thanks lot for quick merge!

**Pull request merged**
