### PR TITLE
Embed MetadataStore in scrape context

### PR DESCRIPTION
**Pull request by gouthamve**
This will allow downstream users to easily access metadata required.

In OpenTelemetry, we need to lookup metadata to figure out the "type" for the metric. We use the upstream scrape manager but use a custom `Appender`. Inside each `Append(ref, lset, t, v)`, we do the following:

1. job, instance := getJobInstance(lset)
2. metadataStore := getMetadataStore(scrapeManager, job, instance)
3. metadata := metadataStore.Get(lset[`__name__`])

This works great is most instances but it fails miserably when the `job` and `instance` labels are not those defined in config / during scrape time. i.e, when the `job`, `instance` labels are relabelled or when using `honor_labels: true`.

There is already a codebase that uses a fork of Prometheus due to this issue, and I want to upstream that chage as suggested here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5757#issuecomment-1054643624

I honestly couldn't come up with a better approach and am looking for better ideas.

Relevant issues: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5757 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5663

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

### CODE REVIEW

**Comment by Aneurysm9** [comment]
This seems like the most likely solution that does not change the `Appendable` interface.  I think that it will work for the needs that OTel currently is aware of, but can't speak to the Prometheus use cases @brian-brazil had in mind.

**Comment by roidelapluie** [comment]
I think this approach is fine. Prometheus appends to TSDB from the ruler as well, which does not need to have a cache attached. I think this is a correct in-between steps until we have further needs and design docs for the TSDB to handle metadata differently.

**Review by roidelapluie — APPROVED** [review]

**Pull request merged**
