### PR TITLE
Parallelize series population

### PR DESCRIPTION
**Pull request by slrtbtfs**
Attempt at #6878

### CODE REVIEW

**Comment by slrtbtfs** [comment]
TODO: We probably want the concurrency limit global or per engine, not per query.

**Comment by slrtbtfs** [comment]
I've just run the engine benchmarks and it looks like this PR doesn't actually improve performance.

Rather, especially the queries that run in parallel seem to be much slower.

It might be that this is only the case with the teststorage used by the engine benchmark, though.

**Comment by krasi-georgiev** [comment]
maybe a trace would explain what is happening?

**Comment by brian-brazil** [comment]
It'll run slower against local storage, to do this efficiently you'd need to redesign the interface a bit.

**Comment by bwplotka** [comment]
Do we want to redesign?

**Comment by brancz** [comment]
Yeah it seems like this needs a little more thought.

**Comment by slrtbtfs** [comment]
If anyone wants to take over, feel free.

**Comment by roidelapluie** [comment]
Just to clarify: I would prefer if we defer this to next releases at this point. Let's keep that out of 2.17.0 scope.

**Comment by bwplotka** [comment]
Not one works on this actively, so closing to not confuse contributors. Still, it will be linked on the issue so someone can grab this as a start (: Thanks @slrtbtfs !

**Pull request closed without merging**
