### PR TITLE
promql: correctly handle unary negation of native histograms and add tests for multiplication and division of native histograms by negative scalars

### PR DESCRIPTION
**Pull request by charleskorn**
This PR fixes the behaviour of unary negation of native histograms in the PromQL engine.

Previously, unary negation of a native histogram did nothing, which was inconsistent with multiplying by -1.

This PR also adds test cases for multiplication and division of native histograms by negative scalars.

I've tried to build up the PR incrementally, I'd suggest reviewing each commit separately.

### CODE REVIEW

**Comment by beorn7** [comment]
Let's discuss the desired behavior on #13934 (and use the discussion here for implementation details).

**Comment by beorn7** [comment]
Broadly speaking, if my reasoning in #13934 is correct, you need to remove the 4th commit from this to bring it in line with my ideas.

**Comment by charleskorn** [comment]
> Broadly speaking, if my reasoning in #13934 is correct, you need to remove the 4th commit from this to bring it in line with my ideas.

Done.

**Review by beorn7 — APPROVED** [review]
Thank you very much.

**Pull request merged**
