### PR TITLE
relabel: add keepequal/dropequal relabel action

### LINKED ISSUE #11556: Relabeling: Using a labelname in a regex (to use the labelname's value)
### Proposal

In relabeling config, let's say I have saved a value in a label like `__tmp_port`. I then want to match some port in Kubernetes service discovery 

```yaml
  relabel_configs:
    - source_labels: [ __meta_kubernetes_pod_container_port_number ]
      action: keep
      regex: ${__tmp_port}
```

If the value of `__meta_kubernetes_pod_container_port_number` and `__tmp_port` are both `8080`, it will keep this target. It could possibly be used in `replacement` as well.

I would like to be able to use any existing `__` value in the regex, even the ones found from service discovery such as `__meta_kubernetes_pod_container_port_number`.

It solves e.g. https://github.com/prometheus/prometheus/issues/3756

### PR DESCRIPTION
**Pull request by roidelapluie**
Fix #11556 

Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>

### CODE REVIEW

**Comment by juliusv** [comment]
Looks good :+1: 

The only thing I'm unsure about is the name of the relabeling action. `keepequal` sounds like it could just be an equality-based (vs. regex-based) version of `keep`, but it works totally differently because it's comparing to a label value, not to a fixed string. But I don't know how to name it better. `keeplabel[s]equal` would also sound bad and wouldn't be fully clear. So maybe it's fine like this.

**Comment by roidelapluie** [comment]
Yeah that is why we reject if there is a regex.

**Comment by juliusv** [comment]
Hmhm ok ok... :)

:+1:

**Comment by thernstig** [comment]
Does this need a PR in https://github.com/prometheus/docs ?

**Comment by thernstig** [comment]
@roidelapluie @juliusv does this new feature also solve and close this long-standing issue with many upvotes?

https://github.com/prometheus/prometheus/issues/3756

**Comment by bboreham** [comment]
How do we get the docs page updated with the new options?
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

**Comment by roidelapluie** [comment]
It will be updated when this will be released, the docs are versionned

**Comment by valyala** [comment]
It is pity that it has been decided to add `keepequal` and `dropequal` relabeling actions into Prometheus instead of backporting `keep_if_equal` and `drop_if_equal` actions with almost identical functionality from VictoriaMetrics according to [these docs](https://docs.victoriametrics.com/vmagent.html#relabeling-enhancements) :(

Historical note: the `keep_if_equal` and `drop_if_equal` relabeling actions were supported by VictoriaMetrics [since June 2020](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/2a39ba639d4446359d1dd77de85eaf9c8dca6771).

**Comment by thernstig** [comment]
@roidelapluie @juliusv would it be possible to change to the names @valyala mentions?

**Comment by roidelapluie** [comment]
Hello, sorry, I was not aware that VM also diverges on relabeling.

I'd note that the functionalities are different. Prometheus keepequal/dropequal will compare the concatenation of inputs with the target. Indeed, in Prometheus relabeling, input labels are seen as a whole.

Additionally, the terminology for relabel action in prometheus is that we do not use underscores and instead just concatenate the nouns.

**Pull request merged**
