### PR TITLE
Fix embarrassing bug of not setting the shrink ratio

### PR DESCRIPTION
**Pull request by beorn7**
Found by @mtanda . Thanks a million!

@brian-brazil This should give benchmarks another bump.

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1: 

My tests didn't run that long, I didn't have enough disk space for that.

**Comment by beorn7** [comment]
For my ingestion speed test, hitting the retention period was the moment when the server fell over.

This is both a happy and a sad moment. :)

**Comment by sodabrew** [comment]
Was this a regression in 1.5, or was `minShrinkRatio` actually never working ever?

**Comment by beorn7** [comment]
It was only ever working in the unit test (that set the struct member directly ;-( ), never in practice.

**Comment by sodabrew** [comment]
Was fixed at 10% or doing rewrites for every ingestion once the retention period was reached?

**Comment by beorn7** [comment]
It was hardcoded at 0%, as far as I can tell.

**Pull request merged**
