### PR TITLE
WIP: opportunistically clean up stale series from remote writes label cache

### PR DESCRIPTION
**Pull request by cstyan**
This PR is a result of a conversation with @rfratto and some other ongoing work by the Grafana Agent team. 

Because staleness is represented by a special NaN value within Prometheus, we can clean up those stale series from remote writes label cache earlier than the 2h WAL truncation interval. We just need to ensure the labels are not removed until all enqueued samples are put into remote write batches.

While this isn't a comprehensive memory usage optimization, this should at least help with environments in which there is a large amount of series churn. It won't help for things like cAdvisor which export timestamps on their metrics. 

I ran a quick experiment with only about 1k active series, but avalanche was churning every 10s or so.

Heap bytes inuse
2023-08-29-204404_2469x985_scrot
Sorry the legend is missing here, the green line is the new version from this PR

And then CPU usage.
2023-08-29-205044_2492x1072_scrot

### CODE REVIEW

**Review by csmarchbanks — COMMENTED** [review]
What would happen if a series went away for a few minutes (and was marked stale) and then reappeared? I can imagine this happening in some exporter scenarios for sure, or on restart of a service that doesn't initialize all status codes for an http metric.

**Comment by cstyan** [comment]
@csmarchbanks I've tried to account for that situation somewhat with requiring that the timestamp seen for the StaleNaN, when we iterate through the cleanup map, is at least X minutes old. ATM that's set to 1m but likely should be more like 5 minutes. On top of that, if we have an entry in the cleanup map but then later receive a sample with a non-StaleNaN value for the same ref ID the entry is removed from the cleanup map. 

I need to track down the exact behaviour, but in Brian's old [blogpost](https://www.robustperception.io/staleness-and-promql/) about the staleness marker it states:
> Things are trickier when a target disappears from service discovery. It's possible that the target will reappear before the next scrape would have been scheduled, so we can't just write out stale markers for when the next scrape would have been when a target goes away. What we do instead is wait until after such a recreated target would have ingested data (which is about 2 scrape intervals), and then ingest those stale markers. If the target was recreated then these stale markers will be rejected as the TSDB only allows appending data - not replacing samples at the latest or previous timestamps.

I think this means there's logic to ingest the staleness markers and consider that series ref ID dead after 2 scrapes, meaning if the target goes away for some amount of time then we would create new series with new ref IDs for the metrics again.

**Comment by csmarchbanks** [comment]
Ahh great, if we can guarantee that a new series ref is created this seems like a great optimization. I do wonder if we could add a WAL message type saying "end of this ref" to be more reliable than a time though. Just in case someone is using a very large scrape interval or if receiving from remote write. I don't have a great idea of how complex that would be of the top of my head though.

**Comment by cstyan** [comment]
I was thinking the same, that would be nice to have. Unfortunately the detection of staleness is part of scrape code and I think the other bits of the same logic are in TSDB. We'd have to have TSDB write it's own new record type to the WAL "series ended" or something like that.

@roidelapluie any thoughts here? I know the agent team already tried something where they wanted to rely on stale markers but couldn't because of the "series exports timestamp" condition from cAdvisor.

**Comment by cstyan** [comment]
@csmarchbanks one thing we'd have to consider is during an extended downtime with a target that goes away and comes back, the new samples with real values could be in the queue or in the WAL segment currently blocked but will be read. I'm not sure it can be as simple as `lastSuccessfulSend not more than X minutes ago AND StaleNaN TS greater than X minutes ago` since then in theory as soon as we successfully start sending again we could drop the series labels from the cache.

**Comment by roidelapluie** [comment]
There is no 'end of this ref' as targets can always be added back by service discovery..

**Comment by rfratto** [comment]
In Prometheus Agent, in-memory series tracking is the biggest consumer of memory. I would love to see a way to eliminate the need for series tracking, or at the very least making the number of tracked series smaller. 

As Julien pointed out, if a target comes back, the appender will re-assign the same ref IDs to the series, at which point (in this PR), remote_write will have lost the entry in the lookup table and won't be able to send the sample. 

I do think reworking staleness markers to act as a garbage collection signal could be useful here, but it would need coordination from the thing writing to a WAL to behave properly. If the appender also acted on staleness markers, then a new ref ID would be created for a target which comes back.

**Comment by rfratto** [comment]
As an aside, staleness markers are never written for series with explicit timestamps. This is always the case for cadvisor, which can be a big source of series churn and memory consumption (as the in-memory series cache grows). 

I would really like to see a long-term solution for improving memory consumption that works with cadvisor.

**Comment by cstyan** [comment]
> Staleness is not only about scrapes. We can receive staleness markers from rules and remote write.
> 
> I also think we should avoid calling runtime.GC.
> 
> It seems that you are also confusing Staleness marker for when a target/rule disappears, which are then ingested later, and staleness markers when a target is down, which are ingested directly.


@roidelapluie 
Yes it sounds like this is behaviour I didn't and still don't understand fully. 

Failing to scrape causes a staleness marker to be ingested into the TSDB immediately, but there's a delay if the target or rule "disappears"? How is a target disappearing different from just being unscrapable due to network issues or something like that?

It sounds like the TL; DR is that currently, until a checkpoint happens and determines a series is no longer active, at any point the target or rule that exposed/generated that series can come back and the same series ID would still be used? In which case there's no safe way to do what I'm trying to achieve here.

**Comment by roidelapluie** [comment]
If a rule disappears, or a target disappears, it might just be because they are moved to a different job or a different file, or simply the config was reloaded and normal samples will be ingested by another scrape loop

**Comment by cstyan** [comment]
> If a rule disappears, or a target disappears, it might just be because they are moved to a different job or a different file, or simply the config was reloaded and normal samples will be ingested by another scrape loop

Wouldn't moving a target to a different scrape job changes the labelset, making it a new series?

I've already tried to account for the case of just "a few scrapes missed, but then we get samples for the series again" in this PR. When we see a Stale NaN for a series I write it to the new map with it's timestamp, and if we see another Stale NaN for the same series we would update the timestamp. If we later we a sample with a real value for the series I remove the entry from the map. Only if there's an entry in that map of Stale NaN tracked series with a timestamp > X minutes old (currently 1 minute) will we clear that series from the regular labels cache. 

My question is whether there's any time period in which this behaviour is safe? Or, for example, if we have a WAL that exists for T=0 to T=N (where N is the last possible timestamp before we truncate the WAL and write a checkpoint), and we have samples with a real value at T=0 and T=N but nothing in between (or only some samples with Stale NaN values) is that still considered valid and the same series for the ref ID?

**Comment by gouthamve** [comment]
@roidelapluie Does the most recent comment address your concerns? Could we move forward with the PR?

_We looked at this in our bug scrub._

**Comment by bboreham** [comment]
Hello from the bug-scrub!  No response in 10 months so closing.
Feel free to re-open if you want to ressurrect.

**Pull request closed without merging**
