### PR TITLE
Added an enabled monitor label to file_sd

### PR DESCRIPTION
**Pull request by chicknsoup**
Sometimes, we want to temporary disable the scrape on some specific targets. The idea is to add a label check to file_sd, whenever a label named enabled has the value "false", the targetGroup will be ignored.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. This is business logic, which doesn't belong in an SD implementation. You can do this with relabelling.

**Comment by chicknsoup** [comment]
But relabeling will not work. For example, in one file we have hundreds of targets with different sets of labels, how would you relabel to disable scraping some targets for some time (1hour, 1 day, etc.). Moreover, relabeling requires configuration reloading or prometheus restarting while changing properties of labels does not.

**Comment by chicknsoup** [comment]
> 
> 
> Thanks for your PR. This is business logic, which doesn't belong in an SD implementation. You can do this with relabelling.

But relabeling will not work. For example, in one file we have hundreds of targets with different sets of labels, how would you relabel to disable scraping some targets for some time (1hour, 1 day, etc.). Moreover, relabeling requires configuration reloading or prometheus restarting while changing properties of labels does not.

**Comment by brian-brazil** [comment]
This is all possible, but this isn't the best place to discuss it.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Pull request closed without merging**
