### PR TITLE
Promote Agent mode to it's own cmdline flag

### LINKED ISSUE #14744: Promote Agent mode as stable
### Proposal

I recently realized that to run Prometheus in agent mode we still need to toogle the feature-flag `agent`. The feature is out for a few years already and is widely adopted.

It might be too close to PromCon, and therefore to 3.0 release date, but should we discuss removing the feature flag and replacing it with other configuration options?

### PR DESCRIPTION
**Pull request by ArthurSens**
If accepted, fix #14744

This PR removes the feature-flag `mode`, while adding a new flag `runtime.mode` that defaults to Server.

### CODE REVIEW

**Comment by ArthurSens** [comment]
Another approach is adding a new field to the config file, but I don't think that would be a good approach.

Changing runtime modes during runtime will create all kinds of errors if the original config file is incompatible with the new mode

**Comment by beorn7** [comment]
Maybe this is worth a top-level flag like `--agent`? See also my ramblings in #14744 .

**Comment by ArthurSens** [comment]
PR updated to use `--agent` instead of `--runtime.mode=agent`

**Comment by beorn7** [comment]
This should go into the v3 release branch, shouldn't it?

**Review by beorn7 — APPROVED** [review]

**Pull request merged**
