### PR TITLE
Allow changing log level at runtime

### PR DESCRIPTION
**Pull request by roidelapluie**
Helps (but does not solve) #7384 

Needs:
- Validation of the approach
- Tests
- PR to commons

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @beorn7 @SuperQ @brian-brazil

**Comment by roidelapluie** [comment]
cc @rfratto to see if that would be helpful for his use case.

**Comment by brian-brazil** [comment]
I'm against anything that involves having a setting coming from more than one place, as that's liable to cause confusion. I'm also wary of ending up with 10s of global options that very few users are likely to care about, and particular if they have no semantic effect such as this one.

What was agreed in #7384 was a way to view the last scrape error in the UI, and this PR does not help with the original claimed problem of #7384 of a logging system that can't handle the load of debug logs. If the level of debug logs are somehow a problem, they're a problem no matter how they're enabled.

**Comment by roidelapluie** [comment]
On the other hand, @SuperQ mentionened in the community meeting that he'd like more settings to be tunable in the configuration. Additionally, this setting would be useful in other situation, like debugging recording rules.

**Comment by roidelapluie** [comment]
I also note that the original reporter said that UI-only options are not enough to help them: https://github.com/prometheus/prometheus/issues/7384#issuecomment-648364335

**Comment by brian-brazil** [comment]
> Additionally, this setting would be useful in other situation, like debugging recording rules.

How would that be relevant? There's only 3 debug logs in the recording rules, only 2 of those are at runtime and could be handled by a similar approach as for scrape failures.

**Comment by brian-brazil** [comment]
> I also note that the original reporter said that UI-only options are not enough to help them: #7384 (comment)

That's what they said, but their claim seems to be that all the debug logs are so voluminous that enabling debug logging isn't viable for their logging solution can't handle it. I'm dubious of this claim, but even if it's true changing how debug logs are enabled doesn't help them as they still can't enable debug logs.

This PR does not help with #7384 as stated.

**Comment by rfratto** [comment]
> That's what they said, but their claim seems to be that all the debug logs are so voluminous that enabling debug logging isn't viable for their logging solution can't handle it. I'm dubious of this claim, but even if it's true changing how debug logs are enabled doesn't help them as they still can't enable debug logs.
>
> This PR does not help with #7384 as stated.

To be fully transparent, the request is originating from a user whose logging system struggles to handle a high volume and they have a significant number of scrape targets. Debug level logging at their scrape load to the centralized logging system would cause a lot of issues for them. I didn't challenge the claim, but I find it to be reasonable (but this also isn't the forum to discuss that).

As Brian mentioned, while I think this is nice, this doesn't alleviate the problems from #7384; between dynamically changing log level and including the last received error in the UI, I think the latter is preferable.

**Comment by roidelapluie** [comment]
thanks!

**Comment by brian-brazil** [comment]
> I didn't challenge the claim, but I find it to be reasonable (but this also isn't the forum to discuss that).

Doing some quick estimation for a worst case, say 15K targets, 15s interval, 100B per log entry, and all scrapes are failing. That's 100kB/s, which is not a high volume. Even if that's off by an order of magnitude, that's still well within what a logging system should be able to handle - particularly as the number of Prometheus servers will tend to be only a small fraction of what is producing logs in such  system. I don't think we should be making design decisions based on the limits of suboptimally performing event-logging systems.

> including the last received error in the UI, I think the latter is preferable.

Indeed. That'd also presumably make it available via the HTTP APIs, and thus someone could build the centralised dashboard you had also mentioned on top of that.

**Pull request closed without merging**
