### PR TITLE
Expose GCE labels during service discovery

### PR DESCRIPTION
**Pull request by woolite64**
This addresses #4137, cc @brian-brazil 

Updated packages under google.golang.org/api/* to support Instance Labels.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you update the docs too?

**Comment by woolite64** [comment]
Updated the docs to include the label field under gce_sd_configs.

**Comment by woolite64** [comment]
@brian-brazil Thanks for your help in getting this added.

Do you have plans to release a new version soon? I may run a custom build with this feature in the meantime, but would like to get back on an official release when available.

**Comment by brian-brazil** [comment]
Thanks!

2.3.0 should be soon hopefully.

**Pull request merged**
