### PR TITLE
PromQL: Make counts over vector selectors lazy.

### PR DESCRIPTION
**Pull request by tomwilkie**
A bit of a special case, but this makes common queries that don't involve a metric name (such as `sort(count({__name__=~".+"}) by (__name__))`) much, much faster.

WDYT?

### CODE REVIEW

**Comment by tomwilkie** [comment]
For those interested in how I came about this; Cortex couldn't answer queries that didn't involve a metric selector until recently (Aaron added a new schema for this), but as we were reading all samples collected in the last 15mins (and therefor fetching a load of chunks) these queries were too slow to be practically useful.  This PR fixes that.

**Comment by fabxc** [comment]
Mh, isn't it possible that we retrieve a series from the index but it doesn't actually have a sample at the queried time? Not entirely sure if this change is aligned with the semantics `count` is supposed to have.

@brian-brazil

**Comment by brian-brazil** [comment]
That would also be my concern with this proposal. I don't know the internals enough to know if this is safe.

**Comment by fabxc** [comment]
In the v2 storage I think it is not. If we instantiate the querier on the range [now-lookbackDelta, now], we cut out series without chunks in this range. But we only know whether there are samples in the range if there's a chunk as we iterate over it.  
Even if we filtered those series out, this would mean we'd have decode the chunks in the background, which just moves the problem elsewhere.

FWIW, I think this would often do what we want, but if the sole purpose is to get an estimate of how many series there, I'm not sure this is best done through PromQL to begin with.

**Comment by brian-brazil** [comment]
> if the sole purpose is to get an estimate of how many series there, I'm not sure this is best done through PromQL to begin with.

Yeah, something that just talked to the indexes would be better there. I've been thinking a debug UI page which indicated which series had the highest cardinality etc. would be handy.

**Comment by tomwilkie** [comment]
> Mh, isn't it possible that we retrieve a series from the index but it doesn't actually have a sample at the queried time?

I guess it is possible, especially with the new staleness code.  Good catch.

@aaron7 I guess we'll have to try something else? 

>> if the sole purpose is to get an estimate of how many series there, I'm not sure this is best done through PromQL to begin with.
>
> Yeah, something that just talked to the indexes would be better there. I've been thinking a debug UI page which indicated which series had the highest cardinality etc. would be handy.

+1 I think this would be super useful; I'll follow up with the idea later.

**Pull request closed without merging**
