### PR TITLE
Improve compression selection in HTTP responses

### PR DESCRIPTION
**Pull request by colega**
Previously this handler only understood simple `Accept-Encoding` header values like `gzip`, it didn't even respond with compression to simple header values `Accept-Encoding: gzip;q=1` or `Accept-Encoding: *`.

This implements a better selection logic, trying to follow the rules described in https://datatracker.ietf.org/doc/html/rfc7231#section-5.3.4

One thing that is not implemented is rejecting the requests if none of available encodings is accepted but identity is explicitly rejected, like `Accept-Encoding: snappy;q=1, *;q=0`. In that case we could respond with `406 Not Acceptable` but I didn't want to take that responsibility since this handler could be wrapped in a different handler that is still able to properly encode the request.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can we use https://pkg.go.dev/github.com/golang/gddo/httputil#NegotiateContentEncoding ?

**Comment by colega** [comment]
I didn't know about that one :)

We can, ([I tried in `6f7752bdc`](https://github.com/prometheus/prometheus/commit/6f7752bdc6d866998b55c177624efd9014c8a04a)) and it definitely requires less code, but also an extra dependency and it's not (unless I misunderstood something) actually correct. It doesn't pass these two test cases:

```go
		{
			name:                  "identity is the best option",
			acceptEncodingHeader:  "gzip;q=0.5, deflate;q=0.5, identity;q=1",
			expectedContentCoding: plainContentEncoding,
		},
```

Returns `gzip`, however `identity` is explicitly the best option here.

```go
		{
			name:                  "wildcard is the best option",
			acceptEncodingHeader:  "gzip;q=0.5, identity;q=0.5, *;q=1",
			expectedContentCoding: "deflate",
		},
```

Returns `gzip`, however the RFC says that:

> _The asterisk "*" symbol in an Accept-Encoding field  matches any available content-coding not explicitly listed in the header field._

Since `gzip` is explicitly listed as 0.5, the weight `1` only applies to `deflate`.

As that project is archived, I can't contribute a fix anymore.

**Comment by dgl** [comment]
It looks like there's already http://github.com/munnerz/goautoneg in go.mod via an indirect dependency. Maybe could use that for the parsing part at least, probably reduces code somewhat.

**Comment by roidelapluie** [comment]
I do notice that browsers use gzip without preference, as well as Prometheus itself. I wonder if we should have that kind of loginc ourselves our just support the general case, which is browsers and prometheus.

**Comment by colega** [comment]
I don't have any strong feelings about this contribution and I can just close it if we're hestitant to merge it.

OTOH it's not so much code (neither too complicated) to oppose it.

I'll leave the decision in your hands, I won't be disappointed if this PR just get closed.

**Comment by roidelapluie** [comment]
Do you have a usecase of a client using this?

**Comment by dgl** [comment]
I haven't had the chance to look in detail, but #10782 is considering using https://github.com/klauspost/compress, which has a gzhttp package, maybe we should consider just using a package someone else maintains like that.

**Comment by colega** [comment]
Sure, I'll take a look next week.

**Pull request closed without merging**
