### PR TITLE
added name label to all discovery metrics

### LINKED ISSUE #4993: Break out all discovery metrics by name
It'd be useful if all the metrics in https://github.com/prometheus/prometheus/blob/master/discovery/manager.go were broken out by name, as that's help debug which discovery manager is having an issue.

### PR DESCRIPTION
**Pull request by qoops-1**
Closes #4993 

cc @brian-brazil 

Signed-off-by: Ilya Gladyshev <ilya.v.gladyshev@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Test failure is some gomod issue - @simonpasquier 

This looks fine, it can go in after 2.6.0 is out.

**Comment by codesome** [comment]
Facing the same gomod error in subquery: https://travis-ci.org/prometheus/prometheus/builds/468500381

**Comment by brian-brazil** [comment]
Can you update your branch, so we can confirm the tests are good?

**Comment by qoops-1** [comment]
is there a way to amend the DCO?

**Comment by brian-brazil** [comment]
That branch isn't right, try `git rebase master`

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
