### PR TITLE
Expand record labels templates

### PR DESCRIPTION
**Pull request by alexandreh2ag**
Add the ability to use template variables or function in recording labels.

### CODE REVIEW

**Comment by alexandreh2ag** [comment]
Hello @roidelapluie @LeviHarrison,

Can you please review that PR ? 

If something is wrong please let me know.

**Comment by roidelapluie** [comment]
Thank you. Unfortunately, this is a breaking change that we can't make in Prometheus 2.x. It is also plausible that some people are using this property to include `{{}}` in alerting rules to avoid escaping.

**Comment by alexandreh2ag** [comment]
Thanks for your respond @roidelapluie.

I thought about this issue. If i add a config variable to interprate or not the {{}} and set it by default to false when not explicitly set to true, could this PR be accepted ? We could set this variable globally or on each record rule. In this case, with the default value being false, it would not be a breaking change, because records with {{}} in it will not be affected by this PR.

Something like this:

```

groups:
  - name: example
    rules:
      - record: code:prometheus_http_requests_total:sum
        expr: sum by (code) (prometheus_http_requests_total)
        expand_label: true
        labels:
          custom: "{{ $labels.instance }}"

```

What do you think about this solution ?

Also, at first, was there a specific reason to not expand variables in record rule labels ? Since it is possible in alert rule.

**Comment by roidelapluie** [comment]
I don't have the full background but I would say we don't really need it as you can use label_replace:

```
sum without (instance) (
  label_replace(
    sum by (code, instance) (prometheus_http_requests_total),
    "custom",
    "$1",
    "instance",
    "(.*)"
  )
)
```

Considering this, the overhead of adding an extra configuration option and the fact I never had this request in the past, I think we should go for the workaround and not add complexity.

cc @juliusv for another opinion

**Comment by juliusv** [comment]
@alexandreh2ag Thanks for suggesting this! I do agree with @roidelapluie that it doesn't seem worth the extra introduced complexity yet, given that this is the first time a request for it has come up and it can be done using `label_replace()` in the expression for someone who really needs it.

> Also, at first, was there a specific reason to not expand variables in record rule labels ? Since it is possible in alert rule.

Honestly, this is the first time I've even thought about this 😅 Historically we started out with the clear need to template the `annotations` of an alert, and then at some point a rare use case for templating alert labels also came up, so we implemented it. I don't remember if there was any discussion at the time around having that for recording rules as well, good question.

**Comment by alexandreh2ag** [comment]
Thanks for yours answers.

The function label_replace will not exactly fit my use case but i will find another solution.

Sorry for wasting time, maybe my next PR will be good :smile:

I close this PR.

**Pull request closed without merging**
