### PR TITLE
Rules v1 API

### PR DESCRIPTION
**Pull request by midnightconman**
This is part of https://github.com/prometheus/prometheus/issues/2467

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you share example output?

**Comment by midnightconman** [comment]
Sure 😄

I added all strings, group name and file, and rules (yaml).
```
{
  "status": "success",
  "data": {
    "groups": [
      {
        "name": "general.rules",
        "file": "rules.yaml",
        "rules": [
          {
            "rule": "alert: DeadMansSwitch\nexpr: vector(1)\nlabels:\n  severity: none\nannotations:\n  description: This is a DeadMansSwitch meant to ensure that the entire Alerting pipeline
\n    is functional.\n  summary: Alerting DeadMansSwitch\n"
          }
        ]
      },
      {
        "name": "general2.rules",
        "file": "rules2.yaml",
        "rules": [
          {
            "rule": "alert: DeadMansSwitch2\nexpr: vector(1)\nlabels:\n  severity: none\nannotations:\n  description: This is a DeadMansSwitch meant to ensure that the entire Alerting pipelin
e\n    is functional.\n  summary: Alerting DeadMansSwitch\n"
          }
        ]
      }
    ]
  }
}
```

**Comment by moolitayer** [comment]
parsing the json and yaml mixture could be complex. 
Would it make sense to convert the rules to json?

**Comment by brian-brazil** [comment]
I think a structure more like #3391 would make more sense. Returning YAML should be for entire files (so someday we can include comments too for the main config), it isn't needed in more detailed views.

**Comment by midnightconman** [comment]
@brian-brazil can you be more specific on the format changes? I don't see a difference between #3391 rules api and this output.
```
{
  "status": "success",
  "data": {
    "groups": [
      {
        "name": "rule_grp2",
        "file": "/home/user/allrules/grp2_rules.yml",
        "rules": [
          {
            "rule": "alert: R1file2\nexpr: up != 2\nfor: 10s\nlabels:\n  env: test\n  severity: high\nannotations:\n  dashboard: http://grafana.com/somelink\n  description: rule1 in file 2\n  summary: rule1 in file 2\n"
          }
        ]
      },
      {
        "name": "grp3",
        "file": "/home/user/allrules/grp3_rules.yml",
        "rules": [
          {
            "rule": "record: instance:errors:rate5m\nexpr: rate(errors_total[5m])\n"
          },
          {
            "rule": "record: instance:requests:rate5m\nexpr: rate(requests_total[5m])\n"
          },
          {
            "rule": "alert: HighErrors\nexpr: (100 - (avg(irate(node_cpu{mode=\"idle\",name=\"node-exporter\"}[5m])) BY (instance)\n  * 100)) > 75\nfor: 5m\nlabels:\n  severity: critical\nannotations:\n  description: '{{$labels.instance}}:CPU usage is above 75% (current value is:{{ $value\n    }})'\n"
          }
        ]
      },
      {
        "name": "rule_grp1",
        "file": "/home/user/allrules/grp1_rules.yml",
        "rules": [
          {
            "rule": "alert: R1file1\nexpr: up{job=\"prometheus\"} == 1\nfor: 2m\nlabels:\n  env: prod\n  severity: high\nannotations:\n  dashboard: http://grafana.com/somelink\n  description: rule1 in file 1\n  summary: rule1 in file 1\n"
          },
          {
            "rule": "alert: R2file1\nexpr: up{job=\"prom\"} == 0\nfor: 2m\nlabels:\n  env: prod\n  severity: critical\nannotations:\n  dashboard: http://grafana.com/somelink\n  description: rule2 in file 1\n  summary: rule2 in file 1\n"
          }
        ]
      }
    ]
  }
}
```

**Comment by midnightconman** [comment]
@moolitayer there were concerns about format and field changes, so the original request was for a string return. We could convert this yaml to json, but it probably shouldn't be here. We could return json from rules.go as a new method?

**Comment by moolitayer** [comment]
@midnightconman I wasn't aware of any backward compatibility concerns, can you elaborate on that a little? It would be helpful to think of how in the future we could request a different output format from the API if we need to implement something different. 

BTW are there any plans for rule mutating API? (and how would that work with rule configuration files)

> We could return json from rules.go as a new method?

How would that be exposed?

**Comment by brian-brazil** [comment]
> I don't see a difference between #3391 rules api and this output.

#3391 breaks out the fields of the rule.

> BTW are there any plans for rule mutating API?

There aren't.

**Comment by midnightconman** [comment]
Do we wan't this to be schema-full or schema-less? Meaning, do we only want to provide the fields in the current struct and new fields would be dropped?

**Comment by brian-brazil** [comment]
If/when there's new fields the code can be changed.

**Comment by simonpasquier** [comment]
@midnightconman are you still working on this?

**Comment by ranjithkumar-s** [comment]
@midnightconman 
Hey I tried to get the list of rules in prometheus via API but i got only Method Not Allowed error
curl -X GET http://192.168.10.101:9090/api/v1/rules

And also i want to create a rule via API. Is that possible?

**Comment by mxinden** [comment]
With https://github.com/prometheus/prometheus/pull/4318 merged, I am closing here. Let me know if I am missing something.

**Pull request closed without merging**
