### PR TITLE
Changes to Marathon service discovery to consider all the ports of a task as targets

### PR DESCRIPTION
**Pull request by rohitChaware**
Please refer issue #2448 . 
ping @fabxc .

### CODE REVIEW

**Comment by fabxc** [comment]
👍 That generally seems in line with what we did for the Kubernetes SD.
A test going with this would be good.

**Comment by brian-brazil** [comment]
This is a breaking change, so we should be sure to flag it in the release notes.

**Comment by fabxc** [comment]
Thanks. Can you update the related configuration documentation in prometheus/docs (PR against next-release branch). Then we are good for merge.

**Comment by ShimiTaNaka** [comment]
Why was this issue closed?
we'd love to have this functionality, or better yet, instead of scraping all the ports, use the port label(?)

**Comment by fabxc** [comment]
Not quite sure either. I think he wanted to resubmit it via his employer? @rohitChaware?

**Comment by rohitChaware** [comment]
Yes, I will be resubmitting it soon on behalf of my employer.

**Comment by grobie** [comment]
@rohitChaware Any updates here? It seems more and more users are running into this problem.

**Comment by rohitChaware** [comment]
Sorry for the delay. I am waiting for some quick approvals from my employer. As soon as I get them, either I will reopen this or make a new PR.

**Comment by grobie** [comment]
@rohitChaware It seems others need this functionality quite urgently. Please have a look at #2506, your review would be very welcome.

**Pull request closed without merging**
