### PR TITLE
API: /delete endpoint

### PR DESCRIPTION
**Pull request by Gouthamve**
So I added a `/api/v2/admin/delete` endpoint and it works as per my manual testing. 

We can now delete in time-ranges. And the endpoint now has the compulsory parameters `match, start, end`.

Per the discussion in #2760 I am thinking of putting all admin endpoints under `/api/v2/admin` and protecting it with a toggle-flag.

This PR is just to get the discussion started (and mostly will be redone):
1. Is the path okay?
2. The new file `/v2/api.go` copies most of the functions and datastructures from `/v1/api.go`. Should I export them instead? Or broadly, how should the new API code be structured.
3. For deletes: what should be the response be? As we can delete time-ranges and would be updating tombstones, I am not able to see what useful info we can provide here. Would `200 OK` suffice with no body?

cc @fabxc @brian-brazil @grobie @juliusv @beorn7 @SuperQ

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/2777)

### CODE REVIEW

**Comment by brian-brazil** [comment]
If we're going to put admin stuff under this path, are we going to switch e.g. the alertmanager to also have a `/api/v2/admin/reload` ?

**Comment by fabxc** [comment]
Eventually yes. Time to start thinking about a properly consistent API
design again.

**Comment by brian-brazil** [comment]
So when we next have a new API, init scripts will break?

I'm not sure we want *all* the admin stuff under the same API as the end-user stuff from a manageability standpoint.

**Comment by fabxc** [comment]
Health and readiness endpoints should probably remain top-level concerns and never be more complex than returning 200 if things are okay. @beorn7 any further thoughts on standardizing that across our components yet?

@brian-brazil did you think about anything other than health and readiness? I think reload falls under the `/v2/admin` category though. APIs are versioned and generally not removed without a long enough overlap for migration.

**Comment by brian-brazil** [comment]
I was mainly thinking about the lifecycle stuff, as it'd be good to have that consistent across binaries.

**Comment by beorn7** [comment]
As discussed in https://github.com/prometheus/pushgateway/issues/105 , it would be great to have consistency for health and liveness checks across all our binaries. API versioning is for the opposite: Separate incompatible HTTP calls, and that even between different versions of the same binary.

I assume @brian-brazil is referring to reload and quit when talking about lifecycle stuff. Which gives us the following endpoints to be outside of API versioning but behind `/-/...` instead:
- `/-/healthy`
- `/-/ready`
- `/-/quit`
- `/-/reload`

Any additions or corrections?

**Comment by Gouthamve** [comment]
Closing in favour of #2821

**Pull request closed without merging**
