### PR TITLE
Pull targets and rules out of status into their own tab

### PR DESCRIPTION
**Pull request by beorn7**
I got feedback from different sources about rules and targets being
too heavy in the status tab if their are lots of them.

This is a pretty straight forward change to pull them into their own
tabs. To keep changes cleanly seperated, I deliberately did not change
anything else (although there is probably a lot that could be
improved).

This change also allows more fine-granular locking. (Currently, if
somebody is fetching a giant list of rules or targets, the status
paged is blocked for everybody else for quite some time.)

### CODE REVIEW

**Comment by beorn7** [comment]
screenshot_20160513_153104

**Comment by beorn7** [comment]
@fabxc @brian-brazil @juliusv Not sure who of you feels most strongly about this...
@mwitkow You'll certainly appreciate this.

**Comment by brian-brazil** [comment]
What I expect to happen long term is that we'd have links to each rule group and target group from the status page. Moving two potentially very large sections into tabs doesn't change the fact that they're still potentially too large to make sense on a single tab. The number of rule groups and target groups should be more tractable though.

Having a tab for everything that's currently on the status would also be very cluttered.

**Comment by grobie** [comment]
See https://github.com/prometheus/prometheus/pull/1366 for the previous discussion about that.

**Comment by beorn7** [comment]
Thanks, @grobie, for linking the discussion. I vaguely remembered it but couldn't find it.

I totally agree that there is a huge potential for long term improvements but given that the other PR has been sitting there for quite some time, my suggestion is to go with this one for now.

It's not a "tab for everything" but for the two heaviest items on the status tab. I think it's a good balance to live with until we revamp the web UI more fundamentally (ideally with a UI expert involved). The current state (or status ;) is just not bearable for too many users to wait for that.

**Comment by grobie** [comment]
I'm fine with that as a step for now. I do have some ideas for a revamped UI, but that won't happen soon.

**Comment by brian-brazil** [comment]
If we take this approach we'll end up with tabs for config and flags too, as they're also pretty heavy.

I'd prefer we do something that makes sense for the majority of users, rather than piecemeal minor improvements that work for few users as that way lies an incoherent UI.

**Comment by grobie** [comment]
Let's use a navbar dropdown: https://getbootstrap.com/components/#navbar

Then we keep the nav item number low while still easily accessible from every page.

**Comment by brian-brazil** [comment]
That seems like a reasonable approach for now.

**Comment by beorn7** [comment]
So, what you mean is to have a dropdown "Status" where all the current section of the status page are individual entries?

**Comment by brian-brazil** [comment]
I guess we'd leave the version and flags where they are for now, so that the main status page isn't completely empty.

**Comment by grobie** [comment]
Maybe "Status" as heading and "Information", "Rules", "Targets" as drop down items?

**Comment by beorn7** [comment]
If I understand the bootstrap dropdown correctly, you cannot just select the title of the dropdown but always need to click on one of the items in the dropdown.

If the dropdown is consensus, I'll craft something along those lines you sketched out.

**Comment by mwitkow** [comment]
Thanks @beorn7, yea we've been hit pretty badly by large /statusz pages.

The navbar organization is not a real concern to me in any way. However, can we have `/rules` and `/targets` and `/config`? We deep-link to Prometheus status pages from our debugging dashboards.

**Comment by beorn7** [comment]
Could stakeholders please comment if the partitioning below looks sane:

screenshot_20160518_162935

Each of the items links to an own endpoint, so deep-linking is still possible. Code snippet (not pushed to PR yet):

```html
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Status <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/status">Runtime &amp; Build Information</a></li>
                <li><a href="/flags">Command-Line Flags</a></li>
                <li><a href="/config">Configuration</a></li>
                <li><a href="/rules">Rules</a></li>
                <li><a href="/targets">Targets</a></li>
              </ul>
            </li>
```

If you all agree, I'll change the remaining code accordingly.

**Comment by brian-brazil** [comment]
:+1:

**Comment by fabxc** [comment]
👍 certainly an improvement.

**Comment by beorn7** [comment]
All done. Please have a look.
(Even less locking now.)

**Comment by beorn7** [comment]
And now with `make assets`...

**Comment by beorn7** [comment]
Weird that `make assets` creates `bindata.go`, but then it still needs to get formatted by other make commands...

**Comment by grobie** [comment]
:+1:

Not sure the build information are the best example to represent the "status" of a prometheus server, but it's probably good to not remove the `/status` path.

**Pull request merged**
