### PR TITLE
Update web UI package.json

### PR DESCRIPTION
**Pull request by SuperQ**
Update several NPM version pinnings.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
Hmm, error in the JS:

image

**Comment by roidelapluie** [comment]
That is expected from netlify since we defaulted to the new UI.

**Comment by roidelapluie** [comment]
I have fixed CI

@juliusv I have updated netlify config with

```
find src -type f -not -name '*.test.tsx' -exec sed -i -e 's@${this.props.pathPrefix}/${API_PATH}@https://prometheus.demo.do.prometheus.io/${API_PATH}@' -e 's@${pathPrefix}/${API_PATH}@https://prometheus.demo.do.prometheus.io/${API_PATH}@' '{}' \; && CI= yarn build && echo '/* /index.html 200' > build/_redirects
```

**Comment by roidelapluie** [comment]
Thanks!

**Comment by juliusv** [comment]
:+1:

**Pull request merged**
