### PR TITLE
discovery/marathon: pass context to the client

### PR DESCRIPTION
**Pull request by simonpasquier**
The change should be safe but it would be good if someone with a Marathon environment could give it a try. 
cc @tommarute @ti-mo  @rjanovski @adrien-f.

### CODE REVIEW

**Comment by ti-mo** [comment]
Sure, looks fine :+1:

**Comment by aixeshunter** [comment]
looks good  +1

**Comment by simonpasquier** [comment]
@brian-brazil PTAL

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
