### PR TITLE
fixes #3083 - api ignores prefix option - when binary started with custom web.external-url

### LINKED ISSUE #3083: Links to /route-prefix/api/ but only responds on /api/
**What did you do?**

Run prometheus with these flags:

~~~
--web.external-url=https://example.com/prometheus
--web.route-prefix=/prometheus
~~~

and behind an Apache reverse proxy

~~~
        ProxyPass /prometheus http://10.85.179.50:9090/prometheus
        ProxyPassReverse /prometheus http://10.85.179.50:9090/prometheus
~~~

Opened the page at https://example.com/prometheus/graph

**What did you expect to see?**

Usual prometheus front page

**What did you see instead? Under which circumstances?**

Usual prometheus front page but with red box: "Error loading available metrics!"

Opening the Javascript console showed that it got a 404 error trying to access
https://example.com/prometheus/api/v1/label/__name__/values?_=1502894473124

Testing this directly from the proxy:

~~~
root@wrn-mon2:~# curl -Lv 10.85.179.50:9090/prometheus/api/v1/label/__name__/values?_=1502894473124*   Trying 10.85.179.50...
* Connected to 10.85.179.50 (10.85.179.50) port 9090 (#0)
> GET /prometheus/api/v1/label/__name__/values?_=1502894473124 HTTP/1.1
> Host: 10.85.179.50:9090
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 16 Aug 2017 14:53:58 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host 10.85.179.50 left intact
~~~

BUT:

~~~
root@wrn-mon2:~# curl -Lv 10.85.179.50:9090/api/v1/label/__name__/values?_=1502894473124
*   Trying 10.85.179.50...
* Connected to 10.85.179.50 (10.85.179.50) port 9090 (#0)
> GET /api/v1/label/__name__/values?_=1502894473124 HTTP/1.1
> Host: 10.85.179.50:9090
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Date
< Content-Type: application/json
< Date: Wed, 16 Aug 2017 14:54:23 GMT
< Transfer-Encoding: chunked
<
{"status":"success","data":["go_gc_duration_seconds","go_gc_duration_seconds_count"
...
~~~

So it appears that the api endpoint doesn't honour the route-prefix.

**Environment**

* System information:

	Linux 4.4.0-87-generic x86_64

* Prometheus version: 

    ~~~
    prometheus, version 2.0.0-beta.1 (branch: HEAD, revision: 4dcb465029f39a2a3030333a81753f8a40ec90ce)
      build user:       root@d3f9974fac5a
      build date:       20170811-12:12:36
      go version:       go1.8.3
    ~~~

* Alertmanager version:

    n/a

* Prometheus configuration file:

    default

* Alertmanager configuration file:

    n/a

* Logs:

    n/a

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fix for #3083 
@fabxc

this pull request doesn't address https as I am not sure whether you want this implemented or return an error that https is not supported for the webHandle

Signed-off-by: Krasi Georgiev <krasi.root@gmail.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
I think this answers the question so maybe review the PR as it is or I can implement to error out when the web.external-url is trying to use https for the scheme

**Comment by krasi-georgiev** [comment]
cc @fabxc

**Comment by krasi-georgiev** [comment]
@grobie are you familiar with this part of the code to check this PR ?

**Comment by grobie** [comment]
Our router package in common/route already has support for prefixes, but I guess that doesn't apply here as we mount the API under its own prefix `/api/v1/`?

Why hasn't this been a problem before? @brancz @matthiasr does the magic Kubernetes proxy rewrite these URLs on-the-fly? Would this change break that?

**Comment by brancz** [comment]
IIRC the we intentionally did not prefix API endpoints, but I might be wrong.

The Kubernetes Proxy does indeed to url and http rewriting, but it doesn't touch the underlying applications paths (if it does, then that would be a bug).

**Comment by brian-brazil** [comment]
We should be treating all endpoints the same way.

**Comment by brancz** [comment]
Agreed.

**Comment by fabxc** [comment]
Either way, this looks good to me. Sorry about not getting to this earlier @krasi-georgiev. I'll rebase.

**Comment by krasi-georgiev** [comment]
@fabxc no problem , I had to squash the commits to keep the CI happy but all looks good now.

**Pull request merged**
