### PR TITLE
openstack_sd: Supporting application credential for authentication.

### PR DESCRIPTION
**Pull request by kmbulebu**
Adding support to authenticate with OpenStack using an application credential rather than a user and password. Introduced three new configuration entries for `openstack_sd_config`: `application_credential_id`, `application_credential_name`, `application_credential_secret`. 

> Users can create application credentials to allow their applications to authenticate to keystone. Users can delegate a subset of their role assignments on a project to an application credential, granting the application the same or restricted authorization to a project. With application credentials, applications authenticate with the application credential ID and a secret string which is not the user’s password. This way, the user’s password is not embedded in the application’s configuration, which is especially important for users whose identities are managed by an external system such as LDAP or a single-signon system.
https://docs.openstack.org/keystone/queens/user/application_credentials.html

Managing application credentials via the OpenStack client cli: https://docs.openstack.org/python-openstackclient/rocky/cli/command-objects/application-credentials.html

Sample configuration:

```
    openstack_sd_configs:
    - role: instance
      region: RegionOne
      identity_endpoint: http://controller:5000/v3/
      application_credential_id: 1524b255415e4dea9082f3464e717616
      application_credential_secret: R6Zpu6GTChO3Q63fDKBEj-BvRiqBjy2lbe77PoY_00iGlfqSoEjtD8Q9-QNm_u8hU2lzEFp0nMhfiUnNBQhLnQ
```
Tested with OpenStack Labs Rocky release. 

This change required vendoring the latest gophercloud module.

### CODE REVIEW

**Comment by simonpasquier** [comment]
You need to sign your latest commit though.

**Comment by kmbulebu** [comment]
Thanks for the review. Signed off.

**Comment by kmbulebu** [comment]
@brian-brazil Hi Brian, please review for merge. Thank you.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
