### PR TITLE
don't close a closed channel

### LINKED ISSUE #4133: Rules manager Panic caused by closing a channel more than once.
caused when sending a SIGHUP. and  SIGTERM right after that.
I looked briefly and seems like an easy one to solve.

```
panic: close of closed channel

goroutine 86182 [running]:
github.com/prometheus/prometheus/rules.(*Group).stop(...)
      ..../src/github.com/prometheus/prometheus/rules/manager.go:238
github.com/prometheus/prometheus/rules.(*Manager).Update.func1(0xc58eeacc01, 0xc42842c480, 0xc4200c5bc0, 0xc53ad459e0, 0xc44f874a20)
      ..../src/github.com/prometheus/prometheus/rules/manager.go:501 +0x80
created by github.com/prometheus/prometheus/rules.(*Manager).Update
      ..../src/github.com/prometheus/prometheus/rules/manager.go:499 +0x512
panic: close of closed channel

goroutine 86140 [running]:
github.com/prometheus/prometheus/rules.(*Group).stop(...)
      ..../src/github.com/prometheus/prometheus/rules/manager.go:238
github.com/prometheus/prometheus/rules.(*Manager).Update.func1(0xc4fab69b01, 0xc428228b40, 0xc4200c5bc0, 0xc53ad459e0, 0xc4e381def0)
      ..../src/github.com/prometheus/prometheus/rules/manager.go:501 +0x80
created by github.com/prometheus/prometheus/rules.(*Manager).Update
      ..../src/github.com/prometheus/prometheus/rules/manager.go:499 +0x512
```

### PR DESCRIPTION
**Pull request by krasi-georgiev**
fixes #4133 

cc @beorn7 

Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why would this already be closed?

**Comment by krasi-georgiev** [comment]
it looks like the mutex is released in some combaniation of calling Update more than once and stopping the manager.

**Comment by fabxc** [comment]
If our assumption is that this can never happen, we should not work around the consequences but fix the cause of it. We might be in for unpleasant surprises later on otherwise.

**Comment by krasi-georgiev** [comment]
reported by @beorn7 , but I couldn't replicate. Closing until we have a good way to replicate.
at first glance closing this channel shouldn't even happen there, but somewhere in the calling side.

**Comment by beorn7** [comment]
This happened during shutdown, IIRC.

**Pull request closed without merging**
