### PR TITLE
Improve config reload

### PR DESCRIPTION
**Pull request by roymiloh**
related to https://github.com/prometheus/prometheus/issues/1149

### CODE REVIEW

**Comment by juliusv** [comment]
Hey, thanks again! I haven't taken a closer look yet because of weekend and now travel to NYC (VelocityConf), but happy to do so later the upcoming week, when I get to PRs again. If others like @fabxc haven't gotten to it yet by then!

**Comment by roymiloh** [comment]
funny, I recall that I fixed it. anyway, something else? what about centralizing the whole thing (from the discussion in the relevant issue)?

**Comment by fabxc** [comment]
@juliusv brought up the valid point that one would have to attach the parsed rule files to the config as they could otherwise be changed after validation and before being loaded again in the rule manager.

So I hit a very similar situation in the Alertmanager and went for the central approach. In retrospect I'm not sure whether passing down a whole config for the sake of having a unified interface was a good idea to begin with as the number of components is reasonably low.

https://github.com/prometheus/alertmanager/blob/fabxc/clean/main.go#L96-L122

Here the validation happens before 113 and everything after that are operations that are guaranteed to succeed.
What do you think about a similar solution for Prometheus itself?

The error-free updating logic could still remain in the components itself. Just with more specialized methods that only receive the portion of config/data they need.

**Comment by roymiloh** [comment]
Well, any solution would have his trade-off, but I agree with your approach, it will be more readable and concise. As long as there are no *that* much components, we can relinquish the interfaces vision.

**Comment by brian-brazil** [comment]
Is this PR still relevant?

**Comment by brian-brazil** [comment]
I believe this has all been redone since.

**Pull request closed without merging**
