### PR TITLE
web/api: add targets endpoint

### PR DESCRIPTION
**Pull request by brancz**
To be able to implement automated tests to see whether a discovery mechanism is working and has been configured correctly, an API to retrieve targets is necessary. For example: it could be used for integration tests of existing service discovery mechanisms built into Prometheus as well as to test whether for example the [prometheus-operator](https://github.com/coreos/prometheus-operator) has setup the kubernetes sd configuration correctly.

Before I invest some time into tests I would like to have a discussion and a general consensus on the resulting representation.

Currently the data part of the object consists of an array of target pools, where a target pool is an array of targets of the same job. For example:

```json
{
   "status":"success",
   "data":[
      [
         {
            "metaLabels":{
               "__address__":"127.0.0.1:8081",
               "__metrics_path__":"/metrics",
               "__scheme__":"http",
               "job":"example-app"
            },
            "labels":{
               "instance":"127.0.0.1:8081",
               "job":"example-app"
            },
            "lastError":"Get http://127.0.0.1:8081/metrics: dial tcp 127.0.0.1:8081: getsockopt: connection refused",
            "lastScrape":"2016-11-29T17:34:53.904539388+01:00",
            "health":"down"
         }
      ]
   ]
}
```

This slightly differs from the internal representation, but as far as I can tell (from comments in code) the internal representation this representation is created from is only kept for backward compatibility at this point.

@fabxc @brian-brazil @juliusv

### CODE REVIEW

**Comment by fabxc** [comment]
That generally looks like what we want. The full URL used for scraping should be in there as well though as we can currently only infer it from the meta labels and other configurations specific to the scrape config will be missing entirely.

However, basic auth should probably be stripped or at least masked.

**Comment by brian-brazil** [comment]
Travelling right now so can't give in depth review, but we should include a
way to get all dropped targets too.

**Comment by fabxc** [comment]
I think we can add that later once there's demand. It would be off by default anyway and would require a bunch of nasty changes in the actual discovery code.

**Comment by brancz** [comment]
@fabxc added the full `scrapeUrl`. As far as I can tell from the code, basic auth is not included in the URL returned by the `Target`.

**Comment by brancz** [comment]
@fabxc @brian-brazil I added a simple test. As we are not testing the `Target` here I think this simple test should be enough. Let me know what you think.

**Comment by fabxc** [comment]
Looks good in general. Just wondering whether we should rename `metaLabels` to `discoveredLabels`. Seems more understandable.

**Comment by brancz** [comment]
Agreed, as meta labels are in the docs usually referred to as labels that start and end with 2x `_` and would seem inconsistent here.

**Comment by brancz** [comment]
@fabxc do you prefer `discoveredLabels` or `origLabels` as seen [here](https://github.com/brancz/prometheus/blob/211311d0f09fcd172e0cbcff1e0c686731f9c04a/retrieval/target.go#L375)?

**Comment by brian-brazil** [comment]
Discovered labels is more likely to be understood by the user I expect.

**Comment by brancz** [comment]
Sounds good to me. As I was already at it, I also changed the naming used internally there by the `Target` to make it consistent across the code base. Re-review @fabxc @brian-brazil ?

**Comment by fabxc** [comment]
Cool, LGTM 👍 
This needs to be added to our HTTP API docs then as well.

**Comment by brancz** [comment]
Alright will get started on that PR as wel then

**Pull request merged**
