### PR TITLE
Restructure helper packages

### PR DESCRIPTION
**Pull request by fabxc**
I'd like to propose to move helper packages to a `pkg/` folder. This blog post should be read in advance:
https://blog.golang.org/package-names

Of course we don't want to pollute our project root with small helper packages. The root should mostly contain Prometheus's core components. The blog post describes well why you might still want to create packages for certain helper functionality, no matter how trivial.
Helper packages should also never live in the directory of the core package that needed them first, unless they have a logical relation to that package.

I find `pkg` very clear: "We have a bunch of less important things, they are packages (short `pkg`), and here they are with their meaningful names."

It's a route many larger Go projects have taken with slightly different "importance thresholds".
It's a good one in my opinion.

In a previous discussion there was the concern that `pkg` conflicts with go's `pkg` directory in some way. 
Import paths are opaque in that regard - `a/pkg` != `b/pkg` just as much as `apple` != `house`.

### CODE REVIEW

**Comment by juliusv** [comment]
Couple of initial thoughts before bed (and want to hear other people's opinions as well):

- Uncluttering the project root a bit sounds good in general.
- Splitting up "generic" packages like `utility` sounds good in general.
- How about `util` instead of `pkg`? Notably, this is not a package name, but just the intermediate directory leading up to the various package dirs. For me as a code reader it would seem clearer that `util` just contains less important packages. `pkg` sounds so generic that it's not clear whether they are important or unimportant ones.
- Not sure about putting `templates` into the `pkg` / `util` directory. It has quite a lot of important Prometheus-specific functionality and might be considered an "important" package.

**Comment by fabxc** [comment]
Sounds good so far. Your last to points are probably what I descibred as "importance threshold" before. We certainly have to set ours in this case.

I think the lower end is fine, i.e. templates not being in this folder. Also not feeling to strong about the name. `util` is fine with me – `utility` is acid in my eyes though ;)

**Comment by juliusv** [comment]
Haha, yeah. `util` >> `utility`.

**Comment by brian-brazil** [comment]
`util` and everything bar `templates` (which has prometheus-specific features) sounds good to me.

**Comment by juliusv** [comment]
Yep :+1:. Make it so.

**Comment by fabxc** [comment]
Still convert `templates` to `template`? Plurals for package names are not generally a thing in Go and this just wraps `(text|html)/template` and not `(text|html)/templates`.

**Comment by brian-brazil** [comment]
We're using `(text|html)/template` directly in places, so probably best not to risk a collision.

**Comment by fabxc** [comment]
I think its better to have it clash then. If you import both you have to import rename properly and explicitly. It's way clearer than a distinction by a tiny trailing `s`.

**Comment by beorn7** [comment]
* I prefer `template` over `template`. Package name collisions in Go are embraced and worked around by local names. (Relying in pluralization to avoid name collisions is arguably more dangerous.) If we want to avoid the collision properly, we should use a more different name, like `consoletemplate` or `contemplate` :-> .
* I prefer `util` over `utility` over `pkg`.

**Comment by fabxc** [comment]
To be honest, in the `templates` package I see 300 lines of generic helper functions. Not entirely sure what's not `util`-y about it. There's no functionality implemented here that keeps Prometheus, just convenience.

The conversion logic in the `query()` function should be refactored to `promql` eventually.

**Comment by juliusv** [comment]
It deals with very Prometheus-specific types (samples, matrices, vectors, ...) and defines a lot of functions that are even visible to the Prometheus user/operator. So IMO it's definitely not just a utility package.

**Comment by fabxc** [comment]
I disagree (strongish and for several reasons) - but I slightly do with the template situation in general.
But the strongish part is more of a taste-thing so the majority wins here.

Should be fixed.

**Comment by juliusv** [comment]
It's always good to hear reasons if they matter enough - they could change majority opinion :)

But also fine with keeping things as they are now.

**Comment by fabxc** [comment]
As I said, the strongish part is a taste-thing, not worth too much discussion time.

Just want to point out that its fine for utility packages of a larger application to not be agnostic of specifics of this applications – that's why they live in a common namespace.

E.g. `stats/` implements generic timers but the timer types are certainly Prometheus-related. That's not a reason it has to be a top-level package.

**Comment by beorn7** [comment]
:+1:

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
:+1:

**Pull request merged**
