### PR TITLE
[WIP] Use standard net/http timeouts.

### PR DESCRIPTION
**Pull request by fabxc**
So for now just switch to what the standard lib has to offer.
Canceling requests is something we should look into some day - to save some time on shutdown.

### CODE REVIEW

**Comment by grobie** [comment]
:+1:

**Comment by juliusv** [comment]
Trying out this branch results in:

```
panic: non-positive interval for NewTicker

goroutine 48 [running]:
time.NewTicker(0x0, 0x1)
	/usr/local/go/src/time/tick.go:23 +0xfd
github.com/prometheus/prometheus/rules.(*Manager).Run(0xc20bd2d6c0)
	/home/julius/gosrc/src/github.com/prometheus/prometheus/.build/root/gopath/src/github.com/prometheus/prometheus/rules/manager.go:128 +0x15e
created by main.(*prometheus).Serve
	/home/julius/gosrc/src/github.com/prometheus/prometheus/main.go:243 +0xf5
```

**Comment by fabxc** [comment]
As turned out, unrelated to those changes.

**Comment by fabxc** [comment]
Blocked until after v0.14.

**Comment by fabxc** [comment]
Closing here. Immediate use questionable and requires lots of measuring.
Can be revisited some time in the future.

**Pull request closed without merging**
