### PR TITLE
cmd/promtool: add $externalLabels for alert unit tests

### PR DESCRIPTION
**Pull request by simonpasquier**
Reported [here](https://groups.google.com/d/msg/prometheus-users/HUpugdInqyo/4gzE851ECAAJ).

### CODE REVIEW

**Comment by brian-brazil** [comment]
This looks like the obvious way to do this to me.

**Comment by adamdougal** [comment]
Heya, I just wondered if this was okay to be merged now? Thanks

**Comment by beorn7** [comment]
Yup, sure. Somehow my wetware parser didn't register Brian's comment as an approval. But I guess it's exactly that.

**Comment by beorn7** [comment]
Or I subconsciously thought Simon would merge his own PR himself. Anyway. Merged now.

**Pull request merged**
