### PR TITLE
Kubernetes SD: Add endpoints role to API servers job to actually discover some API servers

### PR DESCRIPTION
**Pull request by jimmidyson**
Previous PR forgot to add endpoints role... Sorry about that!

Ref #2175 - ping @Priyanka098.

### CODE REVIEW

**Comment by brancz** [comment]
I'll give it a run in a bit, busy right now, but should get to it soon.

**Comment by jimmidyson** [comment]
@brancz Had a chance to try this out?

**Comment by brancz** [comment]
Completely forgot, thanks for reminding me. Trying now.

**Comment by brancz** [comment]
Config works. LGTM 👍 

One nitpick, but we can address this in another PR and/or discuss first. The node scrapes fail due to cert problems, we've seen this for a while, but I feel that ignoring invalid certs in a default config seems like we're not being a role model, plus there are two ways to solve it: ignore cert issues or relabel kubelet scrape targets to `10255` instead of the discovered `10250`. Which one is better?

Either way you have my 👍 so we at least have a working/starting config that we can improve along the way.

**Comment by fabxc** [comment]
Yea, having this fix in is better than not.
We really have to figure out what's the issue with cert validation against the API server. The read-only port is subject to removal and not really an option.

**Pull request merged**
