### PR TITLE
[ENHANCEMENT] remote storage:Add default api implementation of remote write

### PR DESCRIPTION
**Pull request by liguozhong**
[ENHANCEMENT] remote storage:Add default api implementation of remote write

image

### CODE REVIEW

**Comment by liguozhong** [comment]
@csmarchbanks @cstyan 
remote storage module pr

**Comment by liguozhong** [comment]
# prometheus.yaml 1 
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

**Comment by liguozhong** [comment]
# prometheus.yaml 2
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: 'kafka'
    static_configs:
    - targets: ['121.40.124.46:9997']
  - job_name: 'zookeeper'
    static_configs:
    - targets: ['121.40.124.46:8997']
remote_write:
  - url: http://localhost:9090/api/v1/write
    name: prometheus-hangzhou

**Comment by brian-brazil** [comment]
This PR appears to be adding push to Prometheus, which is an explicit non-goal of the project.

**Comment by roidelapluie** [comment]
Is that really something that can be solved in 126 lines of code? What is the catch?

**Comment by cstyan** [comment]
@liguozhong Yeah this isn't really something we plan to support. You might find Thanos appealing as it's deployment on top of Prometheus to add a global query layer is relatively minimal. Otherwise remote write systems such as those suggest by Brian or others listed [here](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage) are your best options.

**Comment by liguozhong** [comment]
> This PR appears to be adding push to Prometheus, which is an explicit non-goal of the project.
> 
> I'd suggest looking at options like Cortex or M3.

thanks.
We use it in an IOT project. We write it to a remote storage of influxdb through remote write. Because the memory and CPU disk configuration of edge host are relatively low, and the network is unidirectional, but in the case of regular condition label filtering such as metrics {namespace ~ = ". *"}, influxdb The query performance of is very slow,And we are worried that in the future, if the influxdb fails, it will be difficult for us to recover from the failure . so we want to switch to Prometheus as a PlanB. 

4 cpu core ,8GB mem: [edge host 1] [edge host 2] [edge host 3] （prometheus server）
⬇️（by remote storage write）
24 core, 128GB mem: [iot master host 1]  （influxdb）
⬇️（by remote storage read）
[prometheus server] 
⬇️(by promql  http api)
[grafana]

We only have one large memory host that can be used to store time series data. We don't know whether cortex or m3 can be deployed on one host. In addition, our team is only familiar with Prometheus thanos at present.

yeah , Prometheus is a pull model. I will close this PR first. We will maintain it in our branch for a while.

**Comment by liguozhong** [comment]
> Yeah

thanks. 
We have used thanos in other projects, Thanos is a great project.
but thanos is not suitable for IOT projects. Thanos needs 128GB memory host, and the network is bidirectional. 
Edge host has only 8 GB of memory, and the network can only send out and prohibit inward network communication

**Comment by liguozhong** [comment]
> Is that really something that can be solved in 126 lines of code? What is the catch?



> Is that really something that can be solved in 126 lines of code? What is the catch?

Yes, the 126 line code works. We are going to use this PR in an IOT project, but this PR is still in the stage of performance test and stress test.

refs map[string]uint64

We are worried that this "refs cache" will expand infinitely and eventually lead to failure, but there is no good way to solve it at present. We hope that it can be put in the community and other experts can help to complete the optimization of "refs cache"

> Is that really something that can be solved in 126 lines of code? What is the catch?


Yes, the 126 line code works. We are going to use this PR in an IOT project, but this PR is still in the stage of performance test and stress test.

refs map[string]uint64

We are worried that this "refs cache" will expand infinitely and eventually lead to failure, but there is no good way to solve it at present. We hope that it can be put in the community and other experts can help to complete the optimization of "refs cache"

**Comment by roidelapluie** [comment]
Hello @liguozhong , we are willing to support this! Can you please help us? We are currently working on a design document:

#8307  https://docs.google.com/document/d/1PpTDtVaKAnhMRxBJ0k7_rCQ3Z3uJVcALgdPo0QpObSk

Thanks!!!!

**Comment by liguozhong** [comment]
Okay, I will complete this PR task

> Hello @liguozhong , we are willing to support this! Can you please help us? We are currently working on a design document:
> 
> #8307 https://docs.google.com/document/d/1PpTDtVaKAnhMRxBJ0k7_rCQ3Z3uJVcALgdPo0QpObSk
> 
> Thanks!!!!

Okay, I will complete this PR task

**Pull request closed without merging**
