### PR TITLE
Cut 2.26.0

### PR DESCRIPTION
**Pull request by bwplotka**
Sorry, for lag. Cutting new candidate based on recent fixes to code mirror.

image

### CODE REVIEW

**Comment by bwplotka** [comment]
```
build github.com/prometheus/prometheus/cmd/prometheus: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
can't load package: package github.com/prometheus/prometheus: unknown import path "github.com/prometheus/prometheus": cannot find module providing package github.com/prometheus/prometheus
```

🤔

**Comment by roidelapluie** [comment]
Error retrieving packages from source 'https://chocolatey.org/api/v2/':
 The remote server returned an error: (503) Server Unavailable.

**Comment by roidelapluie** [comment]
Can you also merge #8655 ? You do not need to rebase this PR.

**Comment by roidelapluie** [comment]
https://status.chocolatey.org/

**Comment by roidelapluie** [comment]
Can we go straight to 2.26.0 ?

**Comment by bwplotka** [comment]
I would be fine to go straight 2.26.0 TBH, given only UI fixed were merged.

**Review by roidelapluie — APPROVED** [review]

**Comment by bwplotka** [comment]
Note: https://github.com/prometheus/prometheus/pull/8640 so not releasing tag yet.https://github.com/prometheus/prometheus/pull/8640#issuecomment-808758837

**Pull request merged**
