### PR TITLE
update vendor'd github.com/prometheus/common/config

### PR DESCRIPTION
**Pull request by adamdecaf**
Updating from https://github.com/prometheus/common/pull/135 

Via: 

```
$ govendor update github.com/prometheus/common/config
```

Fixes: https://github.com/prometheus/prometheus/issues/4173

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
shouldn't this be done using `fetch` instead of `update`  to get the latest from the repo rather than the local copy?
or maybe even include all subpackages 
```
govendor fetch github.com/prometheus/common/...
```

**Comment by krasi-georgiev** [comment]
I always forget the correct commands so I added a simple wiki page with the examples. Feel free to update if you see anything wrong.
https://github.com/prometheus/prometheus/wiki/Updating-a-vendored-package

**Comment by adamdecaf** [comment]
@krasi-georgiev Good call. I get the various tool commands confused. I ran your `fetch` command and pushed.

**Comment by krasi-georgiev** [comment]
Thanks LGTM :+1:

**Pull request merged**
