### PR TITLE
Make scripts/sync_makefiles.sh less chatty

### PR DESCRIPTION
**Pull request by simonpasquier**
Circle CI doesn't mask secret environment variables in logs ([feature request](https://ideas.circleci.com/ideas/CCI-I-397)) so I'd rather disable it for now. Travis CI is [better](https://docs.travis-ci.com/user/best-practices-security/#steps-travis-ci-takes-to-secure-your-data) on this so we could switch to Travis CI [cron jobs](https://docs.travis-ci.com/user/cron-jobs/) instead but 1) there's no guarantee that Travis will never expose data accidentally and 2) this enforces the burden of maintaining 2 CI providers.

IMO changes to `Makefile.common` happen sporadically enough that we can execute the script from someone's local machine whenever an update is due. WDYT?

### CODE REVIEW

**Comment by paulfantom** [comment]
> there's no guarantee that Travis will never expose data accidentally

This is true for every CI system which is showing logs publicly. Travis had some incidents with leaking secrets\[1] in the past and after those they rewrote part of system responsible for printing logs. Right now it is parsing all log lines to prevent leakage. Additionally secrets are permitted to be used only on branches belonging to repository and prohibited on forks (no secrets in PRs).

\[1]: https://blog.travis-ci.com/2017-05-08-security-advisory

**Comment by SuperQ** [comment]
I would much rather keep this automation in place than have to run it manually. If we need to protect the secrets from logs, we should fix the tooling to do this.

**Comment by simonpasquier** [comment]
> If we need to protect the secrets from logs, we should fix the tooling to do this.

ok so here is another version that _shouldn't_ leak anything...

**Comment by SuperQ** [comment]
Thanks @simonpasquier

**Comment by paulfantom** [comment]
Lgtm

**Pull request merged**
