### PR TITLE
Release 0.13.2

### PR DESCRIPTION
**Pull request by discordianfish**
(This is based on the changes in #671)

#669 talked about breaking config changes we should mention in the changelog as well, but I'm not sure what this is refering so

### CODE REVIEW

**Comment by fabxc** [comment]
The breaking changes are not in master yet.

**Comment by beorn7** [comment]
Looks good in general.

However, I try to have our own dependencies pinned to releases. `client_golang` is now a few commits away from 0.4.0. We could, of course, have a `client_golang` release 0.4.1, too.

In this case, it probably doesn't matter so much, but for example Debian package builder probably appreciate the pinning to releases (as they rebuilt the dependency management via package management).

**Comment by juliusv** [comment]
:+1: but dito about the `client_golang` release.

**Comment by fabxc** [comment]
Is there an immediate need to update all the deps right now?
With pending changes in different branches I'm not too much of a fan of this.

**Comment by juliusv** [comment]
Not urgent from my side - I'll defer to @beorn7 here.

**Comment by discordianfish** [comment]
I think it makes sense to cut a 0.13.2 release now, without updated dependencies. After that we can merge all those breaking changes and cut a 0.14.0 prometheus and 0.4.0 client_golang version. Sounds good I've removed the Godep update, so can we merge this now?

**Comment by juliusv** [comment]
:+1:

**Pull request merged**
