### PR TITLE
fix(docs/querying): explain `ceil` behaviour more explicitly with examples

### PR DESCRIPTION
**Pull request by RiRa12621**
The current version didn't make it explicitly clear that `ceil` only ever rounds to a bigger value and doesn't follow regular mathematical rounding rules. Hence this PR adds some extra wording and examples in line with the [godocs](https://pkg.go.dev/math#Ceil)

### CODE REVIEW

**Comment by juliusv** [comment]
Thanks! While it is already explicit in the word "up" (vs. "down" in the `floor()` description), maybe that is easily missed, so I'm good with adding that extra wording snippet if we add the equivalent phrase to the `floor()` description as well to make it consistent.

Regarding the examples: they could be confusing people because they look like you can pass a scalar value into the function, whereas it only takes an instant vector. I see we do something similar for https://prometheus.io/docs/prometheus/latest/querying/functions/#exp already (albeit with capitalized `Exp`), which is not great. If we want to keep the examples, maybe make them more abstract and not look directly like valid PromQL? Open for other ideas as well. And `floor()` would need equivalent ones then.

**Comment by RiRa12621** [comment]
Agreed.
I'll think of a better example and then also do the same for `floor()`.

**Comment by bwplotka** [comment]
I think it's also worth to mention the underlying Go function used, or is it too much?

**Comment by juliusv** [comment]
> Thanks! I think it's also worth to mention the underlying Go function used, or is it too much?

I don't think we should mention that, that's an implementation detail that shouldn't matter (and can also be implemented differently by other PromQL-compatible services).

**Comment by RiRa12621** [comment]
Maybe I could remove the examples and mention that it's based on the behavior of the go library?
That way there's no need to work with the vector in the example and it stays more slim?

**Comment by juliusv** [comment]
Though I guess the special case examples would still be useful, as those are also listed in https://pkg.go.dev/math#Ceil. Eh, maybe just keep your examples as is for now? Not perfect, but hey...

**Comment by RiRa12621** [comment]
So keep as is and just add the same for floor()?

**Comment by juliusv** [comment]
Yep, that's what I would suggest for now after all. Sorry about the back and forth! And maybe we can come up with something better in the future :)

**Comment by roidelapluie** [comment]
We looked at this pull request during our bug scrub.

@RiRa12621 are you still willing to work on this pull request and address @juliusv 's comments?

**Comment by Rick-Rackow-TomTom** [comment]
Oh, I totally forgot about this. Yeah I'll make a note and then try to get to it ASAP

**Comment by RiRa12621** [comment]
Oh, I totally forgot about this. Yeah I'll make a note and then try to get to it ASAP

**Comment by roidelapluie** [comment]
> Oh, I totally forgot about this. Yeah I'll make a note and then try to get to it ASAP

Thank you, would you have time to update this now by any chance?

**Comment by RiRa12621** [comment]
Done. I'm always a bit confused with the DCO check tho. It does say "signed off by"

**Review by bwplotka — APPROVED** [review]
LGTM!

**Pull request merged**
