### PR TITLE
Fix strange code, add messages to code brought in #8106

### PR DESCRIPTION
**Pull request by proggga**
3-4 years ago I did a change for hackaton and today it was merged #8106 . I realized that I extracted method but in one place I extracted only half of function. Not sure this is good for code so I did a second PR (this) and added error messages because in any issues it will be hard to debug

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Thanks for fixing it. I'm very surprised no test failed for this bug, which would have caused a corruption. I wouldn't block this PR until we get a test (cause merging this fix look high priority to me), but we should really get one.

**Comment by proggga** [comment]
Prob it works because it resets buffer but not sure, I'll try to add some tests here today evening

**Comment by pracucci** [comment]
> Prob it works because it resets buffer but not sure, I'll try to add some tests here today evening

Uhm, not sure. The `writeAt()` is called one extra time with the extra length 🤔

**Review by jesusvazquez — APPROVED** [review]
LGTM thanks for the fix! As marco said too bad a test did not catch this. If you are willing to add another PR for the test that would be awesome

**Comment by pracucci** [comment]
I think I may have understood why no test was failing. The length was written twice, but both times at the same position, overwriting the `alen` (4 bytes) placeholder initially written by `writeLabelIndexesOffsetTable()`. The `writeLabelIndexesOffsetTable()` function initially writes 4 bytes placeholder, then the length is later written back in the position of the placeholder. Writing the length twice was overwriting the placeholder twice, which is superfluous but actually not a corruption bug.

**Comment by proggga** [comment]
Ah looks like you're right, it does w.write ... startPos, the same pos to write, so it re-write over and doesn't break anything, just writing 2 times

**Comment by pracucci** [comment]
Even the written length should have been correct, because `w.f.pos` (used to compute the length as `l := w.f.pos - startPos - 4`) was not advanced by `.writeAt()` (the `.Write()` advanced it, but not the `WriteAt()`).

**Comment by proggga** [comment]
Can you please point me in doc, becuase I can't find any piece of doc saying about updateing position. Just need that to learn

**Comment by pracucci** [comment]
> Can you please point me in doc, becuase I can't find any piece of doc saying about updateing position. Just need that to learn

My reasoning:

- The length of an index section is computed by `l := w.f.pos - startPos - 4` ([code](https://github.com/prometheus/prometheus/blob/main/tsdb/index/index.go#L799))
- Before merging this PR we were computing the length twice. If `w.f.pos` changes between the 2 lines of code where we compute the length, then the 2nd length value would be corrupted.
- The length is written by calling `w.writeAt()` ([code](https://github.com/prometheus/prometheus/blob/main/tsdb/index/index.go#L804C12-L804C21)), so question is: does `w.writeAt()` increases `w.f.pos` or not? I don't think so, because `pos` is increased by `FileWriter.Write()` ([code](https://github.com/prometheus/prometheus/blob/main/tsdb/index/index.go#L295)) but not by `FIleWriter.WriteAt()` ([code](https://github.com/prometheus/prometheus/blob/main/tsdb/index/index.go#L314))

**Comment by proggga** [comment]
i see, interesting

**Comment by proggga** [comment]
Postmortem:
Where did we get lucky - we didn't broke anything yet, even bug was introduced =)

**Comment by jesusvazquez** [comment]
Thanks both for caring about this so much 👍

**Pull request merged**
