### PR TITLE
Release 2.21.0

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
@roidelapluie Shouldn't https://github.com/prometheus/prometheus/pull/7902 be listed as a bugfix in there?

**Comment by roidelapluie** [comment]
> @roidelapluie Shouldn't #7902 be listed as a bugfix in there?

I did not list it as it is minor and it is unclear that this was hit by an actual user.
Should I list it?

**Review by bwplotka — APPROVED** [review]
LGTM, modulo @juliusv comment.

**Comment by juliusv** [comment]
@roidelapluie It was hit by me when using Prometheus at least... and I think it would be hit by anyone just setting up the Prometheus Operator like I did, where targets get a `container` label.

**Comment by juliusv** [comment]
(which was the default with kube-prometheus)

**Comment by roidelapluie** [comment]
> (which was the default with kube-prometheus)

OK, do we need the fix for the service discovery page as well?

**Comment by juliusv** [comment]
@roidelapluie No AFAICS, the code for the label display there never had this bug (https://github.com/prometheus/prometheus/blob/a282d2509971174301408c5a5f96946c478dfb0f/web/ui/react-app/src/pages/serviceDiscovery/LabelsTable.tsx#L12-L22). It should probably be deduped between the two pages at some point.

**Comment by roidelapluie** [comment]
Thanks for checking. I have added it to the changelog.

**Review by juliusv — APPROVED** [review]
:+1:

**Pull request merged**
