### PR TITLE
add ``zScoreOverTime`` function

### LINKED ISSUE #12496: Add ``zscore_over_time`` function
### Proposal

Many developers use ``stddev_over_time`` and ``avg_over_time`` to implement z-score.
This function  can help detecting anomalies over time series.

### PR DESCRIPTION
**Pull request by tuguri8**
fixes #12496

### CODE REVIEW

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub.

We will discuss new PromQL functions during our next dev summit. In particular, this function can be emulated with regular PromQL functions so we need to decide where we put the bar to accept new PromQL functions.

Note that we did not review the code.

**Comment by tuguri8** [comment]
Thanks for commenting! I'll close this PR.

**Comment by beorn7** [comment]
I've had a quick look at the code now. Some thoughts:

This still needs documentation, explaining that the function calculates the z-score of the last sample in the range selector based on the avg and stddev of all the samples in the range selector.

This behavior might actually be not flexible enough. I cannot calculate the z-score of the current value based on a representative period that is longer in the past. (For example, maybe I would like to use the last billing month as a reference. Or I would like some gap, i.e. reference period is the same hour of the day, but one day ago.) The "long form" with `avg_over_time` and `stddev_over_time` gives me that flexibility.

But maybe we could create this flexibility by giving the function the form `zscore_over_time(instant-vector, range-vector)`, where the z-score of the values in instant-vector is calculated with reference to corresponding series in range-vector.

I could also imagine a `zscore(range-vector, range-vector)` aggregator (of a new kind). But understanding this new kind of aggregator might be too much mental overhead for this quite specific case.

Which brings us back to the question if it is worth it. Is the benefit of simplifying
```PromQL
  (job:http_requests:rate5m - avg_over_time(job:http_requests:rate5m[1w]))
/
  stddev_over_time(job:http_requests:rate5m[1w])
```
to
```PromQL
zscore_over_time(job:http_requests:rate5m, job:http_requests:rate5m[1w])
```
really worth the effort of introducing a new functions and its cognitive overhead?

As said, to be discussed at the dev summit.

**Comment by beorn7** [comment]
We discussed this topic once more at the dev summit. The outcome was that we are generally open to adding new PromQL functions and operators behind a feature flag, and want to lower the bar here deliberately, but if a newly proposed function or operator can be emulated with existing PromQL primitives, the bar is still pretty high (the words of the consensus: the pure-PromQL solution has to be "…so complex as to be infeasible").

In this case, the "long form" is actually less than twice as long as the newly proposed form, so that I would make the call that we don't need it.

**Pull request closed without merging**
