### PR TITLE
Split API structs into separate package

### PR DESCRIPTION
**Pull request by jacksontj**
All the structs are currently private structs in the v1 package. This
means if you want to create a client in golang you have to reimplement
(or copy/paste) structs etc. This Splits them out to a separate package
for clarity

### CODE REVIEW

**Comment by jacksontj** [comment]
"stats" have been added to the API response, but this patch applies cleanly for a backport. So if this is something that can get merged in I can rework this for whichever version makes sense.

**Comment by jacksontj** [comment]
cc @fabxc @juliusv @beorn7

**Comment by krasi-georgiev** [comment]
can you explain what is the use case? 
I think so far the v1 api has been used only through the http json requests.

Also why not just export the structs than moving them in a separate package?

**Comment by jacksontj** [comment]
**Use Case**

The use case is still to use them over the HTTP Api -- but specifically if your client is in golang right now that is a pain because (from the original message): `This
means if you want to create a client in golang you have to reimplement
(or copy/paste) structs etc.`

**Separate Package**

The main reason to split them out is for docs clarity. I've submitted some PRs in the past to export structs, and the usual complaint it that it pollutes the package godoc space. If we'd prefer to not move these to a separate package I'll gladly change the PR,

**Comment by krasi-georgiev** [comment]
best if @brian-brazil or @fabxc  jumps on this one with some input.

**Comment by fabxc** [comment]
It's indeed a bit inconvenient if one wants to implement something on top. However, isolated struct-packages are more of an anti-pattern. I think just exporting them within the package they are currently in would be perfectly fine.

**Comment by brian-brazil** [comment]
I'm not sure we want these specific structs exported. All the other things we have exported have obviously been internals, and we gave appropriate warnings to the users of them that their use was unsupported which was understood and accepted.
For the structs backing our actual public APIs, that's not really going to be the case. I think this sort of thing belongs in https://github.com/prometheus/client_golang/tree/master/api

**Comment by krasi-georgiev** [comment]
> if you are importing a package just to use its types you are doing somehting wrong.
Package should be imported for its functionality!

That is what I belive in :clap:  :smile:

**Comment by jacksontj** [comment]
This PR now has conflicting instructions I have both ` I think just exporting them within the package they are currently in would be perfectly fine.` and `I'm not sure we want these specific structs exported`. Which one are we working with here?

These particular structs are in use both by the server (as they are what is marshaled out) and the client (as they are receiving them). From the rest of @brian-brazil 's comment it sounds like you want me to move these structs to the client_golang package? If so, do you want the api to require that package or do you expect a copy/paste? I'm fine to move the code there, but it really seems like the structs should stay with this package-- since they'd have the same compatibility guarantees as the prometheus v1 API anyways.

**Comment by brian-brazil** [comment]
I'm proposing that we leave things as-is.

**Comment by jacksontj** [comment]
Meaning the expectation for clients is that they copy/paste or make their own structs? That seems like unnecessary complexity/work for http clients in golang

**Comment by brian-brazil** [comment]
I don't think this makes sense overall.

**Pull request closed without merging**
