### PR TITLE
*: cut 2.0.0-beta.1

### PR DESCRIPTION
**Pull request by fabxc**

### CODE REVIEW

**Comment by grobie** [comment]
Any breaking behavior since the last one we should mention in the changelog?

**Comment by fabxc** [comment]
I thought we settled for not writing changelogs for pre-releases?
Anyway, yes – I changed a name in our meta files, which will break. Would be possible to handle but didn't seem worth it to carry migration code in pre-releases. So this technically needs a storage wipe or a quick manual rename through files.

I will mention it in the email of course.

**Comment by brian-brazil** [comment]
Did you mean to put that vendoring change after the beta release?

**Comment by fabxc** [comment]
The commit is ordered before the version change commit. GitHub just shows them by creation data I think.

**Comment by brian-brazil** [comment]
:+1: 

Yeah, it's annoying like that.

**Comment by grobie** [comment]
> I thought we settled for not writing changelogs for pre-releases?

I think in general that's fine, but with bigger changes between 2.0 beta releases, it'd be great to know about breaking / bigger changes.

**Comment by fabxc** [comment]
@grobie added some best-effort notes. PTAL.

**Comment by aecolley** [comment]
I tried a build of the beta.1 tag today (in-place upgrade from beta.0, with the sed rewrite in the release notes), and the prometheus daemon reliably exited with status 2 exactly 30 seconds after reporting "Listening on <listen-address>". No log message. I haven't investigated yet.

**Comment by aecolley** [comment]
I left one running (monitoring itself) overnight. It survived for longer than 30 seconds, but it eventually panicked after 4h52m:

```
prometheus --config.file=$PWD/config.yml --storage.tsdb.path=$PWD/state --storage.tsdb.retention=25h --web.enable-lifecycle --web.listen-address=:9080
INFO[0000] Starting prometheus (version=2.0.0-beta.1, branch=tripadvisor/releng-2.0.0, revision=tr-prometheus-2.0.0-0.5)  source="main.go:204"
INFO[0000] Build context (go=go1.8.3, user=mockbuild@aecolley.dhcp.tripadvisor.com, date=20170814-13:36:57)  source="main.go:205"
INFO[0000] Host details (Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 aecolley.dhcp.tripadvisor.com (none))  source="main.go:206"
INFO[0000] Starting tsdb                                 source="main.go:218"
INFO[0000] tsdb started                                  source="main.go:224"
INFO[0000] Loading configuration file /home/aecolley/tmp/betaprom/config.yml  source="main.go:357"
INFO[0000] Server is Ready to receive requests.          source="main.go:334"
INFO[0000] Starting target manager...                    source="targetmanager.go:67"
INFO[0000] Listening on :9080                            source="web.go:327"
ts=2017-08-14T14:09:24.005051732Z caller=db.go:901 msg="created head block" ulid=01BQGH7SFQ47WNA1JXQ9XRYQ9P mint=1502712000000 maxt=1502719200000
ts=2017-08-14T14:09:24.007536551Z caller=db.go:901 msg="created head block" ulid=01BQGH7SH5VH8HW618RDDFA92H mint=1502719200000 maxt=1502726400000
ts=2017-08-14T16:00:24.004866341Z caller=db.go:901 msg="created head block" ulid=01BQGQK1CRFHTQWEZJEPHVE7CG mint=1502726400000 maxt=1502733600000
ts=2017-08-14T17:00:30.300028011Z caller=compact.go:321 msg="compact blocks" blocks=[01BQGH7SH5VH8HW618RDDFA92H]
ts=2017-08-14T18:00:24.002760283Z caller=db.go:901 msg="created head block" ulid=01BQGYERMPW9068B49D78CSZGS mint=1502733600000 maxt=1502740800000
ts=2017-08-14T19:00:30.300534839Z caller=compact.go:321 msg="compact blocks" blocks=[01BQGQK1CRFHTQWEZJEPHVE7CG]
panic: runtime error: integer divide by zero

goroutine 109 [running]:
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*LeveledCompactor).Plan(0xc4203c9350, 0x7ffc2ed5d454, 0x21, 0x0, 0xc4204cc500, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/compact.go:173 +0x621
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).compact(0xc4202ba540, 0xc420541101, 0x0, 0x0)
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:406 +0x2c5
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).run(0xc4202ba540)
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:281 +0x3c6
created by github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.Open
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:250 +0x488
zsh: exit 2     prometheus --config.file=$PWD/config.yml --storage.tsdb.path=$PWD/state
```

I restarted the same command with the same state directory, and then it aborted after 30 seconds:

```
prometheus --config.file=$PWD/config.yml --storage.tsdb.path=$PWD/state --storage.tsdb.retention=25h --web.enable-lifecycle --web.listen-address=:9080
INFO[0000] Starting prometheus (version=2.0.0-beta.1, branch=tripadvisor/releng-2.0.0, revision=tr-prometheus-2.0.0-0.5)  source="main.go:204"
INFO[0000] Build context (go=go1.8.3, user=mockbuild@aecolley.dhcp.tripadvisor.com, date=20170814-13:36:57)  source="main.go:205"
INFO[0000] Host details (Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 aecolley.dhcp.tripadvisor.com (none))  source="main.go:206"
INFO[0000] Starting tsdb                                 source="main.go:218"
INFO[0000] tsdb started                                  source="main.go:224"
INFO[0000] Loading configuration file /home/aecolley/tmp/betaprom/config.yml  source="main.go:357"
INFO[0000] Server is Ready to receive requests.          source="main.go:334"
INFO[0000] Starting target manager...                    source="targetmanager.go:67"
INFO[0000] Listening on :9080                            source="web.go:327"
panic: runtime error: integer divide by zero

goroutine 107 [running]:
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*LeveledCompactor).Plan(0xc42039cb70, 0x7fff98ba4454, 0x21, 0x0, 0x15ddc89ba80, 0x15de1792800, 0x0, 0x0)
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/compact.go:173 +0x621
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).compact(0xc4201662a0, 0xc420010d00, 0x0, 0x0)
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:406 +0x2c5
github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.(*DB).run(0xc4201662a0)
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:281 +0x3c6
created by github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb.Open
	/builddir/build/BUILD/gopath/src/github.com/prometheus/prometheus/vendor/github.com/prometheus/tsdb/db.go:250 +0x488
zsh: exit 2     prometheus --config.file=$PWD/config.yml --storage.tsdb.path=$PWD/state
```

I'll make sure this is repeatable with the official release binary, and then file a proper bug report.

**Comment by aecolley** [comment]
Someone beat me to it. See bug #3078.

**Pull request merged**
