### PR TITLE
Fix Uyuni SD initialization

### PR DESCRIPTION
**Pull request by witekest**
The change prevents null pointer exception during SD initialization.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can we cover this with a test? This is done for other providers.

**Comment by roidelapluie** [comment]
see `config/testdata/eureka_no_server.bad.yml` to see how we test that usually, sorry for missing the detail in my last comment.

**Comment by witekest** [comment]
Thanks Julien for the hint.

**Comment by roidelapluie** [comment]
Thanks!

**Comment by juliusv** [comment]
@roidelapluie Shouldn't bug fixes be merged into `release-2.32` first, at least according to https://github.com/prometheus/prometheus/blob/main/RELEASE.md#branch-management-and-versioning-strategy, since it otherwise it may require cherry-picking from `main`?

**Comment by roidelapluie** [comment]
I decided not to put that burdain on the contributor. I will cherry pick today.

**Comment by roidelapluie** [comment]
(the PR already had commits that were not in the release branch)

**Comment by juliusv** [comment]
@roidelapluie Ok cool, thanks!

**Pull request merged**
