### PR TITLE
Add SECURITY.md file

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @SuperQ @simonpasquier Can you please review this ?

**Comment by SuperQ** [comment]
Should we add this to the tarball.files section too?

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by roidelapluie** [comment]
> Should we add this to the tarball.files section too?

I would need to think more about his, we currently don't ship markdown files.

**Pull request merged**
