### PR TITLE
Feature: Add support for Azure Container Instances

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Adding support for Azure Container Instances in the Azure discovery service. Azure Container Instances is a new service by Microsoft which does away with the need to manage your own vm's to run your containers on. This works well, however they did not implement any monitoring yet. Hence, I modified the azure discovery service to also look for containers instances.

Small footnote, this is the first time contributing to this project + the first time using go. So the code probably needs some polishing. But we're using it, and it seems to work fine.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. Unfortunately we are not accepting any new SD integrations at the moment, due to insufficient resources to maintain what we already have.

**Comment by NielsZeilemaker** [comment]
@brian-brazil that's understandable. I can imagine that the SD integrations will be very fragile.

**Comment by brian-brazil** [comment]
Fragile and maintenance heavy. I think we've up to 5 different ways to authenticate to AWS.

What I would suggest doing is converting this to work with file_sd_configs.

**Comment by krasi-georgiev** [comment]
due to lack of man power to review and maintain new SD we are on permanent hold for adding new SD.

As a replacement we have now added an example how to implement a custom SD adapter that converts any SD to json file that can be used by the file SD 
https://github.com/prometheus/prometheus/tree/master/documentation/examples/custom-sd

**Pull request closed without merging**
