### PR TITLE
scrape: Prometheus server support exemplar in native histogram

### PR DESCRIPTION
**Pull request by fatsheep9146**
After https://github.com/prometheus/client_model/pull/80 is merged
we should mirror the change and support parsing those exemplars and ingesting them, as @beorn7 suggested

https://github.com/prometheus/client_model/pull/80#issuecomment-1906275479

### CODE REVIEW

**Review by beorn7 — APPROVED** [review]
Thank you.

The next step would be to actually _use_ the new protobuf field.

Currently, we parse the exemplars from the classic buckets, even if we are ingesting native histograms. I guess the behavior should be that we don't do that if there is at least one exemplar in the new dedicated field. @fatsheep9146 would you be interested in implementing that, too?

**Comment by fatsheep9146** [comment]
> Thank you.
> 
> The next step would be to actually _use_ the new protobuf field.
> 
> Currently, we parse the exemplars from the classic buckets, even if we are ingesting native histograms. I guess the behavior should be that we don't do that if there is at least one exemplar in the new dedicated field. @fatsheep9146 would you be interested in implementing that, too?

Yes, of course. I will also implement that too! @beorn7

**Comment by Nexucis** [comment]
is it safe to include this PR in the next release (v2.50) @beorn7 @fatsheep9146  ? Just asking if I can simply rebase the release branch based on `main` or I will need to cherry pick a bug fixed that has been merged this morning on `main` to avoid to include this one.

**Comment by beorn7** [comment]
I think it is safe to include this PR. The code added here is simply not exercised anywhere.

**Pull request merged**
