### PR TITLE
Exit when web server encounters a startup error

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc

**Comment by juliusv** [comment]
The channel approach instead of normal error return is necessary here because the web server blocks in the successful case and needs to be started in its own goroutine.

**Comment by fabxc** [comment]
Not sure if it so great that we basically crash the server if ListenAndServe errors at a later point. But I've never seen this happen and there is probably no much better solution.

So :+1:

**Comment by juliusv** [comment]
Yeah, by putting the listening and serve-forever into the same API call, Go doesn't make a better solution very doable here unfortunately.

**Pull request merged**
