### PR TITLE
Update documentation about existing feature-flags

### PR DESCRIPTION
**Pull request by ArthurSens**
The feature-flags `created-timestamp-zero-ingestion` and `concurrent-rule-eval` were not listed in the docs for the `--enable-feature` flag.

Additionally, `promql-at-modifier` and `promql-negative-offset` are always on by default (you can't turn them off), so I thought they could be removed from the docs as well

### CODE REVIEW

**Review by machine424 — COMMENTED** [review]
If we stop documenting them, I think it's better to remove their cases https://github.com/prometheus/prometheus/blob/cd72ebb05f79bdd4ddd96a65e3759e2310b173d8/cmd/promtool/main.go#L324 and https://github.com/prometheus/prometheus/blob/cd72ebb05f79bdd4ddd96a65e3759e2310b173d8/cmd/prometheus/main.go#L232 to avoid any confusion.

**Comment by ArthurSens** [comment]
That would be a breaking change, wouldn't it? I believe there's coordination going on to eventually remove them in 3.0

https://github.com/prometheus/prometheus/issues/13206
https://github.com/prometheus/prometheus/issues/13207

**Comment by machine424** [comment]
The default cases for unknown flags just log/print stuff, only the message would change and I wouldn’t consider that as breaking.
But the default cases behavior may change in the future (so it exit 1 or sth instead of just logging/printing, in that case, we may break stuff indeed).

**Comment by roidelapluie** [comment]
I merged this. We could remove the case but we always had hidden flags, so it is not an issue for the moment.

**Comment by kushalShukla-web** [comment]
i think this issue is closed right ?

**Comment by ArthurSens** [comment]
Not sure what you mean, this is a pull request 🤔

**Pull request merged**
