### PR TITLE
up limitSeries to 50000

### PR DESCRIPTION
**Pull request by perestoronin**
Please up limitSeries to 50000 or move this constants to prometheus global config.

https://github.com/prometheus/prometheus/pull/5139

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks, It seems like something that is not wise. Giving 10000 series to the browser is already a lot.

**Comment by perestoronin** [comment]
What about "move this constants to prometheus global config" ?

PS. In my case needs 50000 lines.

**Comment by roidelapluie** [comment]
It seems like you should use the API directly, any browser would be unusable with 50k lines.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and are closing per the above. If you'd like more help with your use case I'd suggest asking on  the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users).

**Pull request closed without merging**
