### PR TITLE
Update dependencies for 2.48

### PR DESCRIPTION
**Pull request by LeviHarrison**
github.com/digitalocean/godo was causing issues at it requires go 1.21 so I added a hack to not update that

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can you revert the makefile? I don't think we want this permanently. Maybe a temporary exclude in the go.mod is isnough

**Comment by LeviHarrison** [comment]
I think we would have to exclude every version that has this go requirement individually though (there is more than one) which could get messy/break at any time.

**Comment by roidelapluie** [comment]
you could still revert the makefile for now.

**Comment by bboreham** [comment]
Note there is a comment on the upstream PR that they un-did the change.

**Comment by LeviHarrison** [comment]
👍🏻

**Comment by LeviHarrison** [comment]
Looks like https://github.com/hashicorp/nomad/pull/18311 broke nomad's go 1.20 compatibility

**Comment by LeviHarrison** [comment]
Well looks like #11860 does this so I'll take a look at that

**Comment by LeviHarrison** [comment]
Ok #11860 is good to be merged once rebased, so I guess I'll just pull it in here

**Comment by roidelapluie** [comment]
Ci fails

**Comment by bboreham** [comment]
```
/go/pkg/mod/github.com/hashicorp/nomad/api@v0.0.0-20231013131504-b697de9dda24/error_unexpected_response.go:11:2: package slices is not in GOROOT (/usr/local/go/src/slices)
```

I have pushed a commit to Levi's branch downgrading that one dependency to the latest stamped version before this change (https://github.com/hashicorp/nomad/pull/18311).

**Comment by LeviHarrison** [comment]
Alright thanks 👍. Think we're good to go now?

**Review by bboreham — APPROVED** [review]
LGTM

**Pull request merged**
