### PR TITLE
Update npm deps for v2.39 and fix the script called to do it

### PR DESCRIPTION
**Pull request by Nexucis**

### CODE REVIEW

**Review by codesome — APPROVED** [review]
Thanks! I am happy to merge this as long as it looks good to you. I don't know much about these packages.

**Comment by Nexucis** [comment]
it looks like there is a dependency update that breaks the react-app. Let me see if I can quickly fix it

**Comment by Nexucis** [comment]
should be good now @codesome :)

**Comment by juliusv** [comment]
:+1:

**Pull request merged**
