### PR TITLE
[comments] change word ‘wheter’ to ‘whether’

### PR DESCRIPTION
**Pull request by liguozhong**
[comments] change word ‘wheter’ to ‘whether’

### CODE REVIEW

**Comment by roidelapluie** [comment]
there is one in cmd/prometheus/query_log_test.go , maybe do both at the same time

**Comment by liguozhong** [comment]
> there is another one in cmd/prometheus/query_log_test.go , maybe do both at the same time

done,thanks

**Comment by codesome** [comment]
Thanks!

**Comment by liguozhong** [comment]
> Thanks!

thanks

**Pull request merged**
