### PR TITLE
discovery/file: fix logging

### LINKED ISSUE #4177: Errors observed in logs
## Bug Report
**What did you do?**
We see these messages in our prometheus logs. 

**What did you expect to see?**
No error or warnings in the log messages. 

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

  Linux 4.1.12-124.14.3.el7uek.x86_64 x86_64

* Prometheus version:

prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10

* Prometheus configuration file:

* Logs:
```
level=error ts=2018-04-26T05:28:00.428178689Z caller=stdlib.go:89 component=web caller="http: panic serving 127.0.0.1:40071" msg="reflect: slice index out of range"
level=error ts=2018-04-26T06:47:56.498513884Z caller=stdlib.go:89 component=web caller="http: panic serving 127.0.0.1:47619" msg="reflect: slice index out of range"

level=debug ts=2018-04-26T05:08:32.100997431Z caller=file.go:289 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths="unsupported value type"
level=debug ts=2018-04-26T05:08:32.101002955Z caller=file.go:289 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths="unsupported value type"


```

For the logging statement below:
level=debug ts=2018-04-26T05:08:32.100997431Z caller=file.go:289 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths="unsupported value type"
 
The following stop() function gets called when file watcher needs to be stopped. 
github.com/prometheus/prometheus/discovery/file/file.go
```
// stop shuts down the file watcher.
func (d *Discovery) stop() {
        level.Debug(d.logger).Log("msg", "Stopping file discovery...", "paths", d.paths)
``` 
The logging function does not handle arrays/slices.
github.com/go-logfmt/logfmt/encode.go

``` 
func writeValue(w io.Writer, value interface{}) error {
   :
default:
                rvalue := reflect.ValueOf(value)
                switch rvalue.Kind() {
                case reflect.Array, reflect.Chan, reflect.Func, reflect.Map, reflect.Slice, reflect.Struct:
                        return ErrUnsupportedValueType
}```

Am I looking at the correct code ?

### PR DESCRIPTION
**Pull request by simonpasquier**
Partial fix for #4177

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
that was quick , Thanks!

did you manage to replicate the bug and test that this fixes it?

**Comment by simonpasquier** [comment]
@krasi-georgiev can we merge this simple fix for now?

**Comment by krasi-georgiev** [comment]
yep good idea the other bug is unrelated to will work on that separately.

LGTM

@brian-brazil PTAL

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
