### PR TITLE
put back feature flag 'delayed-compaction' and 'old-ui'

### PR DESCRIPTION
**Pull request by Nexucis**
This flag has been added with PR https://github.com/prometheus/prometheus/pull/12532.

It seems this flag has been removed somehow. The Git history is not clear 🤔.

Perhaps it's coming from the this commit https://github.com/prometheus/prometheus/commit/60366a8a05c87c922a9d76e532062017a67e5f39

### CODE REVIEW

**Comment by Nexucis** [comment]
I have added back the flag 'old-ui' that seems to have been removed as well (/cc @juliusv)

**Comment by juliusv** [comment]
@Nexucis Thanks for catching that, I guess it got removed somewhere in some 3.0 merge process. However, the list is alphabetically sorted, could you make sure that the added values are sorted correctly as well?

**Comment by Nexucis** [comment]
> @Nexucis Thanks for catching that, I guess it got removed somewhere in some 3.0 merge process. However, the list is alphabetically sorted, could you make sure that the added values are sorted correctly as well?

heu are you sure it should be alphabetically sorted ? Because currently it's not

**Comment by juliusv** [comment]
Whoops, I really thought it was until now, maybe I always looked at the right subparts that were sorted 😅

Oh well... 👍

**Review by juliusv — APPROVED** [review]

**Pull request merged**
