### PR TITLE
Re-ordering config validation

### PR DESCRIPTION
**Pull request by alileza**
according to this breaking changes #1686, adding more explicit error message would help.

### CODE REVIEW

**Comment by juliusv** [comment]
The canonical way for checking additional fields is `checkOverflow()`, see e.g. https://github.com/prometheus/prometheus/pull/1728/files#diff-3baf47c64847a8fb8aaa8cc2e088513bR643. My idea was more to just move the `checkOverflow()` call to the top of the validation method in general, and in all cases (not only for the file SD). But since that's a more fundamental change, it might make sense to hear @fabxc's opinion on that general approach before implementing it.

**Comment by alileza** [comment]
ah i didn't notice, sorry :/. ok then let's wait for @fabxc

**Comment by fabxc** [comment]
Yes, swapping validation order seems right here.

**Comment by alileza** [comment]
i'll make the changes then

**Comment by fabxc** [comment]
Thanks 👍

**Pull request merged**
