### PR TITLE
improve --rules.max-concurrent-evals description

### LINKED ISSUE #13931: improve --rules.max-concurrent-evals description.
### Proposal

Suggest to adjust `–query.max-concurrency` when changing `--rules.max-concurrent-evals` as the rules manager uses the same query engine than the API: https://github.com/prometheus/prometheus/blob/4a6f8704efcabfe9ee0f74eab58d4c11579547be/cmd/prometheus/main.go#L743-L772
Add that to `--rules.max-concurrent-evals`'s description: https://github.com/prometheus/prometheus/blob/633224886a1c975dd3a8a8308a0b1d630048a21c/cmd/prometheus/main.go#L420

Was discussed here: https://cloud-native.slack.com/archives/C167KFM6C/p1712665137550239

### PR DESCRIPTION
**Pull request by tesla59**
Fixes #13931

Based on https://github.com/prometheus/prometheus/pull/13965

builds upon suggestions in https://github.com/prometheus/prometheus/pull/13965#issuecomment-2082772035 and https://github.com/prometheus/prometheus/pull/13965#issuecomment-2083398405

### CODE REVIEW

**Comment by tesla59** [comment]
create a new PR since the original PR had failing checks and it was slate for a while

**Comment by tesla59** [comment]
Hi @machine424 
Can u review please

**Comment by machine424** [comment]
Thanks for the PR
But I'll ping @kushalShukla-web first to see if they're willing to continue working on https://github.com/prometheus/prometheus/pull/13965

**Comment by machine424** [comment]
> Hey @machine424 I was busy with exams , i will complete this pr today
No worries, good luck with your exams!

**Comment by machine424** [comment]
It'll close this as https://github.com/prometheus/prometheus/pull/14120 was merged.
Thanks to you two.

**Pull request closed without merging**
