### PR TITLE
retrieval: Fix "up" reporting for failed scrapes

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@brian-brazil @fabxc

**Comment by srikanth789** [comment]
Hello,

This is my prometheus configuration file.

my global config

global:
scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_timeout is set to the global default (10s).

Attach these labels to any time series or alerts when communicating with

external systems (federation, remote storage, Alertmanager).

external_labels:
monitor: 'codelab-monitor'

Load rules once and periodically evaluate them according to the global 'evaluation_interval'.

rule_files:

"first.rules"
"second.rules"
A scrape configuration containing exactly one endpoint to scrape:

Here it's Prometheus itself.

scrape_configs:

The job name is added as a label job=<job_name> to any timeseries scraped from this config.

job_name: 'prometheus'

metrics_path defaults to '/metrics'

scheme defaults to 'http'.

static_configs:

targets:
"10.93.1.134:9100"
"10.9.64.47:9100"

Issue No 1: When i try to wget from prometheus server to destination server. Seems like request has been sent but response is not getting. Below is the reference.

wget http://10.9.64.47:9100/metrics
--2017-06-08 13:17:09-- http://10.9.64.47:9100/metrics
Connecting to 10.9.64.47:9100... connected.
HTTP request sent, awaiting response...

Issue No 2: In prometheus dashboard i can see the target servers are showing DOWN not sure what would be the issue. I might be doing something wrong. Any help would be greatly appreciated. Please find attached screeen shot is what i'm facing.
prometheus dashboard

**Comment by brian-brazil** [comment]
:+1:

**Comment by brian-brazil** [comment]
@srikanth789 Please do not post in unrelated issues. https://groups.google.com/forum/#!aboutgroup/prometheus-users is the best place to request support.

**Pull request merged**
