### PR TITLE
Cut v2.39.0

### PR DESCRIPTION
**Pull request by codesome**
I will cut the release tomorrow.

### CODE REVIEW

**Comment by juliusv** [comment]
Doesn't this need the UI version bump (`make ui-bump-version`) again as well?

**Comment by codesome** [comment]
Right, thanks for reminding.

**Comment by codesome** [comment]
I wonder why didn't the CI catch it here

**Comment by codesome** [comment]
Btw https://twitter.com/_codesome/status/1577264183208398848 🎉. This was not visible in the prombench; I believe it heavily depends on what the Prometheus is doing and I think https://github.com/prometheus/prometheus/pull/11147/ had a major impact in that reduction.

**Comment by Nexucis** [comment]
wait the bump is again false, let me fix it quickly before the release

**Comment by Nexucis** [comment]
@codesome I created a PR to fix the bump-version manually: https://github.com/codesome/prometheus/pull/2. I will have to look deeper at the script why it doesn't work

**Comment by douglascamata** [comment]
@Nexucis @codesome not sure if you already noticed, but the `v0.39.0` tag wasn't pushed yet 😬

**Comment by codesome** [comment]
@douglascamata you mean the node packages?

**Pull request merged**
