### PR TITLE
Rate extrapolation mode "median/half".

### PR DESCRIPTION
**Pull request by beorn7**
@brian-brazil @fabxc

Not to merge right now, just for you to experiment.

This combines both ideas, i.e. using median (not average) _and_ extrapolate to half the median at the assumed start/end of a series.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Similar to #1253, this causes problems with the #581 case. #1245 is better for resolving #581.

**Comment by beorn7** [comment]
I believe it will deal better with https://github.com/prometheus/prometheus/issues/581 . I'm planning to set up a test server with data like that, and then we can look at the graphs.

**Comment by brian-brazil** [comment]
When I simulated it, it was worse for #581 by half the average sample interval.

**Comment by beorn7** [comment]
Can you provide graphs? I'd like to understand.

**Comment by brian-brazil** [comment]
I did this in a temporary text file as a thought experiment, this was calculating what value `increase([1m])` would have for a 10s sample interval, calculated every 1s for data that was `0 1 1 1 1 1 ...`.

With #1245 with the right timing it's possible to get the true value of 1 for the increase, whereas the closest the half median gets is 1.5.

**Comment by beorn7** [comment]
I'll come back to this PR ASAP. Just loads of distraction right now by other work.

**Comment by beorn7** [comment]
I think your thought experiment is distinctly different from the problem in #581. I'll continue discussion in https://github.com/prometheus/prometheus/pull/1245

**Comment by beorn7** [comment]
Closing as discussed in https://github.com/prometheus/prometheus/pull/1245. I'll create a new PR later today.

**Pull request closed without merging**
