### PR TITLE
Log rule name when evaluating rule groups' Eval function logs anything 

### PR DESCRIPTION
**Pull request by alvinlin123**
in rule group's `Eval` function only log rule group name; it would be nice to log the rule name as well. One use case is when `Rule sample appending failed` happens for a recording rule, it would be useful to know exactly which one failed, so that I won't be as surprised when I see a gap in the metric emitted by the rule.

### CODE REVIEW

**Comment by alvinlin123** [comment]
I understand this PR is creating new logger per rule group, which may hurt performance, so I wrote and ran a benchmark test, and below is the result: 

```
name                      old time/op  new time/op  delta
GroupEvalWithNoSamples-8  3.24ms ± 4%  3.57ms ± 5%  +10.42%  (p=0.008 n=5+5)
```

**Comment by alvinlin123** [comment]
On second thought, I really don't want to worry about perf at all for simple change like this, so I will just add the rule name to each individual logging call.

**Comment by roidelapluie** [comment]
Name is not unique. Can we use id instead?

**Comment by alvinlin123** [comment]
Hi @roidelapluie, I couldn't fine an id field in the `Group` struct, would you kindly let me know which id you were referring to? However your comment made me remember that I probably should add `file` into the logging too, because I think `file` + `rule group name` + `rule name` should uniquely identify a rule too.

**Comment by alvinlin123** [comment]
ok yea `test_windows` is failing because starting from go 1.18 SHA1 is not allowed anymore: https://github.com/golang/go/issues/41682

Although I we can just give `GODEBUG=x509sha1=1` but it's better if we just generate new certificate.

**Comment by roidelapluie** [comment]
Hello,

By ID, I mean the order in the alert in the group.

**Comment by alvinlin123** [comment]
> Hello,
> 
> By ID, I mean the order in the alert in the group.

I see, so I call them "index" in my change, would you prefer the term "id"?

**Comment by alvinlin123** [comment]
Split the cert updates into another PR https://github.com/prometheus/prometheus/pull/10463

Will rebase this PR after cert update PR is merged.

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
