### PR TITLE
Consul SD: Include health check information in meta data

### LINKED ISSUE #770: Consul SD: Include health check information in meta data
So that users who need that information can relabel it onto their metrics.

`__meta_consul_health` or something...

### PR DESCRIPTION
**Pull request by dominikschulz**
This is a first sketch of an implementation of #770. May need some more work. I'd appreciate some early feedback.

Fixes #770

### CODE REVIEW

**Comment by brian-brazil** [comment]
I think you've got your labels the wrong way around, this should go from check -> state.

How many additional RPCs to consul does this add?

**Comment by dominikschulz** [comment]
I'll double check the labels.

The number of RPCs is a valid concern which I also noticed. I'd say it's about two additional RPCs per Node and Service. Which is quite a lot. Don't know if this is worth it. Will try to clean this up as much as possible within the next days.

**Comment by brian-brazil** [comment]
We've had other issues where it appears that the consul client isn't reusing tcp connections, so I'd be very wary of adding more RPC until that is fixed on their end.

**Comment by dominikschulz** [comment]
Did some more testing (no code changes so far).

The label mapping of state -> checks is implemented as suggested by @fabxc in https://github.com/prometheus/prometheus/issues/770#issuecomment-112062345. I can turn it around to be `__meta_consul_health_<check>=<state>` if you think that makes more sense. IMHO both ways have some merit.

The current implementation allows for relabeling rules like:
```
    - source_labels: ['__meta_consul_health_passing']
      regex: '.*,serfHealth,.*'
      action: keep
```

The downside of this implementation is definitely the additional RPC calls to Consul. Given a large number of Consul services this may very well be an issue.

If you think the general approach makes sense we should keep it around until we're sure the Consul issues are fixed on their side.

**Comment by perbly** [comment]
Hi, where are we with this PR? This is one of our missing puzzle pieces to have this information. Regards Per

**Comment by brian-brazil** [comment]
Larger users are running into performance issues with Consul, so more RPCs does not seem wise. In addition you should be trying to scrape targets even if some are reported as unhealthy. Thus I don't think this makes sense on balance.

**Pull request closed without merging**
