### PR TITLE
rulefmt: Remove the need to export ruleGroups

### LINKED ISSUE #7128: RuleGroups.Validate(...) needs unexported struct ruleGroups as input
I'm trying to upgrade prometheus dep in thanos and I'm stuck with this:

```shell
$ make build
all modules verified
>> building binaries /Users/s.rabot/go/bin
 >   thanos
# github.com/thanos-io/thanos/cmd/thanos
cmd/thanos/check.go:88:29: not enough arguments in call to promRgs.Validate
	have ()
	want (rulefmt.ruleGroups)
```

https://github.com/prometheus/prometheus/blob/51c824543bca2f25baa6596827cf4fad8f18dc2e/pkg/rulefmt/rulefmt.go#L66

cc @bwplotka

### PR DESCRIPTION
**Pull request by roidelapluie**
Fixes #7128

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
cc @sylr

**Comment by Harkishen-Singh** [comment]
@roidelapluie recent updates to https://github.com/prometheus/prometheus/pull/7142 have changed the code a bit. Please consider updating the PR after that is merged.

**Comment by Harkishen-Singh** [comment]
This will be good, since having there is better than exporting structs based on `yaml.Node` as they seem less of any use.

**Comment by Harkishen-Singh** [comment]
Extended #7142 to implement this with minor changes. This can be closed now.

**Comment by bwplotka** [comment]
So to me this can be merged as well, looks like quick fix..

**Pull request closed without merging**
