### PR TITLE
fixes space issue in duration range promql

### LINKED ISSUE #6065: promql: Parser bug: Prometheus does not accept spaces after opening brace in subquery.
## Bug Report
**What did you do?**
 
Gave Prometheus a query like `some_query[ 5s]`. Note the space after the bracket.

**What did you expect to see?**
The query get's parsed to the same as  `some_query[5s]` (without space).

**What did you see instead? Under which circumstances?**

` Error executing query: invalid parameter 'query': parse error at char 12: missing unit character in duration`

**Environment**

* System information:

	`Linux 5.2.16-200.fc30.x86_64 x86_64`

* Prometheus version:
`prometheus, version 2.12.0 (branch: master, revision: 8d3083e2563812da1c1125fafb20b9fe2469f4ba)`

### PR DESCRIPTION
**Pull request by Harkishen-Singh**
Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

fixes #6065 

eg-query

### CODE REVIEW

**Comment by juliusv** [comment]
@Harkishen-Singh Thanks! Rather than removing spaces from the duration token in the parser, it would be better to fix the lexer to just skip spaces (like it does in other places, e.g. https://github.com/prometheus/prometheus/blob/master/promql/lex.go#L578-L579) and just emit the actual duration string as the token.

**Comment by Harkishen-Singh** [comment]
@juliusv sure. Thanks for the suggestion.

**Comment by Harkishen-Singh** [comment]
@juliusv I have updated the lexer to skip over the spaces. Please have a look.

**Comment by brian-brazil** [comment]
This should have unittests.

**Comment by Harkishen-Singh** [comment]
@brian-brazil @juliusv added unit tests. please have a look.

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
:+1: Thanks!

**Pull request merged**
