### PR TITLE
Update nodejs version

### PR DESCRIPTION
**Pull request by SuperQ**
Update to the latest nodejs LTS release. The old v16 ends security support 2023.09.11.

* https://nodejs.org/en/blog/announcements/v20-release-announce
* https://nodejs.org/en/blog/announcements/nodejs16-eol

### CODE REVIEW

**Comment by SuperQ** [comment]
Note, the UI tests use golang-builder's Nodejs version, which doesn't use the node version config file.

**Review by bboreham — APPROVED** [review]
Within the bounds of my JS knowledge, this seems fine.

Note the Windows tests flaked first time around.

**Comment by SuperQ** [comment]
Related golang-builder PR: https://github.com/prometheus/golang-builder/pull/222

I tested a local build with NodeJS 20, everything looks OK.

**Comment by SuperQ** [comment]
Rebuilding, golang-builder images now have nodejs 20.

**Pull request merged**
