### PR TITLE
Update architecture diagram

### PR DESCRIPTION
**Pull request by fabxc**
As we point directly to the commit ref, this has to be two-staged :)

https://github.com/prometheus/prometheus/tree/diag#architecture-overview

### CODE REVIEW

**Comment by brian-brazil** [comment]
s/living/lived/

Should there be an arrow from promql back to storage to cover rules?

**Comment by fabxc** [comment]
I think this should be very high level to inform you what you get with Prometheus and not an accurate data/control flow diagram.
Adding a cycle here isn't saying much without a paragraph of explanation, so I would rather leave it out.

**Comment by fabxc** [comment]
@beorn7 @juliusv any comments regarding the diagram before I go back making changes?

**Comment by beorn7** [comment]
Perhaps call the scraped "Prometheus" better "Prometheus Server", too? ("Prometheus" is the whole ecosystem). In the same area, perhaps replace "Targets" by "Instrumented jobs" and "Exporters".

**Comment by juliusv** [comment]
Main thing I care about: was this produced with an open-source tool, so that anyone can edit it later? Looks cool otherwise, modulo comments from others.

**Comment by juliusv** [comment]
Ok, maybe it's not the main thing, but it surely would be nice.

**Comment by fabxc** [comment]
Same as the old one. See how it's the same notice in the folder and XML+SVG
combi.

**Comment by juliusv** [comment]
\o/ Cool then.

**Comment by juliusv** [comment]
Should it also show remote storage replication integration?

**Comment by fabxc** [comment]
Given how experimental it is I refrained from that, especially as there's
no read-back. But can add if it's generally considered a relevant part.

**Comment by beorn7** [comment]
If we include the remote storage, we would only have the write direction for now, obviously. But agreed that it is experimental, and including it might be misleading (but on the other hand, we might want to emphasize the vision of it...)

**Comment by juliusv** [comment]
Yeah, I'd be for including it, but with a notice that it's currently write-only and experimental.

**Comment by fabxc** [comment]
We can update the diagram more frequently than we have in the past :)
Maybe we have a bit clearer vision for it in the upcoming months.

**Comment by juliusv** [comment]
Sounds good either way to me. Ship it!

**Pull request merged**
