### PR TITLE
Quarantine series upon problem writing to the series file

### PR DESCRIPTION
**Pull request by beorn7**
This fixes https://github.com/prometheus/prometheus/issues/1059 , but
not in the obvious way (simply not updating the persist watermark,
because that's actually not that simple - we don't really know what
has gone wrong exactly). As any errors relevant here are most likely
caused by severe and unrecoverable problems with the series file,
Using the now quarantine feature is the right step. We don't really
have to be worried about any inconsistent state of the series because
it will be removed for good ASAP. Another plus is that we don't have
to declare the whole storage dirty anymore.

@juliusv Welcome to depth level 5 of your review queue. :) This is another easy one...

### CODE REVIEW

**Comment by beorn7** [comment]
@fabxc Could you review this? @juliusv `s review queue is not getting shorter…

**Comment by beorn7** [comment]
@fabxc is currently very overloaded, too.
@juliusv Any chance you could do this after all? Just saying "no" would be an improvement over 8d waiting without notice.

**Comment by juliusv** [comment]
:+1:

**Comment by fabxc** [comment]
:+1:

**Comment by beorn7** [comment]
Rejoice!

**Pull request merged**
