### PR TITLE
Kubernetes Discovery: Ensure metrics path isn't overwritten in example relabeling

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by grobie** [comment]
I think this is the new default already 4d1c929.

**Comment by jimmidyson** [comment]
@grobie New default (https://github.com/prometheus/prometheus/commit/4d1c9296d59b432d207e57e83b26b0894ea79e4a#diff-3baf47c64847a8fb8aaa8cc2e088513bR96) is `.*`, this uses `.+` (something must be present unlike default regex or it will have an empty metrics path set which is obviously bad).

**Comment by grobie** [comment]
Oh, I see. :+1:

**Comment by jimmidyson** [comment]
Thanks @grobie!

**Pull request merged**
