### PR TITLE
Update method name in rules template, fix rendering

### PR DESCRIPTION
**Pull request by juliusv**
Fixes https://github.com/prometheus/prometheus/issues/4407

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
Now this raises the general question of testing web templates. For us to get reasonably confident that they all render correctly and refer to the right Go-internal names, we would have to do a lot of the construction steps that `main()` currently does to get all the relevant backing data structures / objects up and running. Maybe it would make sense (not only for this) to refactor `main.go` to be more reusable and allow you to spin up an entire Prometheus server instance internally without spawning a new process?

**Comment by brian-brazil** [comment]
:+1: 

An e2e test might be easier.

**Comment by simonpasquier** [comment]
LGTM. Thanks for fixing this!

**Comment by juliusv** [comment]
Filed issue for web template tests here: https://github.com/prometheus/prometheus/issues/4417

**Pull request merged**
