### PR TITLE
Various WAL remote write updates.

### PR DESCRIPTION
**Pull request by tomwilkie**
- Export timestamps in seconds.
- Refactor WAL watcher to remove some duplication
- Factor out logging ratelimit & dedupe middleware.

### CODE REVIEW

**Comment by tomwilkie** [comment]
ping @cstyan

**Comment by cstyan** [comment]
@tomwilkie we used to have `readToEnd` but now we just start reading from the beginning of the WAL in start to rebuild the labels cache, and only start sending samples after the starting timestamp.

>     * Start following the last segment at startup <- is this safe?
We need to add in some way to replay the existing WAL if we make this change.

**Comment by tomwilkie** [comment]
@cstyan can we rebuild all this from the latest checkpoint?

I added it as the restart time is too slow - esp. when we start pushing to ~5 remote endpoints, and each one needs to replay.

**Comment by cstyan** [comment]
@tomwilkie iiuc the checkpoints only have the series records for active series that started prior to the existing oldest segment, so we still need to replay the segments. 

I think the right fix is to allow remote storage to replay the WAL sooner, or to start from the newest segment but have go routines for each older segment/checkpoint that populate the cache. With the latter we may drop a few samples right on start up.

**Comment by tomwilkie** [comment]
> @tomwilkie iiuc the checkpoints only have the series records for active series that started prior to the existing oldest segment, so we still need to replay the segments.

Isn't that exactly what we need?  We currently read the entire WAL to get the series records for series started prior to the oldest segment.

**Comment by tomwilkie** [comment]
Yeah, thats exactly what TSDB does: https://github.com/prometheus/tsdb/blob/master/head.go#L467

**Comment by cstyan** [comment]
In this whole block: https://github.com/prometheus/tsdb/blob/master/head.go#L466-L490

We get `LastCheckpoint`, and then replay the segments starting from the first one after the checkpoint. `LastCheckpoint` returns the directory and index of the checkpoint, which is why we increment `startFrom` if we successfully read the checkpoint.

So in this example WAL dir:
```
00006132
00006133
00006134
00006135
00006136
00006137
00006138
00006139
00006140
00006141
checkpoint.005089.tmp
checkpoint.006131
```

Last checkpoint would return `checkpoint.06131` and `6131`. And then head `Init` will read the checkpoint followed by segments 6132-6141.

**Comment by tomwilkie** [comment]
(Closing and opening from the grafana repo, so @cstyan can collaborate)

**Pull request closed without merging**
