### PR TITLE
add endponitslice labels metadata

### PR DESCRIPTION
**Pull request by fcddk**
add endponitslice labels metadata

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks for this! it is not building currently.

cc @brancz  for followup.

**Comment by brian-brazil** [comment]
Tests and docs need updating here.

**Comment by roidelapluie** [comment]
it looks like you have unrelated changes, and the documentation still needs to be documented.

If you need help with this, we can talk during Prometheus Contributor Office Hours, all details here: https://docs.google.com/document/d/1bPIsOssTswA244z5SDlws5Qwzc27hQQ2IukNmkIjmPk/edit

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub. Considering that the last comment was not addressed, we are closing this PR for now. Feel free to reopen if you still need this.

**Pull request closed without merging**
