### PR TITLE
Merge release-2.38 back into main

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
Hmm, it's showing me the same merge conflicts and merge resolution message as in https://github.com/prometheus/prometheus/pull/11176 again. Locally when I do `git merge release-2.38` from `main`, I can just resolve things normally and create a merge commit in `main` without touching `release-2.38`. I wonder why this is not possible here.

**Comment by LeviHarrison** [comment]
Weird. Maybe just bypass the PR for this and push directly to `main`?

**Comment by juliusv** [comment]
Yes, that's a bit unusual, but probably best... I'll try that!

**Comment by juliusv** [comment]
Hah interesting, the second I did that it even auto-closed this PR as merged :)

**Pull request merged**
