### PR TITLE
Merge `release-2.52` back to main

### PR DESCRIPTION
**Pull request by ArthurSens**
To backport the fix done in #14047

### CODE REVIEW

**Comment by ArthurSens** [comment]
Wait... my commit is signed... I don't understand why the DCO check is failing 🤔

**Review by gotjosh — COMMENTED** [review]
LGTM

**Comment by ArthurSens** [comment]
Ok, somehow it turned green. I'll take it

**Review by gotjosh — APPROVED** [review]
LGTM

**Pull request merged**
