### PR TITLE
Improved the output of `promtool test rules`

### PR DESCRIPTION
**Pull request by bluechips23**
This PR improves the output of the command `promtool test rules`. It adds a human readable summary on the top which provides stats about all the alerts that were identified along with their intervals. The new output looks like the image shown below. cc: @simonpasquier

Promtool_change

### CODE REVIEW

**Comment by roidelapluie** [comment]
Hello @simonpasquier can you please review this?

**Comment by bluechips23** [comment]
Thank you. @simonpasquier I would really appreciate a review on this. I am excited about my contribution for Prometheus and I have more ideas where I can help.

**Review by dgl — COMMENTED** [review]
This looks like it could be a nice help for writing alert tests. However I think it will need quite a few changes before it's generally suitable.

**Comment by syepes** [comment]
Any news on the MR?

**Comment by roidelapluie** [comment]
We have looked at this pull request during our bug scrub.

Considering that the original author did not reply, we encourage the community to take over this work if they want to in a new pull request.

Thank you for your contribution.

**Pull request closed without merging**
