### PR TITLE
promtool: Speed up checking for duplicate rules

### PR DESCRIPTION
**Pull request by zecke**
Running `promtool check config` on large rule files is rather slow. Improve this by adding a testcase, benchmark and changing the algorithm used to find duplicates.

```
Before:
goos: darwin
goarch: amd64
pkg: github.com/prometheus/prometheus/cmd/promtool
cpu: VirtualApple @ 2.50GHz
BenchmarkCheckDuplicates-8   	       1	9543373875 ns/op

After:
goos: darwin
goarch: amd64
pkg: github.com/prometheus/prometheus/cmd/promtool
cpu: VirtualApple @ 2.50GHz
BenchmarkCheckDuplicates-8   	     187	   6313867 ns/op
```

### CODE REVIEW

**Comment by dgl** [comment]
@zecke thanks for this, looks good, but there's something strange with [CircleCI build](https://app.circleci.com/pipelines/github/zecke/prometheus/368/workflows/af8b8539-d48b-43d9-80b8-0830aef3c638/jobs/802), could you merge main into this?

**Comment by zecke** [comment]
> @zecke thanks for this, looks good, but there's something strange with [CircleCI build](https://app.circleci.com/pipelines/github/zecke/prometheus/368/workflows/af8b8539-d48b-43d9-80b8-0830aef3c638/jobs/802), could you merge main into this?

I lowered the parallelism in circle-ci but now tests fail in code not touched and in go mod sanity checking. I am not sure whether this is related to my changes at all. Needless to say that building locally works.

**Comment by roidelapluie** [comment]
please revert your circleci changes. it is because you probably also have a circleci account.

**Comment by roidelapluie** [comment]
the last test failure was done with a run with SSH, so it might have been tampered somehow.

**Comment by zecke** [comment]
> please revert your circleci changes. it is because you probably also have a circleci account.

Reverted. How can we proceed? How can I not associate this with my account?

**Comment by zecke** [comment]
> the last test failure was done with a run with SSH, so it might have been tampered somehow.

I tried to retrigger the build.

**Comment by dgl** [comment]
Going to merge from my account as CircleCI seems unhappy with @zecke's account.

**Comment by dgl** [comment]
Thank you @zecke! & sorry for the trouble here, I've asked CircleCI if there's anything we can do better for future contributions.

I've merged your exact branch under #9306.

**Pull request closed without merging**
