### PR TITLE
config: ensure correct labelname in JSON target group.

### PR DESCRIPTION
**Pull request by fabxc**

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
Does that play well with Godeps? It looks like you changed the dependencies in the Godops workspace but not `Godeps.json`.

**Comment by fabxc** [comment]
The author of Godeps described this as the way to do it. If you are waiting for a patch in a dependency, you know will be merged, just apply the patch to the dep folder and it will be overwritten with the next vendor upgrade.

Makes way more sense to me then merging tests that fail until the next vendoring upgrade or leaving a bug unfixed until the next vendoring upgrade.

We/I did this for the last few patches to `client_golang` as well. Worked well.

**Comment by beorn7** [comment]
I see... One day, I'll know to handle Godeps correctly... :)

:+1:

**Pull request merged**
