### PR TITLE
Add promql.ErrStorage, which the API propagates as a 500.

### LINKED ISSUE #2571: Allow mechanism for propagating internal errors from the storage
Currently, any error from storage is returned to the user as a 422 (see #1213 for the discussion).  The argument for this seems predicated on the idea that "the storage interface doesn't report errors", but thats not the case any more.

I propose we allow the storage layer to propagate errors by exposing the apiErr type, and adding a case to https://github.com/prometheus/prometheus/blob/master/web/api/v1/api.go#L192 that passes apiErrs straight through.  That way, the storage can throw an apiErr for internal error.

May need to more apiErr to a new package, so prevent circular imports.

WDYT?

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #2571 - see there for discussion.

### CODE REVIEW

**Comment by tomwilkie** [comment]
@juliusv WDYT?

**Comment by juliusv** [comment]
See my latest comment on https://github.com/prometheus/prometheus/issues/2571 - sorry about my confusion earlier.

**Comment by tomwilkie** [comment]
Updated for https://github.com/prometheus/prometheus/issues/2571#issuecomment-291868311 to put the error in the promql package.  @juliusv PTAL

**Comment by juliusv** [comment]
:+1: awesome

**Comment by tomwilkie** [comment]
Thanks!

**Comment by juliusv** [comment]
Actually I totally missed that this error isn't being set in the engine when storage accesses fail. I believe the engine itself should wrap it around errors coming from the storage layer?

**Pull request merged**
