### PR TITLE
Simplify rule group's EvalTimestamp formula

### PR DESCRIPTION
**Pull request by dimitarvdimitrov**
I found it hard to understand how EvalTimestamp works, so I wanted to simplify the math there or explain how it actually works. 

This PR adds comments to clarify how the expressions in the method work.

### CODE REVIEW

**Comment by roidelapluie** [comment]
(A+B (mod M)) = (A (mod M) + B (mod M))

This is not mathematically correct:

7%2+3%2 != 10%2

**Comment by dimitarvdimitrov** [comment]
thanks for the review @roidelapluie, I addressed this problem. But at the current form of it, I can't say it's more clear to me than. I'm happy to leave it as-is and merge, close the PR if it's not bringing value, or add comments to explain why `EvalTimestamp returns the immediately preceding consistently slotted evaluation time.`

**Comment by roidelapluie** [comment]
Maybe we could better comment the existing calculation. The current form is quite confusing to me as we change the value of offset.

**Comment by dimitarvdimitrov** [comment]
I guess I can rename offset to something else, not sure how much difference this can make.

I will try to understand the current formulation once again, but don't have high hopes. Was there a design doc when this was written or should everything past be in git history?

**Comment by roidelapluie** [comment]
I don't know of any, but changing the formula is a risk of introducing new bugs.

**Comment by dimitarvdimitrov** [comment]
I agree. We should start with understanding why it is how it is. I haven't found the time to get back to this _yet_.

**Comment by dimitarvdimitrov** [comment]
So this commit was apparently a noop https://github.com/prometheus/prometheus/pull/4201/commits/2f9ad6e08e3bc6b7f896abedd276b63293e37634 (part of #4201). It translated `if next < now { next += interval }` to modulo operations and subtraction. I tried adding comments in this PR which explain this. I'm not sure whether bringing back the `if ` won't be a more clear approach instead of comments.

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
