### PR TITLE
Add image build for ppc64le architecture

### PR DESCRIPTION
**Pull request by carlosedp**
Add image build for ppc64le architecture

Signed-off-by: Carlos de Paula <me@carlosedp.com>

### CODE REVIEW

**Comment by carlosedp** [comment]
Tests seem flaky @simonpasquier ... doesn't seem related to the changes.

**Comment by carlosedp** [comment]
Builds and tests 100%:

```
>> running all tests
GO111MODULE=on go test   -mod=vendor ./...
ok  	github.com/prometheus/prometheus/cmd/prometheus	(cached)
ok  	github.com/prometheus/prometheus/cmd/promtool	(cached)
ok  	github.com/prometheus/prometheus/config	(cached)
ok  	github.com/prometheus/prometheus/discovery	(cached)
ok  	github.com/prometheus/prometheus/discovery/azure	(cached)
?   	github.com/prometheus/prometheus/discovery/config	[no test files]
ok  	github.com/prometheus/prometheus/discovery/consul	(cached)
ok  	github.com/prometheus/prometheus/discovery/dns	(cached)
?   	github.com/prometheus/prometheus/discovery/ec2	[no test files]
ok  	github.com/prometheus/prometheus/discovery/file	(cached)
?   	github.com/prometheus/prometheus/discovery/gce	[no test files]
ok  	github.com/prometheus/prometheus/discovery/kubernetes	(cached)
ok  	github.com/prometheus/prometheus/discovery/marathon	(cached)
ok  	github.com/prometheus/prometheus/discovery/openstack	(cached)
ok  	github.com/prometheus/prometheus/discovery/refresh	(cached)
ok  	github.com/prometheus/prometheus/discovery/targetgroup	(cached)
ok  	github.com/prometheus/prometheus/discovery/triton	(cached)
ok  	github.com/prometheus/prometheus/discovery/zookeeper	(cached)
ok  	github.com/prometheus/prometheus/documentation/examples/custom-sd/adapter	(cached)
?   	github.com/prometheus/prometheus/documentation/examples/custom-sd/adapter-usage	[no test files]
?   	github.com/prometheus/prometheus/documentation/examples/remote_storage/example_write_adapter	[no test files]
?   	github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter	[no test files]
ok  	github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/graphite	(cached)
ok  	github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/influxdb	(cached)
ok  	github.com/prometheus/prometheus/documentation/examples/remote_storage/remote_storage_adapter/opentsdb	(cached)
ok  	github.com/prometheus/prometheus/notifier	(cached)
?   	github.com/prometheus/prometheus/pkg/exemplar	[no test files]
?   	github.com/prometheus/prometheus/pkg/gate	[no test files]
ok  	github.com/prometheus/prometheus/pkg/labels	(cached)
ok  	github.com/prometheus/prometheus/pkg/logging	(cached)
?   	github.com/prometheus/prometheus/pkg/modtimevfs	[no test files]
?   	github.com/prometheus/prometheus/pkg/pool	[no test files]
ok  	github.com/prometheus/prometheus/pkg/relabel	(cached)
ok  	github.com/prometheus/prometheus/pkg/rulefmt	(cached)
?   	github.com/prometheus/prometheus/pkg/runtime	[no test files]
ok  	github.com/prometheus/prometheus/pkg/textparse	(cached)
?   	github.com/prometheus/prometheus/pkg/timestamp	[no test files]
?   	github.com/prometheus/prometheus/pkg/value	[no test files]
?   	github.com/prometheus/prometheus/prompb	[no test files]
ok  	github.com/prometheus/prometheus/promql	(cached)
ok  	github.com/prometheus/prometheus/promql/parser	(cached)
ok  	github.com/prometheus/prometheus/rules	(cached)
ok  	github.com/prometheus/prometheus/scrape	(cached)
ok  	github.com/prometheus/prometheus/storage	(cached)
ok  	github.com/prometheus/prometheus/storage/fanout	(cached)
ok  	github.com/prometheus/prometheus/storage/remote	(cached)
ok  	github.com/prometheus/prometheus/template	(cached)
ok  	github.com/prometheus/prometheus/tsdb	(cached)
ok  	github.com/prometheus/prometheus/tsdb/chunkenc	(cached)
ok  	github.com/prometheus/prometheus/tsdb/chunks	(cached)
?   	github.com/prometheus/prometheus/tsdb/cmd/tsdb	[no test files]
?   	github.com/prometheus/prometheus/tsdb/encoding	[no test files]
?   	github.com/prometheus/prometheus/tsdb/errors	[no test files]
ok  	github.com/prometheus/prometheus/tsdb/fileutil	(cached)
ok  	github.com/prometheus/prometheus/tsdb/goversion	(cached)
ok  	github.com/prometheus/prometheus/tsdb/index	(cached)
ok  	github.com/prometheus/prometheus/tsdb/record	(cached)
ok  	github.com/prometheus/prometheus/tsdb/test	(cached) [no tests to run]
ok  	github.com/prometheus/prometheus/tsdb/tombstones	(cached)
ok  	github.com/prometheus/prometheus/tsdb/tsdbutil	(cached)
ok  	github.com/prometheus/prometheus/tsdb/wal	(cached)
ok  	github.com/prometheus/prometheus/util/httputil	(cached)
ok  	github.com/prometheus/prometheus/util/promlint	(cached)
ok  	github.com/prometheus/prometheus/util/stats	(cached)
ok  	github.com/prometheus/prometheus/util/strutil	(cached)
?   	github.com/prometheus/prometheus/util/teststorage	[no test files]
?   	github.com/prometheus/prometheus/util/testutil	[no test files]
?   	github.com/prometheus/prometheus/util/treecache	[no test files]
ok  	github.com/prometheus/prometheus/web	(cached)
ok  	github.com/prometheus/prometheus/web/api/v1	(cached)
?   	github.com/prometheus/prometheus/web/api/v2	[no test files]
?   	github.com/prometheus/prometheus/web/ui	[no test files]
```

image

**Comment by carlosedp** [comment]
Ping, any news on this?

**Comment by carlosedp** [comment]
Hey folks, can we get this merged before 2.18 is released?
Thanks.

**Comment by carlosedp** [comment]
Ping. Any news on this?

**Comment by carlosedp** [comment]
Any news about merging this?
Thanks!

**Comment by carlosedp** [comment]
Any news on merging this?

**Comment by roidelapluie** [comment]
Thank you for this!

**Comment by carlosedp** [comment]
Awesome! Thanks! :D

**Pull request merged**
