### PR TITLE
Add missing Apache license headers + travis check

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by fabxc** [comment]
👍 

Thanks

**Comment by sdurrheimer** [comment]
I suggest putting this in `prometheus/promu` because other repos might be interested by this feature.

**Comment by fabxc** [comment]
But let's merge this one and move the existing feature set of promu forward.
We can then consider additions like this later.

**Comment by juliusv** [comment]
:+1: thanks.

**Pull request merged**
