### PR TITLE
[ui] service discovery : Add Alertmanager service discovery to Service Discovery WebUI #3843

### PR DESCRIPTION
**Pull request by liguozhong**
Add Alertmanager service discovery to Service Discovery WebUI #3843

Signed-off-by: fuling <fuling.lgz@alibaba-inc.com>

image
image

### CODE REVIEW

**Comment by liguozhong** [comment]
ui module.  @brian-brazil .issue #3843

**Comment by juliusv** [comment]
@liguozhong Hi, the old web UI is going to be removed in favor of the new React UI under `web/ui/react-app` soon. I see this PR still adds functionality to the old UI - could you add it to the new UI instead?

**Comment by liguozhong** [comment]
> @liguozhong Hi, the old web UI is going to be removed in favor of the new React UI under `web/ui/react-app` soon. I see this PR still adds functionality to the old UI - could you add it to the new UI instead?

👌

**Comment by liguozhong** [comment]
> @liguozhong Hi, the old web UI is going to be removed in favor of the new React UI under `web/ui/react-app` soon. I see this PR still adds functionality to the old UI - could you add it to the new UI instead?

done.
image

**Comment by roidelapluie** [comment]
@juliusv can you please review this pull request?

**Comment by roidelapluie** [comment]
The pull request is unfortunately conflicting now.

I would suggest you to rebase it, and it is not needed to have it on the classic UI. Only on the react UI is fine.

Thanks for all your work so far!!

**Comment by roidelapluie** [comment]
Are you willing to continue the work there? This looks great.

**Comment by liguozhong** [comment]
Signed-off-by: fuling <fuling.lgz@alibaba-inc.com>


> Are you willing to continue the work there? This looks great.

done.
image

**Comment by liguozhong** [comment]
GO111MODULE=on /go/bin/golangci-lint run --timeout 2m ./...
ERRO Timeout exceeded: try increasing it by passing --timeout option 
make: *** [Makefile.common:192: common-lint] Error 4

image

**Comment by fhemberger** [comment]
This seems to be good, anything missing @juliusv, @roidelapluie?

**Comment by roidelapluie** [comment]
We have looked at this pull request during our bug scrub.

Unfortunately this would need another rebase. @liguozhong are you still willing to work on this?

Thank you for your contribution.

**Comment by liguozhong** [comment]
I will try

**Comment by liguozhong** [comment]
2023-10-10 version 
image

**Comment by liguozhong** [comment]
> We have looked at this pull request during our bug scrub.
> 
> Unfortunately this would need another rebase. @liguozhong are you still willing to work on this?
> 
> Thank you for your contribution.

Because this PR existed for too long, it was difficult for me to complete the git rebase. There were too many conflicting files. I submitted another PR to solve the problem of too many git conflicts. Otherwise, it would take a very long time to resolve the git conflicts. Thank you for your understanding.

@roidelapluie ready for review in another PR
https://github.com/prometheus/prometheus/pull/12962

**Comment by bwplotka** [comment]
Thanks, sounds like we could keep the discussion and review on the next one: https://github.com/prometheus/prometheus/pull/12962

Closing this one as dup for now 🤗

**Pull request closed without merging**
