### PR TITLE
docs: Update chunk layot for NHCB

### PR DESCRIPTION
**Pull request by beorn7**
Another part of resolving https://github.com/prometheus/prometheus/issues/12005 .

### CODE REVIEW

**Comment by beorn7** [comment]
@krajorama @zenador is that all we need to document NHCB for the on-disk format?

**Review by krajorama — APPROVED** [review]
Correct. The formatting and placement of the note about `<custom>` looks a bit weird, but I'm not a tech writer to advise on style :)

**Comment by krajorama** [comment]
> @krajorama @zenador is that all we need to document NHCB for the on-disk format?

For now yes, but later when we have #14730 implemented, we should update https://github.com/prometheus/prometheus/blob/main/tsdb/docs/format/wal.md as well. cc @carrieedwards

**Review by fionaliao — APPROVED** [review]

**Review by jesusvazquez — APPROVED** [review]

**Comment by beorn7** [comment]
Thank you.

WRT location of the notes: I just put it with all the other notes. It also struck me as weird to explain all of that only at the bottom, but I didn't want to do two changes in one go.

**Pull request merged**
