### PR TITLE
web/ui: Consistent Content-Type for js and css

### PR DESCRIPTION
**Pull request by mrasu**
Currently, When `/etc/mime.types` has a unusual mime type, web of prometheus uses the type and you may get unexpected result.
With this change, web returns consistent Content-Type header for static js and css files

To reproduce:
1. Add a type at the end of `/etc/mime` like `text/x-js js`
2. Run prometheus
3. Request js file like `http://localhost:9090/static/vendor/js/jquery.min.js`
4. You will see Content-Type of the response is `text/x-js` instead of `application/javascript`

Relates to https://github.com/prometheus/prometheus/issues/4246

Signed-off-by: mrasu <m.rasu.hitsuji@gmail.com>

### CODE REVIEW

**Comment by mrasu** [comment]
Because simulating a change of `etc/mime.types` is not easy for me and existing tests for web doesn't test behavior deeply, I believe no test is needed.
But if it is needed, I will

**Comment by simonpasquier** [comment]
Maybe this should be moved to https://github.com/prometheus/common/ as AlertManager and pushgateway also rely on `http.FileServer`. @brian-brazil WDYT?

**Comment by brian-brazil** [comment]
Makes sense, pgw probably needs it too.

@beorn7 FYI

**Comment by mrasu** [comment]
Thanks for the feedback!
I made at common https://github.com/prometheus/common/pull/191

**Comment by beorn7** [comment]
Thanks for the heads up. I'll follow the implementation in prometheus/common and will adopt it in the PGW once done.

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
prometheus/common got a new release, so I guess it's best to close this PR (or rework into one making prometheus/prometheus use the file server from prometheus/common).

**Pull request closed without merging**
