### PR TITLE
Create rds discovery logic

### PR DESCRIPTION
**Pull request by sheldor14**
We want to be able to discover rds instances from prometheus so we do not have to directly go thru cloudwatch. This discovery file uses the rds apis to fetch rds instance metadata for us to use to filter one, similar to the ec2 discovery logic

### CODE REVIEW

**Comment by sheldor14** [comment]
cc @SuperQ

**Comment by SuperQ** [comment]
I think we should create a more generic `aws_sd_configs` that is role-based like the Kubernetes SD. This way we can add additional AWS endpoints later without a lot more duplicate code.

For example, we also probably want elasticache.

**Comment by roidelapluie** [comment]
@sheldor14 are you still willing to work on this and move it to a generic aws_sd, as suggested by @SuperQ  ?

Thanks!

**Comment by beorn7** [comment]
Looking at this during the bug scrub again.

Since there was no follow-up, we'll close this now. However, we would still love to see progress on this. Whoever wants to help, please feel free to create a new PR or work on this one.

**Pull request closed without merging**
