### PR TITLE
Update Issue Template

### PR DESCRIPTION
**Pull request by Gouthamve**
This is a comment in markdown and won't be shown after creating the issue.

cc @brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Are there docs on this behaviour? I can't find any.

**Comment by Gouthamve** [comment]
Umm, I copy pasted the "comment" while creating a issue and checked it via preview. The comment did not show up.

**Comment by brian-brazil** [comment]
Well, if it doesn't work we'll know soon enough. Thanks!

**Comment by Gouthamve** [comment]
Turns out it does :smile:  Welcome!

**Pull request merged**
