### PR TITLE
Changelog: Add hyperlinks to PRs

### LINKED ISSUE #8689: CHANGELOG: hyperlink PRs
## Proposal

I find the Prometheus CHANGELOG to be quite unfriendly - hyperlinking the PRs would make things a lot nicer, imo.

Happy to do this once given the go-ahead, so assign to me if you're happy for me to do this. Thanks

### PR DESCRIPTION
**Pull request by conorevans**
Signed-off-by: Conor Evans <coevans@tcd.ie>

Closes #8689 

Sed pattern: `'s/ #\([0-9]*\)/ [#\1](https:\/\/github.com\/prometheus\/prometheus\/pull\/\1)/'`

I then did a quick regex for `\(#[0-9]+\)` and in fact the most recent Go 1.16 change was the only one :)

### CODE REVIEW

**Comment by conorevans** [comment]
https://github.com/conorevans/prometheus/blob/conorevans/changelog-include-links/CHANGELOG.md

**Comment by roidelapluie** [comment]
Do you also want to do the tsdb PR in this PR?

**Comment by conorevans** [comment]
Sure thing @roidelapluie, did `prometheus/common` while here too.

**Review by roidelapluie — APPROVED** [review]

**Comment by beorn7** [comment]
I'm not happy with this. If you look at the changelog in the Github context, the PRs are hyperlinked anyway.

This change only helps if you render the markdown outside of Github. However, if you just want to look at the unrendered markdown, this change bloats the text size and makes it much less readable.

I also think we should do the changelog formatting consistently across repos, so this is something we should discuss in a larger group.

**Pull request merged**
