### PR TITLE
storage: Fix checkpointing of fully persisted memory series.

### LINKED ISSUE #2374: Storage: Possible bug handling chunks with very few (one?) samples.
Across the SoundCloud fleet of Prometheus servers, I have seen rare series quarantining because of the dreaded "dropped more chunks from persistence than from memory" error. So far, we attributed this error to data corruption (as the most likely scenario is a truncated file, which can plausibly happen in many different error cases). Now I have seen it happen with the same time series on two mirrored servers, which hints towards properties of that time series to be a factor. The time series in question were very sparse, like one data point every couple of hours. This is a rare occurrence in typical Prometheus setups, so a bug caused by that would only be tickled rarely. Since a head chunk is closed if it doesn't get any samples appended for more than 1h, the time series in question would have only chunks with one sample each. This might throw series maintenance off the rails.

### PR DESCRIPTION
**Pull request by beorn7**
@brian-brazil 

Fixes #2374 

This also fixes/improves a bunch of minor issues that I stumbled upon while hunting for this bug.

### CODE REVIEW

**Comment by beorn7** [comment]
I'm canarying this right now on real servers. Will lot you know how it goes.

**Comment by brian-brazil** [comment]
:+1:

Thanks for tracking this down. What sort of effect will this have on checkpoint size?

**Comment by brian-brazil** [comment]
Also, could we distinguish between series with no chunks to persist that have been written to the index, and ones that haven't? We can exclude the former to reduce checkpoint size if I'm understanding this correctly.

**Comment by beorn7** [comment]
We cannot exclude any of the series this PR re-adds to the checkpoint. _All_ the series are anyway always in the labelname→labelvalue and labelpair→FP index. The problem is the FP→metric index. It is in LevelDB for archived series and purely in memory for in-memory series. In other words: Every series that is in the checkpoint is _not_ in the LevelDB FP→metric index but only in memory (which is the reason why we need to checkpoint it).

WRT checkpoint size: It depends heavily on the nature of the data, of course. In practice, on my two parallel production servers, the difference cannot be distinguished from the noise. The relative difference will matter if you have a lot of series churn but very little persistence pressures, resulting in many metrics in the checkpoint but few chunks.

**Comment by beorn7** [comment]
OK, my canary has finished a fill maintenance cycle. I'm pretty confident this fixes the issue.

**Pull request merged**
