### PR TITLE
Updated action workflow files to work with new test infra Dockerimages.

### PR DESCRIPTION
**Pull request by geekodour**
ref : https://github.com/prometheus/test-infra/pull/362

cc: @krasi-georgiev 

Signed-off-by: Hrishikesh Barman <hrishikeshbman@gmail.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
Thanks!

**Comment by nevill** [comment]
switch to pull request branch: object not found. Could not setup environment, please check logs.

**Pull request merged**
