### PR TITLE
Allow importers to override remote write HTTP client

### PR DESCRIPTION
**Pull request by rfratto**
This PR adds a `NewClient` field to `remote.WriteStorage` to define the function used to create a remote write client. This can allow downstream repositories using Prometheus to add extra functionality to the created HTTP clients used in the remote write queues. 

The `rws` field of `remote.Storage` has been exposed as `Write` to give users of `remote.NewStorage` access to the new field.

I'm opening this in draft for now; it's not clear if this is the best approach to being able to modify the underlying HTTP client that are created for the queues.

/cc @cstyan @tomwilkie 

Signed-off-by: Robert Fratto <robertfratto@gmail.com>

### CODE REVIEW

**Review by csmarchbanks — COMMENTED** [review]
I am ok with this as is, though I do wonder if there is a nicer way to handle customization like this. External sources having to know about all of these components is not ideal, I wonder if passing in a client or providing an option pattern would be nicer?

**Comment by roidelapluie** [comment]
Since grafana agent will become part of Prometheus, why not implementing your use case directly in Prometheus? What are we talking about?

**Comment by rfratto** [comment]
> Since "agent" will become part of Prometheus, why not implementing your use case directly in Prometheus? What are we talking about?

This was used for implementing [SigV4 support](https://github.com/grafana/agent/pull/322) in grafana/agent. I'm happy to contribute it upstream, though I think AWS's SDK might be considered a pretty heavy dependency for prometheus/common. 

> I am ok with this as is, though I do wonder if there is a nicer way to handle customization like this. External sources having to know about all of these components is not ideal, I wonder if passing in a client or providing an option pattern would be nicer?

Yeah, I'm still looking for a nicer way to do this too. In this case, it wouldn't be sufficient for me to just pass in a client directly, since I needed the name of the remote write target to conditionally change the behavior and enable SigV4. 

The option pattern would be fine with me, as long as it gives a `func(name string, conf *ClientConfig) (WriteClient, error)` function and not just a shared client to use across all remote writes.

**Comment by roidelapluie** [comment]
> > Since "agent" will become part of Prometheus, why not implementing your use case directly in Prometheus? What are we talking about?
> 
> This was used for implementing [SigV4 support](https://github.com/grafana/agent/pull/322) in grafana/agent. I'm happy to contribute it upstream, though I think AWS's SDK might be considered a pretty heavy dependency for prometheus/common.

On the other hand, inside Prometheus, we already have the AWS SDK built-in. It seems that this would be pretty useless in common, I wonder if there is a way to have this in this repo. Would need approval of remote write maintainers ofc.

**Comment by brian-brazil** [comment]
>  It seems that this would be pretty useless in common

Keep in mind that the http config in common is used in other places too, any changes there need to make sense in not only all the places we expose HTTP config in Prometheus but also Alertmanager and the blackbox exporter. Nor would it make sense for their to be some auth options that work in some places but not others.

I'd advise against trying to support non-standard authentication methods out of the box, as basically every cloud and hosting provider has their own - in addition to the bespoke auth mechanisms that organisations come up with for their own internal use.

**Comment by roidelapluie** [comment]
Yes, I said useless, not useful.

**Comment by shw26y10** [comment]
I'm

**Comment by csmarchbanks** [comment]
Any opinions on merging this as is vs providing an option pattern?

**Comment by brian-brazil** [comment]
I think we should keep this sort of thing to the simplest thing possible, and I don't think we can get much simpler than this PR.

**Comment by roidelapluie** [comment]
Since we have consensus on having sigv4 directly in Prometheus, is it still needed for grafana agent?

**Comment by rfratto** [comment]
No, we wouldn't need this once sigv4 gets merged upstream.

**Comment by roidelapluie** [comment]
Closing this for now, reopen if needed.

**Pull request closed without merging**
