### PR TITLE
Add k8s 1.15.1 as a vendor dependency.

### PR DESCRIPTION
**Pull request by tariq1890**
~In the interest of getting with the times, we should be using `networking/v1beta1` for ingress and not `extensions/v1beta1`.~

Updating the k8s vendor to v1.15.1

### CODE REVIEW

**Comment by brancz** [comment]
I think @LiliC looked into this before, and identified that this API was only introduced recently, so this change would impact our backward compatibility. My understanding is that the Ingress API as part of the extensions API is sticking around until 1.18.

**Comment by tariq1890** [comment]
Yes you are right. It won't be removed until k8s v1.18 .

**Comment by brancz** [comment]
Then we should wait until the end of 1.17 time-frame to upgrade to the new API.

**Comment by tariq1890** [comment]
I'll undo the api changes and just vendor in the latest k8s library then.

**Comment by tariq1890** [comment]
@simonpasquier Requesting your review as well.

**Pull request merged**
