### PR TITLE
removed "promql-at-modifier" and "promql-negative-offset" features from flag list

### LINKED ISSUE #13207: --enable-feature: remove "promql-at-modifier" and "promql-negative-offset"
### Proposal

Both features are enabled by default and thus should be dropped from the feature flag list for a major version bump.

_edit_
This issue needs no work at this point. https://github.com/prometheus/prometheus/pull/13456 is the proposed fix. We can only merge this when we have a prometheus 3 branch, so this issue is done but will stay open for a bit.

### PR DESCRIPTION
**Pull request by kartikaysaxena**
Fixes #13207
Removed both features from flag list, ran `make cli-documentation` to make necessary changes in the documentation

### CODE REVIEW

**Comment by kartikaysaxena** [comment]
@bboreham @ArthurSens can you please take a look at it?

**Review by ArthurSens — APPROVED** [review]
lgtm, although I'm not the best one to judge here

I'm also not up to date about how issues related to Prometheus 3.0 are handled. Maybe @gouthamve or @jan--f know if this can be merged already or if there's some coordination happening for 3.0?

**Comment by jan--f** [comment]
We want to get the feature flag changes in shortly before the 3.0 release. Otherwise this will hinder 2.x releases before that. So its probably a bit early for this.

**Comment by jan--f** [comment]
@kartikaysaxena mind taking a look at those conflicts? I already changed the base branch to the brand new `release-3.0` branch, so once the conflicts are resolved we can go ahead and merge this.

**Comment by kartikaysaxena** [comment]
Conflicts resolved. Let me know if something else is needed

**Review by jan--f — APPROVED** [review]
:+1:

**Pull request merged**
