### PR TITLE
Backport labels package from 2.0

### PR DESCRIPTION
**Pull request by brian-brazil**
The TSDB depends on this, so CI is failing.
As that's the only dependency, backporting will permit
the CI to pass.

@grobie @fabxc

### CODE REVIEW

**Comment by grobie** [comment]
Right now tsdb expects the package in `pkg/labels/...`. To fix the tests, it either needs to be at this location or tsdbs imports will need to be updated afterwards.

I'm not sure why this new subdirectory was introduced, I assumed @fabxc mirrored the structure of Kubernetes here. Given almost all our directories are indeed golang packages, I'm not sure it's necessary for us, but also no objections against a `pkg` directory.

**Comment by fabxc** [comment]
`pkg/` for packages that may hold relevant domain logic but are not holding core functionality directly is a very common approach if we look at many large Go projects (k8s, etcd, docker, influx, ...). So far we used `util/` but IMO that's not a generally accurate umbrella at all. As the `util` should still be suffix to the package themselves, we end up with `util/xutil`, which has no real benefit over `pkg/xutil`. Just that `pkg/` doesn't imply utility-ness for everything in there.

Just my 2ct.

**Comment by grobie** [comment]
Fine with me.

**Comment by brian-brazil** [comment]
Hmm, we need textparse too for a benchmark.

**Pull request closed without merging**
