### PR TITLE
Log file descriptor limits at startup

### LINKED ISSUE #3564: Log open files ulimit at startup?
We've had over the years a steady stream of issues around the open file ulimit. It might make these a little easier to debug if we included the limit in the startup logs.

### PR DESCRIPTION
**Pull request by simonpasquier**
Fixes #3564

### CODE REVIEW

**Comment by brian-brazil** [comment]
Getrlimits is in Posix, do you really need per-arch variants?

**Comment by simonpasquier** [comment]
AFAICT Windows platforms don't support Getrlimit(). You're right that *nix platforms should be fine though.

**Comment by brian-brazil** [comment]
You should blacklist windows then, rather than whitelisting linux. The CI will catch if something is amiss.

**Comment by simonpasquier** [comment]
@brian-brazil done.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
