### PR TITLE
Add new service discovery: Ambari

### PR DESCRIPTION
**Pull request by deathowl**

### CODE REVIEW

**Comment by brian-brazil** [comment]
What is Ambari? I've never heard of it.

**Comment by deathowl** [comment]
Apache Ambari is a service for managing Hadoop clusters. More info can be found here: https://ambari.apache.org/.
Since Prometheus can be more than useful for monitoring Hadoop clusters with JMX exporter, Node exporter, and also lot of specific exporters: (kafka, zookeeper, etc), I think it's better to give prometheus the ability to discover hosts based on ambari's cluster data.

**Comment by brian-brazil** [comment]
Hadoop is relatively common, however how popular is Ambari for managing it?

There's a maintenance burden for every SD mechanism we accept into the core, so we want to keep it limited to things that are ubiquitous.

**Comment by deathowl** [comment]
Hortonworks ships HDP by default with Ambari (except for some rare edge cases), so it's considered to be pretty common I think. Plus since Ambari is an Apache project, it's not limited to Hortonworks distribution of Hadoop. Anyone, who wants a centralized Hadoop installation, and is not using eg.: CDH or MapR distros(They have their own management interface) is using Ambari Plus if you're thinking of this one as a burden i'm more than happy, to take care of the maintenance of this particular SD mechanism.
Some of the prominent users can be found under the related wikipedia page: https://en.wikipedia.org/wiki/Apache_Ambari

**Comment by brian-brazil** [comment]
So you seem to be saying this is just one of a few ways a user might be managing a Hadoop cluster, I don't think that meets the bar for addition to Prometheus core.

**Comment by deathowl** [comment]
@brian-brazil i wrote you on IRC in public. We could continue the conversation about this topic there, if you don't mind.

**Comment by mattkanwisher** [comment]
We really need the feature in TIP for this
https://tip.golang.org/pkg/plugin/  . The dependency tree will get out of
control

**Comment by brian-brazil** [comment]
Also looking at the code, I don't think this is a useful service discovery method in the broader scheme of things as it's only returns a simple list of hosts on which Hadoop is installed; there's no discovery of services or metadata.

Considering that you'll have non-Hadoop hosts that you'll also need to plumb in in some fashion (via EC2 SD for example), this doesn't buy the typical user anything beyond what they'll already have for general fleet monitoring.

**Comment by deathowl** [comment]
Actual use case follows: 
Take a 1000 node Hadoop cluster as an example fully made of physical nodes. Nodes can be added and decommissioned from the Ambari UI, only ssh access is needed. Also services are being load balanced on the cluster by Ambari(Location of Data Nodes, Name Nodes, etc)  Let's say you have JMX exporters running on Datanodes listening on port 9666. With this SD you can define a service:

`- job_name: service-datanode-jmx
    metrics_path: /metrics
    ambari_sd_configs:
      - username: monitoring
        password: password
        proto: "https"
        port: 9666
        cluster: "clustername"
        ambari_port: 8443
        host: "my.ambari.host"
        refresh_interval: 5m
        services: ['datanode']
`
But you are running node exporter on all of these hosts. Config for that service 

`- job_name: service-hostcollector
    metrics_path: /metrics
    ambari_sd_configs:
      - username: monitoring
        password: password
        proto: "https"
        port: 9100
        cluster: "clustername"
        ambari_port: 8443
        host: "my.ambari.host"
        refresh_interval: 5m
`
This is a pretty common usecase. I mean running Hadoop on physical nodes, with Ambari being the only management utility used. (Actual exporters are installed using Ansible in our case, with the Inventory also feeding from the Ambari API)

**Comment by brian-brazil** [comment]
In that case you're still going to have a machine database that knows about all your nodes, and ansible can write out a config file too.

**Comment by brian-brazil** [comment]
This is host rather than service discovery mechanism, this doesn't make sense to support as it'd imply accepting e.g. a zookeeper discovery that only discovered the zookeeper hosts themselves.

I suggest using another Sd mechanism, or getting ansible to write out targets.

**Pull request closed without merging**
