### PR TITLE
Dockerfile: Run as nobody

### PR DESCRIPTION
**Pull request by Gouthamve**
This needs the mounted directory to be owned by `99:99`

@sdurrheimer @grobie @jimmidyson @devx @brian-brazil @brancz @fabxc

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/2859)

### CODE REVIEW

**Comment by brancz** [comment]
I think in the previous PR it was discussed that this is a breaking change and thus must be deferred until 2.0. But you can just change the target branch from master to dev-2.0.

**Comment by Gouthamve** [comment]
My bad, fixed it. Thanks @brancz

**Comment by andrewhowdencom** [comment]
Just a stub as I'll forget about this, but it might be worth noting the `fsGroup` spec in Kubernetes to fix the perms. https://kubernetes.io/docs/concepts/policy/pod-security-policy/

**Comment by fabxc** [comment]
Anything further speaking against merging this?

**Comment by 2color** [comment]
To anyone who comes across this:

The correct UID would be `65534`

```
$ docker run -it --rm --entrypoint sh prom/prometheus:v2.0.0

/prometheus $ id
uid=65534(nobody) gid=65534(nogroup)
```

**Comment by cliang57** [comment]
Yep for me it is also 65534.
/prometheus $ id
uid=65534(nobody) gid=65534(nogroup)

**Comment by ahoka** [comment]
Nobody is a very bad choice. To mount the data directory as a volume I have to give write permissions on my host to nobody, which is 'nomen est omen' should not have write permissions to any directory.

**Comment by brancz** [comment]
It doesn't mean you should run it as that user, but that you can run it as any user/group combination, giving you the possibility to choose permissions rather than the image forcing you into some seemingly random UID/GID combination.

**Comment by untoldone** [comment]
Isn't it a pretty standard practice to run a docker container processes as root? In this configuration, using attached volumes becomes tricky compared to most every other docker container I've worked with. Basically, I need a startup script to make sure Prometheus has write access to its data volume

**Pull request merged**
