### PR TITLE
bugfix: add missing comma in vector/matrix array

### LINKED ISSUE #14011: Queries failing after upgrade to v2.52.0rc0
### What did you do?

Upgrade to v2.52.0rc0

### What did you expect to see?

Everything continues working just fine

### What did you see instead? Under which circumstances?

Several queries failing (e.g. on Node Exporter Full Dashboard):

Status: 200. Message: ReadArray: expect [ or , or ] or n, but found {, error found in #10 byte of ...|80116"]]}{"metric":{|..., bigger context ...|923262980116"],[1714483080,"47.15923262980116"]]}{"metric":{"device":"/dev/nvme1n1p1","fstype":"vfat|...

Query:

100 - ((node_filesystem_avail_bytes{instance="localhost:9100",job="node_exporter",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance="localhost:9100",job="node_exporter",device!~'rootfs'})

### System information

Ubuntu 24.04 LTS (GNU/Linux 6.8.0-31-generic x86_64)

### Prometheus version

```text
prometheus, version 2.52.0-rc.0 (branch: HEAD, revision: f170a014f31cc97d2aba47cc769e846c68f8545d)
  build user:       root@969a4b73703c
  build date:       20240430-12:21:35
  go version:       go1.22.2
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

_No response_

### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_

### LINKED ISSUE #14040: Malformed JSON in query API result, 2.52-rc.0 regression
### What did you do?

`$ curl 'http://localhost:19092/api/v1/query?query=process_cpu_seconds_total&time=1714716585.782'; echo`

`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"process_cpu_seconds_total","instance":"localhost:19092","job":"prometheus"},"value":[1714716585.782,"0.29"]}{"metric":{"__name__":"process_cpu_seconds_total","job":"a","instance":"baz:20702"},"value":[1714716585.782,"2125535.148752446"]}]}}`

Notice a missing comma between array elements.

### What did you expect to see?

`$ curl 'http://localhost:19091/api/v1/query?query=process_cpu_seconds_total&time=1714716585.782'; echo`

`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"process_cpu_seconds_total","job":"a","instance":"baz:20702"},"value":[1714716585.782,"23600372.135197595"]},{"metric":{"__name__":"process_cpu_seconds_total","instance":"localhost:19092","job":"prometheus"},"value":[1714716585.782,"1.2"]}]}}`

### What did you see instead? Under which circumstances?

See above.

It looks like there are missing comas.

Works fine in 2.51.2

### System information

Linux amd64

### Prometheus version

```text
prometheus, version 2.52.0-rc.0 (branch: HEAD, revision: f170a014f31cc97d2aba47cc769e846c68f8545d)
  build user:       root@969a4b73703c
  build date:       20240430-12:21:35
  go version:       go1.22.2
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:19091"]

  - job_name: "a"
    static_configs:
      - targets:
        - "baz:20702"
```

### PR DESCRIPTION
**Pull request by amirvejahat**
Fixes #14040 
Fixes #14011

### CODE REVIEW

**Comment by ArthurSens** [comment]
We require that all commits are properly signed, could you run `git commit --amend -s` and force push again?

**Comment by bboreham** [comment]
Ideally we would add a test which failed on the previous code too.

**Comment by amirvejahat** [comment]
> We require that all commits are properly signed, could you run `git commit --amend -s` and force push again?
> 
> Also, we want to include this fix on the release branch `release-2.52`. Could you update the base branch for this PR?

Sure, will do

**Comment by ArthurSens** [comment]
I've tested the change locally and it works, but it looks like you've got some extra commits in here by accident 😅

What you wanna do is:
* Clone the repo and checkout the branch `release-2.52`
* Create a new branch from `release-2.52`
* Add your changes in a commit (remember to sign, using the `-s` flag)
* Open a Pull Request with `release-2.52` as the base branch.

You can do this in a new PR, or you can force push commits over here. It's up to you

**Comment by amirvejahat** [comment]
Thanks for the help @ArthurSens . I've fixed the branching issue. please note that circleci has failed due to project suspension, I'm not sure if there's anything I could do to make it work.

**Review by ArthurSens — CHANGES_REQUESTED** [review]
Thanks @amirvejahat, one last thing. 

As Bryan mentioned, it would be nice to have a test case to make sure we don't make this mistake again in the future.

You can add a new test case in `web/api/v1/json_codec.go`, inside the test `TestJsonCodec_Encode`

```go
{
			response: &QueryData{
				ResultType: parser.ValueTypeVector,
				Result: promql.Vector{
					promql.Sample{
						Metric: labels.FromStrings("__name__", "foo"),
						T:      1000,
						F:      1,
					},
					promql.Sample{
						Metric: labels.FromStrings("__name__", "bar"),
						T:      2000,
						F:      2,
					},
				},
			},
			expected: `{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"foo"},"value":[1,"1"]},{"metric":{"__name__":"bar"},"value":[2,"2"]}]}}`,
		},
```

**Comment by ArthurSens** [comment]
> Thanks for the help @ArthurSens . I've fixed the branching issue. please note that circleci has failed due to project suspension, I'm not sure if there's anything I could do to make it work.

Yeah, the failing CI is not related to this PR... no need to worry about it :)

**Comment by gotjosh** [comment]
Hi @amirvejahat at the moment this is breaking `main` so it's rather sensitive - I'll aim to add some tests in the next 30m unless you respond first so that we can keep going.

Thank you again for your contribution!

**Comment by ArthurSens** [comment]
@gotjosh , I've just added the test. Do you mind reviewing it?

**Review by gotjosh — APPROVED** [review]
LGTM

Thank you @ArthurSens!

**Review by ArthurSens — APPROVED** [review]

**Comment by gotjosh** [comment]
This now needs to be merged back into main.

**Comment by ArthurSens** [comment]
> [amirvejahat](/amirvejahat)

Yeah, I've just created the PR to prepare the new release and another PR merging it back to main will follow shortly after

**Comment by amirvejahat** [comment]
Thanks @ArthurSens for adding the test case, I was away from my keyboard. glad to see it's merged now. looking forward to future contribution.

**Pull request merged**
