### PR TITLE
Cut v1.2.3

### PR DESCRIPTION
**Pull request by beorn7**
@brian-brazil

### CODE REVIEW

**Comment by beorn7** [comment]
Also running this in my usual torture environment at SC.

**Comment by brian-brazil** [comment]
:+1:

**Comment by grobie** [comment]
:+1: 

How long do you plan to maintain the 1.2 series?

**Comment by beorn7** [comment]
I plan (euphemism for "I hope") this will be the last bug fix release for 1.2

**Comment by fabxc** [comment]
When discussing our release practices 1.x onwards we explicitly decided to not support any minor but the most recent one.
This case was somewhat special due to the K8S changes but I see no reason to continue after this patch release.

**Pull request merged**
