### PR TITLE
MemPostings: Use dolthub SwissMap for label values/postings map

### PR DESCRIPTION
**Pull request by aknuds1**
Test of [dolthub SwissMap](https://github.com/dolthub/swiss) instead of standard `map` in `tsdb/index.MemPostings`, for performance. Requested by @bboreham for prombench-ing, so we can see if there's any real difference.

Confer corresponding [PR](https://github.com/prometheus/prometheus/pull/13646) for CockroachDB implementation.

### CODE REVIEW

**Comment by bboreham** [comment]
No material difference observed.

image

**Comment by aknuds1** [comment]
@bboreham isn't there a noticeable difference Avg HTTP request latency (especially /api/v1/query_range)?

**Comment by bboreham** [comment]
Yeah if you can explain why the endpoint varies when the time to evaluate doesn't.
The test is explicitly designed to send requests at the same rate.

**Comment by bboreham** [comment]
The difference in http latency measurement has disappeared.

**Comment by aknuds1** [comment]
Closing since outlived its usefulness.

**Pull request closed without merging**
