### PR TITLE
CONTRIBUTING.md: Replace freenode with libera.chat

### PR DESCRIPTION
**Pull request by fhemberger**
/cc @RichiH

### CODE REVIEW

**Comment by RichiH** [comment]
Thanks. Tests flaky, rerunning them manually.

**Comment by RichiH** [comment]
https://github.com/PuerkitoBio/urlesc is failing to download and also archived; trying to figure that out.

**Comment by fhemberger** [comment]
Can't find any reference to the package in the code, yet `go mod tidy` doesn't remove it.
Also looks like the underlying issue in Go has already been fixed in 2015? 🤔

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
