### PR TITLE
fix: dns rfc compliant ttl

### PR DESCRIPTION
**Pull request by jeanphilipperuijs**
Explanation of Changes
1. DNS Caching Mechanism
DNSCache: A new struct to cache DNS responses with their expiration times, based on TTL.
dnsCacheEntry: Stores the DNS message and its expiry time.
2. Modified DNS Discovery
NewDiscovery: Initializes DNSCache.
refreshOne: Checks the cache before making a DNS query. If found in cache and valid, it’s used. If not found or expired, it fetches a new response and caches it.
dnsMsgToTargetGroup: Refactored to convert a DNS message to a Prometheus targetgroup.Group, ensuring TTL compliance by respecting cached responses.

### CODE REVIEW

**Review by bboreham — COMMENTED** [review]
Thank you for your interest in the Prometheus project.
Could you expand your description to include why various comments were removed?

I would expect unit tests of the new functionality, or at least some change in the existing tests.

Also note that various linters complained.

**Comment by jeanphilipperuijs** [comment]
> Thank you for your interest in the Prometheus project. Could you expand your description to include why various comments were removed?
> 
> I would expect unit tests of the new functionality, or at least some change in the existing tests.
> 
> Also note that various linters complained.

Hello!
My apogees for removing some comments, will fix that and linting. :bowing_man:

**Comment by jeanphilipperuijs** [comment]
This pull request introduces significant enhancements to the DNS service discovery functionality by incorporating a caching mechanism for DNS responses. Here are the main changes:

1. **Introduction of DNS Cache:**
   - A new `Cache` struct is added to store DNS responses based on their TTL (Time To Live) values.
   - `dnsCacheEntry` struct is introduced to hold a DNS response and its expiry time.
   - Methods `Get`, `Set`, and `getMinimumTTL` are added to manage the cache. These methods are responsible for retrieving cached entries, adding new entries, and calculating the minimum TTL from DNS records, respectively.

2. **Modifications to the `Discovery` Struct:**
   - A `cache` field of type `*Cache` is added to the `Discovery` struct to hold the DNS cache.
   - The `NewDiscovery` function is updated to initialize the DNS cache when creating a new `Discovery` instance.

3. **Cache Utilization in DNS Lookup:**
   - The `refreshOne` method in the `Discovery` struct is updated to first check the cache for a DNS response before making a network request.
   - If a cached response is found, it is used to create a target group without performing a DNS query.
   - If no cached response is found, a DNS query is made, and the response is stored in the cache before processing.

4. **Conversion of DNS Responses to Target Groups:**
   - A new method `dnsMsgToTargetGroup` is introduced to convert DNS messages into target groups. This method consolidates the logic for processing different DNS record types (e.g., SRV, MX, NS, A, AAAA).

5. **Instrumentation and Metrics:**
   - Existing metrics for DNS lookups and lookup failures are incremented appropriately in the updated methods.
   - The `dnsMsgToTargetGroup` method ensures that the target groups are correctly formed from both cached and fresh DNS responses.

6. **Error Handling and Logging:**
   - Improved error handling is introduced to ensure that lookup failures and invalid records are logged appropriately.
   - The `refreshOne` method handles context cancellation gracefully to avoid processing delays.

### Detailed Explanation of the Changes

#### DNS Cache Implementation
The DNS cache is implemented using a map to store `dnsCacheEntry` structs keyed by DNS names. Each entry includes the DNS message and its expiry time. The `Get` method retrieves an entry if it exists and hasn't expired. The `Set` method adds a new entry to the cache, calculating the TTL from the DNS message to set the expiry time.

#### Updates to Discovery Struct and Methods
The `Discovery` struct now includes a cache. The `NewDiscovery` function initializes this cache along with other fields. The `refreshOne` method first checks if the DNS name is in the cache. If found, it converts the cached message to a target group using `dnsMsgToTargetGroup`. If not found, it performs a DNS lookup, stores the result in the cache, and then converts it to a target group.

#### Conversion of DNS Messages to Target Groups
The `dnsMsgToTargetGroup` method processes DNS messages to extract target information for various record types. This method consolidates the handling of different record types (e.g., SRV, MX, NS, A, AAAA), ensuring consistent processing and labeling.

#### Error Handling and Logging
The updated methods log errors appropriately and handle context cancellations gracefully. This ensures robust operation and easier debugging.

### Summary
These changes enhance the DNS service discovery by adding a caching layer, reducing redundant DNS queries, and improving the overall efficiency and reliability of the discovery process. The addition of the `dnsMsgToTargetGroup` method ensures consistent handling of DNS responses, while improved error handling and logging provide better insights into the discovery process.

**Comment by bboreham** [comment]
TL;DR.
Please focus your explanation more on _why_.  We can see _what_ in the code.

**Comment by jeanphilipperuijs** [comment]
It's to be DNS RFC compliant. Related issues similar to https://github.com/prometheus/prometheus/issues/7552 and https://github.com/prometheus/prometheus/issues/12484 where DNS SD is not possible.

TL:DR
DNS conf changes during runtime but exporter or scraper still hit the old IP

**Comment by bboreham** [comment]
Does this code apply to remote-write, which was the problem in #12484?

**Comment by bboreham** [comment]
It might be a good idea for you to file an issue describing the problem you are fixing.

**Comment by bwplotka** [comment]
From the bug scrub! 

As @bboreham said, none of those issues (https://github.com/prometheus/prometheus/issues/7552 and https://github.com/prometheus/prometheus/issues/12484) relate to DNS service discovery. Seems like https://github.com/prometheus/prometheus/issues/1248 is also not really about caching. 

Let's close it, we can always open it, thanks!

**Pull request closed without merging**
