### PR TITLE
translation to spanish all md files in root folder

### PR DESCRIPTION
**Pull request by johnfelipe**
translation to spanish all md files in root folder

Signed-off-by: Mgtr Felipe Urrego <ingenierofelipeurrego@gmail.com>

### CODE REVIEW

**Comment by a-gavin** [comment]
@johnfelipe CI fails because you forgot to sign the DCO. See the bottom of [this section](https://github.com/prometheus/prometheus/blob/main/CONTRIBUTING.md#contributing) of the contributing instructions

**Comment by a-gavin** [comment]
[This guide](https://github.com/dcoapp/app#how-it-works) shows the steps for how to add the DCO.

Since you only have one commit and it is on your own fork of the repo, you could amend your previous commit and then force push to your main branch like follows (generally not good practice):
```
git commit --amend
git push -f origin/main
```

The main thing would be to add a line like below (with your name and email instead) to the commit message body, as shown in the linked DCO guide:
`Signed-off-by: Random J Developer <random@developer.example.org>`

This would update the PR (showing the force push but 🤷) and pass the failing DCO check.

**Comment by johnfelipe** [comment]
im using github desktop windows

SNAG-1331

how can do it with that?

**Comment by a-gavin** [comment]
I'm unfamiliar with Git Desktop, but if you click on the failing DCO check there's (better) instructions on how to update add the DCO to previous commits. If you want your changes merged, though, you should probably drop everything but the initial commit with the translation changes as I'm sure the maintainers would like a relatively clean git history.

image
(Assuming you have Git Bash installed) To do so, open the repo in explorer, right click on white space in the folder, and run Git Bash in the folder. Then run the commands listed in the DCO check to amend the commits.

To drop the previous commits, see [this](https://stackoverflow.com/questions/50234180/git-remove-old-commits) StackOverflow post. You will also want to run these commands in the repository with Git Bash.

**Comment by johnfelipe** [comment]
Can u guide me for exact steps missing

**Pull request closed without merging**
