### PR TITLE
Go install fixes

### PR DESCRIPTION
**Pull request by douglascamata**
Trying to make Prometheus and `promtool` compatible with `go install` by removing `replace` and `exclude` directives from the Go module file.

Dependencies were upgraded.

I could go-install `promtool`with `go install -a github.com/douglascamata/prometheus/cmd/promtool@a6ae4eb5ba402ab0714efc92be51d72e5c351e2b`. That commit ref from my fork has the module name modified to match the fork's URL.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks! However, this is not sufficient. We need it to be replaced into dependencies, not only in the binary.

**Comment by just1900** [comment]
It seems this pr will fix the `go install` issue. What else is needed to merge this?

**Comment by douglascamata** [comment]
@just1900 although it fixes the `go install` issue, Prometheus seems to **need** those replaces for their logging system. Sadly getting rid of a replace like this is very difficult. Hopefully Go will fix this and allow projects with replaces to be go-installable.

**Comment by douglascamata** [comment]
I know about this closed issue where many people voiced their opinions against the replace directive restriction: https://github.com/golang/go/issues/44840

**Pull request closed without merging**
