### PR TITLE
Update expfmt.NewDecoder usage

### PR DESCRIPTION
**Pull request by fabxc**

### CODE REVIEW

**Comment by juliusv** [comment]
:+1:

**Comment by fabxc** [comment]
After some thinking, I'm considering to let `ResponseFormat` return `FormatUnknown` instead of an error. On that `NewDecoder` can then return an error – less redundant error checking. Thoughts @juliusv ?

**Comment by beorn7** [comment]
Shouldn't we have a fallback format to try in case of an invalid header?
I remember I just fell back to text format at several occasions, and only give up if the content cannot be parsed as text format.
I'm thinking here of ad-hoc exposition using the text format where setting up the right headers might be complicated.

**Comment by fabxc** [comment]
Yes, that would be even one step further, i.e. NewDecoder not returning an error either and defaulting to the text decoder. Also worth considering.

**Comment by juliusv** [comment]
Yeah, when the headers are missing completely, it'd make sense to fall back to the text format. If they are set to something unknown, I'd go for the `FormatUnknown` return. But don't feel strongly about any of these alternatives.

**Comment by fabxc** [comment]
Closing as this is invalidated by prometheus/common#6

**Pull request closed without merging**
