### PR TITLE
Add series match query hint

### PR DESCRIPTION
**Pull request by mtanda**
Implement https://github.com/prometheus/prometheus/issues/4428

### CODE REVIEW

**Comment by mtanda** [comment]
@brian-brazil How do you think this change?

**Comment by brian-brazil** [comment]
This is more @tomwilkie's area.

**Comment by brian-brazil** [comment]
> The inclusion of startMs and endMs is a bit strange, as the query itself has that.

This is to do with whole range vs. range offset needs. This makes sense consistency wise.

**Comment by mtanda** [comment]
> IIUC we've been using the absence of a ReadHints to signify a metadata-only fetch, so I think this is an improvement.

Sorry, I didn't know the detail of remote read.
I can use same method to detect metadata-only fetch if the interface is never changed.

> And the nagging question is whether or not this should be a separate RPC altogether? I'm not a big fan of overloading the interface like this.

I need same functionality for remote read, which Prometheus provide.
`GET /api/v1/label/<label_name>/values` seems to not supported in remote read.
To support the API, current remote read interface can't handle, so need separete RPC.

The remote read interface can't handle all Prometheus API, and `GET /api/v1/series` interface and `GET /api/v1/query_range` is little differ, I think adding RPC is good decision.

**Comment by juliusv** [comment]
I also prefer making each type of query explicit along the entire path (new method on the storage / querier, new remote read endpoint or request message type). The whole read hints business is getting out of hand and is confusing IMO. We should make sure though that we have some kind of consistent vision for remote read should be going, and when we're fine breaking it (since it's strictly still marked experimental, but of course we don't want to break it all the time).

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and decided to close this. There is further discussions needed before we can decide what is the best approach there. See #4057 and #5547  for the discussions.

**Pull request closed without merging**
