### PR TITLE
Remove vendoring

### PR DESCRIPTION
**Pull request by sylr**
Remove vendoring which has became more annoying than useful.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks for the pull request.

As we are in the process of prepping the 2.17 release, I am willing to veto this until the 2.17 branch in created.

**Comment by sylr** [comment]
> As we are in the process of prepping the 2.17 release, I am willing to veto this until the 2.17 branch in created.

Ok 👍

**Comment by roidelapluie** [comment]
I also have further questions regarding licence check that I will raise on the mailing list.

**Comment by simonpasquier** [comment]
Can you elaborate on what is painful with vendoring?

**Comment by roidelapluie** [comment]
https://groups.google.com/forum/#!topic/prometheus-developers/WLQQd_uNRlw

**Comment by sylr** [comment]
> Can you elaborate on what is painful with vendoring?

- it generates big diffs
- Often people send PR without `vendor/` being up to date

**Comment by roidelapluie** [comment]
> > Can you elaborate on what is painful with vendoring?
> 
> * it generates big diffs

How is that painful? git has tooling to exclude that from diff if wanted

> * Often people send PR without `vendor/` being up to date

Please clarify what often means as I don't remember seeing this in the last couple of months

**Comment by gouthamve** [comment]
We looked at this in the bug scrub, and we have also discussed this extensively in our dev summit. The rough consensus is to remove `vendor` but we are going to remove it in `node_exporter` first. @SuperQ and @simonpasquier would be driving this in Prometheus and as it's a simple change, we'll be closing this PR and opening one when we finally decide to remove it. Any PR opened will have a lot of conflicts in the meantime.

We'd like to thank you for all the discussion around vendoring both here and the mailing list! It helped drive a lot of change!

**Pull request closed without merging**
