### PR TITLE
histogram: Fix bounds of buckets returned by floatBucketIterator

### PR DESCRIPTION
**Pull request by beorn7**

### CODE REVIEW

**Comment by beorn7** [comment]
Still needs test.

**Comment by beorn7** [comment]
OK, I have added a test and made the code a bit cleaner and more efficient.

@fatsheep9146 would you like to do the final review.

**Review by fatsheep9146 — APPROVED** [review]
LGTM!

**Comment by beorn7** [comment]
Thanks.

**Pull request merged**
