### PR TITLE
Fix race condition on file SD

### PR DESCRIPTION
**Pull request by simonpasquier**
This is a tentative fix for #3446. I have a hard time reproducing the original bug so I can't say with confidence that it is solving the original issue.

### CODE REVIEW

**Comment by simonpasquier** [comment]
I've modified the patch slightly: instead of moving the defer call after initializing `d.watcher`, the `stop()` method returns early if `d.watcher` is nil. It is easier to understand IMO and less likely to break again.

**Comment by brian-brazil** [comment]
I think the original way with the defer move was better, as it keeps the logic in one function. That's a fairly common pattern in Go.

**Comment by simonpasquier** [comment]
Thx @brian-brazil , I'll amend.

**Comment by simonpasquier** [comment]
@grobie @brian-brazil PTAL

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
