### PR TITLE
simplified default config code

### PR DESCRIPTION
**Pull request by neelance**
Is there some reason why the approach of this PR does not work? I'm not very familiar with the `yaml` package, so I just want to know.

### CODE REVIEW

**Comment by fabxc** [comment]
`unmarshal(c)` calls `c.UnmarshalYAML()` – infinite recursion, we all die.

**Comment by neelance** [comment]
Okay right, I did not immediately see that. Could you please take a look at my second commit? As far as I know this should "hide" the `UnmarshalYAML` method when calling `unmarshal` to avoid the recursion.

**Comment by fabxc** [comment]
No time to test this right now but this should solve the problem with less noise.
I'll take a closer look soonish - seems like a good solution in general, thanks!

**Comment by fabxc** [comment]
Done via #773

**Pull request closed without merging**
