### PR TITLE
Alerts template: remove silence table header

### PR DESCRIPTION
**Pull request by mattbostock**
There's no corresponding table column for this table header. The
placeholder link for silences was removed in e8800730.

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks. Can you run `make assets format` as well and commit the changes?

👍 after that

**Comment by fabxc** [comment]
Seems to need a rebase now.

**Comment by mattbostock** [comment]
@fabxc: I've rebased, but the change to `bindata.go` is quite substantial. Can you please verify that you'd expect so many changes?

**Comment by fabxc** [comment]
Jup, that's fine – the right file changed. The tool just likes to update all timestamps constantly.

**Pull request merged**
