### PR TITLE
mixin: Filter instance by selected job for Prometheus overview dashboard

### PR DESCRIPTION
**Pull request by PhilipGough**
A bug was created downstream which suggested that the Prometheus/Overview dashboard "instance" dropdown was not filtering correctly when a job was selected.

I was able to replicate it locally using the following config:

```yaml
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
scrape_configs:
  - job_name: 'prometheus-k8s-0'
    static_configs:
      - targets:
        - 'localhost:9090'
        labels:
          pod: prometheus-k8s-00
          service: prometheus-k8s
      - targets:
        - 'localhost:9091'
        labels:
          pod: prometheus-k8s-01
          service: prometheus-k8s
  - job_name: 'prometheus-k8s-1'
    static_configs:
      - targets:
        - 'localhost:9090'
        labels:
          pod: prometheus-k8s-10
          service: prometheus-k8s
      - targets:
        - 'localhost:9091'
        labels:
          pod: prometheus-k8s-11
          service: prometheus-k8s
```

Heres a before and after from this change:

before

after

### CODE REVIEW

**Review by arajkumar — APPROVED** [review]
lgtm

**Comment by paulfantom** [comment]
lgtm

@beorn7 could you take a look at this? thanks!

**Comment by beorn7** [comment]
Just back from vacation. Will have a look ASAP.

**Review by beorn7 — APPROVED** [review]

**Comment by beorn7** [comment]
Thank you, looks good.

**Pull request merged**
