### PR TITLE
Kubernetes SD: Add node name and host IP to pod discovery

### LINKED ISSUE #1604: Add node name in Kubernetes discovery
Similar to #1562 , if we can have the name of the node where is scheduled the pod as tag, it would be awesome for case like DaemonSet of node-exporter for instance.

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #1604 

/cc @pdbogen @fabxc

### CODE REVIEW

**Comment by fabxc** [comment]
This won't collide with any potential plans for pod live-migration or anything?

**Comment by jimmidyson** [comment]
Not that I can think of. Can you?

**Comment by fabxc** [comment]
I'm not involved enough to know whether there are such plans. But if live migration will become a thing the node label would change and no longer be static for the target.

**Comment by brian-brazil** [comment]
This is not the only thing that could potentially be dynamic among our SD mechanisms. As long as it being static is plausible then that's fine.

**Comment by jimmidyson** [comment]
All I can find with a quick search on pod migration is a really old issue (kubernetes/kubernetes#3949) that has had no progress. There are various other issues but in similar state & lining back to that issue.

**Comment by jimmidyson** [comment]
For now I expect it can be considered static.

**Comment by fabxc** [comment]
Okay, thanks 👍

**Pull request merged**
