### PR TITLE
discovery: use consul service address if available

### PR DESCRIPTION
**Pull request by nicholascapo**
Consul supports service registrations where the service runs on a different host from the registration [0].
When this happens ServiceAddress is a non-empty string.

If ServiceAddress is non-empty it should be used instead of NodeAddress.

Example "normal" registration (From: `http://localhost:8500/v1/health/service/api-foo`):

```json
{
    "Node": {
      "Node": "foo",
      "Address": "192.168.56.1",
      "CreateIndex": 3,
      "ModifyIndex": 442
    },
    "Service": {
      "ID": "foo",
      "Service": "api-foo",
      "Tags": null,
      "Address": "", <========== ServiceAddress is empty, use NodeAddress:ServicePort
      "Port": 1000,
      "EnableTagOverride": false,
      "CreateIndex": 442,
      "ModifyIndex": 442
    }
  }
```

Example "remote" registration:
```json
{
    "Node": {
      "Node": "foo",
      "Address": "192.168.56.1",
      "CreateIndex": 3,
      "ModifyIndex": 442
    },
    "Service": {
      "ID": "foo",
      "Service": "api-foo",
      "Tags": null,
      "Address": "10.0.0.1", <========== ServiceAddress is empty, use ServiceAddress:ServicePort
      "Port": 1000,
      "EnableTagOverride": false,
      "CreateIndex": 442,
      "ModifyIndex": 442
    }
  }
```

[0] https://www.consul.io/docs/agent/services.html

### CODE REVIEW

**Comment by nicholascapo** [comment]
@fabxc :)

**Comment by brian-brazil** [comment]
We've had several changes to this logic in the past, each of which broke some subset of users.

Do you know if this change makes sense in all possible deployments?

**Comment by nicholascapo** [comment]
As far as I am aware yes, the Service can be found at ServiceAddress:ServicePort, but ServiceAddress  can be empty in which case NodeAddress can be used instead.

From [0] regarding registrations:
> The address field can be used to specify a service-specific IP address. By default, the IP address of the agent is used, and this does not need to be provided [in the registration].

As and example `consul-template` uses ServiceAddress in the environment where `prometheus` uses NodeAddress.

I'm looking for  the code in `consul-template` but I haven't found it yet.

[0] https://www.consul.io/docs/agent/services.html

**Comment by nicholascapo** [comment]
Found it!

`consul-template` fixes the same issue here:
  https://github.com/hashicorp/consul-template/issues/185
  https://github.com/hashicorp/consul-template/pull/186

The code in `master` is here:
  https://github.com/hashicorp/consul-template/blob/master/dependency/health_service.go#L129

I can rewrite this PR to look like theirs if you prefer. This was just a smaller change.

**Comment by nicholascapo** [comment]
Refactored to be cleaner and closer to what consul-template is doing

**Comment by nicholascapo** [comment]
Any word on this? The CircleCI build failure seems to be unrelated to my change.

**Comment by fabxc** [comment]
Thanks for pinging again, lost track of this one.
This generally looks okay 👍 

Let's hope no one relied on the old behavior :)

**Pull request merged**
