### PR TITLE
vendor: update golang client

### PR DESCRIPTION
**Pull request by si74**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why are you updating only some of the client?

**Comment by gouthamve** [comment]
I think it was a `govendor add github.com/prometheus/client_golang`. The top level has only md files and I don't think it's needed.

**Comment by si74** [comment]
yep! that's correct. I did a govendor fetch github.com/prometheus/client_golang

**Comment by brian-brazil** [comment]
Okay, nothing to do here then.

**Pull request closed without merging**
