### PR TITLE
Pass version to docker build

### PR DESCRIPTION
**Pull request by AssafKatz3**

### CODE REVIEW

**Comment by AssafKatz3** [comment]
Hi,
I have no idea why these issues failed, non of them are related to my change...
Thanks

**Comment by roidelapluie** [comment]
Hello, what are you trying to achieve?

IIRC the docker build command is only used to pass the binaries compiled with promu, which should have the correct version.

**Comment by AssafKatz3** [comment]
@roidelapluie I want to achieve certification by RedHat, they require version label in docker file. I know that promu set the correct version but it is accessible from outside so if you download it to air gap by 'docker save'/'docker load', this information is hard to find (this is why RedHat requires it in first place).

**Comment by roidelapluie** [comment]
Is there any documentation of the requirements we would need?

**Comment by AssafKatz3** [comment]
@robbiet480 I hope that you have access to [Technical Prerequisites](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/program-on-boarding/technical-prerequisites)

**Comment by AssafKatz3** [comment]
@robbiet480 PDF of above location [Technical Prerequisites.pdf](https://github.com/prometheus/prometheus/files/5939277/Technical.Prerequisites.pdf). The only additional problematic is release

**Comment by roidelapluie** [comment]
Quoting:

> The Base image must be (or must be based on) a supported Red Hat image, such as Red Hat Enterprise Linux or Red Hat Universal Base Image. Any third party or community supported images such as Ubuntu, Debian, Alpine, CentOS etc are not supported by Red Hat and cannot be certified.

So adding the release won't cut it.

Also:

> The following labels must exist: name, maintainer, vendor, version, release, summary & description.

I don't think we add labels

Then:

> You need to include any relevant licenses within the licenses/directory


We do not do that either.

I would recommend that you look at images provided by red hat, as all of this would be too vendor specific, and if tomorrow Suse or Ubuntu comes with their own conflicting specifications, we could not meet all of them. Additionally, we aim at starting with a really small base image, probably distroless, which would end up also not being supported by red hat.

**Comment by robbiet480** [comment]
Why are you tagging me @AssafKatz3

**Comment by roidelapluie** [comment]
> Why are you tagging me @AssafKatz3

I guess your nickname starts with `ro` like mine ;)

**Comment by AssafKatz3** [comment]
@roidelapluie I can solve the other problems for push gateway (other repositories are already supplied by RedHat or other partners) without impact this repository:
```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3
ARG VERSION
LABEL maintainer="The Prometheus Authors <prometheus-developers@googlegroups.com>"
LABEL name="Prometheus Pushgateway"
LABEL vendor="The Prometheus Authors"
LABEL version=$VERSION
LABEL release="N/A"
LABEL summary="Push acceptor for ephemeral and batch jobs"
LABEL description="The Prometheus Pushgateway exists to allow ephemeral and batch jobs to expose their metrics to Prometheus. Since these kinds of jobs may not exist long enough to be scraped, they can instead push their metrics to a Pushgateway. The Pushgateway then exposes these metrics to Prometheus."

ARG ARCH="amd64"
ARG OS="linux"
COPY --chown=nobody:root .build/${OS}-${ARCH}/pushgateway /bin/pushgateway

EXPOSE 9091
RUN mkdir -p /pushgateway && chown nobody:root /pushgateway
COPY --chown=nobody:root LICENSE /licenses/
WORKDIR /pushgateway

ENTRYPOINT [ "/bin/pushgateway" ]
```
My problem is therefore very focused - I need to supply VERSION build argument.

**Comment by beorn7** [comment]
Message from the bug scrub: @roidelapluie and I are confused about the requested feature here. @bwplotka perhaps you are familiar enough with both Prometheus Dockerfiles and the RH-certified images? Or @discordianfish , you are my usual reference point for Docker questions…

**Comment by discordianfish** [comment]
No idea what this is about..
@AssafKatz3 Maybe you can just create your own Dockerfile with FROM prom/prometheus ... and add whatever labels are needed there?

**Comment by AssafKatz3** [comment]
@discordianfish I will add the labels to Dockerfile so it will be more clear why we need to pass the value of version label

**Comment by discordianfish** [comment]
@AssafKatz3 Yeah I don't think there is any standard for this kind of metadata which we could just adopt here. If there are more people in need for this, I would reconsider. But either way, it would probably make sense to ask on the mailinglist of other people are interested in that and discuss how we'd do that in a consistent way across all our repos.

**Comment by AssafKatz3** [comment]
> @AssafKatz3 Yeah I don't think there is any standard for this kind of metadata which we could just adopt here. If there are more people in need for this, I would reconsider. But either way, it would probably make sense to ask on the mailinglist of other people are interested in that and discuss how we'd do that in a consistent way across all our repos.

@discordianfish There is no standard, but version is common as you can see [in documentation](https://docs.docker.com/engine/reference/builder/#label). I opened [thread in mailing list](https://groups.google.com/g/prometheus-developers/c/kpLh345giTE/m/NgHsIEtOAQAJ) but got no answers.

**Comment by beorn7** [comment]
The lack of response probably means that people rarely run into this kind of issue.

Personally, I don't feel strongly about those labels. So if nothing speaks against it, why not add them?

But I would mostly trust @discordianfish 's judgement here.

**Comment by roidelapluie** [comment]
> The lack of response probably means that people rarely run into this kind of issue.
> 
> Personally, I don't feel strongly about those labels. So if nothing speaks against it, why not add them?

For consistency. I don't think we have anyone willing to maintain this over all the projects we have? Can we automate that?

> 
> But I would mostly trust @discordianfish 's judgement here.

Note that the pull request as is has issues, e.g. it is doing chown /licenses but we don't have it.

**Comment by AssafKatz3** [comment]
@roidelapluie I added copy the to /licences in order to fix the chown issue. The other issues aren't related to this change at all.

**Comment by roidelapluie** [comment]
That still does not make the image red-hat certified so I don't really see the point here :(

**Comment by AssafKatz3** [comment]
@roidelapluie The point here that I want to make push gateway RedHat certified, this requires changing Makefile.common here. Otherwise, this file will be overridden in [push gatway](https://github.com/prometheus/pushgateway) from this repository (or more probably, my pull request to there will be rejected). If know better way, it will be very welcome :-)

**Comment by roidelapluie** [comment]
Since we do not base ourselves on a red hat ceritifed base image, it will not be certified. If it is only the pushgateway, how did you make a prometheus/etc certified image?

**Comment by discordianfish** [comment]
All up for red hat certified images but that's something that should happen externally of the prometheus org and probably be done by redhat. So I'd close this issue.

**Comment by roidelapluie** [comment]
We have looked at this during our bug scrub and decided to follow @discordianfish 's opinion. If there is a clear standard that would bring benefits we would follow it, but in this case, we don't see the added value.

Thanks for your contribution.

**Pull request closed without merging**
