### PR TITLE
Expose a metric with the current value of sample_limit per scrape pool

### PR DESCRIPTION
**Pull request by prymitive**
For target limit there is a metric prometheus_target_scrape_pool_target_limit that can be used to check how close given pool is to the limit. There is no such metric for sample limit, which makes it hard to query for scrape pools close to configured sample limit.
Add prometheus_target_scrape_pool_sample_limit exposing the value of sample_limit scrape config option.

Signed-off-by: Łukasz Mierzwa <l.mierzwa@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. This is making the incorrect assumptions that Prometheus is scraping itself, and that the name of the scrape config matches the job label of the target. Put another way, you can't mix ingested per-target metrics with per-Prometheus metrics like this usefully.

To be useful this would have to be ingested with the scrape, however that's an additional overhead for every single target for all users of Prometheus which is too high a cost for the benefits this would bring.

**Comment by prymitive** [comment]
Both `sample_limit` and `target_limit` scrape config options are set globally for the entire scrape job. If it's valid to expose `target_limit` as a metric then why isn't it valid to do the same for `sample_limit`?

Seems like you're saying I wouldn't be able to use this metric in any practical way, which is probably related to the fact that `prometheus_target_scrape_pool_sample_limit ` metric would have `scrape_job` label, while `scrape_samples_post_metric_relabeling` that I could use to query for the number of samples scraped from each target will have `job` label. The mismatch makes it harder but it feels justified - sample_limit metric describes the scrape config configuration while scrape_samples describes results from specific target of that scrape config, so these are on 2 different level of detail, hence the mismatch. But simple `label_replace` function would allow me to use these two metrics in a single query.

I do get the argument that it's not a straightforward for my intended use,  but I do believe it's still a useful metric (what if you just want to expose it on a dashboard?).

**Comment by brian-brazil** [comment]
> Both sample_limit and target_limit scrape config options are set globally for the entire scrape job. If it's valid to expose target_limit as a metric then why isn't it valid to do the same for sample_limit?

Target_limit applies to the scrape config as a whole, sample_limit applies individually to each target within the scrape config. There are no per-target metrics on the /metrics of Prometheus.

> Seems like you're saying I wouldn't be able to use this metric in any practical way

Yes, it's not generally usable.

> But simple label_replace function would allow me to use these two metrics in a single query.

Not in general, there's no restrictions in relation to what the job label can be.

> I do get the argument that it's not a straightforward for my intended use, but I do believe it's still a useful metric (what if you just want to expose it on a dashboard?).

I don't see how that's of much use on a dashboard, and that is a very weak justification as it could be applied to anything. It's a hardcoded constant coming from your config file which doesn't relate to any other value on the /metrics.

This metric doesn't make sense to add, and would likely cause more confusion than anything else due to the above issues.

**Comment by prymitive** [comment]
Fair enough

**Comment by brian-brazil** [comment]
> Is there some other way to query (for example) all targets that are >= 80% of sample_limit?

Sample limit is meant to be a coarse emergency relief valve, so will tend to have a very small number of potential values in a given setup. So hardcoding it in your alerting rule is typically fine.

> Is there an alternative change I could work on?

Per the above, I don't see any reasonable way to expose this.

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub, and per the above there's no reasonable way to do this.

**Pull request closed without merging**
