### PR TITLE
web/api: Remove legacy REST API

### PR DESCRIPTION
**Pull request by fabxc**
Grafana and PromDash are now both using the HTTP APIv1. The only
remaining (public) component is prometheus/prometheus_cli, which should
be deprecated anyway.

@brian-brazil @juliusv

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
:fire: :+1: RIP

**Comment by beorn7** [comment]
Deprecating the Prometheus CLI will break the Nagios plugin.
Not sure how many are using it.
(We are trying to get rid of it at Soundcloud as I'm writing this, but still ~150 checks left to go...)

**Comment by beorn7** [comment]
I see a few mentions of the Prometheus Nagios plugin on the internet... I guess it would be good if we could keep it working somehow.

**Comment by fabxc** [comment]
Fair point...

**Comment by beorn7** [comment]
Implement the nagios plugin in Go? ;)

It's anyway a wart that the plugin has an implicit dependency on the prometheus_cli... not sure how much effort a rewrite would be.

Integration with Nagios, even if brittle, seems like a good selling point along the lines of gradual transition. So just dropping support might not be a good idea (especially while we still have issues with Alertmanager).

**Comment by fabxc** [comment]
We can always switch it to `promtool` once that has a query functionality.
If anyone wants to port the plugin to Go that's cool as well.

**Comment by beorn7** [comment]
I wasn't even sure that promtool is supposed to support querying, too. (There's no feature-request issue for that, is there?)

If that's the case, I guess the roadmap is pretty clear:
1. Add querying support to promtool (at least the functionality the prometheus_cli has).
2. Move the Nagios plugin to promtool.
3. Remove prometheus_cli.
4. Merge this PR.

**Comment by beorn7** [comment]
Filed https://github.com/prometheus/prometheus/issues/1605 and updated related issues in other repos.

**Pull request closed without merging**
