### PR TITLE
fix: fix slice init length

### PR DESCRIPTION
**Pull request by huochexizhan**
It seems better to initialize it this way. This is an online demo, please take a look

https://go.dev/play/p/nF5ABpPdOo9

```go
// You can edit this code!
// Click here and start typing.
package main

import "fmt"

func main() {
	sli := make([]int, 1)

	fmt.Println(sli)

	sli = sli[:0]

	fmt.Println(sli)

}
```

### CODE REVIEW

**Review by Tusenka — APPROVED** [review]

**Comment by huochexizhan** [comment]
Thanks!

If there's anything I need to do, please feel free to let me know

**Comment by beorn7** [comment]
I think this is a tad cleaner indeed. (We reset the slice anyway later, so it doesn't really matter in practice, but the len=0, cap=1 initialization better convoys the intent.)

@zenador you touched this line last, do you agree?

**Comment by beorn7** [comment]
@huochexizhan in the meantime, could you fix the DCO as described [here](https://github.com/prometheus/prometheus/pull/15026/checks?check_run_id=30920343612)?

**Comment by huochexizhan** [comment]
> @huochexizhan in the meantime, could you fix the DCO as described [here](https://github.com/prometheus/prometheus/pull/15026/checks?check_run_id=30920343612)?

Of course.  Modified

**Review by beorn7 — APPROVED** [review]
With no objections received from @zenador so far, I'll merge this.

**Pull request merged**
