### PR TITLE
retrieval: add missing scrape context cancelation

### PR DESCRIPTION
**Pull request by fabxc**
Same fix as in #2599

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
:+1:

**Comment by grobie** [comment]
Why is it necessary to cancel a context after the scrape has already returned? Does this prevent a leak?

**Comment by fabxc** [comment]
Yes, it must _always_ be canceled. Ultimately, you don't know how much further down a context was passed and whether anything on the way launched a go routine, which listens on `<-ctx.Done()` for termination.

**Comment by juliusv** [comment]
In this particular case, WithTimeout starts a timer goroutine which
continues running until timed out or cancelled.

**Comment by grobie** [comment]
That makes sense actually. Thanks!

**Pull request merged**
