### PR TITLE
Release 2.43.0+stringlabels

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
LGTM, tested against `2.43.0-stringlabels` Docker tag.

**Comment by juliusv** [comment]
:+1: with same nits as in https://github.com/prometheus/prometheus/pull/12162

**Comment by Nexucis** [comment]
Just in case: one of these PR will fail to release the UI component since it's the same version. Don't know if it really matters

**Comment by roidelapluie** [comment]
> Just in case: one of these PR will fail to release the UI component since it's the same version. Don't know if it really matters

this branch does not have the release UI github action

**Pull request merged**
