### PR TITLE
Add logger injection into discovery services

### PR DESCRIPTION
**Pull request by goller**
Hey there, in this PR I updated the discovery services to take a prometheus logging interface to allow logger injection.  Previously, the discovery services except k8s and triton were using the base logger. 

I did this because I'm interested in using the discovery package as a library and use my own logger rather than the base logger.

### CODE REVIEW

**Comment by fabxc** [comment]
Sorry about not taking a look at this earlier. There still seem to be conflicts, but LGTM in general.

**Comment by brancz** [comment]
Oh I completely missed this as well. I was actually looking into doing this some time soon as well. Awesome work!

**Comment by goller** [comment]
@fabxc right on, sorry about that.  Trying to fix 'em now

**Comment by goller** [comment]
@fabxc conflicts resolved!

**Comment by fabxc** [comment]
Thank you! One step closer of getting rid of globals :)

**Pull request merged**
