### PR TITLE
1.7 easyjson

### PR DESCRIPTION
**Pull request by jacksontj**
This is a fix for #3601, this wouldn't be the *actual* PR (as we'll need to commit the changes in https://github.com/prometheus/common/pull/112 first) but this gives an idea of the level of change required (very small).

I've run this locally with some test data, and here are the comparisons:

|        | pre-patch | with-patch |
|--------|-----------|------------|
| Matrix | 214ms     | 37ms       |
| Vector | 108ms     | 20ms       |
| Scalar | 20ms      | 11ms       |
| String | 18ms      | 13ms       |

With this we can see the large performance gains even with small returns. Not only do we get these gains (~5-6 for "real" data) we also significantly reduce the memory required to marshal out the response (which means this scales *significantly* better into large response sizes.

Also, as a bonus, since this iteratively serializes it will also *stop* mid-serialization if the client disconnects!

### CODE REVIEW

**Comment by jacksontj** [comment]
CI CI failure seems unrelated (due to unmounting FS?)

**Comment by jacksontj** [comment]
To include a complete end-to-end benchmark I've done a simple promql query (`metricname[range]`) over various time durations pre and post easyjson change, here are the results:

| Time (minutes) | Old    | New   | Improvement  |
|----------------|--------|-------|--------------|
| 0              | 0.121  | 0.086 | -28.92561983 |
| 1              | 0.171  | 0.076 | -55.55555556 |
| 10             | 1.226  | 0.119 | -90.29363785 |
| 30             | 2.126  | 0.58  | -72.7187206  |
| 60             | 5.173  | 0.441 | -91.47496617 |
| 120            | 9.086  | 1.107 | -87.81642087 |
| 180            | 13.719 | 1.795 | -86.91595597 |
| 240            | 17.668 | 1.956 | -88.92913742 |

**Comment by brian-brazil** [comment]
This PR is against Prometheus 1.7, which is not the current development version. Any changes of this nature should be proposed against master.

**Comment by jacksontj** [comment]
@brian-brazil I can do that, I opened the PR here as the issue (#3601 ) was reported on 1.7. The changes here can (and should) be applied to any releases that are still supported (I'm not sure which ones those are, so I'll need some guidance on what are the currently supported releases).

**Comment by brian-brazil** [comment]
A change like this would be aimed for 2.1 currently, which is to say master. New features are not being added to 1.x.

**Comment by jacksontj** [comment]
I can re-open the PR against master, but https://github.com/prometheus/common/pull/112 needs to be merged first. Before moving the PR I'd like to see that merged and some feedback on this change (since it will be basicaly the same change against master).

Is there also no mechanism to backport to previous releases? From looking at the releases page it seems that N-1 is supported (minor releases etc.)?

**Comment by brian-brazil** [comment]
All the relevant code changed with 2.0, you'd need to redo it all.

Only bugfixes would be considered for backport.

**Comment by jacksontj** [comment]
What classifies bug fix? From the end to end data this is ~10x perf
improvement.

Also, your latest response still has no feedback for a change like this.

**Comment by brian-brazil** [comment]
A performance improvement is not considered a bugfix.

**Comment by jacksontj** [comment]
Ok, how about feedback on the change?

**Comment by brian-brazil** [comment]
It's a highly invasive change that'd require significant ongoing error-prone maintenance, and it also violates layering. Such downsides require major major benefits to justify, and the benchmark numbers produced thus far are at odds with previous profiling in this area.

**Comment by jacksontj** [comment]
> It's a highly invasive change 

I'm not sure if we're looking at the same diff? The reason this particular PR is so large is due to changes in the vendor directory. The actual change to the code is ~30-40 lines of change, which I'd hardly call "highly invasive".

> that'd require significant ongoing error-prone maintenance

I'm also not sure what maintenance you are expecting to perform? There is one codegen'd file -- which requires no human to write the code and the only other one is a small marshal method on the queryData struct -- which isn't exactly a large struct.

> and it also violates layering.

What are you implying with this? What layering is being broken? In golang marshal methods have to be in the package with the struct definition-- so if you don't want the marshal/unmarshal methods in this package then we need to move it to another package. Past that I have no idea what other layering you could be referring to, so please elaborate.

> Such downsides require major major benefits to justify

I agree, which is why I've spent a significant amount of time collecting a LOT of data (and creating a variety of benchmarks to demonstrate this)

> and the benchmark numbers produced thus far are at odds with previous profiling in this area.

Thats usually how performance improvements work? For all the benchmarks we're talking about the code is all open -- so it is comparable. The benchmarks you are referring to are all done by the jsoniter guys on a generic dataset. The benchmarks I've put in place are (1) with the prometheus structs and (2) a full end-to-end test (which is exactly what you asked for). At this point I'm at a loss for what additional information to provide. I have overwhelming data supporting my position, and all you've been able to counter with is "suspicion" -- with no recourse.

What data or proof do you require to get such a change in? I'm growing weary of gathering data only to be met with 'suspicion' and uncertainty. This is a simple performance optimization (a HUGE one, but a simple one nonetheless). If not performance data, what data do you need?

**Comment by brian-brazil** [comment]
Obsoleted by #3536

**Pull request closed without merging**
