### PR TITLE
clarify that 1.0 will eventually be deprecated, it is not yet deprecated

### PR DESCRIPTION
**Pull request by cstyan**
Addressing comments from @bboreham on https://github.com/prometheus/prometheus/pull/14395 re: status of RW1.0

### CODE REVIEW

**Review by bboreham — APPROVED** [review]
Thanks!

**Comment by bboreham** [comment]
Should we do this on release-2.54 branch?

**Comment by cstyan** [comment]
> Should we do this on release-2.54 branch?

which is easier for you, PRing this into the release branch or into main? I can't remember if we have automation for backporting at all

**Comment by bboreham** [comment]
I'm not aware of any automation; if you change the base to release-2.54 it will get merged back with everything else when the release is done.
Or you can open a second PR to cherry-pick this to that branch.

**Comment by cstyan** [comment]
@bboreham changed base to 2.54 :+1: seems like the easiest option for now

**Review by bboreham — APPROVED** [review]

**Pull request merged**
