### PR TITLE
Enable the new UI Help link

### PR DESCRIPTION
**Pull request by SuperQ**
Re-enable the Help link in the manteine-ui.

### CODE REVIEW

**Comment by juliusv** [comment]
The tests are failing because you'll need to import `IconHelp` from the tabler icons. But also I had commented out because I was trying to not clutter the new UI too much again and was wondering how much we *really* need that link? The best UI element is no UI element, unless we think it's critical.

**Comment by SuperQ** [comment]
I think have a link to the official docs is very helpful. I wonder if we can get metrics from the web logs on how many people click the link. :thinking:

**Comment by SuperQ** [comment]
Fixed `IconHelp` import.

**Comment by juliusv** [comment]
Hehe, this is how it always begins, and in the end after a thousand cuts, we have something like the old UI 😛

But ok, fair. I think the `IconBook` icon would look a bit nicer and less info-generic though.
image

I may potentially later play with just making it an icon (instead of icon + text main menu item) next to the settings though.

**Comment by juliusv** [comment]
Ok so how about this instead of making it a full main menu link that looks like a page on the Prometheus server?

image

Happy to send a PR.

**Comment by juliusv** [comment]
PR for that at https://github.com/prometheus/prometheus/pull/14882

**Comment by juliusv** [comment]
I've merged https://github.com/prometheus/prometheus/pull/14882 as an (IMO) less intrusive alternative. Let me know if you feel strongly though, and we can explore some other options.

**Pull request closed without merging**
