### PR TITLE
Upgrade to github.com/Azure/azure-sdk-for-go/sdk

### LINKED ISSUE #10942: Move away from deprecated Azure packages.
Azure packages have depreciation notices:

**github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute**
> Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more details.

**github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-10-01/network**
> Please note, this package has been deprecated. A replacement package is available [github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/network/armnetwork). We strongly encourage you to upgrade to continue receiving updates. See [Migration Guide](https://aka.ms/azsdk/golang/t2/migration) for guidance on upgrading. Refer to our [deprecation policy](https://azure.github.io/azure-sdk/policies_support.html) for more detail

### PR DESCRIPTION
**Pull request by mmorel-35**
I had troubles with my commits signature so I recreated this branch with everything merged.
Replaces #11849
Fixes #10942

xref: https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by kakkoyun** [comment]
I'm having a look at this in preparation for the next release.

https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md

**Review by kakkoyun — APPROVED** [review]
AFAIT, this looks good to me.

I'm not an expert on Azure expert, nor I've ever used it. However, according to the document that I've linked above. Everything looks fine.

**Comment by bwplotka** [comment]
Did anyone had a chance to test it @mmorel-35? There are no automated tests against Azure, so it would nice to at least run it. Have you been able to check it @mmorel-35 maybe? 🤗

**Review by bwplotka — APPROVED** [review]
Double checked with https://github.com/Azure/go-autorest/blob/main/autorest/azure/environments.go#L34 - all looks solid. Thanks!

Have you tested it?

**Comment by mmorel-35** [comment]
Hi @bwplotka ! I don't have any azure account so I don't have any way to check it with an integration test.
Does the Prometheus project have some kind of way to do integration testing on this ?

**Comment by bwplotka** [comment]
No, we rely for contributors for some pieces like this.

**Comment by bwplotka** [comment]
No, we rely for contributors for some pieces like this, sorry!

I will announce on -developer list and Twitter, that we need someone to test this PR. Do you mind resolving go.mod?

**Comment by bwplotka** [comment]
Double checking: https://cloud-native.slack.com/archives/C01AUBA4PFE/p1674724948201319

**Comment by mmorel-35** [comment]
Hi @LeviHarrison , 
If you could find the time to test and review this PR, that would be awesome :) !

**Comment by kakkoyun** [comment]
This needs a rebase.

Have we found a way to test this?

**Comment by mmorel-35** [comment]
> Have we found a way to test this?

Not to my knowledge

**Comment by jkroepke** [comment]
Hi all, I have a VS Code Enterprise licence which includes a personal MPN subscription. (with an budget of 130€)

I'm interest into testing this PR. Are there integration tests to run? Are they instructions which tests should be done manually? I'm also on the CNCF slack.

**Comment by bboreham** [comment]
To clarify, there is no specific set of tests that we need done; we just need someone to say "I use Azure; I tried this out and it worked for me".

**Review by LeviHarrison — APPROVED** [review]
Tested and looks good 👍🏻 

image

**Comment by LeviHarrison** [comment]
Just need a rebase here and I think we'll be good to go

**Comment by mmorel-35** [comment]
Hi @LeviHarrison ,
Rebase is done here

**Comment by LeviHarrison** [comment]
Thanks for fixing that so fast! This is really helpful for the new release.

**Pull request merged**
