### PR TITLE
Assign new code owners for prometheus-mixin

### PR DESCRIPTION
**Pull request by metalmatze**
As discussed I'm happy to take on the mixins as codeowner and delegate to various people who might be able to help too.

### CODE REVIEW

**Comment by metalmatze** [comment]
FYI @beorn7 and @ArthurSens

**Comment by metalmatze** [comment]
Please let me know if there were more repositories we should move you off of owning the mixin code, @beorn7.

**Review by beorn7 — CHANGES_REQUESTED** [review]
Thank you very much.

I'm also listed in https://github.com/prometheus/prometheus/blob/main/MAINTAINERS.md , which should be changed to @metalmatze , too.

(And I think that would be all.)

**Comment by metalmatze** [comment]
Updated. :relieved:

**Review by beorn7 — APPROVED** [review]

**Pull request merged**
