### PR TITLE
specify npm version in the engine

### PR DESCRIPTION
**Pull request by Nexucis**
Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@Nexucis So weird, now Netlify fails with a bunch of linter errors:

```
10:40:31 AM: src/pages/alerts/Alerts.tsx
10:40:31 AM:   Line 12:64:  Replace ``https://prometheus.demo.do.prometheus.io/${API_PATH}/rules?type=alert`` with `⏎····`https://prometheus.demo.do.prometheus.io/${API_PATH}/rules?type=alert`⏎··`  prettier/prettier
10:40:31 AM: src/pages/flags/Flags.tsx
10:40:31 AM:   Line 127:60:  Replace ``https://prometheus.demo.do.prometheus.io/${API_PATH}/status/flags`` with `⏎····`https://prometheus.demo.do.prometheus.io/${API_PATH}/status/flags`⏎··`  prettier/prettier
10:40:31 AM: src/pages/graph/PanelList.tsx
10:40:31 AM:   Line 134:74:  Replace ``https://prometheus.demo.do.prometheus.io/${API_PATH}/label/__name__/values`` with `⏎····`https://prometheus.demo.do.prometheus.io/${API_PATH}/label/__name__/values`⏎··`  prettier/prettier
10:40:31 AM: src/pages/serviceDiscovery/Services.tsx
10:40:31 AM:   Line 113:63:  Replace ``https://prometheus.demo.do.prometheus.io/${API_PATH}/targets`` with `⏎····`https://prometheus.demo.do.prometheus.io/${API_PATH}/targets`⏎··`  prettier/prettier
10:40:31 AM: src/pages/targets/ScrapePoolList.tsx
10:40:31 AM:   Line 60:72:  Replace ``https://prometheus.demo.do.prometheus.io/${API_PATH}/targets?state=active`` with `⏎····`https://prometheus.demo.do.prometheus.io/${API_PATH}/targets?state=active`⏎··`  prettier/prettier
10:40:31 AM: src/pages/tsdbStatus/TSDBStatus.tsx
10:40:31 AM:   Line 117:60:  Replace ``https://prometheus.demo.do.prometheus.io/${API_PATH}/status/tsdb`` with `⏎····`https://prometheus.demo.do.prometheus.io/${API_PATH}/status/tsdb`⏎··`  prettier/prettier
```

But I guess `CI= npm run build` still works locally for you?

**Comment by Nexucis** [comment]
heeeeuuu weirdly no it doesn't work oO: 

```bash
$ CI= npm run build

> build
> bash build_ui.sh --all

build module/codemirror-promql

> codemirror-promql@0.18.0 build
> npm run build:grammar && npm run build:lib


> codemirror-promql@0.18.0 build:grammar
> lezer-generator src/grammar/promql.grammar -o src/grammar/parser

Wrote src/grammar/parser.js and src/grammar/parser.terms.js

> codemirror-promql@0.18.0 build:lib
> bash ./build.sh

+ tsc --module ES2015 --target ES2015 --outDir dist/esm
+ tsc --module commonjs --target es5 --outDir dist/cjs --downlevelIteration
build react-app

> graph@0.1.0 build
> react-scripts build


There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "^26.6.0"
```

**Comment by juliusv** [comment]
Oh wow, a Netlify failure which was actually a real one! :partying_face:

**Comment by Nexucis** [comment]
mmm actually forget what I said. It was because I had a node_module folder in the react-app (coming from the old way). I restarted with a total fresh repo and it works with no issue :( 

```bash
$ CI= npm run build

> build
> bash build_ui.sh --all

build module/codemirror-promql

> codemirror-promql@0.18.0 build
> npm run build:grammar && npm run build:lib


> codemirror-promql@0.18.0 build:grammar
> lezer-generator src/grammar/promql.grammar -o src/grammar/parser

Wrote src/grammar/parser.js and src/grammar/parser.terms.js

> codemirror-promql@0.18.0 build:lib
> bash ./build.sh

+ tsc --module ES2015 --target ES2015 --outDir dist/esm
+ tsc --module commonjs --target es5 --outDir dist/cjs --downlevelIteration
build react-app

> graph@0.1.0 build
> react-scripts build

Creating an optimized production build...
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 302:31  @import
    src\themes\_bootstrap_light.scss 10:9                  @import
    src\themes\light.scss 1:9                              root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 302:31  @import
    src\themes\_bootstrap_dark.scss 9:9                    @import
    src\themes\dark.scss 1:9                               root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
498 │ $input-height-inner-quarter:            add($input-line-height * .25em, $input-padding-y / 2) !default;
    │                                                                         ^^^^^^^^^^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 498:73  @import
    src\themes\_bootstrap_light.scss 10:9                  @import
    src\themes\light.scss 1:9                              root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
498 │ $input-height-inner-quarter:            add($input-line-height * .25em, $input-padding-y / 2) !default;
    │                                                                         ^^^^^^^^^^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 498:73  @import
    src\themes\_bootstrap_dark.scss 9:9                    @import
    src\themes\dark.scss 1:9                               root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
568 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 568:49  @import
    src\themes\_bootstrap_light.scss 10:9                  @import
    src\themes\light.scss 1:9                              root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
568 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 568:49  @import
    src\themes\_bootstrap_dark.scss 9:9                    @import
    src\themes\dark.scss 1:9                               root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
713 │ $nav-divider-margin-y:              $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 713:37  @import
    src\themes\_bootstrap_light.scss 10:9                  @import
    src\themes\light.scss 1:9                              root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
713 │ $nav-divider-margin-y:              $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 713:37  @import
    src\themes\_bootstrap_dark.scss 9:9                    @import
    src\themes\dark.scss 1:9                               root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
718 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 718:37  @import
    src\themes\_bootstrap_light.scss 10:9                  @import
    src\themes\light.scss 1:9                              root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
718 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    ..\node_modules\bootstrap\scss\_variables.scss 718:37  @import
    src\themes\_bootstrap_dark.scss 9:9                    @import
    src\themes\dark.scss 1:9                               root stylesheet

WARNING: 64 repetitive deprecation warnings omitted.

WARNING: 66 repetitive deprecation warnings omitted.

Compiled successfully.

File sizes after gzip:

  372.49 KB  build\static\js\2.dc16daa4.chunk.js
  65.84 KB   build\static\js\main.1a4c410f.chunk.js
  49.15 KB   build\static\css\main.85aeb9fe.chunk.css
  1.89 KB    build\static\css\2.43b85ee5.chunk.css
  769 B      build\static\js\runtime-main.3fe2b361.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment
```

**Comment by Nexucis** [comment]
@juliusv ah the prettier error are coming after replacing the `path` with the sed command.

So according to: https://stackoverflow.com/questions/55821078/disable-eslint-that-create-react-app-provides

it seems (thanks to react-script v4) you can simply replace `CI= npm run build` by `DISABLE_ESLINT_PLUGIN=true npm run build`

Like that it will ignore eslint when building the preview

**Comment by juliusv** [comment]
@Nexucis Ahh, that's why I had the `CI= npm run lint` in there before, because before the modularization, the `lint` script was auto-fixing things: https://github.com/prometheus/prometheus/blob/05a816bfb739b3841acd82bd285bfb5dfec7bfd7/web/ui/react-app/package.json

But yeah, maybe disabling the linting is even better, will try that.

**Comment by roidelapluie** [comment]
> @Nexucis Ahh, that's why I had the `CI= npm run lint` in there before, because before the modularization, the `lint` script was auto-fixing things: https://github.com/prometheus/prometheus/blob/05a816bfb739b3841acd82bd285bfb5dfec7bfd7/web/ui/react-app/package.json
> 
> But yeah, maybe disabling the linting is even better, will try that.

I have done it and build is green

**Comment by juliusv** [comment]
Saw that, thanks :)

**Comment by juliusv** [comment]
:+1:

**Comment by Nexucis** [comment]
It looks like the netifly deployment is working \o/. Cool ! Thanks @roidelapluie and @juliusv haha

**Pull request merged**
