### PR TITLE
fix: setting remote storage queue timestamp of last send only if succesful

### PR DESCRIPTION
**Pull request by FUSAKLA**
Idea to fix the https://github.com/prometheus/prometheus/issues/12559

### CODE REVIEW

**Comment by cstyan** [comment]
I don't think this is the change we actually want to make. We intentionally update the last sent timestamp in the case of non-recoverable errors, for example the receiving end rejecting your write request due to samples out of order or something like that. We intentionally retry on network errors, 5XX status codes, and (if configured) on rate limit 429, and in those cases we don't update the counter. Rereading the retry code for the first time in a while, I think there is an exception in one case. That case being if the context was cancelled

**Comment by FUSAKLA** [comment]
Yes, you are right, I did misread the code and came to the conclusion that the timestamp is set on every error. Thanks for pointing that out. But actually you are right and the issues we are debugging are caused by timeouts, so this might be the issue :thinking:

**Comment by FUSAKLA** [comment]
But if I'm not mistaken, it looks like the only `WithTimeout` is set by the `Store` function of the remote write client 

https://github.com/prometheus/prometheus/blob/657da2eb98451210ef81b9b1dbe377fc725cc994/storage/remote/client.go#L210

But the remote client seems to handle canceled context as error, which should lead to a recoverable error?

https://github.com/prometheus/prometheus/blob/657da2eb98451210ef81b9b1dbe377fc725cc994/storage/remote/client.go#L220

If I follow the path down there to the depth of net/http client context handling, I end up somewhere [here in the `setRequestCancel`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/net/http/client.go;l=344) where it's getting a bit entangled and not sure how canceled context would end up.

So I'm not sure TBH if the only timeout set to the context currently would lead to such result as non-recoverable error :thinking: 

I'll try to come up with some test to try it out and see how it behaves.

**Comment by FUSAKLA** [comment]
Hm, such test passes

```go
func TestTimeout(t *testing.T) {
	c, err := NewWriteClient("test", &ClientConfig{
		URL:              &common_config.URL{URL: &url.URL{Scheme: "http", Host: "10.255.254.1"}},
		Timeout:          model.Duration(1 * time.Second),
		HTTPClientConfig: common_config.DefaultHTTPClientConfig,
		RetryOnRateLimit: false,
	})
	if err != nil {
		t.Fatal(err)
	}
	err = c.Store(context.Background(), nil)
	var backoffErr RecoverableError
	fmt.Println(err)
	fmt.Println(errors.As(err, &backoffErr))
	if !errors.As(err, &backoffErr) {
		t.Fatalf("expected backoff error, got %v", err)
	}
}
```

```
=== RUN   TestTimeout
Post "http://10.255.254.1": context deadline exceeded
true
--- PASS: TestTimeout (1.00s)
PASS
ok      github.com/prometheus/prometheus/storage/remote 1.037s
```

**Comment by jesusvazquez** [comment]
Hello, this PR has been reviewed during the bug scrub.

We see that @cstyan requested some changes back in July and they have not been addressed yet.

So we'll close this but we'll welcome any follow up work.

Thank you.

**Pull request closed without merging**
