### PR TITLE
`MemPostings.Delete()` batches without holding the `Lock()`

### PR DESCRIPTION
**Pull request by colega**
The change introduced in #14307 was great for the performance of MemPostings.Delete(): we know which labels we have to touch, so we just grab the lock once and keep processing them until we're done.

While this is the best for MemPostings.Delete(), it's much worse for other users of that mutex: readers and new series writes. These now have to wait until we've deleted all the affected postings, which are potentially millions. Our operation isn't so urgent, but we're not letting other users grab the mutex.

While #15242 proposes a solution for this by performing small pauses from time to time and letting other callers take the mutex, it still doesn't address the elephant in the room: we're just doing too much stuff with the write mutex being held, that's is exclusive time for us. We can spread it longer over time, decreasing the impact, but the overall exclusive time is the same, and we should try to address that.

What's the long operation we're doing while holding the write mutex? We're filtering the postings list for each label by building a new one, and looking up in a hashmap whether each one of those elements id deleted. These lists are potentially tens or hundreds of thousands of elements each one.

Why don't we build that list while holding just a RLock()? Well there's a small issue with that: maybe a new series is added to the list after we've built that filtered replacement postings list, and before we took the write mutex. ~The good news is that postings are always appended in-order to the list and we are the only ones who delete things from that list, so if we just check whether the list grew, we can know for sure if we're missing something.~ ~Moreover we don't even need to rebuild the entire list if something was added, we just need to add the extra elements that the list has now compared to our snapshot.~

Since postings aren't really added in order, we either have to detect what changed (I have several ideas about how to do that, by tracking which postings were at well known positions) or we just accept our bad luck and recalculate them under the write lock.

Finally, one last thing to address is that with this approach we'd be taking the write mutex once per affected label value again, which is a lot, it causes too long compactions under lots of read pressure, and we mitigated that in the past. We also can't just build all the replacement builds and then swap them in one go: we would be referencing too much memory there. It is true that while we're swapping there's still someone referencing the old slice from some reader, but not at an arbitrary scale: for a 2M series tsdb, label names which reference all series (like the typical env=prod) as 16MB of postings each one (2M * 8B).

So we process labels in batches, with max 128 labels in a batch (so ideally we take one write mutex per each 128 labels) and a maximum of 10*len(allpostings) max postings in the batch (in our example that would be an extra 160MB allocated temporarily, which should be negligible in a 2M series instance.

_I would recommend just checking the new code version instead of checking the diff_

### CODE REVIEW

**Comment by colega** [comment]
There's no difference in benchmarks, but our benchmarks don't really measure the amount of blocking we're doing on that mutex, they're measuring the MemPostings.Delete speed.

**Comment by colega** [comment]
(Draft because I need to fix the fact that new postings added aren't necessarily added in the last positions)

**Review by GiedriusS — COMMENTED** [review]
Any way we could add a benchmark? I'm also seeing increased write latency when head GC is happening and a lot of new series are being created. Would it make sense to do this in a benchmark? If it sounds good then I could try contributing a benchmark.

Another attempt:
https://github.com/prometheus/prometheus/pull/13642/files (sharding the lock)

**Comment by colega** [comment]
Sure, a decent benchmark would definitely help evaluating solutions. We would need to simulate a good pressure on both writes and reads.

Please also note there's https://github.com/prometheus/prometheus/pull/15242 which already alleviates the current problem (re: _I'm also seeing increased write latency when head GC is happening and a lot of new series are being created._ )

**Comment by colega** [comment]
I also sent a draft with a simpler approach without doing the batches in https://github.com/prometheus/prometheus/pull/15310

**Comment by colega** [comment]
I'm concerned here about the fact that if series churn is high, then we would always hit the "recalculate" branch. I think it's worth improving that before even testing it under load.

I think that the benchmark that @GiedriusS suggests would be very useful.

**Comment by colega** [comment]
After running #15242 for a while in production, we no longer see lock contention on `Delete()`.

We do see issues with frequent `Add()` stalling the read path (and the write path too!). We talked about #13642, and it doesn't seem like it's going to alleviate that contention.

We discussed the idea of doing batch `Add`'s, and I've came up with this solution https://github.com/prometheus/prometheus/pull/15374

**Pull request closed without merging**
