### PR TITLE
thanos query downsample 1h datas from  last 7 days, but  lost many datas.

### PR DESCRIPTION
**Pull request by t00350320**
promql:
query=sum(cpu{ip="xx",supplier="ali"})&start=1630574800&end=1631158800&step=1800&max_source_resolution=1h

The actual series timestamp from  thanos-store is 1800s step, like 17:29:59s、17:59:59s、18:29:59s、18:59:59s

current code:

engine.go
func (ev *evaluator) eval
  case *parser.VectorSelector:
                fmt.Println("test,*parser.VectorSelector",e)
                //log,test,*parser.VectorSelector cpu{ip="xx",supplier="ali"}
                ....
                 ev.vectorSelectorSingle(it, e, ts)

func (ev *evaluator) vectorSelectorSingle(it *storage.MemoizedSeriesIterator, node *parser.VectorSelector, ts int64) (int64, float64, bool) {
	refTime := ts - durationMilliseconds(node.Offset)
	var t int64
	var v float64
	//log start, just watch the series datas from 2021-9-2 17:0:0 to 2021-9-2 19:0:0
        if ts >= 1630573200 && ts <= 1630580400 {
                fmt.Println("test,vectorSelectorSingle0",ts,durationSeconds(node.Offset),refTime)
                //test,vectorSelectorSingle0 1630574800 0 1630574800
        }
	//log start
	ok := it.Seek(refTime)
	if !ok {
		if it.Err() != nil {
			ev.error(it.Err())
		}
	}

	if ok {
		t, v = it.Values()
		//log start
        		if ts >= 1630573200 && ts <= 1630580400 {
                      		  fmt.Println("test,vectorSelectorSingle1",ts,t,v)
                                  //test,vectorSelectorSingle1 1630574800 1630574999 6.081878024449999e+06
              	}
		//log end
	}

	if !ok || t > refTime {【actual  data  17:29:59s > refTime:17:26:40】
                if ts >= 1630573200 && ts <= 1630580400 {
                        fmt.Println("test,vectorSelectorSingle2",ts,t,refTime,ok)
                        //test,vectorSelectorSingle2 1630574800 1630574999 1630574800 true
                }
		t, v, ok = it.PeekPrev()【 because there is no data in history , so peekback is false】
		if !ok || t < refTime-durationMilliseconds(ev.lookbackDelta) {
			//log start
			if ts >= 1630573200 && ts <= 1630580400 {
                                fmt.Println("test,vectorSelectorSingle3",ts,t,refTime,durationSeconds(ev.lookbackDelta))
                                //test,vectorSelectorSingle3 1630574800 0 1630574800 300
                       		 }
			// log end
			return 0, 0, false
		}
	}

query starttime=17:26:40(1630574800) or before 17:59， refTime is 17:26:40, actual  data  17:29:59s > refTime, because there is no data in history , so peekback is false. So the point of 17:29:59s  is lost.
 The next query starttime=17:56:40,  refTime is 17:56:40, actual data  17:59:59s > refTime, because there is no data in history too, so peekback is false too. So the point of 17:59:59s  is lost too.
So, we lost many datas by current mechanism.

Based on this, we add a interval check:  
		if t < refTime + ev.interval {
			return t, v, true
		}
we think refTime  falls in (ts,ts+ev.interval) will be a true value.

after:

func (ev *evaluator) vectorSelectorSingle(it *storage.MemoizedSeriesIterator, node *parser.VectorSelector, ts int64) (int64, float64, bool) {
	refTime := ts - durationMilliseconds(node.Offset)
	var t int64
	var v float64
	//log start
    if ts >= 1630573200 && ts <= 1630580400 {
                fmt.Println("test,vectorSelectorSingle0",ts,durationSeconds(node.Offset),refTime)
                //test,vectorSelectorSingle0 1630574800 0 1630574800
     }
	//log start
	ok := it.Seek(refTime)
	if !ok {
		if it.Err() != nil {
			ev.error(it.Err())
		}
	}

	if ok {
		t, v = it.Values()
		//log start
        		if ts >= 1630573200 && ts <= 1630580400 {
                      		  fmt.Println("test,vectorSelectorSingle1",ts,t,v)
                                  //test,vectorSelectorSingle1 1630574800 1630574999 6.081878024449999e+06
              	}
		//log end
               // pull request part
		if t < refTime + ev.interval {
			fmt.Println("test,vectorSelectorSingle1-1",ts,t,refTime,ev.interval)
                        //test,vectorSelectorSingle1-1 1630574800 1630574999 1630574800 1800
			return t, v, true
		}
                // pull request end
	}

	if !ok || t > refTime {
           if ts >= 1630573200 && ts <= 1630580400 {
                        fmt.Println("test,vectorSelectorSingle2",ts,t,refTime,ok)
                }

		t, v, ok = it.PeekPrev()
		if !ok || t < refTime-durationMilliseconds(ev.lookbackDelta) {
			//log start
			if ts >= 1630573200 && ts <= 1630580400 {
                                fmt.Println("test,vectorSelectorSingle3",ts,t,refTime,durationSeconds(ev.lookbackDelta))
                       		 }
			// log end
			return 0, 0, false
		}
	}

after we modify current mechanism, the last 7 day's datas return true.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you, from my understanding, this is not a bug. When prometheus runs a query, it will look back, and should not look ahead.

**Comment by t00350320** [comment]
> Thank you, from my understanding, this is not a bug. When prometheus runs a query, it will look back, and should not look ahead.

**Comment by t00350320** [comment]
> Thank you, from my understanding, this is not a bug. When prometheus runs a query, it will look back, and should not look ahead.

We set starttime=18:00:00 , the datas will be ok. But it get's worse at 18:26:00
Because  user makes query at a random timestamp, this issue confused me for a week.
Do you have any other suggestion?

**Comment by roidelapluie** [comment]
I'd say that you could ask this to the thanos community, they might better help you. I do not know much about thanos downsampling.

**Comment by t00350320** [comment]
> I'd say that you could ask this to the thanos community, they might better help you. I do not know much about thanos downsampling.

thanks for your suggestion.I'll ask them for help. But i guess it has less relation with thanos. Thanos's query engine is the same with prometheus.
Suppose we  scraper a metric in 1800s interval, when query the metric's data with  vectorSelectorSingle(), it also may have this problem.

**Pull request closed without merging**
