### PR TITLE
marathon.go: Simplified conditions in method

### PR DESCRIPTION
**Pull request by proggga**
Small improvement, hope you are hacktoberfest friendly =) Thanks

### CODE REVIEW

**Comment by proggga** [comment]
I need someone to help me with this broken pipeline

**Comment by roidelapluie** [comment]
I wonder if everything needs to be put down under a if or if we should adapt the exiting ifs with the variable

**Comment by proggga** [comment]
> I wonder if everything needs to be put down under a if or if we should adapt the exiting ifs with the variable

I can make any option, as you want, because I'm not a familiar with style in this repo

**Comment by proggga** [comment]
Yep, I'll do this, need few days to find time, but I'll do this

**Comment by proggga** [comment]
@roidelapluie Can you please take a look once again when you have free time, thanks for your help!

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
