### PR TITLE
Fix golint issue caused by incorrect func name

### PR DESCRIPTION
**Pull request by fenggw-fnst**
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Our CI is a bit broken currently, I'll merge once it's happy again.

**Comment by roidelapluie** [comment]
> Our CI is a bit broken currently, I'll merge once it's happy again.

Fork PRs unable to upload artifacts or access caches, workspaces
Resolved - Between 13:10 UTC and 15:00 UTC, fork PRs were unable to access caches, workspaces or upload artifacts due to a permissions error. Caches and artifacts would have failed without aborting jobs, but workspaces caused job failures. Caches, workspaces, and artifacts will now run normally. Jobs that failed or aborted due to this error can be rerun from the UI.
Aug 6, 15:05 UTC

> Our CI is a bit broken currently, I'll merge once it's happy again.

I have relaunched as it is solved per circleci status page.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
