### PR TITLE
Use npm workspace and integrate codemirror-promql locally

### PR DESCRIPTION
**Pull request by Nexucis**
This PR is changing the way to setup the `react-app` and the web module. It is now used the npm workspace.
This is done in order to use locally `codemirror-promql`.

This PR introduces the usage of `craco` which wrappes `react-script` and allows the override of the webpack configuration.

Note: This PR must be merged after https://github.com/prometheus/prometheus/pull/9284 and after https://github.com/prometheus/prometheus/pull/9322

### CODE REVIEW

**Comment by Nexucis** [comment]
Actually we don't need to override the webpack configuration. I managed to avoid it by changing how is configured the package `codemirror-promql`.
So no need to introduce `craco`

**Comment by juliusv** [comment]
This generally looks good to me as well (after adjustments relative to the PRs it depends on etc.).

**Comment by roidelapluie** [comment]
We are getting closer!!

**Comment by Nexucis** [comment]
> We are getting closer!!

yeaah \o/

I merged the PR with the `main`. So this PR is ready to be reviewed :).

I broke netifly. But maybe it should be fixed once the PR is merged ?
I hope it is fine if I took the opportunity to cleanup a bit the makefile regarding the UI build management.

And from my perspective I think moving to npm workspace simplify a bit the way to build the `react-app` and the relative command. But that's maybe just me.
Anyway, I'm happy we will finally be able to used locally `codemirror-promql`. That was more complicated than what I thought haha

**Comment by juliusv** [comment]
I fixed up the base directory & npm version etc. in Netlify. Now it's failing at the linting step since some files in the module have linter errors (I get the same locally when doing `make ui-lint`):

```
[...]

/home/julius/gosrc/src/github.com/prometheus/prometheus/web/ui/module/codemirror-promql/src/complete/hybrid.test.ts
  781:12  error  Delete `⏎·······`  prettier/prettier

/home/julius/gosrc/src/github.com/prometheus/prometheus/web/ui/module/codemirror-promql/src/lint/index.ts
  30:8  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/home/julius/gosrc/src/github.com/prometheus/prometheus/web/ui/module/codemirror-promql/src/parser/parser.ts
  76:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/home/julius/gosrc/src/github.com/prometheus/prometheus/web/ui/module/codemirror-promql/src/parser/vector.ts
  33:8  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/home/julius/gosrc/src/github.com/prometheus/prometheus/web/ui/module/codemirror-promql/src/promql.ts
  27:8    warning  Missing return type on function                                                                                         @typescript-eslint/explicit-module-boundary-types
  38:465  error    Replace `·tags.function(⏎············tags.variableName⏎··········` with `⏎············tags.function(tags.variableName`  prettier/prettier

/home/julius/gosrc/src/github.com/prometheus/prometheus/web/ui/module/codemirror-promql/src/test/utils.test.ts
  31:8  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

✖ 9 problems (2 errors, 7 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by juliusv** [comment]
@Nexucis I allowed myself to push a fix for the linter errors to this PR :grimacing:

**Comment by roidelapluie** [comment]
We should run ui-lint in circle CI as well

**Comment by juliusv** [comment]
> We should run ui-lint in circle CI as well

I added that, hopefully I did it right.

**Comment by Nexucis** [comment]
> @Nexucis I allowed myself to push a fix for the linter errors to this PR

thanks :)

I will fix the warning in another PR, so we can merge this one and unlock others PRs that depends on it.

> I added that, hopefully I did it right.

Yeah I think it's good to do it like that. No need to add a new job just for the linter.

**Comment by juliusv** [comment]
Yep, and as Netlify now fits this PR and not `main` anymore, I'll merge this as soon as the tests go green, and then we can do any required follow-up work :)

**Pull request merged**
