### PR TITLE
Fixes for influxdb-0.9 stable release

### PR DESCRIPTION
**Pull request by jmcfarlane**
- Rename name to measurement.
- Rename timestamp to time.
- Determine success based on http 204, not 200.

@julius

### CODE REVIEW

**Comment by jmcfarlane** [comment]
This is _not_ ready for submission by the way. It does fix the naming changes, but still results in sorta worthless data because the values are passed as string. This means you can fetch data, but cannot use any aggregation functions - and thus is sorta worthless.

I'll fix that (and update it to the new line protocol in the process) in a subsequent commit.

**Comment by beorn7** [comment]
You surely mean @juliusv . ;-)

**Comment by juliusv** [comment]
@jmcfarlane Thanks a lot for these adjustments! The reason why we're sending numbers as strings is because JSON is the most braindead serialization format ever and doesn't support `NaN`, `Inf`, `-Inf` as numeric values (even though JavaScript supports those). Our options would be to either keep storing strings or flatten all of those special float values to `null`. I don't have much InfluxDB querying experience yet, but I guess you're hinting at the fact that the latter is really necessary to then do anything useful with those values in InfluxDB, right?

**Comment by fabxc** [comment]
How about going with `null` for `NaN` and just really large numbers for `+/-Inf`. Not pretty but at least it will be numbers that roughly do what you intend most of the time.
If we are lucky InfluxDB will ingest them as infinity on an out-of-range error. [This](https://github.com/prometheus/prometheus/blob/master/promql/parse_test.go#L171-L173) is about the necessary size.

**Comment by juliusv** [comment]
Haha! That's one possibility, although it is quite ugly.

Just had this conversation on Twitter about it with Paul:
https://twitter.com/juliusvolz/status/610527244885327872

In the official docs, I can currently actually only find this line-based protocol, with no reference to the JSON-based one for writing:

http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html

The line-based writing protocol might support special float values (though it still doesn't solve the read-back problem), but I'll have to experimentally verify that.

**Comment by juliusv** [comment]
Oh, if I understood Paul correctly, they *could* support it with the line-based protocol now, but don't currently. Will still try out what happens...

**Comment by juliusv** [comment]
Humm, I can't even manually write a point into InfluxDB 0.9.0 anymore with the line-based protocol. Trying the instructions from http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html, I get:

```
$ curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
{"results":[{}]}%
$ curl -i -XPOST 'http://localhost:8086/write?db=mydb&rp=mypolicy' -d 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Request-Id: 68a01bcc-139b-11e5-bb31-74d435e862b6
X-Influxdb-Version: 0.9
Date: Mon, 15 Jun 2015 20:16:30 GMT
Content-Length: 65

{"error":"invalid character 'c' looking for beginning of value"}
```

I also couldn't get this PR here to correctly send anything InfluxDB yet (always getting a ton of these errors: `error sending 100 samples to remote storage: invalid character 'p' after top-level value`).

**Comment by jmcfarlane** [comment]
I've got Prometheus successfully writing to influx via the new line
protocol, but I'm also suck in an airport atm and unable to really make any
progress. I'll try to get to this when I fly back to Seattle later this
week.

**Comment by juliusv** [comment]
Ok, the above was my fault for not building the new InfluxDB version correctly. Now the example works, but trying to send a normal float value, and then `NaN`, I get:

```
curl -i -XPOST 'http://localhost:8086/write?db=mydb&rp=default' -d 'cpu_load_short,host=server01,region=us-west value=NaN 1434055562000000000' 
HTTP/1.1 400 Bad Request
Request-Id: 891a7eb5-139c-11e5-8004-000000000000
X-Influxdb-Version: FIXME
Date: Mon, 15 Jun 2015 20:24:34 GMT
Content-Length: 116
Content-Type: text/plain; charset=utf-8

write failed: field type conflict: input field "value" is type bool, already exists as type %!s(influxql.DataType=1)%
```

So `NaN` gets parsed as a boolean.

It seems that fields in InfluxDB (`value` in this case) generally get a type assigned on the first write and then need to keep that type in later writes. The problem is, if you send an integer first, and then a float for the same field for the next sample, it will reject the float because it already set the field's type to integer on the first write. So we'd have to format our floats in such a way that even if they happen to be integers, they get encoded with a dot after the last digit, so that if they ever change to floats, the write will succeed.

I don't know what to do with special float values in the line-based protocol however, since it's not JSON and has no concept of null.

**Comment by jmcfarlane** [comment]
I'll work with Paul to sort this out (I have a vested interest in this
working :)

**Comment by juliusv** [comment]
@jmcfarlane Great! :)

**Comment by juliusv** [comment]
@jmcfarlane Any news on this one?

**Comment by jmcfarlane** [comment]
I'm back from my trip now and working on this today actually. Currently there are two issues I'm looking into:

1. If you convert the prometheus value to a string via `strconv.FormatFloat(point.Value, 'f', -1, 64)` it's sometimes seen by influxdb as an int, other times as a float (based on the presence of decimals). This change in data type is rejected. My current thinking is to force the value to have at least one decimal place.
2. Some of the timestamps I'm passing are considered invalid. For example `1435250669731000000` is a good timestamp, but `1435250668922000000` is invalid.

**Comment by juliusv** [comment]
@jmcfarlane So I spoke to @pauldix in person at GopherCon. Things to note:

- The JSON protocol is deprecated in favor of InfluxDB's new line-based protocol (https://influxdb.com/docs/v0.9/guides/writing_data.html). Would be great to switch to that here already. There's actually a Go client library for InfluxDB that might be worth using here: https://github.com/influxdb/influxdb/tree/master/client

- Though `NaN`, `Inf`, and `-Inf` have their limited uses, we agreed that they're not a priority. Let's just drop them for now.

- The protocol will continue to do automatic type assignments based on absence or presence of decimal periods. So any samples we send to InfluxDB should be suffixed with `.` (or `.0`?) to ensure all series are typed as floats.

I didn't think to ask about the timestamp problems you've been seeing though.

**Comment by juliusv** [comment]
Oh, I see you're already using a manually implemented line protocol. Btw., when using the client library, it already does all the decimal stuff correctly when sending floats: https://github.com/influxdb/influxdb/blob/6b8d3268e6a8d8b5107ad4e4cdef9781a9339ce5/tsdb/points.go#L1090-L1092

While I don't feel *super* strongly about using the client library, it's probably the better option as we know it should handle all edge cases correctly and be updated for us if anything changes.

**Comment by jmcfarlane** [comment]
Oh great. Will switch that to use their library instead. Thanks!

**Comment by juliusv** [comment]
@jmcfarlane Any news on this one, or should I give this a go myself?

**Comment by juliusv** [comment]
@jmcfarlane I'm on this now and try to get this done until tomorrow or so.

**Comment by jmcfarlane** [comment]
That'd be great. I also took a pass day before yesterday and have it
working (with the upstream library + 9.3). I just need to clean it up (move
the client instantation outside the batching call, etc). I'm probably going
to finish it for my own learning anyway (am trying to slowly learn more
about golang).

**Comment by juliusv** [comment]
@jmcfarlane Ha, ok! We can compare in the end, and maybe you can give mine a review then to see if I missed something important.

**Comment by juliusv** [comment]
Currently this is stuck on https://twitter.com/juliusvolz/status/643782802589229056

**Comment by jmcfarlane** [comment]
Funny you mention that... I'm stuck on:

$ ./.build/root/gopath/bin/godep save
> godep: no buildable Go source files in
> /home/ubuntu/dev/monitoring/UPSTREAM/prometheus
> godep: error loading packages


/me recalls previous comment about needing to learn how things work in
goland :)

**Comment by juliusv** [comment]
Yeah, wondering what to do now, because we want to get Prometheus 0.16.0rc1 out. Maybe we'll just leave the InfluxDB support old and broken for now and wait for the client library to become more reasonable in its dependencies :-/

**Comment by jmcfarlane** [comment]
I would recommend that. In the mean time I can run it under some load and
assert it does not impact Prometheus health. We have ~2 terabytes in
Prometheus currently and thus are looking for a long term storage option,
but do not want to rush into it.

I will report back with some info on that in a few weeks :)

**Comment by juliusv** [comment]
@jmcfarlane Cool, yeah. I mean, my InfluxDB support (including some other fixes) is basically done now, just needs fixing of existing tests and solving of the vendoring issue. I pushed the WIP here: https://github.com/prometheus/prometheus/commits/fix-influxdb

**Comment by juliusv** [comment]
I worked around the vendoring issue for now by just cutting up the client library manually and only including the actually necessary parts. My InfluxDB fix PR is up here now:

https://github.com/prometheus/prometheus/pull/1087

**Comment by jmcfarlane** [comment]
This is no longer needed :)

**Pull request closed without merging**
