### PR TITLE
HTML-escape label values in Rickshaw hover-detail.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
@brian-brazil Console graphs have the same issue, adding that...

**Comment by juliusv** [comment]
@brian-brazil :D

cats

**Comment by juliusv** [comment]
@brian-brazil Added fix for console templates - please take another look.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
