### PR TITLE
Only set CORS headers if they aren't set already

### PR DESCRIPTION
**Pull request by jacksontj**
This allow for middleware to set these to more specific values if desired

### CODE REVIEW

**Comment by brian-brazil** [comment]
Do we have code that needs this?

**Comment by jacksontj** [comment]
I have a few use-cases that do this, and as of today I have to maintain a fork of the repo to make prometheus not set these. I'm also open to moving this to a configuration option, but this seemed like the simplest solution to the issue.

**Comment by brian-brazil** [comment]
We don't generally keep code that we don't use, as our internal APIs are internal. If there are existing endpoints that don't have the right headers currently we can discuss changing them.

**Comment by brian-brazil** [comment]
If we don't have code that needs this, then it's best not to have this. Less chance of a mixup that causes an unintentional security issue.

**Comment by aloababa** [comment]
What if i don't want '*' for Access-Control-Allow-Origin ?

**Pull request closed without merging**
