### PR TITLE
Release 2.48.0-rc.1

### PR DESCRIPTION
**Pull request by LeviHarrison**

### CODE REVIEW

**Comment by LeviHarrison** [comment]
Also if someone else with admin doesn't mind merging this once it's ready, I can't because of the broken check.

**Comment by bboreham** [comment]
FYI prombench seems to need its authentication updated. 
See discussion in Slack https://cloud-native.slack.com/archives/C01AUBA4PFE/p1698501889156349

**Comment by LeviHarrison** [comment]
I'm not sure how long it will take for prombench to be fixed, but given that it looks like we're going to have to "refactor the gke provider to be given credentials," maybe in the interest of time I should just figure out how to run it locally so we can get this release out?

**Pull request merged**
