### PR TITLE
config: deprecate `target_groups` for `static_configs`

### PR DESCRIPTION
**Pull request by fabxc**
This change deprecates the `target_groups` option in favor
of `static_configs`. The old configuration is still accepted
but prints a warning.
Configuration loading errors if both options are set.

### CODE REVIEW

**Comment by grobie** [comment]
:+1: but what about `TargetGroup`? I'd rename the type as well for consistency.

**Comment by brian-brazil** [comment]
:+1: 

TargetGroup is used internally for SD.

**Comment by fabxc** [comment]
Yea, `TargetGroup` is literally the representation of targets SDs provide. In the case of static configurations the provider is the configuring user.

**Comment by grobie** [comment]
I see, make sense.

**Pull request merged**
