### PR TITLE
discovery/k8s: update client library

### PR DESCRIPTION
**Pull request by fabxc**
This updates the Kubernetes client library, which seems to fix the extreme memory consumption we could see in #2685.

We ran a bunch of different Prometheus versions using K8S SD (growing lines) and one with the same targets replicated into a static config, and one with the updates of this PR.
The latter two are the stable lines that hardly grow. This should hopefully solve it and we would backport this into 1.5.2 and 1.6.2 patch releases. 

image

Worth noting that we have user reports that 1.6 has the urgency score issues even with sufficient memory, which is why we'll probably generally advise remaining on 1.5 when using k8s/prometheus-operator.

### CODE REVIEW

**Comment by fabxc** [comment]
I also implemented de-duplication of the API watches but as we see with this fix there's no immediate need. As it's another point where regressions could happen I left it out for now.

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
To avoid cherrypicking, I suggest to merge this into the release-1.5 branch. Then merge from there into release-1.6 and master.

**Comment by fabxc** [comment]
Mh, what's the benefit of merging via 2 redirects rather than just cherry-picking. I feel like there are cases where either is easier and here cherry-picking seems a lot simpler.

**Comment by beorn7** [comment]
1000+ files changed, 350k delta lines, very Googley... ;-/

:+1: besides merging this into release-1.5.

**Comment by beorn7** [comment]
I just like to find the same commit id's for the same thing. Cherrypicking creates new commit id's.

**Comment by beorn7** [comment]
And why would cherrypicking be easier here? It's just throwing away the advantages of Git and going back to CVS. I don't see any advantage.

**Comment by fabxc** [comment]
Yea, a lot of repo restructuring happened in the client libs, which is where most of it comes from rather than actual code changes.

I can do the merging, not feeling that strongly. We'll just wait a bit more in our setup to definitely confirm it is fixed.

**Comment by grobie** [comment]
+1 for avoiding cherry-picking if possible. It makes diff'ing the changelog
between releases a lot more hard to read.

**Comment by fabxc** [comment]
Closing here and merging through the chain.

**Pull request closed without merging**
