### PR TITLE
tsdb: stop saving a copy of last 4 samples in memSeries

### PR DESCRIPTION
**Pull request by bboreham**
This extra copy of the last 4 samples was introduced to avoid a race condition between reading the last byte of the chunk and writing to it. ~However this race condition was fixed in f42ed03dc5be, so we don't need the copy any more.~

EDIT: But we can copy just the last byte in `bstreamReader` instead.

This change saves 56 bytes per series, which is very worthwhile when you have millions of series.

(#11280 and #11288 each remove another 8 bytes)

I kept the head snapshot binary compatible by writing zeros where the samples used to be and ignoring any values found, but perhaps we should bump the version and save the work.

### CODE REVIEW

**Comment by pracucci** [comment]
I don't think [my change](https://github.com/prometheus/prometheus/commit/f42ed03dc5be7290a913fe427cdf96f6d1bee792) to `bstreamReader` fixes the race condition you talk about in this PR.

My change assumes the caller never tries to read the last byte if it's unsafe to do. So, in `bstreamReader.loadNextBuffer()` I make sure to never read from the last byte unless it was explicitly requested to do (via the number of `nbits` passed in input). The assumption that the caller never tries to read the last byte if it's unsafe to do, is because we keep the last 4 samples uncompressed in memory, which is what you're removing in this PR.

**Comment by bboreham** [comment]
I have updated this PR to take a copy of the last byte in `bstreamReader`.
Also added comments to clarify that concurrent Iterator and Appender are allowed, but the chunk must not be modified while an Iterator is created. (This was already the case, in order to copy the bstream slice header.)

**Review by pracucci — APPROVED** [review]
Good job, Bryan! I double checking the locking when appending samples to the chunk and creating the iterator, and I can't find any issue 👏

**Review by codesome — APPROVED** [review]
Nice! LGTM

**Pull request merged**
