### PR TITLE
Add resets() function to count counter resets.

### PR DESCRIPTION
**Pull request by juliusv**
resets() returns for every range vector element how many counter
resets there have been in the specified range.

### CODE REVIEW

**Comment by juliusv** [comment]
@brian-brazil @fabxc

**Comment by brian-brazil** [comment]
:+1:

**Comment by fabxc** [comment]
:+1:

**Comment by aecolley** [comment]
Many thanks! This makes it much easier to write a TaskRestartingTooOften alert.

**Comment by juliusv** [comment]
@aecolley `changes()` (https://github.com/prometheus/prometheus/pull/737) would be even better for that as long as your process exports the standard `process_start_time_seconds` metric (I think all our client libraries include it by default now). With counters, you otherwise have to rely on them increasing at all to detect any resets.

**Pull request merged**
