### PR TITLE
Use tag names consistently

### PR DESCRIPTION
**Pull request by grobie**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Didn't we say that the tag would have the v, but not the version number?

**Comment by grobie** [comment]
Our usage is very inconsistent right now across repos and even inside of repos. I can only remember that we that we won't use the v inside of tarball names, as these have already an established naming scheme. See the mailing list thread on prometheus-developers@ and let's discuss there I guess.

**Comment by brian-brazil** [comment]
I wasn't following too closely, that's just my recollection of the last time there was a big discussion of this.

**Comment by juliusv** [comment]
:+1:

**Comment by beorn7** [comment]
@brian-brazil  remembers correctly. Last time we discussed this, we concluded to _not_ use the `v` in `CHANGELOG.md`. The rule is essentially the following: In contexts, where only a version number can appear, just use the version number. In contexts where a version number is just one possibility of many (e.g. in tags), prefix the version number with the `v`. In this way, everything is consistent, including tarballs.

I suggest to revert this change and instead make everything else consistent.

**Comment by grobie** [comment]
Apparently that rule left too much room for ambiguity as a every person has to decide for themselves whether a context can only include version numbers or not. We only use tags for releases, why is that context different to a github release?

That rule is also not following the established naming scheme of other CNCF and prominent Go projects (Kubernetes, Docker, etcd, etc.).

**Comment by juliusv** [comment]
:+1: for having the `v` here too, unless there's a compelling reason not to.

**Comment by beorn7** [comment]
Summary from my personal discussion with @grobie : I think our rule so far is beautifully consistent. On the other hand, I don't think this problem is worth to take a lot of our collective time. That's why I would think once decided, we should stick with it and not do a new vote every 6 months or so. I also don't think that changing the rule every 6 months because the old rule wasn't followed consistently will create more consistency. (I foresee repos still sticking to the old rule, while at some point somebody will come up with v's in the tarball name again, in the name of consistency...)

**Comment by brian-brazil** [comment]
I'm with Beorn on this, we need to make up our minds and stick to it. This is at least the 3rd way we've had of doing this by my count.

**Comment by grobie** [comment]
As I agree that this problem is not worth more discussion, I refrain from further comments on that decision and reverted the change in https://github.com/prometheus/prometheus/commit/2a426bfead5577a85adc7b8ff19401ce769fe6a8. I'll instead hunt down all the release managers using the v prefix in releases ...

**Pull request merged**
