### PR TITLE
[performance optimization] tsdb: Merge two loops in ‘delete’ function

### PR DESCRIPTION
**Pull request by liguozhong**
[performance optimization] tsdb: Merge two loops in ‘delete’ function

### CODE REVIEW

**Comment by csmarchbanks** [comment]
Do you have benchmarks showing a performance improvement? This change will always alloce a slice even in the case where nothing is to be deleted which could cause worse performance.

**Comment by liguozhong** [comment]
> Do you have benchmarks showing a performance improvement? This change will always alloce a slice even in the case where nothing is to be deleted which could cause worse performance.

yes. I run the benchmark and confirmed that it can double the performance.
image
(this pr)
image
(old delete )

**Comment by roidelapluie** [comment]
@csmarchbanks Should we run prombench on this? I don't know if we have other benchmarks that reflects real use cases for this.

**Comment by csmarchbanks** [comment]
It will probably be hard to tell in a prombench if this makes any difference as I think it would only happen during compaction where a lot of cpu intensive things are happening.

To merge this I would like to see benchmarks added to this MR that can be verified, when I ran the benchmark that seems to have been deleted from this thread I actually found the new code to be slower.
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkMemPostings_Delete-8     94931304      105818435     +11.47%
```

**Comment by liguozhong** [comment]
> It will probably be hard to tell in a prombench if this makes any difference as I think it would only happen during compaction where a lot of cpu intensive things are happening.
> 
> To merge this I would like to see benchmarks added to this MR that can be verified, when I ran the benchmark that seems to have been deleted from this thread I actually found the new code to be slower.
> 
> ```
> benchmark                         old ns/op     new ns/op     delta
> BenchmarkMemPostings_Delete-8     94931304      105818435     +11.47%
> ```
OK, I'll try

**Comment by gouthamve** [comment]
Hi @liguozhong, thanks for submitting the PR, seems useful, but with perf its always tricky. Did you have new benchmarks for this?

**Comment by liguozhong** [comment]
> Hi @liguozhong, thanks for submitting the PR, seems useful, but with perf its always tricky. Did you have new benchmarks for this?

My benchmark shows that this PR makes the performance worse, this is not a good idea

**Comment by brian-brazil** [comment]
Thanks for the update, I guess we should close this off then.

**Pull request closed without merging**
