### PR TITLE
Enable autocomplete anywhere in expression.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@beorn7 @fabxc

**Comment by beorn7** [comment]
The problem I see here that it enables the (metric name) autocomplete really _anywhere_, i.e. if I type a label name or a label value, it will still show me metric names. That's perhaps more confusing (especially for the non-pro user) than it helps.

I realize that we basically have to re-implement parts of the parser in JS to provide better autocompletion. It would be super awesome to have label name or even label value autocompletion, but until then, we should at least offer autocompletion only where a metric name is expected.

**Comment by juliusv** [comment]
@beorn7 Valid point. Though after using this for a while, it's hard to imagine going back to a non-autocomplete behavior. So I'm split. Will sleep over this some more (we'll be distracted the next days anyways) and then see how to proceed.

**Comment by beorn7** [comment]
It's probably easy to rule out at least a few cases (within quotes, within curly braces) and not offer auto completion in that case.

**Comment by fabxc** [comment]
"Reimplemeting parts of the parser in JS" sounds intense. In reality "open curly brace" and "in label value" is all we need, which is pretty simple.

Good motivation to think about HTTP endpoints for label stuff (we had some in the planning stage, IIRC).

I think the usability benefits of this feature exceed the required effort by several orders of magnitude.

**Comment by beorn7** [comment]
Yeah, those were my thoughts when writing my last comment.

Plan:
- Have some dumbass recognition of "in metric name" (doesn't have to be perfect)
- Only auto-complete when "in metric name".
- Later, add retrieving label names or even values.
- Then add label completions in a similar approach as above.
- Completing functions and aggregators would be great, too, but then it really evolves into a lot of parsing logic in the UI.

**Comment by fabxc** [comment]
Sounds good.

**Comment by fabxc** [comment]
What's your plan for this PR @juliusv?
I would really like to see this merged as current AC is mostly dysfunctional for serious expressions.

**Comment by juliusv** [comment]
Me too. But before I jump again into more advanced JS parsing, I need a quiet weekend or something like that :) Soon[tm]!

**Comment by juliusv** [comment]
@fabxc @beorn7 Turns out a quiet flight without internet was what I needed. Check this out now, it autocompletes really nicely only outside of strings or label matchers. I wrote this code on a plane in a sleep-deprived mode, but it seems to be working for me...

**Comment by fabxc** [comment]
Sweet, works well for me :+1: 

Next step would be auto-completing label names and values, which our API should provide for.
But this is the most important part.

How about getting rid of the "insert metric at cursor" button?

**Comment by juliusv** [comment]
@fabxc Updated to remove the "Insert Metrics" selector.

**Comment by beorn7** [comment]
@fabxc Are you on top of this or is my review required?

**Comment by fabxc** [comment]
Ah, :+1: implied after removing that button :)

**Comment by juliusv** [comment]
Wheeee!

**Pull request merged**
