### PR TITLE
Use remote storage in queue manager test

### PR DESCRIPTION
**Pull request by mucahitkurt**
Hi @tomwilkie ,
For the issue #3696 I've updated the queue manager `TestSampleDelivery` method to use remote.Storage instead of direct creation of remote.QueueManager.

### CODE REVIEW

**Comment by mucahitkurt** [comment]
Hi there, Is there anyone who can review this PR?

**Comment by codesome** [comment]
@tomwilkie @csmarchbanks @cstyan could one of you take a look at this? Thanks!

**Comment by cstyan** [comment]
@mucahitkurt We'd still like do a refactor of the remote storage tests, which would include the open issue your PR is for. If you're interested in continuing with this PR could you please rebase off master and make any necessary changes to resolve merge conflicts.

**Comment by mucahitkurt** [comment]
> @mucahitkurt We'd still like do a refactor of the remote storage tests, which would include the open issue your PR is for. If you're interested in continuing with this PR could you please rebase off master and make any necessary changes to resolve merge conflicts.

@cstyan I'll do that, thanks!

**Comment by mucahitkurt** [comment]
@cstyan I checked it, `queue_manager_test` already was refactored and I'm not sure about using a `remote.Storage` in `queue_manager_test` is still an issue? And also there is a `write_tests`, it was didn't exist at that time.

**Comment by cstyan** [comment]
I think anywhere we're calling `NewQueueManager` in a test is a potential candidate for this refactor given Tom's comment in the original issue: https://github.com/prometheus/prometheus/issues/3696#issuecomment-361221330

At least one or two where we want to set some specific queue config, we do that via creating storage and using`ApplyConfig`, and the test would fail if that queue config is not applied properly, is enough to consider that issue closed I think.

**Comment by mucahitkurt** [comment]
@cstyan PTAL, thanks!

**Pull request merged**
