### PR TITLE
labels: add extra tests

### PR DESCRIPTION
**Pull request by bboreham**
This PR is a subset of #10887 to make that one easier to work with.

It has a couple of small changes to tests to make them less reliant on internal details, and adds one new test for JSON and YAML marshalling.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Why is checking the exact value of Compare() an issue?

**Comment by bboreham** [comment]
If you change the implementation of `Compare()` such that it gives a different answer, as I did in #10991, then the existing test fails.
However if the test is changed to only check the documented interface - the sign - then the same test works for both.

**Comment by roidelapluie** [comment]
Except that the original test passes with #10991 if I am correct

**Comment by bboreham** [comment]
Not according to this:
```
$ go test ./model/labels/
ok      github.com/prometheus/prometheus/model/labels   0.004s
$ git checkout labels-as-string 
Switched to branch 'labels-as-string'
Your branch is up to date with 'bboreham/labels-as-string'.
$ go test ./model/labels/
ok      github.com/prometheus/prometheus/model/labels   0.004s
$ git revert 95b2090092320a34686443b9b68d8b4f4d6c9400
Auto-merging model/labels/labels_test.go
[labels-as-string 8b713278d] Revert "labels: test Compare without knowing the exact result"
 1 file changed, 1 insertion(+), 11 deletions(-)
$ go test ./model/labels/
--- FAIL: TestLabels_Compare (0.00s)
    labels_test.go:331: 
                Error Trace:    /home/vagrant/src/github.com/prometheus/prometheus/model/labels/labels_test.go:331
                Error:          Not equal: 
                                expected: 1
                                actual  : 8
                Test:           TestLabels_Compare
                Messages:       unexpected comparison result for test case 4
FAIL
FAIL    github.com/prometheus/prometheus/model/labels   0.005s
FAIL
```

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
My bad, Thanks!

**Pull request merged**
