### PR TITLE
promql: include more details in error message when creating test query fails or an unexpected series is returned

### PR DESCRIPTION
**Pull request by charleskorn**
This makes it easier to debug test failures.

### CODE REVIEW

**Comment by charleskorn** [comment]
The CI failure on Windows seems to be unrelated to these changes.

**Review by bboreham — APPROVED** [review]
Lgtm

**Review by jesusvazquez — APPROVED** [review]
LGTM

**Comment by jesusvazquez** [comment]
Also retrying CI

**Comment by bboreham** [comment]
Note CI failed twice; we should understand why.

**Pull request merged**
