### PR TITLE
[RFC] Replace vfsgen with embed for static web assets

### PR DESCRIPTION
**Pull request by jan--f**
$title describes the PR pretty well. The [`embed`](https://pkg.go.dev/embed) package was added in go 1.16 and offers a nice way to embed static files into a binary. 

I marked this RFC because `embed` currently offers no exclude directive, i.e. this initial version of the PR adds the resources excluded [here](https://github.com/prometheus/prometheus/blob/d77c985f8c122cf5947b0eb621999fcc8dcca9bf/web/ui/ui.go#L53-L56) to the binary. The resulting binary is about 10.6 MB larger than a v2.30.0 build (111522587 B instead of 100382142 B) on my machine. I'm not sure though if that is purely caused by the additional assets (iiuc that is currently only [bootstrap.js](prometheus/blob/d77c985f8c122cf5947b0eb621999fcc8dcca9bf/web/ui/static/vendor/bootstrap-4.5.2/js/bootstrap.js) and [bootstrap.css](prometheus/prometheus/blob/d77c985f8c122cf5947b0eb621999fcc8dcca9bf/web/ui/static/vendor/bootstrap-4.5.2/css/bootstrap.css), which certainly don't sum up to 10 MB). 
Furthermore the current version will include any file that is added to the `static` and `templates` subdirectory.

Possible solutions:

1. Embed any file that is present but add a [filter layer](https://pkg.go.dev/github.com/shurcooL/httpfs/filter), similar to what [ui.go](https://github.com/prometheus/prometheus/blob/d77c985f8c122cf5947b0eb621999fcc8dcca9bf/web/ui/ui.go) implements. This however bloats the resulting binary.
2. Craft a list of `//go:embed` directives, that include only the things that are needed instead of relying on naive globbing.
3. Ensure that the respective directory trees only contain the needed files before building.

One of the latter two is probably desirable, I'm just not sure which is easier to maintain. I also might be missing other options.

### CODE REVIEW

**Comment by jan--f** [comment]
cc @roidelapluie

**Comment by roidelapluie** [comment]
That's a nice improvement and cleanup. Now that go 1.17.1 is out, it is also reasonable to use go1.16 features.

However you have raised a few interesting points, I will try to investigate as well. 10MB seems a lot.

**Comment by jan--f** [comment]
I had a look at the respective intermediate compiled packages. Using `embed` results in a 15 MB intermediate package (that only includes `embed`, `net/http` and the file content). The vfsgen based asset package only amounts to ~130 KB. This likely is due to vfsgen using compression internaly.
There seem to be [potential future plans to add compression](https://go.googlesource.com/proposal/+/master/design/draft-embed.md#compression-to-reduce-binary-size) to embed.

I can also look into compressing the assets before embedding, though that may have performance implications.

**Comment by jan--f** [comment]
@roidelapluie I added an additional layer that unzips content on the fly. So if the `embedFS` contains `dir/file.gz` instead of `dir/file` the former is used and decompressed when `dir/file` accessed. The file will be decompressed in memory as a whole when opened. Not ideal but for Prometheus' use case this should be fine (iiuc the web interface reads only whole files anyway).

Unfortunately this currently requires an additional step before building (see below), so it doesn't improve on the existing solution in that respect. It does however bring down the binary size to something closer that a current `main` build yields (`-rwxr-xr-x 1 jan jan 98085936 Oct  5 14:27 prometheus` on my system). 

I do think this still offers improvements:

- uses the standard library packages
- `embed` may improve with respect to handling compressed content in future versions
- potentially enables the web ui to serve (at least some) content compressed (?)

In order to try this run this before building the binary:
```
find web/ui/templates web/ui/static -type f -exec gzip {} \;
```
and to cleanup run
```
find web/ui/static web/ui/templates -name "*gz" -exec rm {} \; && g restore web/ui/static web/ui/templates
```

**Comment by jan--f** [comment]
> In order to try this run this before building the binary:
> 
> ```
> find web/ui/templates web/ui/static -type f -exec gzip {} \;
> ```
> 
> and to cleanup run
> 
> ```
> find web/ui/static web/ui/templates -name "*gz" -exec rm {} \; && g restore web/ui/static web/ui/templates
> ```

Note that without this step, the build should still succeed and produce a functioning binary, it will however contain the uncompressed static assets and thus be roughly 10MB bigger than needed.

**Comment by jan--f** [comment]
Closing in favor of #9719

**Pull request closed without merging**
