### PR TITLE
adjust package-json to match the correct version of the modules

### PR DESCRIPTION
**Pull request by Nexucis**
Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

### CODE REVIEW

**Comment by Nexucis** [comment]
@roidelapluie build is fixed with this PR

**Comment by juliusv** [comment]
Hmm, shouldn't this be merged into `release-2.39` first, and then back from there into main?

**Comment by Nexucis** [comment]
I have another PR to be merged on the release branch there: https://github.com/prometheus/prometheus/pull/11401

**Comment by codesome** [comment]
Closing in favour of https://github.com/prometheus/prometheus/pull/11403. I merged the PR to the release branch. So to keep the commit has same for this change, I opened this linked PR from the release branch.

**Pull request closed without merging**
