### PR TITLE
update tsdb

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <kgeorgie@redhat.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
@gouthamve metnioned that the latest tsdb fixed [this bug](https://github.com/prometheus/prometheus/issues/4108#issuecomment-387420424)  so lets updated.

**Comment by fabxc** [comment]
@krasi-georgiev could you update this to the current TSDB master?

**Comment by krasi-georgiev** [comment]
@fabxc done

**Comment by fabxc** [comment]
Thanks 👍

**Pull request merged**
