### PR TITLE
Add PuppetDB discovery plugin

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by fabxc** [comment]
Your pull requests lacks any description on what you want to contribute and why. The tests are not passing and the implementation provides no tests.

If you want us to spend time on this discussing with you, please file an issue explaining why you are missing a feature and why you think it should be implemented in the proposed way.

**Comment by raphink** [comment]
@fabxc the PR's title is kind of self explanatory: the goal is to query a PuppetDB as a discovery backend.

As for the tests, most discovery plugins lack them (ec2, azure, consul, dns, zookeeper), so it did not seem necessary to add them...

**Comment by raphink** [comment]
Btw, where is the CI status in the PR to see whether it passed the build?

**Comment by cfrantsen** [comment]
Click the red X under the commit tab to see CI status

**Comment by raphink** [comment]
Ah right. It doesn't appear down in the PR status though, weird.

**Comment by beorn7** [comment]
> As for the tests, most discovery plugins lack them (ec2, azure, consul, dns, zookeeper), so it did not seem necessary to add them...

It's actually the other way round: The pain that the missing tests have already caused has made us super cautious about future SD implementations to add.

**Comment by raphink** [comment]
@beorn7 I can understand that. That said, if the existing SD had tests, it would help as templates to add new ones, too.

**Comment by brian-brazil** [comment]
We've not accepted SD based on configuration management tools before, on the basis that it's preferable to have the tool write out the required config file/file_sd directly. Is puppet fundamentally different to say chef in this regard?

**Comment by raphink** [comment]
I'm not sure chef has an equivalent to the PuppetDB. The PuppetDB is a CMDB based on Postgresql which centralizes data from Puppet runs (facts, reports, catalogs, etc.) and provides a REST API. This makes it easy to retrieve e.g. the IP addresses of all nodes configured to run Collectd.

**Comment by brian-brazil** [comment]
That sounds very similar to what Chef provides.

**Comment by tlex** [comment]
Leaving my $0.02 here:
My team runs a Puppet infrastructure for an increasing number of servers (currently at 3k). In order to monitor our infrastructure, we are currently working at a script that generates the scrape list through queries against the PuppetDB API. Would be great to have it directly in Prometheus. It would probably push some of our customers to adopt Prometheus as well (since they wouldn't need to either have their own script or have a list for up to 2k servers that they edit manually).

**Comment by 3mbr4c3** [comment]
As part of the team @tlex mentioned, I can just agree that it would be a great benefit if PuppetDB will be part of the service discovery list.

**Comment by beorn7** [comment]
I guess we should write a blog post or something about new SD methods. Otherwise, we'll explain the same thing to everybody...

**Comment by raphink** [comment]
@tlex if you're interested, we started this in the meanwhile: https://github.com/camptocamp/prometheus-puppetdb

**Pull request closed without merging**
