### PR TITLE
Empty slice declaration via literal

### PR DESCRIPTION
**Pull request by Akiros001**

### CODE REVIEW

**Review by beorn7 — APPROVED** [review]
Personally, I tend to avoid `var` for single line declarations, but this particular case has been added to https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices (which we link in CONTRIBUTING.md). So let's stay faithful to it and merge this.

**Comment by beorn7** [comment]
@Akiros001 we need you to jump through the DCO hoop: https://github.com/prometheus/prometheus/pull/8698/checks?check_run_id=2285375991

**Review by beorn7 — CHANGES_REQUESTED** [review]
Reverting approval because of missing DCO.

**Comment by roidelapluie** [comment]
Thanks for your PR. For legal reasons, we require that all commits are signed with a [DCO](https://developercertificate.org/) before we can merge them. See [this blog post](https://www.cncf.io/blog/2016/11/08/cloud-native-software-can-trust/) for considerations around this.

This means that the last line of your commit message should read like:

`Signed-Off-By: Your Name <your@email.address>`

If you are using GitHub through the web interface, it's quickest to close this PR and open a new one with the appropriate line.

If you are using Git on the command line, it is probably quickest to amend and force push. You can do that with
````
git commit --amend --signoff
git push -f $remote $remote_branch_for_pr
````

As always, be careful when force-pushing.

**Comment by beorn7** [comment]
Closing because of lack of follow-up.

**Pull request closed without merging**
