### PR TITLE
remove template expand error from alert

### PR DESCRIPTION
**Pull request by oiooj**
We should't send template expand error message in alert.

### CODE REVIEW

**Comment by brian-brazil** [comment]
May I ask why you want to make this change? This would completely breaking alerting if there was a runtime template issue, whereas at least now the alert will get through to the alertmanager. The current behaviour seems safer overall.

**Comment by oiooj** [comment]
@brian-brazil , we wrote a bad alert rule, then we got a alert message, and some error in it.
Maybe we should ignore the alert if the template expand failed, just log it.
image

**Comment by brian-brazil** [comment]
That would result in you not getting an alert at all, and silently not sending alerts does not seem like a good idea to me.

**Comment by roidelapluie** [comment]
Yes. If you do not want to have bad alerts, I recommend you to look at unit tests https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/ when you have complex templates.

**Pull request closed without merging**
