### PR TITLE
Remove auto-generated protobuf code from codeclimate

### PR DESCRIPTION
**Pull request by beorn7**
@brancz as promised.

### CODE REVIEW

**Comment by brancz** [comment]
lgtm 👍 

I'm just confused as to why vendored code still appears in the feed and under [code](https://codeclimate.com/github/prometheus/prometheus/code?page=6). Does excluding paths only decide what goes into the grade, or can we also hide those files entirely?

**Comment by beorn7** [comment]
It might be the feed displays all historic comments, and when I added the repo, the config was not yet in place, and thus those issues got recorded in the feed. (Just speculating here.)

**Comment by brancz** [comment]
Maybe @larkinscott can solve our confusion and speculation 🙂

**Comment by larkinscott** [comment]
Thanks for pinging me about this @brancz @beorn7. I updated the .codeclimate.yml config and sent over a PR. Sorry for any confusion!

**Pull request merged**
