### PR TITLE
relabel: move tests to separate package

### PR DESCRIPTION
**Pull request by tesla59**
Move relabel package tests to a separate package relabel_test. Also rename the tests to clearly indicate what they are testing and benchmarking

### CODE REVIEW

**Comment by tesla59** [comment]
please review @machine424

**Comment by beorn7** [comment]
The renaming seems to make sense.

But what's the motivation for moving the tests into a separate package? I know the pattern exists, and some advocate it because it forces tests to only use exported parts of the package to test. But it also adds some friction, so I think there should be some motivation beyond "just follow the pattern". AFAIK we don't regularly use the pattern in the Prometheus codebase. Cases that come to mind have to do with avoiding circular package dependencies.

@machine424 maybe you have discussed this with @tesla59 in advance?

**Comment by tesla59** [comment]
@beorn7 The motivation comes for this PR https://github.com/prometheus/prometheus/pull/13999
Because promql is following the `_test` I thought it can be extended to other part as well

**Comment by beorn7** [comment]
#13999 introduced the `promql_test` package to avoid a circular dependency between packages. We should not take it as a reason to now move all tests to their separate `..._test` package.

I mean, maybe we want that, but then it should be an informed decision taken by the team. For now, I would assume the current state is the desired one and not change it.

**Comment by machine424** [comment]
Thank you for your initiatives and efforts, @tesla59.
I agree with @beorn7, I don’t think moving the tests into promql_test is necessary here.
Regarding the renaming, unless it’s really needed (the test was changed dramatically), I lean towards not changing the names to avoid losing the test’s history. If the test becomes flaky or something, we can look in the issues to check if we had that before, we can easily find threads related to it in Slack, etc. The same goes for benchmarks, we can still compare the results with the previous runs, etc.

Also, you can always start discussions on Stack or here to test the waters before opening a PR. We can also have discussions on the PRs themselves though, as you like. ;)

**Comment by beorn7** [comment]
@machine424 made a good point about not renaming tests unless there is a very compelling reason.

So let's close this PR. @tesla59, this is of course not meant to discourage you from further contributions.

**Pull request closed without merging**
