### PR TITLE
#1246 Update ui add start date

### PR DESCRIPTION
**Pull request by yamatoya**
Source: #1246 UI option to specify time for evaluation

image

* add `from` field

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
@yamatoya wouldn't  it be better like  - Graph Range, From , To , Graph Resolution

@brian-brazil are you in favour of this change?

**Comment by brian-brazil** [comment]
We have an end date and a duration already which specify this, I don't think the additional clutter adds to the UI overall.

**Comment by krasi-georgiev** [comment]
in that case can also close https://github.com/prometheus/prometheus/issues/1246

**Comment by krasi-georgiev** [comment]
@brian-brazil in that case can also close #1246

**Pull request closed without merging**
