### PR TITLE
Merge 2.3 fixes to master

### PR DESCRIPTION
**Pull request by simonpasquier**
cc @brian-brazil @krasi-georgiev 

The fix removing the security headers already exists in master as #4258 (#4259 on the release-2.3 branch) but reading the [Wiki](https://github.com/prometheus/prometheus/wiki/HOWTO-cut-a-new-release#branch-management-and-versioning-strategy), I understand that there's nothing special to do about it.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks!

All this branch messing is a bit confusing.

**Comment by grobie** [comment]
Wait, did you squash these commits @brian-brazil?? This rewrote the history, instead of merging the branch into master. This completely defeats the purpose of having branches.

**Comment by grobie** [comment]
But rebasing rewrites the history. This must not be done when merging release branches back into master, as that will duplicate every commit.

**Comment by brian-brazil** [comment]
If we want to avoid divergent branches, maybe we should work only on master.

**Comment by grobie** [comment]
We have the release branch concept established for years. Following it would remove the need for any "no more features can be merged" moratoriums and provide a clean and readable diff and history between releases.

**Pull request merged**
