### PR TITLE
Make show annotations checkbox match query history checkbox

### PR DESCRIPTION
**Pull request by jamtur01**
After removing the checkbox in #3913 the only remaining element that
looked like it was the new Show Annotations checkbox on the Alerts page.
Which in turn didn't look like the Enable query history checkout on the
graph page. So:

1. This takes the Enable query history button as canonical.
2. Updates the show annotations button code to match it.
3. Simplifies the JS for the checkbox.

Before:

screenshot 2018-03-08 11 09 55

After:

screenshot 2018-03-08 12 45 00

The enable query history checkbox

screenshot 2018-03-08 12 45 45

/cc @juliusv

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: Just needs a rebase + assets rebuild due to merge conflict.

**Comment by jamtur01** [comment]
Rebased.

**Comment by juliusv** [comment]
@jamtur01 since I merged your other PR, now this one needs to be rebased one more time :)

**Comment by jamtur01** [comment]
@juliusv Done.

**Pull request merged**
