### PR TITLE
web: add -web.route-prefix flag

### LINKED ISSUE #1191: Support for reverse proxy that changes path
I am trying to access Prometheus via the Kubernetes reverse proxy (`kubectl proxy`). The resulting URL is `http://localhost:8001/api/v1/proxy/namespaces/prod/services/prometheus/graph` which gets proxied to the path `/graph` on the Prometheus server. Problem is that the JS can not load its resources, since it tries to use  `http://localhost:8001/static/js/` instead of  `http://localhost:8001/api/v1/proxy/namespaces/prod/services/prometheus/static/js/`.

I found the `-web.external-url` flag, but it does not solve my problem. If I do `-web.external-url=/api/v1/proxy/namespaces/prod/services/prometheus/` then `http://localhost:8001/api/v1/proxy/namespaces/prod/services/prometheus/graph` does not work any more, because it would need to be `http://localhost:8001/api/v1/proxy/namespaces/prod/services/prometheus/api/v1/proxy/namespaces/prod/services/prometheus/graph`. So I can't solve the issue with the flag because it expects that the reverse proxy does not change the path, which the Kubernetes proxy does.

### PR DESCRIPTION
**Pull request by fabxc**
Fixes #1191 

@neelance @matthiasr @chancez

### CODE REVIEW

**Comment by fabxc** [comment]
The case in #1191 would respectively be fixed via `-web.external-url=/api/v1/proxy/namespaces/prod/services/prometheus/` and `web.route-prefix=`/`.
Sounds reasonable?

**Comment by matthiasr** [comment]
:+1:

**Comment by grobie** [comment]
This looks better than the older proposal using a boolean flag. :+1:

**Comment by chancez** [comment]
@fabxc Will it still have the redirect behavior? It would be nice to not redirect since it wouldn't be necessary in this setup.

**Comment by fabxc** [comment]
@chancez which redirect do you mean precisely? `-web.route-prefix` is the defined redirect, which can just be `/` for nothing.

**Comment by chancez** [comment]
I recall a redirect loop occurring when trying to set this up with the existing the external URL flag.

**Comment by fabxc** [comment]
That should be fixed

**Comment by thenayr** [comment]
This isn't working for me.

Two problems from what I can see:

`-web.external-url=/api/v1/proxy/namespaces/prod/services/prometheus/`  (or anything with no FQDN) fails validation as a "Prometheus URL". 

AND

Changing the `-web.route-prefix` to `/` causes an endless redirect loop.  

These are my current settings:

`"-web.external-url=/api/v1/proxy/namespaces/kube-system/services/prometheus/", "web.route-prefix=/"`

Fails with this:

```
level=error msg="invalid Prometheus URL: /api/v1/proxy/namespaces/kube-system/services/prometheus/"
```

**Comment by mkokho** [comment]
These settings are working for us. The difference is that we have full url, not just relative path
```
-web.external-url=http://localhost/api/v1/proxy/namespaces/prod/services/prometheus/ 
-web.route-prefix=/
```

**Comment by fabxc** [comment]
Yes, the external URL must be a full one.

Pinging @brian-brazil @juliusv on whether this was a concious decision or we can remove that requirement in future versions? Seems like a valid use case to just use the seen hostname there by default.

**Comment by thenayr** [comment]
@fabxc Yeah I would hope it would function without a root URL in there.  I'd rather not have to pass a different argument for every kubernetes cluster it ends up in. 

Thanks for looking into this.

**Comment by juliusv** [comment]
I guess the decision to require a full URL was only semi-conscious. I'm fine with changing it.

**Comment by mingfang** [comment]
I set -web.route-prefix=prometheus and the it kinda of works.
/prometheus/metrics and /prometheus/graph works.
But all the /static files are not prefixed properly.

**Comment by bitplane** [comment]
@mingfang same problem here. I've raised as #2193

**Comment by juliusv** [comment]
@mingfang @bitplane see https://github.com/prometheus/prometheus/issues/2193#issuecomment-261163937

**Pull request merged**
