### PR TITLE
Allow blank issue reports again

### PR DESCRIPTION
**Pull request by juliusv**
I frequently find myself in the situation where the standard bug issue template fields are all irrelevant for what I want to report, and then I have to first shoehorn my info into the template somehow, save the issue, edit it, and remove all the unnecessary parts. This demotivates me from filing casual issues, e.g. when I see a CI test fail. We should have a way of still filing custom issues without all the templatey bits.

### CODE REVIEW

**Review by cstyan — APPROVED** [review]

**Comment by machine424** [comment]
For bug reports, only 2 fields are mandatory (I think both of them make sense for a bug, sometimes I just put a dot in one of them), I personally just leave the other fields empty when not relevant or/and fill them later when I have more info.

**Comment by juliusv** [comment]
Yes, but even the two mandatory ones don't always make sense when I know
exactly what a bug is, and then the result is also messy to read unless I
go in and edit things again to remove all the unnecessary boilerplate. We
should really have a way around this.

**Review by machine424 — APPROVED** [review]
If it’s going to make your life easier, let’s go for it. We can always reconsider if it starts being abused.

**Comment by juliusv** [comment]
Yep, or as a middle ground, if people abuse it, we could disallow regular free-form posting again but introduce an explicit "I know what I'm doing" issue type for experts that is just one big Markdown field. For now, let's maybe just try allowing blank issue templates again.

**Pull request merged**
