### PR TITLE
Revert "Changelog: Add hyperlinks to PRs"

### PR DESCRIPTION
**Pull request by beorn7**
Reverts prometheus/prometheus#8690

We don't have to merge this now. I just want to give the discussion a place that is not an already merged PR or a closed issue.

### CODE REVIEW

**Comment by roidelapluie** [comment]
It's OK to merge this.

I am usually looking at https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md which does not render those links by default, so it felt like a user friendly improvement for me as a user, but all your concerns are valid, including the fact that all repos should be aligned.

**Comment by beorn7** [comment]
> I am usually looking at https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md which does not render those links by default,

It does for me. Have I perhaps a setting at a non-default value, or do you? (o:

**Comment by roidelapluie** [comment]
https://github.com/prometheus/prometheus/blob/f3e7921595ab72b82081b3591953a01ec2b5b2e1/CHANGELOG.md

Are you looking at the latest version with the links?

**Comment by roidelapluie** [comment]
e.g. I see no links here: https://github.com/prometheus/alertmanager/blob/master/CHANGELOG.md

**Comment by beorn7** [comment]
> Are you looking at the latest version with the links?

I am. :rofl: 

So point taken. It doesn't always work in GH context. It works on the release page (and I guess that's where it's coming from).

While I personally think we should leave it as is, I don't think it's an obvious decision. Let's get a few more opinions.

**Comment by beorn7** [comment]
OK, no further discussion happened here. We should come to a conclusion before cutting the next release.

Should we make noise about this, or just decide among the people looking at this PR?

Despite acknowledging the advantage of explicit links, I prefer the old version of just doing the `#1234` thing, mostly to keep handling the file as a pure text file easy and since the most commonly used context (the release page) renders the links fine.

**Comment by roidelapluie** [comment]
We can decide here I think. We should ping @conorevans about this too.

**Comment by conorevans** [comment]
Hey guys. I saw this but figured I'd leave the discussion to you since some of the most relevant points (e.g. consistency across your repos) were org-specific and not end-user-related. Happy to chime in here, though.

I mean it's not a hill I would die on, but I do think the `CHANGELOG` is somewhat ubiquitous (it's been around longer and is used in many repositories that don't do releases). I previously "mained" Github but now "main" Gitlab so honestly I was not aware that the markdown would render differently there. So I could use the releases page but personally I actually really dislike it. I mean look at this image, 60-70% of the `2.26.0` section is used up by download links - I personally find it very unfriendly to navigate.

releases

The only other comment I have relates back to a comment on the issue:

> This change only helps if you render the markdown outside of Github. However, if you just want to look at the unrendered markdown, this change bloats the text size and makes it much less readable.

I mean, is that particularly important? How many people are reading this in unrendered markdown? Maybe somebody (a contributor) is looking for something in the raw contents via Github (a non-standard view that has to be explicitly chosen) or in their IDE, but I mean in that case they're probably looking for something and will CTRL+F? I think almost every person reading the CHANGELOG for the sake of reading the CHANGELOG (and not for editing it, or referencing it) will be an end-user with markdown enabled -- and ultimately end-users are the main target of these CHANGELOG notes, no? I mean of course they are useful for everyone, but they're to highlight changes to folks who don't keep up with the day-to-day / week-to-week of a project and instead merely consume/upgrade it periodically.

**Comment by beorn7** [comment]
It's a trade-off, of course. For weighing the various options, we also have to consider in which situation you would actually click on the PR links. And in what situations are you not so much interested in the links but more the direct text content.

In my experience, I often look at the changelog outside of markdown rendering when I'm interested in the text content. And I usually only want to have the links when I'm looking at the release page. So the current situation makes perfect sense to me. But it might be just me.

If looking at the changelog in a browser were the dominant use case, we should actually not use markdown, but HTML directly. The fact that we use markdown is a hint that looking at the file as plain text is a common mode of consumption, and therefore I'm opposed to cluttering that mode of consumption.

**Comment by roidelapluie** [comment]
I do not buy the "If looking at the changelog in a browser were the dominant use case, we should actually not use markdown, but HTML directly." argument but the rest of the discussion makes sense.

Maybe one day GitHub will automatically render the PR links in changelog.

**Comment by roidelapluie** [comment]
based on this discussion, and because we are releasing 2.27 this week, I am merging this PR.

**Pull request merged**
