### PR TITLE
Introduce favicons

### PR DESCRIPTION
**Pull request by RichiH**
Suggestion for fixing prometheus/prometheus/issues/643

---

This change is [Reviewable](https://reviewable.io/reviews/prometheus/prometheus/1238)

### CODE REVIEW

**Comment by beorn7** [comment]
Why are all the favicons inverted (and start with `inverted-`)? Is that some kind of trick even Google isn't able to tell me about?
(Sorry for being a frontend rookie...)

**Comment by barkerd427** [comment]
I believe that indicates that the colors are inverted from the original.
Search "inverted spectrum" or "inverted colors."

**Comment by beorn7** [comment]
I know what inverted colors are. But how is that helpful?

**Comment by RichiH** [comment]
It's near to the original logo, distinct enough to be seen at a glance, and takes almost no time to produce ;)

ATM, I am going with "anything that's not utter crap is better than nothing".

**Comment by beorn7** [comment]
I still don't get it. Perhaps I'm thinking in a too complicated way…

So is this a suggestion to use an inverted logo for the server to distinguish it from the logo on prometheus.io (which could/should have a favicon in the first place..)?

But even then, why are the files called `inverted-*`? No browser will ever try to retrieve a favicon with that name…

**Comment by jimmidyson** [comment]
> No browser will ever try to retrieve a favicon with that name…

It will if that is specified as the favicon in head (`<link rel="icon" href="....">`

**Comment by RichiH** [comment]
If we agree that we want to use those favicons for now, I will simply rename them. It's an artifact from my one-liner and does not have any meaning deeper than "I forgot to rename".

**Comment by beorn7** [comment]
I see... So this is really just for reviewing the design, not meant as something that would already work as a favicon if merged...

I leave the review to those that are not as design-illiterate as I am.

**Comment by sdurrheimer** [comment]
Prometheus should have the original logo as a favicon. I would suggest other colors for alertmanager, promdash etc.

**Comment by mdlayher** [comment]
Leaving a comment to try and nudge this one along.  Seems like a totally reasonable first step (or perhaps just using the actual logo).

Anything is better than the blank favicon prometheus uses now, in my opinion.

**Comment by mattbostock** [comment]
IMHO, the design looks fine, though I'd question whether we need all the varieties and if a simple 'favicon.ico' file would be sufficient.

**Comment by mdlayher** [comment]
This PR is obsolete now because of #2305 , yes?

**Comment by fabxc** [comment]
Yes, thanks

**Pull request closed without merging**
