### PR TITLE
Fix various misspellings of "shepherd" in the release docs

### PR DESCRIPTION
**Pull request by juliusv**
Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
Travis tests fail for unrelated reason:

```
go: verifying github.com/hashicorp/go-rootcerts@v0.0.0-20160503143440-6bb64b370b90: checksum mismatch
	downloaded: h1:VBj0QYQ0u2MCJzBfeYXGexnAl17GsH1yidnoxCqqD9E=
	go.sum:     h1:9HVkPxOpo+yO93Ah4yrO67d/qh0fbLLWbKqhYjyHq9A=
```

**Comment by codesome** [comment]
:+1:, and yes, the test is failing everywhere in the same way.

**Comment by simonpasquier** [comment]
Re the test failure, I'll send a patch. This is due to a change in the latest Go 1.11 version (see https://github.com/golang/go/issues/29278#issuecomment-447537558).

**Comment by simonpasquier** [comment]
Travis passes now. :+1:

**Pull request merged**
