### PR TITLE
Fix storage/local tests for 32-bit systems

### PR DESCRIPTION
**Pull request by chkno**

### CODE REVIEW

**Comment by fabxc** [comment]
Cool, thanks! :+1:

**Comment by juliusv** [comment]
Oh, interesting, thanks. I would have incorrectly assumed that Go would automatically infer a 64-bit integer type for a >32-bit constant.

:+1:

**Comment by fabxc** [comment]
@juliusv was wondering about the same thing. If not explicitly typed the type is implied on assignment/usage.

**Comment by chkno** [comment]
The variadic ...interface{} argument to Errorf seems to try to convert it to an int rather than an int64.  http://play.golang.org/p/u2WWycGJuL

**Pull request merged**
