### PR TITLE
Revert /graph changes.

### PR DESCRIPTION
**Pull request by beorn7**
@grandbora 
@matthiasr (for sanity checking with somebody who sits next to me)

As described in the commits, this is the only way I see to get to a state with all the changes but not the /graph changes. This will now be released as v1.1.

Only then, we will create a release-1.1 branch, and then we can revert this revert in master.

However, we cannot just do this revert in the release-1.1 branch only because then merges from release-1.1 into master will revert the /graph changes in master.

I hope you cane follow me…

### CODE REVIEW

**Comment by grandbora** [comment]
This revert looks good. Many apologies for this... I'll put this back with backward compatibility as soon as possible.

**Comment by beorn7** [comment]
I'm also running a canary server with this. Looks good so far.

**Comment by beorn7** [comment]
I'll now nag @matthiasr in person.

**Comment by beorn7** [comment]
:+1: from @matthiasr

**Comment by grandbora** [comment]
Hey I made https://xkcd.com/1172/ to fix backward compatibility.

**Pull request merged**
