### PR TITLE
Support HuaWei Cloud Discovery

### PR DESCRIPTION
**Pull request by zbbkeepgoing**
Support instance discovery in huawei cloud.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thank you for this.

Some questions/remarks before I deep dive this:

- Is it possible to use ECS with our plain openstack SD instead of having a dedicated SD?
- Could we rename the service discovery to `huawei_cloud_ecs` or `huaweicloud_ecs` ?

**Comment by zbbkeepgoing** [comment]
> Thank you for this.
> 
> Some questions/remarks before I deep dive this:
> 
> * Is it possible to use ECS with our plain openstack SD instead of having a dedicated SD?

**Yes, it can be confirmed that Huawei cloud can be implemented through plain openstack according to password (just happy path). But there are some features in Huawei cloud SDK. For example, plain openstack does not support aksk. Many people prefer aksk to passowrd when they use it.**

> * Could we rename the service discovery to `huawei_cloud_ecs` or `huaweicloud_ecs` ?

**Of course**

**Comment by zbbkeepgoing** [comment]
@roidelapluie Hi, Juline. Have other ideas?

**Comment by roidelapluie** [comment]
Hello,

Adding new service discoveries is not trivial. In the review process I always try it against the service discovery provider. This might take time. In this specific case, I will also need to see if adding aksk authentication to the openstack SD could work.

**Comment by zbbkeepgoing** [comment]
> Hello,
> 
> Adding new service discoveries is not trivial. In the review process I always try it against the service discovery provider. This might take time. In this specific case, I will also need to see if adding aksk authentication to the openstack SD could work.

Sounds good and rigorous. Thank you

**Comment by binbinzou** [comment]
Is there any progress on this PR and when will it be merged?

**Comment by guojing013214** [comment]
We have customers on Huaweicloud and we are hunger for this.

**Comment by zbbkeepgoing** [comment]
> This is look good to me, @zbbkeepgoing Cloud you give resources from Huawei to test this.

I'm sorry, but currently my work does not involve that specific area anymore. Therefore, I don't have the resources on hand. However, prior to this, it has been tested and proven to be functional. We have already used it in some production environments.

**Comment by beorn7** [comment]
Hello from the bug scrub.

Thanks for the responses. However, we still need dedicated maintainers for this to merge it, and we also need a way to test this to avoid regressions. We'll close this PR until we have those.

**Pull request closed without merging**
