### PR TITLE
Enable perfsprint linter and fix up code

### PR DESCRIPTION
**Pull request by alexandear**
This PR enables perfsprint linter and fixes its issues.

Changes that improves both readability and performance are:
- replace `fmt.Sprintf("%d", x)`, `fmt.Sprint(x)`  with `strconv.Itoa(x)` for int values;
- replace `fmt.Sprintf("%t", b)` with `strconv.FormatBool(b)` for bool values.

### CODE REVIEW

**Comment by machine424** [comment]
Hello,
Any reason why this was closed?

**Comment by alexandear** [comment]
@machine424 Hello,

Apologies for any inconvenience caused. The pull request was closed because it's been open for quite a long period, specifically six months, without any reviews or further actions taken. If the information within the pull request is still pertinent and relevant, I can to reopen it.

**Comment by machine424** [comment]
Yes, I think we can give this linter a try, it can help avoid regressions after changes like https://github.com/prometheus/prometheus/pull/13669. Thanks.


(Maybe there is a glitch or sth, but I see that the PR was opened in 29/11/2023 and closed on the same day)

**Comment by alexandear** [comment]
@machine424 I created a new PR https://github.com/prometheus/prometheus/pull/14091, because it's not possible to re-open this due to the deleted fork.

> (Maybe there is a glitch or sth, but I see that the PR was opened in 29/11/2023 and closed on the same day)

Yes, you're correct. I got confused and provided the wrong reason for closing this PR. The correct reason is as follows: `perfsprint` was first introduced in [golangci-lint v1.55.0](https://golangci-lint.run/usage/linters/), but 6 months ago the Prometheus repo was using [v1.54.2](https://github.com/alexandear/prometheus/blob/0efb647f59cbec7f5f3c571803f9a00b602ebcd3/.github/workflows/ci.yml#L154). Therefore, I chose not to upgrade the golangci-lint version due to the minor changes.

**Pull request closed without merging**
