### PR TITLE
doc: Mark `mad_over_time` as experimental

### PR DESCRIPTION
**Pull request by beorn7**
We forgot to do that in
https://github.com/prometheus/prometheus/pull/13059

@zenador could you review this?

### CODE REVIEW

**Comment by hadjiski** [comment]
@beorn7 @zenador I am a bit confused about [the documentation around the `mad_over_time`](https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time).
It states that it is only available after enabling the `promql-experimental-functions` feature, which I dont have:
image
But still I see the function and I can use it, how come? I am happy though ;)

**Comment by beorn7** [comment]
It is visible in the autocomplete feature (because it is hard to make that dependent on feature flags (but PRs welcome ;)). But if you actually try it, you'll get the following:

image

**Comment by hadjiski** [comment]
Thanks, I understand, though for me it still works for some reason

**Comment by beorn7** [comment]
If you could get to the bottom of that, that would be great.

**Comment by hadjiski** [comment]
You are right, on prometheus I get the error, I was trying it out on Victoriametrics, where it wasn't so obvious that it is not the prometheus input field. Sorry about the confusion

**Pull request merged**
