### PR TITLE
Add debounce when changing range

### LINKED ISSUE #406: Debounce timerange setting changes
After pressing any of the buttons that cause timerange changes, we should wait a short amount of time before updating the graph. That way, if the user presses the button multiple times, we don't load every intermediate result immediately.

### PR DESCRIPTION
**Pull request by biglovisa**
Fixes #406

Wraps all functions that change range in a debounce function.

### CODE REVIEW

**Comment by lovisas** [comment]
@Conorbro would you be able to review this? I took a different approach than suggested in the related issue so that it wouldn't slow down the page.

**Comment by simonpasquier** [comment]
@biglovisa can you rebase on master?

**Comment by biglovisa** [comment]
I will open up a new PR for this instead, I don't have access to this fork any longer.

**Comment by biglovisa** [comment]
@simonpasquier new PR is up on #4495

**Pull request closed without merging**
