### PR TITLE
improve pkg/pool: use binary search to locate bucket

### PR DESCRIPTION
**Pull request by damnever**
@brian-brazil

### CODE REVIEW

**Comment by brian-brazil** [comment]
Do you have benchmarks for this? I'd expect binary search to be slower with the small number of buckets we use given branch misprediction costs. The number of calls we make to this is also low enough (at most once per scrape) that the complexity probably isn't worth it.

**Comment by damnever** [comment]
Yes, you are right, no big improvement but the complexity seems ok to me. 

I saw this line and I think it made a little improvement  😅 
https://github.com/prometheus/prometheus/blob/fbe960f2c1ad9d6f5fe2f267d2559bf7ecfab6df/scrape/scrape.go#L239

Anyway, I leave it open for you..

**Comment by brian-brazil** [comment]
Do you have benchmarks for the improvement?

**Comment by damnever** [comment]
No benchmarks for the code path.

**Pull request closed without merging**
