### PR TITLE
Do not stop scrapes in progress during reload

### PR DESCRIPTION
**Pull request by roidelapluie**
See #7097

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
@brian-brazil It is going to be difficult to test this one but I have tested it locally. I can reproduce the issue and see that this PR fixes it.

prometheus.yml:

```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    sample_limit: 10000

    file_sd_configs:
      - files: [all.yml]
```

all.yml https://gist.github.com/roidelapluie/2b0a0e30b66443741cd5b26eb07f9e66

**Comment by roidelapluie** [comment]
@brian-brazil I am torn on this one.

I'd like to consider hard-cutting the scrape but skipping the stale markers and the registration of the error in the UI.

This PR would slow down reloads a lot. I could not fine a release of prometheus which would act differently, so it is probably like this for a long time.

**Comment by brian-brazil** [comment]
Creating a goroutine per scrape does not seem wise. I also think this is a bit simpler, shouldn't it be the parentCtx that we're passing into the scrape?

**Comment by brian-brazil** [comment]
That looks about right, can you add a unittest? Triggering the cancel from inside the scrape should do it.

**Comment by roidelapluie** [comment]
> That looks about right, can you add a unittest? Triggering the cancel from inside the scrape should do it.

I have adapted the current test.

The modified test fails on master with:

--- FAIL: TestScrapeLoopStop (0.03s)                                 
    scrape_test.go:582: Expected at least 3 scrapes with 6 samples each, got 17 samples

On master we indeed get 17 samples instead of 18 due to the failed scrape.

**Comment by brian-brazil** [comment]
:+1:

**Pull request merged**
