### PR TITLE
Cut v1.3.0-beta.0

### PR DESCRIPTION
**Pull request by brancz**
This is a breaking change to the Kubernetes service discovery. This is ok as the Kubernetes SD is in beta status. It requires a configuration change. See prometheus/docs#601 for documentation on the configuration.

@brian-brazil @fabxc @juliusv @grobie @beorn7

### CODE REVIEW

**Comment by brancz** [comment]
I guess we'll wait for https://github.com/prometheus/prometheus/pull/2078#issuecomment-254539237

**Comment by beorn7** [comment]
Yes.

Otherwise, this looks good to me.

**Comment by beorn7** [comment]
Fix is in . Since this is only a beta version, let's go with that.

Perhaps rebase this on top of the fix to avoid confusion.

:+1:

**Comment by brian-brazil** [comment]
Can we get #2096 in also as it's a bugfix?

**Comment by beorn7** [comment]
Yes, please.

Feel free to merge #2096 .

**Comment by brancz** [comment]
Will rebase tomorrow, then we'll do the release :)

**Comment by brancz** [comment]
Rebased and updated the changelog. PTAL @beorn7 @brian-brazil @fabxc

**Comment by fabxc** [comment]
👍

**Comment by beorn7** [comment]
:+1:

**Pull request merged**
