### PR TITLE
add ssl certificats as a volume

### PR DESCRIPTION
**Pull request by devx**
Fixes issue #911, one can pass a volume, to pass certificates.

### CODE REVIEW

**Comment by fabxc** [comment]
I'm not an expert for Dockerfiles, but why `/etcd/ssl/certificates`? That doesn't seem to be a well-known path at all.
Wouldn't the general approach be for people to take our Dockerfile as a base and add their certs on top through their own Dockerfile?

**Comment by jimmidyson** [comment]
Yes this does nothing other than declare that as a volume. If you want to mount custom certificates then you would need to use `-v ...` with your Docker run command.

**Comment by devx** [comment]
By adding the certificates as a volume it makes it possible for me to pass my own certificates, with out having to create a new image.  This is much cleaner than having to create new image just to add my certificates.  If you need certificates changes are that it will be easier for you to just create an image that has your certificates and just mount that at run time.  

For example if I'm using coreos and I just want to use the systems CA certificates I can just pass that at run time like this:
```
docker run -d --name prometheus-server -p 9090:9090 -v /etc/ssl/certs/:/etcd/ssl/certificates -v $PWD/prometheus.conf:/prometheus.conf prom/prometheus -config.file=/prometheus.conf
```

Alternatively you can create a certificates volume and just mount that at run time, you can read more about data volumes here: https://docs.docker.com/engine/userguide/dockervolumes/

**Comment by sdurrheimer** [comment]
You can bind-mount any volume at runtime, it's not necessary to declare it in the Dockerfile.
By declaring it in the Dockerfile, people have no way to prevent this from being a volume.

**Comment by fabxc** [comment]
I think we can close this then.

**Pull request closed without merging**
