### PR TITLE
Clamp functions should ignore native histograms

### PR DESCRIPTION
**Pull request by jhesketh**
As per the documentation, native histograms are skipped. This is in line with other `simpleFunc`'s.

### CODE REVIEW

**Review by Tusenka — APPROVED** [review]

**Review by beorn7 — APPROVED** [review]
Thank you very much.

/cc @NeerajGartia21 (who is also working on fixing PromQL for native histograms)

**Comment by beorn7** [comment]
@jhesketh FYI it might be a good idea to @-mention me on native histogram related PRs. As NH relevant code changes happen all over the place, there is no auto-assign to me.

**Comment by krajorama** [comment]
Also you can mention me :) By the way interestingly the clamp function may make some sense for native histograms, but it's feature request at this point. Clamp => all observations within the interval.

**Comment by beorn7** [comment]
Isn't that what we want to accomplish with https://github.com/prometheus/prometheus/issues/14651 ? (which, BTW, we want to implement as a binop so we can use vectors for the limits, while the `clamp` function only accepts scalars).

**Comment by krajorama** [comment]
> Isn't that what we want to accomplish with #14651 ? (which, BTW, we want to implement as a binop so we can use vectors for the limits, while the `clamp` function only accepts scalars).

Nope, trim alters the samples, clamp filters the samples as far as I understand

**Comment by krajorama** [comment]
you're right, I misunderstood the function

**Pull request merged**
