### PR TITLE
Added formal proposal process.

### PR DESCRIPTION
**Pull request by bwplotka**
So far this idea was a bit rejected, but I believe it's very powerful if done correctly. Maybe exposing all details will show value for those who were sceptical so far.

Proposing a soft, clear process that is already used in many projects (kubernetes, Thanos, openshift etc). I really think it's worth our time!

Please review and give feedback, I will put that as a topic for next dev summit.

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Did you see https://prometheus.io/docs/introduction/design-doc/ ?

**Comment by roidelapluie** [comment]
I think you should review https://prometheus.io/docs/introduction/design-doc/ and integrate it in your proposal somehow.

**Comment by beorn7** [comment]
Perhaps we can try a lightweight process first, along those lines:

1. Test the waters on prometheus-developers@ and/or #prometheus-dev. Optionally, put it on the agenda of the dev-summit.
2. Write a design doc and add it to https://prometheus.io/docs/introduction/design-doc/ .
3. Respond to reviewers.
4. If lazy consensus is established among prometheus-team, you are done. On to implementation!
5. If consensus is unclear, the proposal will be discussed at the dev-summit.
6. If there is still no consensus, prometheus-team members can call a vote as usual.

In any case, this whole proposal of a proposal process is a design doc by itself and should be added to https://prometheus.io/docs/introduction/design-doc/ . I don't think any of this (except the link from CONTRIBUTING.md) should live in prometheus/prometheus because it applies to the project as a whole.

**Comment by bwplotka** [comment]
> I think you could review https://prometheus.io/docs/introduction/design-doc/ and integrate it in your proposal somehow. This is our current attempt at improving this already.

Lol,  I haven't seen it. Nice. That's why I think we need to make sure the process is defined better ;p

**Comment by bwplotka** [comment]
Nice, I think I would be fine with that too.

> Write a design doc and add it to https://prometheus.io/docs/introduction/design-doc/ .

Do we care about template, tool, format e.g google doc / markdown?

**Comment by roidelapluie** [comment]
> > I think you could review https://prometheus.io/docs/introduction/design-doc/ and integrate it in your proposal somehow. This is our current attempt at improving this already.
> 
> Lol, I haven't seen it. Nice. That's why I think we need to make sure the process is defined better ;p

This was discussed in the last dev summit, that is why I made that page :)

**Comment by bwplotka** [comment]
Why maintaining this manually if we can have users just propose PRs with
consistent proposal document in a specific place? 🤔

Kind Regards,
Bartek Płotka ***@***.***)

**Comment by bwplotka** [comment]
Thanks everyone for feedback on the Dev Summit. We got an idea for experimenting with proposal process further. PR to docs coming.

**Comment by RichiH** [comment]
Cross-ref: https://docs.google.com/document/d/11LC3wJcVk00l8w5P3oLQ-m3Y37iom6INAMEu2ZAGIIE/edit#heading=h.omrxayfajpwh

**Pull request closed without merging**
