### PR TITLE
Improve DNS error reporting and update to current miekg/dns

### PR DESCRIPTION
**Pull request by beorn7**
We hit the 64kiB limit at SC on Monday, and the error message was so misleading that a major treasure hunt ensued.

While investigating, I incorporated the update to the current miekg/dns, inspired by @discordianfish 

@brian-brazil @fabxc @matthiasr whoever…

### CODE REVIEW

**Comment by beorn7** [comment]
Re-fixes #360.

**Comment by discordianfish** [comment]
LGTM - but having some integration tests for this would be useful.

BTW: I'm pretty sure I ran into the 64k limit back then already and up till today I'm surprised this limit so barely known.. I still haven't found anything stating that "64k is max". IIRC this limit was due to the limit of a pointer or something.

**Comment by beorn7** [comment]
@discordianfish Surely integration tests would be great. If you have something up your sleeves, you'd make us all very happy.

There is a 2byte field for the payload size in DNS, so more than 64k cannot be expressed.

**Comment by beorn7** [comment]
@brian-brazil Does this look good to you? With this in, I could cut 1.2.3

**Comment by brian-brazil** [comment]
:+1:

**Comment by beorn7** [comment]
Yes.

To be clear: The existing implementation had worked alright. Just that it said "No servers could be reached" instead of "truncated despite using TCP".

**Pull request merged**
