### PR TITLE
Add UI warning for time drift >30 seconds

### PR DESCRIPTION
**Pull request by BasPH**
Experienced time drift a couple a times while working with Prometheus in Docker on MacOS (Docker time is frozen while sleeping and not synced afterwards).

This change displays a warning on the Graph page if time drift is >30 seconds (see https://github.com/prometheus/prometheus/issues/3059).

image

### CODE REVIEW

**Comment by fabxc** [comment]
That's actually really neat. I experience that quite often recently.
Can we just give a precise number rather than `>30`? Maybe a clearer description of what "time drift" actually means would be good too and picking a yellow for warnings rather than red.

**Comment by fabxc** [comment]
That's actually really neat. I experience that quite often recently.
Can we just give a precise number rather than `>30`? Maybe a clearer description of what "time drift" actually means would be good too and picking a yellow for warnings rather than red.

**Comment by BasPH** [comment]
Agree, I'll change it to yellow color and I think 30 seconds is already quite long. We could display a warning if the drift is >5 seconds with the exact time drift in seconds or milliseconds?

How about this text? "Detected XXX.XXX seconds time difference between your browser and the server. Prometheus relies on accurate time and time drift might cause anomalies in query results."

**Comment by grobie** [comment]
Not sure about anomalies, maybe "... might cause unexpected query results."? SGTM besides that. Thanks!

**Comment by BasPH** [comment]
New warning message:
image

**Comment by juliusv** [comment]
This is great, thanks. We have seen this problem so frequently as the underlying cause in user query issues. Latest one from today: https://twitter.com/wasntbornaninja/status/917994357512441856

I like it as it is now, with the exception that maybe 5 seconds is a bit too sensitive? I mean, not sure if everyone runs NTP on both the server and browser machine, so the original 30 seconds sound better? Other opinions?

**Comment by fabxc** [comment]
Yes, I'd still only show it after a threshold, but then make the message accurate regardless.

**Comment by BasPH** [comment]
Maybe 5 seconds is a bit too much :) 30 seconds then?

**Comment by brian-brazil** [comment]
30s sounds good to me.

**Comment by fabxc** [comment]
Can you run `make assets` and commit the changes?

**Pull request merged**
