### PR TITLE
Add some IDE auto generated files to gitignore

### PR DESCRIPTION
**Pull request by RainbowMango**
Signed-off-by: RainbowMango <renhongcai@huawei.com>

Minor change, just adds some paths/files to .gitignore file.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. We recommend putting these in your global git configuration, rather than each of our repositories gradually growing a list of all the IDEs out there.

**Comment by roidelapluie** [comment]
If you don't want that in your global git config, you can also put it in your `.git/info/exclude` in the prometheus repo.

**Comment by RainbowMango** [comment]
Cool! Let me have a try.  Thanks!

**Comment by brian-brazil** [comment]
We looked at this in the bug scrub and it appears to be resolved, so closing.

**Pull request closed without merging**
