### PR TITLE
React UI: Send cookies on fetch() on older browsers

### PR DESCRIPTION
**Pull request by juliusv**
Fixes https://github.com/prometheus/prometheus/issues/6428

Signed-off-by: Julius Volz <julius.volz@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
@simonpasquier Do you have one of those older browsers lying around to test this?

**Comment by simonpasquier** [comment]
I don't have one but I can ask the person that reported the issue originally.

**Comment by juliusv** [comment]
@simonpasquier That'd be cool! Also fixed the tests.

**Comment by juliusv** [comment]
Rebased on master.

@simonpasquier Any news here from users, or should we just merge it?

**Comment by simonpasquier** [comment]
No news yet. I think it's fine to merge as-is.

**Comment by juliusv** [comment]
Ok thanks, merging...

**Pull request merged**
