### PR TITLE
remote-write: slow down retries to avoid DDOS

### PR DESCRIPTION
**Pull request by bboreham**
Increase the default max retry time from 100ms to 5 seconds.

Remote write calls are retried after a recoverable error such as the back-end returning 500. Prometheus waits the minimum time and retries, then doubles the wait on each subsequent retry until the maximum is reached.

If some data is still getting through, remote-write will also increase shards, and the default maximum shards is 200.
200 shards sending every 100ms is 20 calls per second, to a back-end that is already in trouble. If you have multiple such Prometheus sending to your back-end, it's now a DDOS.

5 seconds was chosen to match the default BatchSendDeadline: if we can afford to wait that long for no response, then we can wait the same time to retry. We will reach 5 seconds after 9 successive failures.

### CODE REVIEW

**Comment by bboreham** [comment]
CI failures look like this; I don't think it's related.
```
=== RUN   TestWALReplay
    db_test.go:363: 
        	Error Trace:	db_test.go:363
        	            				testing.go:912
        	            				testing.go:1049
        	            				testing.go:1253
        	Error:      	Received unexpected error:
        	            	remove C:\Users\circleci\AppData\Local\Temp\TestWALReplay539615288\wal\00000000: The process cannot access the file because it is being used by another process.
        	Test:       	TestWALReplay
--- FAIL: TestWALReplay (0.04s)
FAIL
FAIL	github.com/prometheus/prometheus/tsdb/agent	2.068s
```

**Comment by cstyan** [comment]
Yeah failure doesn't appear to be related. We have identical failures on master at the moment.

**Comment by cstyan** [comment]
@bboreham can you also ensure docs are updated? At least `docs/configuration/configuration.md` needs an update.

**Comment by bboreham** [comment]
I updated docs/configuration/configuration.md; I think there is a "tuning guide" somewhere but not in this repo?
Any other suggestions where to update docs?

**Comment by cstyan** [comment]
I think that file might be it. IIRC everything else is in blog posts. I will take a look today.

**Comment by cstyan** [comment]
Merging, windows CI failures are related to the merging of the grafana agent but are fixed in master.

**Pull request merged**
