### PR TITLE
tsdb: sort checkpoints by segment number

### PR DESCRIPTION
**Pull request by zhulongcheng**
Updates #6979

### CODE REVIEW

**Comment by brian-brazil** [comment]
This only covers checkpoints, segments need fixing too.

**Comment by zhulongcheng** [comment]
> This only covers checkpoints, segments need fixing too.

WAL segments have fixed by `listSegments `:
https://github.com/prometheus/prometheus/blob/4d6f9b75e230465443391ca76a4182b130eb99e9/tsdb/wal/wal.go#L761

**Comment by brian-brazil** [comment]
:+1: 

So it is.

**Comment by zhulongcheng** [comment]
thanks @cstyan 

need `FileInfo`  to know if it is a dir here.

do you think it is better to refactor `fileutil.Readdir` in a new single PR?

**Pull request merged**
