### PR TITLE
Replay m-map chunks irrespective of WAL

### PR DESCRIPTION
**Pull request by codesome**
We should always replay m-map chunks as that is something unavoidable, unlike WAL.

/cc @beorn7, would be nice to get it in 2.20, its a tiny change

### CODE REVIEW

**Comment by beorn7** [comment]
Will merge on green.

**Comment by beorn7** [comment]
Note: The problem solved here can only be exposed by using TSDB as a library. In the way it is used within Prometheus, `h.wal` can ever be `nil`.

**Comment by roidelapluie** [comment]
Yes, BUT the extra log line is really great.

**Comment by roidelapluie** [comment]
Should L710 be adapted to say: `WAL and memory chunks replay....` ? or should we reset start after playing the mmap chunks?

**Comment by codesome** [comment]
I added the extra log line as that marks the end of the replay, so thought of keeping a single log at the end.
We could log time taken by mmap, checkpoint and WAL replay in the last log line.

**Comment by codesome** [comment]
I modified the last log line to be `WAL and on-disk memory mappable chunks replay completed`

**Comment by roidelapluie** [comment]
What I do not like is that I have a lot of time before the WAL replay starts - or at least that it what it looks like. Would love a log line after the in memory replay stops.

**Comment by roidelapluie** [comment]
Especially since WAL replay is quite verbose, while mmap chunk replay is completely silent.

**Comment by codesome** [comment]
I have added more logs. Also showing the time taken to replay each component (mmap chunks, checkpoint, and the WAL), which is useful.

**Pull request merged**
