### PR TITLE
Update javascript dependencies

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Cc @juliusv @SuperQ

**Comment by juliusv** [comment]
:+1:

**Comment by SuperQ** [comment]
We should also do a round of updating the pinning in `package.json`.
```
Package                           Current  Wanted   Latest   Package Type    URL                                                                  
@fortawesome/fontawesome-svg-core 1.2.32   1.2.34   1.2.34   dependencies    https://fontawesome.com                                              
@fortawesome/free-solid-svg-icons 5.15.1   5.15.2   5.15.2   dependencies    https://fontawesome.com                                              
@testing-library/react-hooks      3.7.0    3.7.0    5.0.3    dependencies    https://github.com/testing-library/react-hooks-testing-library#readme
@types/jest                       26.0.19  26.0.20  26.0.20  dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@types/node                       12.19.11 12.19.16 14.14.25 dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@types/reach__router              1.3.6    1.3.7    1.3.7    dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@types/react                      16.14.2  16.14.3  17.0.1   dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@types/react-copy-to-clipboard    4.3.0    4.3.0    5.0.0    dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@types/react-dom                  16.9.10  16.9.10  17.0.0   dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@types/react-resize-detector      4.2.0    4.2.0    5.0.0    dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@types/sanitize-html              1.27.0   1.27.1   1.27.1   dependencies    https://github.com/DefinitelyTyped/DefinitelyTyped.git               
@typescript-eslint/eslint-plugin  2.34.0   2.34.0   4.15.0   devDependencies https://github.com/typescript-eslint/typescript-eslint#readme        
@typescript-eslint/parser         2.34.0   2.34.0   4.15.0   devDependencies https://github.com/typescript-eslint/typescript-eslint#readme        
bootstrap                         4.5.3    4.6.0    4.6.0    dependencies    https://getbootstrap.com/                                            
downshift                         3.4.8    3.4.8    6.1.0    dependencies    https://downshift-js.com                                             
enzyme-adapter-react-16           1.15.5   1.15.6   1.15.6   devDependencies https://enzymejs.github.io/enzyme/                                   
eslint                            6.8.0    6.8.0    7.19.0   devDependencies https://eslint.org                                                   
eslint-config-prettier            6.15.0   6.15.0   7.2.0    devDependencies https://github.com/prettier/eslint-config-prettier#readme            
eslint-config-react-app           5.2.1    5.2.1    6.0.0    devDependencies https://github.com/facebook/create-react-app#readme                  
eslint-plugin-flowtype            4.7.0    4.7.0    5.2.0    devDependencies https://github.com/gajus/eslint-plugin-flowtype#readme               
eslint-plugin-prettier            3.3.0    3.3.1    3.3.1    devDependencies https://github.com/prettier/eslint-plugin-prettier#readme            
eslint-plugin-react               7.21.5   7.22.0   7.22.0   devDependencies https://github.com/yannickcr/eslint-plugin-react                     
eslint-plugin-react-hooks         2.5.1    2.5.1    4.2.0    devDependencies https://reactjs.org/                                                 
moment-timezone                   0.5.32   0.5.33   0.5.33   dependencies    http://momentjs.com/timezone/                                        
prettier                          1.19.1   1.19.1   2.2.1    devDependencies https://prettier.io                                                  
react                             16.14.0  16.14.0  17.0.1   dependencies    https://reactjs.org/                                                 
react-copy-to-clipboard           5.0.2    5.0.3    5.0.3    dependencies    https://github.com/nkbt/react-copy-to-clipboard                      
react-dom                         16.14.0  16.14.0  17.0.1   dependencies    https://reactjs.org/                                                 
react-resize-detector             5.2.0    5.2.0    6.5.0    dependencies    https://github.com/maslianok/react-resize-detector                   
react-scripts                     3.4.3    3.4.3    4.0.2    dependencies    https://github.com/facebook/create-react-app#readme                  
react-test-renderer               16.14.0  16.14.0  17.0.1   dependencies    https://reactjs.org/                                                 
reactstrap                        8.8.1    8.9.0    8.9.0    dependencies    https://github.com/reactstrap/reactstrap#readme                      
sanitize-html                     1.27.5   1.27.5   2.3.2    dependencies    https://github.com/apostrophecms/sanitize-html#readme                
sinon                             9.2.2    9.2.4    9.2.4    devDependencies https://sinonjs.org/                                                 
typescript                        3.9.7    3.9.8    4.1.4    dependencies    https://www.typescriptlang.org/                                      
```

**Review by SuperQ — APPROVED** [review]
LGTM

**Pull request merged**
