### PR TITLE
codemirror-promql: add method to fetch flags in prometheus client

### PR DESCRIPTION
**Pull request by Nexucis**
I'm just adding a new method `flags` in the prometheus client of `codemirror-promql`.
That should help once the feature flag of the native histogram is defined. Based on the value of the flag, it will filter the list of the functions autocompleted.

/cc @beorn7 @codesome  

Signed-off-by: Augustin Husson <husson.augustin@gmail.com>

### CODE REVIEW

**Comment by juliusv** [comment]
Passing in all Prometheus flags seems like a very unexplicit way of affecting the behavior of this library, similar to attaching bags of unstructured values to a context. I think it'd be much better to only pass in specific explicit configuration values. This is similar to how we also do not directly read any flag values on the Go side outside of the `main` function, we just use them in `main` to configure things and then they aren't touched again.

**Comment by Nexucis** [comment]
well here it's just the code of the client. For the moment it doesn't affect the lib.

My initial idea was to propose two ways to activate the native histogram:
* based on the value of the flag coming from the endpoint /api/v1/status/flags. Like that the lib is automatically configured based on the Prometheus configuration
* based on a manual config. It can be useful in case the lib is not connected to a remote Prometheus server

So maybe instead of returning the full list of flag, the method could return just the value of the flag passed as a parameter. Would it be better @juliusv ?

**Comment by juliusv** [comment]
Ah sorry, I didn't look correctly yesterday, was too tired :/ Yeah, just adding a method like that seems fine for now for probing a Prometheus endpoint from the outside later. I remember there was also the idea to add an HTTP API to expose just the feature flags (or supported features) at some point, which would be even better, but that doesn't exist yet.

**Comment by juliusv** [comment]
:+1:

**Pull request merged**
