### PR TITLE
Fix race condition when updating lastSeriesID during loading chunk snapshot

### PR DESCRIPTION
**Pull request by damnever**

### CODE REVIEW

**Review by codesome — APPROVED** [review]
Nice catch!

**Comment by codesome** [comment]
Can you please fix the DCO? Thanks!

**Comment by roidelapluie** [comment]
What is the impact of this pull request? Should it have a test?

**Comment by damnever** [comment]
@codesome DCO fixed

@roidelapluie `lastSeriesID` is used to generate new id for new series, the problem is this race condition may cause `lastSeriesID` less than the maximum we know, thus multiple different series may get same id.

**Comment by roidelapluie** [comment]
I think a test is relevant. I also  wonder what are the chances that this creates an infinite loop in the wild.

**Comment by damnever** [comment]
Maybe we should do some checks at the runtime since this kind of issue is severe. 

> I also wonder what are the chances that this creates an infinite loop in the wild.

I don't think this is an issue since the operation is fast and the runtime shouldn't schedule it away if we are in the CAS loop.

**Pull request merged**
