### PR TITLE
web: display job label in targets page

### PR DESCRIPTION
**Pull request by simonpasquier**
#4526 incidentally changed the layout of the targets page as targets are now grouped by scrape configurations instead of jobs (see https://github.com/prometheus/prometheus/pull/4526/files#diff-73cbd2009b0e4f156e8ca0f47e95b016L677). From discussions on IRC with @beorn7 and @brian-brazil, this isn't a bad thing but the `job` label shouldn't be filtered anymore.

cc @brancz

### CODE REVIEW

**Comment by simonpasquier** [comment]
After the change:

image

**Comment by brian-brazil** [comment]
Are you sure that's the right image? There's no job label there.

**Comment by simonpasquier** [comment]
@brian-brazil oops my bad! I've updated the comment.

**Comment by brian-brazil** [comment]
:+1:

**Comment by brancz** [comment]
lgtm :+1:

**Pull request merged**
