### PR TITLE
Remove closing of Consul SD targetgroup channel

### PR DESCRIPTION
**Pull request by juliusv**
Because target providers are now stopped via a context, this is no
longer needed and has actually caused a crash bug, see
https://github.com/prometheus/prometheus/pull/2201

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc Beware, I have no Consul to test this against...

**Comment by fabxc** [comment]
If we do it, we have to do it consistently.
I just started working through this across all SDs.

**Comment by fabxc** [comment]
Especially because every new SD added always fails to respect the done channel...

**Comment by juliusv** [comment]
Ah ok, even better than. Closing this one here and heading to bed :)

**Pull request closed without merging**
