### PR TITLE
bugfix: pass error up if WALWathcer.segments() return err

### PR DESCRIPTION
**Pull request by YaoZengzeng**
Signed-off-by: YaoZengzeng <yaozengzeng@zju.edu.cn>

### CODE REVIEW

**Comment by tomwilkie** [comment]
ping @cstyan

**Comment by cstyan** [comment]
@YaoZengzeng did you run into an actual bug that was caused by this error not being bubbled up? If so, can you add a test?

Otherwise lgtm.

**Comment by YaoZengzeng** [comment]
@cstyan 
I have not encountered it in practice actually.

But in theory, if the segments are not sequential, the segments() would return error and we should bubble up the error ASAP, instead of replaying the WAL until encounter the missed segments.

In addition, the functions with similar function in TSDB bubbles up the error when list segments failed.
https://github.com/prometheus/tsdb/blob/master/wal/wal.go#L634

So it's reasonable to bubble up the error here :)

**Comment by cstyan** [comment]
Yes, the error should be bubbled up. I was just wondering if you'd come across an actual bug.

> But in theory, if the segments are not sequential, the segments() would return error and we should bubble up the error ASAP, instead of replaying the WAL until encounter the missed segments.

In this particular case Prometheus will exit with an error on startup before the WAL watcher code even starts :)

**Comment by YaoZengzeng** [comment]
@cstyan 
I just read through the WAL and TSDB related code to try to figure out why memory surge when WAL watcher and remote write are enabled in Prometheus v2.8.0

And find this bug by accident, haha...

**Comment by cstyan** [comment]
2.8 included a rewrite of remote write that will use more memory in the happy path than previous versions, but in failure cases it should use less memory than before, and not lose samples or OOM your Prometheus. 

There have been numerous small improvements since then though, if you're having issues with memory usage when using remote write try 2.10/2.11 and then open an issue (and ping me!) if you're still seeing something problematic.

**Comment by YaoZengzeng** [comment]
@cstyan 
Yes , thanks!

Also, I'd to contribute if there are issues to be fixed :joy:

**Comment by tomwilkie** [comment]
LGTM from me too.

**Pull request merged**
