### PR TITLE
Add an example.rules file.

### PR DESCRIPTION
**Pull request by SuperQ**
* Add example alerting rule for persistence problems.
* Update `.gitignore` to allow for the example rules file.

### CODE REVIEW

**Comment by beorn7** [comment]
I'm not sure if it is helpful to add such a relatively complex example without any further context. This would make more sense if embedded in some general lessons about meta-monitoring. (Somebody was working on getting some examples inspired by SonudCloud into shape, perhaps @juliusv ?)

Other concerns:
- If we really want to put example rules files in the repo, then perhaps in the https://github.com/prometheus/prometheus/tree/master/documentation/examples directory?
- This particular alert is about a problem that will go away with Prometheus 2. Perhaps something with a longer expected lifetime would be a better showcase?

**Comment by juliusv** [comment]
If we do this (no strong opinion), then indeed putting it into `documentation/examples` alongside the config file in there seems better. And then also make the example config file load this rule file?

And yes, it should be a much simpler alert (and one that carries over well to Prom 2), IMO. Possibly not even metamonitoring-specific, but just an instance-level `up`-ness alert or something?

**Comment by SuperQ** [comment]
Moved file to requested location.

**Comment by beorn7** [comment]
Thanks for moving the file. However, that leaves us with the other two concerns, namely that this kind of alert doesn't make sense with Prom2, and that we should start with something simpler as an example.

To be clear: It would be great to have a useful set of examples, with some explanations as comments, here in the repo. However, I think it takes some time to make it helpful rather than confusing. (I'm currently working on a similar effort for internal purposes with our intern, and yeah, it _does_ take time to get it right.)

IMHO, starting with simply putting this particular file in place is more confusing than helpful. I'm happy to be convinced otherwise, but Julius seems to see the exact same concerns.

**Comment by SuperQ** [comment]
The alert, in the current format isn't compatible with Prom2 anyway, so we can simply delete it when we merge 2.0 into master.

I understand wanting to start with simpler things, but I want to start rather than stall endlessly on getting examples going.  We've said we wanted to start adding examples for atleast a year now, I would rather just check something in than keep ignoring it.

If you would like, we could add some comments about the meaning of the alert and how it works.

**Comment by juliusv** [comment]
Ok, but how about just the simplest possible thing then, like:

```
ALERT InstanceDown
  IF up == 0
  FOR 5m
  LABELS = {
    severity = "page"
  }
  ANNOTATIONS {
    title = "Instance {{$labels.instance}} of job {{$labels.job}} is unreachable",
    description = "{{$labels.job}} at {{$labels.instance}} could not be scraped for over 5 minutes."
  }
```

...and then also load it from the example `prometheus.yml`.

**Comment by beorn7** [comment]
Comments would be good, of course.

As said, I believe checking the file in as is is counter-productive. Comments will help, but why not use the time to add simpler examples instead? This discussion is also costing time that could be invested in more productive ways.

I wouldn't oppose merging, even in this state, if there's another positive vote on it.

**Comment by grobie** [comment]
Prometheus 2.0 has been released, no point in adding examples for the old storage.

**Pull request closed without merging**
