### PR TITLE
web/ui: Display graph hover date in ISO format

### PR DESCRIPTION
**Pull request by nicholascapo**
Signed-off-by: Nicholas Capo <nicholas.capo@gmail.com>

### CODE REVIEW

**Comment by nicholascapo** [comment]
Most things I need to compare with the metric graphs are in ISO format, this makes it easier.

**Comment by codesome** [comment]
@juliusv can you take a look? Also I think we need updating in many other places where we are displaying the graph/query results (like the React UI).

**Comment by nicholascapo** [comment]
By the way, the new React UI already does this.
React_Date_Format

**Comment by nicholascapo** [comment]
Closing since the release of v2.23.0 promotes the new React UI which uses ISO date format.

**Pull request closed without merging**
